### ISSUE TITLE
Hide description, show author

### ISSUE THREAD

**Issue by jasonmader** [Ranchero-Software/NetNewsWire#1001]
On a feed where the `<description>` text is the same as the `<title>` it would be nice to not show the duplicate text. And in cases where the `<author>` exists, it would be nice to show the author. Maybe as per-feed configurable options?

```
<item>
 <title>Beam signing lets campus community put its mark on new building</title>
 <link>https://www2.gmu.edu/news/579211</link>
 <description>Beam signing lets campus community put its mark on new building</description>
 <author>Mariam Aburdeineh</author>
 <guid isPermaLink="false">579211</guid>
 <pubDate>August 28, 2019</pubDate>
</item>
```

**Comment by brentsimmons** [comment]
What’s the URL of the feed?

By the way — the author name should appear at the upper-left of the article pane, right below the name of the feed.

**Comment by jasonmader** [comment]
You’re right. I didn’t see it until you mentioned it though. I think I was expecting to see an author byline between the title & date.

Here's the URL,
https://content.gmu.edu/rss/news/8/all/14471

**Comment by vincode-io** [comment]
@brentsimmons Are you sure we should do something about this?  It looks to me like the feed is bugged.  The article text is always the same as the title.  It looks to me like we would be putting some code in for one weird feed.

**Comment by brentsimmons** [comment]
Agreed. Not worth working a bug in this particular feed.

If it comes up with other feeds, then we could reopen this.
