### ISSUE TITLE
Incorrect selection index on consecutive sidebar deletions

### ISSUE THREAD

**Issue by wvdk** [Ranchero-Software/NetNewsWire#1002]
Repo steps:

1. Select a feed from the side bar
2. Hit the delete key and see the correct item disappear
3. Click on another feed
4. Hit delete and see the item _below_ your selected item disappear

**Comment by brentsimmons** [comment]
Good catch!

**Comment by vincode-io** [comment]
@wvdk Which version of NetNewsWire are you running?  Which version of macOS are you on.  I'm having problems recreating the problem you are describing.

**Comment by wvdk** [comment]
@vincode-io Ah, yes, good question. Running NetNewsWire 5.0.1a, and macOS 10.15 Beta (19A546d)

Could definitely be a Catalina beta thing.

**Comment by vincode-io** [comment]
I'm running Catalina too and not seeing it.  Are you using the On My Mac account or a Feedbin account?

Could you try the latest developer version and try to recreate your problem again?  It is 5.0.1d2.  You can use undo to get your feeds back while testing.

**Comment by wvdk** [comment]
@vincode-io still seeing the issue on 5.0.1d2. Example: https://imgur.com/a/eNP3a5f

**Comment by vincode-io** [comment]
Thanks much for the gif.  It looks like the NSOutlineView is getting out of sync with the backing data.  I can't figure out how to recreate it yet though.

Does this happen every time or is there maybe something you are doing that gets the application state confused?  Can you go straight from application launch to deleting feeds and make this happen?

I'll keep chasing this.

**Comment by wvdk** [comment]
No funky app state I can think of. I can repo from a clean launch. It's always - first delete correct, second delete incorrect. Let me know if I can provide any more info. Maybe I'll try to dig into the codebase when I get a bit of free time.

**Comment by brentsimmons** [comment]
Since this isn’t easily reproducible, and we haven’t been getting other reports, I’m taking it off the 5.0.1 beta milestone. We’ll keep it open, though.

**Comment by chrisrenner** [comment]
I can reproduce on a debug build of df642c128ac47c140aaa76c8344611693df1bb5c. macOS 10.15.1

I actually stumbled on this issue after experiencing something different, but I think related. If I delete one or more top level items from the beginning of the list, then try to delete near the bottom of the list, it fails and I see the following in logs:

(this specific log is after I delete the container to have a fresh set of default feeds, re-run, delete inessential, then try to delete Michael Tsai)

```2019-12-26 15:43:20.145939-0500 NetNewsWire[9526:8485301] [General] NSOutlineView error removing child indexes <NSMutableIndexSet: 0x600000d4ec10>[number of indexes: 1 (in 1 ranges), indexes: (15)] in parent 0x60000178b200 (which has 15 children).
2019-12-26 15:43:20.148201-0500 NetNewsWire[9526:8485301] [General] (
	0   CoreFoundation                      0x00007fff2d3f2f53 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff63320835 objc_exception_throw + 48
	2   AppKit                              0x00007fff2ac09a19 -[NSOutlineView _validateParentRowEntry:reason:indexes:] + 0
	3   AppKit                              0x00007fff2ac09eb8 -[NSOutlineView _removeItemsAtIndexes:inParentRowEntry:withAnimation:] + 127
	4   AppKit                              0x00007fff2a7666b2 -[NSTableView _doUpdatedWorkWithHandler:] + 74
	5   AppKit                              0x00007fff2ac0ba04 -[NSOutlineView removeItemsAtIndexes:inParent:withAnimation:] + 238
	6   NetNewsWire                         0x0000000100066167 $s11NetNewsWire21SidebarViewControllerC11deleteNodesyySay6RSTree4NodeCGF + 2567
	7   NetNewsWire                         0x0000000100061aaa $s11NetNewsWire21SidebarViewControllerC6deleteyyyXlSgF + 330
	8   NetNewsWire                         0x0000000100061b00 $s11NetNewsWire21SidebarViewControllerC6deleteyyyXlSgFTo + 64
	9   AppKit                              0x00007fff2a7ff894 -[NSApplication(NSResponder) sendAction:to:from:] + 299
	10  RSCore                              0x00000001011906a7 $s6RSCore16KeyboardShortcutV7perform4withySo6NSViewC_tF + 743
	11  NetNewsWire                         0x00000001001c7cac $s11NetNewsWire23SidebarKeyboardDelegateC7keydown_2inSbSo7NSEventC_So6NSViewCtF + 828
	12  NetNewsWire                         0x00000001001c7d4d $s11NetNewsWire23SidebarKeyboardDelegateC7keydown_2inSbSo7NSEventC_So6NSViewCtFTo + 93
	13  NetNewsWire                         0x000000010006d960 $s11NetNewsWire18SidebarOutlineViewC7keyDown4withySo7NSEventC_tF + 272
	14  NetNewsWire                         0x000000010006da44 $s11NetNewsWire18SidebarOutlineViewC7keyDown4withySo7NSEventC_tFTo + 68
	15  AppKit                              0x00007fff2a693d9c -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 6512
	16  AppKit                              0x00007fff2a6921ed -[NSWindow(NSEventRouting) sendEvent:] + 349
	17  AppKit                              0x00007fff2a556d5f -[NSApplication(NSEvent) sendEvent:] + 2739
	18  AppKit                              0x00007fff2a545d57 -[NSApplication run] + 707
	19  AppKit                              0x00007fff2a53790d NSApplicationMain + 777
	20  NetNewsWire                         0x0000000100162dcd main + 13
	21  libdyld.dylib                       0x00007fff646832e5 start + 1
)```

**Comment by vincode-io** [comment]
I'm still not able to recreate this problem, but I did find a problem in the code that may have been the culprit.  We should have been waiting for each delete to complete asynchronously before rebuilding the tree controller.  I think that was how the tree controller was getting out of sync with the outline view.

@wvdk If you could watch for us to release the 5.0.4 alpha version and then test this again, we would really appreciate it.  It seems to be able to recreate with your rig and it would be a big help if you could verify that this bug was handled.

**Comment by wvdk** [comment]
Sure I'll keep a look out for 5.0.4 and test again
