### ISSUE TITLE
Closing the sidebar makes a toolbar button first responder

### ISSUE THREAD

**Issue by mdiep** [Ranchero-Software/NetNewsWire#1004]
**Steps**
1. Open sidebar
2. Select something in sidebar
3. Hide sidebar

**Expected**
An article in the list should have focus / be first responder.

**Actual**
The `+` button in the toolbar is the first responder.

I do have "All Access" turned on for controls in the system preferences. That might be a requirement for this.

**Comment by vincode-io** [comment]
This is fixed and will be in the upcoming 5.1 release.
