### ISSUE TITLE
Feature Request: Swipe to toggle unread status ala Mail.app [macOS]

### ISSUE THREAD

**Issue by jjatie** [Ranchero-Software/NetNewsWire#1015]
Swipe to mark as read/unread just like in Mail.app (should be same direction too for muscle memory).

**Comment by Wevah** [comment]
I have working code for this if it's decided it should be added. Currently the actions are just text; images à la Mail would be good.

**Comment by vincode-io** [comment]
I'm assigning this to 5.1 since we have working code and are going to try to get design assets for it.

**Comment by vincode-io** [comment]
This will be part of the 5.1 release.
