### ISSUE TITLE
Make direct-download version of NNW sandboxed

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#1023]
This work has to be done for the MAS version anyway.

I assume it’s easy to upgrade people who are running the non-sandboxed app.

When it comes to future power user features — scripted feeds, for instance — we’ll just have to figure out what to do. One option would be, as Daniel suggested, a NetNewsWire Pro that is not sandboxed.

**Comment by brentsimmons** [comment]
Here’s the reasoning…

I think sandboxing is security theater more than anything. That said, what matters more is what potential users think.

Our goal is getting as many people as possible using RSS. If there’s something in their way — such as not trusting a non-sandboxed app — then we’re not reaching our goal as well as we could.

I’d like to continue my mini-rebellion against sandboxing, sure, but that’s such a small thing compared to NNW’s main goal.

Plus: there’s always Rainier, which probably can’t be sandboxed. I’ll continue my rebellion there. :)

**Comment by danielpunkass** [comment]
Mac NNW has been sandboxed for a while.
