### ISSUE TITLE
Feature Request: Smart Search

### ISSUE THREAD

**Issue by tachoknight** [Ranchero-Software/NetNewsWire#1038]
I subscribe to a lot of feeds, and it would be nice to have the ability to have a feature whereby I can create a filter for the articles that come in by a word or phrase (e.g. "AAPL"), regardless of feed it appears. 

Theoretically I should be able to create multiple smart searches and have them saved on the left-side navigation bar in its own section.

**Comment by OddHouseGames** [comment]
A Search bar for the iOS app would immensely improve my use/flow of the app.

Case: you add a new RSS but accidentally pick the wrong folder, and you have 10-20 folders that it could be in.

**Comment by brentsimmons** [comment]
Duplicate of #217
