### ISSUE TITLE
Feedly: register with Feedly for client ID and secret

### ISSUE THREAD

**Issue by kielgillard** [Ranchero-Software/NetNewsWire#1040]
It is important to get people using the Feedly integration so we can start finding issues, particularly with articles, as symptoms of the way we're ingesting Feedly content.

To do this, we need to register NetNewsWire with Feedly to obtain a Client App ID and Secret so the app can make requests to their Production API.

**Comment by kielgillard** [comment]
I'm currently reaching out with Feedly. When I have the ID and secret, I will share them with @vincode-io and @brentsimmons directly. They are not to be pushed to the repo.

**Comment by brentsimmons** [comment]
@kielgillard Great job on the email to the Feedly folks!
