### ISSUE TITLE
Dragging & dropping images to Messages causes error

### ISSUE THREAD

**Issue by andyvn22** [Ranchero-Software/NetNewsWire#1049]
Dragging & dropping any image from a NetNewsWire article into Messages (to share it) results in Messages displaying the error: "The operation couldn't be completed. (NSURLErrorDomain error -1001.)"

**Comment by brentsimmons** [comment]
Verified true in 10.14.6. Need to test on Catalina.

But I’m not sure we can fix this. It’s a WKWebView, and dragging from it is entirely handled by Apple code, and I don’t think there’s a way in for us to fix this.

**Comment by brentsimmons** [comment]
I can’t find anything in WKWebView and related headers about drag and drop. This is an Apple bug, and I don’t see any way to work around it.

**Comment by andyvn22** [comment]
This bug is resolved in later versions of macOS.
