### ISSUE TITLE
Feedly: consistent content and counts between web and app client

### ISSUE THREAD

**Issue by kielgillard** [Ranchero-Software/NetNewsWire#1077]
When I compare the number of articles and unread counts in the Feedly sandbox web client with the articles and unread counts in NNW, the Feedly web client has more content.

We want to try to get this right so users can feel they trust NNW as a Feedly client, that they're not missing out on something.

Check we're asking for articles after the right date. I think Feedly asks for articles 31 days before the moment they're requested.

**Comment by brentsimmons** [comment]
Our database fetching code also imposes time limits. It’s worth checking to see if that’s the issue. If it is, we’ll have to figure out what’s the best way to deal with it.

**Comment by kielgillard** [comment]
Implemented. Please file specific issues if something doesn't work as expected. In any case, it probably shouldn't be bound to consistency since NNW has different goals or priorities to Feedly.
