### ISSUE TITLE
Design needed: Make the Inspector more discoverable

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#1081]
This is where per-feed settings live. The first one is for using Reader view. We’ll almost certainly add more per-feed settings in the future.

**Comment by vincode-io** [comment]
Maybe we could evolve the Inspector into a Get Info type of window like Finder uses for files and folders. A Get Info window would spawn for each resource request. That would make it possible to add a Get Info context menu option to the Sidebar.

**Comment by vincode-io** [comment]
In the multiplatform app we do this the same way on iOS and macOS.  We have sheet dialogs that show the intended resource (Feed, Account, Folder) to be updated.  These are shown with the Get Info context menu or (when we implement it) keyboard shortcut.

I consider this issue resolved and am going to close it out.  We can open other defect issues to refine the design later if we don't like it.
