### ISSUE TITLE
Incorrect HTML display

### ISSUE THREAD

**Issue by echolet** [Ranchero-Software/NetNewsWire#1088]
I'm getting an incorrect display of the contents of this feed:
https://www.afyi.fr/spip.php?page=backend

**Comment by brentsimmons** [comment]
How is it incorrect? It looks fine to me, but I’m not familiar with feed so I don’t know what you’re expecting.

**Comment by echolet** [comment]
Here's a screenshot of the display
<img width="544" alt="nnafyi" src="https://user-images.githubusercontent.com/633473/66224201-985a7b80-e6d5-11e9-962d-2a3e9a62e1d6.png">

**Comment by brentsimmons** [comment]
That item no longer appears in the feed. My bet is that the incorrect HTML display was due to a bug in the feed. (99% of the time that’s the case.)

But I’ll leave this open for a couple days to double-check — hopefully that item will reappear in the feed.
