### ISSUE TITLE
Mac: Connection errors when fetching latest feed

### ISSUE THREAD

**Issue by samesimilar** [Ranchero-Software/NetNewsWire#1098]
For a long time (including the previews) I've had a problem with NetNewsWire in that it doesn't fetch the latest items for many (all? randomly alternate?) feeds in my collection. The feeds begin to grow stale by days and weeks, although restarts of NNW and using the refresh option will occasionally force one or more of the feeds to finally update. 

I've been using Charles Proxy 4.2.7 to try to diagnose the issue, and I've noticed that during fetch activity I get 503 Errors for many of the feeds. I've copy/pasted a typical log below. 

URL	http://inessential.com/xml/rss.xml
Status	Failed
Failure	Connect: Connection refused (Connection refused)
Response Code	503 Error
Protocol	HTTP/1.1
TLS	-
Protocol	-
Session Resumed	-
Cipher Suite	-
ALPN	-
Client Certificates	-
Server Certificates	-
Extensions	
Method	GET
Kept Alive	No
Content-Type	text/html;charset=ISO-8859-1
Client Address	127.0.0.1:56782
Remote Address	inessential.com/64.90.45.138:80
Connection	
WebSockets	-
Timing	
Request Start Time	04/10/19 14:25:50
Request End Time	-
Response Start Time	-
Response End Time	04/10/19 14:25:51
Duration	1.08 s
DNS	1.08 s
Connect	-
TLS Handshake	-
Request	-
Response	-
Latency	-
Speed	1.17 KB/s
Request Speed	-
Response Speed	-
Size	
Request	358 bytes
Response	942 bytes
Total	1.27 KB (1,300 bytes)

REQUEST
	GET http://inessential.com/xml/rss.xml HTTP/1.1
Host	inessential.com
If-None-Match	"10870-592758160ffc0"
Proxy-Connection	keep-alive
Accept	*/*
If-Modified-Since	Fri, 13 Sep 2019 20:57:43 GMT
User-Agent	NetNewsWire (RSS Reader; https://ranchero.com/netnewswire/)
Accept-Language	en-ca
Accept-Encoding	gzip, deflate
Connection	keep-alive

**Comment by brentsimmons** [comment]
This is the first I’ve heard of this particular problem, so I figure it has something to do with your setup.

Are you using Little Snitch or some other kind of firewall software? Are you on a corporate network? What happens if you try a different computer on a different network?

**Comment by samesimilar** [comment]
No firewall, no VPN, no Little Snitch or anything like that (except
when trying to diagnose with Charles). I'm on the main wireless
network of a large public university.

When Charles is running, I swear it actually seems to help (make more
successful connections).

I'd like to get some more data for you. I haven't tried updating NNW
at home for a while, but I'll try again (on the same Macbook) and
closely monitor the results.

If I were to set this up to try on a different laptop, what
configuration files should I copy over? ~/Application
Support/NetNewsWire ?


On 10/4/19, Brent Simmons <notifications@github.com> wrote:
> This is the first I’ve heard of this particular problem, so I figure it has
> something to do with your setup.

>

> Are you using Little Snitch or some other kind of firewall software? Are you
> on a corporate network? What happens if you try a different computer on a
> different network?

>

> --

> You are receiving this because you authored the thread.

> Reply to this email directly or view it on GitHub:

> https://github.com/brentsimmons/NetNewsWire/issues/1098#issuecomment-538525837


-- 
mike.

**Comment by brentsimmons** [comment]
That folder should be enough.

You could also copy over preferences: ~/Library/Preferences/com.ranchero.NetNewsWire-Evergreen.plist

You probably don’t need it, but it can’t hurt.

**Comment by samesimilar** [comment]
I did some testing at work and at home over the weekend. My hunch (and the most likely thing I can think of that I can't rule out) is that when NNW initiates a refresh, it tries to make a bunch of connections in a short period of time and something on my work wifi network is not happy with that, and starts blocking connections after the first few are made. 

Running NNW with the same database, on the same network, but different MacBook had the same result. 

NNW seems to update fine on different networks than my main one, but it's a little hard to tell in the short term since the problem is a bit subtle (depends waiting for blogs to update).

I'm going to try running it at work for a few days with just one single feed (Daring Fireball). In my experience, this feed typically wouldn't be updated successfully even when it should have new items. If my hypothesis is correct, it will update promptly and reliably when it is the only feed in NNW.

Then maybe next I'll make a script that just goes out and tries to fetch 30-40 feeds from Terminal at a time, and see if I get 503 errors.

**Comment by brentsimmons** [comment]
Good detective work! It’s quite plausible that it’s the rate of http(s) requests triggering something in your work wifi network.

**Comment by vincode-io** [comment]
Looks like this was resolved.
