### ISSUE TITLE
detecting multiple RSS feeds

### ISSUE THREAD

**Issue by drewx0r** [Ranchero-Software/NetNewsWire#1100]
Entering a URL that has multiple rss feeds listed as link tags, NNW selects one of the two (seems like maybe the last one listed?). I have other rss programs that will pop up a list of linked RSS feeds and ask which one(s) I'd like to subscribe to.

**Comment by brentsimmons** [comment]
It has an algorithm where it tries to pick the best of the listed feeds — it’s not necessarily the last one.

But I could see providing a list. The trick is that it can’t just be a list — it should have a description and probably a preview of each feed, so that the user can make a decision. This means quite a bit of design work and UI programming.

**Comment by drewx0r** [comment]
That's a good point. Doing it right would probably take a lot of effort. The other app is an iOS app that's pretty rough around the edges, and it just puts up whatever's in the "name" field of the link tag. That's worked well enough for me on the pages I've tried, but that's probably because I'm already pretty familiar with the pages. 

The flip side is that until I ran the rough-around-the-edges program, I was under the impression that the site only offered one rss feed. And the feed it returned was a subset of posts, rather than the all posts.

**Comment by brentsimmons** [comment]
What’s the URL of the site? Ideally our algorithm would have picked up the best feed, and maybe there’s a chance here to improve it.

**Comment by drewx0r** [comment]
https://talkingpointsmemo.com/ has both a full blog rss feed and an editor's blog rss feed. NNW picks the editor's blog.

**Comment by pfefferle** [comment]
I had the same issue. I subscribed using the URL of my Blog: https://notiz.blog/ and NNW selected the `video` feed.

**Comment by finnito** [comment]
I'm the same, the less preferable feed is being detected on my website. An example page is here: https://adventurelog.nz/places/ahaura-river-and-lake-brunner-catchments-area/camp-creek-hut

The website has a master feed at `https://adventurelog.nz/feed.xml` as well as individual feeds for many pages at `https://adventurelog.nz/places/ahaura-river-and-lake-brunner-catchments-area/camp-creek-hut/feed.xml` for example.

Both are linked in the <head> element. I think that the master feed is linked first.

**Comment by brentsimmons** [comment]
Let’s use these to help tweak the algorithm

**Comment by vincode-io** [comment]
I modified the algorithm to take into consideration the order in the page that the link was found in.  The assumption here is that the first link will be more important than the second one and so on.

The scoring algorithm will now decrement the feed specifier's score by 5 for each step away from the first found link.  So the second link starts out at -5, the third at -10 and so on.

This change fixed all the examples in this issue.  This change will be available in NetNewsWire 6.0 unless we find some negative side effects of this change and have to pull it.

**Comment by vincode-io** [comment]
@brentsimmons You might want to review the scoring based on this change.  We might want to throw more weight to finding `json` in the URL.  Right now if `json` is found in the second link, we will choose it.  If it is found in the third link, we won't.
