### ISSUE TITLE
Feedly: high level review with Feedly engineer

### ISSUE THREAD

**Issue by kielgillard** [Ranchero-Software/NetNewsWire#1111]
Share a high level review of the Feedly implementation with an engineer from Feedly via email to determine if best practices are being followed and if there’s anything missed.
To be considered done:
- a Feedly engineer confirms via email (or however they want) that the client seems to follow best practices
- any overlooked or missed details are raised in separate GitHub issues.

**Comment by brentsimmons** [comment]
Good email.

**Comment by kielgillard** [comment]
While some conversation continues, this is essentially done.
