### ISSUE TITLE
Images squash (after you scroll past and then scroll back up) in a particular feed

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#1132]
Feed URL: http://feeds.feedburner.com/PhotographyBay

**Comment by brentsimmons** [comment]
Look at a Reader Photos Roundup article.

**Comment by Wevah** [comment]
I can't reproduce this; is there anything else I need to do?

**Comment by vincode-io** [comment]
I think that is what is supposed to happen when the images get fully loaded.  They all are wrapped in iframes and have some complicated JavaScript from Flickr that somehow crops the images to all be the same size.

@brentsimmons I'm going to leave this one for you to close, but I don't think there is anything for us to do here.
