### ISSUE TITLE
Supported macOS versions

### ISSUE THREAD

**Issue by schriftgestalt** [Ranchero-Software/NetNewsWire#1134]
Regarding: https://inessential.com/2019/10/14/netnewswire_os_compatibility_strategy

Don't you think that is a bit fast to drop support for Mojave so quickly (especially after all the warnings not to upgrade to Catalina, yet)? I would hope that you at least support one version back. I’m a software vendor myself and I’m supporting several version back (10.9 for the current version and 10.11 with the upcoming). The overhead of supporting the older macOS is not that bad. 

And one or two year old APIs are not “old stuff”.

**Comment by RobFog** [comment]
https://www.macrumors.com/2019/10/15/catalina-supplemental-update/ Seems like it might take a while till all major bugs in Catalina get ironed out…

**Comment by brentsimmons** [comment]
Indeed! Given that NetNewsWire 5.1 (the first Catalina-only release) probably won’t ship till January or February, it should be fine.

**Comment by schriftgestalt** [comment]
Why are you so eager to only support  the latest system? What features can’t be supported and how much time is saved?

**Comment by sheriferson** [comment]
I understand if the decision to drop Mojave in 5.1 doesn't change, but Catalina seems an extreme negative outlier in terms of OS quality compared to previous Mac OS releases, and I hope warrants an exception to accommodate people who don't upgrade as soon as January or February.

I'd paste links from Michael Tsai's blog that catalog how bad Catalina is, but I'm sure Brent and other NNW developers already read them. Catalina is really bad, and I think the set of people who choose not to upgrade any time soon does not just include those who are lazy or overly conservative, but people who know it might largely harm their ability to do work.

Just something to consider as the date for NNW 5.1 approaches – maybe poll NNW users closer to 5.1 release to see how many are on Catalina?
But as I said, I understand not wanting to start making exceptions, as the slippery slope of exceptions may never end.

**Comment by parkr** [comment]
Hey! I wanted to voice my support 10 months later after reading about NetNewsWire for Mac 5.1 dropping Mojave support and having Feedly support. I am a user of both Mojave and Feedly.

**Is there a way to measure NetNewsWire usage on each platform?** If we find that Mojave is such a small portion of the install base, then I'd accept the drop.

I certainly voice my support for the Catalina-isn't-ready-for-daily-use camp, as I have heard horror stories of data loss and every Catalina upgrade causes problems for colleagues. So I'm going to stick with Mojave for a while longer.

I would really like to see Mojave supported in NNW 5.x, and would ask that you not drop a major OS version until 6.x (if only to adhere to the generally-accepted semver practices that major changes happen in major version bumps).

Thanks for considering! If you have any further details on the rationale for enforcing Catalina-and-up, I'd love to learn more about the why so I can be better informed.
