### ISSUE TITLE
Worse than version 3!!!

### ISSUE THREAD

**Issue by arnold234** [Ranchero-Software/NetNewsWire#1143]
1. You cannot custom sort the feeds
2. The preview doesn't include the descriptive text, just the headline
3. I don;t want the 3 column layout of Feed Name / Feed Title / Preview - I want the old click on the preview to a separate full page

As ever, new version, worse features!!!!

**Comment by brentsimmons** [comment]
Too true!

**Comment by happycollision** [comment]
I think they have a good refund policy if you are unsatisfied.
