### ISSUE TITLE
Add padding to the right of unread count bubbles

### ISSUE THREAD

**Issue by danielpunkass** [Ranchero-Software/NetNewsWire#1162]
<img width="179" alt="image" src="https://user-images.githubusercontent.com/14606/67343958-c678f180-f504-11e9-8926-67258e567be6.png">

My instinct might be in conflict with @brentsimmons's previous ticket, but that doesn't have a lot of context: https://github.com/brentsimmons/NetNewsWire/issues/200

**Comment by vincode-io** [comment]
I might have been the last guy to touch this?  See issue #546.

**Comment by brentsimmons** [comment]
I saw something like this in some older versions of NetNewsWire.

How I fixed it: instead of laying out the row based on the width it thinks it is, instead I had it look out the enclosing view to get the apparent width, since it was being clipped by the table view (or scroll view).

**Comment by danielpunkass** [comment]
This issue seems to be related to having the system-wide preference to "Always" show scroll bars set. I don't normally run my Mac this way but I had set it that way to test something and that must explain why I only recently ran into this issue in NNW.

**Comment by danielpunkass** [comment]
This appears to have been addressed at some point. At least I'm not seeing it on 11.2.3 (20D91) with NNW 6.x. 

<img width="247" alt="image" src="https://user-images.githubusercontent.com/14606/115974625-07076000-a52c-11eb-8dce-fa589866382e.png">
