### ISSUE TITLE
Article content not displayed

### ISSUE THREAD

**Issue by Thomas-U** [Ranchero-Software/NetNewsWire#1179]
I had to throw out NNW for it to show the selected article again after restart. Before that I had selected different articles from different feeds, the unread mark disappeared but no content. All touches were respnded to but no article visible. I tried switching to another app and come back, nothing.
iPadPro 2018, I tried several feeds, some from the local account that came with the beta. After I had tried with half a dozen different feeds I decided that it had nothing to do with specific feeds. Btw: Reader also just got dark (the icon) but showed nada, the webkit view worked though.

**Comment by brentsimmons** [comment]
Some kind of unhandled exception, I presume. If you can provide steps to reproduce, I’ll re-open the ticket.
