### ISSUE TITLE
Feature Request: Option to open all URLs in new Safari tab

### ISSUE THREAD

**Issue by Thomas-U** [Ranchero-Software/NetNewsWire#1184]
Without Webkit in between.

In Safari I have all my bookmarks, passwords and tabs with Deepl and other tools always open and all easly synced accross all devices.

**Comment by brentsimmons** [comment]
Can you explain this in more detail? What’s the exact workflow you’d like?

**Comment by Thomas-U** [comment]
Puuh, that post is from a long time ago... ;-)

Thanks for the reminder.

I have no clue now. I'll close this topic.
