### ISSUE TITLE
Feature request: Option to choose default browser

### ISSUE THREAD

**Issue by pharwood** [Ranchero-Software/NetNewsWire#1231]
I use Safari as my system default browser, but would like NetNewsWire articles to open in Brave. Would it be possible to offer a choice for the default browser in the preferences?

**Comment by sashkab** [comment]
I'm using [Bumpr](https://getbumpr.com/) to achieve this. It's not ideal solution, but it works.

**Comment by weedegee** [comment]
I would also like to see this ER implemented. I block myself from mindlessly checking websites in Safari, but I'd like to be able to punch out of NNW articles so it'd be super helpful if it could open in Firefox by default.

**Comment by Wevah** [comment]
I’m part of the way there on an old branch if we want to do this.

**Comment by Wevah** [comment]
I'm all of the way there on a new branch if we want to do this. 😬

**Comment by cwmke** [comment]
Just want to check: the desired function for this issue is upon clicking a headline or other link, the link will open in the default iOS browser?

**Comment by vincode-io** [comment]
@cwmke This was a Mac feature.
