### ISSUE TITLE
After initial launch, spacebar doesn't navigate to next unread item

### ISSUE THREAD

**Issue by cupright** [Ranchero-Software/NetNewsWire#1262]
When I first launch NNW, I can use the keyboard to navigate to "All Unread." Great. I would then like to press spacebar to change the focus to the first unread item. That doesn't work for me; nothing happens, the focus doesn't change. After I click on the first unread article, the spacebar works as described and expected. This only happens immediately after launching NNW.

**Comment by cupright** [comment]
I should have mentioned that I am using NNW 5.0.3, with MacOS 10.14.6.

**Comment by vincode-io** [comment]
@cupright I am having trouble recreating this problem.  Could you please verify for me that I am doing it correctly?

1) Launch NNW
2) Press the down key twice (All Unread is now selected)
3) Press the spacebar (The first item in the All Unread timeline is selected)

Thanks for your help!

**Comment by cupright** [comment]
Hi, Maurice,

If I follow your steps precisely, the second one (“Press the down key twice”) results in two beeps. When I launch NNW the spacebar beeps in error until I have clicked on something in the window with my mouse. That also happens if I immediately press the down key. There seems to be no focus until I first click on something with the mouse. After that, everything is okay.

-- Craig

**Comment by vincode-io** [comment]
Is it possible that you are running a third-party task switch, launcher, or other utility that is preventing NNW from coming to the foreground when launched?

**Comment by cupright** [comment]
I’m launching it from the MacOS Dock. When I get back to my laptop later this evening, I’ll try launching it in different ways. 

-- Craig

**Comment by cupright** [comment]
I tried launching NNW directly from the Finder, and from a Spotlight search window. Same result. If you cannot see this behavior, I guess that’s good. This is an institutional laptop, and our IT department loads it up with MalwareBytes, Alertus, and probably another dozen items that I am not aware of, so maybe one of them is responsible for the focus issue. I don’t see this bug in any other applications, however.

The only other piece of information I can provide is that when I press Command-2 to navigate to my “All Unread” feed (after first launching NNW), that feed is highlighted but dim (gray on my screen). Clicking on that with the mouse makes it blue, and then the spacebar works. I have to click somewhere in the feed sidebar or on a news item before spacebar works. Clicking anywhere else on the window, such as the main bar with the icons, won’t help me.

-- Craig

**Comment by brentsimmons** [comment]
I can’t reproduce this on 10.15, but I can reproduce it on 10.14.

The problem is that I’m not sure I can build and debug the app on 10.14 anymore, so I may not be able to fix it.

**Comment by cupright** [comment]
No worries on my end. As soon as my institution’s sysadmin gives us the go ahead, I’ll be upgrading to 10.15 and the bug will disappear on my end, too :) And it was a fairly minor one anyway — I only reported it because I know you all are sticklers for creating an intuitive user environment.

-- Craig

**Comment by brentsimmons** [comment]
I’m going to see what I can do anyway. :) Fingers crossed.
