### ISSUE TITLE
Bug: individual author feeds from The Nation don't import correctly

### ISSUE THREAD

**Issue by LowTech** [Ranchero-Software/NetNewsWire#1275]
Using On My Mac, with NNW 5.0.3 on Catalina.

I tried adding (individual author) feeds from The Nation magazine, through the "+" button. There's probably something (or things) wrong with the feeds, though, because articles are out of order, and the date/time stamp on them are set to when I imported them. There's also an extremely odd site/author header above the articles (especially for Mike Konczal's). I've attached screenshots of Mike Konczal's (https://www.thenation.com/feeds/?author_id=3495) and Matt Stoller's (https://www.thenation.com/feeds/?author_id=19119) feed displays in NNW. I've also attached a screenshot from Inoreader, which, even though it's not picking up date/time correctly, at least displays the articles in the correct order, which you can see by comparing it to a screenshot from The Nation's website.

![Screen Shot 2019-11-07 at 3 31 56 PM](https://user-images.githubusercontent.com/2559116/68425594-6cb72f00-0174-11ea-8d60-ccdef6216926.png)

![Screen Shot 2019-11-07 at 3 32 20 PM](https://user-images.githubusercontent.com/2559116/68425597-6e80f280-0174-11ea-8688-45340077a6b7.png)

![Screen Shot 2019-11-07 at 3 37 13 PM](https://user-images.githubusercontent.com/2559116/68425664-8ce6ee00-0174-11ea-8ae5-be6518c6efa1.png)

![Screen Shot 2019-11-07 at 3 33 19 PM](https://user-images.githubusercontent.com/2559116/68425668-8eb0b180-0174-11ea-8282-1cb2a019fbbb.png)

**Comment by brentsimmons** [comment]
It’s a terrible feed.

1. It doesn’t include any `pubDate` elements, which is where RSS dates are specified.

2. Instead, it includes `date` elements, which is not a thing in RSS.

3. And — inside those `date` elements it uses a non-standard way to specify the date.

I would recommend reporting this as a bug to the publisher.

**Comment by brentsimmons** [comment]
It gets worse, though it’s not relevant.

It made up a `teaser` element which is also not a thing.

And inside the `author` tags it looks like this: `Mike Konczal,Mike Konczal,Mike Konczal`

**Comment by LowTech** [comment]
Yeah, figured. lol. *sigh*

I'll reach out to them! Thanks for looking through them. :)
