### ISSUE TITLE
"Mark as Read" and "Open in Browser" icon color make them hard to distinguish

### ISSUE THREAD

**Issue by Elzonor** [Ranchero-Software/NetNewsWire#1283]
My suggestion: go with a green-background for the "Mark as Read" checkbox icon and keep the blue for the "Open in Browser" safari-ish icon.
Same color criteria should be applied to the "Mark All as Read" icon.

**Comment by vincode-io** [comment]
Closing since we've moved on to the new monochrome toolbar icons.
