### ISSUE TITLE
Feature Request: Copy Plain Text Link to Article

### ISSUE THREAD

**Issue by kwgriese** [Ranchero-Software/NetNewsWire#1285]
It would be nice to be able to copy just the URL of an article. When you right-click the title you can 'Copy Link' but that copies the title as a hyperlink which doesn't always play nice with other apps like Messages.

**Comment by teroyks** [comment]
I regularly want to open the article URL in some other app than my default browser, so a keyboard shortcut to copy the URL to the Mac clipboard would be extremely helpful.
