### ISSUE TITLE
Incorrect Display of BandCamp Widget (macOS)

### ISSUE THREAD

**Issue by hyakugei** [Ranchero-Software/NetNewsWire#1290]
When displaying the bandcamp widget, the macOS version of NNW (v5.0.3, on MacOS v10.14.6) presents a (much) larger area around the actual widget. (see https://www.dropbox.com/s/40ales0wzi0wojw/Screenshot%202019-11-12%2009.01.18.png?dl=0). Here is the item in Safari (v13.0.3) -- https://www.dropbox.com/s/13rj4anvulufknm/Screenshot%202019-11-12%2009.02.45.png?dl=0 (url -- https://www.idieyoudie.com/2019/11/08/observer-mind-matter-crystal-geometry/)

The feed url: https://www.idieyoudie.com/feed/

**Comment by Wevah** [comment]
Looks like a result of the fixes for #1034.
