### ISSUE TITLE
Timeline: View menu thing to hide all read articles

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#130]

**Comment by ZevEisenberg** [comment]
Would this also hide feeds that contain no unread articles?

**Comment by cparnot** [comment]
This menu thing could be slightly different in the context of the 'All Unread' feed.

The ‘All Unread’ feed is a bit special in that it’s all about unread vs read. But of course we keep the read articles visible while in there, even though they are technically not ‘unread’ anymore.

However, at some point, one might want to “clean” the current list of articles (middle pane) to hide the read articles. The only way as of 5.0a1 seems to unselect the ‘All Unread’ item in the source list, then select it again. One simple 'Clean' menu item would do the trick. Probably in the View menu as well.

**Comment by dvincent747** [comment]
> This menu thing could be slightly different in the context of the 'All Unread' feed.
> 
> The ‘All Unread’ feed is a bit special in that it’s all about unread vs read. But of course we keep the read articles visible while in there, even though they are technically not ‘unread’ anymore.
> 
> However, at some point, one might want to “clean” the current list of articles (middle pane) to hide the read articles. The only way as of 5.0a1 seems to unselect the ‘All Unread’ item in the source list, then select it again. One simple 'Clean' menu item would do the trick. Probably in the View menu as well.

The behavior of previous versions of NNW would automatically hide read articles in the "All Unread" view on each refresh cycle. It would be nice to have this back in 5.x. I believe it's OK to leave "read" articles behind in things like the Today view, but I'm not sure if all users would be satisfied without a "Clean up unread articles automatically in smart feeds" option.

Having read articles stay around in the Today feed has been useful in past versions of NNW. My personal use case would be for "All Unread" to automatically clean up, while "Today" doesn't, since Today is supposed to show all articles from today regardless of the read status.

**Comment by timlance** [comment]
+1 for hiding read items. Currently I mark all a feed's articles read and they stay in the list when new are added upon refresh. Interestingly if I click another feed then return to the one where I just marked all read they are in fact hidden.

**Comment by lilyball** [comment]
I'd like to have a toolbar toggle that switches between "show everything" and "only show unread stuff", which would hide both read feeds and read articles within a feed.

In the "hide read stuff" mode, reading an article wouldn't immediately remove it from the article list, but if I select a different feed and then back to the current feed, that's when it would be removed.

**Comment by timothyekl** [comment]
+1 on this issue — I'd love a "clean up" or similar button that immediately hides read articles. My usual workflow is to notice that NNW has a badge, flip over to it, read a few articles — and then I'd like to hit some key combo to make those articles disappear, so I have a clean slate in NNW before I tab away again.

**Comment by vincode-io** [comment]
Should we handle this one the same way that we do on the iOS app?  We could add an option to clear the read timeline items on manual refresh.

<img width="624" alt="Screen Shot 2020-02-27 at 3 56 50 PM" src="https://user-images.githubusercontent.com/16448027/75497701-f2582800-5979-11ea-8417-2a4d3a2f40cb.png">

**Comment by cparnot** [comment]
I did not know it existed on iOS, but that's a great idea. It will work even better on Mac where the refresh is a keyboard shortcut away!

One small nitpick I noticed from the iOS implementation, and that would be relevant for the Mac, is that the read articles only disappear **after** the update is done. I think it would be better to have the articles disappear right away when you hit the menu item or the keyboard shortcut. This would really make this feature even more consistent: the reason why one would choose this option (like me!), is to have a way to quickly dismiss read articles from the view. The refresh becomes a side effect of it (and a welcomed one).

I am happy to test the different options on my local builds or even to help with any of it if you have other priorities. I want this feature (and would follow any decision regarding my comment in the previous paragraph). 👻

**Comment by vincode-io** [comment]
@cparnot based on your feedback, I have created an iOS issue. #1834. It won’t make it into the 5.0 release, but I have it tentatively scheduled for the 5.0.1 release.

**Comment by skoontastic** [comment]
I would love to see an option in the Mac app to clear out the "All Unread" list when clicking the "Mark All as Read" button.

**Comment by vincode-io** [comment]
@brentsimmons Is it ok to implement the "Manual Refresh to Clear Articles" option I mention above?  As I dogfood the 5.1 release, I find this option something that I miss from the iOS app.

**Comment by brentsimmons** [comment]
On Mac we’re going to do something a little different: we’ll have a “Hide Read Articles” command in the View menu.

The command will be selectively enabled. It would be enabled when in a folder, in All Unread, or when the unread-only filter is on.

This command will have the keyboard shortcut cmd-shift-H.

(The above all matches earlier versions of NetNewsWire.)

The idea is that you shouldn’t have to do a refresh just to clean up.

**Comment by brentsimmons** [comment]
Filed above as https://github.com/Ranchero-Software/NetNewsWire/issues/1912
