### ISSUE TITLE
Feedly: Create web feed doesn't do feed finding

### ISSUE THREAD

**Issue by vincode-io** [Ranchero-Software/NetNewsWire#1300]
Create feed should be able to accept a web page url and find the RSS feed associated with that page.  I'm not sure if Feedly provides something like this.  Maybe its search service?

If Feedly doesn't supply a service, we can always use our FeedFinder code to search for the RSS feed.

**Comment by kielgillard** [comment]
What’s the URL you used?

**Comment by vincode-io** [comment]
You can test against my blog, https://vincode.io.  I also had an issue with https://quickbirdstudios.com/blog.  Pretty much every time I've tried it, the create feed fails unless you give it the RSS feed URL.

**Comment by kielgillard** [comment]
@vincode-io Can you please close this issue if you find https://github.com/brentsimmons/NetNewsWire/pull/1392 addresses it?

**Comment by kielgillard** [comment]
Implemented. Please file specific issues if something doesn't work as expected.
