### ISSUE TITLE
MacOS: "Open in background in browser" not working with Brave

### ISSUE THREAD

**Issue by tubereuse** [Ranchero-Software/NetNewsWire#1302]
I have recently switched to Brave instead of Safari and have set it as my default browser. Although my NNW preference is set to "Open in background in browser", pages now open in the foreground. The preference causes the correct behaviour when Safari is the default browser.

**Comment by Wevah** [comment]
I wonder if Brave forces activation when it opens a URL.

**Comment by Wevah** [comment]
Yeah, this looks like an issue with Brave not respecting the "don't activate" part of the Apple Event.

**Comment by brentsimmons** [comment]
Unfortunately we can’t do anything about it. It’s a bug in Brave.
