### ISSUE TITLE
Feedly: Missing article

### ISSUE THREAD

**Issue by vincode-io** [Ranchero-Software/NetNewsWire#1369]
I had a situation come up where I was missing an unread article on the Mac, but it was available on iOS and the Feedly website.  I don't have much to go on except that the article was older than 30 days.

![Screen Shot 2019-11-27 at 7 07 03 PM](https://user-images.githubusercontent.com/16448027/69769205-829f8a80-1149-11ea-86d9-86421c901712.png)

Note that the unread counts are 1 off.  The article is there on my iPhone and my iPad.

![IMG_0411](https://user-images.githubusercontent.com/16448027/69769318-fb064b80-1149-11ea-82b2-a852cc44699c.png)

**Comment by kielgillard** [comment]
Did you add this feed on your Mac first and then sync on your phone/iPad?

**Comment by vincode-io** [comment]
I don't remember which device I added it to first.  Sorry.

**Comment by pdokas** [comment]
From [Slack discussion](https://netnewswire.slack.com/archives/CPNED2D7Y/p1577945163348100), I’m seeing a 38 item delta in my Feedly account between iOS NNW and feedly.com/Reeder on iOS/Reeder on macOS.

It looks like all the missing articles in NNW were posted around or after 12/30. Here’s one such article:

Feedly.com showing all available articles:
<img width="1679" alt="Feedly" src="https://user-images.githubusercontent.com/190134/71654693-fc4a0b80-2ce7-11ea-9eb4-685f82418c52.png">

Reeder in agreement:
![Reeder](https://user-images.githubusercontent.com/190134/71654694-fc4a0b80-2ce7-11ea-9c84-c7a166696b0d.jpeg)

NNW missing the latest item:
![NNW](https://user-images.githubusercontent.com/190134/71654743-34e9e500-2ce8-11ea-8140-36b2d206158b.jpeg)

**Comment by kielgillard** [comment]
Thanks @pdokas!

**Comment by kielgillard** [comment]
Fixed in the next release.
