### ISSUE TITLE
Mac: Items linger in the "All Unread" Smart Feed

### ISSUE THREAD

**Issue by frou** [Ranchero-Software/NetNewsWire#1381]
I leave NNW5 (Mac) in the "All Unread" view permanently. Say there are 3 items in there:

    • C
    • B
    • A

...and I read them all, then Hide the app.

When I click on the app to show it again (could be an hour later, could be days later), I see:

    • E
    • D
      C
      B
      A

...but I would expect to see this:

    • E
    • D

The old read items shouldn't linger in the "All Unread" view.

If they all got cleared out immediately when the app was Hidden, that would suit me personally. But perhaps the more obvious approach would be individual items aging out some period after being read.

**Comment by brentsimmons** [comment]
The way it works right now is that those items stay there until you move elsewhere — to any other feed, folder, or smart feed. Then, when you come back to All Unread, it will include only unread articles.

**Comment by frou** [comment]
That works, but would you agree that the user sitting in the All Unread smart feed permanently is a perfectly valid way to use the app?

**Comment by brentsimmons** [comment]
Oh, sure! I was just providing more information, in case it’s helpful. The bug remains open.

**Comment by llevieux** [comment]
Solved as #1912 (View > Clean Up), but hasn't yet been released.  

Workaround: switch views temporarily (cmd-1, cmd-2 in quick succession).

**Comment by blackketter** [comment]
I see that #1912 is closed with a change that's marked as 5.1b1, and I see the button and menu option for Clean Up in 5.1b1, but they are disabled.  Is this supposed to be working now?

**Comment by vincode-io** [comment]
It works.  You have to have the timeline filter enabled and articles that have been read, but aren't currently selected.

**Comment by blackketter** [comment]
Ah, I see, thanks @vincode-io.  

I was expecting it to work in the All Unread area (which is always filtered).  I should have looked around harder.

**Comment by vincode-io** [comment]
It should work for All Unread as well.  That is a bug.

**Comment by damrtom** [comment]
Hello guys, I use NNW connected to a Feedly account and each time I have read all the articles, I click on “Mark All as Read”. However, I expect they would be cleaned up at the same time, but no, so I have to do an extra click on “Clean Up Articles”. Is it the way it should work, is it related to Feedly, or could it be a feature request to “Mark All as Read and Clean Up Articles” with one mouse click?
