### ISSUE TITLE
"Smart" quotation marks not recognized

### ISSUE THREAD

**Issue by cupright** [Ranchero-Software/NetNewsWire#1393]
Back in the day, we used to call these "high-bit characters." In both the item headlines and the summaries, "smart" quotation marks are rendered as question marks. This is in version 5.0.3 of the MacOS application.

**Comment by brentsimmons** [comment]
What’s the URL of the feed?

**Comment by cupright** [comment]
Here’s the one that I noticed today:

https://www.washingtonpost.com/politics/the-mueller-report-illustrated-chapter-6-the-president-goes-after-muellers-witnesses/2019/12/02/b9c75fc6-1534-11ea-a659-7d69641c6ff7_graphic.html

It happens every now and again.

**Comment by brentsimmons** [comment]
Do you have the URL of the actual feed that you‘re subscribed-to in NetNewsWire?

**Comment by cupright** [comment]
Ah, yes. Try this:

http://feeds.washingtonpost.com/rss/politics

The errant post has a 5:15 a.m. timestamp.

**Comment by Wevah** [comment]
Looks like that article has been pushed off the end. Sounds like an encoding mismatch, though.

**Comment by brentsimmons** [comment]
Are you using Feedbin or On My Mac?

**Comment by cupright** [comment]
I believe “On My Mac” — that is what is in the “accounts” left hand column. I have know idea what those refer to, and as far as I know I never changed the default preference settings.

**Comment by cupright** [comment]
Fwiw, here’s the html entity from some of the meta content:

&#39;

As in

<meta name="twitter:title" content="The Mueller Report Illustrated, Chapter 6: The president goes after Mueller&#39;s witnesses"> <meta property="og:title" content="The Mueller Report Illustrated, Chapter 6: The president goes after Mueller&#39;s witnesses"> <meta name="description" content="Trump&#39;s public and private comments raise fears he is trying to sway the testimony of his associates."> <meta property="og:description" content="Trump&#39;s public and private comments raise fears he is trying to sway the testimony of his associates."> <meta name="twitter:description" content="Trump&#39;s public and private comments raise fears he is trying to sway the testimony of his associates.”>

**Comment by Wevah** [comment]
Huh, that's just a regular straight quote.

**Comment by cupright** [comment]
Yeah, I see now that my original report was incorrect regarding the rendering of fancy characters -- this was just a regular html entity. But for some reason that [&#39;] entity wasn't recognized. Hopefully this is just noise that you don't have to worry about, although I have seen it a few times before. If you want, I will let you know if I run across it again.

**Comment by Wevah** [comment]
Yeah, not sure what's going on there. :/

**Comment by brentsimmons** [comment]
Is this bug still happening to you?

**Comment by cupright** [comment]
No. You can close this ticket — I forgot that I even filed it.

-- Craig
