### ISSUE TITLE
Article remains open after deleting corresponding feed

### ISSUE THREAD

**Issue by strangebirds** [Ranchero-Software/NetNewsWire#1397]
If an article is open in the righthand reading pane and the feed is deleted, the article remains open. This is fairly unimportant/low priority in the grand scheme of things.

I'm not sure if there is an elegant solution to this: possibly moving to blank reading pane (like on app open) and leaving feeds deselected in the leftmost pane?

**Comment by strangebirds** [comment]
Apologies:

NNW: Version 5.0.3b2 (2617)
Mac: 10.14.6 Beta (18G59b)

**Comment by brentsimmons** [comment]
You should upgrade to the released version of 5.0.3!

But: the bug still probably exists there. Thanks for the report!

**Comment by vincode-io** [comment]
@strangebirds Did you ever update to the shipping version, 5.0.3?  On 5.0.3 it shows me the "No selection" message in the article pane when I delete a feed and a there had previously been an article from that feed in the article pane.

**Comment by strangebirds** [comment]
This does appear to be fixed in 5.0.3 (2618).

**Comment by vincode-io** [comment]
Thanks!  I just wanted to be sure before I closed this issue.
