### ISSUE TITLE
iOS and Mac: ability to have articles that can’t be marked as unread

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#1407]
Feedly, for instance, marks everything as read after 31 days, and you can’t mark something as unread.

Other systems may have similar policies.

We need a couple things:

1. Some kind of way to specify this policy.
2. Code in the UI that respects this policy. This comes into play with command validation and with the actual implementations of a command.

**Comment by vincode-io** [comment]
Previously I've specified account specific UI policies using `AccountBehaviors`.  It is an OptionSet and might be insufficient for this policy, unless we want to create separate behavior option for each number of days specified.  `AccountBehaviors.disallowMarkAsReadAfter31Days` would work, but might be too restrictive if other sync services use a different number of days.

**Comment by brentsimmons** [comment]
Different services probably will use different numbers of days. So we need some way to specify that 1) there is a mark-as-unread window, and 2) the duration.
