### ISSUE TITLE
NNW update stall

### ISSUE THREAD

**Issue by strangebirds** [Ranchero-Software/NetNewsWire#1410]
This is probably a watch and see, and not a current bug. It may be known limitations of Sparkle  or macOS as well. Feel free to close this issue if so (I mean, you can do that regardless 🙂).

Steps and Situation:
- I manually checked for update to 5.0.3 release from 5.0.3b (this wasn't prompted, btw).
- I chose the update option and the little update window with the download progress bar opened.
- I opened another app that I believe also uses Sparkle (Black Ink). I had Safari open with way too many tabs and windows (hundreds and twelve, respectively).
- The update stalled at ~500KB. Open Console and there is a lot of traffic but nothing immediately stood out. The stall was several minutes long. There were messages in the console from NNW, but I foolishly closed and they weren't warnings, just short messages.
- Cancel update, close NNW, restart, restart update. Stall at around 2MB. Suspect Sparkle.
- Cancel update, close Black Ink, close Safari. Check for update and update work as suspected.

**I see two unexpected behaviors:**
1. not prompting for update to stable from beta build
2. the update download stall

Stall could be related to another Sparkle framework app and/or Safari (connections? memory load? Computer responsiveness was normal). I don't know how you'd recreate this for testing.
---
macOS 10.14.6 (18G59b)
  Model Name:	iMac
  Model Identifier:	iMac15,1
  Processor Name:	Intel Core i7
  Processor Speed:	4 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	8 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB

**Comment by brentsimmons** [comment]
Is this bug still happening to you?

**Comment by strangebirds** [comment]
I haven’t seen evidence of this bug for a long while
