### ISSUE TITLE
Old articles appearing as new every day

### ISSUE THREAD

**Issue by Alfred-von-Campe** [Ranchero-Software/NetNewsWire#1414]
I subscribe to http://feeds.feedburner.com/comixed/CMX and every morning I get almost 50 new articles dating back to 2010.  I don't know if it's a problem with the feed, but I wasn't having that issue with NNW 4.X.

**Comment by brentsimmons** [comment]
Using On My Mac or Feedbin?

**Comment by Alfred-von-Campe** [comment]
I should have mentioned that: I'm using Version 5.0.3 (2618) on maOS 10.14.6

**Comment by brentsimmons** [comment]
Is this bug still happening to you?

**Comment by Alfred-von-Campe** [comment]
No, not in a long time,  Thanks for the follow-up.

Alfred
