### ISSUE TITLE
Share extension — so people can send to NetNewsWire

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#142]
Send Evergreen a URL and it will attempt to subscribe to the feed.

**Comment by Einkoro** [comment]
Will this work only with the feed: URL scheme or are you planning to support passing any URL regardless of protocol? Asking as I’ve encountered several readers that will open feed:example.org/rss but would choke on feed:https://example.org/rss which is how the RFC describes https feeds should be used with the scheme.

**Comment by olofhellman** [comment]
I am looking at picking this one up, as I want to learn how to do it.  Will work on master branch, not mac candidate.
