### ISSUE TITLE
iOS : Cannot import OPML file

### ISSUE THREAD

**Issue by adamprocter** [Ranchero-Software/NetNewsWire#1443]
1.Export Subscriptions from NetNewsWire macOS
2.Move or Save direct opml file to iCloud drive.
3.Open iOS NetNewsWire .
4.Select Import subscriptions - browse to the opml file from step 2 in iCloud Drive it is greyed out and not select-able also does not showing the file extension strangely.

Latest Beta NNW on both devices
Latest Release Catalina and iOS

Odd work around save opml to a server, browse and download via iOS safari to iCloud and file can be selected and imported into NNW iOS

**Comment by prk60091** [comment]
Cannot import from iCloud to NNW 1st public beta 

1.Export Subscriptions from NetNewsWire macOS
2.Move or Save direct opml file to iCloud drive.
3.Open iOS NetNewsWire .
4.Select Import subscriptions - browse to the opml file from step 2 in iCloud Drive it is greyed out and not select-able also does not showing the file extension strangely.

First Public Beta NNW on iPhone
Latest Release Catalina and iOS 13.3

I do not have an internet facing server to try work around mentioned above

**Comment by vincode-io** [comment]
Could you do me a favor and try changing the file extension to XML and see if that helps?

**Comment by Ninjoe-142** [comment]
I was having the same issue and converting to XML fixed it for me

**Comment by prk60091** [comment]
Changing the extension worked for me

**Comment by vincode-io** [comment]
There is clearly a problem here, but I am unable to recreate it.  Could someone who is having problems importing the OPML help me out?

If you could go to the Files app on your iOS device and navigate to the file, then long press to get the context menu, and select the Info option.  I would like a screenshot of what the Info of the bad file looks like.

**Comment by adamprocter** [comment]
It seems the one downloaded via iOS safari added .xml to the file for some strange reason. 

See the same file one saved from desktop and one downloaded via a link on website in iOS Safari. 

![6575F9CF-EEB0-4A86-80FB-1D5FA084B443](https://user-images.githubusercontent.com/123951/71514474-99471780-2896-11ea-9dca-a45fc5f1fd07.png)

![4C28BA58-C506-495F-ACF6-581BD1D1C30E](https://user-images.githubusercontent.com/123951/71514475-99471780-2896-11ea-9178-915218f0a456.png)

![95F5EA3D-6EDE-452B-8326-33FFD46AA64F](https://user-images.githubusercontent.com/123951/71514504-c72c5c00-2896-11ea-8a1a-d5f8c8c62c71.jpeg)

**Comment by adamprocter** [comment]
![BF1527E2-B12D-40E0-B258-36533E609873](https://user-images.githubusercontent.com/123951/71514583-3f931d00-2897-11ea-8cb6-182e87d8d035.png)
View of same files from within NNW as an FYI

**Comment by davidmancuso** [comment]
I changed the extension on my Mac exported NNW .opml file to .xml and that resolved the issue. It was no longer grayed out in IOS Files and imported fine. I couldn’t access the extension to rename it in IOS files, btw. Files doesn’t display the extension in IOS and I couldn’t find a way to access it to rename it. Had to go to my Mac. Sigh.
