### ISSUE TITLE
iOS: Error when syncing with Feedly

### ISSUE THREAD

**Issue by marcoskirsch** [Ranchero-Software/NetNewsWire#1449]
After entering my Feedly account details (iPad), NetNewsWire fetches the feeds I'm subscribed to ok – everything is populated correctly under "Feedly" in the left side pane; but never succeeds to retrieve the actual items. I get a dialog that says:

> **Error**
>
> The data couldn't be read because it is missing.
>
> ---
> Dismiss

The same exact thing happens, unsurprisingly, on iPhone.

I have version 5.0 (23).

![IMG_0103](https://user-images.githubusercontent.com/8085768/71335979-e7f95800-250a-11ea-89b2-146d69eb2d25.PNG)

**Comment by gerriet** [comment]
For me it worked in iPhone, but have the same error message on iPad. Same version.

**Comment by marcoskirsch** [comment]
Looks like it synchronized ok this morning on my iPad.

**Comment by marcoskirsch** [comment]
Now I’m getting the error again.

**Comment by kielgillard** [comment]
@marcoskirsch Thanks for creating this issue. Do you have a Mac? If so, can you please follow these instructions?

1. Connect your iOS device to your Mac.
2. On your Mac, open Console.app.
3. Using Console.app, choose the iOS device connected to your Mac in the “Devices” sectino of the side bar on the left.
4. From the menu bar, click the “Action” menu. 
5. Ensure “Include Info Messages” and “Include Debug” messages is checked.
6. In the search bar, type “Feedly”
1. On your connected iOS device, attempt to reproduce the alert.


Messages about the behaviour of the Feedly integration in NNW should be revealed in the Console as you use the Feedly account.

**Comment by kielgillard** [comment]
Would appreciate it if you could try the above too please @gerriet (when you get the error!).

**Comment by gerriet** [comment]
@kielgillard I tried the steps you suggested but got no log message from Feedly. NNW gave me mostly messages with "send gesture actions" and one "SecTrustReportTLSAnalytics". When I start the Feedly app I do get log messages from it.

**Comment by kielgillard** [comment]
@gerriet I’ve had this same feedback about the instructions and yet the very same person got back to me today with the logs. It’s a confusing process, I know. So I have to ask: can you please try a pull to refresh or killing and launching NNW in step seven?

**Comment by gerriet** [comment]
@kielgillard Pull to refresh is what I do to get the error message. I started and left NNW, I killed it and started it again, I pulled to refresh to get the error - I never got a single Feedly log message in the Console. Any ideas on what else to try? Any more information that would be helpful? I see at least half the progress bar being filled before the error pops up (when it does, the progress is full and then completely removed). It's an iPad Pro 11 inch running 13.3 on a german locale. I had Feedly installed before.

**Comment by peterwoods-io** [comment]
@kielgillard I am seeing the same issue and was able to capture the following logs:

```
debug	11:17:17.949724-0800	Starting sync 9158F2DC-328D-481C-A618-2A3359B5F642
debug	11:17:17.953584-0800	Sending article statuses...
debug	11:17:17.960577-0800	Done sending article statuses.
debug	11:17:17.960774-0800	Requesting collections.
debug	11:17:18.200014-0800	Received collections: <private>.
debug	11:17:18.200058-0800	Ensured 6 folders for 6 collections.
debug	11:17:18.200149-0800	Removed 0 folders: <private>
debug	2019-12-.20080930 11:17:18-0800	Processing 88 feeds.
debug	11:17:18.452914-0800	Unable to get stream contents: Error Domain=NSCocoaErrorDomain Code=4865 "No value associated with key CodingKeys(stringValue: "streamId", intValue: nil) ("streamId"), converted to stream_id." UserInfo={NSDebugDescription=No value associated with key CodingKeys(stringValue: "streamId", intValue: nil) ("streamId"), converted to stream_id., NSCodingPath=(
    "CodingKeys(stringValue: \"items\", intValue: nil)",
    "_JSONKey(stringValue: \"Index 1\", intValue: 1)",
    "CodingKeys(stringValue: \"origin\", intValue: nil)"
)}.
debug	11:17:18.456060-0800	<Account.FeedlyGetStreamContentsOperation: 0x104da3970> failing and cancelling other operations because The data couldn’t be read because it is missing..
debug	11:17:18.460244-0800	<Account.FeedlySyncStarredArticlesOperation: 0x104d9a8e0> failed with error: Error Domain=NSCocoaErrorDomain Code=4865 "No value associated with key CodingKeys(stringValue: "streamId", intValue: nil) ("streamId"), converted to stream_id." UserInfo={NSDebugDescription=No value associated with key CodingKeys(stringValue: "streamId", intValue: nil) ("streamId"), converted to stream_id., NSCodingPath=(
    "CodingKeys(stringValue: \"items\", intValue: nil)",
    "_JSONKey(stringValue: \"Index 1\", intValue: 1)",
    "CodingKeys(stringValue: \"origin\", intValue: nil)"
)}.
debug	11:17:18.460470-0800	Sync took 0.510 seconds
debug	11:17:18.467699-0800	Cancelling sync 9158F2DC-328D-481C-A618-2A3359B5F642
debug	11:17:18.467782-0800	Canceling sync unread statuses
debug	11:17:18.467885-0800	Canceling sync stream contents
debug	11:17:18.467926-0800	Canceling sync starred articles
```

**Comment by kielgillard** [comment]
Thanks @peterwoods-io! Good news is the PR above fixes this.

**Comment by marcoskirsch** [comment]
The new build, unfortunately, does not fix the issue for me.
<img width="1194" alt="Joining Apple Computer 40 Years Ago" src="https://user-images.githubusercontent.com/8085768/71637772-24ffd180-2c12-11ea-8fdb-b5897d160f52.png">

I verified on both iPhone and iPad.

I do have a Mac and while I’m not a Mac/iOS developer, I do have a Mac and can probably find my way around Xcode (I do software for other platforms). I just haven’t gotten the chance since I’m still out on vacation. Hope to provide a bit more hands on help after Jan 2.

**Comment by peterwoods-io** [comment]
I'm still seeing the issue as well, looks like `htmlUrl` is the culprit for me this time around.

```
debug	10:48:10.198312-0800	Starting sync BCF8B990-6433-497F-9CCE-47578A34B1D6
debug	10:48:10.198402-0800	Sending article statuses...
debug	10:48:10.199022-0800	Done sending article statuses.
debug	10:48:10.199353-0800	Requesting collections.
debug	10:48:10.396502-0800	Received collections: <private>.
debug	10:48:10.396852-0800	Ensured 6 folders for 6 collections.
debug	10:48:10.396903-0800	Removed 0 folders: <private>
debug	10:48:10.397633-0800	Processing 88 feeds.
debug	10:48:10.613187-0800	Unable to get stream contents: Error Domain=NSCocoaErrorDomain Code=4865 "No value associated with key CodingKeys(stringValue: "htmlUrl", intValue: nil) ("htmlUrl"), converted to html_url." UserInfo={NSCodingPath=(
    "CodingKeys(stringValue: \"items\", intValue: nil)",
    "_JSONKey(stringValue: \"Index 1\", intValue: 1)",
    "CodingKeys(stringValue: \"origin\", intValue: nil)"
), NSDebugDescription=No value associated with key CodingKeys(stringValue: "htmlUrl", intValue: nil) ("htmlUrl"), converted to html_url.}.
debug	10:48:10.613496-0800	<Account.FeedlyGetStreamContentsOperation: 0x101621820> failing and cancelling other operations because The data couldn’t be read because it is missing..
debug	10:48:10.613622-0800	<Account.FeedlySyncStarredArticlesOperation: 0x101615050> failed with error: Error Domain=NSCocoaErrorDomain Code=4865 "No value associated with key CodingKeys(stringValue: "htmlUrl", intValue: nil) ("htmlUrl"), converted to html_url." UserInfo={NSCodingPath=(
    "CodingKeys(stringValue: \"items\", intValue: nil)",
    "_JSONKey(stringValue: \"Index 1\", intValue: 1)",
    "CodingKeys(stringValue: \"origin\", intValue: nil)"
), NSDebugDescription=No value associated with key CodingKeys(stringValue: "htmlUrl", intValue: nil) ("htmlUrl"), converted to html_url.}.
debug	10:48:10.613686-0800	Sync took 0.419 seconds
debug	10:48:10.629395-0800	Cancelling sync BCF8B990-6433-497F-9CCE-47578A34B1D6
debug	10:48:10.629549-0800	Canceling sync unread statuses
debug	10:48:10.629601-0800	Canceling sync stream contents
debug	10:48:10.629704-0800	Canceling sync starred articles
```

**Comment by kielgillard** [comment]
Thanks @peterwoods-io. I've submitted a fix for this one, too.

**Comment by nferro** [comment]
I'm also having this issue with build 24. On the Console I can't see anything, only thing I remember that might help is that I have my iPhone set to Portuguese.

**Comment by gerriet** [comment]
For me release 26 fixed the issue on both iPhone and iPad (it was present on both in release 24). Thank you very much @kielgillard!

**Comment by nferro** [comment]
Release 26 also fixed it for me

**Comment by marcoskirsch** [comment]
Freely synchronized successfully for me with release 26. Closing. Thanks!

**Comment by kielgillard** [comment]
Thanks @marcoskirsch, @gerriet and everyone else who helped.

**Comment by michaelperrin** [comment]
Hello, I have this issue too when I try to delete a feed from my Feedly account on Mac.

Version 6.0b3 (6023)

**Comment by vincode-io** [comment]
@michaelperrin Could you please open a new ticket for this and let us know the URL of the feed you are trying to delete?

**Comment by michaelperrin** [comment]
Thank you for your message @vincode-io . I just opened #2897
