### ISSUE TITLE
Folder shows incorrect unread count

### ISSUE THREAD

**Issue by jemostrom** [Ranchero-Software/NetNewsWire#1453]
![E4EA2392-3156-47F2-B896-89D52786BDBF](https://user-images.githubusercontent.com/1286228/71346484-4f91c080-2568-11ea-8c61-b9d727c779e1.png)

As you can see here the folder show an incorrect unread number

**Comment by vincode-io** [comment]
Could you give me a little more information about your problem?  I'm having a hard time recreating it.

Did you recently add the MacHash feed?  Did the issue persist or did it eventually correct itself?  Do you typically leave the filter on all the time?  If you added the MacHash feed right before this screenshot, was the filter on during the add or did you click it after?

Any other details to get to the UI into this state would be appreciated.

**Comment by jeroenleenarts** [comment]
@vincode-io I see a similar issue.

What happens with me is as follows.

Go into a folder with unread items. Now I leave the app alone for a while so new items can appear on my (feedly) feeds. App syncs on becoming active. Now my drilled down unread count is correct. But if I go up one level in the navigation stack, the count is incorrect. I think it shows the old unread number that was correct before the feed sync.

Does the above make sense? I can try and describe this better.

**Comment by jeroenleenarts** [comment]
@jemostrom are there other client that you use that can decrease the unread count? Like another RSS feed reeder syncing to the same feedbin account?

**Comment by kielgillard** [comment]
@jemostrom Is this still an issue in the latest TestFlight build 28?

**Comment by jemostrom** [comment]
No, I haven’t noticed anything lately
