### ISSUE TITLE
Feature request: iOS option to view all articles using built-in Safari View Controller

### ISSUE THREAD

**Issue by Pixtriks** [Ranchero-Software/NetNewsWire#1471]
Currently testing the new iOS app. Everything has been working well so far.

I was wondering: maybe it's a good idea to add the option to open articles in a Safari View Controller. Not only for the "Open in Safari" button but also as a permanent option. Some sites don't play nicely when added in an RSS reader and directly opening an article with Safari View Controller would 'fix' this.

**Comment by MarcusP-P** [comment]
I find it easier to manage my web browsing in safari - tabs can be opened on other devices if I didn't finish reading something, etc.

**Comment by brentsimmons** [comment]
In 6.1 there’s a setting to control whether or not links open in Safari vs. in NetNewsWire (in a Safari view controller). I hope that does the trick for you! If not, we can re-open this ticket.
