### ISSUE TITLE
iOS: Add gesture to go to next unread

### ISSUE THREAD

**Issue by vincode-io** [Ranchero-Software/NetNewsWire#1474]
We will use a two finger swipe to the left to go to the next unread.

**Comment by arcticleo** [comment]
Curious why not simply a one finger swipe to maintain one handed operability? Would nice to avoid two handed use where possible.

**Comment by brentsimmons** [comment]
The next-unread button in the toolbar is still available for one-handed use.

**Comment by marcoskirsch** [comment]
> The next-unread button in the toolbar is still available for one-handed use.

That button is near the top, making it hard to reach especially on larger Max phones. Maybe that button should go bottom right?

**Comment by brentsimmons** [comment]
Next-unread is in the bottom — the middle one, with the circle containing the down-pointing chevron.

**Comment by paulpalinkas** [comment]
I’d also like gestural navigation, including next unread. Gestures need to be worked out in concert with each other, so I won’t suggest a specific one.

**Comment by JeremiahDJordan** [comment]
A vote for the option of single finger swipes for next/previous in the feed. Liking the app so far, but that gesture not being there makes it very hard to use for real.

**Comment by blackketter** [comment]
+1 for single finger swipe for next/previous article.  This is how my current reader, Byline, works and it's awesome.  Very natural and quick.   

Suggestion: Two-finger swipe for next/previous unread.

**Comment by danieldickison** [comment]
I might be in the minority but I appreciate the lack of single-finger swipe gestures. In other apps I find them easy to trigger accidentally, especially when they don’t have live UI feedback. The button in the toolbar works perfectly well for me.

**Comment by brentsimmons** [comment]
Closing this. The button works great!
