### ISSUE TITLE
some rss not work.  somebody help ...

### ISSUE THREAD

**Issue by 97wow** [Ranchero-Software/NetNewsWire#1477]
this rss url:
http://kc0011.net/RssFeed.asp?RssID=4&RssDataMode=1&BoardID=10
![a1](https://user-images.githubusercontent.com/11026453/71513854-185c4000-28d7-11ea-954a-171f5ab01a92.png)

add into feed
but not work
![a4](https://user-images.githubusercontent.com/11026453/71513884-388bff00-28d7-11ea-9343-80b704765a08.png)
![a3](https://user-images.githubusercontent.com/11026453/71513887-3e81e000-28d7-11ea-98d2-cc218c0bca17.png)

and I see the url was changed
![a5](https://user-images.githubusercontent.com/11026453/71513893-45105780-28d7-11ea-9944-8474579fe311.png)

somebody help ...
thanks
weichat:

**Comment by 97wow** [comment]
encoding error : input conversion failed due to input error, bytes 0x74 0x22 0x20 0x74

**Comment by brentsimmons** [comment]
Some notes:

The feed has lots of bugs: https://www.feedvalidator.org/check.cgi?url=http%3A%2F%2Fkc0011.net%2FRssFeed.asp%3FRssID%3D4%26RssDataMode%3D1%26BoardID%3D10

But Feedbin seems to parse it fine. The bug is in our parser.

If I had to guess, it’s the unusual encoding: gb2312. But that’s just a guess.

**Comment by 97wow** [comment]
thanks for your answer.

The problem is indeed with the character encoding
----------------------------------------------------------------
http://www.kc0011.net/RssFeed.asp?RssID=4&BoardID=10
This rss URL is working now。
but
http://www.kc0011.net/RssFeed.asp?RssID=4&RssDataMode=1&BoardID=10
this rss URL not working。

**Comment by 97wow** [comment]
thanks for your answer.

The problem is indeed with the character encoding
----------------------------------------------------------------
http://www.kc0011.net/RssFeed.asp?RssID=4&BoardID=10
This rss URL is working now。
but
http://www.kc0011.net/RssFeed.asp?RssID=4&RssDataMode=1&BoardID=10
this rss URL not working。

**Comment by brentsimmons** [comment]
The library we use, libxml2, does not support GB2312 encoding.

Being able to parse this feed would mean first writing code to detect the encoding, then converting the text into UTF8 encoding before parsing.

This won’t happen in time for 5.0. I’d like to get to it in 5.0.1.

**Comment by brentsimmons** [comment]
This URL now returns a 404. Closing. We can reopen later if this comes up again.
