### ISSUE TITLE
macOS app does not pull in full Tweet threads but Feedbin does

### ISSUE THREAD

**Issue by davidmytton** [Ranchero-Software/NetNewsWire#1480]
Feedbin displays all tweets in a thread but Netnewswire only shows the first Tweet.

Twitter https://twitter.com/patio11/status/1210750259736899586 : 

<img width="608" alt="image" src="https://user-images.githubusercontent.com/117833/71541114-b38efd00-294b-11ea-95f0-ae3780c61a22.png">

Feedbin:

<img width="609" alt="image" src="https://user-images.githubusercontent.com/117833/71541102-96f2c500-294b-11ea-9eb5-ab16d8aef45e.png">

NetNewsWire:

<img width="552" alt="image" src="https://user-images.githubusercontent.com/117833/71541111-a4a84a80-294b-11ea-914c-53065c0255d5.png">

NetNewsWire Version 5.0.3 (2618) on macOS 10.15.2 (19C57).

**Comment by brentsimmons** [comment]
I’m not sure what if anything we can do about this. I’m adding it to the Mac 5.1 milestone for investigation.

**Comment by vincode-io** [comment]
The Feedbin API does provide the Twitter API id's for the thread tweets.  Feedbin doesn't supply the thread tweets via its API.

From the Feedbin API docs:
> twitter_thread_ids: If the entry has a related Twitter thread, this array of ids can be used with the Twitter API to load to load the full thread. The ids are sorted in ascending chronological order.

We would need to become a Twitter client to implement this.  If we decided to go this path, it might be better to have a Twitter initiative.  Support for using Twitter URL's in the Local Account (similar to how the sync services support them) and looking up Twitter Avatars for our feed icons would also be cool to have.

**Comment by vincode-io** [comment]
Assigning to Brent to see if we can close this one or not.

**Comment by brentsimmons** [comment]
NetNewsWire is not a Twitter client.
