### ISSUE TITLE
iOS: Feeds do not refresh after initial sync

### ISSUE THREAD

**Issue by EmmEff** [Ranchero-Software/NetNewsWire#1483]
I installed on my iPad running iOS 13.3, refreshed the built-in feeds, marked all as read, and subsequent attempts to refresh these feeds do not reveal new articles, even days later.

**Comment by vincode-io** [comment]
It looks like it has been a couple days since the last article was published in the default feeds. Do you have a specific feed that you are missing articles for?  If so, could you please share it with us to help us debug the issue?

**Comment by EmmEff** [comment]
As an example, I initially installed NNN prior to December 25th and did not see the Daring Fireball posting from December 27th as new. It shows up in NNN as read, however.
