### ISSUE TITLE
iOS: Timeline context menu should have “Mark Above as Read” and “Mark Below as Read”

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#1485]
These should replace “Mark Older as Read.” And they should do what they say on the tin. (They should pay attention to the current sort order. “Above” could be mean older or newer, depending.)

**Comment by hartlco** [comment]
I announced in the Slack room that I would be happy to work on this. Just leaving a comment so I could get the ticket assigned to me, if needed.

**Comment by vincode-io** [comment]
@brentsimmons there isn't a keyboard shortcut for "Mark Above as Read".  What key should we assign that command to?

**Comment by brentsimmons** [comment]
cmd-ctrl-K
