### ISSUE TITLE
iOS: Use a new WKWebView periodically

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#1487]
We think the WKWebView gets worn out somehow and stops showing HTML. Totally weird, yes.

We could work around this by tossing the WKWebView periodically and creating a new one. I have no idea how often “periodically” should be. Every 100 views? Totally just guessing.

**Comment by vincode-io** [comment]
We now reload the web view every 10 javascript usages.  I'm working under the assumption that our javascript DOM replacement wasn't sustainable for WKWebView and that it needed to do a full reset every once in a while.

I made the change and tested against about 650 consecutive article views on the iPad and couldn't cause any loss of responsiveness or rendering errors.
