### ISSUE TITLE
RSImage.scaledForIcon should use a serial dispatch queue

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#1489]
This isn’t the site of a crash. But I’ve seen in crash logs where a whole bunch of threads are doing image work at the same time. Even though this doesn’t block the main thread, it can make the app feel slow just because too much is going on at once.

I’d rather have icon scaling happen more slowly if it means the app feels smoother.

So this method should have its own serial dispatch queue — but that queue should have as its target the global dispatch queue.

**Comment by vincode-io** [comment]
This is something I could use an education on when you get the time.  I thought something like this kind of image processing was a textbook definition of when to use a concurrent queue.  I also thought that with the lower priority and multiple cores on devices, that it couldn't slow the app down any.  I think there is a lot for me to learn about multithreading in a single user environment.
