### ISSUE TITLE
iOS: Tapping Home Page on the Feed Info view should open home page

### ISSUE THREAD

**Issue by stuartbreckenridge** [Ranchero-Software/NetNewsWire#1500]
In the feed info screen tapping the home page should open the home page. 
![D7EE2453-7006-4C68-8AC1-88943309192E](https://user-images.githubusercontent.com/7046652/71612580-58276e00-2bdc-11ea-8746-d4938b1004c3.png)

**Comment by brentsimmons** [comment]
Right now it lets you copy the URL. Maybe it needs a button the right side — or something — that opens the home page.

**Comment by brentsimmons** [comment]
(Design required, in other words.)

**Comment by vincode-io** [comment]
We use a long press to get the copy menu to pop since that is the iOS convention. We shouldn’t have a problem opening the home page on tap.

**Comment by stuartbreckenridge** [comment]
I have it working through the tableview’s didSelect method, but it’s not the most robust solution.

**Comment by vincode-io** [comment]
@stuartbreckenridge does it use our Vibrant cell code to highlight it when tapped?

**Comment by stuartbreckenridge** [comment]
@vincode-io No. It’s just `didSelect`, then if it’s detected a tap in the in the correct section it’s presenting a Safari view controller. It’s not fit for a PR.

**Comment by myurieff** [comment]
Picking this up
