### ISSUE TITLE
iOS: (Feedly) Read articles switch back to unread

### ISSUE THREAD

**Issue by vincode-io** [Ranchero-Software/NetNewsWire#1516]
We've been seeing articles that should have been marked as read either not marking as unread or switching back to unread.  This is probably how it is happening.

1) We begin to send our article statuses to the sync service by selecting all available statuses from the sync database.
2) An article is marked as read and added to the sync database.
3) We complete sending our statuses.
4) We request article statuses from the sync service.
5) The article just marked as read in NNW is unread in the sync service, so we mark it as unread in NNW, putting us in sync with the sync service but out of sync with what we will send to the sync service and what the user is expecting.
6) Eventually the entry in the sync database gets processed and we go back into a read state for the article or the user manually marks it as read again.

To rectify this we will need to check the sync database for pending entries while processing statuses from the sync service.  If we have a pending entry we should discard the sync service status since we know that we have more recent status information than the sync service.

**Comment by vincode-io** [comment]
I added two functions to `SyncDatabase`, `selectPendingReadStatusArticleIDs` and `selectPendingStarredStatusArticleIDs` to get the article ids that we don't want to update when receiving statuses from the sync service.

**Comment by kielgillard** [comment]
Used https://github.com/Ranchero-Software/NetNewsWire/commit/c3fbf88fbb9776ed11e8a024b98440f733bfc785 for reference.

**Comment by kielgillard** [comment]
Fixed in next release.
