### ISSUE TITLE
iOS: Sharing article to OmniFocus leaves new item title blank

### ISSUE THREAD

**Issue by blackketter** [Ranchero-Software/NetNewsWire#1517]
When I use the OmniFocus share sheet widget to share an article in NNW 5.0 (24), the URL is set properly in the notes field but the title of the article is missing from the title of the new OmniFocus item.

If I share a web page from Safari (or an article from my other newsreader, Byline) the title of the current page or article is in the title field of the OmniFocus item and the URL is in the Notes field.

**Comment by vincode-io** [comment]
This has been resolved and will be in the upcoming release.

**Comment by blackketter** [comment]
Works great so far!

**Comment by blackketter** [comment]
Just noticed that NNW appears to add an extraneous newline at the end of the subject.  Should I open a separate issue?

**Comment by brentsimmons** [comment]
Yes, please do.
