### ISSUE TITLE
Feed content different for Sonatype Blog depending on whether feed is On My Mac or in Feedbin

### ISSUE THREAD

**Issue by dmittman** [Ranchero-Software/NetNewsWire#1518]
I've got a feed (http://blog.sonatype.com/rss.xml) that shows three unread articles from 2017 when the feed is stored in Feedbin, but nine unread articles from 2019 when stored On My Mac. The On My Mac version seems correct, but I'm wondering 1) what might be the cause of Feedbin showing the wrong count, and 2) if this is a Feedbin error, if there's a way of showing the problem in the NNW GUI. I'm using Version 5.0.3 (2618) on macOS 10.14.6 (18G2022). Perhaps Feedbin is blocked from accessing Sonatype to get an updated feed? If so, and there's an error available from Feedbin, that error would be good to display in NNW so I know to keep that feed On My Mac.

**Comment by brentsimmons** [comment]
This could be on the Feedbin side, but we should investigate. It sounds like it’s really about items not showing up (and not having to do with read/unread status). I think.

**Comment by vincode-io** [comment]
I think this is a Feedbin issue or at least a matter of opinion on how dead feeds should work.

The http version of the feed is dead, but the https version is still working.  We automatically go after the https version, but it looks like Feedbin still has old stuff in it's database from 2017 and uses that.

I'm not sure what if anything we should/could do about this.

**Comment by brentsimmons** [comment]
The issue is that it’s really two different feeds. Even though this isn’t ideal behavior, it’s expected.

**Comment by dmittman** [comment]
Interesting. I'm happy to follow up with Feedbin; I'll look for a feedback link unless someone has a better channel for contacting them about this kind of problem.
