### ISSUE TITLE
FreshRSS: Read articles switch back to unread

### ISSUE THREAD

**Issue by vincode-io** [Ranchero-Software/NetNewsWire#1519]
We've been seeing articles that should have been marked as read either not marking as unread or switching back to unread. This is probably how it is happening.

We begin to send our article statuses to the sync service by selecting all available statuses from the sync database.
An article is marked as read and added to the sync database.
We complete sending our statuses.
We request article statuses from the sync service.
The article just marked as read in NNW is unread in the sync service, so we mark it as unread in NNW, putting us in sync with the sync service but out of sync with what we will send to the sync service and what the user is expecting.
Eventually the entry in the sync database gets processed and we go back into a read state for the article or the user manually marks it as read again.
To rectify this we will need to check the sync database for pending entries while processing statuses from the sync service. If we have a pending entry we should discard the sync service status since we know that we have more recent status information than the sync service.

**Comment by vincode-io** [comment]
I'm removing this from the 5.1 milestone as we don't plan on shipping FreshRSS in 5.1.

**Comment by Alkarex** [comment]
Hello,
Let me know whether I can provide any sparing from FreshRSS side.

Regarding the synchronisation, here is my suggestion of synchronisation strategy, using 7 requests
https://github.com/FreshRSS/FreshRSS/issues/2566#issuecomment-541317776
For pending local changes, I can also provide a suggestion if you like.

Please ping us when there is something new 😃 https://github.com/FreshRSS/FreshRSS/issues/2916

**Comment by vincode-io** [comment]
Thanks for checking in @Alkarex.  I imagine we will be picking up the FreshRSS integration in the near future and finishing it.
