### ISSUE TITLE
iOS: Feature request - move feed to another category from list 

### ISSUE THREAD

**Issue by georgesnow** [Ranchero-Software/NetNewsWire#1523]
it would be nice to be able to move a feed previous added that is in uncategorized (or another category) to 3D (or haptic) touch to move another category. 

![image](https://user-images.githubusercontent.com/12751441/71736005-ff471800-2e1d-11ea-8418-7cccfa459ed0.png)

**Comment by vincode-io** [comment]
We do support drag and drop of Feeds between Folders. Are you unfamiliar with how to do it or do you have a specific bug to report?

**Comment by georgesnow** [comment]
on the macOS version it was intuitive. drag and drop like any other Mac app. 

Thought 1:
From the feed list on iOS my thought was. Is there an "Edit Feed List", which I could select 1 or more feeds then choose a folder to move them into.  (didn't see that)

Thought 2:
Press the feed with menu in my previous post and click an option like "Move to Folder...". So I finally tried "Get Info" but the feed itself doesn't contain the properties of the folder it exists in ie I can't say move from "Uncategorized" to "Tech"  (didn't see that either...)

I included another screenshot for reference if that helps. The red circle is the feed I want to select and move in UI space that seemed logical to me, but you can't do on iOS.

Does that help? Am I missing something obvious?

macOS (drag and drop):
![Untitled 8](https://user-images.githubusercontent.com/12751441/71747290-48f32b00-2e3d-11ea-8eca-4e93c64fe2dd.png)



 iOS (attempting to complete the same action):
![Untitled 7](https://user-images.githubusercontent.com/12751441/71747205-0d586100-2e3d-11ea-8d4d-7f423ca36d0d.png)

**Comment by vincode-io** [comment]
We do drag and drop just like any other iOS 13 app.

Press and hold the Feed that you want to drag.  Wait until the context menu appears without lifting your finger.  Pull gently away from the context menu until the Feed breaks free.  You can then drag it around the screen and drop in another Folder.

**Comment by georgesnow** [comment]
ah thank you! 

if possible, I would like my original request to be considered as a possible enhancement. The drag and drop on iOS works great for single feeds (and probably fine on iPadOS), but doing this with multiple feeds on an iPhone (if that's even possible) seems awkward 🤷‍♂️. It would be nice to be able to select (similar to Mail.app on iOS for messages) multiple feeds to be moved into a folder.

**Comment by vincode-io** [comment]
For now we don't support multiple selection on iOS.
