### ISSUE TITLE
iOS: Want a way to go from an article directly to that article's feed

### ISSUE THREAD

**Issue by blackketter** [Ranchero-Software/NetNewsWire#1530]
When reading an article from one of the Smart Feeds, say, All Unread, I would like to jump to the feed from that article.   As far as I can tell I need to navigate to the top Feeds screen and then scroll down to the feed in question.

I see that if I tap on the feed name at the top it takes me to the web view of the web site.  And tapping on the icon brings it up in an image viewer.  

Maybe one of these could be repurposed to take you to the feed or bring up a menu that has that as an option.

**Comment by brentsimmons** [comment]
In the timeline, if you tap and hold on an article, you should get a Go to Feed command. Will that do the trick for you?

**Comment by blackketter** [comment]
Thanks @brentsimmons.

I didn't discover that, but I eventually find the swipe left "More (...)" menu, which works but is an extra step. 

My intuitive expectation was that tapping on the feed name would take me to the feed, not the feed's web site.  Or at least give me a menu of feed related actions.

Thinking about it more, the consistent thing would be to treat tapping on a feed name the same wherever.  Tap to go to the feed, hold to pull up the feed menu (which includes going to the web site).
