### ISSUE TITLE
Audit logging

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#1531]
We have two types of logging: os.log and RSCore logging.

We need to go through our code and figure out if RSCore logging is still needed.

The deliverable here is a small report that answers the question: can we just switch to os.log everywhere and delete RSCore logging?

**Comment by Wevah** [comment]
My initial guess is "yes", though it might be useful to use a custom service identifier for things originating inside of RSCore.

**Comment by lorenzolewis** [comment]
I'm not sure of the context of this, but I was talking with Apple support for my own app to look at switching to the unified logging platform, and there is currently no way to extract logs in iOS programmatically. You must have the user create a sysDiagnosis file and send the (sometimes multi-gig) file. The other option is to have the user connect their iOS device to a Mac and they can then extract the logs. If there is more question around this then happy to fill in some more.

**Comment by Wevah** [comment]
Are we actually writing out the contents of the RSCore log anywhere?

**Comment by Wevah** [comment]
If we're not, then we should certainly move completely to os.log.

**Comment by vincode-io** [comment]
We only use RSCore log in the Mac app and then very little.  Almost all the common code is already using os.log.  I'm pretty sure it is safe to move the Mac app to using os.log.

**Comment by Wevah** [comment]
I see where it's used, but I don't think it ever gets persisted anywhere.

We may want to use our own defined subsystem constants with os.log at some point.

**Comment by Wevah** [comment]
Okay, I think it's probably safe to convert all uses of the RSCore `Log` class to use os_log or a simple wrapper around it. Going to double-check though.
