### ISSUE TITLE
iOS : background crash

### ISSUE THREAD

**Issue by georgesnow** [Ranchero-Software/NetNewsWire#1534]
Not sure if this related to other open issues. I have hd 2 crashes of NNW in the background. I haven’t be able to determine what steps to recreate it except leaving NNW for undetermined amount of time in the background running.

**Comment by brentsimmons** [comment]
I’m closing this — not because this crash has been fixed, but because we do have crash logs elsewhere with more information.

**Comment by georgesnow** [comment]
Sounds good. I did report the crash through the iOS/Apple mechanism that prompted me about the crash and said to share with developer. Just wasn’t sure if they made it to anyone🤷‍♂️

**Comment by brentsimmons** [comment]
Yup — Apple passes the crash logs on to us.
