### ISSUE TITLE
IOS: Application crash when renaming folder

### ISSUE THREAD

**Issue by mswan819** [Ranchero-Software/NetNewsWire#1535]
Version 5.0 build 24

I renamed a folder from my Feedly section and NNW crashed
- Long pressed on the folder I wanted to rename
- rename
- entered the new name
- OK > crash

Upon reopen, the folder was there with the new name

**Comment by vincode-io** [comment]
This is the crashlog for this incident.  I'm not sure could have gone wrong yet.

[crashlog.crash.zip](https://github.com/Ranchero-Software/NetNewsWire/files/4038145/crashlog.crash.zip)

**Comment by vincode-io** [comment]
This is fixed and is coming in an update soon.
