### ISSUE TITLE
iOS: Rearranging feed items with Drag & Drop causes a crash

### ISSUE THREAD

**Issue by myurieff** [Ranchero-Software/NetNewsWire#1537]
Steps to reproduce: 

1. Be on the main screen
2. Tap and hold on a feed 
3. Move the item and let go 

The following crash log is generated:

```
2020-01-05 23:49:55.103580+0200 NetNewsWire[92429:12497960] *** Assertion failure in -[UITableView performBatchUpdates:completion:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore_Sim/UIKit-3900.9.3/UITableView.m:7434
2020-01-05 23:49:55.113421+0200 NetNewsWire[92429:12497960] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'UITableView must be updated via the UITableViewDiffableDataSource APIs when acting as the UITableView's dataSource: please do not call mutation APIs directly on UITableView. 
```

I'll be happy to work on this myself.
Let me know if drag & drop should be supported at all and if there are any other details I should be aware of. 

Thank you.

**Comment by vincode-io** [comment]
Drag and drop is supported. I use it all the time and this crash is new to me. 

If you can reliably recreate this problem, could you add any details to this ticket you have?  Which build of the app are you using and which version of iOS you have would help. 

Go ahead and feel free to work this issue.  Please submit any pull request against the ios-candidate branch.

**Comment by myurieff** [comment]
> Drag and drop is supported. I use it all the time and this crash is new to me.
> 
> If you can reliably recreate this problem, could you add any details to this ticket you have? Which build of the app are you using and which version of iOS you have would help.
> 
> Go ahead and feel free to work this issue. Please submit any pull request against the ios-candidate branch.

I built the latest master as of yesterday and ran it in simulator. On my personal device I use the latest TestFlight beta and it works just fine.

**Comment by vincode-io** [comment]
I'm not sure why you are seeing this crash.  I have tested in the simulator and don't have a problem.  Do you know the line of code that is causing the crash?  There shouldn't be any code in there doing direct table manipulation as is described in the crash log.  If there is any, we should remove it.

**Comment by myurieff** [comment]
Hmm.. It might be occurring only on Xcode 11.2. By making the change I did in the PR it stopped crashing. Tomorrow I can take a video. But if it’s only specific to an older version, we can move on and refer to the PR should it occur in future. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vincode-io** [comment]
Ideally, we will track down the line of code causing this problem and correct it.  Try to catch the crash in the debugger and see if it stops on a given instruction.
