### ISSUE TITLE
iOS: Article context menus should include preview

### ISSUE THREAD

**Issue by myurieff** [Ranchero-Software/NetNewsWire#1541]
In my opinion, it would be a better UX if a preview is included in the context menu for articles. Also, it's something the user would expect, given that's how the late Peek & Pop used to work. 

Here's a visual comparison: 
OLD:
![Simulator Screen Shot - iPhone 8 - 2020-01-06 at 14 53 48](https://user-images.githubusercontent.com/25137824/71819569-f57b1a00-3094-11ea-8d1e-8f2436062812.png)

PROPOSED:
![Simulator Screen Shot - iPhone 8 - 2020-01-06 at 14 51 58](https://user-images.githubusercontent.com/25137824/71819586-fad86480-3094-11ea-84e3-5184c0f1bc38.png)

Here's also the PR, if you agree:
https://github.com/Ranchero-Software/NetNewsWire/pull/1540

**Comment by brentsimmons** [comment]
It looks like this is what Mail does. That makes for a good precedent, and we should do the same.

**Comment by vincode-io** [comment]
@myurieff This was a really good idea and one we were excited to implement.  Unfortunately the previews forced the context menu to go below bottom of the screen.  We did think about limiting the size of the preview, but because of how the Article view is formatted didn't think it would work well.

Please don't be discouraged by this.  You do good work and we would like to continue to see contributions from you.  Per the [Contributing Guidelines](https://github.com/Ranchero-Software/NetNewsWire/blob/master/CONTRIBUTING.md) drop into the Slack #work channel and let us know what you would like to work on.

**Comment by vincode-io** [comment]
@myurieff I'm going to revive this issue.  I think the preview will work if you use `ContextMenuPreviewViewController` instead of `ArticleViewController`.  Would you be willing to submit a pull request with that change?

**Comment by myurieff** [comment]
> brentsimmons Today at 1:33 AM
> Agreed. We can’t obscure the context menu. 

> myurieff  14 minutes ago
> I see your point. But the menu can be brought to the viewable area by a short swipe. Also, in the previous iOS implementatin, a.k.a Peek&Pop, the context actions weren’t visible at all without doing the swipe up action. For me (at least how my brain is wired to work now), when I do the haptic touch, I expect the preview as a primary point of interest. The context menu is a secondary thing that I can bring up only if i want to do something. That’s just my 2 cents. I’ll research if I can modify the preview size, so that the context menu fits the available area 👌 


@vincode-io @brentsimmons Thank you :) I shared my thoughts in the #work channel, but if we consider the context menu the highest priority element, we should abandon the proposal and just move on. I tried it with `ContextMenuPreviewViewController` and I don't think it provides any additional value to the user, it's just styled more prominently.

Anyway, I'm really excited to start contributing in my free time and I think NNW would be the perfect side creative outlet for me. I'll hang around in #work and pickup / come up with something soon. ✌️
