### ISSUE TITLE
iOS: Items in feeds with "Always Show Reader View" that fail to load get stuck

### ISSUE THREAD

**Issue by blackketter** [Ranchero-Software/NetNewsWire#1542]
I have a feed set to "Always Show Reader View" (http://news.ycombinator.com/rss) .

A couple of items in that feed failed to load properly today. The reader icon pulsated indefinitely and Loading... was displayed.  I was able to exit the item with the "< Back" button, but no other buttons worked, including turning off reader view.  (i.e. I couldn't use the up or down arrows or any of the buttons on the bottom row).

When I did pop back, the article in question was marked as read even though no information was displayed.

If I turn off "Always Show Reader View" and view the failing item the non-reader view works properly.  If I tap on the reader button it pulsates for a second and correctly shows a reader icon with an exclamation mark in it.

Suggestion:  If an item in a feed set to  "Always Show Reader View" fails, default back to the non reader view, show the [!] failure icon and reenable all the buttons.

**Comment by blackketter** [comment]
I got a slightly different failure mode today under 5.0 (26).  The load failed but the word message "Loading..." remained.  The buttons at the bottom were enabled, but I expected to be able to tap the [!] button to flip back to the RSS feed provided data.  (I also expected the [!] button to be solid blue to indicate that we were in the reader mode.

![Image1](https://user-images.githubusercontent.com/131679/71935014-98e23280-315a-11ea-8299-3210288df24c.jpg)

**Comment by vincode-io** [comment]
We now load the feed article on extraction failure.  This fix will be in the next release.
