### ISSUE TITLE
iOS: HTML entities in titles not escaped properly

### ISSUE THREAD

**Issue by blackketter** [Ranchero-Software/NetNewsWire#1543]
Not sure if this is a duplicate bug, but the feed http://www.nytimes.com/services/xml/rss/nyt/Science.xml appears as: 

NYT \&gt; Science

instead of:

NYT > Science

on iOS.  Doesn't happen on Mac.

**Comment by vincode-io** [comment]
Which title are you seeing this happen in?  Which sync service are you using?

**Comment by blackketter** [comment]
Synced via Feedly on iOS, manually entered on Mac.

The entity is in the feed name and appears in feed listings as well as subheads for feed items.  Interestingly it does not appear at the top of the item screen.

![IMG_6094](https://user-images.githubusercontent.com/131679/71839165-67406d00-306f-11ea-853e-0eb4faa05398.png)

![IMG_6092](https://user-images.githubusercontent.com/131679/71838916-cce02980-306e-11ea-8f6a-711e7e615234.png)

![IMG_6093](https://user-images.githubusercontent.com/131679/71839177-6dcee480-306f-11ea-87d3-cec3b01d45ba.png)

**Comment by kevbrice** [comment]
@vincode-io Should this be fixed in iOS build 5.0 (29)? I’m still seeing this issue.

**Comment by vincode-io** [comment]
@kevbrice it should be. Could you let me know which account type you are using and what feed you are having a problem with?

**Comment by kevbrice** [comment]
@vincode-io Same as the original report: NYT feeds in Feedly.
![272626D3-F3DE-4BFD-B773-28CDF07C254F](https://user-images.githubusercontent.com/48140644/73105049-cb0ac880-3eac-11ea-97f3-33c8bc075d2e.jpeg)

**Comment by vincode-io** [comment]
Have you tried deleting and reading the feed in Build 29 yet?  I just tested it and it looks like it is fixed there to me, but it won’t fix previously corrupted titles.

**Comment by kevbrice** [comment]
@vincode-io Ahh, you’re right—I deleted and re-added my Feedly account, and now it appears correctly. Thanks!

**Comment by vincode-io** [comment]
Thanks for verifying for us.
