### ISSUE TITLE
Rename account "Create" button to "Add Account"

### ISSUE THREAD

**Issue by mgreiner** [Ranchero-Software/NetNewsWire#1544]
When adding a Feedbin account, the sheet's action button is titled "Create".

<img width="624" alt="Screen Shot 2020-01-06 at 3 20 59 PM" src="https://user-images.githubusercontent.com/1541293/71846986-dcc13300-3099-11ea-81e7-12061046e1cc.png">

I've never used Feedbin before and I mistakenly assumed that clicking "Create" would create an account on the service for me. Of course I got an error when I entered credentials that Feedbin didn't recognize.

I notice that the iOS app uses "Add Account" as the button title instead. I think that's a better choice. Using the same terminology on both platforms is a good idea regardless.

![IMG_ED9D94EB45C5-1](https://user-images.githubusercontent.com/1541293/71847007-ed71a900-3099-11ea-8ffa-3dfba59c06c9.jpeg)

**Comment by vincode-io** [comment]
Oops.  Looks like we forgot to close this one.
