### ISSUE TITLE
Scrolling left/right from next/previous article doesn't match user's mental model

### ISSUE THREAD

**Issue by marcoskirsch** [Ranchero-Software/NetNewsWire#1549]
In #1460:

>We've implemented left and right swiping to navigate articles. We are still testing this feature, but it will be available in a future release. (It won't be available in the upcoming release)

I'm testing this on release 26 on iOS. I think that swiping left/right for next/previous article is not the best way to go because it breaks the user's mental model of how things are spatially laid out. I will try to explain:

Because articles are shown in a list, I expect the next article to "be below" not "to the right of" the article I'm looking at. To the right of the article I would expect, if anything, the full render of the link.

When I'm looking at an article, I expect the previous article to "be above", not "to the left" of the article I'm looking at. To the left I expect the list of articles. What makes this especially tricky is that, as implemented, swiping right takes me to the previous article; but swiping right _from the edge of the screen_ takes me back to the article list, which is a system-wide gesture. The two are too similar to each other in my mind, and it's easy to do the wrong thing accidentally - bad UI smell.

In this regard, I think [Reeder](https://www.reederapp.com) got it right. The way you go to the next article is by scrolling down past the end of an article and past some threshold. This matches the "physical layout" of articles.

I understand this is related to UI design so opinion matters a lot and my muscle memory from years of using Reeder could be making me biased.

**Comment by vincode-io** [comment]
We intentionally didn’t implement it the way Reeder does. You can’t quickly scan through articles because you always have to scroll to the bottom. You also can accidentally go to the next article by just checking to see if you are at the end of an article. Personally, it is the thing I dislike most about Reeder. 

We understand that the mental model is imperfect.  We are willing to make that trade off for now.

**Comment by marcoskirsch** [comment]
I undestand the tradeoff. The explanation was very helpful, thanks.
