### ISSUE TITLE
Mac folder remember if its open or closed.

### ISSUE THREAD

**Issue by lanox** [Ranchero-Software/NetNewsWire#1560]
Hi, 

I did quick search but could not find anything, I was wondering is it possible to make the NetNewsWire remember if the folder is collapsed or not ?

Thanks
L

**Comment by Wevah** [comment]
I think we'd just have to set `autosaveExpandedItems = true` on the outline view and make sure the other requirements are met.

**Comment by lanox** [comment]
It would be nice, if that is possible, I do find it little annoying that I have to collapse folders all the time, but that is just my view. 

Thanks

**Comment by vincode-io** [comment]
This is on the product road map and is documented as #562.  Closing this issue as a duplicate.

**Comment by lanox** [comment]
🤦‍♂  I seem to be king of duplicating issues.

**Comment by vincode-io** [comment]
@lanox Better a dup than not reported at all!
