### ISSUE TITLE
iOS: long delay adding RSS feed

### ISSUE THREAD

**Issue by georgesnow** [Ranchero-Software/NetNewsWire#1561]
Issue: Adding a new feed from Share screen to NNW on iOS caused Safari lock up for 30 seconds. I was able to take screenshot in that time period. Screenshot below. 

Few notes none of the buttons were selectable in this time. While Safari was in this state I went back to Apple News.app, which was running in the background. It opened what seemed like a fresh launch. I went back to safari and it stayed in this state for another 10 seconds and I finally quit out of Safari. I went back to NNW and the feed was added successfully.

This might be an iOS memory issue, but it seems I can trigger this behavior specifically with NNW and adding a feed. 

Hardware: iPhone 7
iOS: 13.3
NNW: 5.0 (Build 26)

URL: pcworld.com
Account: Feedly while adding to specific Feed.

Screenshot: 

![image](https://user-images.githubusercontent.com/12751441/71984444-d7c5c600-31f6-11ea-8c3d-5b32e66ab0fa.png)

**Comment by brentsimmons** [comment]
This may in fact be a memory issue — but we should try to reproduce it anyway and see if there’s something we can fix.

**Comment by vincode-io** [comment]
This is actually network time spent searching for the feed. I’m going to modify the share extension so that the feed finding happens in the background after the share dialog dismisses itself.

**Comment by georgesnow** [comment]
sounds good to me

**Comment by vincode-io** [comment]
This change will be in the next release.  Thanks for the report!
