### ISSUE TITLE
Importing a Subscriptions.opml to iPhone not working

### ISSUE THREAD

**Issue by Pau1Mc** [Ranchero-Software/NetNewsWire#1598]
Importing a Subscriptions.opml to iPhone app not working for me when having generated the .opml from the iPad app.

Have set up my feeds “on my iPad” and whilst the iCloud sync feature is not ready yet was trying to manually copy my feed to my iPhone.

**Comment by vincode-io** [comment]
Thanks for the report.  We are aware of this bug and are addressing it in Issue #1443.  I'm closing this Issue since it is a duplicate.
