### ISSUE TITLE
iOS: Mark All as Read should have a confirmation that can be shut off via Settings

### ISSUE THREAD

**Issue by vincode-io** [Ranchero-Software/NetNewsWire#1603]
The setting should be called "Confirm Marking All as Read".

In the confirmation dialog, there should be a note: “You can turn this confirmation off in settings.”

Ideally there’s also an “Open Settings” button in the confirmation alert, so people can go right there and turn it off. Bonus points if it scrolls the settings screen to make this option visible.

In the alert, the button to press when you agree should read “Mark All as Read” or “Mark Below as Read” or “Mark Above as Read.” It should not say “OK” or similar.  If that button is so large that “Open Settings” won’t also fit, then that’s fine.

**Comment by brentsimmons** [comment]
Late-breaking change…

The setting should be called “Confirm Mark All as Read”
