### ISSUE TITLE
IPadOS... Article title overwritten by previous one

### ISSUE THREAD

**Issue by markmio** [Ranchero-Software/NetNewsWire#1606]
![05A6CAAC-1EC1-49FA-8555-A0E228651445](https://user-images.githubusercontent.com/12297926/72202658-14ddc280-345a-11ea-8d6b-b202a548ff85.png)

Reading in landscape with keyboard attached, using up/down arrow. Title of one article overwriting the start of next when viewed.

**Comment by vincode-io** [comment]
I think this corruption issue is related to Issue #1487.  I'm going to close this one and track the fix via the other issue.  If we find out they are unrelated, we can reopen this issue.
