### ISSUE TITLE
iOS: Newsfoot footnotes display under YouTube(?) videos

### ISSUE THREAD

**Issue by sh4338** [Ranchero-Software/NetNewsWire#1611]
![B317606F-A619-432F-9FBD-E01F24602038](https://user-images.githubusercontent.com/36467736/72213961-32884780-34ad-11ea-96ce-c4cadb15b4eb.jpeg)

This Newsfoot footnote got covered up by a video...  Pretty sure it's YouTube.

**Comment by Wevah** [comment]
Can you provide the feed URL and article name you’re seeing this on?

**Comment by sh4338** [comment]
The article is at https://tiffanywhite.blog/2020/01/11/wonder-and-delight-on-christmas/

**Comment by vincode-io** [comment]
This is fixed and is coming in an upcoming release.
