### ISSUE TITLE
iOS: add swiping to move to next/prev article when in web view

### ISSUE THREAD

**Issue by blackketter** [Ranchero-Software/NetNewsWire#1615]
I’m loving the swipe to move to the next article in a feed but it doesn’t work if you’ve tapped on the title and entered the web view.  

I did notice that I can swipe from the left edge to go back to the rss view but there’s no way afaict to move forward.

**Comment by vincode-io** [comment]
The Safari view has its own navigation logic for navigating the web. I think this would cause a lot of confusion with the Safari back and foreword buttons. 

The Safari view is a secondary way of reading an article.  It’s better that we focus our developer efforts on primarily how we expect the user to interact with articles. 

I’m going to close this issue out, but feel free to comment. It might get reopened, but honestly, this one is a long shot.

**Comment by blackketter** [comment]
Thanks, @vincode-io, I understand that logic.  

Unfortunately, my fingers keep trying to swipe to go on to the next article from the web view.  :)

If it's technically possible and not too difficult I think it would be worth testing.  

It's a funny situations here with the UI, with the regular rss view, reader view and web view with different ways of moving between them.  

I hate to ask for a preference setting on this, but there was some original pushback on the swipe gestures too.  If people really are confused by the various gesture maybe they are an opt-in power user feature.

One last note: Ideally the Safari web view would be embedded article screen, like the reader view, but my understanding is that this is a technical limitation for Safari views.  Right?
