### ISSUE TITLE
Some Feedly feeds work, some don’t

### ISSUE THREAD

**Issue by yphoenix** [Ranchero-Software/NetNewsWire#1620]
Most of the feeds from Feedly work but some (example below) only work when I add them directly to my iPad feed. If I access the feed via my Feedly account they don’t update. They update when I view them directly on Feedly.

Eg: http://blog.dreamhost.com/feed/

**Comment by kielgillard** [comment]
Thanks for reaching out @yphoenix. I could add the feed and it showed in NetNewsWire as it would directly on the Feedly web site. Can you please include some screen shots demonstrating what you mean by "they don't update"?

Please feel free to share the other feeds you find that do not update, too. Maybe I might have more luck with those.

**Comment by yphoenix** [comment]
What I mean by "don't update" is when there is a new post on the RSS feed it shows up if I have the feed in the "On my iPad" folder and doesn't show up if the feed is in a "Feedly" folder. If I check on feedly.com directly it shows up. I assume there is some sync issue between NNW and Feedly going on as NNW can obviously understand the feed.

Other feeds I have had the same problem with are ones from CraigslIst, eg:

https://sfbay.craigslist.org/search/acc?format=rss&is_telecommuting=1
https://sfbay.craigslist.org/search/sfc/acc?format=rss&is_telecommuting=1
https://sfbay.craigslist.org/search/sfc/acc?employment_type=2&format=rss
https://sfbay.craigslist.org/search/eby/acc?employment_type=2&format=rss

Adding them to the "on my iPad" section works, but then of course no sync across devices using Feedlyis lost.

**Comment by yphoenix** [comment]
![OnFeedly](https://user-images.githubusercontent.com/5900728/72302074-b82b0500-361d-11ea-83da-9948292049d0.jpeg)
![OniPad](https://user-images.githubusercontent.com/5900728/72302075-bb25f580-361d-11ea-8a84-9ad73dc9dad9.jpeg)

**Comment by yphoenix** [comment]
Actually looking at Feedly now, it looks like a Feedly bug with the Craigslist stuff. I'll report to them.

**Comment by yphoenix** [comment]
Actually the DreamHost one seems to be a Feedly issue too. Oh well. Thanks for your time. You can close this as a non-issue.

**Comment by kielgillard** [comment]
Right, so the dreamhost feed wasn't showing the same content on Feedly as it was over RSS?

**Comment by yphoenix** [comment]
Yep, sorry about that. I was sure it was before reporting the issue. Turns out FeedBin has the same issue with the DH feed and won't even accept the CraigsList ones as being valid. Thankfully NNW handles them both directly just fine.
