### ISSUE TITLE
macOS: toolbar icons in black and white following the macOS standard UI

### ISSUE THREAD

**Issue by gferreroferri** [Ranchero-Software/NetNewsWire#1624]
It would be good to have toolbar icons in black and white as other macOS integrated apps. Also the side bar could have gray scale

**Comment by Wevah** [comment]
I'm open to a (hidden?) pref for the toolbar, at least, depending on others' thoughts.

**Comment by brentsimmons** [comment]
The color is part of the spirit of the app! Lots of apps have toolbar icons with color — Pages and Numbers, for example.

**Comment by r-thomson** [comment]
@brentsimmons Is an option to choose between colored and grayscale icons something you would be open to a PR for?

**Comment by brentsimmons** [comment]
Not right now — with NNW 6.0 we’ll be making UI changes to adapt to Big Sur, and I have no idea yet what that will mean for our toolbar icons.
