### ISSUE TITLE
Sync from iOS to Mac

### ISSUE THREAD

**Issue by jsit** [Ranchero-Software/NetNewsWire#1630]
It’d be great to be able to sync your subscriptions/stars/read+unread locally between iOS and Mac without touching the cloud or needing a syncing account

**Comment by vincode-io** [comment]
We are looking at iCloud syncing. Tracking this issue in #491. Closing duplicate.

**Comment by jsit** [comment]
Sure, but I'm talking about *non*-cloud syncing, which is different.

**Comment by vincode-io** [comment]
Sorry that I misunderstood you. 

Honestly, this is probably never going to happen. The industry trend has been toward untethered device syncing for a number of years now. We’ve got our hands full just supporting current technologies. Supporting sunset technologies isn’t feasible on a project like this that is developer constrained. 

Out of curiosity, why are you opposed to iCloud as a syncing option?
