### ISSUE TITLE
iOS: last search results cannot be selected

### ISSUE THREAD

**Issue by blackketter** [Ranchero-Software/NetNewsWire#1634]
If there are more than a screenful of search results, it may be impossible to choose the last couple as they are hidden by the keyboard.  I believe the keyboard should be hidden when the user starts scrolling the list.  Screen capture attached:

[RPReplay_Final1579226261.MP4.zip](https://github.com/Ranchero-Software/NetNewsWire/files/4074853/RPReplay_Final1579226261.MP4.zip)

**Comment by vincode-io** [comment]
Thanks for the report.  This is resolved and will be in the next release.
