### ISSUE TITLE
Embedded video audio continues after NNW window is closed

### ISSUE THREAD

**Issue by ampsonic** [Ranchero-Software/NetNewsWire#1646]
When an embedded video is playing and the NetNewsWire window is closed (not closing the app, just the window) the audio continues to play in the background. My expectation as a user is that the audio would not continue to play. 

To reproduce in version 5.0.3 (2618): 

- Begin playback of an embedded video file ("About that Easy Pay Video" from http://feedpress.me/512pixels)
- Close NetNewsWire window (cmd+w)

**Comment by vincode-io** [comment]
@brentsimmons This is a macOS bug.  Did you intend to put this in the Mac 5.0.4 release?
