### ISSUE TITLE
iOS: Home Page field in feed info sheet doesn't handle nil well

### ISSUE THREAD

**Issue by Wevah** [Ranchero-Software/NetNewsWire#1658]
A feed with no home page URL set causes the home page field to render as very short:

![Simulator Screen Shot - iPhone 11 Pro - 2020-01-19 at 20 05 15](https://user-images.githubusercontent.com/130825/72694666-6c83ca00-3afb-11ea-90c3-d6a03e834076.png)

**Comment by Wevah** [comment]
Might also be for `homePageURL = ""`.

**Comment by brentsimmons** [comment]
Let’s remove the field entirely in that case.

**Comment by myurieff** [comment]
Seems like there is no _clean_ way to hide a static cell.. I'll try to make time this weekend to rewrite the tableview 👌

**Comment by vincode-io** [comment]
You can. Check out SettingsViewController to see how we hide the Full Screen Preference.

**Comment by myurieff** [comment]
> You can. Check out SettingsViewController to see how we hide the Full Screen Preference.

My concern is that I have to modify `numberOfRows`, `heightForHeader` and `titleForHeader` and still not get pleasant results. Also, I'm getting a lot of constraints warnings.

![Simulator Screen Shot - iPhone 11 - 2020-01-22 at 10 33 51](https://user-images.githubusercontent.com/25137824/72878197-3153e780-3d03-11ea-8939-e8c32f13fa81.png)

**Comment by vincode-io** [comment]
I would prefer that we keep how we do this consistent with Settings.  What do you propose as an alternate solution?

**Comment by myurieff** [comment]
I would too prefer sticking to the common solution. My concern is that we’re breaking auto-layout constraints and the end result doesn’t even look properly (too much spacing between the sections)

I’d love to do it with SwiftUI. The other approach would be a dynamic table view. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vincode-io** [comment]
We don’t want to do a full rewrite this close to our release date.

I’ve successfully hidden entire sections before without the problems you are experiencing. Did you maybe only hide the row and not the entire section?  If so, that may explain the layout problems.

**Comment by myurieff** [comment]
> We don’t want to do a full rewrite this close to our release date.
> 
> I’ve successfully hidden entire sections before without the problems you are experiencing. Did you maybe only hide the row and not the entire section? If so, that may explain the layout problems.

_Feels a little bit hacky_, but: https://github.com/Ranchero-Software/NetNewsWire/pull/1704

**Comment by vincode-io** [comment]
I apologize for not being more clear on how to do this.  You don't need to do the height hacks.

What you want to do is return one less from `numberOfSections` and adjust methods that are passed in the section index.  This also won't feel super clean, but it does work.

Check this commit where I removed section hiding from `SettingsViewController` to get a better idea of what I'm looking for.  https://github.com/Ranchero-Software/NetNewsWire/commit/e183345f98440fe321e5b0d16039e2be2a2f38e0#diff-e488c35055e2586cba3a2f34e7788052

**Comment by myurieff** [comment]
New PR: https://github.com/Ranchero-Software/NetNewsWire/pull/1776
