### ISSUE TITLE
Swiping on the parent folder, swipes the cell below

### ISSUE THREAD

**Issue by stuartbreckenridge** [Ranchero-Software/NetNewsWire#1661]
In this example video, I am physically swiping left to right on the Feedbin row, but the app is displaying the swipe on the Apple folder row. 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/7046652/72716473-343cc400-3bad-11ea-9668-c48d44be1078.gif)

**Comment by vincode-io** [comment]
This is fixed and will be in the next release.
