### ISSUE TITLE
iOS: Basic table rendering improperly.

### ISSUE THREAD

**Issue by zbennett-chem** [Ranchero-Software/NetNewsWire#1663]
A table from [this](https://marco.org/2020/01/13/macos-low-power-mode-redux) article is squeezed into the view on my iPhone 7 (see image). I’m wondering if a possible solution to tables is something like code blocks that can be scrolled side to side. Just an idea. 

![image](https://user-images.githubusercontent.com/56807139/72732172-cc5d8d80-3b5a-11ea-997b-e396663035ea.jpg)

**Comment by Wevah** [comment]
I've got a partial fix for both of these which stops hyphenation and mid-word breaking. The Dr. Drang example might still be too squished on the right.
