### ISSUE TITLE
iOS: Large emoji graphics in FiveThirtyEight feed synced via Feedly

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#1666]
Feed URL: http://fivethirtyeight.com/features/feed/

![Can You Track The Delirious Ducks](https://user-images.githubusercontent.com/1297121/72750408-a0013b80-3b71-11ea-9af5-1111d1c4f77a.png)

**Comment by vincode-io** [comment]
I as sure that we'd fixed this when we did #1263.  Looks like it got lost.  Added in now.

**Comment by Wevah** [comment]
I removed it when we stopped stripping all inline-styles; maybe that feed doesn't have them or Feedly is stripping them itself.

**Comment by Wevah** [comment]
Looks like the inline styles are in the feed; my only guess then is that Feedly is removing them.
