### ISSUE TITLE
iOS: HTML tags showing in timeline with Feedly sub

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#1670]
Reported on Twitter: https://twitter.com/saeed_taheri/status/1219348478830268418

Feed URL: http://tabnak.ir/fa/rss/allnews

Using Feedly.

![EOv-7VYWoAEIksd](https://user-images.githubusercontent.com/1297121/72768053-e6bf5780-3baa-11ea-9142-276001bf6d01.jpeg)

**Comment by kielgillard** [comment]
It's coming in the JSON from the Feedly API (full response attached):
```
{
    "id": "feed/http://www.tabnak.ir/fa/rss/allnews",
    "title": "<div style=\"direction:rtl;text-align:right\">تابناک | TABNAK</div>",
    "updated": 1579568648808,
```
This seems to be in contradiction to the [documentation for title](https://developer.feedly.com/v3/entries/):
> This string does not contain any HTML markup.

[tabnak.json.zip](https://github.com/Ranchero-Software/NetNewsWire/files/4088807/tabnak.json.zip)

**Comment by brentsimmons** [comment]
My guess: this only happens with RTL text.

Let’s add some code to strip out this specific div and /div in results from Feedly.

**Comment by kielgillard** [comment]
Since it seems the div element is appearing in places other than the title of the article, such as the title of the feed, I’ve reached out to Feedly for advice: should I process the necessary strings here, there or everywhere? Or is there some other option from Feedly I haven’t considered?

I will add an update here when I've Feedly's response to the question above.

**Comment by kielgillard** [comment]
From Feedly:
>   This is a feature. When Feedly detects that the source is written with a right-to-left language (Hebrew, Arabic, and Persian and the 3 main ones), it will wrap the feed title, the article title, and/or the article summary and content in a right-to-left <div> element. The Feedly API was written with HTML clients in mind, which require specific instructions to display text in right-to-left order. There's no flag or option to turn this off right now.
>   If NetNewsWire doesn't expect HTML in the feed title or article title, you will need to strip these out. Otherwise the HTML will appear in cleartext in the interface(?).
>   I hope this helps.

So it seems we need to get processing every user facing string in a feed and article.

**Comment by brentsimmons** [comment]
We do that with the local account already, and we can do that with Feedly articles too.

**Comment by kielgillard** [comment]
Good to know. I’ll check out how the local account does it. Thanks!
