### ISSUE TITLE
Memory Leak: String+RSCore strippingHTML

### ISSUE THREAD

**Issue by hartlco** [Ranchero-Software/NetNewsWire#1679]
While testing for memory leaks on iOS in Instruments I discovered a leak in `String+RSCore.strippingHTML(maxCharacters:)`. Not sure if this issue should be inside the RSCore repository or here

<img width="512" alt="Screenshot 2020-01-21 at 08 37 05" src="https://user-images.githubusercontent.com/1497750/72784746-c5ea1700-3c29-11ea-8fbe-3e7a0a9447f8.png">
<img width="1435" alt="Screenshot 2020-01-21 at 08 40 56" src="https://user-images.githubusercontent.com/1497750/72784747-c5ea1700-3c29-11ea-8394-2de71dbd449e.png">

I was not able to reproduce it reliable but got it a few times while a sync operation was ongoing and I was swiping through articles.

Here is a [link](https://www.dropbox.com/s/wbro49erl096d93/String.strippingHTML.zip?dl=0) to an instrument file. It's pretty big and my 16 inch MacBook struggled to open it.

**Comment by Wevah** [comment]
Maybe it’s because some of the reserved capacity is never used; it shouldn’t leak, though.

Should be safe enough to remove that line of there’s no real-world performance impact.

**Comment by Wevah** [comment]
Might be a fluke, too. Unsure!

**Comment by Wevah** [comment]
I'm going to close this; feel free to open if it becomes a bigger issue.
