### ISSUE TITLE
iOS: Wouldn't refresh after wifi failure

### ISSUE THREAD

**Issue by blackketter** [Ranchero-Software/NetNewsWire#1682]
I was unable to manually refresh (or automatically, I think) after rebooting my router and cable modem.  Cellular data was disabled for NNW.

Force closing NNW and relaunching it made it possible to refresh.

**Comment by vincode-io** [comment]
Looks like you got your network problem figured out.

**Comment by blackketter** [comment]
Sorry, I wasn’t clear.  The network was back up and I was able to use the WiFi in other apps.  Only NNW was unable to refresh.  Restarting the app made it start working again.  I’ll try to put together a set of steps to reproduce reliably.

**Comment by vincode-io** [comment]
Ok, I’ll reopen it then and we’ll take a look.

**Comment by kielgillard** [comment]
@blackketter what kind of account? I’m having this issue with Feedly.

**Comment by blackketter** [comment]
Feedly also.

**Comment by kielgillard** [comment]
When the sync operation fails, it cancels. For another sync to start, the previous sync operation must be deallocated. But it seems cancelled operations aren’t being deallocated. So Feedly accounts can’t sync again after failure without a relaunch of the app.

**Comment by brentsimmons** [comment]
That should be on me, then. I thought I had it so canceled operations were deallocated. I’ll look into it.

**Comment by brentsimmons** [comment]
@kielgillard I fixed the bug with releasing canceled operations. This should fix this bug, too — but I’ll leave it to you to verify that it’s truly fixed.

**Comment by kielgillard** [comment]
I’m my own testing I’m confident this regression is fixed for the next release — build 30.
