### ISSUE TITLE
iOS: change All Unread feed to All with filter button

### ISSUE THREAD

**Issue by okla** [Ranchero-Software/NetNewsWire#1689]
Suggestion to replace "All Unread" smart feed with "All" and add a filter button to it, just like in "Today" and "Starred" feeds. As a result more consistency and an ability to quickly find read posts that are not from today.

**Comment by vincode-io** [comment]
We can't do this one due to performance reasons.  An all articles feed would pull all the articles in the database which could be 100's of thousands.  I agree it would be more consistent, but it isn't technically feasible.
