### ISSUE TITLE
Feedly: Remove feed doesn’t always work

### ISSUE THREAD

**Issue by melgu** [Ranchero-Software/NetNewsWire#1691]
For example, when I try to remove the YouTube: LEMMiNO feed [1], I get a `Bad Request` Pop up with no further info.

[1] https://www.youtube.com/feeds/videos.xml?channel_id=UCRcgy6GzDeccI7dkbbBna3Q

Related to this: When I add the feed in the *On my phone* section, everything works and feed items are shown. The same feed in the *Feedly* section doesn’t have any items – but also not in other RSS readers, so probably a Feedly issue.

**Comment by kielgillard** [comment]
Does it work when you remove the same feed in the Feedly web app?

**Comment by melgu** [comment]
Yes, I can just unfollow in the Feedly website and the feed disappears (also in NNW).

**Comment by melgu** [comment]
Now when I try to re-add it in NNW, it tells me `The feed couldn’t be found and can’t be added`, but for some reason NNW adds it anyway.

**Comment by kielgillard** [comment]
Thanks! Much appreciated.

**Comment by kielgillard** [comment]
@melgu I'm looking into this now and I add and remove this feed without any issue. How does it work for you now?

**Comment by kielgillard** [comment]
Moreover, I tried adding less popular YouTube channels. Still works as expected.

**Comment by melgu** [comment]
I still get the same errors.

**Comment by melgu** [comment]
Many of the other YouTube channel feeds work though. Just not this one, but only in combination of NNW+Feedly. Each on their own work.

**Comment by kielgillard** [comment]
Okay, this is getting tricky. What version of iOS are you running?

**Comment by melgu** [comment]
I'm running on the latest official version: 13.3

**Comment by kielgillard** [comment]
@melgu do you have any other urls you could please share that produce the error?

**Comment by melgu** [comment]
@kielgillard Yes, e.g. the NewsNetWire feed [1] or The Happy Broadcast [2] have the same issues (also only in the NNW+Feedly combo).

[1] https://nnw.ranchero.com/feed.json
[1] https://www.thehappybroadcast.com/rss

**Comment by kielgillard** [comment]
Thanks @melgu. Will check with these URLs too.

**Comment by kielgillard** [comment]
Those feeds add as expected for me. Are you using a VPN or proxy or something?

**Comment by kielgillard** [comment]
@melgu Next TestFlight build will have some logging to help debug the failure. Do you have a Mac you can connect your iOS device to?

**Comment by melgu** [comment]
I'm not connected to a VPN or similar.
Yes, I have a Mac. Thanks for your investment!

**Comment by kielgillard** [comment]
The latest build logs why the Feedly integration fails to add a feed. Can you please following these instructions?

1. Connect your iOS device to your Mac.
1. Make sure your iOS device trusts your Mac when prompted. If it prompts you, trust this Mac and reconnect the iOS device to your Mac.
1. On your Mac, open Console.app.
1. Using Console.app, choose the iOS device connected to your Mac in the “Devices” section of the side bar on the left.
1. From the menu bar, click the “Action” menu.
1. Ensure “Include Info Messages” and “Include Debug” messages is checked.
In the search bar, type “Feedly”
1. On your connected iOS device, attempt to reproduce the alert.

Messages about the behaviour of the Feedly integration in NNW should be revealed in the Console as you use the Feedly account.

In particular, look for something along the lines of “unable to add new feed”.

**Comment by kielgillard** [comment]
@melgu sorry, forgot to mention you in the post above. Hopefully it’ll add some light to the issue. Good luck!

**Comment by melgu** [comment]
I couldn't find anything when searching for "Feedly" and when the Bad Request pop-up came up.

**Comment by melgu** [comment]
It's really hard to look for errors or hints in the total of NewsNetWire logs as the app is spamming the console with all sorts of messages.

**Comment by melgu** [comment]
I just realized that there's also no Console entry (still searching for "Feedly") when successfully deleting or adding a feed.

**Comment by melgu** [comment]
No warning or error shows up during the failed deletion when searching for NetNewsWire in the console.

**Comment by kielgillard** [comment]
You're using the latest TestFlight build?

**Comment by melgu** [comment]
I was using the latest TestFlight build available then (34). Will try again with 36.

**Comment by melgu** [comment]
Sorry for the long delay. I just tried again with the latest version in the App Store right now. It still doesn't work and there is still no error in the console (nothing really) when I search for Feedly.

**Comment by melgu** [comment]
There is also no warning or error related to this when I search for "NetNewsWire" in general.
But maybe this helps: I tried to find the debug messages related to the query.

<img width="1680" alt="Bildschirmfoto 2020-03-21 um 11 26 10" src="https://user-images.githubusercontent.com/9601403/77224520-cb4ed980-6b66-11ea-91e5-8a904f76d5d1.png">
The highlighted line is the error pop up, so the error has to be in the task before, which resulted in an error 400.

**Comment by melgu** [comment]
I did some packet snooping and caught the error 400.

The request URL is:
```
https://cloud.feedly.com/v3/collections/user%2Fa16b7792-b31f-4a40-a91c-cdd5023b31dd%2Fcategory%2FTech/feeds/https%3A%2F%2Fnnw.ranchero.com%2Ffeed.json
```

And the answer from the server is:
```
{
  "errorCode": 400,
  "errorId": "ap4int-sv2.2020033020.2729438",
  "errorMessage": "invalid feed id"
}
```

Hope, this helps.

**Comment by melgu** [comment]
Just testet again in 5.0.1 (42). Still the same error message.

**Comment by kielgillard** [comment]
Thanks for continuing to look into this. I'm going to try following the lead of Feedly web and use the endpoint they're using.

**Comment by kielgillard** [comment]
@melgu Okay, in the next TestFlight builds for 5.0.2, can you please let me know if the situation is improved? The "packet snooping" helped. Thanks so much!

**Comment by kielgillard** [comment]
@melgu following the way the team is handling other issues on GitHub, I've attempted to fix this for iOS 5.0.2. I still couldn't reproduce it. If the changes in iOS 5.0.2 don't fix this, we can re-open this issue. Thanks again for your help and patience.

**Comment by melgu** [comment]
I’m sad to bring bad news: 5.0.2 (iOS) didn’t fix the issue for me 😕

**Comment by melgu** [comment]
BUT: Turns our, reinstalling the app, helped.

Feeds that didn’t properly load before, now work after re-adding them (now that I can delete those).

So, I see this issue as resolved.
Thanks for your investment!
