### ISSUE TITLE
Search should also search author field

### ISSUE THREAD

**Issue by pdokas** [Ranchero-Software/NetNewsWire#1695]
When doing a search in NNW it looks like it searches in the item’s title and description.

I sometimes want to search by author, e.g. to find columns by an author in a newspaper’s opinion section.

I wish search would also include the author field to let this happen.

**Comment by pdokas** [comment]
🎉 I’m so excited, thank you @banaslee and @vincode-io!

**Comment by vincode-io** [comment]
Reopening while we make some minor changes to the implementation.

**Comment by vincode-io** [comment]
This was merged.

**Comment by pdokas** [comment]
@vincode-io It was merged but I don't think it works. Using current TestFlight (6.0 605):

![image](https://user-images.githubusercontent.com/190134/122317006-a19f7200-ced1-11eb-8378-70a108bf1342.png)
![image](https://user-images.githubusercontent.com/190134/122317016-a5cb8f80-ced1-11eb-83a4-558f02ac2430.png)

Searching in the Daring Fireball feed for "Gruber" yields 0 articles.

**Comment by vincode-io** [comment]
That's because it is part of the NNW 6.1 release.

**Comment by pdokas** [comment]
@vincode-io I just pulled the NNW iOS 6.1 TF build and I’m not seeing searches for displayed author names return any articles, e.g. "Gruber" brings up zero DF posts.

**Comment by vincode-io** [comment]
@pdokas I just tried it and it worked for me. You did select the "All Articles" option, right?

**Comment by vincode-io** [comment]
Another thing to keep in mind is that it won't work retroactively. It only works for new articles received after the upgrade to 6.1. Reindexing the whole database would be too CPU intensive, so we decided not to do it.

**Comment by pdokas** [comment]
Ah, got it. I was searching the backlog of articles loaded before installation. Confirmed it works with something received since! Yay 😄

And happy anniversary to this ticket!
<img width="294" alt="image" src="https://user-images.githubusercontent.com/190134/150841744-8701d53a-46f0-45a7-b61d-c9abc4bad9e3.png">
