### ISSUE TITLE
Launch image needs updating

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#1706]
This screenshot was taken during launch time.

![Screen Shot 2020-01-25 at 6 52 28 PM](https://user-images.githubusercontent.com/1297121/73129951-fc19f480-3fa3-11ea-9d82-f419f7a3fd68.png)

**Comment by vincode-io** [comment]
The launch images have been updated.  Unfortunately iOS caches these and doesn't update them when the app is updated.  You have to uninstall and reinstall the app to pick up the new launch images.  Could you please delete and reinstall the app to verify that the launch images are correct?

**Comment by vincode-io** [comment]
@brentsimmons I'm closing this one as there isn't anything further we can do about it.  Here is some more reading on the problem.  https://stackoverflow.com/questions/33002829/ios-keeping-old-launch-screen-and-app-icon-after-update#35783070
