### ISSUE TITLE
iOS: Wrong 'vibrant' tap-down state text colour for account type buttons

### ISSUE THREAD

**Issue by nostodnayr** [Ranchero-Software/NetNewsWire#1709]
1. Settings › Add Account
2. Tap on an account type

Bonus marks: Timeline Layout button, too.

**Comment by brentsimmons** [comment]
@nostodnayr I’m not seeing the wrong text color. Would you add a screenshot?

**Comment by nostodnayr** [comment]
Sorry I wasn't very clear.

![Uploading 845B1418-EA0F-4229-BEBF-91058A8BAD6F.png…]()
![3575B835-8F54-4260-BB9E-6B3BEBE40E4E](https://user-images.githubusercontent.com/2190735/73143624-c11cdb80-40df-11ea-9633-2cbe06af55b1.png)

**Comment by brentsimmons** [comment]
Got it! I was looking in the wrong place. Good catch.
