### ISSUE TITLE
Today unread count apparently zero sometimes when it actually should be > 0

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#1711]

**Comment by vincode-io** [comment]
I fixed an issue where the currently selected row might not get updated.  There isn't anything to go on in this report, so I'm not sure if that was the issue here or not.  We still want to keep our eyes open for reports of unread counts not matching.

**Comment by vincode-io** [comment]
I finally had this happen to me.  I've made a change now that hopefully fixes this once and for all.
