### ISSUE TITLE
Bottom toolbar elements not centered vertically on non-iPhone-X-like screens

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#1712]
Reported on a 6S, but probably affects other models with a home button.

![screenshot_01](https://user-images.githubusercontent.com/1297121/73130157-e0185200-3fa7-11ea-9a18-9ba2b6d7891c.jpg)

**Comment by vincode-io** [comment]
What am I not seeing here?  When I hold a straight edge up to the screen, they are all aligned vertically.  Besides, we don't do any real layout code with toolbars.  Everything is automatically placed for you by UIKit.

**Comment by brentsimmons** [comment]
I think the point was just that the items aren’t centered vertically in the space — there’s more room above than below.

But, yes, if this is UIKit layout, then whatever. It’s proper.
