### ISSUE TITLE
Underlined title persists in Article view

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#1713]
If you tap the title link to open a page, the underlining for the title persists after going to next unread.

**Comment by vincode-io** [comment]
This and other rendering issues make me wonder if we shouldn’t abandon our JavaScript loading code. WKWebView just doesn’t seem up to the task.

**Comment by brentsimmons** [comment]
What do we lose if we give up our JavaScript loading code?

**Comment by vincode-io** [comment]
The JavaScript version loads slightly quicker when we aren’t pushing a new WebViewController. This would be when hitting the prev button, next button, or next unread button.

**Comment by brentsimmons** [comment]
I’m willing to give up a little performance if it fixes bugs. I’m cool with dropping the JavaScript loading code.

**Comment by vincode-io** [comment]
I did a lot of work to change back to loading a string and it really slowed down performance.  By a lot.  I ended up with a hybrid approach.  We now reload the base page.html file and then populate the body using JavaScript.  This seems to be a good compromise between performance and corruptibility.
