### ISSUE TITLE
Fullscreen on iPhone can sometimes be sized incorrectly

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#1715]
Reported on an XS Max.

Screen recording:

https://ranchero.com/downloads/NNW-iPhone-fullscreen-zoomed-bug.MP4

Frame from the screen recording:

![Screen Shot 2020-01-25 at 10 15 31 PM](https://user-images.githubusercontent.com/1297121/73131471-3d200200-3fc0-11ea-930e-083cb06b86a5.png)

**Comment by vincode-io** [comment]
Steps to recreate:

1. Load an article
2. Zoom in on the article using the pinch gesture
3. Zoom back to normal using the pinch gesture
4. Tap the center of the titlebar to go to full screen

Somehow the zoomed version size gets restored instead of the current one.

**Comment by hartlco** [comment]
@vincode-io 
I'm really stuck with this issue. It seems like hiding the two bars really changes `UIScrollView.zoomScale` inside the webView. I was only able to reproduce it with articles that don't fill the full screen. I also noticed, the zoomIn change is less if you only hide one of the bars.

After hours I still was not able to figure out what is actually changing the `zoomScale`. It seems like auto-layout is not the issue as the same bug happens using manual view layout.

The only "fix" I was able to come up with is re-applying the zoomScale after the hiding animation is done but this leads to a very noticeable jump. I tried it out in this [branch](https://github.com/hartlco/NetNewsWire/tree/1715-fullscreen-on-iphone-sized-incorrectly).

I would love to know if someone else has ideas about this issue!

**Comment by vincode-io** [comment]
@brentsimmons I've got nothing for this one.  It is a strange edge case.  Would it be possible to unassign this one and move it out of the milestone?

**Comment by brentsimmons** [comment]
Done. We can revisit some time after shipping.

**Comment by vincode-io** [comment]
This issue was fixed when the WKWebView delegates got cleared before recycling.  This was causing all kinds of indeterminate behavior, especially regarding the UIScrollView.
