### ISSUE TITLE
xkcd alt text not opening with tap

### ISSUE THREAD

**Issue by afragen** [Ranchero-Software/NetNewsWire#1726]
This in build 31

**Comment by afragen** [comment]
This in build 31

**Comment by brentsimmons** [comment]
Would you elaborate?

**Comment by afragen** [comment]
When in the xkcd feed an image is displayed. Tapping on the image used to open the image and the alt text. It no longer seems to open the image. This in an iPhone. Also confirmed on iPad. 

It worked in build 30.

**Comment by afragen** [comment]
Feed is http://xkcd.com/rss.xml

**Comment by vincode-io** [comment]
I’ve verified that this is an issue in Build 31. Strangely it isn’t an issue in my local development build. I’ll investigate what happened in Build 31.

**Comment by vincode-io** [comment]
This is resolved and will be in Build 32, coming soon.

**Comment by thiagowfx** [comment]
I was going to file a new bug but then I found this existing one.

This issue seems to be happening again.

http://xkcd.com/rss.xml

Image alt text does not show up with tap/hold.

Newswire 6.0 (Build 605).
iOS 14.6.

Happy to provide more info.

**Comment by vincode-io** [comment]
We don't support tap and hold to view the alt text. You tap the image to zoom into it and the alt text will appear at the bottom if it exists.
