### ISSUE TITLE
iOS: cannot select past a certain point in the url on the add feed page

### ISSUE THREAD

**Issue by sh4338** [Ranchero-Software/NetNewsWire#1730]
When I try to select text past a certain point on the add feed page url field, I can't.  Best explained in a photo:

![39417EB0-6A70-460E-AC1D-FD7A8882EC3A](https://user-images.githubusercontent.com/36467736/73330293-3ccc7480-4215-11ea-81bf-f667a97f3c99.jpeg)

Cannot select text past the red arrow.

**Comment by vincode-io** [comment]
Unfortunately this looks like a bug in iOS 13's new text selection.  We're going to have to wait for Apple to fix this one.  I'm closing the issue since there isn't anything we can do about it.
