### ISSUE TITLE
iOS: Reader view message when a feed links to a YouTube video.

### ISSUE THREAD

**Issue by zbennett-chem** [Ranchero-Software/NetNewsWire#1738]
Just got an odd message in the reader view of [this](http://www.cgpgrey.com/blog?format=rss) feed. This is probably from YouTube, but I’m not sure if this is something NNW should handle or not. 

![image](https://user-images.githubusercontent.com/56807139/73387086-9c6a6480-4295-11ea-87e2-cd7959132cb0.jpg)

**Comment by vincode-io** [comment]
Like I mentioned in Slack there isn't much we can do about article extraction content right now.
