### ISSUE TITLE
iOS: Item pointing to Wikipedia does not load in Reader view

### ISSUE THREAD

**Issue by blackketter** [Ranchero-Software/NetNewsWire#1740]
An item from HackerNews (http://news.ycombinator.com/rss) that points to a wikipedia page fails to load in Reader view (icon shows exclamation point).  From the feed:

`<item><title>Hachikō</title><link>https://en.wikipedia.org/wiki/Hachikō</link><pubDate>Tue, 28 Jan 2020 12:20:25 +0000</pubDate><comments>https://news.ycombinator.com/item?id=22168670</comments><description><![CDATA[<a href="https://news.ycombinator.com/item?id=22168670">Comments</a>]]></description></item>
`

**Comment by vincode-io** [comment]
Lots of pages aren't parsable by the Mercury reader code, which is why there is the exclamation point icon.  We don't have the resources to chase them all down.  Sorry.

**Comment by blackketter** [comment]
Thanks, @vincode-io.  I didn't realize how the reader worked.  I do understand that many pages won't be able to be processed by the Mercury reader.

Out of curiosity, I installed the Mercury Reader extension in Chrome and tried to open the page in question: https://en.wikipedia.org/wiki/Hachikō and it was able to process it correctly.  If that extension uses the same code, it may be that the issue doesn't lie in the Mercury parser.

How is it possible to determine the cause of a Reader failure?

**Comment by vincode-io** [comment]
We use the Mercury code hosted at Feedbin. The version at Feedbin is most certainly different from your plugin one, so you can’t expect similar results.
