### ISSUE TITLE
iOS build 33: Images aren’t loaded

### ISSUE THREAD

**Issue by NorbertLindenberg** [Ranchero-Software/NetNewsWire#1744]
Images aren’t loaded in the <img width="23" alt="NNW button" src="https://user-images.githubusercontent.com/216206/73429957-b8035880-42f1-11ea-8631-5d03a400060d.png"> view.

To reproduce:

– Add web feed for https://lindenbergsoftware.com/all.atom (no sync service).

– Go to the “Bringing Balinese to iOS” article.

– Tap the <img width="23" alt="NNW button" src="https://user-images.githubusercontent.com/216206/73429957-b8035880-42f1-11ea-8631-5d03a400060d.png"> button.

– Scroll down and notice a number of empty rectangles such as this one:

<img alt="Bringing Balinese to iOS" src="https://user-images.githubusercontent.com/216206/73430189-4bd52480-42f2-11ea-85b5-f964f2f5d365.png">

**Comment by NorbertLindenberg** [comment]
A note on the configuration of lindenbergsoftware.com: The server will return a 403 Forbidden if an image is requested where the request doesn’t indicate the same server in the referrer field. Not sure if this plays a role here.

**Comment by Wevah** [comment]
I'm guessing the core bug here is the same as #1745.

**Comment by Wevah** [comment]
Not sure if it was the `<base>` in the `<body>`, or if `<base>` just needed to be resolved first.

**Comment by Wevah** [comment]
This also affects macOS 5.1 development.

**Comment by NorbertLindenberg** [comment]
According to the HTML spec, `base` can only be used in the `head`:
https://html.spec.whatwg.org/multipage/semantics.html#the-base-element

**Comment by Wevah** [comment]
Some renderers are (wrongly?) a bit more lax and still obey things in the body. It certainly feels better having it where it's supposed to be, though!
