### ISSUE TITLE
iOS: icon loaded from wrong location

### ISSUE THREAD

**Issue by NorbertLindenberg** [Ranchero-Software/NetNewsWire#1745]
Server logs at lindenbergsoftware.com indicate that NetNewsWire/33 attempts to load icons specified with `rel="icon"` from a wrong location.

Requests for /en/index.html are immediately followed by requests for /en/shared/globe-rust.svg . The file /en/index.html has `<link href="../shared/globe-rust.svg" rel="icon" sizes="any" type="image/svg+xml"/>`, so the icon should be loaded from /shared/globe-rust.svg .

**Comment by Wevah** [comment]
I’m not sure if we support SVG icons natively, but we should at least be trying the right path. I should probably check the mine-type, too, if we don’t support SVG.

**Comment by Wevah** [comment]
Yeah, we don't render SVGs outside of the article view (since WebKit takes care of that). I found https://github.com/IconJar/IJSVG which is under the MIT license and compiles to ≈700 KB if we ever want to support them ourselves.
