### ISSUE TITLE
Mac feature request: Vim-style keyboard navigation

### ISSUE THREAD

**Issue by gueorgui** [Ranchero-Software/NetNewsWire#1747]
Many Web-based RSS services (Feedly, Feedbin, Newsblur) support Vim-style keyboard navigation (`j` for next article, `k` for previous article, etc). It would be nice to have this available as an option in NetNewsWire as well.

Thank you for building NetNewsWire, it's a fantastic app!

**Comment by vincode-io** [comment]
Eventually we plan to have customizable keyboard shortcuts.  We are tracking this as #508 for a future release.  I'm closing this one since it is basically a duplicate.

**Comment by gueorgui** [comment]
Thank you!

**Comment by brentsimmons** [comment]
When we do customizable keyboard shortcuts, we might have something like a “Vim Set” that you could use, rather than having to do all the customizations manually.
