### ISSUE TITLE
iOS: Pull to refresh has dead zones

### ISSUE THREAD

**Issue by joekissell** [Ranchero-Software/NetNewsWire#1760]
In the Feeds list, if the spot where your finger lands to pull down to refresh happens to be a heading (Feedly, On My iPad, Smart Feeds), the list does not pull down, so no refresh occurs. The pull has to start on an area of the list that is not gray. There shouldn't be any dead zones—pulling down anywhere in the list should work.

**Comment by Wevah** [comment]
This is probably a side effect of the gesture recognizers added to fix #1661.
