### ISSUE TITLE
"Go to Feed" action visible when you are already inside the feed

### ISSUE THREAD

**Issue by hartlco** [Ranchero-Software/NetNewsWire#1766]
Triggering the context menu (or popover menu) for an article inside a specific feed shows the "Go to Feed" action. Clicking this will have no effect for the user. I believe it should be removed in this case and only show up when the action will actually take the user to the feed.

![IMG_3966](https://user-images.githubusercontent.com/1497750/73603858-97a0fb80-4588-11ea-931d-300373333b87.PNG)

**Comment by vincode-io** [comment]
@hartlco good catch. Now you own it!  😀
