### ISSUE TITLE
lastImageCacheFlushDate is never actually persisted

### ISSUE THREAD

**Issue by Wevah** [Ranchero-Software/NetNewsWire#1770]
We set it to the current date via `UserDefaults.standard.register()` on launch, which means the cleanup branch is never hit in `CacheCleaner`, which in turn means `lastImageCacheFlushDate` is never set outside of `register()` and is never persisted to the defaults database. This means the cache is never actually purged.

**Comment by vincode-io** [comment]
@Wevah Can this be closed now?

**Comment by Wevah** [comment]
Yes, sorry!
