### ISSUE TITLE
iOS: "Website Name" is displayed in web viewer

### ISSUE THREAD

**Issue by blackketter** [Ranchero-Software/NetNewsWire#1774]
When I tap a link to open in the web viewer the words "Website Name" will sometimes appear in the header of the new view when the page is loading.  This seems like a placeholder and should probably be blank or say something like "Loading..."  

Additionally, if I tap on a link from the web viewer that opens in another app (say a link that goes to the Amazon app), upon returning to NNW, the web viewer will remain with that text at the top of the window. (This may be a separate bug...). See screenshot:  
![Image2](https://user-images.githubusercontent.com/131679/73796368-db9b2880-4761-11ea-8950-3f06d3e263b1.jpg)

**Comment by brentsimmons** [comment]
I don‘t believe there’s anything we can do about this, unfortunately — this view is outside of our control. I’ve actually seen the same thing in Safari.

**Comment by brentsimmons** [comment]
But maybe there’s some way we can prevent the view from sticking around.

**Comment by vincode-io** [comment]
Reading through the SFSafariViewController documentation, I don't think there is anything we can do here.  Interaction with SFSafariViewController is very limited (most likely for security reasons).
