### ISSUE TITLE
Cmd-click should open in Safari without switching

### ISSUE THREAD

**Issue by MtnBiker** [Ranchero-Software/NetNewsWire#1778]
I don't know if this is a bug or feature, but Cmd-clicking on an article title should open the Safari window behind NNW. This is a common action in macOS.

Feature: An option for right arrow from an article to do the same as above, i.e., open the article in Safari behind NNW. Has to be an option or accidental arrowing would be frustrating to those who hadn't selected the option.

Safari should of course be taken to mean default browser.

Keep up the good work.

**Comment by Wevah** [comment]
There's an option in the preferences for opening in the background; Command-click should probably invert this setting.

**Comment by spodick** [comment]
More of an FYI - may be Apple's or Google's problem instead.  I use the "Open in background in browser" preference.  That works fine for Safari and Firefox, but if Chrome is set as my default web browser then command-clicking a link does not open in the background and takes me directly to the link in Chrome.
MacOS: 10.15.5
Chrome: Version 83.0.4103.116 (Official Build) (64-bit)

**Comment by brentsimmons** [comment]
Chrome bug.

**Comment by brentsimmons** [comment]
It’s a bug in Chrome, and I don’t know of any way to work around it.

**Comment by nskh** [comment]
Sounds good, thank you!

**Comment by timharek** [comment]
This is also the case with Firefox 87.

When I'm using Newsboat in the terminal, I'm able to open articles from my feeds without bringing the application to the foreground with `open -ga`.

I'm not very familiar with macOS development, so I'm not sure if there is an equivilant in Swift when opening an application from another.

**Comment by vincode-io** [comment]
This has been implemented, so I'm closing this one out.
