### ISSUE TITLE
Web feed icons missing in article view in some Feedly feeds

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#1779]
I’m not sure if it’s coincidence or not that these are Feedly feeds. Could be some other reason.

But for these two feeds I get an icon on the Feeds list and Timeline but *not* in the article view:

https://daringfireball.net/index.xml

http://fivethirtyeight.com/features/feed/

This is not new in build 36. I feel like I noticed it just recently, but it’s also possible it never worked for these two feeds. I wish I had better details. (Sorry about that!)

**Comment by Wevah** [comment]
FWIW I get the icons fine when they're added as OnMyMac feeds.

**Comment by vincode-io** [comment]
This is definitely a Feedly specific bug.  It works fine in Feedbin as well.

Since the bug appears on the web view instead and not the timeline, I would look for the problem in ArticleIconSchemeHandler.  It could be that the articleID is different for Feedly and causing some issues.
