### ISSUE TITLE
Has importing xml files to the iOS application been removed?

### ISSUE THREAD

**Issue by dlevi309** [Ranchero-Software/NetNewsWire#1781]

**Comment by brentsimmons** [comment]
It has not been removed.

What are you trying to do, and what is happening?

**Comment by dlevi309** [comment]
Sorry, I think something was wrong with TestFlight at the time I commented. Apps kept acting like it was the initial launch every time they were killed.

**Comment by dlevi309** [comment]
And thank you for such a wonderful product. 👊

**Comment by brentsimmons** [comment]
Thanks!
