### ISSUE TITLE
iOS: Swipe left to delete

### ISSUE THREAD

**Issue by tubereuse** [Ranchero-Software/NetNewsWire#1789]
This is somewhere between a feature request and a UI "bug": swipe left to delete is easy to do and can have big consequences, especially if a folder is deleted. The majority of users will not have back-ups. I would suggest a pop-up delete/cancel is triggered to prevent inadvertent deletions.

**Comment by brentsimmons** [comment]
Good point. For now, undo should work.

**Comment by lilyball** [comment]
I just accidentally swiped to delete a feed. I reflexively hit Cmd-Z, but I didn’t see any feedback in the app. I cmd-tabbed away to another app, and back, at which point I saw the feed was in my list again.

However, the 4 starred items I had in the feed are gone. And they were really old items, so there’s no hope of finding them again. This is a rather serious consequence and is extremely annoying.

Also NetNewsWire didn’t restore my Read Articles Filter setting for the feed, though that’s pretty minor.

**Comment by lilyball** [comment]
Also the 10 most recent entries were marked as unread again, even though everything in the feed (except the 4 starred items) had been marked as read.

**Comment by lilyball** [comment]
Interesting. I just checked the Feedbin website and if I scroll back into the history of the feed I can actually see the items are still starred there. But they’re old enough that they’re not being synced to NetNewsWire. I don’t know precisely what controls what gets synced to NetNewsWire, I’d have hoped that starred items always would, but after restoring the feed, NetNewsWire’s oldest post is June 29, 2020, but the Feedbin website shows a much longer history (and all the starred items are older than that).

**Comment by vincode-io** [comment]
@lilyball if you do a manual sync, do the starred articles come back?

**Comment by lilyball** [comment]
@vincode-io I think Feedbin is actually being a little weird here. These starred articles aren’t showing up in the “Starred” section of Feedbin. If I go back to one of them and star an adjacent article, it pops up in Feedbin’s “Starred” section, but unstarring and restarring one of these previously-starred items does not do this.

**Comment by vincode-io** [comment]
@benubois do you have any ideas as to what could be happening with @lilyball 's starred items?  They won't appear in the starred Feedbin area after a delete and re-add of a feed.

**Comment by lilyball** [comment]
If it helps, the blog is https://mjtsai.com/blog/, and one of the items is [Fast Safe Mutable State in Swift 5](https://mjtsai.com/blog/2019/02/07/fast-safe-mutable-state-in-swift-5/) (dated Feb 7, 2019).

**Comment by vincode-io** [comment]
@lilyball Could you do an experiment for me?  If you star an article that is older than 3 months in that feed that you previously didn't have starred and then sync NNW, does it show up as starred in NNW?

**Comment by lilyball** [comment]
@vincode-io Yes, that worked. I just starred an article from November of last year, then went to NNW and checked the feed, and it’s showing that starred article.

I’m pretty sure the issue with the missing starred articles right now is entirely on Feedbin’s end, given that Feedbin isn’t showing these previously-starred articles in the Starred list even if I unstar and restar them (but it does show other articles of similar or older age that I’m starring now for the first time).

As far as NNW is concerned, it still needs a prompt to confirm when swiping to delete a feed, both because Undo doesn’t properly restore all state even on NNW’s end (e.g. filter unread articles), and because it’s easy to do by accident so we shouldn’t rely on Undo as the only safeguard (e.g. I might not even realize I deleted a feed until later).

**Comment by vincode-io** [comment]
@lilyball, @brentsimmons and I agree and will be putting a confirmation dialog for feed deletes in NNW.

**Comment by brentsimmons** [comment]
Let’s do a confirmation for both Mac and iOS in 6.0.

**Comment by benubois** [comment]
@vincode-io no idea off the top of my head. I'd be interested in figuring it out though. 

>  Feedbin isn’t showing these previously-starred articles in the Starred list even if I unstar and restar

@lilyball Are you staring/unstaring  in NetNewsWire or Feedbin?

**Comment by lilyball** [comment]
@benubois Feedbin. The articles are old enough that they won’t sync to NNW.

**Comment by vincode-io** [comment]
Starred articles will sync to NNW regardless of age.
