### ISSUE TITLE
Tabs support

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#179]

**Comment by brentsimmons** [comment]
Part of support for multiple windows.

**Comment by stuartbreckenridge** [comment]
@vincode-io 

For the SwiftUI building—I **may** be missing something obvious—but tabbing can be enabled in the SwiftUI building by removing this line from the app delegate:

`NSWindow.allowsAutomaticWindowTabbing = false`

Tabbed windows seems to broadly work (though there are some layout issues).

<img width="1537" alt="Screenshot 2020-07-23 at 8 30 59 PM" src="https://user-images.githubusercontent.com/7046652/88286510-71803b00-cd23-11ea-8c6b-068b3c48eca6.png">
<img width="1537" alt="Screenshot 2020-07-23 at 8 31 03 PM" src="https://user-images.githubusercontent.com/7046652/88286529-78a74900-cd23-11ea-8fc6-e23594d081f0.png">
