### ISSUE TITLE
NNW doesn't sync read/unread items to/from Feedly

### ISSUE THREAD

**Issue by davidtbrady** [Ranchero-Software/NetNewsWire#1790]
Sorry if this is redundant... I did look through the known issues using the keyword "Feedly"... and did not find this as a reported issue.

NNW doesn't sync read/unread items to/from Feedly: I'm finding that NNW doesn't seem to sync the read/unread status of news items. That is, if I read through all my NNW feeds, they're marked as read. However, when I go to Feedly on the web or via the iOS app, the news items are marked as unread. The inverse is true as well.

Steps to repro:
1. Read feeds on NNW
2. Observe as articles are marked as read
3. Go to Feedly.com or the iOS app
4. Observe that news items are marked as unread

Alternatively:
1. Read items on Feedly.com or the iOS app
2. Observe that articles are marked as read
3. Open NNW
4. Observe that articles are marked as unread

**Comment by vincode-io** [comment]
Is this a bug for the NNW on the Mac?

**Comment by brentsimmons** [comment]
Things to check:

1) That you’re using a Feedly account. (Rather than just importing your Feedly OPML into an On My iPhone/iPad account.)

2) That the problem exists on different networks. (A work network might, for instance, be tracking some traffic.)

**Comment by davidtbrady** [comment]
Hey Brent, thanks for the quick reply!

I am using an OPML import of my Feedly subscriptions.

Thing is, how do I use a Feedly account in NNW? I don’t see an option for it? See screenshot below (clicking “+” does nothing):


Apologies as maybe I’m missing something rather obvious…

-David

**Comment by brentsimmons** [comment]
For some reason the screenshot doesn’t show up — but I’m guessing you’re on the Mac. If so, then the reason is pretty simple — we don’t have Feedly support on the Mac yet. (We will. Feedly support is included in the beta version of the iOS app.)

**Comment by davidtbrady** [comment]
Got it — yep that was it. Not sure why the screenshot didn’t show up… I’m simply using Mail.app as usual.

Thanks so much — I appreciate you taking the time to reply! I’m sure you guys are quite busy.

Thanks for all the hard work! The detail really shows.

-David
