### ISSUE TITLE
iOS: Squished close button

### ISSUE THREAD

**Issue by J-rg** [Ranchero-Software/NetNewsWire#1797]
The close button of the image view controller is 2px short in width, making it look slightly squished:

![nnw1797](https://user-images.githubusercontent.com/4042863/74597376-d17d0200-505e-11ea-901f-051b8874551c.png)

**Comment by flowinho** [comment]
@vincode-io i checked this. As far as I can tell, this is not the case anymore. Neither in the simulator, nor on the device does the image look cramped. I zoomed in and couldn't find anything.
The IB definitions also suggest no issue.

- Constraints are set 44x44 which is a square, not a rectangle as suggested.
- The asset is a system asset, reducing the chance that there is an issue with the graphic itself.

**Comment by vincode-io** [comment]
It doesn't look squished to me either.  @J-rg do you want to take a look at this one and see if there is something we can do here?  Otherwise, I will close the issue.

**Comment by J-rg** [comment]
Ich checked build 39 on an iPhone SE on iOS 13.3.1, the symbol is still displayed incorrectly there. Maybe the issue only occurs on @2x devices?

**Comment by vincode-io** [comment]
@flowinho found it.  Thanks for pointing it out @J-rg.  The fix will be in the first 5.0.1 TF build.
