### ISSUE TITLE
iOS: Articles getting closed after refresh

### ISSUE THREAD

**Issue by J-rg** [Ranchero-Software/NetNewsWire#1798]
When the Refresh to Clear Read Articles option is enabled, you get kicked out of an article if you opened it while refreshing:

![nnw1798](https://user-images.githubusercontent.com/4042863/74597491-967bce00-5060-11ea-986e-6400d3b8866c.png)

**Comment by Wevah** [comment]
Does it happen when you have the unread filter turned off?

**Comment by J-rg** [comment]
No, articles are only closed if something makes them disappear from the article list. It does not happen if you mark the article as unread before refreshing finishes.
The same happens if an article marked as read is selected and you turn on the unread filter.

**Comment by vincode-io** [comment]
This behavior has been changed and will be in the next release.
