### ISSUE TITLE
iOS: (37) “Enable Full Screen Articles” doesn’t work

### ISSUE THREAD

**Issue by andrewhag** [Ranchero-Software/NetNewsWire#1799]
Bug Report:
When I toggle on “Enable Full Screen Articles” in Settings then return to an article, it doesn’t make my articles full screen. Toolbars are still visible.
Expected: the top navigation bar and bottom toolbar would hide in the article view when scrolling. There doesn’t seem to be a difference whether the switch is on or off.

Feature Request:
Ability to toggle on “Full Screen Article” while on the article view (ex. maybe as an option when you tap the “Reader mode” button).

I like having the toolbars available when swiping through lots of articles, but when I find something I want to read, especially long articles, I want a distraction-free reading experience.

Heading all the way back to the Settings view is a pain. I usually just open the link in Safari and enter Reading Mode… which isn’t ideal.

Device: iPhone 11 Pro, iOS 13.3.1

**Comment by alexcfaber** [comment]
As far as I know; when you have full screen mode enabled in settings you can switch from the article view by Tapping the navigation bar. 

Can you confirm if that’s not working either?

**Comment by andrewhag** [comment]
Oh cool, if I have “full screen” enabled in Settings I can successfully tap the navigation bar to hide the toolbars on the article view. Good to know!

I assumed this feature worked like this:
If “full screen” is enabled, the controls hide after scrolling (similar to Safari). It’d be nicer if toggling full screen from the article view was more discoverable, otherwise it seems like the feature doesn’t work.

Couple suggestions:
- on scroll, hide the controls
- a dedicated “full screen” button in the navbar
- last resort: add as an action in the share sheet

Aside:
If activating/disabling full screen from the article view was more obvious, you may not need a toggle in Settings at all. I assume the setting is there so someone doesn’t accidentally activate fullscreen and doesn’t know how to deactivate it

**Comment by vincode-io** [comment]
I've added some instructions on the full screen setting to make this easier to understand.  You should see it in the next build.
