### ISSUE TITLE
iOS: Incorrect row height for empty list

### ISSUE THREAD

**Issue by sharplet** [Ranchero-Software/NetNewsWire#1800]
The article view has a nice tall row height when there are articles visible, and this height is continued after the end of the content:

![image](https://user-images.githubusercontent.com/147686/74679881-08513600-518d-11ea-876f-919374ef660c.jpg)

But when the list is empty, it reverts to the default row height, which is slightly jarring:

![image](https://user-images.githubusercontent.com/147686/74679904-1a32d900-518d-11ea-858b-f53bcf1b90b2.jpg)

Setting the table view’s `rowHeight` before the first layout has worked for me in the past.

**Comment by flowinho** [comment]
I think there are several approaches to this, depending of the desired “playfulness” of the app.

- Remove the UITableView when there is no content from the super view (or hide it, whichever fits better in the current code structure). And do not display anything. 
- Remove the UITableView and display a “You’ve catched up!” or something similar in your now empty view. This could also be made in a funny way, like “You’ve catched up! Isn’t it time to walk the dog?” (Or something else).
- Prevent the empty ViewController from being reached. If the button is disabled, users will know “there is no content”. This depends on your usability concept. 
- Display the articles but in a greyed our state to tell the user “you’ve already read those”. This might be the nicest approach however it impacts memory - which NNW is concerned about - that’s why we love it 😏

**Comment by vincode-io** [comment]
Here is one approach we should investigate.  https://swiftjectivec.com/Diffable-Datasource-Empty-View/

**Comment by flowinho** [comment]
This would make NNW iOS13+ only. What’s the targeted iOS version support?

**Comment by vincode-io** [comment]
Yep. iOS 13 only.

**Comment by flowinho** [comment]
@vincode-io I can have a look into this. But someone would need to choose / create the asset to be displayed when the list is empty.
Also I'd love @brentsimmons to comment on this, especially on the multiple suggestions I made above.

**Comment by vincode-io** [comment]
My personal favorite would be to do @flowinho's second suggestion and put up a "You're all caught up!" message using this technique https://swiftjectivec.com/Diffable-Datasource-Empty-View/.  It would/should match the font and styling of the the article view when the article view displays its "No selection" message.

**Comment by flowinho** [comment]
There could also be a funny Yoda version similar to GitHub 404 sites. When all feeds are read we could display a stylized drawing that matches the app that says:

„In 15mins again to check your feeds, you want.“ or something like that.

Or that’s just my mind wanting to have that and it’s abusing the fact that this software is open source and therefore I can suggest stuff like this 🤪

**Comment by brentsimmons** [comment]
We should do something like the below. “No Articles” instead of “No Mail.” It should still be possible to run a search from there.

![IMG_4215](https://user-images.githubusercontent.com/1297121/76692899-58031000-661a-11ea-828d-b443e21e605e.png)

**Comment by vincode-io** [comment]
Assigning to @flowinho since he expressed an interest in working on it.

**Comment by flowinho** [comment]
Gotcha! 💪
