### ISSUE TITLE
iOS: Share and reader buttons should be disabled if the permalink is missing

### ISSUE THREAD

**Issue by vincode-io** [Ranchero-Software/NetNewsWire#1802]
This occurs on Feedly and only on this blog https://blog.hal.codes/rss.xml.

**Comment by vincode-io** [comment]
It looks like this is an issue with the permalink. The article title correctly doesn’t link out.

When the permalink is missing or invalid, the share and reader buttons should be disabled. 

There is still the issue of why the permalink is bad on Feedly.

**Comment by vincode-io** [comment]
The blogs permalink is invalid. It looks like Feedly strips out invalid URL’s.

**Comment by flowinho** [comment]
@vincode-io Is the permalink stored in the `url` property of `ExtractedArticle` ?

**Comment by vincode-io** [comment]
You should test to see if the `preferredLink` on the `article` is nil.

**Comment by flowinho** [comment]
@vincode-io As I'm in a hurry and cannot open another PR right now, here is my change to fix this issue: Edit LOC 144 onwards in `ArticleViewController.swift` to the following:

```swift
nextUnreadBarButtonItem.isEnabled = coordinator.isAnyUnreadAvailable
prevArticleBarButtonItem.isEnabled = coordinator.isPrevArticleAvailable
nextArticleBarButtonItem.isEnabled = coordinator.isNextArticleAvailable
readBarButtonItem.isEnabled = true
starBarButtonItem.isEnabled = true
		
let permalinkPresent = article.preferredLink != nil && article.preferredLink?.count ?? 0 > 7
articleExtractorButton.isEnabled = permalinkPresent
actionBarButtonItem.isEnabled = permalinkPresent		
```

**Comment by flowinho** [comment]
`article.preferredLink?.count ?? 0 > 7` is just pure guessing. We could also 8 characters to make sure it's `https://` or similar. What is also entire feasible: Use `URL(from string:String)` to check wether iOS can create a valid URL from this string. If this works, we treat the link as present.

There are multiple ways of solving this.

**Comment by vincode-io** [comment]
You can trust `preferredLink` to be nil if the link isn't there.  You don't need the length test.

We've got plenty of time still to get this in.  Just open a pull request for it when you are available.
