### ISSUE TITLE
Mac: No Icon & Text option in toolbar

### ISSUE THREAD

**Issue by sharplet** [Ranchero-Software/NetNewsWire#1804]
I'd love to have the option to use Icon & Text mode in the toolbar, as I find Icon Only difficult to scan visually.

<img width="341" alt="capture 2020-02-20 at 7 18 17 pm" src="https://user-images.githubusercontent.com/147686/74992341-d272b280-5415-11ea-869c-a816ae673f28.png">

**Comment by nostodnayr** [comment]
This isn’t possible with the modern-style macOS toolbars. You can turn on the traditional style with a hidden preference, and then ‘Icon and Text’ will be an option: https://ranchero.com/netnewswire/help/mac/5.0/en/hidden-preferences

**Comment by sharplet** [comment]
Fantastic, thank you!
