### ISSUE TITLE
iOS: Article view blank after viewing content in Safari

### ISSUE THREAD

**Issue by pungerfreak** [Ranchero-Software/NetNewsWire#1808]
When following an in-article link, then transferring it from the embedded view to Safari before closing the embedded view to return to the original article.

While I have not encountered this 100% of the time, it has been more often than not. I noticed it after updating to version 38 this morning and have tried a few different scenarios, all with the same results:

1. waiting for the embedded view to load fully before transferring to Safari vs transferring hastily
2. complex vs simple pages
3. Feedly vs On My Phone
4. Several different feeds (Codrops, Surfin’ Safari, Daring Fireball)

Here are a few recordings of the activity to reproduce.

http://raygreenlaw.s3.amazonaws.com/nnw/RPReplay_Final1582390283.MP4
http://raygreenlaw.s3.amazonaws.com/nnw/RPReplay_Final1582390110.MP4

**Comment by vincode-io** [comment]
@pungerfreak Which build were you running when you were having this problem?  I'm having trouble recreating it.

**Comment by vincode-io** [comment]
@pungerfreak Nevermind.  I see that you are referencing build 38.

**Comment by pungerfreak** [comment]
@vincode-io, I updated to iOS 13.3.1 this morning and I have not seen it since. I'll keep an eye and update the issue if it resurfaces.

**Comment by vincode-io** [comment]
I think this might be related to another bug that I just fixed and referenced in the commit.  I'm going to close this issue.  @pungerfreak if you can recreate this after we put build 39 out, let reply to this issue and I will reopen it.
