### ISSUE TITLE
iOS: Footnotes don’t open when tapped

### ISSUE THREAD

**Issue by vincode-io** [Ranchero-Software/NetNewsWire#1812]
See this article for an example. https://aplus.rs/2020/building-sff-pc-in-2020/

**Comment by vincode-io** [comment]
It also looks like we are failing on Daring Fireball footnotes now.  https://daringfireball.net/2020/02/df_tootbot_is_fully_operational  

Is it because Daring Fireball is using absolute URL's on the footnote links?

**Comment by Wevah** [comment]
The Daring Fireball ones are working for me. Is this feed in On My Mac or elsewhere?

**Comment by Wevah** [comment]
I can reproduce the issue for the article in the OP, however.

**Comment by Wevah** [comment]
Error is:

TypeError: null is not an object (evaluating 'document.querySelector(`[id='${targetId}']`).innerHTML')

**Comment by Wevah** [comment]
Ok, the issue is that `url.hash` doesn't decode the fragment, which is needed for it to work correctly in `querySelector()` or `getElementByID()`.

**Comment by Wevah** [comment]
Someone will have to let me know if this fixes the issue they're seeing on DF, since I can't reproduce it there.
