### ISSUE TITLE
macOS: After hitting “Mark all as read” all read feed items should disappear

### ISSUE THREAD

**Issue by irodknocker1** [Ranchero-Software/NetNewsWire#1814]
When i hit “Mark all as read” all read feed items should disappear? Especially in Smart Feeds.

They only disappear when i switch for example from “All Unread” to “Today” and back to “All Unread”. Or when i quit the app and launch it again.

It would be then the same as on NNW on iOS.

**Comment by vincode-io** [comment]
We intend to add something to handle this. It is being tracked as issue #130.
