### ISSUE TITLE
iOS: Daring Fireball footnotes aren't recognized when coming from Feedbin

### ISSUE THREAD

**Issue by vincode-io** [Ranchero-Software/NetNewsWire#1817]
It looks like the DF footnote URL's are getting changed to absolute URL's by Feedbin.  Our pattern matching doesn't take this into consideration and they aren't getting recognized as footnotes.

**Comment by Wevah** [comment]
If we want to match to style in only CSS, we can change `a[href^='#fn']` to `a[href*='#fn']`, but that might introduce issues if the link actually goes to an external site.

**Comment by vincode-io** [comment]
It sounds to me like the JS option is the better one.

**Comment by Wevah** [comment]
Agreed.

**Comment by Wevah** [comment]
(For future reference, there's a `:local-link` pseudoclass in CSS4, but nothing implements it yet.)
