### ISSUE TITLE
iOS: Add bottom and top padding to images

### ISSUE THREAD

**Issue by vincode-io** [Ranchero-Software/NetNewsWire#1819]
Right now there is no padding, so two pictures, one after another look like they are just one picture.

**Comment by Wevah** [comment]
Is there a good test feed/article for this one? Otherwise I'll whip up a sample file for it.

**Comment by vincode-io** [comment]
https://blog.thenounproject.com/tutorial-diy-coloring-book-noun-project-f5da884e39a5?source=rss----e1758884c61e---4

This is the third article from the end, dated Dec 9. About halfway through you should see a couple images butted up against each other.

**Comment by Wevah** [comment]
Looks like it might be partly to do with their being wrapped in `<figure>`s. Adding a margin to those is probably the thing to do.
