### ISSUE TITLE
iOS: 0x8badf00d crash

### ISSUE THREAD

**Issue by vincode-io** [Ranchero-Software/NetNewsWire#1821]
I got back 4 crash logs from users.  The symbolicated crashes are attached.

[symbolicated-crashes.zip](https://github.com/Ranchero-Software/NetNewsWire/files/4247523/symbolicated-crashes.zip)

One of them has no useful information.  The other 3 all seem to have crashed because the watchdog killed them while they were blocking the main thread while trying to do disk I/O.

**Comment by vincode-io** [comment]
Got another one.  Same issue here.  Waiting for disk access.

[symbolicated-5.crash.zip](https://github.com/Ranchero-Software/NetNewsWire/files/4257501/symbolicated-5.crash.zip)

**Comment by vincode-io** [comment]
Of those that allow share their email addresses, we have one user that has been experiencing this crash fairly regularly.  I've emailed them to see if it there is a disk storage issue on the device.  Maybe we're seeing some strange behavior if the user is running out of storage.

**Comment by vincode-io** [comment]
BTW, no disk space issues with this user.  They are on an iPhone 7.  I'm not sure why, but this user seems to get hit particularly hard.

**Comment by brentsimmons** [comment]
Let’s see if we’re still getting these with the release version. If not, we can close this.
