### ISSUE TITLE
Feature Request: IOS - Hide read articles when mark as read is invoked

### ISSUE THREAD

**Issue by travelingflwr** [Ranchero-Software/NetNewsWire#1825]
Would love to see this sometimes as it would remove the need to do an extra feed refresh to hide them.  It may also cut down on the total number of read requests.

I don’t think it’s needed to do an extra network request when the articles are hidden.  Just sync the read status on the next update.

**Comment by vincode-io** [comment]
Hi @travelingflwr.  Thank you for the suggestion, but we as a team, have discussed this subject many times.

The problem with automatically removing the articles from the timeline is that is surprises the average user.  This is problematic, especially if they didn't intend mark it as read.  In fact, it is so problematic that we leave the option to clear read items by doing the refresh off by default.

**Comment by travelingflwr** [comment]
Ack. Sounds very well thought out then.  Completely reasonable design then.

Thanks for the detailed explanation!!

Amy
