### ISSUE TITLE
Problem adding site

### ISSUE THREAD

**Issue by ghost** [Ranchero-Software/NetNewsWire#1829]
I’m trying to add this site and even if it’s correct it’s impossible to add

![6E9FC18B-0845-4313-9E2E-C5FABE5F1F49](https://user-images.githubusercontent.com/61545389/75442417-badc8200-595f-11ea-922b-8aae5a898d28.png)

**Comment by brentsimmons** [comment]
There may or may not be a bug here. The feed may not be findable. But, just in case, let’s check.

**Comment by mvolpato** [comment]
This website does not provide feeds.
