### ISSUE TITLE
The alt text implementation is hard to read, obscures content, and does't feel iOS-like

### ISSUE THREAD

**Issue by colons** [Ranchero-Software/NetNewsWire#1831]
As raised [in 1468](https://github.com/Ranchero-Software/NetNewsWire/issues/1468#issuecomment-578693998):

>i am not a fan of this implementation. on ipad in landscape, it is hard to read due to the very long line length, and due to the lack of padding i feel doesn't look good. i also can't seem to to dismiss it, so it often obscures important content in a way that's not really possible to work around.
>
>i really like how Mast and Reeder handle this; as text that appears at the top of the list of actions when you peek (press and hold) an image
>
>![Mast's alt text strat](https://user-images.githubusercontent.com/1394710/73169073-27f7c000-40f3-11ea-8b2c-c67d5a2fb172.jpeg)
>
>![Reeder's alt text strat](https://user-images.githubusercontent.com/1394710/73169047-16161d00-40f3-11ea-803c-7cf0d89bfc69.jpeg)

**Comment by vincode-io** [comment]
As you have pointed out, this has already been discussed. This may not be your favorite implementation, but being pushy about it won’t get it changed.
