### ISSUE TITLE
IOS: How to get NetNewsWire invite code for TestFlight?

### ISSUE THREAD

**Issue by garyanson** [Ranchero-Software/NetNewsWire#1835]
I've been doing beta testing on other apps and needed a code to get them loaded through TestFlight.
Where and How do you suggest I get beta through TestFlight?

**Comment by pdokas** [comment]
https://ranchero.com/netnewswire/test-ios

**Comment by mvolpato** [comment]
There is a _sign up on TestFlight_ link in the page @pdokas posted. You need to open that page from the iOS device.
