### ISSUE TITLE
iOS: UISwitch layout is off (margin/alignment)

### ISSUE THREAD

**Issue by flowinho** [Ranchero-Software/NetNewsWire#1837]
The Switches are somewhat placed with a strange margin to the top / bottom of the superview. Also their right edges do not perfectly line up with the arrow symbols. Took me a while to find what’s bothering me. Added Apples Settings.app to showcase what I mean. 

![DB9F6DC9-6098-4BB9-A23D-068B4DFA86C9](https://user-images.githubusercontent.com/1244071/75592989-261f7480-5a84-11ea-9f71-d05d17cf2b97.jpeg)

**Comment by flowinho** [comment]
@vincode-io Mind if I work on this?

**Comment by vincode-io** [comment]
Go ahead. We won’t open up work on 5.0.1 until after we release to the App Store.  Until then just mark your pull request as work in progress and make it against the ios-candidate branch.
