### ISSUE TITLE
iOS: UISwitch background color varies for some switches

### ISSUE THREAD

**Issue by flowinho** [Ranchero-Software/NetNewsWire#1838]
The toggles for “Confirm Mark All as Read” and “Enable Full Screen Articles” do not have the same color when toggled to ON.

![49DCEC80-4EF2-4EF9-A744-05EA8EF6D0E7](https://user-images.githubusercontent.com/1244071/75593075-641c9880-5a84-11ea-8fde-1485c93dbfb7.jpeg)

**Comment by vincode-io** [comment]
Adding to the iOS beta because it is so bad and low risk to fix.
