### ISSUE TITLE
iOS: Import / export subscriptions feature should feature OPML

### ISSUE THREAD

**Issue by flowinho** [Ranchero-Software/NetNewsWire#1839]
Suggestion: display the expected / resulting file type (OPML) next to TableViewSection that allows importing and exporting feeds.

![7932678B-F8E7-431A-8D8B-D540A51F3EEB](https://user-images.githubusercontent.com/1244071/75593145-a9d96100-5a84-11ea-8777-64bae5e114e0.png)

**Comment by vincode-io** [comment]
This is intentional and matches verbiage used in the Mac app.
