### ISSUE TITLE
RFE: Mark read on scroll in timeline

### ISSUE THREAD

**Issue by vincode-io** [Ranchero-Software/NetNewsWire#1844]

**Comment by brentsimmons** [comment]
How would this behave exactly? For instance, say I tap on a feed and the timeline opens. Is everything visible in the timeline marked as read immediately? Or do I have to scroll a little first? Or…?

**Comment by vincode-io** [comment]
This was requested more than a couple times. I know at least once or twice in test flight feedback and I think in the feedback slack channel as well. 

I believe that the goal here is to make the timeline work more like a infinite scroll social media timeline. Once you scroll past a timeline item it doesn’t come back again. 

Since we always scroll up, an item would get marked as read after it was visible and then gets scrolled out of site through the top of the scroll area.

**Comment by Bunn** [comment]
@brentsimmons @vincode-io I played around with an implementation of it some time ago and came to this approach:
https://www.dropbox.com/s/ftob2f62somw9ir/autoread.mov?dl=0

One problem that this might cause is that the last items on the table would never be marked as read during a scroll and the user would need to manually mark as read anyways, breaking out the seamless flow that this feature provides.

One possible way to solve this is to change the table contentInset a little bit to allow the user to scroll more than necessary but it might not be visually pleasant, looking like a tableview bug to scroll and see no new content.

**Comment by brentsimmons** [comment]
What other app does this well? I’d like to look at prior art.

**Comment by vincode-io** [comment]
Unread has this feature.

**Comment by Bunn** [comment]
Feedly

**Comment by scapix** [comment]
Feedly - "Mark all as read" button at bottom of the list
Newsify - pull up to mark all as read when at the bottom (similar to how refreshing stuff works in most up, just in opposite direction)

I prefer Feedly implementation as in Newsify you are able to trigger it accidentaly when trying to scrolldown and not noticing you are at the end.

**Comment by abonham** [comment]
I second the Feedly approach, it's the only thing that's stopping me switching full time. It's frustrating when I've scrolled past a number of things I'm not interested and forget to mark all above as read if I need to do something else before getting to FeedZero

**Comment by vincode-io** [comment]
We have a Mark All as Read button at the bottom of the Timeline at all times. Another one like Feedly has would be redundant for us. 

I think all we need to do is mark the article as read after it leaves the viewable area.

**Comment by scapix** [comment]
Feedly has got that Mark All icon button, but still they just added text button at the bottom as part of the feed - scrolling with articles. As you mentioned it is redutant, but "easier" to use than their regular one. You do not need to switch "mentally" from feed and it is also awkwardly placed at top right.
In NNW it is much better placed so probably another one should not be needed.

**Comment by vincode-io** [comment]
We've spent a lot of time talking about Mark All as Read in this thread.  I don't think this functionality is for completionists anyway.  They are always going to hit the Mark All as Read when leaving the timeline which means that the Mark Read on Scroll isn't useful.

I imagine this would be more used by people browsing All Unread like a social media feed.  They may not ever hit the bottom of the list, but don't want to have to remember that they need to do a Mark All Above as Read before leaving the All Unread timeline.

**Comment by scapix** [comment]
I think it's exactly the opposite:

- Completioninst - i'm one of them and i always scroll/read (most articles just the titles) to the bottom of the feed/unreads and never Mark All as Read without doing so. Mark on scroll is important as I switch feeds/categories midway quite a lot (depending on time, mood and number of unread counts) and marking "all above" as read is cumbersome. Additional Mark All as Read button at the bottom of the list / of Feedly like behavior is not required, but nice to have.

- Social feed readers - if they never hit bottom, they will never encounter that Feedly's like mark all button (or Newsify scroll up to mark behaviour). As i'm not regular social media user, but probably all they need is already there and don't need marking at all - there is nothing like that and in any social media service if i'm correct (and that's reason i don't use them) or any similar news service (like Flipboard, Apple News,...).

**Comment by vincode-io** [comment]
I’m defining a completionist as someone that gets to 0 unreads most every time they use the app.

**Comment by scapix** [comment]
> I’m defining a completionist as someone that gets to 0 unreads most every time they use the app. 

Me too. As I’ve many sources and articles, I try to get to 0 at the end of the day. Mostly reading few articles in short sessions during day, thats probably why we have different needs.

**Comment by johnburnett** [comment]
Would love to +1 vote for this, as it's the one thing preventing me from switching to NetNewsWire.

@brentsimmons : the Feedly app has this behavior, and generally works the way you described (articles scrolling up off-screen are marked as read, and the bottom of a given feed has enough space to scroll off the top of the screen).  Additionally, once an article is marked as read, it can be manually marked unread, and it will then NOT be marked as read again when scrolling off-screen.  This manual marking is respected until you refresh the feed again or come back it in the future (so it's more transient than a "save for later" flag).  This is useful to quickly skim through a feed, "tagging" articles that are worth digging into by marking them unread, and then scrolling the rest off.  You're then left with the set of articles that are interesting.

**Comment by brosenz** [comment]
I would love to have this feature, I use Newsify and it works great, but I am trying to standardize NetNewsWire across all my iOS, iPadOS and macOS devices, please implement this feature, even as optional, thanks

**Comment by vevek** [comment]
Recently released Reeder 5 added this feature of marking items as read while scrolling.

**Comment by scapix** [comment]
i don't know what were the problems with pull request implementing this feature, but could this be reopened as that code was reverted?

**Comment by everhardt** [comment]
The maintainers (unfortunately IMO) decided they did not want this feature. See oa. https://github.com/Ranchero-Software/NetNewsWire/pull/3359. The slack messages that is being referred to are [here](https://netnewswire.slack.com/archives/CCGTPJDPD/p1640728340297900), but if you're not in slack:
![image](https://user-images.githubusercontent.com/1840153/150312603-4253a2fe-417e-41bb-a22d-08f008057841.png)

Here's the blog post that relates to this topic: https://nnw.ranchero.com/2021/12/28/on-not-being.html

**Comment by scapix** [comment]
@everhardt  thanks for explanation
Right, it's their choice to leave this feature out. I think NNW the only RSS reader I have used/paid during the years (eg. feedly, ziner, newsify, fiery feeds, ..) missing this feature unfortunately :(
I just don't get the reasoning behind: if a feature exist in another app, that's a reason not to do
That way there won't be any features at all because most (all) features are already implemented in those and other aps.
