### ISSUE TITLE
iOS: Database clean up code may delete old unread items that are still available in sync services

### ISSUE THREAD

**Issue by vincode-io** [Ranchero-Software/NetNewsWire#1846]
Our unread counts and sync goes out of sync because we delete old unread items that are still in the sync service (in this case Feedbin).

**Comment by brentsimmons** [comment]
I need to find out more details about this. It’s going to be different for each sync system, most likely.

**Comment by vincode-io** [comment]
I think we will need to pass some kind indicator to the cleanup code that unread automatic marking is externally managed. In that case all unreads are preserved.

That way we don’t have to try to understand the policy for each service. As that service automatically marks something as unread, we delete it. Otherwise we don’t.

**Comment by jaanus** [comment]
Is there any further info I should provide about the symptoms or logs as a user affected by this?

Observed: at random times, NNW on a given iOS device deletes all Feedbin items (both read and unread)  that are older than 90 days.

Expected: I’m not entirely sure what’s my expectation as a user. It definitely should never touch the unread items, no matter how old they are. As for read items, I don’t care much either way. I have no idea what is Feedbin approach to keeping read items around - is it global, per feed, can I affect it somehow. I have never taken interest in this, and similarly, doesn’t matter too much to me as a user what NNW does here. Unreads, though, should definitely match fully between Feedbin, NNW, and other clients.

**Comment by brentsimmons** [comment]
It’s not just about deleting. Our SQL queries specify last-90-days, so those would have to be updated too.

It looks like we’ll have to have different deleting/querying policies. Hopefully just two different policies (one for local and one for synced).
