### ISSUE TITLE
iOS: create max line limit for iPad

### ISSUE THREAD

**Issue by vincode-io** [Ranchero-Software/NetNewsWire#1847]
Typographers typically cap line widths at 65–70 characters or about 13 words per line.  This would be a good place to start.

**Comment by vincode-io** [comment]
@Wevah Am I miss remembering, or did you say you wanted to work on this one?

**Comment by Wevah** [comment]
We decided on `44em` for the Mac version; that might work here. I'll try it out.

**Comment by Wevah** [comment]
That seems a bit wide for iPad.

**Comment by Wevah** [comment]
44em seems okay:
![Simulator Screen Shot - iPad Pro (12 9-inch) (3rd generation) - 2020-03-13 at 21 34 11](https://user-images.githubusercontent.com/130825/76673386-6bf33700-6572-11ea-9fc1-9224800b4428.png)

**Comment by vincode-io** [comment]
That looks great to me.
