### ISSUE TITLE
iOS: Account login views should tell password auto fill-in about the URL they need

### ISSUE THREAD

**Issue by flowinho** [Ranchero-Software/NetNewsWire#1853]
When I tested Feedbin and Feedly accounts I saw that that the URL field of iOS's password auto fill-in feature does not get populated. 

This issue affects only users that use either password managers or iCloud Keychain.

Expected behaviour: URL is provided, users can "1Click" their passwords into the account fields.
Observered behaviour: URL not provided, password managers did not know which item to pick. 

This is quite easy to fix and imho users expect it.

**Comment by flowinho** [comment]
Related links:

- https://developer.apple.com/documentation/security/password_autofill
- https://developer.apple.com/documentation/authenticationservices

**Comment by kielgillard** [comment]
Not sure about Feedbin but Feedly is using the [ASWebAuthenticationSession](https://developer.apple.com/documentation/authenticationservices/authenticating_a_user_through_a_web_service) API. In my experience, once I tap on the email field, I get password auto fill offer to fill in the form. I don’t think Feedly can do anything more to optimise that first touch away. It would have to be Safari (I think?).

Is your experience from Feedly different?

**Comment by flowinho** [comment]
Yes you are right. I wrote the issue w/o specific rss-sync providers to make sure that I mean that it should work for _all_ providers. OFC for services like Feedly that use a WebView to authenticate it's different.

**Comment by vincode-io** [comment]
@flowinho do you want to tackle this one when we open up 5.0.1 work?

**Comment by flowinho** [comment]
@vincode-io Can do! :)

**Comment by flowinho** [comment]
@vincode-io I encountered the issue that I need to be able to add a Password AutoFill Extension in order to provide fill iOS 12 Password API functionality to the users. I cannot do that since I'm not part of the development team. Please see Slack starting with [this message](https://netnewswire.slack.com/archives/CCGTPJDPD/p1583783675130500) to get a more in-depth view into the issue.

**Comment by flowinho** [comment]
Update: I made a misinterpretation. We most likely don’t need the password api extension as that is solely for apps that _provide_ credentials rather than _accept_ them.

That’s bad news, since this would mean it is not possible to implement this in satisfactory way.

**Comment by vincode-io** [comment]
Thanks for giving it a shot.
