### ISSUE TITLE
iOS: zoomed image title view should have a limited width

### ISSUE THREAD

**Issue by vincode-io** [Ranchero-Software/NetNewsWire#1855]
We need to limit how wide this label is so that when viewed in the iPad it is more readable.

**Comment by flowinho** [comment]
Can explain a bit more on this? I'm confused about what is actually meant.

**Comment by vincode-io** [comment]
If you look at the zoomed image code that triggers when you tap an image in the article view, you can see that we have a label along the bottom of the image.  This label is populated using the title attribute of the image element from the article.  Pretty much the only time you see this label is when you zoom the comic from the XCKD.com website feed.  You will want to subscribe to this feed for testing.

The title label is currently the full width of the controller view. We should restrict the label width, while keeping it centered on the bottom.   This will make it more readable on iPads when the image is zoomed and taking up the full device size.

**Comment by flowinho** [comment]
Alright - I can fix this. @vincode-io Can you assign this to me?

**Comment by vincode-io** [comment]
Done.
