### ISSUE TITLE
Adding feed with "ä" in the URL doesn't work

### ISSUE THREAD

**Issue by johanthebiologist** [Ranchero-Software/NetNewsWire#1862]
Trying to add https://västkustinvesteraren.se/ in the macOS app (Version 5.0.3 (2618)).
Nothing happens when I click add.
When I use the Want My RSS extension in Firefox to manually find the feed address, it showed https://xn--vstkustinvesteraren-gwb.se/feed/, which worked fine in NetNewsWire.

**Comment by Wevah** [comment]
Looks like the feed linked here updated the URLs it uses inside of itself to use the alread-encoded versions, so I can't test some of the link breakage anymore.

**Comment by Wevah** [comment]
(Though I imagine most feeds would just specify root-relative URLs for favicons, etc.)

**Comment by vincode-io** [comment]
This has been fixed and is coming in an upcoming 5.1 release.
