### ISSUE TITLE
Article view blank when returning after switching to another app

### ISSUE THREAD

**Issue by willhains** [Ranchero-Software/NetNewsWire#1863]
After switching to another app and returning to NNW, the article view (rightmost view) is blank. The selection state of the feed and post lists is maintained, but tapping again on the currently selected post list doesn’t work. Tapping on a different post in the post list restores the article view, but obviously that toggles the read status of that other post.

This has happened a couple of times, but not every time.

**Comment by Purpleistacky** [comment]
Happens almost every time with me as well. Especially annoying when reading a long article, it refreshes it back to the top, once you get rid of the blank view. 

iPad Pro 2018, 13.3.1

**Comment by vincode-io** [comment]
Could you confirm that the article view is blank, but has the words "No selection" in it?  I think I fixed this, but want to verify.

**Comment by vincode-io** [comment]
I'm pretty sure I got this one working.  Let me know if anyone finds a truly blank article and not one that says "No selection" in it and I will reopen this issue.
