### ISSUE TITLE
iOS: Please support older iOS versions

### ISSUE THREAD

**Issue by nmatt** [Ranchero-Software/NetNewsWire#1866]
Please support older versions of iOS. I'm still using an iPhone 6 pn iOS 11 and an iPad 4 on iOS 10. It would be great to be able to use NetNewsWire on hose.

**Comment by brentsimmons** [comment]
I hate having to break bad news, but I have to be honest — we won’t be supporting older versions of iOS.

Supporting older versions is a *lot* of work, and that work would take away from us adding the important features that NetNewsWire users are asking for.
