### ISSUE TITLE
iOS feature requests: Fonts & Read items filter

### ISSUE THREAD

**Issue by rodney-topor** [Ranchero-Software/NetNewsWire#1867]
Just installed on my iPad and synced with my Feedly account.  All went very smoothly.  Very familiar interface for this Reeder user.

Requests:
1. Ability to apply read items filter to all feeds and not only to each feed separately.

2. Ability to display one-line item heading (middle panel) in regular font not bold font.  Bold font makes it seems like the app is shouting at me.

**Comment by vincode-io** [comment]
Thanks for the suggestions. We feel that per feed article filters are very useful and would like to keep them. As for the bold font, it is important that we keep that so that it is possible to differentiate between title and summary text in the timeline. 

I’m sorry that we can’t help you more.
