### ISSUE TITLE
Feature Request: Load full stories by default

### ISSUE THREAD

**Issue by impaler80s** [Ranchero-Software/NetNewsWire#1874]
Glad to see this now out for iOS. The only thing keeping me from moving to NNW full time is that I have to tap/click to load full articles every time I open something. If I open it, I want to read the full article. I realize this may be done to keep things lightweight, but using Feedbin with Reeder, I can set this by feed. It’s a must for me. Perhaps others?

**Comment by brentsimmons** [comment]
You can set this on a per-feed basis.

Will that do the trick for you?

**Comment by impaler80s** [comment]
Sure will! Is this function available on MacOS? And does the per feed setting sync?

--
Brian Hippel
brian@hippel.us

**Comment by brentsimmons** [comment]
In general, the two apps will have feature parity — except that one may be ahead of the other sometimes, like now.

(In other words — the Mac app doesn’t have this feature yet.)

We haven’t even thought about making that setting sync.

**Comment by brentsimmons** [comment]
This is basically a request for Reader view on macOS, which is coming, so I’ll close this.
