### ISSUE TITLE
Feedly account setup button doesn't show up on macOS

### ISSUE THREAD

**Issue by matteoprata** [Ranchero-Software/NetNewsWire#1875]
Hello, in the macOS Version 5.0.3 I can't manage to set up my Feedly account since the button doesn't show up, as shown in the screenshot below of the preferences window.

<img width="624" alt="Schermata 2020-03-11 alle 09 10 41" src="https://user-images.githubusercontent.com/18751574/76396219-1142bb00-6379-11ea-8c61-7348a27ba5d8.png">

**Comment by kielgillard** [comment]
Hello @matteoprata, Feedly integration for macOS will be [shipping in version 5.1](https://ranchero.com/netnewswire/frequently-asked-questions). Thanks for taking the time to reach out — it’s good to know how much interest there is!
