### ISSUE TITLE
Article Theming

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#19]
Define and document theme package. Create shipping themes. Make theme popup work in toolbar and in prefs. Handle double-click to install theme package.

**Comment by brentsimmons** [comment]
To be clear: this is for the detail view.

**Comment by davidbgk** [comment]
I would love to make a custom theme (most notably for a bigger font size), would it be based on CSS?

**Comment by brentsimmons** [comment]
Yes — the article view will be themeable via CSS.

**Comment by fannar** [comment]
> Yes — the article view will be themeable via CSS.

Really looking forward to this. Would be nice to have sepia for articles and fix headings.

**Comment by davidbgk** [comment]
Since version 6.0, we already can change the font size, which is awesome 🙇

**Comment by brentsimmons** [comment]
Stylesheets from NNW of yore
[StyleSheets.zip](https://github.com/Ranchero-Software/NetNewsWire/files/6664671/StyleSheets.zip)

**Comment by vincode-io** [comment]
This has been implemented and will be in the 6.1 release.
