### ISSUE TITLE
Failed to log in if password includes "&="

### ISSUE THREAD

**Issue by quanganhdo** [Ranchero-Software/NetNewsWire#1903]
My password happens to include "&=" and this adds an unexpected Name-Value pair to the post body.

https://github.com/Ranchero-Software/NetNewsWire/blob/229aada857ccd682ca2f0c89fe25036d96f2bd77/Frameworks/Account/Credentials/URLRequest%2BRSWeb.swift#L39

I'm doing something like this for my NewsBlur implementation:

```
var postData = URLComponents()
postData.queryItems = [
	URLQueryItem(name: "username", value: credentials.username),
	URLQueryItem(name: "password", value: credentials.secret),
]
httpBody = postData.percentEncodedQuery?.data(using: .utf8)
```

**Comment by brentsimmons** [comment]
RSWeb thing. Assigning to @Wevah.

**Comment by Wevah** [comment]
Using `URLQueryItem` is definitely the route to take. Filing a companion bug over on RSWeb.

**Comment by Wevah** [comment]
Huh, that file has deviated from the one in the RSWeb project proper.

**Comment by vincode-io** [comment]
Removing from the iOS 5.0.1 milestone since the NewsBlur work is happening on the master branch and is unrelated to the iOS release.

**Comment by Wevah** [comment]
This isn't related to NewsBlur!

**Comment by Wevah** [comment]
@quanganhdo What service does this happen under?

**Comment by vincode-io** [comment]
Oh, I see what you are saying.  He just noticed a bug in the ReaderAPI implementation while working on the NewsBlur implementation.  Regardless, this work should be happening on master, not ios-release.

**Comment by Wevah** [comment]
Agreed.
