### ISSUE TITLE
View > Clean Up

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#1912]
The command will be selectively enabled. It would be enabled when in a folder, in All Unread, or when the unread-only filter is on.

This command will have the keyboard shortcut cmd-shift-H.

(The above all matches earlier versions of NetNewsWire.)

The idea is that you shouldn’t have to do a refresh just to clean up.

**Comment by vincode-io** [comment]
We already created that menu item (not the shortcut key tho). It enables and disables the article read filter.

**Comment by brentsimmons** [comment]
Ah. Nuts. Okay.

Let’s call it “Clean Up” instead.

**Comment by vincode-io** [comment]
On iOS 5.0.1 the refresh command clears both read feeds and read articles. Should Clean Up do the same and clean up both the sidebar and timeline?  If so, we would want it enabled all the time.

**Comment by brentsimmons** [comment]
Yes — it should clean up the sidebar and the current timeline.

There is a case when it shouldn’t be enabled, though. If the unread filter is off, and you’re viewing an individual feed or Today or Starred, then Clean Up should not be available because it wouldn’t do anything.

**Comment by vincode-io** [comment]
If the article read filter is off, but the Feed read filter is on, we would still want to be able to clean up the sidebar I think. 

But you are right, there is a scenario where it should be disabled. If both read filters are off. Then nothing could be cleaned up.

**Comment by brentsimmons** [comment]
Perfect.

**Comment by vincode-io** [comment]
Should the new menu item / keyboard shortcut impact all open windows or just the foremost window?

On iOS, the refresh clears all windows since refresh is an application level command.  

It seems to me that Clean Up may get a toolbar icon someday and that in that case, it may just be expected to impact the window with the toolbar icon.  Keyboard shortcut and menu item should behave the same I think.

**Comment by brentsimmons** [comment]
Yes — it just impacts the frontmost window.
