### ISSUE TITLE
macOS: Reader View Support

### ISSUE THREAD

**Issue by Swordee** [Ranchero-Software/NetNewsWire#1917]
Not an issue, but rather a feature request.

It would be great if the macOS app had Reader View support. Many articles have quite poor RSS support, so reader view makes it extremely easy to view the whole article without leaving the app. This feature would be it a lot easier than having to open the article in a web browser.

**Comment by vincode-io** [comment]
We completely agree and it will be part of the upcoming 5.1 release of NetNewsWire for Mac.  I'm closing this issue because we are tracking it elsewhere (I just can't find it right now.)
