### ISSUE TITLE
iOS: Cells should be sized according to their content 

### ISSUE THREAD

**Issue by vincode-io** [Ranchero-Software/NetNewsWire#1919]
It looks like this is a regression caused by fixing the empty row height. 

![D2A0E25C-95F4-4D6D-B75D-D15DF5010D24](https://user-images.githubusercontent.com/16448027/76716826-9aeae380-66ff-11ea-9be5-69a2dc37ee62.png)

**Comment by flowinho** [comment]
Awesome catch!

@vincode-io This is most likely due to the `calculateEstimatedRowHeight` not using the custom layout code that was inserted to fix the row layout when no title / no description where present!

**Comment by vincode-io** [comment]
@flowinho, if you are too busy to get to this, I can take it.

**Comment by flowinho** [comment]
Sure, I’m currently busy. Feel free.
