### ISSUE TITLE
Make the unread filter on iOS more obvious in onboarding

### ISSUE THREAD

**Issue by jasikpark** [Ranchero-Software/NetNewsWire#1922]
I was about to make a feature request for an unread filter a la what you can get via Feedbin or Unread 2 on iOS. 

But it seems that's what the top right button does? I only just now discovered it 😅 

Is there a way it could possibly be better communicated?

**Comment by vincode-io** [comment]
It is the same filter button used by Mail.app to filter read emails.  That usually helps people figure it out (and you did figure it out). 

Are you suggesting we walk the user through the user interface on first use?  I find those kinds of tutorials pretty annoying myself.

**Comment by jasikpark** [comment]
I'm not sure? I've been using the app on beta for about 2 months, and I was disappointed about the lack of the feature until I finally figured it out.

I agree with your disdain for lengthy app tutorial, but maybe just a simple popup tooltip near the beginning of downloading the app? Or maybe just include the description in a help section of the settings?

**Comment by vincode-io** [comment]
One thing we would like to do is make it easier to figure out what the buttons do by displaying a HUD or tooltip when you long press them. Do you think you would have found the read filter sooner if we had had that option?

**Comment by jasikpark** [comment]
Hmm... I think that's a good idea, but I'm not sure whether I would assume that was an option. 

It's definitely a good idea though, and should help marginally. This is the only app I use that utilizes that icon since I use Airmail for email; 

I think probably just that + documentation of features accessible via the website would work best maybe? I figured it out by searching through Github issues for mention of unread filters.

**Comment by vincode-io** [comment]
We have it documented in the help book that you can access from the Settings. https://ranchero.com/netnewswire/help/ios/5.0/en/filters

**Comment by jasikpark** [comment]
Sweet! So then yeah, that would probably be good to just add a "on focus"-esque label

**Comment by jasikpark** [comment]
Is there a similar feature in the macOS version yet? Or is that still on the roadmap?

**Comment by vincode-io** [comment]
It will be coming in the Mac 5.1 release. Keep watching the project. We’ll be needing beta testers for it soonish. 

Thanks for helping beta test the iOS app and reminding us we need to keep trying to make the buttons more discoverable.
