### ISSUE TITLE
Double quote marks in folder names get re-written as &quot; after app relaunch

### ISSUE THREAD

**Issue by slater** [Ranchero-Software/NetNewsWire#1924]
If you have a folder name that contains double quote marks, they will get rewritten as &-quot; after closing the app. Editing them keeps them as double quote marks, but closing and relaunching the app will have them back to &-quot; (the hyphen after & is only for this bug report, Github helpfully turns those into actual ""s)

**Comment by vincode-io** [comment]
@slater, I'm only able to recreate this on Mac 5.0.3.  Could you please verify if this is the release you are using?

**Comment by slater** [comment]
Can confirm. I only use NNW on desktop, and I'm on 5.0.3

**Comment by vincode-io** [comment]
Since I can't recreate this on iOS and only can on Mac 5.0.3, I'm moving this to Mac 5.0.4.

**Comment by vincode-io** [comment]
This is fixed and will be released in Mac 5.0.4.
