### ISSUE TITLE
Smart Feeds should have updated icons

### ISSUE THREAD

**Issue by vincode-io** [Ranchero-Software/NetNewsWire#1926]
Here is a rough mockup of NNW with an idea of what we could use.

![Screen Shot 2020-03-18 at 5 40 47 PM](https://user-images.githubusercontent.com/16448027/77014878-433bba80-6941-11ea-8f0a-259e956bab23.png)

**Comment by thienlh** [comment]
I like it, they look great and match the style of the toolbar icons 👍

**Comment by vincode-io** [comment]
I think this should be moved to 6.0 when we do the visual refresh.

**Comment by vincode-io** [comment]
I think we can just us the same SF Symbols that are in the mockup now that we are targeting this change for the Big Sur release.  I'm calling this one done.
