### ISSUE TITLE
NetNewsWire for Mac should use NNW blue instead of system accent color

### ISSUE THREAD

**Issue by vincode-io** [Ranchero-Software/NetNewsWire#1930]
When you use the system blue accent color in light mode on the Mac, it looks pretty decent.  Switch to darkmode and the system blue is off compared to the NNW blue we use in darkmode.  Use any other system accent color besides gray, and things look real weird.

On iOS we use a NNW blue for our accent color.  I think it makes the NNW UI look more cohesive when the unread indicators and cell selection state color match the color used in the article view.

**Comment by vincode-io** [comment]
Before:

![Screen Shot 2020-03-19 at 8 20 27 AM](https://user-images.githubusercontent.com/16448027/77073760-c1d63d80-69bd-11ea-9322-c635c1b1a5fa.png)

After:

![Screen Shot 2020-03-19 at 8 42 48 AM](https://user-images.githubusercontent.com/16448027/77073776-c864b500-69bd-11ea-84bc-85e06e014497.png)

**Comment by brentsimmons** [comment]
On my machine I use a non-blue accent color. Is it possible to detect when it’s set to blue and then use a different color only in that case?

For reference, here’s my machine:

![Screen Shot 2020-03-19 at 3 23 21 PM](https://user-images.githubusercontent.com/1297121/77120296-bd2d7b80-69f5-11ea-8e2d-6f980efd21f5.png)

**Comment by vincode-io** [comment]
I don't think I can reliably detect the blue.  I could hard code the RGB values, but they might not be the same between OS releases.

I was suggesting that we ignore the accent colors all together, but I now see that isn't very Mac like.  Instead, maybe embracing the accent colors a little more is what is needed to stop the clashing colors between the table view selections and the article?

![Screen Shot 2020-03-19 at 6 25 19 PM](https://user-images.githubusercontent.com/16448027/77123907-6b91ea80-6a0f-11ea-976d-424110902685.png)

![Screen Shot 2020-03-19 at 6 33 45 PM](https://user-images.githubusercontent.com/16448027/77124196-36d26300-6a10-11ea-9458-d26ff3f47f29.png)

I'm not completely sold on the idea though.

**Comment by vincode-io** [comment]
The coloring looks like a bit much in the examples I gave.  It would be better if didn't have the article title in the accent color.  I'll mock that up real quick.

**Comment by vincode-io** [comment]
I think this might work.

![Screen Shot 2020-03-19 at 6 43 49 PM](https://user-images.githubusercontent.com/16448027/77124713-a432c380-6a11-11ea-9406-e1913c04be52.png)

![Screen Shot 2020-03-19 at 6 43 58 PM](https://user-images.githubusercontent.com/16448027/77124720-a9900e00-6a11-11ea-92e8-7e7ff504c147.png)

**Comment by brentsimmons** [comment]
I can see removing the blue from the title. I’m not sure about using the accent color for other links. That might be more orange than I actually want.

But maybe not?

I’ll think about this some more.

**Comment by vincode-io** [comment]
I pushed the code to a feature branch so that you could try it out with different colors and see if it grows on you.  The branch is `accent-color-experimental`.

We might be able to tone down the accent color in the article view if it is too distracting.  We could increase brightness or decrease brightness.

**Comment by vincode-io** [comment]
Here are some screenshots where we lighten the accent color 25% in dark mode and darken it 25% in light mode.  This decreases the amount of contrast between the links and regular text, making it pop out less at the user.

![Screen Shot 2020-03-20 at 8 12 06 AM](https://user-images.githubusercontent.com/16448027/77167037-42ab3d00-6a83-11ea-94a2-e5271b35ff28.png)

![Screen Shot 2020-03-20 at 8 12 17 AM](https://user-images.githubusercontent.com/16448027/77167051-48088780-6a83-11ea-80b8-f9ade70ff101.png)

It seems to do a decent job of toning even the most garish of accent colors.

Code is in the repo if you get time to check it out.

**Comment by vincode-io** [comment]
Opacity of the article accent color is currently set at 75%.  You can mess with that in the CSS file to change how much the accent color pops.

**Comment by vincode-io** [comment]
This has been implemented.  We can open another issue if we don't like how it as done.
