### ISSUE TITLE
Enhancement Request: The way to enable “Always Show Reader View”

### ISSUE THREAD

**Issue by lkvnclh** [Ranchero-Software/NetNewsWire#1931]
**Scenarios:**
Currently I need to go through each of the feed by following steps:
“Go to feed” > Click the feed > “enable “Always Show Reader View”
 I may have hundred /thousand of active feed..which cause a lots of traffic to enable “Always Show Reader View” feed by feed.

**Enhancement Request:**
Would it be possible add another option to activate “Always Show Reader View” right from the article , say long pressing the “Reader view” icon to show prompt-up to select feed to ““Always Show Reader View”

Borrow some concept from “Reeder” here:
![image](https://user-images.githubusercontent.com/23471942/77128834-a25a1600-6a8c-11ea-996c-19d5b0c01ff6.png)

**Comment by VirrageS** [comment]
I would also to have this feature. For now I’ve been using Feedly just for the reason it has the setting that always to activate reader view for all the articles. It works great and it would be super nice to have that in the NetNewsWire as well.

![96F04931-5701-4B42-8191-EEA22DDDD776](https://user-images.githubusercontent.com/3855799/77801513-4dfcfa80-7079-11ea-8bc5-6a572d477118.jpeg)

**Comment by vincode-io** [comment]
@VirrageS That isn't the same thing as our Reader functionality.  That just automatically turns on *Safari's* reader functionality when you go to a website.  With ours you don't have to go into Safari at all.  Ours will actually replace the RSS article with the website extracted one if you configure it to do so in the Feed Inspector.

**Comment by VirrageS** [comment]
Yeah, I understand but basically it does the same thing - show just the text with images. It would be just nice to have the global option as well.

**Comment by vincode-io** [comment]
We feel that a global option provides an inferior user experience.  When the Reader view executes, it has to go to the website and try to extract the text from the webpage which it may or may not be able to do.  Regardless, it has to make a web request to get the data.

This is both slower and less accurate than the article provided by the RSS feed itself in most cases.  That is why we provide it on a per feed setting and probably won't ever do this as a global setting.

However we could make it easier for you to toggle the setting on for each feed.  This is something we are looking into and may provide in a future release.

**Comment by phylaxis** [comment]
Would you consider just adding a keyboard shortcut to toggle your Reader view on and off?

**Comment by vincode-io** [comment]
We've added the option to click the Feed Icon in the Article View to get the Feed Inspector.  This allows you to toggle the Always Show Reader View for the feed without having to go back to the Feed List.

**Comment by vincode-io** [comment]
@phylaxis I wrote your request up as issue #2029. You can follow it for updates.
