### ISSUE TITLE
Sharing on iOS should share both title and URL

### ISSUE THREAD

**Issue by ahockley** [Ranchero-Software/NetNewsWire#1932]
When sharing an article from NewsBlur to another iOS app via the share sheet, it appears only the URL is being shared.  In many (most?) cases it would be nice to share both the title and URL.

Specific use case: sharing to the Buffer app which allows someone to add articles to a social media posting queue, it would be great to pull in both the title as well as the URL.

**Comment by manuelgrabowski** [comment]
Counter-point: I absolutely hate it when I want to share an URL and more than the URL is shared. I've spent way too much time to remove redundant titles from iMessage drafts in the share sheet before sending the URL. iMessage (and Twitter as well) show previews for URLs, I don't see the need to duplicate the title again.

**Comment by uncleungie** [comment]
Unread for iOS used to include a summary with with the URL, but wisely removed this behavior. Please don’t add this.

**Comment by vincode-io** [comment]
We currently only show the title in the stare sheet on an exception basis.  Right now only Things and OmniFocus get the title shared.  These are TODO apps and it makes sense to share them there.

I think the question is if we think Buffer should be added to the exception list and have the title shared to it as well.

**Comment by ahockley** [comment]
That's good to know that it's conditional by app.  I also noticed while attempting to share to Tweetbot yesterday that it didn't share the title, which would likely be preferable there as well.

**Comment by vincode-io** [comment]
I think what we want to do with this one is to share the title along with the URL when sharing to Buffer and Tweetbot.

**Comment by ahockley** [comment]
@vincode-io That seems reasonable.  I would say that categorically when sharing to a Twitter-specific app, sharing the title would be desired.  In addition to Buffer and Tweetbot, I would recommend adding Twitteriffic and the native Twitter app to that list.

**Comment by manuelgrabowski** [comment]
I can only repeat what I said above – why would you want to repeat the title, which Twitter will show in their preview anyway? I'm a Tweetbot user myself, I realize that they don't show URL previews like the official app and website, but for 99,9% of Twitter users you'll just make them read the same information twice, waste characters in which you could say something personal about the content. To me, tweets that repeat the title of an embedded URL basically look like SEO spam and make me think the author doesn't really understand the medium.

**Comment by vincode-io** [comment]
This has been changed and is coming in NNW for iOS 5.0.2.
