### ISSUE TITLE
Feedly account remembers Google credentials after deleting

### ISSUE THREAD

**Issue by rlb222** [Ranchero-Software/NetNewsWire#1933]
In iOS 
I added a feedly account with google credentials. I then saw I choose the wrong google account. 

I went to credentials, in case of the  feedly account it doesn’t show much. Only delete. (The manual said I would see credential information in that screen)

So I deleted the account. 
Added a new feedly account, google login. And I didn’t need to specify an account. It choose the previous wrong account. Without login etc. 

I stopped and started NetNewsWire but no reset of the google cached account. 

Summary
I want to add a feedly account with a new/another google account-credentials after I have already logged into a feedly account with google credentials.

**Comment by rlb222** [comment]
It’s a feedly problem I think, I have the same problem on de feedly website now, where I can’t figure out how to switch accounts.

**Comment by kielgillard** [comment]
NNW delegates the Feedly log in process Safari so you don’t need to enter passwords etc again. Can you log into both, say, gmail accounts in Safari?

You should get a choice of account when adding a Feedly account if you’ve used safari to log into your Google accounts before.

**Comment by rlb222** [comment]
Correct. On an iPad. Not on my iPhone 6s I found out. On the iPhone 6s i don’t get a choice. I’m still thinking of a way to correct this. 
Thks for the answer.
