### ISSUE TITLE
Adding same URL after a "Feed not found" error does not generate new request

### ISSUE THREAD

**Issue by abilops** [Ranchero-Software/NetNewsWire#1935]
The "Feed not found" error repeats, without actually trying again. 
# Steps to reproduce
1. Try to add the feed
<img width="720" alt="Screenshot 2020-03-21 at 20 06 29" src="https://user-images.githubusercontent.com/20786355/77228753-7edbbc00-6baf-11ea-88d3-20b32bb777da.png">

2. The request must go through fine but the file returned must not be a valid feed.
<img width="790" alt="Screenshot 2020-03-21 at 20 12 52" src="https://user-images.githubusercontent.com/20786355/77228891-628c4f00-6bb0-11ea-9f79-779702d17146.png">

3. An error pops up saying "Couldn't add feed because no feed was found"
<img width="864" alt="Screenshot 2020-03-21 at 20 40 16" src="https://user-images.githubusercontent.com/20786355/77229473-3c68ae00-6bb4-11ea-846d-d82b9c9fd63e.png">

4. Now try adding the same feed again, and the error dialogue will reappear (without the progress bar window preceding it as before). Proxyman does not log another request.

5. The app *remembers* the fact that no such feed existed at that URL, until it is restarted. It does that for every URL for which the request was completed but the feed wasn't found.

# Expected behaviour
The request should be carried out every time the user taps/clicks "Add", regardless of any previous responses.
This makes a difference wherever an invalid feed is returned some, but not every, time. For example, while debugging feed generators or maybe when a CDN has cached an invalid feed.
Some ISP's like to inject trash into HTTP responses, which may also trigger the error the first time. The next request might come through untouched, but the only way to try again is to relaunch the app.

**Comment by Wevah** [comment]
My guess is it’s due to `URLSession`’s caching behavior.

**Comment by brentsimmons** [comment]
We also have a cache. I haven’t looked at the code — we should make sure it’s not our cache that’s the problem here.

**Comment by abilops** [comment]
Looks like the function [`find(url:completion:)`](https://github.com/Ranchero-Software/NetNewsWire/blob/ef6a79489ade1f315bea4403c92fcfe3f2a3a145/Frameworks/Account/FeedFinder/FeedFinder.swift#L16) calls `downloadUsingCache(url)`. I don't have a lot of knowledge about how the whole app is put together, but it looks like `find` is called only when a feed is added. If that is so, why do we need to use the cache while adding the feed?
It appears that replacing that call with just `download(url)` and touching nothing else solves the problem, but I am not sure that is the right approach since it might have some unwanted consequences.
What do you think?
