### ISSUE TITLE
Small header view at top of timeline for turning on/off read-articles filter

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#1937]
This should emulate the corresponding header in Mail. Filter button on right, with text showing as needed.

Instead of a sort-by menu like in Mail, do a similar popup but showing sort order with an additional option for grouping by feed.

Newest to Oldest
Oldest to Newest
[separator]
[checkmark] Group by Feed

Importantly: the text shown in the popup when it’s at rest is one of the first two items.

**Comment by vincode-io** [comment]
In the menu options use 

Newest Article on Top
Oldest Article on Top

Do we want to change these to be the same or more similar?
