### ISSUE TITLE
Background refresh not working (iOS)

### ISSUE THREAD

**Issue by pineappleburger** [Ranchero-Software/NetNewsWire#1948]
App doesn‘t refresh in the background. (iOS 13.3.1, Background refreshing is turned on for the app in system settings.) App works perfectly fine otherwise, I hope it‘s not an error on my part.

Thanks!

**Comment by vincode-io** [comment]
How long have you had the app installed and are you using it regularly?

iOS uses machine learning to determine when background app refreshes can happen. The less you open the app, the less frequently or not at all, background refreshes happen.  Fresh installs also take some time to train the system on when background refreshes should be happening.

**Comment by pineappleburger** [comment]
I use the app quite often but I did only install it two weeks ago. Sounds like I’ll just have to wait and see.

Thank you for your help!

**Comment by vincode-io** [comment]
You probably should be seeing background refreshes happening by now, especially if you use the app a few times per day.  I'm a little bit concerned that you aren't seeing them happen.

Another thing that can impact refreshes is if you have a very large number of feeds and/or are on a low bandwidth connection.  Apple only gives us 30 seconds to complete the sync.  That can mean that syncs won't be able to complete.  That can mean that the sync will have to start over when you next launch the app.

Do get back to us if you don't see any improvement.

**Comment by pineappleburger** [comment]
I tried to find out whether it has anything to do with the number of feeds and deleted all feeds but one for the past few days: There don’t seem to be any background refreshes happening tho, still. Only when I open the app I get the notifications I activated for the feed. 

What do you think? 🤔

**Comment by vincode-io** [comment]
Could you let me know which kind of account are you using?  I’m going to try to recreate the same environment you are using. What is the feed you are trying to get notifications for?

**Comment by pineappleburger** [comment]
I was using this feed because it has new content fairly often:
http://feeds.bmj.com/bmj/recent?format=xml

I wasn’t using any other account, I added the feeds manually on my phone. Is that a problem?

**Comment by vincode-io** [comment]
I just wanted to know if you are using the On My Phone account or were using Feedly or Feedbin.

**Comment by vincode-io** [comment]
Could you add the below feed and enable notifications on it?  It has a crazy amount of articles and we should be able to see if background refresh is working or not with it. 


http://feeds.washingtonpost.com/rss/homepage

**Comment by vincode-io** [comment]
The other question I have is, do you slide the app off the top of the screen when you quit it or do you just leave it?

**Comment by pineappleburger** [comment]
I replaced the BMJ feed with the feed you suggested and enabled notifications. The feed takes surprisingly long to load, approx 20s? I only use the On My Phone account.

I normally quit the app like you described... I resisted that urge at least partly for the past few days, I now have the app running in the background.

**Comment by pineappleburger** [comment]
It works now! Seems like I was the culprit for quitting it... I’ll try if it still works with my full list of rss feeds.

Naive question: Is it only supposed to work while not quit?

**Comment by vincode-io** [comment]
It does work when you quit, but not when you force quit which is what you were doing.  Force quitting is a last resort if you are having problems with an application freezing up or you get it stuck somehow.  If you force quit, iOS thinks there is something wrong with the app and won't launch it in the background.  That is why you weren't seeing background syncing and notifications happen.

It is a common misconception that force quitting saves you battery life or resources.  This couldn't be farther from the truth.  If you just leave the app alone and move on to the next app, iOS suspends the app.  This means it no longer is using battery or memory or any other resources.  It actually takes more resources to launch an app after it has been force quit than if you just had let it suspend and unsuspend itself.

**Comment by pineappleburger** [comment]
Ok, thanks for your help! Really learned something there...

For anyone that might stumble across this:
![6BCC1098-2CD1-42D0-85BF-76C639552A92](https://user-images.githubusercontent.com/50545687/77939930-2b0c5980-72b8-11ea-889a-90112e5978ed.png)
(from an old version of Apple’s app programming guide at https://thehustle.co/stop-force-quitting-your-iphone-apps)

**Comment by Genesis0x1b** [comment]
> It does work when you quit, but not when you force quit which is what you were doing. Force quitting is a last resort if you are having problems with an application freezing up or you get it stuck somehow. If you force quit, iOS thinks there is something wrong with the app and won't launch it in the background. That is why you weren't seeing background syncing and notifications happen.
> 
> It is a common misconception that force quitting saves you battery life or resources. This couldn't be farther from the truth. If you just leave the app alone and move on to the next app, iOS suspends the app. This means it no longer is using battery or memory or any other resources. It actually takes more resources to launch an app after it has been force quit than if you just had let it suspend and unsuspend itself.

Yes, you are right. But sometimes people may accidentally close the application as a habit. It would be great if you add support for notifications like many other iOS apps support even if they are forcefully closed.
