### ISSUE TITLE
U+2122 (trademark symbol) displayed much larger than surrounding text

### ISSUE THREAD

**Issue by jralls** [Ranchero-Software/NetNewsWire#1958]
The text: TheGenealogist has released the Colour Tithe Maps for Essex with full integration with its MapExplorer™. This release allows us to 

NetNewsWire's render:
<img width="408" alt="Screen Shot 2020-03-30 at 9 06 59 AM" src="https://user-images.githubusercontent.com/58910/77935191-fb346600-7265-11ea-9c75-c159e8ca6f54.png">

MacOS 10.15.4
MacBook Pro 13" Retina 2014

**Comment by vincode-io** [comment]
I think we have a fix for this in an upcoming release.  Could you please supply me with the URL of the feed you are using so that I can verify it?

**Comment by jralls** [comment]
Sure, it's https://blog.eogn.com.

**Comment by vincode-io** [comment]
That is fixed in the upcoming 5.0.4 release.  That is actually an image from word press.  We've implemented a custom style for that which makes it the correct size.  Thanks for the report!

**Comment by jralls** [comment]
Wouldn't make  more sense to just let CoreText render it?

**Comment by vincode-io** [comment]
It is an inline image we receive, not `U+2122`.  Wordpress changes it when it generates the RSS feed.

**Comment by jralls** [comment]
That's rude of them. Is there a WordPress bug report?

**Comment by vincode-io** [comment]
Dunno. They do the same thing with emojis. I’m sure they consider it a feature, but we don’t much appreciate it.

**Comment by jralls** [comment]
I didn't find one in their trac, so https://core.trac.wordpress.org/ticket/49730#ticket.
