### ISSUE TITLE
Feature Request: Next unread button on home screen

### ISSUE THREAD

**Issue by specter78** [Ranchero-Software/NetNewsWire#1961]
There should be a next unread button on home screen. Moreover the button should be on bottom right to bring consistency (as within feed, it is on bottom right). The add feed button can be moved to the centre.

**Comment by vincode-io** [comment]
We love the next unread function and would like to put it everywhere.  Unfortunately the UI is about as full as we can make it without it being cluttered.  Besides, where would the status indicator go if we put the Add button in the middle of the toolbar?

Did you know that you can go straight to the First Unread without even going to the home screen?  Just long press the application icon to get the context menu.

![IMG_0524](https://user-images.githubusercontent.com/16448027/78134329-93a52480-73e5-11ea-8f3b-a6e578720d70.png)
