### ISSUE TITLE
Keyboard shortcuts not revealed when bluetooth pointing device connected

### ISSUE THREAD

**Issue by RosemaryOrchard** [Ranchero-Software/NetNewsWire#1963]
I just discovered that if you have a "bluetooth pointing device" connected to your iPad (iOS 13.4), then pressing and holding CMD does not reveal a list of keyboard shortcuts as you would expect. But on another iPad without a mouse connected - it does.

**Comment by karan301** [comment]
Not sure if I’m seeing the same or a similar issue but, with a trackpad connected, I often switch to NNW and no keyboard input is recognized (thus holding ⌘ doesn’t populate the shortcuts sheet). However, if I click on any item on screen (like the Search bar) everything starts to work as expected — until I leave the app and return, that is.

**Comment by vincode-io** [comment]
I was able to verify that the command overlay is erratic when a bluetooth pointing device is attached.  I could sometimes get it to come up by pressing command a second time and holding it again, but not always.

The other thing I was able to verify was that we were getting keyboard events for our command shortcuts.  That means that we aren't losing keyboard focus, which is what I thought was possibly happening.

We don't have any API to interact with the keyboard overlay directly.  Indirectly, we register that we have keyboard shortcuts and iOS handles the rest.  This includes when to show the overlay.

I'll keep my eyes open for anything we can do to resolve this, but right now I am at a loss.

**Comment by ssgelm** [comment]
I am having the same experience as @karan301.  When I first switch back to the app no keyboard input of any kind works but it starts again upon clicking on anything.  This is using the Magic Keyboard so there is a trackpad connected (though not via bluetooth).  It’s possible this is a bug in iOS but I haven’t observed this behavior in any other app.

**Comment by vincode-io** [comment]
I've got this issue addressed.  Please verify for me that is has been resolved when we put out the next TestFlight build.  Thanks!

**Comment by karan301** [comment]
Preliminary testing on a handful of iPads looks good. Haven’t been able to reproduce with the current TestFlight 5.0.1 build (43). Checked with Magic Keyboard case as well as standalone Magic Keyboard and Trackpad over Bluetooth. 👍🏽

**Comment by vincode-io** [comment]
@karan301 Thanks for the thorough test!

**Comment by ssgelm** [comment]
This is resolved for me as well!
