### ISSUE TITLE
Mac: HTML rendered from an article title

### ISSUE THREAD

**Issue by mttlmnt** [Ranchero-Software/NetNewsWire#1964]
<img width="1353" alt="image" src="https://user-images.githubusercontent.com/8701480/78301793-1c62c280-7596-11ea-82db-804696ada005.png">

It's a bit surprising.

I'm not sure if this is expected behaviour.

**Comment by Wevah** [comment]
Definitely not intended, as far as I’m aware! Can you add the URL of the post?

**Comment by vincode-io** [comment]
The URL is https://lobste.rs.  Here is the title element pulled up in the debugger incase that article rolls off.

![Screen Shot 2020-04-02 at 4 40 03 PM](https://user-images.githubusercontent.com/16448027/78304509-8894e600-7504-11ea-876d-2ad71099fed3.png)

**Comment by brentsimmons** [comment]
There’s an ambiguity in the RSS spec about this.

What if, instead, the title contained an <i> tag? You’d probably want it to make the thing italic.

The answer is, probably, to let some HTML through as HTML and escape everything else.

**Comment by Wevah** [comment]
I'd go for whitelisting tags like `i`, `b`, `strong`, `em` and disallowing everything else.

**Comment by Wevah** [comment]
I can do this if nobody else picks it up I need a break from all this IDNA stuff.

**Comment by Wevah** [comment]
What other tags should be allowed, other than the four I mentioned? Perhaps most non-attributed styling tags, like `sup`?

**Comment by Wevah** [comment]
Allowing any of these causes the rendered title to not match what's shown in the article list; is that reasonable?

**Comment by Wevah** [comment]
Currently I'm leaning towards:

- Allow certain non-interactive, typographic, inline tags, such as `i`, `strong`, `sup`, etc. (but not `a`).
- HTML encoding all other tags from the title in the article view (e.g., `input`).
- Stripping the allowed tags from the title rendered in the timeline view, or converting them to their equivalent attributed-string versions.

For example:

```html
foo <input> <i>bar</i>
```

would be converted to

```html
foo &lt;input&gt; <i>bar</i>
```

in the article, and display as

#### foo &lt;input&gt; bar

or

#### foo &lt;input&gt; *bar*

in the timeline.
