### ISSUE TITLE
High Battery Usage

### ISSUE THREAD

**Issue by specter78** [Ranchero-Software/NetNewsWire#1965]
iPhone 11
iOS 13.4
NNW 5.0 build 39

Battery usage - 5% for 2h usage in last 10 days
Background- 45m
On screen - 1h 11m

**Comment by vincode-io** [comment]
@specter78 could you please explain a little more why you think that this shows high battery usage?  5% for 2h of usage means you will get 40 hrs of usage on your phone with the same usage pattern you are showing.

**Comment by specter78** [comment]
When you put it like that, it doesn’t sound too much!

Also, I don’t have exact figures, but the battery usage has increased post 13.4 update.

**Comment by vincode-io** [comment]
Thanks. It sounds like we are okay, so I’m going to close this one out.
