### ISSUE TITLE
Can’t return to timeline when full screen for articles is enabled 

### ISSUE THREAD

**Issue by sergeykrasilnik** [Ranchero-Software/NetNewsWire#1970]
Don’t know, maybe it’s a feature but previously it worked well. Now swiping from the edge doesn’t return to timeline, instead it just switches to previous article.

**Comment by vincode-io** [comment]
Wow. It looks like the 13.4 update broke this. I’ll see what I can do.

**Comment by vincode-io** [comment]
I've got a fix in for this.  We'll get it out as soon as possible with the 5.0.1 release.
