### ISSUE TITLE
iOS: icons background color glitches

### ISSUE THREAD

**Issue by sergeykrasilnik** [Ranchero-Software/NetNewsWire#1972]
![224A83B1-E567-4579-A284-2AC5C3C15E74](https://user-images.githubusercontent.com/45911681/78744619-b9dd3e00-796a-11ea-9b6a-c7aa2736d9c4.jpeg)
![BD026B91-88A1-4767-9E70-B5F8C69D7E75](https://user-images.githubusercontent.com/45911681/78744620-bba70180-796a-11ea-94dd-0b792e4d8f0b.jpeg)

Often background color appeares under smart folders icons. I haven’t found what actually causes that, sometimes that happens after switching between light and dark themes and sometimes it seems like it appeares randomly.

**Comment by vincode-io** [comment]
I _think_ we have made a change coming in the 5.0.1 release that should prevent this from happening.  Could you please reverify for us after we release 5.0.1 that this is no longer a problem please?  If you see it again after that, I will reopen this issue.

**Comment by sergeykrasilnik** [comment]
Sure
