### ISSUE TITLE
Push Notification not working

### ISSUE THREAD

**Issue by specter78** [Ranchero-Software/NetNewsWire#1973]
The app asks for push notification permission on both iOS and macOS. However, in either case, they are not working. Just the unread count is shown on app icon.

**Comment by vincode-io** [comment]
We don't send out notifications for every article you get.  Only the ones that you have specifically set up notifications for.  https://ranchero.com/netnewswire/help/ios/5.0/en/notifications

**Comment by specter78** [comment]
Thanks. Didn’t know this. 

Suggestion: show an icon next to feed for which notifications are on.
