### ISSUE TITLE
Problem with images blocking text

### ISSUE THREAD

**Issue by mape85** [Ranchero-Software/NetNewsWire#1975]
Hi!

Using NNW Version 5.0.3 (2618) images on the blog of the Real Society block some text. They are not in line.

I first saw the issue in this post:
`http://rss.royalsociety.org/~/621057056/0/publishing~Why-do-viruses-jump-from-animals-to-humans-Clues-to-the-COVID-pandemic/`

The feed's URL is:
`http://rss.royalsociety.org/publishing`

And the Home Page URL is:
`https://blogs.royalsociety.org/publishing`

I have no idea why, but maybe you can take a look whenever possible.

Hope everybody is safe.

😊

**Comment by vincode-io** [comment]
Are you talking about this?

![Screen Shot 2020-04-08 at 1 11 46 PM](https://user-images.githubusercontent.com/16448027/78818598-8914fd00-799a-11ea-9c09-15ffa49f15f7.png)

If so, there is nothing we can do about it.  The HTML they sent us has an image tag right in the middle of the word "findings".

**Comment by mape85** [comment]
Correct!

That’s weird…

Because on the website it looks alright


And using reader mode on Safari it is also rendered well


Anyway… Thank you for taking time to check the issue.

Hope you’re doing fine and are safe!

Best,

Miguel

**Comment by vincode-io** [comment]
It is weird.  I don't know what their CMS is doing.  Sorry we couldn't help you out more.

![Screen Shot 2020-04-08 at 1 22 04 PM](https://user-images.githubusercontent.com/16448027/78819627-23297500-799c-11ea-8458-dcb806d5e20d.png)
