### ISSUE TITLE
Crash when navigating back to home page, collapsing a folder, and selecting a feed before the folder collapses

### ISSUE THREAD

**Issue by r-token** [Ranchero-Software/NetNewsWire#1976]
On version 5.0 of NetNewsWire for iOS, I can consistently reproduce a crash by taking the following steps:

1. Start on the home screen. Ensure that all folders are 'open', meaning you can see all your Smart Feeds, everything On My iPhone, etc
2. Select any option, be it Today, All Unread, Starred, a certain RSS feed, etc
3. From the selected feed, navigate back to the home screen, and quickly tap the folder arrow to collapse one of the folders
4. In that same folder you just tapped to collapse, before it fully closes, tap a feed. The app will crash.

Example:
* Tap into the Today feed -> navigate out -> quickly collapse the Smart Feeds folder -> tap Today again before/while Smart Feeds collapses, NNW crashes.

The app only seems to crash if all folders are open. If one is closed, the behavior goes away (or, at least, I'm unable to reproduce it).

I have a screen recording of this behavior, and I'm able to reproduce it consistently. It looks like GitHub Issues doesn't support .mp4 files though. This is the first issue I've opened, and I'd love to be involved in helping resolve this if deemed necessary to fix.

If you'd like the screen recording, let me know how I can best send that to you.
 
Note: this looks somewhat similar to [this issue](https://github.com/Ranchero-Software/NetNewsWire/issues/1562), but I wasn't sure if they were the same or not.

**Comment by vincode-io** [comment]
@r-token I think I got this one licked.  Let me know if you can still crash the app using this technique.
