### ISSUE TITLE
Share support for Simplepin

### ISSUE THREAD

**Issue by josephholsten** [Ranchero-Software/NetNewsWire#1985]
As a user of pinboard for bookmark tracking
I want to save posts into pinboard from NNW

Since full pinboard support is a big project, much better would be support for any of the many pinboard apps. I currently use Simplepin. Other worthwhile apps are mentioned in https://thesweetsetup.com/apps/best-pinboard-app-ios/

I’m not sure what would need to change to support this how how to research it. I know fiery feeds’ share dialog supports it. I’m also really weak on programming Apple systems, so if you could just point me to where the existing share dialog is configured now, I’ll try to work out the fix.

**Comment by vincode-io** [comment]
Is this for iOS right?  If so, it looks to me like SimplePin works fine.  Did you try adding it to your favorites in the "More" section of the share dialog?

All we do on our side is share the URL and iOS handles the rest.  If your app accepts a URL as a share, as SimplePin appears to, it works fine.

**Comment by josephholsten** [comment]
Yes, for iOS. I checked both More apps triple dots as well as the Edit Actions..., no mention of SimplePin in either. 

Let me go compare behavior with Fiery Feeds and update details.

**Comment by josephholsten** [comment]
Ah, I misremembered. It has its own pinboard action. SimplePin is only available from a Safari View. Sorry for misplacing the bug!
