### ISSUE TITLE
[feature request] Implement support for closed RSS-feeds with login and password

### ISSUE THREAD

**Issue by sherlock440** [Ranchero-Software/NetNewsWire#1992]
Some RSS feeds are closed and require a login and password. The NetNewsWire application does not support this - it writes that it was not possible to find an RSS feed (although it is, but closed with a login and password).

If this helps, Vienna (another open source RSS reader) has support for private RSS feeds - perhaps you can just copy the code you already have and embed it in the application.

**Comment by vincode-io** [comment]
Duplicate of #502.
