### ISSUE TITLE
Angle brackets in folder names get entity-encoded after relaunching

### ISSUE THREAD

**Issue by michaeljtsai** [Ranchero-Software/NetNewsWire#1996]
If I have “>” or “<” in a folder name, when I quit and relaunch the app (5.0.4 for Mac) they change to “&gt;” and “&lt;”. Perhaps this is related to #1924.

**Comment by vincode-io** [comment]
That has been fixed in the upcoming 5.0.4 release and was the same thing as #1924.  You can build from the mac-release branch to pick up the fix if you don't want to wait for the release.  We are trying to get the 5.0.4 release out soon though.
