### ISSUE TITLE
[feature request] cloud synchronization

### ISSUE THREAD

**Issue by sherlock440** [Ranchero-Software/NetNewsWire#1997]
Как-то очень странно, что RSS-ленты не синхронизируются между версиями приложения для mac и для iOS. Насколько я понимаю, нужно либо вручную загружать OPML-файл из одной версии в другую, либо синхронизировать через Feedbin (которого может и не быть).

Было бы супер, если бы появилась облачная синхронизация между версиямиприложения для mac и для iOS

**Comment by stephenwade** [comment]
Translated to English:

> It’s somehow very strange that RSS feeds do not sync between versions of the application for Mac and for iOS. As far as I understand, you need to either manually upload the OPML file from one version to another, or synchronize through Feedbin (which may not be possible).
>
> It would be great if there was cloud synchronization between application versions for Mac and for iOS.

**Comment by vincode-io** [comment]
Duplicate of #491.
