### ISSUE TITLE
iOS [feature request] Allow dark mode separate from system setting

### ISSUE THREAD

**Issue by crankygeek** [Ranchero-Software/NetNewsWire#1999]
I'd like to be able to set NNW to always use dark mode, independent of the system setting.

For whatever reason, I've developed a preference for reading light text on dark backgrounds for stuff like RSS, ebooks, etc. Though I generally prefer scheduled dark/light mode for the rest of the OS.

**Comment by vincode-io** [comment]
That is a feature that we did implement for iOS 5.0.1.  Sign up to test it to get early access.

**Comment by crankygeek** [comment]
@vincode-io Just installed 5.0.1. Looks great. Thanks!
