### ISSUE TITLE
iOS [bug] Appearance > Color Palette label isn't adjusting size with system text size

### ISSUE THREAD

**Issue by crankygeek** [Ranchero-Software/NetNewsWire#2000]
The new Color Palette label under Settings > Appearance is not resizing to match system text size.

Steps to reproduce

1. Open Settings > Accessibility > Larger Text
2. Set text slider to extreme minimum or maximum value (screenshot is with max value)
3. In NNW 5.0.1, Open Settings
4. Swipe until Appearance is visible
5. Observe "Color Palette" text doesn't match other options text size

NNW  5.0.1 (build 40)
iPad 2017 (9.7 inch) iOS 13.3.1 

![IMG_7220E83C8AA5-1](https://user-images.githubusercontent.com/1638278/79802892-ba37ea80-8315-11ea-9a53-172292fa7dbc.jpeg)

**Comment by vincode-io** [comment]
Thanks for the report.  This has been resolved and will be in the next Test Flight build.
