### ISSUE TITLE
iOS [feature request] Automatically hide Feeds list after selecting a post in an item

### ISSUE THREAD

**Issue by crankygeek** [Ranchero-Software/NetNewsWire#2001]
I use my iPad exclusively in landscape layout. After I select a feed or folder, I would like the Feeds list to automatically hide to maximize the content area, rather than require me to tap on the double arrow button each time I switch feeds or folders.

This is a behavior I've enjoyed in Reeder for many years.

NNW iOS 5.0.1 (build 40)
iPad 2017 (9.7 inch) iOS 13.3.1

**Comment by vincode-io** [comment]
This is how it works now in NNW 6.0.  Basically it is the same Sidebar behavior as Mail.
