### ISSUE TITLE
Articles Scrolling In Scroll View When Using Swipe-Back

### ISSUE THREAD

**Issue by jalexandratos** [Ranchero-Software/NetNewsWire#2002]
When swiping from articles list to feed list the articles list is still scrollable - swipe-back isn't disabling the ability to scroll.

This is a regression from v5.0 where swipe-back did scroll lock the articles sheet.

Screen capture posted to Slack channel.

**Comment by vincode-io** [comment]
This is fixed and will be in the next Test Flight build.
