### ISSUE TITLE
[Feature Request] Opened article should remain open even on changing feed

### ISSUE THREAD

**Issue by specter78** [Ranchero-Software/NetNewsWire#2003]
Presently, if an article of a feed is open and feed changes, article pane becomes empty. Instead of this, same article should get displayed till new article is selected.

**Comment by vincode-io** [comment]
We need to keep the user interface in a consistent state.  We always try to keep the timeline in sync with the article view.  For this reason we have to close the article if you change the feed.  This functions as designed.
