### ISSUE TITLE
"Feedly" stays highlighted even after canceling prompt for sign-in

### ISSUE THREAD

**Issue by gruber** [Ranchero-Software/NetNewsWire#2009]
iOS
Version: 5.0.1 (41)

1. Go to NNW's Settings, then tap "Add Account". You see the list of On My Phone, Feedbin, Feedly.
2. Tap "Feedly".
3. You get a prompt "NetNewsWire wants to use 'feedly.com' to sign in". Tap Cancel.

Expected: You got back to the normal list of On My Phone, Feedbin, Feedly, with none of them highlighted.

Actual: "Feedly" remains the highlighted selection.

**Comment by vincode-io** [comment]
Fixed and coming in the next release.
