### ISSUE TITLE
Canceling addition of a Feedbin account takes you back to root level of settings

### ISSUE THREAD

**Issue by gruber** [Ranchero-Software/NetNewsWire#2010]
iOS
Version 5.0.1 (41)

1. Settings: Add Account: Feedbin
2. You now get a screen to sign into a Feedbin Account. Tap Cancel.

Expected: Go back to the Add Account screen (listing options like On My iPhone, Feedbin, Feedly, etc.

Actual: Takes you all the way back to the root level of settings.

For reference, go to the iOS Settings app, Passwords & Accounts → Add Account → tap any of the choices and then tap Cancel.

**Comment by vincode-io** [comment]
Fixed and coming in the next release.
