### ISSUE TITLE
"Add Account" screen in settings is untitled

### ISSUE THREAD

**Issue by gruber** [Ranchero-Software/NetNewsWire#2011]
iOS
Version 5.0.1 (41)

When you go to Settings: Add Account, the nav bar should be labeled "Add Account". Instead, it has no label at all.

Reference: iOS Settings app: Passwords & Accounts → Add Account

**Comment by jaanus** [comment]
Also the icon sizes are questionable in that dialog.

**Comment by jaanus** [comment]
… or rather, icon+text sizes. Attaching the current UI state for reference.

![Screenshot 2020-04-24 at 10 06 44](https://user-images.githubusercontent.com/184253/80184506-61b56580-8613-11ea-9deb-ae18da884a6b.png)

**Comment by vincode-io** [comment]
Fixed and coming in the next release.
