### ISSUE TITLE
“Mark all as Read” confirmation should be an action sheet, not an alert

### ISSUE THREAD

**Issue by dweiner13** [Ranchero-Software/NetNewsWire#2018]
Just a small UI suggestion. Currently, if you try to mark all articles in a timeline as read using the button in the toolbar, the confirmation appears as an alert. IMO, it would feel more natural for this to be an action sheet, especially on iPad as a popover anchored to the button, so that you don’t have to move your finger/cursor all the way to center of the screen. (if the function is activated by a keyboard shortcut, an alert is OK I think).

Happy to hear thoughts on this!

**Comment by brentsimmons** [comment]
We’ll consider this in 5.0.2.

**Comment by vincode-io** [comment]
This has been changed and will be in the upcoming 5.0.2 release.
