### ISSUE TITLE
iOS freeze after opening article in browser

### ISSUE THREAD

**Issue by Centurion** [Ranchero-Software/NetNewsWire#2019]
on iPad mini with recent OS after opening an article in Opera Touch (via share icon) and returning to app, it gets unusable (frozen); thank you in advance.

**Comment by vincode-io** [comment]
Do you mean that the article is gone or that you can't select another article or anything?

**Comment by Centurion** [comment]
> 
> 
> Do you mean that the article is gone or that you can't select another article or anything?
Hi, I can't select anything once an article is opened in browser and returning to NetNewsWire; I need to restart it completely.

**Comment by vincode-io** [comment]
I was able to recreate this problem and it is actually a problem with Opera Touch.  Opera provides the Opera Touch share extension.  It doesn't look like their share extension properly dismisses the share dialog when done.

Could you please report this bug to Opera?  Unfortunately there isn't anything we can do about it.

**Comment by Centurion** [comment]
excellent; thanks for your time. I will head out to Opera bug reporting.
