### ISSUE TITLE
Drop cap characters omitted in Reader View

### ISSUE THREAD

**Issue by michaelkirkpatrick** [Ranchero-Software/NetNewsWire#2021]
When loading Reader View for an article, characters rendered in drop cap are omitted.

**Steps to reproduce:**

1. Subscribe to this feed: `https://medium.com/feed/@ASlavitt` in NewNewsWire for iOS
2. Load a recent article from that feed, for example "The Coronavirus Crisis Will Force Us to Reconsider Universal Health Care"
3. Scroll down about halfway through the article and you'll see a sentence in the app that reads: "to the big question..."

![Reader-View-iOS](https://user-images.githubusercontent.com/23110714/80296240-07f58e00-872e-11ea-8d1e-549aaada69d0.jpeg)
In the image above, note the circled portion.

4. [Load the page for the article](https://medium.com/@ASlavitt/the-coronavirus-crisis-will-force-us-to-reconsider-universal-health-care-d5e26380e744) in a web browser. Scroll halfway down and you'll see that the sentence should have read "On to the big question..."

![Webpage-with-Drop-Cap](https://user-images.githubusercontent.com/23110714/80296262-36736900-872e-11ea-9d2e-c772542b57f3.jpeg)

The HTML on the page is as follows for that portion: `<p id="cf06" class="lv lw av ck lx b jr ly jt lz ma mb mc md me mf mg mw gl" data-selectable-paragraph=""><span class="y le mx my mz na nb nc nd ne cv">On</span> to the big question ...</p>`. My hypothesis is that Reader View is omitting text within a `<span>` element at the start of a `<p>`.

**Comment by vincode-io** [comment]
We use the Mercury Reader for our Reader View.  You might be able to file a bug there to get this addressed, but we can't fix it in NetNewsWire.  https://github.com/postlight/mercury-parser
