### ISSUE TITLE
Missing unread count for feed

### ISSUE THREAD

**Issue by donnywdavis** [Ranchero-Software/NetNewsWire#2031]
I noticed on the latest iOS Test Flight build 5.0.1 that randomly the unread count next to a feed would not display even though there were unread items in that feed. Refreshing the feeds corrected the issue and I have not been able to reproduce it. It happened on a few feeds after updating to this version.

I noticed this on my iPhone X running iOS 13.4.1.

**Comment by vincode-io** [comment]
Which account type are you using @donnywdavis ?

**Comment by donnywdavis** [comment]
@vincode-io Sorry, that would help, forgot to mention that. 🙈 I am using Feedly and only noticed this on a couple of individual accounts. Did not notice it on the smart feeds or feeds or local on my iPhone feeds. 

I just noticed it once and have not been able to replicate it. I hate these kinds of bugs. 😂

I have not noticed it on the latest TF build 5.0.1 (44) either.

**Comment by donnywdavis** [comment]
Just had the issue happen again. I captured a video just to make sure that I wasn’t crazy but it won’t let me attach it here. 😔

Steps that I did before I noticed it. I opened the app and then scrolled down the feeds and selected one to see the articles. Then I went back and marked all feeds in that list as read using the context menu. Then as I was scrolling back to the top I noticed one of the feeds showing no unread count. The folder that it was in had the correct count and selecting the feed showed the unread items. Only way to get the unread count to refresh was to collapse/ un-collapse the folder.

**Comment by vincode-io** [comment]
You can zip the file before attaching it.  I'd like to see the video if you can share it.

**Comment by vincode-io** [comment]
I'm beginning to suspect that our reloads on individual cells are sometimes failing due to how diffable datasources work.  This should probably be reworked to not use Node as the ItemIdentifier and create a custom struct for it.  See: https://www.donnywals.com/modern-table-views-with-diffable-data-sources/

**Comment by donnywdavis** [comment]
@vincode-io So sorry that I missed your replies here. 🙈 I was curious if it was something due to cell reuse. Haven't played around much with diffable datasources, but want to have a look into them. 

I have only seen this issue happen once since I last posted this and it did seem to be related to scrolling down the list of feeds, then selecting a feed to view the articles and using the mark all as read option. This doesn't seem to happen every time doing this though.

Here's the video that I mentioned previously. This example on had one feed show the issue, but the most recent one had 3 feeds. It had been a few days since I opened the app so the list of unread feeds was a little long.

[RPReplay_Final1588591820.mov.zip](https://github.com/Ranchero-Software/NetNewsWire/files/4661136/RPReplay_Final1588591820.mov.zip)

**Comment by vincode-io** [comment]
I made a change that I think will fix this.  It will be in the 5.1 NNW for iOS release.
