### ISSUE TITLE
iOS: Image zooming is losing resolution

### ISSUE THREAD

**Issue by vincode-io** [Ranchero-Software/NetNewsWire#2032]
It looks like we aren't handing full resolution images from the WKWebView to our ImageViewer code.  Rolling back to the version where we load the image from the source for display resolves this issue.

**Comment by jargonjustin** [comment]
I’m experiencing an issue with iOS NetNewsWire 5.0 (Build 39) on iOS 13.4.1 with both an iPad Pro (2018, 11-inch) and an iPhone X. When tapping an image to expand it, some expanded images appear to be a crop of the upper left of the full image (happens reliably for certain images in feeds across devices).

Is this the same issue, or should I open a new bug report?

**Comment by vincode-io** [comment]
That is a different issue that was resolved in the latest 5.0.1 test build versions.  Join our TestFlight to see it resolved.

**Comment by jargonjustin** [comment]
Thanks! Appreciate the pointer, and apologies for the duplicate report.

**Comment by vincode-io** [comment]
The fix is contained in the snippet below.  We will implement when preparing the 5.0.2 release.

```
var canvas = document.createElement("canvas");
canvas.width = this.img.naturalWidth * window.devicePixelRatio;
canvas.height = this.img.naturalHeight * window.devicePixelRatio;
canvas.getContext("2d").drawImage(this.img, 0, 0, canvas.width, canvas.height);
```
