### ISSUE TITLE
iOS: Adding UIInteraction randomly crashes

### ISSUE THREAD

**Issue by vincode-io** [Ranchero-Software/NetNewsWire#2034]

**Comment by vincode-io** [comment]
We're seeing this still in build 44.

**Comment by rizwankce** [comment]
@vincode-io Do we happen to know these crashes are from iOS 13.4 beta?

Looks like it's an unknown issue on 13.4 betas - https://twitter.com/steipete/status/1257980461739016193

**Comment by vincode-io** [comment]
Since this looks like it was only a problem on 13.4 betas, we're going to close this and reopen if we see it in prod.
