### ISSUE TITLE
Mailto links don't open the mail compose sheet on iOS

### ISSUE THREAD

**Issue by williamleuschner** [Ranchero-Software/NetNewsWire#2036]
NetNewsWire iOS: 5.0.1 (44)
iOS: 13.4.1
Device: iPhone 11 Pro

In the [most recent post](https://onefoottsunami.com/2020/05/01/protecting-whats-important/) on [One Foot Tsunami](https://onefoottsunami.com) ([feed](https://onefoottsunami.com/feed/atom/)), Paul includes a `mailto:` link to send him an email. On iOS, tapping this link doesn't do anything. I'm pretty sure that's a bug, since usually `mailto:` links open the Mail.app compose sheet.

**Comment by vincode-io** [comment]
This is fixed and is coming in 5.0.2.
