### ISSUE TITLE
Icons do not update

### ISSUE THREAD

**Issue by freshking** [Ranchero-Software/NetNewsWire#2037]
Sometimes the icons of a source do not update. It does not help scrolling them off and back on to screen so the cell renders again. 

Before:

![2FEA7D59-5EAA-4578-8FCD-9A3359C17478](https://user-images.githubusercontent.com/3601228/80870043-3cc09280-8ca4-11ea-8204-0c3c4bb126df.png)

After force quitting and reopening the app:

![0FB41428-7F15-41DD-96C3-152876385C5D](https://user-images.githubusercontent.com/3601228/80870061-4fd36280-8ca4-11ea-8016-336dace85796.png)

Also today table does not update after midnight (compare unread tag in the navigation bar of both screenshots)

**Comment by vincode-io** [comment]
Thanks for the report.  We'll look into the icon issue.

The Today feed is for the last 24 hours and only clears articles when you leave it.  Clearing it at midnight wasn't a good user experience when we had it implemented.  Night owls were losing articles that they were trying to read and were surprised by it.  We try not to surprise people and so took it out.  We realize that using the work "Today" for the last 24 hours is playing a little fast and loose with the word.

**Comment by vincode-io** [comment]
@freshking You might have been experiencing network connectivity issues when your icons weren't updating.  Is this still a problem that you have been having?

**Comment by freshking** [comment]
@vincode-io I never noticed the issue again. I guess it can be closed.
