### ISSUE TITLE
Enhanced Twitter Support

### ISSUE THREAD

**Issue by vincode-io** [Ranchero-Software/NetNewsWire#2038]
@benubois and I had a discussion about where Twitter support in NetNewsWire could be enhanced.  These are the main takeaways.

1) Support for Twitter Threads - Many twitter users use Twitter threads for long form writing, very similar to a blog post.  It would be nice to support this in NetNewsWire.  Feedbin already supports this in the Feedbin web interface.

2) Support for inlining articles.  Feedbin already supports adding a linked article inline using the Mercury service.  This could be something that NetNewsWire does on demand using some JavaScript and a custom scheme handler.

3) Better Feedbin / Twitter integration in NetNewsWire.  Specifically we discussed using NetNewsWire's Twitter rendering instead of the article content passed by Feedbin.  This would enable the above features for Feedbin as well as NetNewsWire local and iCloud accounts.

**Comment by michaelwoodruff** [comment]
This is awesome that you two are even discussing this. Looking forward to seeing this implemented in NetNewsWire!!

**Comment by jvican** [comment]
@vincode-io Are you planning to do any work on this? I see Feedbin has nice support for Twitter threads and it's a shame it cannot be used right now. Ideally we would have both twitter thread support and inlining articles.

**Comment by vincode-io** [comment]
Maybe I'll work on this someday and maybe I won't. We have lots of things to implement that benefit all NetNewsWire users, not just Feedbin users with Twitter feeds.

We aren't overriding any Feedbin functionality. To support Feedbin's Twitter threads, we would have to put Feedbin specific code in NetNewsWire. That is why this issue exists in the first place.

**Comment by jvican** [comment]
Thanks for the answer and the correction; it clarifies what needs to be done to get this ticket resolved.

**Comment by brentsimmons** [comment]
Adding additional Twitter support is pretty unlikely at this point, so I’m closing this.
