### ISSUE TITLE
Potential encoding issue

### ISSUE THREAD

**Issue by vincode-io** [Ranchero-Software/NetNewsWire#2039]
From Test Flight feedback:

> This RSS feed has encoding UTF-8. The description elements embed HTML inside CDATA and NetNewsWire appears to interpret the CDATA blocks as latin1.

![original](https://user-images.githubusercontent.com/16448027/80893754-ca978000-8c9a-11ea-9fb1-ba242d8b1416.jpg)

**Comment by Wevah** [comment]
Weird; it's showing up correctly for me on desktop build from `master`.

**Comment by Wevah** [comment]
I can't repro on iPhone either, with build 44. Maybe they fixed their feed?

**Comment by vincode-io** [comment]
If we aren't seeing it in build 44, I don't think this is something we need to worry about.
