### ISSUE TITLE
Firefox Favorite in Share Menu

### ISSUE THREAD

**Issue by griffineyes** [Ranchero-Software/NetNewsWire#2042]
Excuse me if I missed this issue, I searched for a solution but could not find one. Firefox is my iOS browser of choice, but NNW does not show in the "Favorites" toolbar. The function is enabled in Safari and I am able to share a website to NNW in Safari to have NNW parse the feed. I would like the same function for Firefox. Am I missing something?

Edit: grammar

**Comment by vincode-io** [comment]
A Share menu item is something we should look at implementing.  It just isn't there yet.

**Comment by Wevah** [comment]
I think this is about sharing _from_ Firefox on iOS. Not sure why it’s not picking up our extension.

**Comment by vincode-io** [comment]
Good catch.  I totally missed the iOS part of it.

**Comment by Wevah** [comment]
I can verify that we don't show up in Firefox (iOS)'s share sheet.

**Comment by rizwankce** [comment]
From Firefox official [website](https://support.mozilla.org/en-US/kb/add-ons-firefox-ios)

>Apple has created a proprietary iOS extension system which is incompatible with Firefox add-ons and extensions for Android, Mac, Windows and Linux. Also, iOS extensions written for other iOS apps won't work on Firefox for iOS (for example extensions written for Safari won't automatically work on Firefox for iOS).

I did test with other browsers like Chrome, DuckDuckGo and everything seems fine and was able to get the share extension.

Also found out that there is undocumented predicate way to set `NSExtensionActivationRule` for a share extension which I found [here](https://stackoverflow.com/questions/33933883/ios-share-extension-only-shows-in-safari) but not sure that would work

**Comment by vincode-io** [comment]
I'm suspect we just need to be able to take the plain text activation rule, similar to what that last link says @rizwankce.

**Comment by vincode-io** [comment]
We've changed this and it will be fixed in the next release.

**Comment by griffineyes** [comment]
Thank you!

Sincerely,

__
Richard Ashe
[+1 917 251 3391](tel:+1%20917%20251%203391)
www.richardashe.me

On May 14, 2020 at 12:25 GMT, Maurice Parker <notifications@github.com> wrote:

We've changed this and it will be fixed in the next release.
