### ISSUE TITLE
iOS: Blank web view after leaving and returning to the app

### ISSUE THREAD

**Issue by vincode-io** [Ranchero-Software/NetNewsWire#2043]
I suspect this is due to the out of process web view crashing.  Try this to see if it remedies the problem https://stackoverflow.com/a/41706111/11330872.

**Comment by nertzy** [comment]
Video posted to Slack at https://netnewswire.slack.com/archives/CPNED2D7Y/p1588545365118500

**Comment by vincode-io** [comment]
We've addressed this and it will be available for verification in the next TestFlight build.

**Comment by vincode-io** [comment]
I was able to successfully recreate this in the latest build.

**Comment by vincode-io** [comment]
Fixed by serializing access to the web view provider.
