### ISSUE TITLE
Not refreshing after reboot

### ISSUE THREAD

**Issue by richardfive** [Ranchero-Software/NetNewsWire#2044]
I've noticed that NNW doesn't perform the automated refresh cycle after I've rebooted my Mac and the applications like NNW are automatically restarted. After a manual refresh everything is fine again. Is this a NNW or a MacOSX issue?

Using NNW 5.0.3 (2618) and MacOSX Catalina 10.15.4.

**Comment by vincode-io** [comment]
This has been fixed in the upcoming 5.0.4 release.

**Comment by richardfive** [comment]
Sorry for the duplicate, didn't find a closed issue....

**Comment by vincode-io** [comment]
Thanks for the report!  It is better that we have some dupes than we not know about a problem. Bug reports are always appreciated.
