### ISSUE TITLE
‘⌘,’ should bring up NNW Settings

### ISSUE THREAD

**Issue by karan301** [Ranchero-Software/NetNewsWire#2052]
I semi-frequently find myself hitting ‘⌘,’ (CMD-,) with Magic Keyboard to bring up the Settings (Preferences?) pane In NetNewsWire but it doesn’t respond. Similarly, ‘⌘W’ (CMD-W) should dismiss it (as well as esc).

**Comment by karan301** [comment]
Apologies if this is an existing item. I did a quick search but didn’t find anything.

**Comment by vincode-io** [comment]
This has been added and will be in the 5.0.2 release.
