### ISSUE TITLE
Feed not found - Can’t add a feed because no feed was found.

### ISSUE THREAD

**Issue by kiwijuice** [Ranchero-Software/NetNewsWire#2055]
The following feed can not be added to NetNewsWire. However it can be added to other RSS services (i.e flowreader):

* https://www.gov.il/he/api/NewsApi/rss/d6b46ce2-975b-43ee-afbd-404ba29b01e8
* https://www.gov.il/he/api/NewsApi/rss/48eaee91-0c97-4ef3-b364-50ae52e3b56f
* https://www.gov.il/he/api/NewsApi/rss/e744bba9-d17e-429f-abc3-50f7a8a55667

When I'm trying to add it, I get the following message:
Feed not found - Can’t add a feed because no feed was found.
 
These feeds are valid, according to the w3 validator:
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.gov.il%2Fhe%2Fapi%2FNewsApi%2Frss%2Fd6b46ce2-975b-43ee-afbd-404ba29b01e8

Desktop Version 5.0.3 (2618) on macOS 10.15.3

**Comment by brentsimmons** [comment]
When I try to downloaded these via the command line, I get a 404 Not Found error on each. We don’t plan to deal with this.

	```[RSAir:~/Desktop] brent% curl -I 'https://www.gov.il/he/api/NewsApi/rss/d6b46ce2-975b-43ee-afbd-404ba29b01e8'
	HTTP/1.1 404 Not Found
	Content-Type: text/html; charset=UTF-8
	Cache-Control: no-cache
	Pragma: no-cache
	Expires: 0
	Connection: close```

**Comment by kiwijuice** [comment]
Is there any way to enable logs, I'll check it?

**Comment by brentsimmons** [comment]
Ah! I see.

My guess is that the issue is that it’s using UTF-16 encoding, and our feed-finding code may not work with UTF-16. So I’ll reopen this.

**Comment by andrewtj** [comment]
I've encountered another UTF-16 feed: https://blog.briancmoses.com/atom.xml

**Comment by brentsimmons** [comment]
The feed claims that it’s in UTF-8 encoding…

`<?xml version="1.0" encoding="utf-8"?>`

…but you’re correct, it’s UTF-16.

This comes up so immensely rarely that it may be a long time before we deal with it.

**Comment by zimmerman1181** [comment]
Here's another feed example that seems to be drumming up the same "Feed not found" error message:
https://www.mcknightsseniorliving.com/feed/

And the results from curl:

```
~ % curl -I 'https://www.mcknightsseniorliving.com/feed/'
HTTP/2 200 
date: Wed, 23 Mar 2022 15:56:04 GMT
content-type: application/rss+xml; charset=UTF-8
cf-ray: 6f085adc295727c4-SLC
cache-control: max-age=600, must-revalidate
etag: W/"d6c742eb966b6c957774a576721fc206-gzip"
last-modified: Wed, 23 Mar 2022 11:30:00 GMT
link: <https://www.mcknightsseniorliving.com/wp-json/>; rel="https://api.w.org/"
vary: Accept-Encoding, Accept-Encoding, X-WPENGINE-SEGMENT, Accept-Encoding
cf-cache-status: DYNAMIC
x-frame-options: SAMEORIGIN
x-distributor: yes
x-powered-by: WP Engine
x-cacheable: CacheAlways: feed
x-cache: MISS
content-security-policy: frame-ancestors 'self' https://www.mycme.com/ https://mycmesandbox.thoughtindustries.com https://nacesandbox.thoughtindustries.com https://www.naceonline.com/
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
```

**Comment by brentsimmons** [comment]
When I use curl to view the response body — the actual feed — I get nothing. Zero bytes. It’s worth reporting a bug to the feed owner.
