### ISSUE TITLE
Feature request: add article switch animation

### ISSUE THREAD

**Issue by zgjie** [Ranchero-Software/NetNewsWire#2060]
Maybe when tapping the left or right chevron in the top right of an article, the opening of the next or last article can have a page turning animation like the animation of swipe left or right, so there is one more chance to let the user discover the swipe gesture.

**Comment by vincode-io** [comment]
That's a good thought, and one that we had considered.  In the end we decided to keep the arrows going up and down, not left to right, and skip the animation.  This had a lot to do with how it functions on the iPad where you have the timeline visible.  We would be doing a left/right animation on the article while doing an up/down animation on the timeline.
