### ISSUE TITLE
Bug: unread count after updating to 5.0.1

### ISSUE THREAD

**Issue by specter78** [Ranchero-Software/NetNewsWire#2061]
![image](https://user-images.githubusercontent.com/40606342/81600523-620d7900-93e7-11ea-9740-d11b55739f56.jpeg)

This number was 0 before.

**Comment by vincode-io** [comment]
What is the URL of the feed in question.  Are you using the On My Device account or a syncing service?

**Comment by specter78** [comment]
https://explainxkcd.com/rss.xml

On my device account

**Comment by vincode-io** [comment]
This is probably due to a change in the feed that caused the reruns.  If not, it released to issue #1828.  We'll track progress on the issue there.

**Comment by brentsimmons** [comment]
I have another theory: this is due to the retention policy change. This feeds contains over 700 items, and we’re now showing everything that’s in the feed.

**Comment by vincode-io** [comment]
Yes, that makes sense.

**Comment by specter78** [comment]
> I have another theory: this is due to the retention policy change. This feeds contains over 700 items, and we’re now showing everything that’s in the feed.

Can you please elaborate on the retention policy change?

**Comment by brentsimmons** [comment]
For on-my-device accounts, articles are now kept if 1) they are still in the feed, or 2) they arrived in the last 30 days. (Whichever is longer)

Previously the retention policy was just to keep articles arrived in the last 90 days. This policy penalized slow-moving feeds — they could end up being empty.
