### ISSUE TITLE
Suggestion: Release updates at smaller intervals

### ISSUE THREAD

**Issue by specter78** [Ranchero-Software/NetNewsWire#2069]
The time period between release of 5.0 and 5.0.1 was long, for a 0.0.1 update. Moreover there were too many bug fixes (I got tired while reading the list!!!)

I think it would be better if updates are released at smaller intervals with fewer bug fixes.

**Comment by brentsimmons** [comment]
I agree that more-frequent updates would be better! This one took two months, and I would rather see just one month for an update like this.

However, it’s worth remembering that this is a free app, made entirely by volunteers, and in the last two months there’s been a global health crisis that we’re all dealing with — and, to make matters worse, the leader of the project (me) got laid off and spent about six weeks looking for a job.

Under those circumstances, I’m quite proud that we fixed so many bugs and it only took two months!
