### ISSUE TITLE
iOS: Read position is stored once and restored a lot

### ISSUE THREAD

**Issue by boxed** [Ranchero-Software/NetNewsWire#2075]
Reproduction:

1. Open a long article. Scroll down. 
2. Go to home screen
3. Back to NNW, the scroll position is correct.  
4. Scroll down
5. Exit to home screen
6. Back to NNW
7. The scroll position of point 3 is restored, not the new one. 

This also behaves like this if you lock the screen instead of going to the home screen.

**Comment by vincode-io** [comment]
We should tighten up the `scrollPositionQueue` duration so that people who are switching within a second of scrolling don't lose their scroll position.

**Comment by boxed** [comment]
What is the time to store now? It seems I can wait a long time and it doesn't ever store. But if I enter an article, scroll and lock it saves.

**Comment by vincode-io** [comment]
It is supposed to be between 0.3 and 1 second after a scroll event. Unless there is a bug preventing that from happening that is.

**Comment by boxed** [comment]
I tried waiting more than 5 seconds. Still restores the old position.

**Comment by vincode-io** [comment]
This has been fixed and will be in the next release, 5.0.2.
