### ISSUE TITLE
Notification Grouping by Feed & Preview

### ISSUE THREAD

**Issue by stuartbreckenridge** [Ranchero-Software/NetNewsWire#2076]
I'm not sure if there was a design choice not to use notification subtitles and threads; however, what's the feeling behind using these, instead of grouping all notifications under the app. 

Below is an example with title, subtitle, truncated summaries, and grouping by feed. 

![image](https://user-images.githubusercontent.com/7046652/82033889-f7eb2180-96cf-11ea-9405-7dab4621e5ee.png)

**Comment by vincode-io** [comment]
No design decision was made.  We just overlooked it.  This looks like a positive change and small enough for a minor point release, so I'll add it to 5.0.2.
