### ISSUE TITLE
iOS: [Bug] Trackpad 2-Finger Swipe Right to Toggle Read Status

### ISSUE THREAD

**Issue by robfeldmann** [Ranchero-Software/NetNewsWire#2084]
I found a bug on iPad when the UISplitViewController is in a two-column master/detail mode, such that the master view is a UINavigationController with two UIViewControllers on the stack: the “Feeds” screen and any list of articles (i.e., Today).

**Steps to Reproduce**:

1. Using the trackpad on the Magic Keyboard, use a two-finger swipe-right gesture on an article cell to toggle the item’s read status.

2. As you begin the gesture, observe that the cell begins to slide revealing the blue “[Un]Read” swipe action.

3. After a very brief moment, the cell’s slide action cancels and instead the NavigationController’s interactive pop gesture begins, revealing the Feeds screen underneath.

**Expected Result**: 

I expected to be able to complete the toggle read status gesture.

Alternatively, I would have expected the cell action to never reveal with the trackpad, and instead only trigger the interactive pop back to the feeds list (although at the time of invoking the gesture, I really did want to toggle the read status).

**Comment by stuartbreckenridge** [comment]
I can’t reproduce this on iOS 13.5. Is it possible that it’s a bug with 13.4?

**Comment by stuartbreckenridge** [comment]
Actually, this reproducible when other apps are running side by side. 
![Swift-bug-gif](https://user-images.githubusercontent.com/7046652/82446961-26a33680-9ada-11ea-836a-f5a63447fd75.gif)

**Comment by robfeldmann** [comment]
Nice detective work. That's exactly the scenario I was running in (another app side-by-side) which is how I almost exclusively run NNW on my iPad. I'm on iOS 13.4.1 btw.

**Comment by stuartbreckenridge** [comment]
It's also reproducible in portrait mode (not side-by-side).

**Comment by vincode-io** [comment]
@stuartbreckenridge I think disabling `interactivePopGestureRecognizer` is probably the right call.  Before we commit to it, could we check to see how Mail handles this problem?  They also use the right swipe for unread.  Did which ended up with precedence, the navigation pop or the cell swipe?  

I can't check it as I don't have a trackpad new enough to test this with.

**Comment by robfeldmann** [comment]
@vincode-io @stuartbreckenridge Don’t mean to butt in, but I was literally using Mail on my iPad at this moment. :) Mail’s swipe gestures are triggered when the cursor is on a cell.

Of course, if the cursor is on the navigation bar or toolbar, then then interactive back gesture is triggered.

**Comment by vincode-io** [comment]
@robfeldmann Perfect!  That's what I needed to know.

**Comment by vincode-io** [comment]
This will be in the upcoming iOS 5.0.2 release.
