### ISSUE TITLE
Feature request: Remove articles after “Mark Above/Below as Read”

### ISSUE THREAD

**Issue by petebocken** [Ranchero-Software/NetNewsWire#2086]
After marking above or below as read (and filtering by unread only) you are required to manually pull to refresh the list to remove those read articles from the view.

It would make sense to automatically remove those articles that are marked as read from the view and not require a manual refresh.

**Comment by vincode-io** [comment]
We very deliberately don't remove articles from the timeline when they are marked as read, even for the bulk mark as read actions.  In our experience this tends to surprise the user, which isn't a good thing.  We realize that users would prefer that this be changed, but we've decided that the trade off isn't worth it.  Sorry.
