### ISSUE TITLE
Make OPML export order stable

### ISSUE THREAD

**Issue by michaeljtsai** [Ranchero-Software/NetNewsWire#2094]
Currently, exporting subscriptions to OPML changes the order of the folders and the feeds within them at each launch of the app. Ideally, they would be sorted the same way as in the UI. This would make it possible to compare the export against what the app is showing and to compare one's own subscriptions over time by diffing the OPML files.

**Comment by vincode-io** [comment]
This is something that I fixed for 5.1 a while back, but didn't document it.  I've added this issue to the 5.1 milestone so that we know if got fixed during 5.1 development.  Look for it when we get 5.1 released!

**Comment by michaeljtsai** [comment]
Awesome, thanks!
