### ISSUE TITLE
iOS: CMD-I should bring up Info pane for feeds

### ISSUE THREAD

**Issue by karan301** [Ranchero-Software/NetNewsWire#2104]
Summary:
CMD-I should bring up Info pane for feeds.

Steps to Reproduce:
1. Select a feed in the sidebar.
2. Press `⌘I` to view Get Info.

Workaround:
Long press the feed and select Get Info from the Contextual Menu.

**Comment by vincode-io** [comment]
This has been added and will be in the upcoming 5.0.2 release.
