### ISSUE TITLE
Free Newspaper article get recognized as premium article and only popup text is shown

### ISSUE THREAD

**Issue by nvfl600d** [Ranchero-Software/NetNewsWire#2108]
Hey guys, I've had some problems with properly reading the rss feed of Zeit.de (newsfeed.zeit.de/index) and sueddeutsche.de (rss.sueddeutsche.de/rss/topthemen) on iOS. Both German newspapers. Zeit.de just added a popup to get people to pay for not getting ads anymore and this popup text will show up in every new article, the sad thing is that nothing else is shown except for this pop up message. It says: "To agree to the use of zeit.de with advertising, JavaScript must be activated in your browser. [...]"

For Sueddeutsche it's a bit different as every article is classified as premium article (behind the paywall) even if it's actually a free article. So a small snippet of the article is shown and then comes the hint for paying for the article.

The problem with both feeds is that these issues do not appear with Newsify. If that's not detailed or clear enough, I'd be happy to provide you with more information :smile:

**Comment by vincode-io** [comment]
Is it the Reader View that is giving you problems?  It looks like the feed itself only has summary of the article in it.

**Comment by nvfl600d** [comment]
> Is it the Reader View that is giving you problems? It looks like the feed itself only has summary of the article in it.

Im not much into rss, but as I mentioned, newsify pulls the original texts out of the feed without these issues.

1) I click the article 2) the snippet is shown correctly 3) I click the "read"-button (2nd from right) to read the full text and zeit.de then shows the popup text only

Sorry if thats confusing

**Comment by vincode-io** [comment]
That button is our Reader View.  We rely on a third party service to provide us with the text from a webpage.  If it weren't for this service, we wouldn't be able to provide a Reader View.  We don't have the developer resources to support it.

Unfortunately, it won't always be able to extract the webpage text.  Especially if there is paywall there.  I'm sorry, but there really isn't anything we can do to help you.
