### ISSUE TITLE
Problem with date parser on certain feeds?

### ISSUE THREAD

**Issue by luckman212** [Ranchero-Software/NetNewsWire#2109]
- NNW 5.0.3-2618
- macOS 10.15.4

Not sure if this is an RSS spec violation, but given this feed from Microsoft:
https://techcommunity.microsoft.com/plugins/custom/microsoft/o365/custom-blog-rss?tid=1056150819275488761?board=MicrosoftEndpointManagerBlog&size=10

The dates are mangled in NNW:
![image](https://user-images.githubusercontent.com/1992842/82832628-a4c05e00-9e89-11ea-8f31-02cb80de3201.png)
I checked the raw feed with cURL and I see the `<pubDate>` is formatted like this:
```
<pubDate>Mon, May 25 2020 04:45:26 +0000</pubDate>
<pubDate>Sun, May 24 2020 17:08:10 +0000</pubDate>
<pubDate>Sun, May 24 2020 13:02:26 +0000</pubDate>
<pubDate>Sun, May 24 2020 01:43:22 +0000</pubDate>
```
Which seems valid enough.

**Comment by Wevah** [comment]
I think this happens because the time zone is defined to be UTC/GMT and not a numeric offset. Supporting parsing of numeric time zone offsets would make sense, though.

**Comment by Wevah** [comment]
For reference: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Ftechcommunity.microsoft.com%2Fplugins%2Fcustom%2Fmicrosoft%2Fo365%2Fcustom-blog-rss%3Ftid%3D1056150819275488761%3Fboard%3DMicrosoftEndpointManagerBlog%26size%3D10

**Comment by luckman212** [comment]
Ah - I see. Ugh. I guess I'll try to report this to Microsoft. Probably farting into the wind, or pissing into the ocean as they say...

**Comment by vincode-io** [comment]
I'm closing this one since there isn't anything we can do about it on our end.
