### ISSUE TITLE
FeedWranger Feed Items API Contract has url as nullable

### ISSUE THREAD

**Issue by JustinSharkey** [Ranchero-Software/NetNewsWire#2110]
### Issue
The API contract for FeedWrangler seems to have url as a nullable field.

### Solution
Make `FeedWranglerFeedItem.url` an optional.

### Notes

```
▿ DecodingError
  ▿ valueNotFound : 2 elements
    - .0 : Swift.String
    ▿ .1 : Context
      ▿ codingPath : 3 elements
        - 0 : CodingKeys(stringValue: "feed_items", intValue: nil)
        ▿ 1 : _JSONKey(stringValue: "Index 45", intValue: 45)
          - stringValue : "Index 45"
          ▿ intValue : Optional<Int>
            - some : 45
        - 2 : CodingKeys(stringValue: "url", intValue: nil)
      - debugDescription : "Expected String value but found null instead."
      - underlyingError : nil
```

`{"feed_item_id":4160173291,"published_at":1588195823,"created_at":1588200095,"version_key":1588200095,"updated_at":1588200095,"starred":false,"read":false,"read_later":false,"author":"Dan Moren","feed_id":346361,"feed_name":"Six Colors","url":null,"body":"\u003Cp\u003EThis morning saw the release of the third developer beta of the newly christened iOS 13.5\u0026nbsp;\u003Ca href=\"#fn:pointfive\" id=\"fnref:pointfive\" title=\"see footnote\" class=\"footnote\"\u003E1\u003C/a\u003E (formerly iOS 13.4.5), which \u003Ca href=\"https://www.macrumors.com/2020/04/29/apple-seeds-third-ios-13-5-beta-to-developers/\"\u003Ewill bring some welcome improvements\u003C/a\u003E designed for our current world situation.\u003C/p\u003E\n\n\u003Cp\u003E\u003Ca href=\"https://www.macrumors.com/2020/04/29/apple-ios-13-5-passcode-unlock-faster/\"\u003EFace ID will now reportedly detect when you\u0026#8217;re wearing a mask\u003C/a\u003E, and though it will not recognize your face, it will pop up the passcode entry screen faster once it realizes that. (Personally, I would like to see a \u0026#8220;simple four-digit passcode until I leave this location\u0026#8221; option or something similar, for when I have to take my phone to the grocery store.) \u003C/p\u003E\n\n\u003Cp\u003ESecondly, Apple is adding a toggle in iOS 13.5 \u003Ca href=\"https://9to5mac.com/2020/04/29/turn-off-group-facetime-zooming/\"\u003Eallowing you to disable the \u0026#8220;enlarge the face of the speaker\u0026#8221; feature\u003C/a\u003E in Group FaceTime calls, which comes as a great relief to anybody who has used, and potentially become nauseated by, this feature. However, it\u0026#8217;s not disabled by default (boo), so you\u0026#8217;re still going to have to walk all your less tech-savvy relatives through how to turn this off. \u003C/p\u003E\n\n\u003Cp\u003EiOS 13.5 will also include the first version of the new exposure notification API being \u003Ca href=\"https://sixcolors.com/link/2020/04/apple-and-google-will-work-together-to-build-contact-tracing-system/\"\u003Ejointly developed with Google\u003C/a\u003E to help track the spread of COVID-19 and alert you if you have encountered someone else who has reported being tested positive.  \u003C/p\u003E\n\n\u003Cp\u003ENaturally, this is pre-release software, which means all of this features are subject to change. This is the third beta of the 13.5 release, which will be available to the public at large sometime next month. \u003C/p\u003E\n\n\u003Cdiv class=\"footnotes\"\u003E\n\u003Chr /\u003E\n\u003Col\u003E\n\n\u003Cli id=\"fn:pointfive\"\u003E\u003Cp\u003EThe first x.5 release in the history of iOS! \u003Ca href=\"#fnref:pointfive\" title=\"return to article\" class=\"reversefootnote\"\u003E\u0026#160;\u0026#8617;\u003C/a\u003E\u003C/p\u003E\u003C/li\u003E\n\n\u003C/ol\u003E\n\u003C/div\u003E\n\u003Cp\u003E[\u003Ca href=\"https://sixcolors.com/link/2020/04/ios-135-will-bring-group-facetime-face-id-improvements/\"\u003ERead on Six Colors\u003C/a\u003E.]\u003C/p\u003E","title":"iOS 13.5 will bring Group FaceTime, Face ID improvements ↦\n"}`

**Comment by vincode-io** [comment]
FeedWrangler is shutting down so we don't have any further plans to support it.
