### ISSUE TITLE
macOS: Feedbin: deleting a feed via keyboard shortcut, selection state is lost

### ISSUE THREAD

**Issue by shazron** [Ranchero-Software/NetNewsWire#2114]
## Motivation:
I just added a Feedbin account, and I want to be able to navigate my feeds using the keyboard, so I can curate the feeds I have so I can delete any obsolete feeds. The selection behaviour below is not intuitive and prevents an effective navigation to do this task if you have hundreds of feeds.

## Version: 
Version 5.0.3 (2618)

## Account:
Feedbin

## Expected:
When I delete a feed using the key "Backspace", the selection goes to the next item in the tree.

## Actual:
When I delete a feed using the key "Backspace", there is no selection of a feed after. I will have to use the mouse to select the next item in the list.

**Comment by vincode-io** [comment]
Feature added and will be available in the NNW for Mac 5.1 release.
