### ISSUE TITLE
(macOS, Feedbin) Articles do not get marked as read when selecting them

### ISSUE THREAD

**Issue by oniskanen** [Ranchero-Software/NetNewsWire#2115]
There is a sporadic issue when I'm reading Feedbin synced articles, where the article state stays as unread even though I just opened the article. Opening it again marks it as read correctly.

I tried searching for similar issues, and the closest I could find was #1515. I decided to open a new one, as the platform is different.

**Comment by vincode-io** [comment]
That is the same issue as #1515.  We just haven't released a Mac update with it fixed yet.

**Comment by vincode-io** [comment]
This has been added to the mac-release branch and will be part of the upcoming 5.0.4 release.
