### ISSUE TITLE
New Feed doesn't support localhost in URL

### ISSUE THREAD

**Issue by dmittman** [Ranchero-Software/NetNewsWire#2116]
I just tried adding a feed for a service running on my laptop, and discovered that I can't add a feed if the URL looks like `http://localhost:<port>/<feed>`. I had to edit `/etc/hosts/` to map a fully-qualified domain name to localhost before NetNewWire Version 5.0.3 (2618) (macOS) would enable the Add button. So, there's a workaround, but giving some love to localhost would be appreciated.

**Comment by brentsimmons** [comment]
Does 127.0.0.1 work instead?

**Comment by Wevah** [comment]
Are you adding the URL to your “On This Device” account?

**Comment by Wevah** [comment]
Oh, I see. The button is disabled.

**Comment by Wevah** [comment]
I know what the problem is: It's some validation code I added to make sure the URL contains a period.

In my testing `http://localhost/foo` doesn't work, but `http://localhost/foo.rss` does.

**Comment by dmittman** [comment]
Thanks! I didn't try `127.0.0.1`, but my guess is that it would have worked, based on what @Wevah shared.
