### ISSUE TITLE
Images/videos displayed in thin slices

### ISSUE THREAD

**Issue by urbanrob** [Ranchero-Software/NetNewsWire#2120]
Both still images and videos are often displayed as thin (not tall vertically) slices. In the attached screenshot I show a video which if played displays within that vertically short box.

<img width="907" alt="Screen Shot 2020-05-28 at 11 18 05 PM" src="https://user-images.githubusercontent.com/6887403/83217447-ce9fac00-a139-11ea-929c-72aa2d5f65a0.png">

**Comment by vincode-io** [comment]
Is this on the iPad or macOS?  Do you have a feed URL that you could share with us that exhibits this behavior?

**Comment by urbanrob** [comment]
MacOS
http://www.gourmetpens.com/feeds/posts/default

**Comment by vincode-io** [comment]
The good news is that the video issue you show in your screen shot is resolved and will be in the upcoming 5.0.4 release.

The bad news is that the Flickr images are intended to be cropped like that and there isn't any thing we can do about it.  I'm assuming that they are cropped that way to get you to click through to Flickr.  Sorry.
