### ISSUE TITLE
iOS: flashing during refresh.

### ISSUE THREAD

**Issue by dbarros** [Ranchero-Software/NetNewsWire#2124]
I notice some funky flashing of cells when doing a refresh on iOS. I'm not sure if this is by design, but I thought I'd share what I'm seeing in this video.

I am using NNW 5.0.1 (46), with a Feedly account.

![Untitled2](https://user-images.githubusercontent.com/1286/83346385-3125c180-a35f-11ea-83b0-de25d6737b77.gif)

**Comment by kielgillard** [comment]
@dbarros Does this happen on the first refresh after adding an account or on every refresh?

**Comment by dbarros** [comment]
@kielgillard This happens on every refresh. Both when I go in to the app and it automatically refreshes, or when I pull-to-refresh.

**Comment by dbarros** [comment]
@kielgillard I don' know if this makes a difference, but please note, in the screen recording above, that the items are mostly under the folder "Uncategorized".

**Comment by vincode-io** [comment]
This has been fixed and will be part of the 5.1 NNW for iOS release.
