### ISSUE TITLE
Sign in to Wired?

### ISSUE THREAD

**Issue by DarkAthena** [Ranchero-Software/NetNewsWire#2126]
Just came to NNW from Reeder. I subscribe to Wired (paywall) but can’t figure out to enter my credentials into NNW to access Wired. I use Feedbin to aggregate my feeds. iOS 13.4.

**Comment by brentsimmons** [comment]
Can you be more specific? What screen are you on, and what are you trying to do, and what’s happening instead?

**Comment by DarkAthena** [comment]
I think I figured it out. Thank you anyway.

**Comment by shazron** [comment]
FWIW Wired doesn't have full text RSS feeds anyway even for paywalled subscribers. All their RSS feeds are open and are excerpts only.

**Comment by dbarros** [comment]
> I think I figured it out. Thank you anyway.

Can you please provide info on how you resolved this issue?
