### ISSUE TITLE
Notifications only when I open app (iOS)

### ISSUE THREAD

**Issue by tylerwolf35** [Ranchero-Software/NetNewsWire#2127]
I am using NetNewsWire on my iPhone 11 Pro Max running iOS 13.5 and notifications only work when I open the app. I have background refresh’s enabled in the settings.

**Comment by pineappleburger** [comment]
Do you force-quit the app? ([Like I did <.<](https://github.com/Ranchero-Software/NetNewsWire/issues/1948))

**Comment by tylerwolf35** [comment]
> Do you force-quit the app? ([Like I did <.<](https://github.com/Ranchero-Software/NetNewsWire/issues/1948))

Yes, I force quit every app when I am done using it. Would it be possible to use an API to get notifications like with other news apps (e.g. AP News, CNN, ESPN) with the app closed.

**Comment by brentsimmons** [comment]
It’s a bad idea to force-quit apps when you’re done — for one thing, this prevents apps like NetNewsWire from doing background refresh and notifications.

To do push notifications the same way AP News, CNN, ESPN, and others do would require us to write and operate a server. This would take a lot of time and money to operate. This is a free and open source app with zero budget.

**Comment by Wevah** [comment]
Yes, there is really no reason to force-quit an app on iOS except as a troubleshooting step or the like.

**Comment by tylerwolf35** [comment]
> It’s a bad idea to force-quit apps when you’re done — for one thing, this prevents apps like NetNewsWire from doing background refresh and notifications.
> 
> To do push notifications the same way AP News, CNN, ESPN, and others do would require us to write and operate a server. This would take a lot of time and money to operate. This is a free and open source app with zero budget.

I know the server would take a lot of time and money to operate but would it be possible to self-host a server?

**Comment by brentsimmons** [comment]
We’d have to write that server in the first place, which would take quite a bit of time and would take away from our work on NetNewsWire itself.

**Comment by eneda8** [comment]
I don't force quit the app and I'm still having the same issue

**Comment by FlowOverFail** [comment]
I am having the same issue on iOS 14 with an iPhone 11 Pro. I am not force closing the app, but notifications only appear after re-opening the app. Background settings and everything is set correctly. I am not on any data saving mode or low power mode either.

**Comment by vincode-io** [comment]
We have to rely on background refresh for notifications to work.  iOS uses machine learning and battery power to determine when and more importantly *if* background refresh happens.  If you rarely open NetNewsWire or only do so one specific time of the day, iOS won't do background refreshes for NetNewsWire often if at all.

I'm sorry, but there isn't anything we can do about how often background refresh happens.  Apple has completely stripped control of that from the developers.
