### ISSUE TITLE
Scrolling up to random locations in very long posts

### ISSUE THREAD

**Issue by particleandparcel** [Ranchero-Software/NetNewsWire#2129]
I can’t find evidence that this has already been reported, but please let me know if it has. 

In very long posts (eg several thousand words) if I let my phone lock or switch to another app, I find that the item has been scrolled up from where I last was. But not to the top (like if the app had memory suspended by iOS) or to a specific spot — it might be 10% higher or 50% higher. And if it happens again, the location it goes back to isn’t the same as before. 

I’m not sure how to document this, but I could provide some example links of posts I’ve observed the behavior on. Let me know what other info would be helpful. 

Would think the preferred behavior would be to stay in the same spot as possible. 

Thanks!

**Comment by vincode-io** [comment]
Yeah, we know about this one and it will be fixed in the upcoming 5.0.2 release.
