### ISSUE TITLE
Feature request: Tap blue dot to mark read

### ISSUE THREAD

**Issue by githubnavigator** [Ranchero-Software/NetNewsWire#2131]
This app is fantastic!

Suggestion: On the list of articles, allow users to tap the blue Unread dot to mark as Read. When you have 20 or 30 articles to go through, it’s a lot of swiping to make all of the ones you don’t care about as read. Tapping the blue dot to mark as Read (a feature I have found in other readers) is much faster. 

Thanks everyone for this great app!

**Comment by vincode-io** [comment]
The blue dot is too small of a target to use for mark as unread.  We have many ways to mark multiple unread at once via the toolbar or context menu.  Hopefully these fill your need to mark quickly.
