### ISSUE TITLE
Marking a feed as read, then quickly tapping a different feed navigates to the wrong feed

### ISSUE THREAD

**Issue by Mackarous** [Ranchero-Software/NetNewsWire#2132]
Seems like an issue with updating the index paths of the table before it gets updated in the UI, then quickly selecting a new item in the list navigates to the one underneath.

Here's an example screenshot of my feeds:

<img src="https://user-images.githubusercontent.com/1043281/83978759-9df90880-a8d7-11ea-9216-a36ffdc88856.jpeg" width="400"/>

If I were to go into `Dev` for example, then mark all as read, when the navigation stack is popped, `Dev` remains visible, but quickly disappears because I have it filtered to unread items. If I select a different row before it disappears, it navigates to the wrong row.

I will try to catch it through a screen recording to attach to this issue

**Comment by vincode-io** [comment]
@Mackarous I've desk checked this and it looks ok to me.  Since this will be for the 5.0.2 release, could you make your pull request against the ios-release branch?  That will save me from having to cherry pick it off of master.
