### ISSUE TITLE
AppleScript: add feed property to article

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#2133]
This way you can get the feed from the current article, for one thing.

**Comment by Wevah** [comment]
Looks like `webFeed` doesn't return its fully-qualified reference (i.e., no parent chain).

**Comment by Wevah** [comment]
Ok, nope `self.container` is coming back as `Application` for `selected article`'s feed.

**Comment by Wevah** [comment]
This is complicated by the fact that a feed can be in multiple folders/top level account + folder.

**Comment by Wevah** [comment]
Actually, maybe the full chain isn't necessary as long as the Account can find a feed by id even in folders.

**Comment by Wevah** [comment]
When a feed has the same ID but is in two different places, is it backed by the same exact data?

**Comment by brentsimmons** [comment]
Yes, it is.

**Comment by Wevah** [comment]
It might be ok for `webFeed id "someid" of account "OnMyMac"` to find a feed in a subfolder, then.

**Comment by vincode-io** [comment]
@Wevah it looks like you were working on this.  Should it be assigned to you?

**Comment by Wevah** [comment]
Yes, that's fine. Still need to sort out specifics.

**Comment by Wevah** [comment]
Fixed in #2294. Open new issues if extra functionality is required!
