### ISSUE TITLE
Feeds get marked as unread

### ISSUE THREAD

**Issue by l1ghthouse** [Ranchero-Software/NetNewsWire#2138]
In the last few weeks all my feeds get marked as unread one by one. The first few times I thought that it was the case of a feed being republished. 

I don't use any sync account (waiting for CloudKit based sync), so it happens all on the local account My iPhone.

Things I noticed:
- it doesn't happen every day
- it is not limited to one feed a day
- it is not all the feeds at the same time
- a feed with all items unread doesn't appear again with all items unread (so it's a one time thing?)

**Panic articles from the past in the all unread smart feed**
![See articles in  “All Unread”](https://user-images.githubusercontent.com/42917186/84483504-b41d1500-ac99-11ea-989b-be846c97ad77.png)

**Six Colors with 503 unread articles**
![Six Colors](https://user-images.githubusercontent.com/42917186/84483495-aff0f780-ac99-11ea-8ea1-ab44c40334ac.png)

**Comment by brentsimmons** [comment]
With Six Colors there was a server side change that accounts for this. But that’s not necessarily true for the others.

**Comment by srgkrslnk** [comment]
I’m experiencing same thing with random feeds.

**Comment by l1ghthouse** [comment]
@brentsimmons okay that could be the case for a few of them. But not all of them. Is there something I can do to debug this?

**Comment by l1ghthouse** [comment]
did not happen again :)
