### ISSUE TITLE
Feed search does not cancel correctly

### ISSUE THREAD

**Issue by freshking** [Ranchero-Software/NetNewsWire#2139]
When you tap in the searchbar in the feed and then cancel it does not restore the previous state. The search controller is deactivated but mo feeds are shown and the title view with the badge ist missing. 

Here are the steps to reproduce:

1. Open a feed:

![3CE37C44-3C69-4BBA-9377-D0C88CB300AF](https://user-images.githubusercontent.com/3601228/84977964-03e15d80-b12c-11ea-9ad2-ba7bc9dbaaf3.png)

2. Tap the search bar:

![FD441DB7-BEF9-46E9-ACD5-DFC87E8AA54F](https://user-images.githubusercontent.com/3601228/84977987-178cc400-b12c-11ea-8d6e-f3a870939421.png)

3. Tap cancel on the right of the search bar:

![E1028739-DBD4-47DC-B70E-5B507935EC55](https://user-images.githubusercontent.com/3601228/84978014-23788600-b12c-11ea-967d-cd2e01ec61df.png)

Thats how it looks in the end. You have to go back to the feeds list and reopen the feed to view the articles again.

**Comment by vincode-io** [comment]
Got it fixed.  This will be in the 5.0.2 release.
