### ISSUE TITLE
Translate NetNewsWire?

### ISSUE THREAD

**Issue by CyrosX** [Ranchero-Software/NetNewsWire#2140]
Could you make NetNewsWire translatable?
There are some group-online-translation applications, which allows users to contribute easily to translations

**Comment by shazron** [comment]
see comments in #850 and #851

**Comment by Krinkle** [comment]
I'd love to help out with a Dutch translation.

If you're interested in levering an open platform, then [translatewiki.net](https://translatewiki.net/) could help you get a wide range of translations for app on an on-going basis, including peer review from non-technical volunteers. I've worked with them before and could help set things. Practically speaking they'd provide periodic pull requests with semi-automatic exports of the latest string sets.

**Comment by vincode-io** [comment]
Duplicate of #78.
