### ISSUE TITLE
RFE: "Go to next feed" when marking a feed as "read" on ios

### ISSUE THREAD

**Issue by ChrisRozon** [Ranchero-Software/NetNewsWire#2141]
Current workflow: when in a feed, select "mark as read" button on bottom left.
The app switches back to the Feeds index screen, and I then select the next feed that has unread posts. Rinse and repeat.

Desired workflow: when in a feed, select "mark as read" button on bottom left.
The app switches directly to the next feed that has unread posts. 

This is literally the only thing keeping me on the Feedly app right now. As I read through my feeds, it's nice to automatically jump to the next feed source.

**Comment by vincode-io** [comment]
If you are using a keyboard you can press the `l` key (lower case L) and that will perform the behavior you are looking for.

Unfortunately, there just isn't enough space on the screen to support both the current functionality and the one you describe with a new button or something.  Sorry.

**Comment by ChrisRozon** [comment]
This is on iPad, so no keyboard, sorry.
I'm thinking more as an option for default behaviour, controlled in settings?

**Comment by vincode-io** [comment]
We try really hard not to have so many settings that it begins to intimidate the user.  It isn't that we won't add new settings, it just that it almost has to be super popular or an accessibility issue to get added at this point.  We've just got so many settings already.

I'd love it if we could help you out, but it just isn't possible to be all things to all people.  Maybe you'll get a keyboard for your iPad at some point.
