### ISSUE TITLE
VoiceOver should read “unread” before  unread items

### ISSUE THREAD

**Issue by PeterSaathoff-Harshfield** [Ranchero-Software/NetNewsWire#2142]
Environment:
iOS 13.5
NNW 5.0.1 from TestFlight

1. Turn on VoiceOver
2. Navigate into a feed
3. Focus VoiceOver on an unread item in the list

Expected:
The name of the item is preceded by “unread”, like in the Mail app

Actual:
VoiceOver reads read and unread items the same way

**Comment by vincode-io** [comment]
Great but report.  This is fixed and will be released in the upcoming 5.0.2 release.
