### ISSUE TITLE
NetNewsWire for Mac is (very) fast to launch, but slow to quit

### ISSUE THREAD

**Issue by sharplet** [Ranchero-Software/NetNewsWire#2143]
I usually use NNW for Mac in pretty short bursts: I launch the app, browse through anything unread, saving longer posts that I still want to read for later, and then quitting. The quitting part is slow, taking around 1 second on my 2019 16-inch MacBook Pro. It would be great if quitting was just as snappy as launching.

**Comment by brentsimmons** [comment]
I assume you’re syncing with Feedbin — it’s syncing some read/unread state before the app actually quits.

**Comment by vincode-io** [comment]
The sync on close behavior was removed in the upcoming 5.0.4 release, so it will be fast to close on when you get that version.

**Comment by sharplet** [comment]
@vincode-io Thank you!
