### ISSUE TITLE
Number of unread items not displayed

### ISSUE THREAD

**Issue by TwentyH** [Ranchero-Software/NetNewsWire#2145]
Although there are unread items under the feed Wirecutter (8), they don’t show up until after I opened that feed. Please see [attached video.](https://share.icloud.com/photos/00Bpd0Y9iN-CHg_XIJMG1iXvw)

**Comment by vincode-io** [comment]
Thanks for the report.  We've made changes in iOS 5.1 (coming soon) that address this issue.
