### ISSUE TITLE
Accessing paste board shows warning on iOS 14

### ISSUE THREAD

**Issue by rizwankce** [Ranchero-Software/NetNewsWire#2146]
Due to changes on iOS 14, whenever user opens the app we get a notification saying "NetNewsWire pasted from --app name--"
<img src="https://user-images.githubusercontent.com/12063704/85592848-26133800-b664-11ea-88d4-21491b5df00d.jpg" width="320">

I guess, we are checking the pasteboard for any feed url. There is also new official API's from iOS 14 to listen to changes on clipboard. More info can be found [here](https://twitter.com/arekholko/status/1275497178195247107)

Apple documentation on [UIPasteboardDetectionPattern](https://developer.apple.com/documentation/uikit/uipasteboard/detectionpattern?changes=latest_major)

**Comment by rizwankce** [comment]
just making my findings here. 

There is no official documentation on how to use `detectPatterns(for:completionHandler:)` yet as of iOS 14 beta 1. I will keep an 👀 out on documentations

**Comment by vincode-io** [comment]
I'm closing this one out, since I don't think there is anything we can do about it.
