### ISSUE TITLE
Item Posts display "Description" and "Date" only. No Title or Author (feed URL given)

### ISSUE THREAD

**Issue by admwrd** [Ranchero-Software/NetNewsWire#2167]
**System:** macOS Catalina 10.15.5 (19F101)

**NetNewsWire Version**: 5.0.3 (2618)

**Issue**: 
NetNewsWire is displaying the `description` as if it was a title, and not displaying `title` or `author`. As per [this comment](https://github.com/Ranchero-Software/NetNewsWire/issues/1001#issuecomment-529576857), it seems that author should also show up, along with the title. 

**Feed URL**: https://www.starterstory.com/feed?format=rss

**Feed Body (Example)**

```XML
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel>
    <title>Starter Story</title>
    <author>Pat Walls</author>
    <description>Entrepreneurship, Business, E-Commerce</description>
    <link>https://www.starterstory.com</link>
    <language>en</language>
    <item>
      <title>How I Started A $80K/Month Amazon Consulting Service</title>
      <author>Scott Bartnick</author>
      <pubDate>02 Jul 2020</pubDate>
      <link>https://www.starterstory.com/amazon-consulting-service</link>
      <guid>2686</guid>
      <image>
        <url>https://s3.amazonaws.com/www.starterstory.com/stories/social_shares/000/002/686/original/open-uri20200625-4-mw98rf?1593047321</url>
        <title>How I Started A $80K/Month Amazon Consulting Service</title>
        <link>https://www.starterstory.com/amazon-consulting-service</link>
      </image>
      <description>Read the full story &lt;a href="https://starterstory.com/amazon-consulting-service"&gt;here&lt;/a&gt;.</description>
    </item>
  </channel>
</rss>
```

_Note - every item.description will always be "Read the full story here"._

**Displayed**:

* Read the full story here
    * July 1, 2020
* Read the full story here
    * June 30, 2020
* Read the full story here
    * June 29, 2020

No title or author is displayed in NetNewsWire, just the description and date for each post.

**Screenshot**:

[Image displaying this](https://github.com/admwrd/github-issues/blob/master/img/NetNewsWire-description-only.png). 
(linking as the PNG is 2MB and I don't want to put imagemagick on my system, but also want to be kind to metered data users)

**Comment by Wevah** [comment]
I'm getting the author shown, still no the title.

**Comment by Wevah** [comment]
`<image>` elements are supposed to be children of `<channel>`, not `<item>`; maybe we're choking on those.

**Comment by brentsimmons** [comment]
I think @Wevah is probably correct — get rid of those image elements, and I bet it works fine.
