### ISSUE TITLE
[FR] Make it possible to configure a default Smart Feeds selector, such as All unread

### ISSUE THREAD

**Issue by jeroenrotty** [Ranchero-Software/NetNewsWire#2169]
Unless I've slept under a rock, there is currently no setting to configure a default feed to open on the desktop (using mac) app? Right? It would be cool if I there's one so I can configure the "all unread" smart feeds is the default.

**Comment by vincode-io** [comment]
We will remember the last selected feed between launches in the upcoming Mac 5.1 release of NNW.  We don't have any plans to always launch to a chosen feed, but if you primarily use Unread then this should work for you.

**Comment by jeroenrotty** [comment]
Awesome, works for me! Thanks.
