### ISSUE TITLE
Implement Add Feed dialog

### ISSUE THREAD

**Issue by vincode-io** [Ranchero-Software/NetNewsWire#2184]

**Comment by stuartbreckenridge** [comment]
@vincode-io Do you mind having a look at 6b6ff7c?

It covers the Mac side of things, but it's quite a departure from the existing AppKit code. It works well...replicates the pasting of a URL from clipboard and adds feeds to the correct account / folder.


[Mac Add Feed.mov.zip](https://github.com/Ranchero-Software/NetNewsWire/files/4869721/Mac.Add.Feed.mov.zip)

**Comment by vincode-io** [comment]
I think it looks fine.  Unless there was something you thought I should be worried about that I might have overlooked, I say go with it.
