### ISSUE TITLE
Implement Add Folder dialog

### ISSUE THREAD

**Issue by vincode-io** [Ranchero-Software/NetNewsWire#2187]

**Comment by alexcfaber** [comment]
First PR: https://github.com/Ranchero-Software/NetNewsWire/pull/2207

**Comment by alexcfaber** [comment]
Outstanding tasks:
- [ ] Doesn't open the correct sheet on a mac; need to expand MainApp.swift to take different sheets in to account.

- [ ] Add window on the Mac doesn't resize correctly

- [ ] Share more code between Mac and iOS

- [ ] Share more code between AddFeed and AddFolder

**Comment by alexcfaber** [comment]
Addressed the first two with this PR: https://github.com/Ranchero-Software/NetNewsWire/pull/2241

Currently contemplating how to proceed with 3 & 4 in light, the attempts I did so far did get rid of duplicate lines of code, but did very little for readability.
