### ISSUE TITLE
Add feed button never enables itself

### ISSUE THREAD

**Issue by vincode-io** [Ranchero-Software/NetNewsWire#2199]
I also noticed that auto capitalization and auto correct is on for iOS when trying to enter a URL.

**Comment by stuartbreckenridge** [comment]
what is the url you are using? I've not been able to reproduce either with typed entries or urls from pasteboard

**Comment by stuartbreckenridge** [comment]
Something without `http:`, `https:`, or `feed:`?

**Comment by vincode-io** [comment]
Yeah.  See in slack.  We don't require the scheme when adding a URL to the Add Feed screen.
