### ISSUE TITLE
Sidebar icon for Starred has gray background — possibly only on iOS 14

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#2202]
![original-1](https://user-images.githubusercontent.com/1297121/86505326-eccf7c00-bd77-11ea-871f-0f5a4814859f.jpg)

![Screen Shot 2020-07-03 at 9 55 58 PM](https://user-images.githubusercontent.com/1297121/86505334-feb11f00-bd77-11ea-9130-9aaeb595ad96.png)

**Comment by vincode-io** [comment]
I'm honestly not sure what happened here.  I can't recreate it, so maybe it is a cell reuse issue?  Desk checking it, I can't find that to be the case.  The code looks good to me.  I'll keep thinking about it.

**Comment by vincode-io** [comment]
This shouldn't be possible anymore on the NNW 6.0 branch.  We should keep our eyes out for it because if we see it again, we know for sure that it is a cell reuse issue.
