### ISSUE TITLE
Sidebar expands to full screen and snaps back

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#2203]
From AppStoreConnect:

>Using 5.0.1 and now 5.0.2, I often find that I cannot hide the sidebar and use the full screen feature. It expands to full screen and snaps back, uncommanded.
>
>iPad Pro (10.5‑inch) 13.5.1

**Comment by vincode-io** [comment]
Is this the only report we got about this?  I'm not able to recreate this bug and have to wonder if the user didn't have their finger in the top right corner and is accidentally hitting it.

**Comment by brentsimmons** [comment]
Closing. We can reopen it if this bug gets reported again.
