### ISSUE TITLE
[Multiplatform] macOS - Clicking Add Web Feed with multiple NNW windows open shows the add feed sheet in all the windows simultaneously 

### ISSUE THREAD

**Issue by stuartbreckenridge** [Ranchero-Software/NetNewsWire#2217]
This can be prevented by moving the `.toolbar{ ... }` modifier from `SceneNavigationView()` to `SidebarContainerView()`. However, this causes a crash when continuing to navigate around the sidebar.

**Comment by vincode-io** [comment]
Rumor has it that we might see another beta release tomorrow.  If this hasn't been fixed in the next beta release, I'll create a sample project demonstrating it and submit a Feedback.
