### ISSUE TITLE
NNW 5.0.3 Mac: odd behaviour of this feed

### ISSUE THREAD

**Issue by Thomas-U** [Ranchero-Software/NetNewsWire#2226]
https://scilogs.spektrum.de/multifeed

In NNW more than half the entries have no clickable headline to load the full article. The site title and logo connect not to the page but to the feed.  **In other readers all elements are visible and functional.**

Is there something the site admins need to change in the feed-file that I should send them a note about?

in the **yes, we can** screenshot the headline works, in the other not.

![Screenshot 2020-07-06 at 14 56 26](https://user-images.githubusercontent.com/171936/86805573-45549100-c078-11ea-9069-4f006ca5ff66.png)
![Screenshot 2020-07-06 at 14 56 40](https://user-images.githubusercontent.com/171936/86805601-4d143580-c078-11ea-9a8b-71708b850b84.png)

**Comment by brentsimmons** [comment]
In those cases, there is no link element and the guid element says that it is not a permalink.

The guid is something like this…

<guid isPermaLink="false">https://scilogs.spektrum.de/go-for-launch/?p=8567</guid>

…which tells NetNewsWire that it can’t use https://scilogs.spektrum.de/go-for-launch/?p=8567 as a link.

So NetNewsWire ends up with nothing to link too.

There’s another issue with this feed, too. It has an image element inside the item element. This is not part of RSS, and it actually will confuse some parsers.
