### ISSUE TITLE
Pull to refresh in feed sidebar with filter enabled does not clear read articles in iPadOS 14b2

### ISSUE THREAD

**Issue by AngeloStavrow** [Ranchero-Software/NetNewsWire#2231]
**Description**
This behaviour occurs in iPadOS 14 beta 2 (and likely iOS 14b2 as well, but cannot confirm). On iOS 13, the pull-to-refresh gesture on the feed sidebar will clear any read articles from the table view if the "unread-only" filter is active. This gesture no longer works on iPadOS 14 beta 2.

**Steps to Reproduce**
1. Tap to view a feed (or smart feed) in the sidebar.
2. Make sure that the filter is active by tapping the filter button in the sidebar header.
3. Tap through a few articles to mark them as read.
4. Apply a pull-to-refresh gesture to the sidebar to re-apply the unread-only filter.

**Expected Behaviour**
The read articles are cleared from the sidebar's filtered table view.

**Actual Behaviour**
The sidebar's table view remains unchanged.

**Workaround**
Tap the filter button twice to toggle the unread-only filter on and off.

**Other Notes**
Tested on a 2018 iPad Pro running iPadOS beta 2. I don't have a device running iOS 14 beta 2 to determine whether this is iPad-specific or beta-specific behaviour.

**Comment by AngeloStavrow** [comment]
I'm closing this — what I experienced is user error. Turns out I didn't enable the setting!

**Comment by bensheldon** [comment]
Thank you for reporting this, even if it is user error. I came to report this same bug and TIL that setting exists 🙇
