### ISSUE TITLE
[TASK] Coding Guideline Update for SwiftUI

### ISSUE THREAD

**Issue by stuartbreckenridge** [Ranchero-Software/NetNewsWire#2233]

**Comment by vincode-io** [comment]
We definitely need this.  Let's use this ticket to keep ideas about what should be included.  We are all learning about SwiftUI and best practices.  Best practices as they apply to NNW are very much in flux right now.

Everyone, please add to this list as you find something you feel like you would have benefited from by knowing it in advance.

**Comment by vincode-io** [comment]
I posted this in Slack and we should adapt it to the coding guidelines since it seems to be working out:

> This hasn’t been communicated out to the developers yet and we will probably end up writing a technote to formalize it.  I was waiting until we had more experience with implementing it as a pattern before doing so.  But, it’s come up, so I’ll address it briefly here.
> We want to put any system state changing logic inside of the ViewModel classes.  That would mean moving AddWebFeedView.addWebFeed to AddWebFeedViewModel.  I recommend everyone review AddWebFeedViewto see what I mean.
> If you have to respond to system events, like a Notification, it should also be placed inside the ViewModel.  The goal here is to use ViewModels (as ObservableObjects) as an abstraction that gives the impression to SwiftUI that NNW is built as a reactive system.  Inside your ViewModel’s you can mix and match Combine or imperative code, which ever works best.  Views should never subscribe to Notifications or other events.  These should always go through a ViewModel which translates them into published events.
> I’d also like to put the ViewModels in separate swift files from the View itself.  Lots of times this wouldn’t be necessary, but I think we should do it for consistency sake.

**Comment by vincode-io** [comment]
We don’t suffix our view models with ViewModel, we just use Model.

**Comment by vincode-io** [comment]
We don't have any current plans to add Combine support to the Framework projects or Submodules.  If you feel that it would be helpful for you, please bring it up in the #work channel.  Instead, you should create a View Model class that subscribes to existing Notifications and implements itself as an `ObservableObject`.

**Comment by stuartbreckenridge** [comment]
_I was about to write about notifications._

As a guideline, should notifications be subscribed to in the view:

```swift
.onReceive(NotificationCenter.default.publisher(for: .AccountRefreshDidBegin)) { _ in
	viewModel.doSomething()
}
```

Or in the View Model:

```swift
NotificationCenter.default.addObserver(self, selector: #selector(doSomething(_:)), name: .AccountRefreshDidBegin, object: nil)
```

**Comment by vincode-io** [comment]
For each scene (window) we could have an `SceneModel`.  This would provide and have access to three additional models.  The `SidebarModel`, `TimelineModel`, and `ArticleModel`.  The submodels would create delegates that `SceneModel` can implement to all us to call up into `SceneModel` when necesssary.  For example if `SidebarModel` needs to do a “Mark All as Read” it would call a delegate method that `SceneModel` would implement.  `SceneModel` would then forward the request to `TimelineModel` which would mark the Timeline as read.

This is most similar to how the Mac app is implemented today.  `MainWindowController` == `SceneModel`, `SidebarController` == `SidebarModel`, etc…  If you squint real hard it is also how iOS is implemented.  `SceneCoordinator` == `SceneModel`, `MasterFeedViewController` == `SidebarModel`, etc…

By more tracking how the Mac app is done by delegating work to the submodels, I think we can avoid having a super large class like `SceneCoordinator` turned into.

**Comment by vincode-io** [comment]
For each scene (window) we could have an `SceneModel`.  This would provide and have access to three additional models.  The `SidebarModel`, `TimelineModel`, and `ArticleModel`.  The submodels would create delegates that `SceneModel` can implement to all us to call up into `SceneModel` when necesssary.  For example if `SidebarModel` needs to do a “Mark All as Read” it would call a delegate method that `SceneModel` would implement.  `SceneModel` would then forward the request to `TimelineModel` which would mark the Timeline as read.

This is most similar to how the Mac app is implemented today.  `MainWindowController` == `SceneModel`, `SidebarController` == `SidebarModel`, etc…  If you squint real hard it is also how iOS is implemented.  `SceneCoordinator` == `SceneModel`, `MasterFeedViewController` == `SidebarModel`, etc…

By more tracking how the Mac app is done by delegating work to the submodels, I think we can avoid having a super large class like `SceneCoordinator` turned into.

**Comment by stuartbreckenridge** [comment]
- [ ] Do use `self`
- [ ] Don't use `self` [SE-0269](https://github.com/apple/swift-evolution/blob/master/proposals/0269-implicit-self-explicit-capture.md)

**Comment by stuartbreckenridge** [comment]
Use `@StateObject` when the model is owned by the view or will be passed to child views as a binding.
Use `@ObservedObject` to observe changes in an object passed down the hierarchy.

**Comment by rizwankce** [comment]
• Swiftui views are cheap. So it’s okay to create as much views as we want 
• always indent with what Xcode suggests. I make sure Ctrl+I to auto indent

**Comment by stuartbreckenridge** [comment]
Accessibility: 

On user interactive controls—e.g. `Button`, add help tags using the `.help("Add Feed")` modifier. On macOS, this will appear as a help tag; on iOS this provides an Accessibility Hint for VoiceOver.

**Comment by vincode-io** [comment]
If a we need to gate code that has both macOS and iOS then it should be macOS first:

```
#if os(macOS)
    // AppKit code
#endif

#if os(iOS)
    // UIKit code
#endif
```

**Comment by Wevah** [comment]
There's also `canImport()` which might be more semantically appropriate, depending:

```swift
#if canImport(AppKit)
    // AppKit code
#elseif canImport(UIKit)
    // UIKit code
#endif
```

**Comment by stuartbreckenridge** [comment]
Related to notifications, subscribing via `.sink` or stick with `#selector`?

```swift
class MyModel: ObservableObject {

    // Subscriptions
    var notificationSubscriptions = Set<AnyCancellable>()

    init() {
        NotificationCenter.default.publisher(for: .UserDidAddAccount).sink(receiveValue: {  _ in
		self.sortedAccounts = AccountManager.shared.sortedAccounts
	}).store(in: &notificationSubscriptions)
    }
}
```

**Comment by vincode-io** [comment]
We should use the new trailing syntax as much as possible to make SwiftUI code more readable.

```swift
Button {
    sceneModel.shareArticle()
} label: {
    AppAssets.shareImage
}
```

**Comment by stuartbreckenridge** [comment]
When we are dipping into AppKit or UIKit in SwiftUI code, should we annotate it with `#warning` so we know we have to go back to it to clean it up?

Example [here](https://github.com/Ranchero-Software/NetNewsWire/pull/2327/commits/88ee63ba6836ab71190300253022ac0bedd0ff87).

**Comment by vincode-io** [comment]
I don't think the warning is necessary.  We'll remember to clear out the hacks when we get SwiftUI solutions for them.

**Comment by stuartbreckenridge** [comment]
Ok. I’ve removed it where it was used. 
GitHub Notifications <notifications@github.com> wrote:
“I don't think the warning is necessary. We'll remember to clear out the hacks when we get SwiftUI solutions for them.”

**Comment by vincode-io** [comment]
Closing this because we don't plan on doing SwiftUI in the immediate future.
