### ISSUE TITLE
Add feed folder picker has wrong tint color

### ISSUE THREAD

**Issue by vincode-io** [Ranchero-Software/NetNewsWire#2237]
If you look closely, you can see that it is using the system blue instead of our NNW blue Accent Color.  I'm not sure if there is something we can pass in the environment to picker to make it work correctly or if this is just a SwiftUI bug.

**Comment by alexcfaber** [comment]
I tried looking in to this with the digital colour meter, but I'm not sure. It looks like the back button on the folder picker is not bold, where the cancel button is. 

On saying that; I don't see accentColor being set anywhere, except on some individual assets, like the folderimage

**Comment by vincode-io** [comment]
Sorry, I should have been more clear.  The icons used aren't the right shade of blue.  This is easier to see in darkmode where we have a much lighter blue than the system blue.  Create a test folder and compare the shade of blue in the Sidebar vs. the picker for the new folder.
