### ISSUE TITLE
WidgetKit: Add an NNW iOS14/macOS 11 Widget

### ISSUE THREAD

**Issue by stuartbreckenridge** [Ranchero-Software/NetNewsWire#2240]

**Comment by vincode-io** [comment]
Aren't Widgets cross platform?  If we make one, it should probably work for macOS too right?

**Comment by stuartbreckenridge** [comment]
Correct. Amended the title

**Comment by vincode-io** [comment]
I wonder if our lack of remove push notifications is going to make a widget a poor user experience.  I still need to watch the WWDC session on them, so I don't know.

If the NNW isn't running on the Mac, will we still get updates for the widget?  If background sync is being flaky on iOS, will we still get an up to date widget?

**Comment by stuartbreckenridge** [comment]
I haven't done the code-along yet. 

My understanding is the widget can trigger a background download.

**Comment by stuartbreckenridge** [comment]
Are there instructions for adding new targets and making sure they pick up the settings from `SharedXcodeSettings`? 

I'm missing something as, unless I type in my organisation identifier, it just sees `group..NetNewsWire.iOS`.

**Comment by vincode-io** [comment]
There aren't any instructions.  We don't do it often enough to document it.  If you want to open a pull request with what you have, I'll finish up the target configuration for you.

**Comment by stuartbreckenridge** [comment]
I will park this for the time being until we work out a way forward. If we go for a remote notification route then I think the work on the branch will be effective as it just writes out a selection of the latest data to JSON which the widget can use.

**Comment by stuartbreckenridge** [comment]
I've picked this up again...it's more useful with remote notifications (which I have running), but there is still utility without them and just background refresh (e.g. for feeds that don't have notifications enabled).

![iVBORw0KGgoAAAANSUhEUgAABwgAAA1ICAYAAACDu8CkAAAACXBIWXMAAAsTAAALEwEAmpwYAAALMWlUWHRYTUw6Y29tLmFkb2Jl-2](https://user-images.githubusercontent.com/7046652/99251251-fb5e9180-2847-11eb-9ce3-8c00f48770fb.PNG)

**Comment by jean-io** [comment]
@stuartbreckenridge this looks great, can't wait to have it my iPhone 🤩
