### ISSUE TITLE
Article width is too narrow in 5.0.4d2  on macOS

### ISSUE THREAD

**Issue by sashkab** [Ranchero-Software/NetNewsWire#2252]
After upgrading to 5.0.4d2  version, I noticed that article width is now narrower than it used to be. I clearly understand that this is preference not to have wide articles, but I would like to have an option in preferences to select article width. It can be either check box (wide or narrow), or slider with 3-5 presets.

**Comment by Wevah** [comment]
I'll implement this if we want to do this.

**Comment by brentsimmons** [comment]
It’s too early to be adding this is as a preference, I think. I’m putting it in the Future milestone for consideration some time after 6.0 ships.

**Comment by nicksherman** [comment]
One possible (and very easy) solution for this is to simply change the padding of the theme's body to a percentage value instead of a fixed value. This way the outer padding will shrink and grow according to the size of the screen.

**Comment by brentsimmons** [comment]
Is this still an issue?

**Comment by sashkab** [comment]
Safe to close. This can be addressed by modifying existing theme.
