### ISSUE TITLE
Inline CSS positioning styles should be removed

### ISSUE THREAD

**Issue by slater** [Ranchero-Software/NetNewsWire#2255]
Currently, NNW leaves some CSS in articles. It should probably remove position styles.

**Example:**
https://www.gyford.com/phil/feeds/everything/rss/

The current latest post ("w/e 2020-07-12") has an embedded video, with inline styles (position:absolute, top:0; etc.), and that's exactly where NNW puts the video embed.

**Comment by Wevah** [comment]
I'm looking into forcing iframes that declare their height in percent units to be 50% of the web view's width instead, too. Not sure if that'll break anything.
