### ISSUE TITLE
iOS: subject not populated in mail composer when tapping mailto link

### ISSUE THREAD

**Issue by georgemblack** [Ranchero-Software/NetNewsWire#2256]
Environment:
iOS 13.5.1
NNW 5.0.2

When tapping a `mailto` link in an article, the subject in the link is not pre-populated in the mail composer. This behavior only appears on NNW for iOS.

Example `mailto` link with subject:
```
<a href="mailto:person@email.com?subject=Birds">Click here to email me</a>
```

Behavior on iOS:

<img width="414" alt="nnw-ios-upload" src="https://user-images.githubusercontent.com/35464130/87263522-0ad96280-c483-11ea-85bc-8ad766b0b691.png">

Behavior on macOS:

<img width="487" alt="nnw-mac-upload" src="https://user-images.githubusercontent.com/35464130/87263763-baaed000-c483-11ea-8e4b-f9af53282d19.png">

**Comment by vincode-io** [comment]
This is fixed and scheduled to be part of the NNW iOS 5.0.3 release.
