### ISSUE TITLE
Open external link with Open in Browser

### ISSUE THREAD

**Issue by cadin** [Ranchero-Software/NetNewsWire#2261]
On Daring Fireball, the article title typically links to an external site (`link rel="alternate"`), with an embedded URL at the bottom of the post that links to the DF post itself (`link rel="related"`).
In NetNewsWire, the external link doesn't appear anywhere in the post, so one has to open the post in a browser, then click the post title to visit the link.

Ideally, Open in Browser would open the external link instead of the link to the post.

Or is the DF feed format non-standard? I couldn't find any other examples of sites that behave this way.
DF Feed: https://daringfireball.net/feeds/main

**Comment by Wevah** [comment]
Clicking title of the article should bring you to the external site in DF's XML feed (the JSON feed has the external link on the bottom and the title goes to DF).

**Comment by cadin** [comment]
@Wevah That's not the behavior I see for the XML feed in the Mac app (v 5.0.3).
Clicking the article title brings me to the DF post, as does the star link at the bottom, and Open in Browser.
There doesn't seem to be any link to the external site when viewing the XML feed in NNW.

**Comment by Wevah** [comment]
That's weird; it's the same content as http://daringfireball.net/index.xml, but one works while the other doesn't.

**Comment by Wevah** [comment]
Oh, hm, I wonder if it's because my DF feed is going through FeedBin.

**Comment by cadin** [comment]
Yeah, neither link works for me (no Feedbin).

**Comment by Wevah** [comment]
Seems like something we should remedy. Subscribing to the JSON feed at https://daringfireball.net/feeds/json might work as a workaround for now, though.

**Comment by cadin** [comment]
I consider [6398c56](https://github.com/Ranchero-Software/NetNewsWire/commit/6398c56511803baef2aa59b0c673ed95614a7a8a) an acceptable fix for this. Thanks!
