### ISSUE TITLE
Sync status label doesn’t reflect failures

### ISSUE THREAD

**Issue by mcclurgm** [Ranchero-Software/NetNewsWire#2262]
In the bottom bar of the iOS app, there’s a label that says when the feed was last updated. It’s usually correct, but it doesn’t account for sync failures. Here’s an example:
- Turn on airplane mode
- Wait until the refresh label says something other than “Just now” (for instance, 5 minutes ago)
- Refresh. You should see a pop up that says the sync failed. 
- The label will update to say “Just now”. 
- The label will stay up to date with this new value. In 1 minute, it’ll say 1 minute ago, and so on. 

It’s a minor issue, but I would argue it’s confusing. The label implies that the information in my feed is up to date as of X minutes ago. However, in this case that is not correct, and the information is actually farther out of date. If I’m out of service range for a longish stretch of time, it can mean that I think NNW is a few hours or even days up to date than it is. This is particularly so if NNW updates in the background, so I won’t know when it actually was up to date. 

(I don’t have a Mac so can’t say whether this behavior is there too.)

**Comment by brentsimmons** [comment]
Todo: check on Mac.

**Comment by vincode-io** [comment]
Let's say that we have 100 feeds and only 50 successfully updated.  Is that a successful update or not?

The only scenario we can really handle for failures is the airplane mode one.  We could check the network connection before we try to sync and if it is unavailable, don't try to sync at all.

**Comment by mcclurgm** [comment]
That's a good question that I didn't consider. I suppose it could be considered a successful update. I want to say that NNW should notify me that there were errors, but I don't know how to do it in an unobtrusive way. It's not a very important error really, so probably not worthwhile.

The network connection fix would pretty much fix this for me in practical terms.

**Comment by vincode-io** [comment]
We no longer try to sync if the network is unavailable.  This should help with the status message being incorrect when in Airplane Mode.

**Comment by mcclurgm** [comment]
Awesome, thanks for your work here!
