### ISSUE TITLE
Unable to Add Feedly on Mac

### ISSUE THREAD

**Issue by kernjackson** [Ranchero-Software/NetNewsWire#2264]
## Issue

I was able to add Feedly on iOS, but it does not appear as an option on Mac. I searched the existing tickets for "Feedly", and did not find an existing issue. 

Is this a bug, enhancement, or a Feedly restriction?

## Mac

<img width="562" alt="Mac Add Account (Feedly is Missing)" src="https://user-images.githubusercontent.com/6172851/87453130-b25fad80-c5c7-11ea-906a-c4109833ee1f.png">

- MacOS 10.15.5
- NNW 5.0.3 (2618)

## iOS

![iOS Add Acount ](https://user-images.githubusercontent.com/6172851/87453133-b4297100-c5c7-11ea-93ce-048da5c506a0.jpeg)

- iOS 13.5.1
- NNW 5.0.2 (Build 49) (AppStore)

**Comment by pdokas** [comment]
Feedly is scheduled for 5.1 for macOS.

https://github.com/Ranchero-Software/NetNewsWire/milestone/7
