### ISSUE TITLE
Embedded video sizing

### ISSUE THREAD

**Issue by petebocken** [Ranchero-Software/NetNewsWire#2267]
Blog post example: https://leancrew.com/all-this/2020/07/scibble/

On iPhone when using On My iPhone or Feedbin, the video does not fit and lets you scroll horizontally. When using Feedly, the video doesn’t show at all.

Tested with Reeder and not a problem with OMi or Feedbin, fits the screen. Video also doesn’t show at all with Feedly.

**Comment by Wevah** [comment]
The video doesn't show up on the page for me in Safari, either, presumably because it's using an `<object>` instead of `<video>`.

**Comment by Wevah** [comment]
Ah, works in Safari on iOS but not on Mac.
