### ISSUE TITLE
Refresh errors should route to the correct account for updated credentials

### ISSUE THREAD

**Issue by vincode-io** [Ranchero-Software/NetNewsWire#2270]
For example, if a Feedbin account sync fails while in the foreground, we should show the Feedbin account in a dialog sheet so that the user can correct their credentials.

**Comment by stuartbreckenridge** [comment]
For the edge case of a user who has, for example, both a Feedbin and Newsblur account, and both fail to sync, what should the behaviour be? Should syncing stop on the first failure?

**Comment by vincode-io** [comment]
I don't think we want to stop syncing other accounts just because one account might be unavailable.  Feedly going down shouldn't stop the local account from syncing.

I see where you are going though.  With the current way that we have set up to display the account errors only one failure at a time can be displayed.  Honestly, I'm not quite sure what to do about that yet.

**Comment by stuartbreckenridge** [comment]
Maybe an error collection? If one account errors out it can take you to that account; if more than one, an error message saying 

"these accounts (x,y,z) failed to sync. Go to accounts to update your credentials"

**Comment by vincode-io** [comment]
Yeah, let's go with that.

**Comment by stuartbreckenridge** [comment]
I'll have a swing at this over the weekend.

**Comment by stuartbreckenridge** [comment]
Is this ok? I've added a new FixAccountCredentialView which is shared across Mac/iOS. 


![Simulator Screen Shot - iPhone 11 Pro - 2020-07-25 at 09 43 59](https://user-images.githubusercontent.com/7046652/88446326-a98a9980-ce5b-11ea-9dae-2e9b24701d31.png)
<img width="369" alt="Screenshot 2020-07-25 at 9 43 07 AM" src="https://user-images.githubusercontent.com/7046652/88446329-ac858a00-ce5b-11ea-8a99-3aeef68f1706.png">

**Comment by vincode-io** [comment]
That looks really good!
