### ISSUE TITLE
Support Undo operations

### ISSUE THREAD

**Issue by vincode-io** [Ranchero-Software/NetNewsWire#2284]
The code is there to support undo, but the undoManager isn't being correctly set in the environment by SwiftUI.  We need to file a bug report and revisit when fixed or we abandon the SwiftUI App Lifecycle.

**Comment by brentsimmons** [comment]
Thinking this is now invalid since we’re not using the SwiftUI App Lifecycle. Re-open this if I’m wrong and this is still a valid issue.
