### ISSUE TITLE
Feed "Netkwesties" doesn't list titles

### ISSUE THREAD

**Issue by doekman** [Ranchero-Software/NetNewsWire#2285]
When adding the feed <http://feeds.feedburner.com/Netkwesties> (from [this website](https://www.netkwesties.nl)) to NetNewsWire, it lists zero (0) articles.

When I fetch it with `curl` and look at it in an editor, it lists many items. Also, it's valid XML (Tidy works). I've added the fetched feed here: [NetKwesties.xml.zip](https://github.com/Ranchero-Software/NetNewsWire/files/4946247/NetKwesties.xml.zip)

I use NetNewsWire Version 5.0.4d2 (2620) on macOS.

**Comment by brentsimmons** [comment]
What type of account — On My Mac or Feedbin?

If On My Mac, what happens if you create a second On My Mac account and add it there?

**Comment by doekman** [comment]
On My Mac account.

When I create a 2nd On My Mac account (I didn't even know one could do that), it works fine. It has got 25 new acticles.

**Comment by brentsimmons** [comment]
Got it. This is certainly a retention policy issue, which will be fixed in the next build.
