### ISSUE TITLE
iOS 14 treats back button as scribble target for search

### ISSUE THREAD

**Issue by voldyman** [Ranchero-Software/NetNewsWire#2307]
I am running the iOS 14 beta, not sure if this is a bug in NNW or in iOS (reporting at both places)

I tried pressing the back button to go from my feed category and the app registered it as a scribble input for search. The same thing happens when i try to press cancel on search.

Screenshots:

![IMG_0011](https://user-images.githubusercontent.com/2378083/88688875-aa673980-d0ae-11ea-810f-bf10bad1329f.jpg)
![IMG_0012](https://user-images.githubusercontent.com/2378083/88688878-aaffd000-d0ae-11ea-8c31-0419c0a444b7.jpg)

**Comment by vincode-io** [comment]
This is most likely an iOS 14 beta bug. We'll keep this open to verify again as we get closer to a production release of iOS.

**Comment by MaineSoNewOrleans504** [comment]
Support

**Comment by brentsimmons** [comment]
Is this still a bug?

**Comment by voldyman** [comment]
No, I can successfully press back and cancel buttons.
