### ISSUE TITLE
Add IDNA support

### ISSUE THREAD

**Issue by vincode-io** [Ranchero-Software/NetNewsWire#2310]
This was done for the 5.x series, but hasn't been done for 6.0 yet.  We should check the following pull request to see where we need to make changes to support IDNA in url's.

https://github.com/Ranchero-Software/NetNewsWire/pull/2309/files

**Comment by Wevah** [comment]
5.1 needs the files too but I haven't gotten to it yet.

**Comment by Wevah** [comment]
Pretty sure this was fixed ages ago in #2392, so I'm closing this to help clean up a bit.
