### ISSUE TITLE
Unable to add web feeds 

### ISSUE THREAD

**Issue by stuartbreckenridge** [Ranchero-Software/NetNewsWire#2311]
The changes in `main` as a result of #2309 seem to prevent web feeds from being added. 

On iOS:
- tap +
- enter url (I used my own site)
- tap Add

nothing happens

**Comment by Wevah** [comment]
I’ll take a look.

**Comment by Wevah** [comment]
Really disliking how SPM doesn't put resources in the actual framework bundle.

**Comment by Wevah** [comment]
This should be fixed in Ranchero-Software/RSWeb#18. Reopen if it's still an issue!
