### ISSUE TITLE
Render issue with Teslarati

### ISSUE THREAD

**Issue by peternlewis** [Ranchero-Software/NetNewsWire#2312]
When viewing the Teslarati feed (https://www.teslarati.com/feed/), Tweets show clipped at the bottom.

For example, the recent article “Elon Musk details Neuralink’s August 28 event, hints toward future developments”:

<img width="832" alt="image" src="https://user-images.githubusercontent.com/83102/89017638-35fdf600-d34d-11ea-9c9d-86c4b3f58692.png">

It may well be a problem with the feed or whatever, but I figured I'd report it. I couldn't see any way to get the raw feed data to try to see where the problem might lie.

NetNewsWire Version 5.0.3 (2618) / Catalina 10.15.5

Let me know if you need any further information.

**Comment by vincode-io** [comment]
This has been fixed in the upcoming 5.0.4 release.
