### ISSUE TITLE
NetNewsWire with a `&lt;title>` element in the content

### ISSUE THREAD

**Issue by karlcow** [Ranchero-Software/NetNewsWire#2316]
Version: NetNewsWire Version 5.0.3 (2618)
Platform: macOS 10.15.6 (19G73)

Netnewswire bails out on Tim Bray last feed. @timbray

This seems valid.
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.tbray.org%2Fongoing%2Fongoing.atom

But this post contains a `<title>` element
https://www.tbray.org/ongoing/When/202x/2020/07/23/Not-an-Amazon-Problem

<img width="577" alt="Capture d’écran 2020-08-04 à 11 14 58" src="https://user-images.githubusercontent.com/505230/89245450-c9804100-d643-11ea-8bd6-aca770c9d3e9.png">

And this is how it got rendered in NetNewsWire

<img width="967" alt="Capture d’écran 2020-08-04 à 11 15 34" src="https://user-images.githubusercontent.com/505230/89245489-ddc43e00-d643-11ea-997f-ff666dc6ded7.png">

The rest of the post is gone. But it is inside the feed.

<img width="893" alt="Capture d’écran 2020-08-04 à 11 17 58" src="https://user-images.githubusercontent.com/505230/89245632-33004f80-d644-11ea-94c1-0a22a767d61d.png">

So something is happening.

**Comment by brentsimmons** [comment]
Using Feedbin or On My Mac?

**Comment by Wevah** [comment]
The XML parser is most likely choking on the unescaped `>`.

**Comment by karlcow** [comment]
@brentsimmons On My Mac

**Comment by timbray** [comment]
There's a botch in the front page https://www.tbray.org/ongoing where it
says "and the HTML <code>&amp;lt;title></code> says…"

YES I SHOULD FIX IT OK

However it's correct in the actual piece "and the HTML
<code>&lt;title></code> says"

And the atom feed is correct: "and the HTML <code>&lt;title></code> says"

**Comment by Wevah** [comment]
The content is all there in the articles database, but it's converted that `&lt;` to a `<`.

**Comment by Wevah** [comment]
Okay, it's coming through into RSAtomParser correctly, but when it gets to an RSParsedArticle it's wrong.

**Comment by Wevah** [comment]
Wait, nope, the summary is coming in "correctly", but that's because it has `&amp;lt;`!

**Comment by Wevah** [comment]
Okay, I think I've tracked this down: libxml2 is decoding all entities; reencoding `<` to `&lt;` when `parsingXHTML` is true should be a good enough fix (unencoded `<`s are already handled).

**Comment by Wevah** [comment]
Re-encoding `&` and `>` is probably the right thing to do also (so things like `&amp;para;` will display correctly as `&para;` and not `¶`.

However, the summary for the article in question has `&amp;lt;title>`, which should technically correctly display as `&lt;title>`, though it was probably intended that it display as `<title>`, as in the content.

**Comment by timbray** [comment]
Correct and correct. It's a bug, which the software shouldn't be trying to
fix.
