### ISSUE TITLE
Cannot subscribe to https://gsong.dev/articles feed

### ISSUE THREAD

**Issue by billsaysthis** [Ranchero-Software/NetNewsWire#2317]
There is (what seems like) a valid RSS feed at https://gsong.dev/articles/rss.xml, at least it shows in Firefox, but NNW gives me a feed not found error when I try to subscribe using any of the following:

- https://gsong.dev/articles/rss.xml
- https://gsong.dev/articles/
- https://gsong.dev/articles

Using latest NNW on macOs 10.15.5

**Comment by vincode-io** [comment]
I was able to subscribe to it using NNW 5.0.3 and the https://gsong.dev/articles/rss.xml URL.  Is that the version you are using?

**Comment by billsaysthis** [comment]
![image](https://user-images.githubusercontent.com/11235/89317782-b7e26d80-d632-11ea-9505-1a6be5c015e2.png)

**Comment by vincode-io** [comment]
Are you using Feedbin or an On My Mac account?

**Comment by billsaysthis** [comment]
On My Mac

**Comment by vincode-io** [comment]
This is working for me every time.  Is it possible that you are on a managed network that is blocking access?

![Screen Shot 2020-08-04 at 11 44 42 AM](https://user-images.githubusercontent.com/16448027/89321074-0ea67200-d648-11ea-9325-8741517279cf.png)

**Comment by billsaysthis** [comment]
I'm on my home network (Comcast ISP) and don't recall encountering this issue with any other feed having used NNW for years now (including switching to the "new" version when it first released).

**Comment by vincode-io** [comment]
Could post a screenshot of the NNW error you are getting when trying to add the feed?

**Comment by billsaysthis** [comment]
![image](https://user-images.githubusercontent.com/11235/89321553-f890b580-d637-11ea-9da3-1dbd63ffab01.png)

![image](https://user-images.githubusercontent.com/11235/89321644-16f6b100-d638-11ea-9c9c-c9836e0cd124.png)

**Comment by vincode-io** [comment]
Thanks for hanging in there for me.  

Are you sure there is no chance that you are accidentally selecting a Feedbin folder?  

If not, have you restarted NNW recently?  I wonder if maybe there isn't a bad version of that feed that has been cached and you aren't getting the corrected one.  As a last resort we may need to reboot to make sure there isn't anything cached.

**Comment by billsaysthis** [comment]
I restarted NNW. I don't have a Feedbin folder but just to be sure I tried to add this feed at the top level On My Mac folder after the restart and get the same error. Can't take the time to reboot right now though.

**Comment by vincode-io** [comment]
Sorry that I'm having such a hard time helping you out.  It isn't possible for me to recreate your problem on my end, so I'm just feeling around in the dark right now.

![Screen Shot 2020-08-04 at 11 50 17 AM](https://user-images.githubusercontent.com/16448027/89323201-f8e67c00-d64a-11ea-8d93-b2e8db041a8d.png)

**Comment by billsaysthis** [comment]
No worries, I appreciate your time and effort.

**Comment by danburzo** [comment]
FWIW it's working for me to subscribe to https://gsong.dev/articles/rss.xml using NNW 6.0.3.

**Comment by billsaysthis** [comment]
With current version I can subscribe
