### ISSUE TITLE
Respect Sidebar size preferences from General preferences

### ISSUE THREAD

**Issue by vincode-io** [Ranchero-Software/NetNewsWire#2321]

**Comment by blackketter** [comment]
I believe that this is not working on Big Sur with 6.0d5.  

Adjusting the system preferences sidebar icon size setting does not update in NNW, even after a relaunch.  The fixed size appears to be close to "Medium" when compared to a Finder sidebar.

@vincode-io : should I file a new issue?

**Comment by vincode-io** [comment]
Yeah, let's open a new issue to track this.
