### ISSUE TITLE
Question about accounts

### ISSUE THREAD

**Issue by lanox** [Ranchero-Software/NetNewsWire#2324]
Hi thanks for the great app.

Wanted to ask is it possible to add github repo as account to sync your feeds across the iOS and macOS app? 

If you don't use feedbin or feedly it's hard to keep the sync across both devices.

Thanks

Lano

**Comment by vincode-io** [comment]
That's an interesting suggestion.  I don't think it would work well.  Git is designed more toward syncing text files and we need to sync a lot of fine grained database items.

Stay tuned.  We have more sync options coming soon.

**Comment by lanox** [comment]
Thanks looking forward to it.
