### ISSUE TITLE
Smartfeed "Today" uses different timezone or is labeled wrong

### ISSUE THREAD

**Issue by adrianburmester** [Ranchero-Software/NetNewsWire#2328]
Hi!
The "Today"-feed seems to be using a different timezone than the system/article list.
It includes articles published yesterday, as can be seen in the attached screenshot.

Maybe the feed shows the last 24h, but in that case it should be labeled accordingly.
I would expect "today" to only show articles published since midnight, in the timezone the rest of the app is working in, wich seems to be local system time (CEST, in this case)
<img width="826" alt="MBP16 2020-08-11 um 18 09 41" src="https://user-images.githubusercontent.com/30344284/89921335-dc73b200-dbfd-11ea-891f-f88efd82f613.png">

**Comment by vincode-io** [comment]
As you have figured out on your own, we are taking some liberties with the word "Today" as it is the last 24 hrs of articles.  Through user testing we found that users don't like having the Today smartfeed cutoff at midnight.

Most people don't have an issue with this and it is documented on the application help.

https://ranchero.com/netnewswire/help/mac/5.0/en/smart-feeds
