### ISSUE TITLE
Restore last view selection when opening app

### ISSUE THREAD

**Issue by dansteeves68** [Ranchero-Software/NetNewsWire#2331]
Enhancement/feature request: Instead of opening to "No Selection", open to the last used selection.

Why does NetNewsWire always open to no view selection? I'd prefer restoring the last view or (gasp) maybe some people would like a preference for it.

I nearly always open NetNewsWire to All Unread. On iOS (14 beta) I was offered a shortcut for this which is fun when I see it and use it. But on macOS I end up doing Open NetNewsWire, Command-Shift-R, Command-1, Command-2; which is habit now but reliably updates from Feedbin and opens the All Unread view up-to-date.

(Apologies if this is already an open issue. I did try a few searches to find something.)

**Comment by vincode-io** [comment]
That has been implemented and is coming in the upcoming NNW 5.1 for Mac release.
