### ISSUE TITLE
Timeline filter button is blurry, at least on non-retina screens

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#2336]
Compare ours (bottom)with Mail’s (top):

![Screen Shot 2020-08-14 at 6 18 09 PM](https://user-images.githubusercontent.com/1297121/90302388-ba2aa000-de5a-11ea-97d1-dc4c28959925.png)

**Comment by vincode-io** [comment]
I've updated the assets that are used for the filter button.  They should look better at 1x resolution, but I don't have any way to check for sure.
