### ISSUE TITLE
Warnings about use of @import in Sparkle

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#2341]
Using Xcode 11.6, there are warnings that say “Use of '@import' in framework header is discouraged, including this header requires -fmodules”

**Comment by vincode-io** [comment]
Since this issue is in the Sparkle project itself, how do you recommend we proceed?

**Comment by brentsimmons** [comment]
Since we’re using our own fork, we can make the change ourselves. https://github.com/Ranchero-Software/Sparkle on the “ui-separation-and-xpc” branch.

**Comment by vincode-io** [comment]
@danielpunkass I can't remember what the reason was that we needed to compile Sparkle from source.  Was it because we needed features that weren't released yet?

I'm wondering, because it might be a be a better solution to go back to a binary than maintain our own fork of Sparkle, in order to to remove these warnings.

**Comment by danielpunkass** [comment]
@vincode-io  I don't remember if I had a specific reason to recommend it or if it was just my general proclivity to always build from source. I tend to prefer to know that all the code being compiled into my apps go through the compiler so they can have issues flagged, benefit from performance enhancements in the compiler, etc.

**Comment by vincode-io** [comment]
It looks like the Sparkle team has implemented a binary SPM solution for this.  It hasn't been release yet.  We should watch the Sparkle project and when version 1.24 is release, we should be able to migrate to that.  All our dependencies will be SPM then and the warnings will be gone.

**Comment by stuartbreckenridge** [comment]
I've removed the Sparkle submodule from my local build and built the SPM package from the `2.x` beta branch of Sparkle and it seems to integrate fine. I had to make sure XPC services were copied earlier in the build phases though - straight after Compile Sources. 

The only warnings that are left are Updates to Project Settings and Auto-layout complaints on `MainWindow.xib`(one of which relates to Xcode 5.1!). 

The Sparkle SPM package I've built is here if anyone wants to test with it: https://github.com/stuartbreckenridge/SparkleNNW 

<img width="331" alt="Screenshot 2020-11-12 at 10 18 47" src="https://user-images.githubusercontent.com/7046652/98887194-7df5f280-24d0-11eb-9e05-5ae3ad9d0694.png">

**Comment by vincode-io** [comment]
Some great work here @stuartbreckenridge.  I think this is good for a several reasons.

1. We get rid of our last submodule
2. We clear up the vast majority of the remaining compiler warnings
3. We get to the most up to date version of Sparkle that can update sandboxed apps

How I recommend we do this.  @brentsimmons creates a Ranchero Software project called something like Sparkle-Binary.  @stuartbreckenridge can submit a pull request to it.  Once that is done, someone can update the main NetNewsWire project to remove the submodule and utilize the Swift Package.

This will make our build instructions simpler and get rid of the one thing that seems to trip people up the most.  The submodule init.

**Comment by stuartbreckenridge** [comment]
OK with me.

**Comment by brentsimmons** [comment]
I’ve created a new empty repo for Sparkle-Binary: https://github.com/Ranchero-Software/Sparkle-Binary

**Comment by stuartbreckenridge** [comment]
I've submitted a PR for it.

**Comment by brentsimmons** [comment]
Awesome — thanks, @stuartbreckenridge

**Comment by brentsimmons** [comment]
This appears to be fixed — I don’t get these warnings when building NNW 6.
