### ISSUE TITLE
Warning: ld: warning: linking against a dylib which is not safe for use in application extensions: /Users/brent/Library/Developer/Xcode/DerivedData/NetNewsWire-atgqegjvlalitpbygxclbbfdhhjh/Build/Products/Debug/OAuthSwift.framework/OAuthSwift

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#2343]
Xcode 11.6

**Comment by vincode-io** [comment]
This is because the OAuthSwift project doesn't have the "Allow app extension API only" checkbox checked.  I could submit a pull request to OAuthSwift to make the change, but who knows if it will get accepted.

**Comment by brentsimmons** [comment]
Let’s make the change in our own fork: https://github.com/Ranchero-Software/OAuthSwift

(Let’s also do a PR to the main repo, to be good citizens.)

**Comment by vincode-io** [comment]
This is no longer an issue now that we are using SPM to manage this dependency.
