### ISSUE TITLE
New window sidebar items remain truncated after resizing sidebar

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#2345]
Create a new window, then resize the sidebar. Text in the sidebar remains truncated.

macOS 10.15.6

![Screen Shot 2020-08-16 at 12 37 00 PM](https://user-images.githubusercontent.com/1297121/90342448-48b73280-dfbd-11ea-9f10-fcf4fcce5ca3.png)

**Comment by vincode-io** [comment]
I'm pretty sure I accidentally resolved this while working on another issue.  I can't recreate it now anyway.  Please reopen if it is possible to recreate it after you do your next build off of `mac-candidate`.
