### ISSUE TITLE
Preferences > Accounts - need to gate off some systems

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#2355]
It’s currently listing Feed Wrangler, FreshRSS, iCloud, and NewsBlur.

**Comment by vincode-io** [comment]
This is only for the test build.  These have been removed from the release build.  Do you want them removed from the test build as well?

**Comment by brentsimmons** [comment]
If those are viewable only in Debug, then that’s fine.
