### ISSUE TITLE
Detail view: date should be lighter text

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#2361]
Right now it looks like the same gray percentage and weight as the headline. The fix is probably just to make it 50% black or something like that. (Whatever looks good and is still easily readable.)

![Screen Shot 2020-08-16 at 1 38 56 PM](https://user-images.githubusercontent.com/1297121/90343527-0ba36e00-dfc6-11ea-9464-4910daa109cd.png)

**Comment by vincode-io** [comment]
What do you want to do about the case where there isn't a title and the permalink basically becomes the title?  Do you want it to stay the darker gray or take on the lighter title color?

**Comment by brentsimmons** [comment]
It should take on the color that the title would have, if there were a title.
