### ISSUE TITLE
Sidebar: restore width on relaunch

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#2362]
Even with the global setting (system preference) “Close windows when quitting an app” set, we should restore the sidebar width on relaunch.

Here’s what happens now:

Before quitting…

![BeforeQuit](https://user-images.githubusercontent.com/1297121/90344536-74dbaf00-dfcf-11ea-9cb4-504f54bc908a.png)

…after relaunching…

![AfterRelaunch](https://user-images.githubusercontent.com/1297121/90344543-7b6a2680-dfcf-11ea-8f7d-a70f44a88678.png)

**Comment by vincode-io** [comment]
I can't recreate this one either.  I tried all different sizes and with the System Preference toggled both ways.  This may have also gotten resolved at the same time as #2345.  Please reopen if you can recreate again.
