### ISSUE TITLE
Star icon should be white when selected

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#2364]
![Screen Shot 2020-08-16 at 3 04 49 PM](https://user-images.githubusercontent.com/1297121/90344782-e1f04400-dfd1-11ea-8e73-ae3bd1a24bcd.png)

**Comment by vincode-io** [comment]
Do we want to switch this to using a flat resource so that it can be tinted like we do on iOS and Big Sur?  If we want to keep the 3D look, maybe we could get a white 3D star graphic asset?

**Comment by brentsimmons** [comment]
Yes, let’s switch to a flat resource that we can tint.
