### ISSUE TITLE
Is there a way to download a select number of articles per feed in NNW, or a way to move the database?

### ISSUE THREAD

**Issue by gitatmax** [Ranchero-Software/NetNewsWire#2370]
I use Feedbin to manage my feeds and NNW to read them everywhere; I love it. On my Mac, my article DB is getting large; is there a way to either move it to an external or a way to limit the number of feeds NNW will save locally? Thanks!

**Comment by brentsimmons** [comment]
We’ve recently added some code that will prune the databases more aggressively, so they won’t get so large.

In the meantime, you could quit NetNewsWire, run a SQLite vacuum on your database, then relaunch NetNewsWire. This would make your database smaller.

**Comment by gitatmax** [comment]
@brentsimmons Thank you!
