### ISSUE TITLE
Article view - light mode - colors for author name and date should match 5.0.4

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#2379]
In this screenshot, 5.0.4 is at the top and 5.1 at the bottom. The colors for the author name “Jason Kottke” and the date should match 5.0.4.

**Comment by vincode-io** [comment]
It looks like you forgot the screenshot.  I think I had this fixed before you filed this bug, but correct me if I'm wrong.  Here is a screenshot from a current build.

![Screen Shot 2020-08-25 at 4 28 45 PM](https://user-images.githubusercontent.com/16448027/91229890-32615300-e6f0-11ea-84b8-78d19fbc4814.png)

**Comment by brentsimmons** [comment]
__
