### ISSUE TITLE
Support image enclosures

### ISSUE THREAD

**Issue by j-f1** [Ranchero-Software/NetNewsWire#2380]
I follow the NASA Image of the Day RSS feed (https://www.nasa.gov/rss/dyn/lg_image_of_the_day.rss), which uses the following format:

```xml
<item>
  <title>Defining Radiation Risk to Astronauts</title>
  <link>http://www.nasa.gov/image-feature/defining-radiation-risk-to-astronauts</link>
  <description>In this image, one of the radiation detectors for the Radi-N2 experiment floats in the space station. This device will help researchers explore the radition risk to humans in space.</description>
  <enclosure url="http://www.nasa.gov/sites/default/files/thumbnails/image/2_iss035e031921_0.jpg" length="846869" type="image/jpeg"/>
  <guid isPermaLink="false">http://www.nasa.gov/image-feature/defining-radiation-risk-to-astronauts</guid>
  <pubDate>Mon, 24 Aug 2020 02:16 EDT</pubDate>
  <source url="http://www.nasa.gov/rss/dyn/lg_image_of_the_day.rss?title_no=79544">NASA Image of the Day</source>
</item>
```

Note that it has its image embedded as an `<enclosure type="image/jpeg">` tag. As far as I can tell, these enclosure values are not used anywhere. That means that the image of the day cannot be viewed without tapping or clicking on the link to open the web page (the reader view does not support displaying the image either due to client-side JS).  Would it be possible to display image attachments at the beginning or end of the content, or would it be better for me to contact NASA to see if they are willing to change the feed to include the image another way/should I just make my own feed?

**Comment by brentsimmons** [comment]
They shouldn’t assume that RSS readers will do anything with image enclosures. Instead, they should link to those images as part of the HTML body of each item.

**Comment by lukekrikorian** [comment]
I think this could be reopened as image enclosures are [semantically correct RSS](https://www.rssboard.org/rss-specification#ltenclosuregtSubelementOfLtitemgt) and not [only for podcasts](https://github.com/Ranchero-Software/NetNewsWire/issues/3131#issuecomment-848376537), unless I'm mistaken.

**Comment by gingerbeardman** [comment]
I also think this should be reopened for the reason stated above.

**Comment by brentsimmons** [comment]
The main issue is that this would mean parsing enclosures for every single feed, which would make the parser slower. It also means adding columns to the database for storing enclosures, which will make database operations in general slower. It’s a performance hit that everyone would suffer while it would benefit few feeds.

That’s not to say we’d never do it! I’m just explaining the trade-off.

**Comment by gingerbeardman** [comment]
Understood.

I'll keep one eye on NetNewWire, meanwhile I'll have to stick with Newsify. Their macOS app is Catalyst, so pretty terrible all said, but browsing my feeds is so much quicker with visible thumbnails. Here are some screenshots to illustrate my situation.

NetNewsWire
![Screen shot 2022-02-05 at 14 51 34](https://user-images.githubusercontent.com/49612/152646985-6e12f70d-ad92-40c3-9777-41a2afb917e3.png)

Newsify
![Screen shot 2022-02-05 at 14 52 15](https://user-images.githubusercontent.com/49612/152646994-5670802f-8369-445f-a269-49ffc6d6d1ac.png)

**Comment by gingerbeardman** [comment]
Wait, I just realised, the feed in my example above is _not using enclosures_!

RSS: https://politepol.com/fd/UAWxeIa8I3Lk
Contents: https://gist.github.com/gingerbeardman/a96871572d0016025b6409ba7e30e107

So, Newsify is getting the image is from the main content of the article.
