### ISSUE TITLE
Cannot set NNW as default RSS reader in Preferences

### ISSUE THREAD

**Issue by jaanus** [Ranchero-Software/NetNewsWire#2381]
Version: NNW 5.1d3 (3003)
OS: Catalina 10.15.6 (19G2021)

How to reproduce: Open NNW preferences. Observe that another reader is default RSS reader. Try to set NNW as default reader.

Observed: preference does not change.

Expected: NNW is set as default reader.

See the attached video.

[NNW as default.mov.zip](https://github.com/Ranchero-Software/NetNewsWire/files/5121820/NNW.as.default.mov.zip)

**Comment by vincode-io** [comment]
This looks like it is because the app is sandboxed.  `LSSetDefaultHandlerForURLScheme` is returning -54.

https://stackoverflow.com/questions/26601840/making-app-default-handler-on-osx-10-10-with-sandbox-enabled

**Comment by brentsimmons** [comment]
Damn.

Do we have any options besides not sandboxing?

**Comment by vincode-io** [comment]
I don't think so.  I've been trying to find some kind of entitlement we could add, but searching the web isn't turning up anything.

**Comment by brentsimmons** [comment]
Maybe somebody on Twitter has a good idea? https://twitter.com/brentsimmons/status/1300571980488294402

**Comment by heckj** [comment]
🤦 That's a real bite on the whole sandboxing setup, isn't it. I'll also do what digging I can...

**Comment by galad87** [comment]
An unsandboxed XPC service to simply change the default RSS reader would be a solution (outside of the app store).

**Comment by vincode-io** [comment]
After rereading the comments on your Twitter post, I'm for removing the feature.  I lot of people feel strongly that apps should be sandboxed.  I feel like they should be, if possible.

You were leaning toward a separate utility and I think that would be a good idea.  There isn't any reason that it couldn't be a SwiftUI app and I think we would have plenty of volunteers willing to write it.  If didn't give any preference to the RSS reader, I think it would be useful to the Mac/RSS ecosystem in general.

**Comment by brentsimmons** [comment]
Agreed. Let’s do the separate app and remove this feature from 5.1.

**Comment by jaanus** [comment]
Makes sense to have a separate utility app. What would NNW preferences show about it?
1) nothing at all, completely disappears from NNW UI?
2) link to a web destination that provides the utility app and more information?

**Comment by rway7** [comment]
I'm running macOS 11.3.1, can confirm that `LSSetDefaultHandlerForURLScheme` is working fine in the sandbox.
