### ISSUE TITLE
Hide Read Articles not sticky

### ISSUE THREAD

**Issue by emmschool** [Ranchero-Software/NetNewsWire#2382]
If I select 'Hide Read Articles' it works fine but when I move to the next Feed, read articles will be shown again. I would expect that setting to apply to all feeds.

This is in version 5.1d3 (3003)

**Comment by MaineSoNewOrleans504** [comment]
Fix

**Comment by vincode-io** [comment]
This is by design.  The filter is remembered on a per feed basis.  Once you set it on a feed it stays set for that feed.  We realize some might want the other behavior, but we don't have any plans to change it at this time.

**Comment by emmschool** [comment]
I understand that this is a setting per feed but it is not sticky ie I view a feed and set the filter to Unread only. I go back to that feed the next day and the filter is unset. This is not the expected behaviour.

I'm currently on version 5.1.1 (3012) and using Feedly.
