### ISSUE TITLE
Feature Request: Always Show Starred Smart Feed

### ISSUE THREAD

**Issue by garbonsai** [Ranchero-Software/NetNewsWire#2386]
When the show/hide read articles toggle is active, the starred articles smart feed is hidden unless there are starred articles that have also been marked unread. This feels wrong to me, as it requires two steps to get back to something important that I started reading but didn't finish—either I have to mark an article as unread *and* star it, or I have to star it *and* remember to deactivate the show/hide articles toggle.

I think a better option would be to exclude all three smart feeds (or at the very least the starred smart feed) from being affected by the show/hide read articles toggle to make it easier to find / remember to get back to important articles.

**Comment by michaelclach** [comment]
Agreed!

**Comment by DavidWJ19** [comment]
+1 on this.

**Comment by vincode-io** [comment]
This is already there in the iOS 6.0 release and will be in the upcoming mac 6.0.3 release.

**Comment by DavidWJ19** [comment]
I should have said that I was speaking to OS X. I am aware of it in iOS. Thank you for your reply.
