### ISSUE TITLE
Bulk import list of feed URLs

### ISSUE THREAD

**Issue by jsit** [Ranchero-Software/NetNewsWire#2387]
I'd love to be able to import a newline-separated list of multiple feed URLs all at once

**Comment by brentsimmons** [comment]
You can import multiple feed URLs via OPML. Will that work for you?

**Comment by jsit** [comment]
Sometimes I have a list of feed URLs that aren't formatted as OPML. I could wrap these in simple `<outline xmlUrl=""/>` tags, but that won't import their titles correctly.

**Comment by brentsimmons** [comment]
OPML does have a title field.

**Comment by jsit** [comment]
Oh sure, I just mean, if I don't know their titles, I would have to enter that manually. I suppose an alternative to this feature request could be to retrieve feed titles in imported OPML if they aren't explicitly provided.

**Comment by brentsimmons** [comment]
Ah. You can leave off titles and NetNewsWire will pull them from the feed itself.

**Comment by jsit** [comment]
When importing OPML? I swear I just tried that this morning and it didn't work. I'll take another look, thanks.

**Comment by jsit** [comment]
```xml
<?xml version="1.0" encoding="UTF-8"?>
<opml>
<outline text="no titles">
  <outline xmlUrl="https://feeds.npr.org/1007/rss.xml"  />
</outline>
</opml>
```

**Comment by vincode-io** [comment]
@jsit What kind of account are you using?  On My Mac, Feedbin, or Feedly?

**Comment by jsit** [comment]
On My Mac

**Comment by vincode-io** [comment]
I tested this today and it worked for On My Mac accounts for me. Is it possible that you have previously subscribed to this feed?  We save metadata, like feed name, so that you can undelete feeds.  You might want to create a new On My Mac account and see if you get feed titles then.

**Comment by jsit** [comment]
Hey you're right! It must have been a caching issue. Thanks!

**Comment by vincode-io** [comment]
It looks like we got this one figured out.  Closing the issue.
