### ISSUE TITLE
Cannot get unread count badge on Dock icon until you request notifications for new items on some feed

### ISSUE THREAD

**Issue by AngeloStavrow** [Ranchero-Software/NetNewsWire#2390]
In fixing #2058, the user is no longer prompted to allow notifications that show the unread count badge on the Dock icon. The only way to get this back is to select some feed, go to Window > Info in the menu, and enable "Notify About New Articles" to get the allow-notifications prompt.

IIRC the original behaviour was to just prompt for notification permissions on first launch.

One solution could be to add a "Show Unread Count On Dock Icon" setting to the preferences window that then prompts the user to allow notifications. This would decouple getting notifications about new articles from seeing the unread-count badge.

**Comment by vincode-io** [comment]
Since we show the unread count by default, this solution would only work if we change that behavior.

I thought I had this fixed in #2375.  @AngeloStavrow could you verify that it is or isn't fixed?

**Comment by AngeloStavrow** [comment]
Sure, @vincode-io! I didn't see #2375 and while it seems to repopulate the NNW entry in the Notifications prefpane, it doesn't seem to fix a specific scenario — here's how I tested the issue on NNW 5.1d3 (3003):

0. Quit NetNewsWire if it's running
1. Open Settings > Notifications
2. Find NetNewsWire in the list and select it, then press <kbd>Delete</kbd> on your keyboard to remove the setting
3. Launch NetNewsWire and observe that the Dock icon does not show the unread count badge
4. Open NetNewsWire preferences and verify if _Show unread count_ is enable
5. Toggle the _Show unread count_ preference until it's enabled

## Expected

Re-enabling the _Show unread count_ preference prompts the user to allow notifications.

## Actual

No prompt is presented and the unread count badge does not appear on the dock icon; the NetNewsWire entry returns to the Notifications pref pane, but it is set to _Off_.

## Workaround

User must enable notifications for some feed via the web feed inspector to get the prompt to allow notifications.

---

I haven't dug into the code, but it looks like the issue is that checking/unchecking the _Show unread count_ setting in NNW's preferences doesn't check to see if it's still authorized to send notifications.

**Comment by vincode-io** [comment]
I think it does make sense to prompt again if setting is off and we are trying to enable it.

**Comment by vincode-io** [comment]
@AngeloStavrow I'm assigning to you since you expressed an interest.
