### ISSUE TITLE
Article list for a Tumblr photo feed looks strange

### ISSUE THREAD

**Issue by jaanus** [Ranchero-Software/NetNewsWire#2391]
NNW: Version 5.1a2 (3004)
OS: Catalina 10.15.6 (19G2021)

Observed: a feed which consists mostly of photos looks weird in article list. Lots of blankness. Everything is technically correct, but user experience is weird.

Expected: less weird representation in article list. Not sure what exactly that would be.

Feed URL: http://screenshotsofdespair.tumblr.com/rss

<img width="1140" alt="Screenshot 2020-09-02 at 10 19 02" src="https://user-images.githubusercontent.com/184253/91956236-0d329d00-ed0d-11ea-9d77-f82ee232123d.png">

**Comment by jaanus** [comment]
I note that it looks even stranger on iOS 14, where the posts are in some kind of more collapsed state.

I am also attaching the RSS contents that produced the layout on iOS 14.

![PNG image](https://user-images.githubusercontent.com/184253/96964749-ad3dc300-1513-11eb-91fc-4a660d1ea3d2.png)


[screenshots-of-despair.rss.zip](https://github.com/Ranchero-Software/NetNewsWire/files/5427730/screenshots-of-despair.rss.zip)

**Comment by vincode-io** [comment]
@brentsimmons Do you have any ideas what we want to do here?  I'm not a fan of providing default text for missing values, but I can't think of anything else to do.  We do need to implement a minimum table row height for iOS, but I'm not sure what to do about macOS or if we need to do something more for iOS.

**Comment by brentsimmons** [comment]
How about this: if there’s no title and no text, we just show “(No Text)” as a string, using the body font/color (instead of title font/color). On both platforms.

**Comment by jaanus** [comment]
🎉
