### ISSUE TITLE
Can not enable notifications on iOS 

### ISSUE THREAD

**Issue by Scarysize** [Ranchero-Software/NetNewsWire#2395]
Hey, NetNewsWire is not showing up in the notifications settings anymore. Which means I can’t configure the badge count for unread messages...

I’ve migrated from a 7 to an iPhone SE. Currently running 13.7. NetNewsWire is v 5.0.3 (Build 50).

**Comment by Scarysize** [comment]
Screenshots from the iPhone 7 and SE respectively. Both run the same NetNewsWire version, but the 7 runs on iOS 13.6.1.

<img width="375" alt="PNG image" src="https://user-images.githubusercontent.com/10571630/92300553-457bea80-ef5c-11ea-9b3f-51f9ffb6c69a.png">
<img width="375" alt="PNG image 2" src="https://user-images.githubusercontent.com/10571630/92300558-4ca2f880-ef5c-11ea-9f3c-c271656c9e74.png">

**Comment by vincode-io** [comment]
It looks like NNW may not be installed correctly.  Could you do me a favor and delete the app and then reinstall it?

**Comment by Scarysize** [comment]
After reinstalling the app the "Mobile Data" preference is now shown (in addition to Siri & Background App Refresh as seen in the last screenshot). But still no notification settings...

**Comment by vincode-io** [comment]
I'm going to be honest.  I have no idea what is happening on that particular phone.  I wish I could help you more.  Something must have gone wrong when you migrated to the new phone, but I have no clue what it could be.  If you figure it out or are able to correct it, please update us.  In the mean time, I'll keep investigating to see if there is anything we can do.

**Comment by Scarysize** [comment]
Okay, let me know if I can provide you with any debug information/log etc. from the version & phone I'm running. Eager to help!

**Comment by sheepworrier** [comment]
I have the same issue on iOS 13.6.1 and 13.7 and 14 on my iPhone 11 Pro

**Comment by vincode-io** [comment]
Has anyone in this thread tried to set a notification using the Feed Inspector yet?  It should prompt you for permission to use notifications as a work around for this problem.

**Comment by sheepworrier** [comment]
> Has anyone in this thread tried to set a notification using the Feed Inspector yet? It should prompt you for permission to use notifications as a work around for this problem.

Brilliant! That fixed it for me

**Comment by Scarysize** [comment]
Yep for me too, thanks a lot! Do you want to keep this issue open as this is just a workaround?

**Comment by vincode-io** [comment]
We'll be addressing this issue under #2447 and this will get fixed in 5.0.4.
