### ISSUE TITLE
Multiple sidebar selection should not result in empty timeline

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#2399]
The timeline should be the union of articles.

**Comment by vincode-io** [comment]
I'm not able to recreate this.  Could you post a screenshot of it happening?  Maybe I can figure out how to recreate it from the screenshot.

**Comment by brentsimmons** [comment]
I think I figured it out — it’s showing only unread articles.

**Comment by vincode-io** [comment]
Yeah, I made it that way since the default behavior for Folders is to only show unread articles.  Because multiple selection doesn't have a way to save the unread filter state, I figured this would be the correct behavior.

**Comment by brentsimmons** [comment]
Let’s make it so that it’s the union of what you would see if you clicked each item individually, respecting the filter settings of each individual item.
