### ISSUE TITLE
Article is opened unexpected

### ISSUE THREAD

**Issue by doekman** [Ranchero-Software/NetNewsWire#2405]
For starters, this is not a NetNewsWire bug, since Finder has the same behaviour. It's only that with NNW it happens to me every now-and-then. Maybe there is something you guys can do.

Take this scenario:

1. Just finished reading an article in Safari.
2. I want to go back to NNW to select a new article in the current selected feed.
3. With Safari active, and NNW inactive, but both applications in view, in NNW I click on an article that is not yet selected.
4. The article doesn't get selected, so I click one more time (being a bit impatient). This probably is interpreted as a double click
5. Result: NNW becomes active, _and_ opens the article in Safari. 

I do have the setting that NNW opens pages in the background, so after step 5, Safari is still inactive. But that doens't mather to this issue.

Not sure what is proper expected behaviour, but I want to _select_ the article so the contents come into view, and the NNW window to be active. When I click twice, but more slowly (more time between clicks) this will be interpreted as two single clicks. The first click will make NNW active, and the second click will select the article.

I think the confusion with me about this behaviour is the following: 

- a _single click_ on an non-active window is making the window active, but the application doesn't respond to the event itself
- a _double click_ on a non-active window is making the window active, and the application is interpreting this double click as if the application was already activated.

Does this make sense? It's probably some OS X/macOS thing, but can you shine some more light on this?

**Comment by blackketter** [comment]
I had a similar issue with a different app that was resolved by speeding up the double-click speed in System Preferences->Accessibility->Pointer Control.  I had inadvertently set it to be very slow at some point and hadn't noticed.

**Comment by doekman** [comment]
I have a real mouse, so the setting is there also with the Mouse preference. But this helps.

I'm now at one off the highest setting. But I might put it one step back, because now I miss some double clicks. But I haven't had any trouble with NNW.
