### ISSUE TITLE
macOS Big Sur - Selection in Article List Not Visible

### ISSUE THREAD

**Issue by daboyter** [Ranchero-Software/NetNewsWire#2407]
OS: 11.0 Beta (20A5364e)
NNW: Version 5.1b1 (3005)

When selecting an article from the article list the text disappears and the colored highlight doesn't show up. Attaching screenshots.

It could be an OS bug, but Mail seems to be working ok.

![Screen Shot 2020-09-09 at 9 17 29 AM](https://user-images.githubusercontent.com/16779656/92647561-11832b00-f2b6-11ea-966c-c5c2c5847d2b.png)
![Screen Shot 2020-09-09 at 9 17 27 AM](https://user-images.githubusercontent.com/16779656/92647563-11832b00-f2b6-11ea-8c06-8d7dd1ef671e.png)
![Screen Shot 2020-09-09 at 9 17 19 AM](https://user-images.githubusercontent.com/16779656/92647564-11832b00-f2b6-11ea-886b-0430896ab5ef.png)

I don't know how helpful bug reports for Big Sur are right now, but thought I'd file just in case. Just close it out if you want me to re-file after Big Sur release.

**Comment by jaanus** [comment]
I just encountered this in a completely unrelated app (Git Tower) on Big Sur. It really feels like a system bug.

**Comment by vincode-io** [comment]
This issue was resolved by Apple in macOS 11 Beta 7.  Please upgrade if you are experiencing this problem.
