### ISSUE TITLE
macOS: Add per-feed "Always Show Reader View" option, like on iOS

### ISSUE THREAD

**Issue by blackketter** [Ranchero-Software/NetNewsWire#2408]
NNW on iOS has per-feed settings that include "Always Show Reader View".  Would love to have this on macOS too!

**Comment by brentsimmons** [comment]
It’s there — it’s in the inspector. (Window > Info)

**Comment by blackketter** [comment]
Aha, thanks @brentsimmons my bad. 

I suppose this is a discoverability bug, I did try pretty hard to find it, looked for Get Info in File menu, tried right-clicking on the feed name, looked at the toolbar editor, even looked in the documentation. :). Should have tried command-I

I suggest that it get added to some or all of those places to make it easier to find for those who come after me.

**Comment by phymann** [comment]
I come here just to say it is indeed really hard to find this option...
