### ISSUE TITLE
iOS 14: Starred smart list item has a grey background

### ISSUE THREAD

**Issue by pdokas** [Ranchero-Software/NetNewsWire#2414]
![image](https://user-images.githubusercontent.com/190134/92779654-1ba93600-f357-11ea-8e2a-a4d8c00fa83d.png)

In the main feed list the Starred smart list has a grey background behind the ⭐ icon in both light mode and dark mode.

iOS 14 public beta 7 / NNW TestFlight 5.0.3 (50)

**Comment by lorenzolewis** [comment]
I'm running NNW public 5.0.4 (build 53) and iOS public 14.0.1 and not seeing this issue. Could you confirm if this still exists in the latest software versions for you?

**Comment by pdokas** [comment]
Yep, it is with the same NNW and iOS versions. I've noticed it's not **always** wrong, but I've also noticed that launching it from a cold state, e.g. after force quitting it will reliably trigger the background layer behind the star.

**Comment by vincode-io** [comment]
This issue has been addressed and will be in the next bug fix release.
