### ISSUE TITLE
Make keyboard navigation select a saner default article in the list view

### ISSUE THREAD

**Issue by doekman** [Ranchero-Software/NetNewsWire#2420]
I like to read my articles feed-by-feed, and from oldest-to-newest (smart feeds are smart, but just not for me). I really love the keyboard navigation with the arrows.

When you have a feed selected, you press right to select the list view. With up/down you select an article. With right you select the article view, so you can scroll down to read the article. After that you can press left to select the list view again, and select another article.

However, when selecting an other feed, and then select the list view, the top article is automatically selected. Since I want to read from old-to-new, I select the oldest unread article with my mouse.

A possible solution to this problem would be to store the last selected article (per feed), and to restore this when the feed is selected again. This way, no new keyboard shortcuts would need to be defined to achieve the same result.

I think it might be part of this issue: https://github.com/Ranchero-Software/NetNewsWire/issues/300. I'm on NNW Version 5.1b1 (3005) and my proposed behaviour doesn't seem present (Folder state restoration does work now: 👍).

**Comment by brentsimmons** [comment]
What if you reverse the sort order, so the oldest article is at the top of the timeline?

**Comment by doekman** [comment]
That solves the issue that articles are marked as read, when using keyboard only. I could also press option+down. But in either case, I need to scroll past the read articles. Screenshot below demonstrates the problem more clearly.

You could also make a keyboard shortcut moving to latest unread. But that wouldn't be the same, since there can be holes in the read list. Moving to the oldest read article would also not be the same, because that action would mark the item as read. Although I wouldn't consider that as a problem for my use case.

<img width="616" alt="Schermafbeelding 2020-09-15 om 18 10 47" src="https://user-images.githubusercontent.com/1086388/93236183-cae27480-f77e-11ea-99bc-b8aadf442996.png">

**Comment by vincode-io** [comment]
@doekman Have you tried a workflow where you sort oldest-to-newest and then engage the timeline read filter?  That's how I do it and find that it works well if you are reading oldest-to-newest.

**Comment by doekman** [comment]
Yes, that works. The sorting appears to be a application-setting, and the filter is a feed-setting, but I'll live.

BTW: I now recognize the filter-icon from Mail.app. I always thought it was a bit scrary for some reason. There is not a lot of discoverability about it but to try it. Thought I'd share this.
