### ISSUE TITLE
Update Deleted all of My Feeds

### ISSUE THREAD

**Issue by macdaddy1944** [Ranchero-Software/NetNewsWire#2421]
The latest update reverted to the default feeds. Fortunately I had a recent backup.

**Comment by kielgillard** [comment]
@macdaddy1944 Is what you are reporting different from what was mentioned in the release notes for this beta? For this beta specifically, this was an expected side effect. For the release notes, see: https://nnw.ranchero.com/2020/09/15/netnewswire-b-for.html

**Comment by macdaddy1944** [comment]
I guess I missed that. Sorry.

**Comment by kielgillard** [comment]
All good. If you're not sure you have all your data, check out the section "How to Migrate Your Old Data" in the [release notes](https://nnw.ranchero.com/2020/09/15/netnewswire-b-for.html).

**Comment by include** [comment]
err missed this migration too :(. BTW your blog is down. Can you please bring it up for me to read the release note and recover my feeds :) thank you very mucho :)
