### ISSUE TITLE
Is this meant to be the icon for ‘On My Mac’?

### ISSUE THREAD

**Issue by paulrobertlloyd** [Ranchero-Software/NetNewsWire#2422]
Don’t know if it has always been this way, but re-adding my account after installing the latest beta, I saw the ‘On My Mac’ icon on the account screen, and thought it looked like a placeholder, almost like a missing character glyph `□`.

<img width="624" alt="Screenshot 2020-09-16 at 19 38 36" src="https://user-images.githubusercontent.com/813383/93378519-7c9fa500-f854-11ea-8a95-6af956d35fc3.png">

**Comment by brentsimmons** [comment]
Not a placeholder! :) Represents a computer screen.
