### ISSUE TITLE
Option to change modifier keys

### ISSUE THREAD

**Issue by ErniePC12** [Ranchero-Software/NetNewsWire#2424]
I find that the Command key is larger than the Option key.  

Is there a way that the keys could be swapped around, maybe as a user selection?

**Comment by lorenzolewis** [comment]
Are you talking about in macOS? You want to switch the modifier key from say for example Command-N to Option-N? 
This is probably outside the scope of this project, but you could try referring to https://osxdaily.com/2017/08/08/create-custom-keyboard-shortcut-mac/ and see if that helps as it isn't specific to just NetNewsWire

**Comment by vincode-io** [comment]
This issue isn't specific to NNW, so I'm going to go ahead and close this issue.
