### ISSUE TITLE
Footnotes have bad contrast

### ISSUE THREAD

**Issue by ArttuLai** [Ranchero-Software/NetNewsWire#2425]
I noticed that footnote numbers are very hard to read. Could those numbers use a different color?

##### Light mode
<img width="97" alt="netsnews-badContrast2" src="https://user-images.githubusercontent.com/42007282/93591493-3021aa00-f9b9-11ea-96b8-9a6eaa4f68ad.png">

##### Dark mode
<img width="173" alt="netnews-badContrast" src="https://user-images.githubusercontent.com/42007282/93591792-b0480f80-f9b9-11ea-8acc-315b336caccb.png">

**Comment by Wevah** [comment]
FTR: This is caused by `a:link`/`a:visited` having higher specificity than a naked `a`.

**Comment by vincode-io** [comment]
This is fixed and will be in the next beta build.
