### ISSUE TITLE
Previous OS X compatibility

### ISSUE THREAD

**Issue by jon-daemon** [Ranchero-Software/NetNewsWire#2429]
Is it possible to support previous OS verions?
I use 10.13.6 for my everyday jobs and I'd really like to see NetNewsWire supported by my OS.

**Comment by ErniePC12** [comment]
I noticed that it does not work for macOS Mojave 10.14 as well.

**Comment by brentsimmons** [comment]
We address this question in our FAQ: https://ranchero.com/netnewswire/frequently-asked-questions

The gist is that we concentrate on app quality and features over supporting older versions of iOS and macOS.

We make several older versions of NetNewsWire for Mac available here: https://ranchero.com/netnewswire/old-versions

**Comment by UnderEu** [comment]
If you're really that into "app quality", you should work with OS versions who works w/ no hassle, no "notarization" BS, no "App needs your permission to access Internet", no "App needs your permission to store things on your disk drive", no "App needs your permission to show notifications", no "App needs your permission to blah blah blah..."... 

That's a shame! This had everything to be my main RSS feed on macOS but not anymore - and NO, I WON'T UPDATE MY MACHINE FROM MOJAVE TO ANYTHING ELSE!!!
