### ISSUE TITLE
Starred Smart Feed?

### ISSUE THREAD

**Issue by michaelclach** [Ranchero-Software/NetNewsWire#2430]
I can't seem to find this on MacOS 5.1. I've a bunch of (old, read) articles that are marked starred and I can't figure out how to get to them.

**Comment by brentsimmons** [comment]
Had you collapsed the Smart Feeds section?

**Comment by michaelclach** [comment]
Yes, but when I toggle between hide and show I only see Today and All Unread. I'm sure I've missed something obvious...

**Comment by brentsimmons** [comment]
Did you turn on View > Hide Read Feeds? That could explain it.

**Comment by michaelclach** [comment]
Yeah, that's it. Sorry, thanks for the help.
