### ISSUE TITLE
Feeds deleted from "On My Mac"

### ISSUE THREAD

**Issue by beaucollins** [Ranchero-Software/NetNewsWire#2431]
I'm running the "Test Builds".

Between launching after updating all on my feeds were deleted from my mac.

The "Name" of the "On My Mac" account was "🚀". Can't seem to find any record of this information anywhere in `~/Library/Application\ Support`.

Not exactly sure which version I had updated from but currently running `Version 5.1b2 (3006)`

**Comment by brentsimmons** [comment]
Migration instructions are here: https://nnw.ranchero.com/2020/09/15/netnewswire-b-for.html

**Comment by beaucollins** [comment]
Thanks, I promise I searched the issues first. I'm not subscribed to the NNW blog, time to fix that!
