### ISSUE TITLE
"Check for updates" doesn't know about 5.1

### ISSUE THREAD

**Issue by kach** [Ranchero-Software/NetNewsWire#2433]
I'm running NNW 5.0.4 on macOS 10.14.6. I saw the announcement for NNW 5.1, but "Check for updates" doesn't seem to have realized that it's available yet!

<img width="532" alt="image" src="https://user-images.githubusercontent.com/5202416/93705814-5177b880-fad5-11ea-803b-1150f66608de.png">

(In any case, thanks for creating this wonderful piece of software!)

**Comment by kielgillard** [comment]
Hello @kach, thanks for your interest and taking the time to share this feedback. NetNewsWire 5.1 requires macOS 10.15 or later.

https://nnw.ranchero.com/2020/09/19/netnewswire-for-mac.html

**Comment by kach** [comment]
Ohp, my bad for not seeing that! Thanks for clarifying. I guess I'll stick with 5.0.4 for now. :)
