### ISSUE TITLE
All folders with their feeds disappeared

### ISSUE THREAD

**Issue by doekman** [Ranchero-Software/NetNewsWire#2434]
I just upgraded to NNW 5.1, but all my folders have disappeared, and it seems I now only have the default set.

I started with 5.1b1 (not sure why, I have the Release builds checked in the preferences), then pressed Check for Updates, and that installed 5.1b2. Then I pressed again, and 5.1 got installed.

I do have a time machine backup from a couple of days old. How can I get my feeds back?

**Comment by jamadden** [comment]
@doekman: This looks like #2421 Have you followed the "how to migrate your data section" in [the release notes](https://nnw.ranchero.com/2020/09/15/netnewswire-b-for.html)?
