### ISSUE TITLE
Sort dropdown in the UI feels heavy-handed, obtrusive

### ISSUE THREAD

**Issue by heymarkreeves** [Ranchero-Software/NetNewsWire#2435]
Hello!

I'm finding that the new "Newest/Oldest Article on Top; Group by Feed" dropdown in the UI is disruptive to the reading experience. The toolbar can be hidden—why can't this? Everything else in the window is an article title or the article itself. This feels very disruptive, especially when its 3 limited options are available at the top of the View menu, too.

**Comment by brentsimmons** [comment]
Is this still an issue? I suspect this refers to an earlier version of the UI.

**Comment by heymarkreeves** [comment]
I haven't used the desktop app in a while—I use the iPadOS app daily—and can't find what I was describing looking at it now. I suspect you're right! Thanks for the reply.
