### ISSUE TITLE
Cannot write in search field with external keyboard

### ISSUE THREAD

**Issue by odmir** [Ranchero-Software/NetNewsWire#2437]
Hello! Attempting to write in the search field using an external keyboard on an iPad running iPadOS 14.2 is impossible as it triggers the single-key keyboard shortcuts defined in the app, resulting in all kinds of actions like marking everything as read. I can give more details if necessary.

**Comment by rizwankce** [comment]
Looks like this is a bug on OS. `UIKeyCommand` is not disabled when we focus on a text field. 
But we can get it working with a hack mentioned [here](https://stackoverflow.com/questions/37356815/uikeycommand-is-not-disabled-when-typing-into-a-text-field-swift)

Basically, whenever user is focusing on a text field, we remove key commands and add them back from a view controller

**Comment by vincode-io** [comment]
@rizwankce This looks like the way to go.  Do you have time to implement this or do you want me to take it over?

**Comment by vincode-io** [comment]
BTW, I hit this problem on another side project that I have and think that this is a cleaner solution: https://stackoverflow.com/a/58342531  

I think we should probably put the UIResponder extension in RSCore so that it can be reused on other projects.
