### ISSUE TITLE
Does anyone have a doc for the css changes that will make NNW readable?

### ISSUE THREAD

**Issue by frankleahy3** [Ranchero-Software/NetNewsWire#2438]
I've been playing around with shared.css and stylesheet.css and have changed the detail view to something reasonable, but I really want to change the list view to make it more like the old NNW, e.g. get rid of the icon, change the font size, and add 100 chars of the feed.  Has anyone documented the changes needed and/or what's possible.  Here are my changes...minor but important.

---------------
SHARED.CSS
---------------
body {
	margin-left: auto;
	margin-right: auto;
	
	word-wrap: break-word;
	/* max-width: 44em; */
}

a {
	text-decoration: none;
}
a:hover {
	text-decoration: underline;
}
.feedlink {
	font-weight: bold;
}
.headerTable {
	width: 100%;
	height: 20px;
}

.systemMessage {
	position: absolute;
	top: 45%;
	left: 50%;
	transform: translateX(-55%) translateY(-50%);
}

:root {
	--header-table-border-color: rgba(0, 0, 0, 0.1);
	--header-color: rgba(0, 0, 0, 0.3);
	--body-code-color: #666;
	--system-message-color: #cbcbcb;
	--feedlink-color: rgba(255, 0, 0, 0.6);
	--article-title-color: #333;
	--article-date-color: rgba(0, 0, 0, 0.3);
	--table-cell-border-color: lightgray;
}

@media(prefers-color-scheme: dark) {
	:root {
		--header-color: rgba(94, 158, 244, 1);
		--body-code-color: #b2b2b2;
		--system-message-color: #5f5f5f;
		--feedlink-color: rgba(94, 158, 244, 1);
		--article-title-color: #e0e0e0;
		--article-date-color: rgba(255, 255, 255, 0.5);
		--table-cell-border-color: dimgray;
	}
}

body {
	color: var(--body-color);
	background-color: var(--body-background-color);
}

body .headerTable {
	border-bottom: 1px solid var(--header-table-border-color);
	color: var(--header-color);
}
body .header {
	color: var(--header-color);
}
body .header a:link, .header a:visited {
	color: var(--header-color);
}

body code, body pre {
	color: var(--body-code-color);
}

body > .systemMessage {
	color: var(--system-message-color);
}

.feedlink a:link, .feedlink a:visited {
	color: var(--feedlink-color);
}

.avatar img {
	border-radius: 4px;
}

.feedIcon {
	border-radius: 4px;
}
.rightAlign {
	text-align: right;
}
.leftAlign {
	text-align: left;
}

.articleTitle a:link, .articleTitle a:visited {
	color: var(--article-title-color);
	margin-top: 16px;
}

.articleDateline {
	margin-bottom: 15px;
	font-weight: bold;
}

.articleDateline a:link, .articleDateline a:visited {
	color: var(--article-date-color);
}

.articleDatelineTitle {
	margin-bottom: 15px;
	font-weight: bold;
}

.articleDatelineTitle a:link, .articleDatelineTitle a:visited {
	color: var(--article-title-color);
}

.articleBody {
	line-height: 1.2em;
}
h1 {
	line-height: 1.15em;
	font-weight: bold;
	padding-bottom: 0;
	margin-bottom: 5px;
}

pre {
	max-width: 100%;
	margin: 0;
	overflow: auto;
	overflow-y: hidden;

	word-wrap: normal;
	word-break: normal;
}

pre {
	line-height: 1.4286em;
}
code, pre {
	font-family: "SF Mono", Menlo, "Courier New", Courier, monospace;
	font-size: .8235em;
	-webkit-hyphens: none;
}

.nnw-overflow {
	overflow-x: auto;
}
/*
 Instead of the last-child bits, border-collapse: collapse
 could have been used. However, then the inter-cell borders
 overlap the table border, which looks bad.
 */
.nnw-overflow table {
	margin-bottom: 1px;
	border-spacing: 0;
	border: 1px solid var(--secondary-accent-color);
	font-size: inherit;
}
.nnw-overflow table table {
	margin-bottom: 0;
	border: none;
}
.nnw-overflow td, .nnw-overflow th {
	-webkit-hyphens: none;
	word-break: normal;
	border: 1px solid var(--table-cell-border-color);
	border-top: none;
	border-left: none;
	padding: 5px;
}

.nnw-overflow tr :matches(td, th):last-child {
	border-right: none;
}

.nnw-overflow :matches(thead, tbody, tfoot):last-child > tr:last-child :matches(td, th) {
	border-bottom: none;
}
.nnw-overflow td pre {
	border: none;
	padding: 0;
}

img, figure, video, div, object {
	max-width: 100%;
	height: auto !important;
	margin: 0 auto;
}

iframe {
	max-width: 100%;
	margin: 0 auto;
}

figure {
	margin-bottom: 1em;
	margin-top: 1em;
}

figcaption {
	font-size: 14px;
	line-height: 1.3em;
}

sup {
	vertical-align: top;
	position: relative;
	bottom: 0.2rem;
}

sub {
	vertical-align: bottom;
	position: relative;
	top: 0.2rem;
}

.iframeWrap {
	position: relative;
	display: block;
	padding-top: 56.25%;
}

.iframeWrap iframe {
	position: absolute;
	top: 0;
	left: 0;
	height: 100% !important;
	width: 100% !important;
}

blockquote {
	margin-inline-start: 0;
	margin-inline-end: 0;
	padding-left: 15px;
	border-left: 3px solid var(--block-quote-border-color);
}

/* Feed Specific */

.feedbin--article-wrap {
	border-top: 1px solid var(--header-table-border-color);
}

.wp-smiley {
   height: 1em;
   max-height: 1em;
}

/* Twitter */

.twitterAvatar {
	vertical-align: middle;
	border-radius: 4px;
	height: 24px;
	width: 24px;
}

.twitterUsername {
	margin-left: 4px;
	display: inline-block;
	vertical-align: middle;
}

.twitterTimestamp {
	font-size: 66%;
}

/*Block ads and junk*/

iframe[src*="feedads"],
iframe[src*="doubleclick"],
iframe[src*="plusone.google"] {
	display: none !important;
}

a[href*=".ads."],
a[href*="feedads"],
a[href*="doubleclick"],
a[href*="//ads."],
a[href*="api.tweetmeme"],
a[href*="delicious.com/post?"],
a[href*="digg.com/submit?"],
a[href*="google.com/bookmarks/mark?"],
a[href*="posterous.com/share?"],
a[href*="tumblr.com/share?"],
a[href*="linkedin.com/shareArticle?"],
a[href*="facebook.com/share.php?"],
a[href*="http://twitter.com/home?"],
a[href*="addtoany.com/share_save"] {
	display: none !important;
}

img[src*=".ads."],
img[src*="//ads."],
img[src*="doubleclick"],
img[src*="feedads"],
img[src*="feedburner"],
img[src*="feedblitz"],
img[src*="share-buttons"] {
	display: none !important;
}

/* Newsfoot specific styles. Structural styles come first, theme styles second */
.newsfoot-footnote-container {
	position: relative;
	display: inline-block;
	z-index: 9999;
}

.newsfoot-footnote-popover {
	position: absolute;
	display: block;
	padding: 0em 1em;
	margin: 1em;
	top: 0.75em;
	max-width: none;
	border-radius: 0.3em;
	box-sizing: border-box;
}

.newsfoot-footnote-popover {
	left: calc(-1 * (50vw - 1em));
	right: calc(-1 * (50vw - 1em));
}
.newsfoot-footnote-popover-arrow {
	content: '';
	display: block;
	width: 1em;
	position: absolute;
	top: -0.5em;
	left: calc(50% - 0.5em);
	height: 1em !important;
	transform: rotate(45deg);
	z-index:0;
}
.newsfoot-footnote-popover-inner {
	border-radius: calc(0.3em - 1px);
	padding: 1em;
	position: relative;
	z-index: 1;
}

.newsfoot-footnote-popover-inner :first-child {
	margin-top: 0;
}
.newsfoot-footnote-popover-inner :last-child {
	margin-bottom: 0;
}

.newsfoot-footnote-popover .reversefootnote,
.newsfoot-footnote-popover .footnoteBackLink,
.newsfoot-footnote-popover .footnote-return {
	display: none;
}

sup[id^='fn'] {
	vertical-align: baseline;
}

a.footnote {
	display: inline-block;
	text-decoration: none;
	padding: 0.05em 0.75em;
	border-radius: 1em;
	min-width: 1em;
	text-align: center;
	font-size: 0.8em;
	line-height: 1em;
	position:relative;
	top: -0.1em;
}

/* light / default */
.newsfoot-footnote-popover {
	background: #ccc;
	box-shadow: 0 2px 4px rgba(0, 0, 0, 0.5), 0 3px 6px rgba(0, 0, 0, 0.25);
	color: black;
	padding: 1px;
}
.newsfoot-footnote-popover-arrow {
	background: #fafafa;
	border: 1px solid #ccc;
}
.newsfoot-footnote-popover-inner {
	background: #fafafa;
}
body a.footnote,
body a.footnote:visited,
.newsfoot-footnote-popover + a.footnote:hover {
	background: #aaa;
	color: white;
	transition: background-color 200ms ease-out;
}
a.footnote:hover,
.newsfoot-footnote-popover + a.footnote {
	background: #666;
	transition: background-color 200ms ease-out;
}

/* dark */
@media screen and (prefers-color-scheme: dark) {
	.newsfoot-footnote-popover {
		background: #444;
		color: rgb(224, 224, 224);
	}
	.newsfoot-footnote-popover-arrow {
		background: #242424;
		border: 1px solid #444;
	}
	.newsfoot-footnote-popover-inner {
		background: #242424;
	}
	body a.footnote,
	body a.footnote:visited,
	.newsfoot-footnote-popover + a.footnote:hover {
		background: #aaa;
		color: white;
		transition: background-color 200ms ease-out;
	}
	a.footnote:hover,
	.newsfoot-footnote-popover + a.footnote {
		background: #666;
		transition: background-color 200ms ease-out;
	}
}

------------------
STYLESHEET.CSS
------------------

body {
	margin-top: 5px;
	margin-bottom: 64px;
	padding-left: 10px;
	padding-right: 10px;
	font-family: -apple-system;
	font-size: 14px;
	color: #000000;
}

:root {
	--body-color: #444;
	--body-background-color: -apple-system-text-background;
	--accent-color: rgba(8, 106, 238, 1);
	--block-quote-border-color: rgba(8, 106, 238, .50);
}

@media(prefers-color-scheme: dark) {
	:root {
		--body-color: #d2d2d2;
		--body-background-color: #2d2d2d;
		--accent-color: rgba(94, 158, 244, 1);
		--block-quote-border-color: rgba(94, 158, 244, .50);
		--header-table-border-color: rgba(255, 255, 255, 0.1);
	}
}

body a, body a:link, body a:visited {
	color: var(--accent-color);
}

pre {
	border: 1px solid var(--accent-color);
	padding: 10px;
}

.nnw-overflow table {
	border: 1px solid var(--accent-color);
}

**Comment by brentsimmons** [comment]
The timeline is not HTML, so it can’t be styled with CSS. We do have several feature requests for making it customizable in various ways, so I’ll close this ticket.
