### ISSUE TITLE
5.1 release notes appear to be empty?

### ISSUE THREAD

**Issue by slater** [Ranchero-Software/NetNewsWire#2439]
Not sure if this is just when upgrading from a beta?

<img width="812" alt="Screen Shot 2020-09-20 at 20 10 16" src="https://user-images.githubusercontent.com/8721/93730581-1c737080-fb7e-11ea-9029-54ab59136e4f.png">

Or maybe that's intentional? ¯\_(ツ)_/¯

**Comment by brentsimmons** [comment]
This is normal for the beta release notes. There were no changes from the previous beta.
