### ISSUE TITLE
Unauthorized

### ISSUE THREAD

**Issue by punkish** [Ranchero-Software/NetNewsWire#2444]
I don't know what else to say. This is on OS X 10.15.6 with NNW 5.1. Clicking on the refresh button causes the following to popup

![image](https://user-images.githubusercontent.com/349242/93768299-d29a9100-fc36-11ea-9e2d-e344ae70a73c.jpeg)

**Comment by brentsimmons** [comment]
Are you using a syncing system? Which one? Has it worked previously?

**Comment by punkish** [comment]
Yes, I am using Feedly. It has been a while since I launched the Mac version of NNW. All my feeds showed up, and the previously read articles, starred, etc. all show up. But when I click the refresh button, I get that mysterious dialog. I will delete my account (from NNW) and re-add it, and report back if the error persists.

**Comment by punkish** [comment]
ooooh, even weirder. So, I deleted my Feedly account, (was warned that it can't be undone), and then re-added it. NNW asked my permission to use Feedly login to add the account. I clicked yes, entered my login creds, and NNW went to the background (Safari popped back to the foreground). That was odd. I clicked on the NNW icon on the menubar to bring it to the front, and NNW asked me to add the Feedly account again. For kicks, I repeated the cycle. And then, NNW asked me again. Now I have three copies of my Feedly account added to NNW, and it still is waiting for me to say yes a fourth time.

![image](https://user-images.githubusercontent.com/349242/93775290-dbdc2b80-fc3f-11ea-80af-c595a46b9de5.jpeg)

**Comment by punkish** [comment]
**Update:** Fwiw, deleted the two extra Feedly accounts and pressed the [ Refresh ] button. The mysterious "Unauthorized" dialog did not popup, and NNW refreshed the feeds successfully. So, two steps back, but one step forward :)

**Comment by blackketter** [comment]
I had a similar issue when updating to 5.1.  Despite being relatively careful I somehow added two Feedly accounts to NNW.  Deleted both and tried to add one again, but ended up with two. My recollection is that the adding and deleting was slow or unresponsive. At the time I chalked it up to me being impatient and clicking add or delete twice.  I did not see the Unauthorized error though.

**Comment by vincode-io** [comment]
Do we think #2448 fixed this issue?  It looks to me like we were trying to sync multiple Feedly accounts of which only one could be valid at a time.

**Comment by kielgillard** [comment]
@vincode-io yes I do expect it to prevent this issue. Some of the other feedback was to do with the UX of adding an account which lead to multiple attempts and my open pull request (to the wrong branch) attempts to deal with this aspect.

**Comment by kielgillard** [comment]
https://github.com/Ranchero-Software/NetNewsWire/pull/2468 contains all the UX fixes related to this issue. In combination with @vincode-io's duplicate account detection changes, I we've gone a long way to preventing this from happening again.

**Comment by vincode-io** [comment]
This is fixed and will be in the next beta release.
