### ISSUE TITLE
No badges

### ISSUE THREAD

**Issue by brosenz** [Ranchero-Software/NetNewsWire#2447]
I installed the latest version on my iPhone and iPad, both with iOS 14, Badges are working on iPhone but not on iPad, I noticed the app is not configurable in Notifications, what do you advise to do? Thanks

**Comment by vincode-io** [comment]
This is a known issue and will be addressed in a bug fix release.  To work around it you can enable notifications for a specific feed in the Feed Inspector (Get Info) dialog.   It will prompt you for notifications.

**Comment by vincode-io** [comment]
This is fixed and is coming in the next release.
