### ISSUE TITLE
Do not allow multiple copies of the same sync account (same sync service and username)

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#2448]
Two parts:

1. Don’t let this happen during account creation, and

2. Don’t let this happen at startup. (If there are multiple of the same account, ignore subsequent. It’s possible these need to be de-duped via a stable sort — just use guid in that case.)

**Comment by vincode-io** [comment]
@kielgillard Correct me if I'm wrong, but this won't be possible to do with Feedly because we never know the username when using OAuth.  IIRC, the people having this problem were using Feedly, so I don't know if this is going to fix what we want it to.

**Comment by kielgillard** [comment]
https://github.com/Ranchero-Software/NetNewsWire/blob/66991a85e61e5b0de12ebf6685ddd545a14a4209/Account/Sources/Account/Feedly/FeedlyAccountDelegate%2BOAuth.swift#L50

The `accessToken` and the `refreshToken` have the `username` property and the values are the user id from Feedly. I'm not sure if this is part of the OAuth spec though. But we should be able to use the Feedly user id in the path to the Account folder.

**Comment by kielgillard** [comment]
@vincode-io forgot to tag you in the reply above, sorry!

**Comment by vincode-io** [comment]
I don't think we will want to mess around with paths.  I think we will have to test each account for its type and username.  If I call `FeedlyAccountDelegate.credentials` will the credentials returned have the username populated with the Feedly username?

**Comment by kielgillard** [comment]
Yes, it should have the username. On the face of it, I would expect that approach to work.

**Comment by vincode-io** [comment]
@brentsimmons We should do this for the iOS app as well.  Which release do you want it in?

**Comment by brentsimmons** [comment]
Would this be do-able for 5.0.4 for iOS?

**Comment by vincode-io** [comment]
I think so.  I should have it done tomorrow or the day after.
