### ISSUE TITLE
macOS/5.1: 'o' keyboard shortcut no longer works to mark older articles as read

### ISSUE THREAD

**Issue by ned21** [Ranchero-Software/NetNewsWire#2451]
In previous versions, and still documented in Help->Keyboard Shortcuts, the unmodified 'o' key could be used to `Mark older articles as read`. In Version 5.1 (3007) on 10.15.6 this no longer works. ⇧⌘K works as expected and can be used as a workaround.

**Comment by vincode-io** [comment]
For this one do we want to restore the old "Mark Older as Read" functionality or do we want new single keyboard shortcuts for "Mark Above as Read" and "Mark Below as Read"?

**Comment by brentsimmons** [comment]
The o key should continue to mark older as read — we don’t want to break people’s expectations there. We need new shortcuts for above and below.
