### ISSUE TITLE
Feature Request (iOS): setting to adjust the font sizes

### ISSUE THREAD

**Issue by auge8472** [Ranchero-Software/NetNewsWire#2454]
At least in the single item view of the iOS app the font sizes are *for me* to large in case of item titles (especially with longer title text) and (a bit) to small for the content text. Thatswhy I want to propose setting points to adjust the font sizes.

**Comment by vincode-io** [comment]
Duplicate of #38.

**Comment by auge8472** [comment]
Arrgh. Checked the whole 15-pages-list of issues and overlooked this one (#38). Sorry.
