### ISSUE TITLE
Articles not appearing on 10.15.7

### ISSUE THREAD

**Issue by MrNoodle** [Ranchero-Software/NetNewsWire#2461]
I may be wrong but it seemed like this started happening after updating to 10.15.7. NNW will show a badge with unread articles, but when I click on the aggregate feeds, the badge disappears and no articles appear. Clicking on individual feeds will show old articles but nothing new.

**Comment by vincode-io** [comment]
What kind of account are you using?  Can you recreate this consistently?

**Comment by MrNoodle** [comment]
No account. Just reading feeds on my local machine.

**Comment by vincode-io** [comment]
Are you using keyboard shortcuts to navigate any?

**Comment by MrNoodle** [comment]
Same result as clicking. Unread badge disappears but no articles.

Also, a slight correction. When clicking on "Today", the badge remains (still no articles). The other ones will clear the badge.

**Comment by vincode-io** [comment]
Would it be possible for you to get a screen recording of this happening so that I can recreate the scenario on my computer?  I have to be able to recreate it to debug the problem.  (You need to compress the video into a zip file to attach it to this ticket.)

**Comment by MrNoodle** [comment]
I have a screen recording along with logs. Do you have a way I could send this info to you in private?

**Comment by vincode-io** [comment]
Sure, just email it to mo@vincode.io.  I really appreciate the extra effort.

**Comment by MrNoodle** [comment]
Sent. Thanks.

**Comment by vincode-io** [comment]
Ok, so as you mentioned in your email, we might have a database corruption problem.  This is a new one for me.

Let's try this:

1. Export your OPML file from the On My Mac account from the File menu.
2. Deactivate your On My Mac account in the Preferences.
3. Create a new On My Mac account and name it what ever you want.
4. Import your previously exported OPML file into the new account.

This will create a new database for you and we should be able to get closer to the root of the problem.  It could be a disk corruption issue, something in a feed that is corrupting your database, or some scenario where NNW is corrupting it.

**Comment by MrNoodle** [comment]
That seemed to work. Let me know what information you need now.

**Comment by vincode-io** [comment]
I don't think we need anything more right now.  I think this was a one-time disk corruption issue that may or may not have had something to do with the upgrade to 10.15.7.

If it happens again, just comment on this ticket and @brentsimmons or I will see it and reopen the issue.
