### ISSUE TITLE
Feature request - remember Reader view preference on a per feed basis

### ISSUE THREAD

**Issue by timothyarmes** [Ranchero-Software/NetNewsWire#2466]
I would like to specify that certain feeds default to using reader view.

**Comment by brentsimmons** [comment]
Mac or iOS?

**Comment by timothyarmes** [comment]
Sorry, Mac OS

Tim

**Comment by brentsimmons** [comment]
Select a feed in the sidebar, choose Window > Info, check “Always use Reader view”

**Comment by timothyarmes** [comment]
Thanks Brent.

However, there's no way I'd have found that.  Perhaps it could just be added as a toggle menu item to the context menu?
