### ISSUE TITLE
Version 5.1 (3007) for Mac does not flag new items in the Dock

### ISSUE THREAD

**Issue by SpelunkerToday** [Ranchero-Software/NetNewsWire#2473]
OS X 10.15.7 (19H2)

Since upgrading to 5.1 the notifications in the Dock on the NNW icon no longer shows unread items

**Comment by lorenzolewis** [comment]
I have the same version of macOS running (including build number) and am seeing the badge icons for unread items in the dock.
Can you confirm that you have notifications enabled for NNW via System Preferences > Notifications > NetNewsWire and make sure that AT LEAST you have "Allow Notifications from NetNewsWire" enabled and the "Badge app icon" box checked?
When starting the app for the first time, you are asked if you would like to allow notifications, so you possibly missed that notification.

**Comment by SpelunkerToday** [comment]
Interesting. Thank you. It was set to OFF, but it was presumably set to ON prior to my upgrading. I suspect the status did not carry forward, that I was interrogated after upgrade and, as you say, missed  it.

**Comment by vincode-io** [comment]
It looks like we got this one figured out.  Closing the issue.
