### ISSUE TITLE
Crash when opening Google Doc

### ISSUE THREAD

**Issue by mikequinlan** [Ranchero-Software/NetNewsWire#2475]
This page

https://daringfireball.net/linked/2020/10/02/covid-19-aerosol

Has a link to

https://docs.google.com/document/d/1fB5pysccOHvxphpTmCG_TGdytavMmc1cUumn8m0pwzo/preview?pru=AAABdQ5s5mA*YrLy9epGlHWhKPSl5JMT3w#

Clicking the the Google Doc link in the preview window crashes NetNewsWire.

Version 5.1 (3007)

**Comment by brentsimmons** [comment]
Thanks! We have a fix in a test build: https://nnw.ranchero.com/2020/10/02/netnewswire-a-for.html
