### ISSUE TITLE
Wishlist: Purge cached content on iOS

### ISSUE THREAD

**Issue by TravellerSam** [Ranchero-Software/NetNewsWire#2484]
I don't know if the cached content is automatically purged after a while, but maybe it would be a good idea to clean up the cache after a defined period (week, month?), at some storage limit or to manually delete the cache in settings. 

NNW 5.0.4 on iOS 14.0.1, iPhone SE 1st gen 32GB

**Comment by vincode-io** [comment]
We do purge content.  See this article for the details of how it is done:

https://github.com/Ranchero-Software/NetNewsWire/blob/main/Technotes/RetentionPolicy.markdown
