### ISSUE TITLE
No badges on load (Mac)

### ISSUE THREAD

**Issue by kuiro5** [Ranchero-Software/NetNewsWire#2487]
Hi! Thanks for the awesome piece of software. Running into a small issue that I was hoping to get help with.

When I first load the Mac client, there are no unread badges. If I click on a particular folder or feed, the badge icon for that folder/feed shows (with the appropriate articles). The unread badges used to show on load and didn't require clicking into the folder/feed.

Version 5.1.1 (3012)

![Screen Shot 2020-10-08 at 9 35 36 AM](https://user-images.githubusercontent.com/4662473/95487855-b2aee100-0949-11eb-8184-68a43535dbb5.png)
![Screen Shot 2020-10-08 at 9 35 57 AM](https://user-images.githubusercontent.com/4662473/95487863-b3e00e00-0949-11eb-9d4f-d93f5c5d4f43.png)

**Comment by brentsimmons** [comment]
Using Feedly, Feedbin, or On My Mac?

**Comment by kuiro5** [comment]
Feedbin

**Comment by brentsimmons** [comment]
I’ve seen this before when I’ve accidentally had two copies of NetNewsWire running at the same time. Could that be true in your case? (Probably not, I’m sure, but I figured I should check.)

**Comment by kuiro5** [comment]
Just double checked, but there only seems be one instance of NetNewWire running.

**Comment by vincode-io** [comment]
@kuiro5 Could you run an experiment for me?  Click on `View > Hide Read Articles` and let me know if that corrects the badge issue.

**Comment by kuiro5** [comment]
Just gave it a try, but doesn't seem to fix it. The badges that are shown when clicking `Hide Read Articles` are seemingly random:
<img width="235" alt="Screen Shot 2020-10-09 at 11 04 13 PM" src="https://user-images.githubusercontent.com/4662473/95647399-fd347880-0a83-11eb-8f5b-c44fe3b2f3a2.png">
<img width="246" alt="Screen Shot 2020-10-09 at 11 04 23 PM" src="https://user-images.githubusercontent.com/4662473/95647401-fefe3c00-0a83-11eb-9766-ae6908eef91c.png">

**Comment by kuiro5** [comment]
It seemed to resolve itself by uninstalling NetNewsWire, removing all application data (`~/Library/Application Support/NetNewsWire`), and reinstalling.

**Comment by vincode-io** [comment]
So weird.  I wish we had gotten to the bottom of what the problem was, but I'm glad you found a work around.
