### ISSUE TITLE
Selected article in article pane goes blank on selection

### ISSUE THREAD

**Issue by jwhevans** [Ranchero-Software/NetNewsWire#2488]
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/45521229/95497360-d3862f00-0967-11eb-88af-bb6025452088.png">

When an article is selected in the article list pane the article loads correctly in the reader but the list pane goes blank for that article. When another article is selected the text returns but the newly selected article goes blank.

NetNewsWire for Mac Version 5.1.1 (3012)

**Comment by brentsimmons** [comment]
Are you using Big Sur? This was a bug in one of the betas.

**Comment by jwhevans** [comment]
Brent, yes I should have mentioned that. I'm currently running Version 11.0 Beta (20A5364e). If you are already aware then I will close the issue.

**Comment by vincode-io** [comment]
The current Beta build is 20A5384c which doesn't have this bug.  Closing since this has been resolved by Apple.
