### ISSUE TITLE
Feature Request: Reader view configuration by feed

### ISSUE THREAD

**Issue by drchrispinnock** [Ranchero-Software/NetNewsWire#2495]
**Use case:** Some sites such as The Register only provide a short summary in the RSS feed. The user has to resort to going to the full article or clicking reader view.

**Possible enhancement:** 
- Add a configuration item per feed to setup NetNewsWire to use the reader view by default.
- If the user clicks reader view >=5 times on a particular feed, offer a hint to switch this feature on for the feed

**Comment by brentsimmons** [comment]
To always use Reader View with a feed: select the feed in the sidebar, choose Window > Info, then check “Always Use Reader View.”
