### ISSUE TITLE
Last article in list is cut off

### ISSUE THREAD

**Issue by MushuMaxMax** [Ranchero-Software/NetNewsWire#2497]
Version 5.1.1 (3012)

The last article in the article list is cut off. See screenshots.

![Screen Shot 2020-10-16 at 10 15 47 PM](https://user-images.githubusercontent.com/73011244/96329034-f4045800-0ffd-11eb-99ed-e787e85666cd.png)
![Screen Shot 2020-10-16 at 10 14 25 PM](https://user-images.githubusercontent.com/73011244/96329040-fe265680-0ffd-11eb-8736-f5bb0befce2d.png)

**Comment by brentsimmons** [comment]
Super weird. I think this is a new one.

Does this happen all the time?

**Comment by MushuMaxMax** [comment]
I played around a little to see when it triggered. 

I discovered that it happens when the scroll bar is there. When the list fits in in window, the items look fine. Resize the window smaller to trigger a scroll bar and the rendering bug appears. 

I was also able to trigger it at just the right resize that there was no scroll bar, but the last item was partially  below the bottom edge, and was cut off as well. 

And to answer your question, yes, it seems to happen all the time. 

-Neil

**Comment by vincode-io** [comment]
@MushuMaxMax Are you using the Big Sur beta?

**Comment by MushuMaxMax** [comment]
Should have included that info on the initial report. Running Catalina 10.15.7 (19H2) on a MacBook Pro (15-inch, 2017).

**Comment by vincode-io** [comment]
Like @brentsimmons said, "Super weird".  I have Catalina 10.15.7 install and have tried everything to recreate this, to no avail.  I'm stumped for now.

You could start trying the desperation measures of reinstalling from scratch and rebooting to see if that helps.

**Comment by MushuMaxMax** [comment]
A reboot of my MacBook did resolve the rendering bug, not that it really bothered me, but I’ll let you know if I see it happen again.

**Comment by vincode-io** [comment]
If you see it again, let us know and I'll reopen this issue.
