### ISSUE TITLE
Feature request: Add in-app browser

### ISSUE THREAD

**Issue by kevinm6** [Ranchero-Software/NetNewsWire#2505]
It’d be cool and useful to have in-app browser to just show the article without leaving the app.

**Comment by jaanus** [comment]
Can you be more specific with your request? What platform? Articles already open in in-app browser in NNW on my iPhone without leaving the app.

**Comment by kevinm6** [comment]
Both iOS and macOS.
Yes, the articles are shown in-app like a standard reader, but sometimes the reader doesn’t get all the text of the article or the images, so would it be nice to set another option in settings to change from “Open in 'browser_name’ “ to “Open in-app browser” and it show the original website article without opening Safari or other browsers and leaving temporarily the app.

**Comment by vincode-io** [comment]
On iOS if you click the title, the article will open in the in-app browser.  We've found that on macOS using the external browser is a better experience than using an in-app browser because macOS supports multiple windows better than iOS.  We don't have any plans to support an in-app browser on macOS.

**Comment by kevinm6** [comment]
Yes, on iOS can be nice set a gesture to open in-app browser.
I think that on macOS is useful as much as on iOS, for not leaving the app: Because NNW is for stay informed, learn e stay updated with the news, in the same time maybe I’m using Safari or other browser in the first “Desktop space", and I’m in another space on my Mac doing other stuff and using NNW, in that case it change my focus and space on another thing and app, and it happens a lot in my case.
But is just my opinion and my type of use. 
I used "Reeder 4” for RSSfeed on both iOS & macOS and I really appreciate that, even the pull to refresh on macOS. (I understand that Reeder 4 is built like a Universal App…)
