### ISSUE TITLE
Feature request: < macOS & iOS > Icons for folders

### ISSUE THREAD

**Issue by kevinm6** [Ranchero-Software/NetNewsWire#2515]
It could be possible to add a thumbnail for folders on both macOS (that has the classic folder look) & iOS? Like the "Smart Feeds”? 
And remove the “table lines” for the articles in the feed.

**Comment by vincode-io** [comment]
What would the thumbnail for a folder be a thumbnail of?

**Comment by kevinm6** [comment]
A thumbnail of the content, it could be a simple symbol (like a Macbook glyph for the "Tech Folder” and so on…) that help you to go directly to a folder.
Like the “Smart Feeds Folder”; and is not necessary to add a database of glyph, it could be just a image added by the user.


![IMG_5354](https://user-images.githubusercontent.com/72861758/96682086-9f076f80-1378-11eb-967f-b554c7dd6e4d.png)

**Comment by brentsimmons** [comment]
Duplicate of https://github.com/Ranchero-Software/NetNewsWire/issues/3613
