### ISSUE TITLE
Quotation marks render as â

### ISSUE THREAD

**Issue by doekman** [Ranchero-Software/NetNewsWire#2519]
A starred article from the Daring Fireball feed has weird characters in the title. Screen-shot:

<img width="1377" alt="Schermafbeelding 2020-10-21 om 10 20 52" src="https://user-images.githubusercontent.com/1086388/96693494-99fdec80-1387-11eb-9107-9867847e492a.png">

Title from reader (the question-marks are not shown in reader, or here in markdown, but is probably some UTF-8 problem):

> Christopher McQuarrie: âFocus Entirely on Execution and Not on Resultâ

Title from the website:

> CHRISTOPHER MCQUARRIE: ‘FOCUS ENTIRELY ON EXECUTION AND NOT ON RESULT’

Article: <https://daringfireball.net/linked/2019/10/26/mcquarrie->

I'm on macOS Catalina 10.15.7 (19H2) and NetNewsWire Version 5.1.1 (3012). The feed is stored in On My Mac account.

I haven't seen this behaviour on other articles in Daring Fireball's feed. Quotations in other titles render correct.

**Comment by brentsimmons** [comment]
There are multiple feeds for Daring Fireball. Which one are you using?

**Comment by doekman** [comment]
<https://daringfireball.net/feeds/json>

**Comment by doekman** [comment]
For what's worth: this issue is still present in Version 5.1.2 (3016).

Also, I didn't see it originally, but the article body also contain encoding issues. Copy/paste:

> 
> Daring Fireball
> John Gruber	
> Christopher McQuarrie: âFocus Entirely on Execution and Not on Resultâ
> 26 Oct 2019 at 22:18
> Christopher McQuarrie:
> 
> After twenty five years in the craft, Iâve learned the secret to making movies is making moviesâââstarting with little movies no one will ever see.
> 
> The secret to knowledge is doing and failingâââoften and painfullyâââand letting everyone see.
> 
> The secret to success is doing what you love, whether or not youâre being paid. The secret to a rewarding career in film (and many other fields) is focusing entirely on execution and not on result.
> 
> McQuarrie is writing from the field he knows bestâââmoviesâââbut I really do believe this advice is universal. You want to be a writer? Write. You want to make apps? Create apps.
> 
> Thereâs not much similar between football and filmmaking, but I recently heard Alabama head coach Nick Saban give the same advice to a younger coach: focus on execution, not results. The results you deserve will follow from the quality of your execution.
> 
> Link: twitter.com/chrismcquarrie/status/1187023381251670017

**Comment by vincode-io** [comment]
Since you aren't seeing this in other articles, I'm going to have to assume that this was a problem with the article itself.  I can't know for sure though.  The article you have starred is over a year old and no longer in the Daring Fireball RSS feed.

If you encounter this issue again, please let us know and I will reopen this issue.  We should be able to get to the root of the problem if we have an article to work with.
