### ISSUE TITLE
Bug Report: Renamed Feedly feed names are not synced between macOS and iOS vice versa.

### ISSUE THREAD

**Issue by mhoutman** [Ranchero-Software/NetNewsWire#2520]
Using a Feedly account I have feeds within several folders. When I rename a feed name on macOS it s not synced as such to iOS.
Renemaing on iOS does not sync too

**Comment by vincode-io** [comment]
Are you doing a sync on the secondary device after doing the rename?  If I rename an item on the Mac and the go to my iPhone and pull to refresh the folder is getting renamed correctly.

**Comment by mhoutman** [comment]
> Are you doing a sync on the secondary device after doing the rename? If I rename an item on the Mac and the go to my iPhone and pull to refresh the folder is getting renamed correctly.

Sorry, my mistake as it was written not correctly. You should read Feed name and NOT Folder name

**Comment by vincode-io** [comment]
I can confirm that we aren't pulling down Feed name changes.  They are getting sent correctly to Feedly, we just aren't responding to them when they happen.

@brentsimmons We probably want to fix this bug for Mac 5.1.2 and iOS 5.0.5.

@kielgillard Is this something you have time to take a look at or do you want me to dig into it?

**Comment by kielgillard** [comment]
@vincode-io I'll take a look at this. I'll follow up with you on slack DMs.

**Comment by vincode-io** [comment]
This has been resolved and will be in the next release.
