### ISSUE TITLE
Not fetching feed

### ISSUE THREAD

**Issue by boldlion** [Ranchero-Software/NetNewsWire#2521]
I have the latest version of NetNewsWire installed (Version 5.1.1) on macOS Catalina. It simply does not download the feed when being refreshed. 

I thought the feed URLs might have changed, but I manually checked them and they work, it's just that the app is not fetching the results. 

Not a single feed is fetched and I have probably 200 Craigslist feed URLs in my list.

**Comment by brentsimmons** [comment]
Using Feedly, Feedbin, or On My Mac? Did it ever fetch the feeds? Would you provide the URL of one of those feeds?

**Comment by BZBR** [comment]
Im running NNW 5.0.4 on an  14.0.1 IPhone and feeds were working great until about a week ago. I created a new RSS file from the source, searchtempest, and imported it - still nothing. Am still receiving NNW feed. Thanks

**Comment by brentsimmons** [comment]
Using Feedly, Feedbin, or On My iPhone? What’s the URL of the feed?

**Comment by BZBR** [comment]
Using only Net News Wire. This is the url from which to download .opml file.
https://www.searchtempest.com/getrss?search_string=Desk&category=8&subcat=sss&cityselect=zip&location=85603&maxDist=1000&Region=combined

**Comment by brentsimmons** [comment]
@BZBR These feeds are gone, unfortunately. They’re returning a 410 Gone response instead of a feed.

**Comment by BZBR** [comment]
Brent thanks for checking this out so quickly. Guess this means SOL on the searchtempest. Are people having any luck with direct CL feeds? It seems the OP those may be not functional at this point either. thanks again

**Comment by boldlion** [comment]
Interesting. When I tested the feed it was working, now it's removed. Its craigslist's feed. 

So, the issue is not NetNewsWire, it's the feed itself
