### ISSUE TITLE
Star icon has gray background

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#2523]

**Comment by brentsimmons** [comment]
Still happening with 5.0.5 build 55, released Oct 29.

**Comment by stuartbreckenridge** [comment]
iPad running 14.2:
- no issue

iPhone running 14.1:
- Background shows when app is launched in Light Mode.
- Background doesn’t show when app is launched in Dark Mode and is then switched to Light Mode.

Weird.
