### ISSUE TITLE
Fix sandboxing issues

### ISSUE THREAD

**Issue by vincode-io** [Ranchero-Software/NetNewsWire#2524]
- [x] What to do about select default RSS reader setting
- [x] Determine if sandboxing has broken crash reporting

**Comment by vincode-io** [comment]
@brentsimmons I did verify that the crash reporter is broken when NNW is sandboxed.  Should we look at what we can do with plcrashreporter?

**Comment by brentsimmons** [comment]
Yes — let’s integrate PLCrashReporter. It’s time.
