### ISSUE TITLE
Feature Request: Show author in feed view

### ISSUE THREAD

**Issue by jsit** [Ranchero-Software/NetNewsWire#2563]
Sometimes feeds have a lot of different authors, and it would be nice to be able to see the name of the author for each article in the feed view, not just the author view.

**Comment by vincode-io** [comment]
We do display the author in the timeline when it is available. Lots of feeds don't supply the author on a article basis, and then we can't display the author in the timeline. 


Do you have a feed that you think should be showing the author in the timeline, but isn't?

**Comment by jsit** [comment]
I'm talking about iOS; maybe it shows on macOS? I forget.

https://www.theatlantic.com/feed/channel/ideas/

![image](https://user-images.githubusercontent.com/643417/98471676-09634100-21bc-11eb-89f8-a032eca27fd6.png)

**Comment by vincode-io** [comment]
This feature hasn't made it to iOS yet.  It is coming in version 6.0.  Closing this out since it has already been implemented, just not released on iOS yet.

**Comment by jsit** [comment]
Would it be possible to show the author in the _folder_ view, as well? Not sure I'm using the correct terminology, but I mean when you're looking at feeds in a folder. It shows the feed title, but not the author.

<img width="439" alt="Screen Shot 2020-11-09 at 9 24 51 AM" src="https://user-images.githubusercontent.com/643417/98553245-6e2aa400-226d-11eb-98e5-4ba047bf3275.png">

**Comment by vincode-io** [comment]
For mixed feeds, like the Folder view, we show the feed name instead of the author name.  If we had room for both, we probably would show both.

**Comment by jsit** [comment]
Often there is enough room; I wonder if it would be worth just appending the author, and if it truncates, it truncates.
