### ISSUE TITLE
Options to open url and external_url for JSON Feed items

### ISSUE THREAD

**Issue by nickheer** [Ranchero-Software/NetNewsWire#2569]
I am not much of a programmer so this is more of an idea request than something I can commit to working on.

The idea: since JSON Feed items support both `url` and `external_url` properties, I think it would be neat if NetNewsWire could support opening either one on demand. 

As an unfortunately self-promotional example, the latest item in my JSON Feed (https://pxlnv.com/feed/json) has the following properties:

    "url": "https://pxlnv.com/linklog/first-m1-benchmarks/",
    
    "external_url": "https://www.macrumors.com/2020/11/11/m1-macbook-air-first-benchmark/",

Right now, NetNewsWire defaults to opening the `url` in all cases on MacOS and iOS using the "Open in Browser" buttons. I wish there were an option — perhaps in a contextual menu or a standalone button — to open the `external_url` instead, if present. Perhaps this could be extended to a per-feed preference; in a linkblog-style feed, you may always wish to open `external_url`s or not.

This may be related to #2261 or #339. It is also possible that I am using JSON Feed all wrong on my own website. I apologize for not being able to directly contribute to this, but I thought I'd throw it on the radar as something I would like to see added to NNW if time and effort permits.

**Comment by vincode-io** [comment]
@brentsimmons  I was thinking about this and how Daring Fireball has to manually put the link at the bottom of the article.  What if we included the external link as part of the header when it exists and doesn't match the permalink?

<img width="589" alt="Screen Shot 2020-11-12 at 2 28 34 PM" src="https://user-images.githubusercontent.com/16448027/98993069-99bec000-24f3-11eb-84df-5585564b6aac.png">

I think something like this would help link blogs.

**Comment by stuartbreckenridge** [comment]
I think we should steer away from adding a link to the top of the article. It will look weird if the article _originally_ started with an image and then we insert the `external_url` above it. 

I'd go for something more subtle, e.g. putting the `external_url` after the date with a separator and shortening the URL down to just the domain:

No `external_url`:

> Hands-On With the iPhone 12 Mini and Pro Max
> Nov 5, 2020 at 6:33 PM

With `external_url`:


> Hands-On With the iPhone 12 Mini and Pro Max
> Nov 5, 2020 at 6:33 PM | [engadget.com](engadget.com)

**Comment by vincode-io** [comment]
Shortening it all the way down to the domain makes it look like a link to a domain, not an article or blog post.

**Comment by vincode-io** [comment]
I was trying to find a link blog that starts with an image, but wasn't successful.  I'm not sure that it will look weird.  If you have an example of a JSON, link blog that I can check, I'll get us a screen shot so that we can see it.

**Comment by stuartbreckenridge** [comment]
Now that you mention it, I can’t find one either!

Sent from my iPhone

On November 13, 2020, GitHub Notifications <notifications@github.com>
wrote:
> I was trying to find a link blog that starts with an image, but wasn't

> successful. I'm not sure that it will look weird. If you have an
> example of a JSON, link blog that I can check, I'll get us a screen
> shot so that we can see it.
>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Ranchero-
Software/NetNewsWire/issues/2569#issuecomment-726438763>, or unsubscribe

<https://github.com/notifications/unsubscribe-
auth/ABVYL7GYQP6YXJINJWIGH43SPSAWFANCNFSM4TTVGR3Q>.

**Comment by brentsimmons** [comment]
I like it. Let’s do it. 👍

**Comment by nickheer** [comment]
Thank you everyone!
