### ISSUE TITLE
Renamed feed’s title not preserved.

### ISSUE THREAD

**Issue by kevinm6** [Ranchero-Software/NetNewsWire#2572]
Changing the title (name) of a feed added to NNW works, but after if I move that feed to another folder, the name go back to the original one.

**Comment by kielgillard** [comment]
@kevinm6 are you using a syncing service or a local RSS account?

**Comment by kevinm6** [comment]
I've moved to sync on iCloud on all my devices and this is not happening anymore, so for me the issue is closed.

**Comment by kielgillard** [comment]
I think this issue was fixed in NNW 6, too.
