### ISSUE TITLE
Custom keyboard shortcuts

### ISSUE THREAD

**Issue by kadimisetty** [Ranchero-Software/NetNewsWire#2576]
Having keyboard shortcuts is nice, but the default ones are unintuitive for some of us, as people do come in from different feed readers with different shortcuts. As such a customizable option would be very welcoming. 

If not, the next best thing would be menu entries for the movements, like next or previous, so we can customize them up in system accessibility preferences instead.

**Comment by kevinm6** [comment]
On macOS, you can already do it in System Preferences > Keyboard > Shortcuts > Application Shortcuts and add NNW with the name of the menu function you want to change.

**Comment by kadimisetty** [comment]
Thanks!
