### ISSUE TITLE
Future enhancement: add stories feature

### ISSUE THREAD

**Issue by palanp** [Ranchero-Software/NetNewsWire#2578]
![C07E5623-86A6-4949-9C67-63B92D37A5A1](https://user-images.githubusercontent.com/61982388/99599369-d9d4e580-29c0-11eb-8496-8cd4eb08f433.jpeg)

**Comment by vincode-io** [comment]
Could you give us some more details about this?  I'm sure that the circles are feeds of some kind. What would make them selected to be at the top?

**Comment by stuartbreckenridge** [comment]
Favourite feeds flag in addition to starred posts?

**Comment by palanp** [comment]
Sorry guys, I should have made it more obvious. There’s a big meme going around about how Twitter added a “stories” feature, similar to Snapchat, Instagram, Facebook and every other app. But Twitter called theirs “Fleets” and its ridiculous. Now folks are proposing a “stories” feature for every app on the market — even iOS Calculator. Just wanted to make sure NNW didn’t miss out on the fun 🙃

Love watching you folks develop the app. Can’t wait to use the code base to learn how to write code for Mac myself. Keep up the great work!

**Comment by brentsimmons** [comment]
What’s Twitter?

**Comment by palanp** [comment]
@brentsimmons touché!! Does micro do stories?
