### ISSUE TITLE
Accounts: guitar emoji is clipped at bottom

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#2586]
<img width="244" alt="Screen Shot 2020-11-18 at 6 43 35 PM" src="https://user-images.githubusercontent.com/1297121/99614261-fdeaf380-29cd-11eb-88f9-66ad1d9171b3.png">

**Comment by vincode-io** [comment]
I'm blaming this one on Big Sur.  This doesn't happen on Catalina at least.  Currently, I have no idea how to work around this except by maybe making a custom NSTextField subclass.

**Comment by stuartbreckenridge** [comment]
@vincode-io Go to the Title in the `xib`, select the last character (after the guitar), then `Option + Return` to add an extra line.

**Comment by vincode-io** [comment]
@stuartbreckenridge Thanks for the tip!
