### ISSUE TITLE
Useful improvements of UI.

### ISSUE THREAD

**Issue by kevinm6** [Ranchero-Software/NetNewsWire#2595]
It would be very nice, I think, have the top bar (and even the bottom one maybe) in the Article view get smaller during the scrolling of the article.
Just like in Safari on iOS & iPadOS.
![image](https://user-images.githubusercontent.com/72861758/99703602-9600df80-2a97-11eb-806f-bb9556d6d50a.jpeg)

**Comment by vincode-io** [comment]
We've experimented with different sizes and hiding the toolbar and nav bar on the articles view.  We didn't like it because it was too distracting.  If you want to see more of the article on the iPhone you can enable Fullscreen in the system settings.

**Comment by kevinm6** [comment]
I had it enabled. 
But the problem is that is not responsive: if I want the full screen and then I need to turn on the Reader view for that article, it takes several steps (and I do that several times during my sessions on NNW) :
 - Enable Full Screen if is not already enabled
 - Scrolling
 - tap bottom/top to disable full screen
 - enable "Reader View”
 - tap the top to enable again full screen


I think the Safari behavior for the bottom and top bar is one of the best feature of it. And in some way Safari & NNW have the same purpose (read the content and focus on it).
Even because with a small top bar, the feed name is still available (like in Safari), and is the only thing interesting in the top bar in the Article View.

Just one more thing: this two buttons are a little bit misleading, just because unlike other Feed Reader apps, moving from an article to the next/prev in NNW you have to do a right/left sliding gesture and this buttons are up/down instead of right/left.

![IMG_5432](https://user-images.githubusercontent.com/72861758/99711854-93f04e00-2aa2-11eb-9fec-ddd6c8897f5f.jpeg)

By the way, you're all doing a great job with this app (I quit Reeder 4 from both iOS & macOS), and I can’t wait for the new update with iCloud Sync feature.

**Comment by vincode-io** [comment]
You don't have to go through all those steps to get the toolbar functionality.  Just long press on the article while in full screen and you will get a context menu that allows you to enable reader view among other things.

The previous and next buttons match the Timeline flow which is especially important on the iPad where the Timeline is showing.  We also allow paging through articles by going left to right, but that isn't the primary means of navigation for NetNewsWire.  Article movement happens up and down along the Timeline.

UI/UX is a series of tradeoffs.  We've agonized over the hiding of the bars and the navigation buttons. In the end, we have come up with what we feel is the best solution for most users.

Thanks for the kind words!  We hope to begin testing on NNW 6.0 in the near future.

**Comment by kevinm6** [comment]
I have an iPhone 7, so there are some little bugs with long press and 3D Touch in NNW, is so slow most of the times.
I understand all the problems/doubts, I know a little bit of Swift, I tried and then I quit develop some app, even a brightness slider for the menu bar of macOS (before Big Sur), rejected 4 times by Apple.
Thanks for the reply.

I would be happy to help maybe for the Italian localizations for the next update (milestone) of new year!
Have a great day.
