### ISSUE TITLE
Feedly login message should say "Safari will open" if your default browser doesn't support web authentication

### ISSUE THREAD

**Issue by stephenwade** [Ranchero-Software/NetNewsWire#2596]
<img width="624" alt="Screenshot of NetNewsWire Accounts window, showing the text 'Your default web browser will open the Feedly login page'" src="https://user-images.githubusercontent.com/4148577/99751264-db310b80-2aaf-11eb-9ed0-e28b1b748c03.png">

When I log in to Feedly from NetNewsWire, NNW says it will open my "default web browser". However, it opens Safari instead of Chrome.

Either NetNewsWire should use my default web browser, or the text should be updated to say "Safari will open the Feedly login page".

**Comment by stephenwade** [comment]
If it matters, my default browser is technically [Choosy](https://www.choosyosx.com/), but since I had Chrome open, Choosy would have passed the link to Chrome.

**Comment by kielgillard** [comment]
macOS [will open Safari if the default web browser does not support web authentication](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession). Do you know if Choosy supports it?

**Comment by kielgillard** [comment]
But you're right, it should probably say "Your default browser or Safari will open..."

**Comment by stephenwade** [comment]
Choosy probably doesn't support web authentication, because there's no guarantee that the browsers I have configured in Choosy would support web authentication.

**Comment by stephenwade** [comment]
I think "Your default browser or Safari" is awkward. Could the app detect that ahead of time and display whichever message is accurate?

**Comment by kielgillard** [comment]
That's fair. What should NNW say in the case Choosy is the default browser?

**Comment by stephenwade** [comment]
"Safari will open the Feedly login page for you to authorize access."

**Comment by kielgillard** [comment]
In case it's not clear, NNW won't know ahead of time if the default browser supports web authentication. What should the message read?

**Comment by kielgillard** [comment]
> NNW won't know ahead of time if the default browser supports web authentication.

To the best of my knowledge, no API exists, so NNW can't tell. Maybe I'm wrong?

**Comment by stephenwade** [comment]
If there's no way to tell, I think the text could be changed to something more generic, such as "The Feedly login page will open for you to authorize access."

**Comment by kielgillard** [comment]
I like the simplicity of this message. Sometimes the login page takes a bit of time to appear and the user could click around somewhere else, in which case the login page could easily get lost in the background. Do you think saying "Feedly login page" without reference to one or two of the apps the page might be in is enough for someone to find it again?

**Comment by stephenwade** [comment]
I think so, yes. If I see that message I'm going to look around for a window with a Feedly login screen.

**Comment by brentsimmons** [comment]
New text:

A web browser will open the Feedly login for you to authorize access.
