### ISSUE TITLE
macOS: Article Layout Issues (NNW 6)

### ISSUE THREAD

**Issue by stuartbreckenridge** [Ranchero-Software/NetNewsWire#2597]
The layout of articles has issues when going to full screen and toggling the sidebar.

To recreate:

1. Launch the app
2. Select an article
3. Go to full screen mode and the top of the article is placed under the toolbar.

<img width="1339" alt="Screenshot 2020-11-20 at 12 01 26 PM" src="https://user-images.githubusercontent.com/7046652/99756835-f5f39680-2b28-11eb-8d5e-15d60591a355.png">

4. Toggle the sidebar to hide it
5. Toggle the sidebar to show it
6. Go out of full screen mode and the article is placed about 2/3 of the way down the window.

<img width="584" alt="Screenshot 2020-11-20 at 12 02 25 PM" src="https://user-images.githubusercontent.com/7046652/99756883-1de2fa00-2b29-11eb-9ec6-3ca4d7328e6a.png">

**Comment by vincode-io** [comment]
I took a look at this one and have no idea what to do about it.  If you just move the window a bit while it is in that odd state, it redraws itself correctly.  It's like the web view has a bad frame when it tries to draw and then it gets corrected.
