### ISSUE TITLE
NNW6 — iOS — Widget doesn’t always show feed icon for new feeds

### ISSUE THREAD

**Issue by stuartbreckenridge** [Ranchero-Software/NetNewsWire#2612]
![image](https://user-images.githubusercontent.com/7046652/100083443-747f6980-2e84-11eb-944e-df7716d121ab.jpeg)

![image](https://user-images.githubusercontent.com/7046652/100083457-7a754a80-2e84-11eb-8b9a-06f8d3aad1a0.jpeg)

**Comment by brentsimmons** [comment]
Is this still a bug?

**Comment by stuartbreckenridge** [comment]
No. It was fixed when started saving the images to disk rather than writing base64 to the JSON file.
