### ISSUE TITLE
Suggestion: Use Big Sur-styled icon on macOS

### ISSUE THREAD

**Issue by blackketter** [Ranchero-Software/NetNewsWire#2613]
Big Sur introduced application icons that are styled more like iOS icons.  I suggest that NNW on macOS use the new icon style, possibly the same icon as the iOS version of the app.

**Comment by matthewtodd** [comment]
Looks like it's coming in version 6.0! See 461f0f35.

**Comment by blackketter** [comment]
Fantastic! Looks great.
