### ISSUE TITLE
Feed Parsing Error In Reader Mode

### ISSUE THREAD

**Issue by jalexandratos** [Ranchero-Software/NetNewsWire#2614]
Seeing the following error on Boing Boing feed (boingboing.net/feed):

When viewing an article, the article summary looks fine. In reader mode, the story doesn’t appear to parse correctly and shows a snippet of a different article. In addtion, article header/hero images properly display in article view, but not reader mode.

This behavior is odd b/c it doesn’t happen on every article.

Screenshots attached which show this behavior.

<img width="1080" alt="bb-normal-view" src="https://user-images.githubusercontent.com/801650/100124337-8394f600-2e49-11eb-837e-a19c32ff09b5.png">

<img width="1080" alt="bb-reader-mode" src="https://user-images.githubusercontent.com/801650/100124358-8c85c780-2e49-11eb-98f5-739ef6b9014f.png">

<img width="1080" alt="bb-header-image-normal" src="https://user-images.githubusercontent.com/801650/100124375-93143f00-2e49-11eb-9b58-9b6a2832f267.png">

<img width="1080" alt="bb-header-image-reader" src="https://user-images.githubusercontent.com/801650/100124393-97d8f300-2e49-11eb-85d5-c6353e6d0c62.png">

**Comment by vincode-io** [comment]
I'm afraid there isn't much we can do about this.  The content extraction work is done by a webservice we use called Mercury that does the article extraction.

How these content extractors work is that they use heuristics to try to find the area in the page with the most text.  In you first example the "article" is basically one sentence and a Youtube video.  When the content extractor looks at that "article" it actually finds more text farther down the page.  The content extractor doesn't have the intelligence to know that it isn't relevant.

Some content extractors have special code for specific sites.  Maybe this is how other content extractors are doing a better job of extracting Boing Boing posts.  I can't know for sure.

Sorry, I wish there was more we could do here.

**Comment by jalexandratos** [comment]
Thanks for checking this out! Also, thanks for the pointer to Mercury. I’ll see if I can submit a ticket to the Mercury team.
