### ISSUE TITLE
Feature request: allow to hide the feed icon or select the size on macos interface

### ISSUE THREAD

**Issue by sbarex** [Ranchero-Software/NetNewsWire#2622]
When a folder of feeds is selected in the message list the feed icon is shown for each one. It would be nice to be able to choose to hide the icons and / or to be able to choose between a normal size and a smaller one that disturbs the reading less.

**Comment by vincode-io** [comment]
This is similar enough to Issue #1551 that I'm going to close it as a duplicate.  The suggested solution to #1551 is that you can pick and choose between having the feed icon or an image or neither.
