### ISSUE TITLE
Confirmation for deleting Extension (as we do for Accounts)

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#2632]

**Comment by vincode-io** [comment]
The big difference between deleting an Extension and an Account is that deleting an Account is a destructive act and data will be lost.  Deleting an Extension has no penalty beyond having to add it again.  That's why I didn't put a confirmation on this one.

**Comment by brentsimmons** [comment]
Could we do Undo support for this?

**Comment by vincode-io** [comment]
I think the dialog would be more appropriate than undo.  I'm not dragging my feet on doing the work, I just wanted to make sure that you had looked at it from all the angles.  My only point was that the only downside to hitting delete on accident was you had to sign in again, probably using keychain.  I don't think that is destructive, but if you do, let's add the dialog.

**Comment by brentsimmons** [comment]
Technically it’s not destructive. But I’m considering how people will feel about it — and adding back an account feels like just enough work that people will *feel* like it’s destructive, even when it isn’t.
