### ISSUE TITLE
Article view is jumpy vertically when window is resized

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#2634]
Note how the header and title change x positions as the window is resized. They should not.

https://ranchero.com/downloads/JumpyArticleView.mov

**Comment by vincode-io** [comment]
@Wevah Is this one you could help out on?  I'm just not very good with web stuff anymore and frankly, probably never was.

**Comment by vincode-io** [comment]
This looks like another Big Sur bug.  I can recreate it using the sample project that I put together to test the toolbar separator.  The sample project uses a plain WKWebView that directly loads inessential.com.  It isn't doing any of the fancy stuff we do in NetNewsWire.

[Screen Recording 2020-12-09 at 7.50.53 PM.mov.zip](https://github.com/Ranchero-Software/NetNewsWire/files/5669774/Screen.Recording.2020-12-09.at.7.50.53.PM.mov.zip)

**Comment by vincode-io** [comment]
FB filed: FB8935679

**Comment by stuartbreckenridge** [comment]
Is it possible that this issue and #2597 are related to this [article](https://developer.apple.com/documentation/appkit/nswindow/stylemask/1644646-fullsizecontentview)? NNW 6 uses the fullSizeContentView mask, but it doesn't use the `contentLayoutRect` or `contentLayoutGuide` for laying things out underneath the toolbar.

> # fullSizeContentView
> When set, the window’s contentView consumes the full size of the window. Although you can combine this constant with other window style masks, it is respected only for windows with a title bar. Note that using this mask opts in to layer-backing. **Use the contentLayoutRect or the contentLayoutGuide to lay out views underneath the title bar–toolbar area.**

**Comment by stuartbreckenridge** [comment]
Disabling fullSizeContentView solves both issues.

**Comment by vincode-io** [comment]
Can you disable `fullSizeContentView` without completely messing up the unified toolbar?

**Comment by stuartbreckenridge** [comment]
If you disable `fullSizeContentView` and set the Toolbar Style to `Expanded` in Interface Builder then things are OK. 
[Screen Recording 2020-12-17 at 06.47.50.zip](https://github.com/Ranchero-Software/NetNewsWire/files/5705881/Screen.Recording.2020-12-17.at.06.47.50.zip)

**Comment by stuartbreckenridge** [comment]
The difference in behaviour / performance is nutty.

**Comment by vincode-io** [comment]
I think we still want to go with the Unified toolbar to match the rest of Big Sur.  Hopefully Apple gets this resolved in a point release.

**Comment by stuartbreckenridge** [comment]
Is it a layout issue on our part though?

**Comment by vincode-io** [comment]
I'm not following you.  You can look in the view debugger to see that we are laying out our views underneath the toolbars.  What do you think we could do differently?

**Comment by stuartbreckenridge** [comment]
In these screenshots: 
1 - the `Window` height is 867
2 - the `layoutGuide` has a height of 815 (it's `top` is offset by 52 for the Toolbar)
3 - the `DetailContainerView` has a height of 867

My understanding is that when `fullSizeContentView` is on, the top constraint of the views under the toolbar should be pinned to the topAnchor of the `layoutGuide`, and therefore the height of the `DetailContainerView` should actually be 815 (the same as the `NSClipView` of the Sidebar). 

<img width="1792" alt="1 - NSWindow" src="https://user-images.githubusercontent.com/7046652/102439271-ea788a00-4058-11eb-8594-313c8a24965a.png">
<img width="1792" alt="2 - LayoutGuide" src="https://user-images.githubusercontent.com/7046652/102439288-f19f9800-4058-11eb-8ef5-a2d42af536e7.png">
<img width="1792" alt="3 - DetailContainerView" src="https://user-images.githubusercontent.com/7046652/102439291-f2d0c500-4058-11eb-92de-f817fe9ea202.png">

**Comment by vincode-io** [comment]
Here is sample project with the same issue that might be easier to experiment on.

[UnifiedWindow.zip](https://github.com/Ranchero-Software/NetNewsWire/files/5706878/UnifiedWindow.zip)

**Comment by stuartbreckenridge** [comment]
@brentsimmons I think this can be closed. On macOS 12 there are no issues and we've done what we can to sort it on macOS 11.
