### ISSUE TITLE
Article text size preference should use Apple terminology

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#2638]
Maybe it does already — but I’m guessing that X-Large and XX-Large aren’t used by Apple. (Extra Large, maybe? Needs research.)

**Comment by vincode-io** [comment]
I would have sworn that these were used on iOS to adjust Dynamic Type, but I would have been wrong.  I can't find anywhere that Apple addresses this.  They use an unlabeled slider on iOS for Dynamic Type.  Maybe we should look at doing that?
