### ISSUE TITLE
Warning about MainWindow storyboard

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#2645]
![Screen Shot 2020-12-05 at 6 25 40 PM](https://user-images.githubusercontent.com/1297121/101269799-538e0280-3727-11eb-90cc-0db73aef32e6.png)

```/Users/brent/Projects/NetNewsWire/Mac/Base.lproj/MainWindow.storyboard:pZU-jW-B1h: warning: Unsupported configuration of constraint attributes. This may produce unexpected results at runtime before Xcode 5.1 [9]```

**Comment by vincode-io** [comment]
This is gone now.  I think my forking the storyboards cleared it up the other day.
