### ISSUE TITLE
Error on adding Twitter extension

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#2647]
I choose to add a Twitter extension, and then I get this dialog:

<img width="293" alt="Screen Shot 2020-12-05 at 6 40 39 PM" src="https://user-images.githubusercontent.com/1297121/101270023-a49ef600-3729-11eb-8a4a-c87b92534895.png">

My ProjectSettings.xcconfig file has entries for TWITTER_CONSUMER_KEY and TWITTER_CONSUMER_SECRET.

**Comment by vincode-io** [comment]
We've got this working now!

**Comment by zgosalvez** [comment]
Got this same error on Version 6.0a1 (6006)

**Comment by LitoFrame** [comment]
For me Twitter Timeline stopped working on 6.0a1.

**Comment by zgosalvez** [comment]
Confirming that this has been fixed on Version 6.0a2 (6007).
