### ISSUE TITLE
Sidebar/timeline splitter has extraneous lines (Big Sur)

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#2648]
Here’s what we have:

<img width="389" alt="Screen Shot 2020-12-05 at 6 51 08 PM" src="https://user-images.githubusercontent.com/1297121/101270142-1cb9eb80-372b-11eb-896d-df4bf4dc9827.png">

It ends up looking a bit blurry at regular size.

Here’s Mail — our should match this:

<img width="444" alt="Screen Shot 2020-12-05 at 6 51 23 PM" src="https://user-images.githubusercontent.com/1297121/101270149-33604280-372b-11eb-888b-a4c62e1a7d9d.png">

**Comment by vincode-io** [comment]
Please verify, but I think rolling back and forking the storyboard fixed this.
