### ISSUE TITLE
iOS: NNW use a lot of space on iCloud Backup.

### ISSUE THREAD

**Issue by kevinm6** [Ranchero-Software/NetNewsWire#2651]
NNW requires a lot of space on iCloud for Backup, I don't know if this change with the new release and maybe with "iCloud Sync".

![image](https://user-images.githubusercontent.com/72861758/101336403-b643e300-387a-11eb-8c07-5c59c9f67b68.png)

**Comment by vincode-io** [comment]
What is "iCloud sync feeds"?  There isn't a shipping version of NetNewsWire that uses iCloud.

Is it possible that you are backing up the documents folder for NetNewsWire and that is what you are seeing?

**Comment by kevinm6** [comment]
I don’t know the name you gave to the “iCloud Sync”: the milestone of upcoming NNW 6 around December 21.

It doesn’t seem!
But I’ll check better and let you know.

**Comment by philviso** [comment]
@kevinm6 What types of accounts do you have? Do you use a sync service, or is it just a local account?

At quick glance of the code (look for `NSURLIsExcludedFromBackupKey` and follow the trail), it looks like we're backing up databases related to sync services. If that's the case, we might be able to trim down the backup size by only backing up databases that we have no external way of being restored. If that's true we would only need to backup local account related stuff.

**Comment by kevinm6** [comment]
I’m using Feedly like sync service.
The backup of NNW on iCloud is taking 573Mb.

**Comment by kevinm6** [comment]
With the latest updates (even betas) the amount of data of NNW on iCloud Backups for me is okay, less than the half of the previous screenshot so I closed this issue.
