### ISSUE TITLE
Default toolbar set on Catalina has changed from NNW 5

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#2652]
![Screen Shot 2020-12-07 at 9 49 53 PM](https://user-images.githubusercontent.com/1297121/101446449-3a788380-38d8-11eb-8f05-7a3b88dd94e3.png)

It should be as it was in NNW 5.

**Comment by vincode-io** [comment]
This is a regression from me forking the storyboards and copying the 5.1 storyboard into the 6.0 branch.  Same with the Reader icon.  I'll get it straightened out shortly.
