### ISSUE TITLE
Auto-refresh didn’t happen after wake from sleep in the morning

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#2658]
I woke up my laptop in the morning. An hour later it hasn’t refreshed yet. (My setting is to refresh feeds every hour.)

**Comment by vincode-io** [comment]
This one has me puzzled.  I checked and we are still getting the wake notification on Big Sur and it is calling `fireOldTimers`.  This was the fix for this previously, so I'll have to dig in a little deeper here.

**Comment by vincode-io** [comment]
I can't recreate this.  I'm syncing fine after coming back from sleep.  I think we'll need more criteria to figure out what caused this.

**Comment by brentsimmons** [comment]
I wonder if this is a result of my running a Debug build.

**Comment by vincode-io** [comment]
If you have the debug menu enabled, I think you have to hit the refresh once to get the timer going.

**Comment by brentsimmons** [comment]
Closing this. We’ll see if other people report it or if it’s jut me running a Debug build.
