### ISSUE TITLE
 'Mark All as Read' window size (iOS)

### ISSUE THREAD

**Issue by mhoutman** [Ranchero-Software/NetNewsWire#2662]
When using a Feedly account and subfolders,, the 'Mark All as Read' window size needs a small resize.  This also makes a scroll bar obsolete.

![IMG_1869](https://user-images.githubusercontent.com/73284519/101644253-43cb3280-3a35-11eb-8a80-86728b496186.PNG)

**Comment by vincode-io** [comment]
That shouldn't be happening.  The size of the menu is computed by the system and usually only cuts off on super long menus.  We don't have much control over this, but let's try to figure out what is going on.

- Which version of iOS are you using?
- What device are you on?
- What is your text size set to in Settings?

**Comment by mhoutman** [comment]
Hi Mark,

I am on iOS 14.2, iPhone X and font size slider set centered.

If font size is smallest, I have same issue. In fact I can still scroll a bit in the 

Cheers, Michiel

**Comment by vincode-io** [comment]
What is your language setting?  

I'm trying to figure out why your menu is showing up in reverse order from what it normally does.  I've never seen that before.

**Comment by mhoutman** [comment]
Region: Dutch
Language: English UK


FYI: if region is set to US issue persists

**Comment by mhoutman** [comment]
On iPad same issues under iOS 14.2 and same settings

**Comment by vincode-io** [comment]
Are there any other settings that you can think of that might have impacted the order of the menu?  I've tried changing Language and Region to get it to go backwards with no effect.

Can you think of anything else you might have set that impacts the order of the menu?  Any Accessibility settings maybe?  Are you running any system hacks that might customize how iOS works?

**Comment by mhoutman** [comment]
Not really. 

But what do you mean with reverse order? All seems alphabetical

**Comment by mhoutman** [comment]
I deleted the app and made a fresh install. 

On my iPhone section same issue

**Comment by vincode-io** [comment]
The menu items are programmed to be in this order and that is the order that they show in on most devices.  For some reason they are backwards on your and cut off.  I can't figure out why.

![IMG_0004](https://user-images.githubusercontent.com/16448027/101672584-ab748400-3a1b-11eb-8334-06bbf4981faf.PNG)

**Comment by mhoutman** [comment]
Now I understand. 

I have no system tweaks or else but it this reverse order is very strange indeed.

Never mind but I am same as you: WHAT is cause 🤔

**Comment by kevinm6** [comment]
It happens even to me: 
![IMG_5478](https://user-images.githubusercontent.com/72861758/101679957-4f801e80-3a60-11eb-90d7-b4f8d80ac1ce.PNG)

- Region           : Italy
- Language      : Italian

- Model            : iPhone 7
- iOS Version   : 14.2
- NNW version : 5.0.5 (Build 56)

**Comment by vincode-io** [comment]
I think the clipping and scrolling problem was introduced in iOS 14.2, but I'm not positive.  I've never seen it before then at least.

I was able to successfully recreate this issue and it is already resolved in the upcoming NNW 6.0.  That confused the heck out of me.  Thanks for being patient.

![IMG_0005](https://user-images.githubusercontent.com/16448027/101697526-9872ab80-3a3d-11eb-8ba8-e51cfa2c8166.jpeg)

I'm labeling this for the 6.0 release and closing it.
