### ISSUE TITLE
Missing entitlement icloud-services... (macOS Big Sur)

### ISSUE THREAD

**Issue by rsyncOSX** [Ranchero-Software/NetNewsWire#2663]
Pulled last updates from master, the app stops (crash) due to a missing entitlement..

<img width="693" alt="Skjermbilde 2020-12-10 kl  07 07 44" src="https://user-images.githubusercontent.com/22427340/101728713-2b036100-3ab7-11eb-807f-f6adad9c9089.png">

**Comment by rsyncOSX** [comment]
The above build instructions are followed, still it does crash with execption.. The crash came probably last week after some updates, before last week compiled and executed OK

<img width="603" alt="Skjermbilde 2020-12-10 kl  20 13 35" src="https://user-images.githubusercontent.com/22427340/101818917-d8608e00-3b24-11eb-8006-cd0b46638b00.png">

**Comment by vincode-io** [comment]
My bad.  I should have had more coffee when checking this out this morning.  I'll look into it and see what we can do.

**Comment by vincode-io** [comment]
At what point are you receiving this exception?  Is it at application launch or are you trying to do something that triggers the exception?

**Comment by vincode-io** [comment]
Here is probably what happened to you.  You tried to add the iCloud account type because we didn't correctly have it hidden on the Developer build.  I've updated that, and you shouldn't be able to try to add it again.

To get your app to launch now, you will have to delete the iCloud account that got created.  Delete this folder and you should be good:  `~/Library/Application Support/NetNewsWire/Accounts/2_iCloud`

Let me know if this doesn't fix you up and I'll reopen the issue.

**Comment by vincode-io** [comment]
BTW, it looks like you are a developer.  If you have a paid developer account and are specifically wanting to try out iCloud support, you want to remove the `DEVELOPER_ENTITLEMENTS = -dev` from your shared build settings.  You will have access to things like Reader View and other account types that won't work without API keys.  You'll just have to step around those.

If you need help, Slack is a good place to find us.

**Comment by rsyncOSX** [comment]
Hi, I pulled the last changes and it still crash.. It stops in a closure in CloudKitAccount... Attached is a dump of scree where it crashes.. (with `DEVELOPER_ENTITLEMENTS = -dev`)
I am a developer, not at work though, and have a paid developer account.. 
Removing the `DEVELOPER_ENTITLEMENTS = -dev` did the magic, but there seems to be an issue with dev account..
Any way, nice work you are doing ..

![Skjermbilde 2020-12-11 kl  06 55 23](https://user-images.githubusercontent.com/22427340/101869068-e80cc080-3b7e-11eb-8152-dfd0b488a6f9.png)

**Comment by vincode-io** [comment]
Did you delete the `2_iCloud` Account when testing with the `-dev` configuration?  It will definitely crash if you have a CloudKit Account and are using `-dev`.

**Comment by rsyncOSX** [comment]
Switched off iCloud in pref and it does work (after adding -dev).. But then
it does not pick up any web sources... I dont know if this is a bug or just
something to do with dev configuration... I am compiling and using the
latest code pulled from master.. It is fine for me now, I am only using it
and also studying parts of your code...
[image: Skjermbilde 2020-12-11 kl. 07.23.01.png]
[image: Skjermbilde 2020-12-11 kl. 07.23.32.png]

fre. 11. des. 2020 kl. 07:08 skrev Maurice Parker <notifications@github.com
