### ISSUE TITLE
unable to get feeds to update

### ISSUE THREAD

**Issue by Thejereme** [Ranchero-Software/NetNewsWire#2664]
I have net newswire 5 on my Mac laptop, as does my boss...separate accounts.  neither of us can get new feeds since the last time we tried first of October.  I click 'refresh' and it looks like it is trying to download, but noting ever comes
![Screen Shot 2020-12-10 at 9 46 31 AM](https://user-images.githubusercontent.com/75804421/101809690-b3d8c780-3acc-11eb-8e90-5d9d348f3ec8.png)

**Comment by vincode-io** [comment]
Are you guys running any firewall software either on your Mac's or on your company network?  Little Snitch or something like that?

**Comment by Thejereme** [comment]
no firewall software...not even the one that comes with the Mac

**Comment by Thejereme** [comment]
![Screen Shot 2020-12-10 at 10 03 58 AM](https://user-images.githubusercontent.com/75804421/101811521-074c1500-3acf-11eb-83b3-1da8797a4d39.png)
most latest ad is from Oct 5

seems odd that 2 separate programs running on different computers under different accounts would have the same problem

**Comment by vincode-io** [comment]
It isn't odd.  You are on the same network and this looks like a network connection issue.  Do you require the use of a proxy server or is there company firewall software that is potentially blocking your network connections?

**Comment by Thejereme** [comment]
different network.  I am in Southern Oregon.  Boss is in Tucson Az

**Comment by vincode-io** [comment]
Are you running any VPN software to connect to your company network?

**Comment by Thejereme** [comment]
I just switched from my super-fast land line from Spectrum, to my semi-fast cell phone hot spot...no change

**Comment by Thejereme** [comment]
No VPN

**Comment by vincode-io** [comment]
Did you ever try any of the Beta's of NNW?  This might be due to some things we changed between the Beta's and the Release.

**Comment by Thejereme** [comment]
This morning, we were running version 4 something.  it had worked fine until this morning...although neither of us had opened the program since beginning of Oct.  in my troubleshooting, I updated to 5 (screenshot) and it still does not work. I am making the efforts to fix my issue before addressing my bosses, which is likely the same problem


![Screen Shot 2020-12-10 at 10 28 09 AM](https://user-images.githubusercontent.com/75804421/101814047-7119ee00-3ad2-11eb-914d-4a08c1d28198.png)

**Comment by vincode-io** [comment]
I'm not sure if you are aware or not, but versions of NetNewsWire before version 5 are not related to version 5.  NetNewsWire 5 is a brand new codebase.

Could you do an experiment for me?  Try to subscribe to https://inessential.com and send me a screenshot of the feed.

**Comment by Thejereme** [comment]
![Screen Shot 2020-12-10 at 10 35 51 AM](https://user-images.githubusercontent.com/75804421/101814863-8cd1c400-3ad3-11eb-81bd-5f52d84f9cd5.png)
that feed seems to work.  the other still don't.  not sure it's relevant...all the other feeds are looking at craigslist

**Comment by vincode-io** [comment]
It is very relevant.  Craigslist RSS feeds don't work anymore.  They discontinued support for them.

**Comment by Thejereme** [comment]
oh.......um.......this is vital, and the reason we paid for this program.  will that be coming back?

**Comment by vincode-io** [comment]
I don't think you understand.  You didn't buy the NetNewsWire from us.  It is free.  When you downloaded NetNewsWire 5.0 this morning, you must have noticed that no one asked you for a credit card number?

We are unaffiliated with Craigslist and have no control over their RSS feeds.  RSS feeds are like webpages.  If a web page goes away, you don't blame your web browser do you?  There is nothing we can do to bring back Craigslist RSS feeds.

**Comment by Thejereme** [comment]
ok
