### ISSUE TITLE
macOS: "Refresh feeds" popup button and "Privacy Policy" button are clipped in Preferences

### ISSUE THREAD

**Issue by LumingYin** [Ranchero-Software/NetNewsWire#2665]
Version: NetNewsWire Version 5.1.3 (3018)

Steps to reproduce:
1. System Preferences > Accessibility > Display > Turn on "Increase contrast". This step is optional, but makes the clipping issue more obvious.
2. NetNewsWire > Preferences > General. The "Refresh feeds" popup button is clipped.
3. Open the Advanced tab. The "Privacy Policy" button is clipped.

<img width="624" alt="Screen Shot 2020-12-10 at 10 52 46 PM" src="https://user-images.githubusercontent.com/20536283/101872787-ace89e00-3b3a-11eb-9c58-a2bc4025d207.png">
<img width="624" alt="Screen Shot 2020-12-10 at 10 52 48 PM" src="https://user-images.githubusercontent.com/20536283/101872790-ae19cb00-3b3a-11eb-90cb-86c2935ab7e8.png">

From [AppKit Release Notes for macOS Big Sur 11](https://developer.apple.com/documentation/macos-release-notes/appkit-release-notes-for-macos-11#NSButton):

> NSButton and its subclasses now draw more content outside their alignment rects. Therefore, if you pin them to a superview without any margins, the control will appear clipped. To resolve this issue, ensure that your controls are pinned with a minimum of standard space to the parent, rather than zero, to allow for sufficient space to fully draw the artwork. Alternatively, place your controls in NSStackView or NSGridView, which won’t clip their contents to the frame. NSStackView has had this behavior since inception; NSGridView adopts this behavior as of macOS Big Sur 11 beta 4.

**Comment by vincode-io** [comment]
These issues have been resolved in our upcoming 6.0 release of NetNewsWire which will be the first to adopt Big Sur UI changes.
