### ISSUE TITLE
Letterboxing on iPhone Mini

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#2666]
This screenshot of an iPhone Mini shows NNW 5, but we should make sure it’s not an issue on NNW 6, since we’re no longer updating NNW 5.

![image0](https://user-images.githubusercontent.com/1297121/101946333-ae9a7c00-3ba3-11eb-9e1c-3255b18d5451.png)

**Comment by vincode-io** [comment]
This took a little bit of doing to figure out.  The user has Display Zoom turned on.  Display Zoom simulates the screen size of another iPhone to make your display look bigger.  I'm not sure why NNW 5 doesn't fill the screen though.  It has always been build to be adaptable to different screen sizes.

This doesn't seem to be a problem for NNW 6, but we didn't do anything to accommodate for it.  Maybe you just have to link against the newer SDK?  I'm unsure, but it doesn't seem to be a problem and I ran the NNW 6 side by side with NNW 5.

**Comment by bsuto** [comment]
I can confirm, using the latest TestFlight build on a mini without display zoom, that every view looks as intended
