### ISSUE TITLE
macOS Big Sur: Strange deselect delay

### ISSUE THREAD

**Issue by jasonhan-vassar** [Ranchero-Software/NetNewsWire#2667]
This is a small bug and I'm not even sure if it's specific to NetNewsWire, but I felt I should report it. I am on NNW 5.1.3 and on macOS 11.0.1.

### Steps to reproduce
1. Select two or more articles using either Shift or Command
2. Left click on one of the selected ones
3. After a small delay, the others should deselect
4. Repeat the above, but left click on an unselected article this time

There should be a noticeable delay left clicking on a selected article, but there should be almost no delay for selecting an unselected one. Strangely enough, I can also reproduce this in other macOS apps like Notes, Mail, Activity Monitor, etc. Let me know if this is just a Big Sur/Swift bug or feature. Thanks so much for making this great app by the way!

**Comment by vincode-io** [comment]
That is a system behavior and, yeah, there isn't anything we can do about it.
