### ISSUE TITLE
Latest pull crash on getting Feedly resources..

### ISSUE THREAD

**Issue by rsyncOSX** [Ranchero-Software/NetNewsWire#2668]
Pulled latest code from GitHub, stops when pulling resources from Feedly..

![Skjermbilde 2020-12-14 kl  06 41 18](https://user-images.githubusercontent.com/22427340/102044834-f6094e00-3dd7-11eb-8b80-34222cb925ed.png)

**Comment by kielgillard** [comment]
Can you please paste the debug description of the `entry` property?

**Comment by kielgillard** [comment]
The [missing origin suggests](https://developer.feedly.com/v3/entries/#get-the-content-of-an-entry) the entry/article does not have a feed, which is not a big deal for NNW since every article is expected to be owned by a feed.

**Comment by rsyncOSX** [comment]
like this...
![Skjermbilde 2020-12-14 kl  09 12 04](https://user-images.githubusercontent.com/22427340/102056362-88b3e800-3dec-11eb-9317-58a2de359983.png)

**Comment by kielgillard** [comment]
@stuartbreckenridge That's right so the article will be skipped/ignored by NNW. The assertion was mostly there for me debugging Feedly content. It should probably be replaced with a log.
