### ISSUE TITLE
Thumbnail for feed is different in the current master build

### ISSUE THREAD

**Issue by jasonhan-vassar** [Ranchero-Software/NetNewsWire#2669]
After switching from the release build of 5.1.3 to building from master, I noticed the thumbnail for the RSS feed https://xkcd.com/rss.xml is different. It no longer uses the website's thumbnail but it uses the first image in the XML in this case:

### Old
<img width="236" alt="old" src="https://user-images.githubusercontent.com/34594853/102147096-2e407900-3e38-11eb-8c6f-9ef3c49175b3.png">

### New
<img width="236" alt="new" src="https://user-images.githubusercontent.com/34594853/102147134-41534900-3e38-11eb-9612-76d671a0bd22.png">

Was this an intentional change? If so, is this logged on a changelog somewhere? The latest changelog I could find was from [5.0.1](https://nnw.ranchero.com/2019/09/13/netnewswire.html).

**Comment by vincode-io** [comment]
This is intentional.  NNW 6.0 uses higher resolution images for the feed icon if available.  In this case, what you are seeing is the image specified in the open graph image (og:image) from the XKCD homepage.

**Comment by vincode-io** [comment]
I'm going to reopen this issue just to fix XKCD.  They seem to be switching the og:image to always match the current comic.  These are almost never legible when turned into an icon.  I'll be adding this to our `homePagesWithUglyIcons` array so that we don't use og:image when loading XKCD.
