### ISSUE TITLE
Hangs related to com.apple.network.boringssl.metrics_queue

### ISSUE THREAD

**Issue by michaeljtsai** [Ranchero-Software/NetNewsWire#2671]
I’m getting intermittent hangs after NNW has been running for a long time. The Dock reports that the app has stopped responding, and I have to force quit it. Then it usually works fine on relaunch until a day or two later when I get the same hang.

I’m using NetNewsWire 5.1.3 on macOS 10.15.7. This did not occur with 5.0.x on 10.14.6.

[Sample of NetNewsWire.txt](https://github.com/Ranchero-Software/NetNewsWire/files/5697734/Sample.of.NetNewsWire.txt)

**Comment by brentsimmons** [comment]
This looks like an Apple bug.

`Dispatch Thread Hard Limit: 512 reached in 1580 of 1580 samples -- too many dispatch threads blocked in synchronous operations`

And then, if you look, there are a ton of these:

`DispatchQueue_8226860: com.apple.network.boringssl.metrics_queue  (serial)`

…which don’t actually appear to be serial.

It looks to me as if Apple’s SSL metrics system is at fault. This isn’t a bug I’ve seen before.

**Comment by brentsimmons** [comment]
I’ve seen this with another use now, and my theory is that this is most likely to happen when people have a large number of feeds and they’re downloading  directly.

My guess: Apple’s doing some kind of metrics report on each feed download. But, if you have 1,000 feeds (or some large number), and Apple’s metric calls are slow to complete, then you could hit that 512 limit: `Dispatch Thread Hard Limit: 512 reached in 1580 of 1580 samples -- too many dispatch threads blocked in synchronous operations`

I don’t have a way to control this. Possibly I could slow down feed downloading to give the metrics system the chance to keep up.

**Comment by brentsimmons** [comment]
https://inessential.com/2020/12/23/com_apple_network_boringssl_metrics_queu

**Comment by tclementdev** [comment]
> And then, if you look, there are a ton of these:
> 
> `DispatchQueue_8226860: com.apple.network.boringssl.metrics_queue (serial)`
> 
> …which don’t actually appear to be serial.

I think they are serial, there are just *a lot* of those. Workaround indeed would be to bound the number of requests on your side.

**Comment by michaeljtsai** [comment]
> I’ve seen this with another user now, and my theory is that this is most likely to happen when people have a large number of feeds and they’re downloading directly (as opposed to using a syncing system).

Makes sense. I have around 1,500 feeds that NetNewsWire is fetching directly. I don’t know whether the problem is related to errors, but my guess is that many of the URLs no longer exist.

I agree that it makes sense to limit the number of requests. It doesn’t matter very much to me how long fetching takes. I just don’t want the app to hang.

**Comment by vincode-io** [comment]
@michaeljtsai Would you be so good as to share your OPML file with me if you are comfortable doing so?  I need one larger than I have available.  You can email it to me @ mo@vincode.io.

**Comment by michaeljtsai** [comment]
Sorry, I’m not comfortable sharing the file, but I can run a test build here if you would like.

**Comment by vincode-io** [comment]
Now that I think about it, I should be able to cobble one together on my own.  There are a bunch in iOS Dev Directory.

**Comment by vincode-io** [comment]
This should be fixed by https://github.com/Ranchero-Software/RSWeb/commit/44fb82a6aa400412faef77ca6eadb87cf3b8f38e which restricts each `DownloadSession` to 500 connections.
