### ISSUE TITLE
Reddit feed stopped updating

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#2672]
<img width="724" alt="Screen Shot 2020-12-15 at 1 06 31 PM" src="https://user-images.githubusercontent.com/1297121/102272930-67c7c180-3ed6-11eb-96d0-678eaa8c8d54.png">

<img width="315" alt="Screen Shot 2020-12-15 at 1 06 42 PM" src="https://user-images.githubusercontent.com/1297121/102272939-6c8c7580-3ed6-11eb-84b9-440602699283.png">

**Comment by vincode-io** [comment]
Is it possible that you disabled Reddit in the Preferences while testing?

**Comment by brentsimmons** [comment]
Looks like it’s still active:

<img width="538" alt="Screen Shot 2020-12-15 at 2 01 55 PM" src="https://user-images.githubusercontent.com/1297121/102278155-29ce9b80-3ede-11eb-8325-9809c906b976.png">

I’ll try pulling — I don’t have the very latest — and see if it fixes.

**Comment by brentsimmons** [comment]
Got the latest — still not updating.

**Comment by vincode-io** [comment]
Can you see any errors in the console door the RedditFeedProvider when you do a refresh?

**Comment by brentsimmons** [comment]
No matches for RedditFeedProvider.

**Comment by vincode-io** [comment]
We must be having some kind of token expiration problem. Can you add any new Reddit feeds like your Home feed?  If not, let's try disabling and enabling the Reddit extension. 

The first screenshot makes it look like you didn't refresh the feed since the 8th. Did you have your iCloud account inactive during this time?  I'm wondering if Reddit needs to be reauthorized if it was inactive for too long.

**Comment by vincode-io** [comment]
Before you disable the Reddit extension, we probably should use Proxyman to see what if anything is being received back from the Reddit request.

**Comment by brentsimmons** [comment]
Here’s what I get back from a request to https://www.reddit.com/api/v1/access_token 

```
HTTP/1.1 400 Bad Request
Connection: keep-alive
Content-Length: 40
Content-Type: application/json; charset=UTF-8
x-frame-options: SAMEORIGIN
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
x-ua-compatible: IE=edge
set-cookie: loid=00000000009colxjdy.2.1608083100004.Z0FBQUFBQmYyV2FjNG9vb2ExdDZxMkdsUGk4eTFjRk1VZlpPN2VpT25hNENrYzlSSmFNWHluNWhhQTNyc0sxNjNtTGoxWTRuclluTXRKMXNmMXhrdGZSdjc4NnJPOWpFanRoSWtuZGczTjNvSDM2dmNTd2U2NllETEFmcVZacm5URGpFdmNrT2Vsd3Q; Domain=reddit.com; Max-Age=63071999; Path=/; expires=Fri, 16-Dec-2022 01:45:00 GMT; secure
set-cookie: session_tracker=dYb64uF0vaRaiY0pmM.0.1608083100004.Z0FBQUFBQmYyV2FjWGNOY1JfSkNTekJicUtuNmROaXZpVlFlbGFGMDZWZjJqaHF4OUtCcG45SEhiQ2ZMeU92aFQ0Z0I2V1dBcFNMU1ExWWMxN0lQTzgtTkJtMlQwR1Y3eGpZWmc0TUo2bG1zQ2F6UDlGTkIwN2RHcWloUDJxempzeUhXeEtmeGpfSGY; Domain=reddit.com; Max-Age=7199; Path=/; expires=Wed, 16-Dec-2020 03:45:00 GMT; secure
cache-control: max-age=0, must-revalidate
X-Moose: majestic
Accept-Ranges: bytes
Date: Wed, 16 Dec 2020 01:45:00 GMT
Via: 1.1 varnish
Set-Cookie: edgebucket=kpKHfDVKT7KCYRljmx; Domain=reddit.com; Max-Age=63071999; Path=/;  secure
Strict-Transport-Security: max-age=15552000; includeSubDomains; preload
Server: snooserv

{"message": "Bad Request", "error": 400}

```

**Comment by vincode-io** [comment]
I wonder if your REDDIT_CONSUMER_KEY got corrupted or revoked.  Let's go ahead and disable/reenable the Reddit extension to find out.

**Comment by brentsimmons** [comment]
I deleted the extension, then re-added it, and now the feed updates. 👍

**Comment by vincode-io** [comment]
I'm not sure what happened with your access token(s).  Maybe they hadn't been used recently enough or you changed your password or did something that invalidated it.

We now throw an error if that happens with instructions to deactivate and activate the Reddit extension.
