### ISSUE TITLE
Folder disappear when mark as read MacOS 11.1

### ISSUE THREAD

**Issue by s4v4me** [Ranchero-Software/NetNewsWire#2673]
I don't know if it's due to the last macOS 11.1 update but when I marked all articles of that folder as read suddenly the folder disappear. To let it show again I have to uninstall the NNW6 and import subscription but the problem show again when I marked as read. How can be fixed? 

Thanks

**Comment by vincode-io** [comment]
Have you tried this menu option?

View -> Show Read Feeds

**Comment by Wevah** [comment]
I ran into this on Catalina. It’s non-obvious now that the filter icon has been removed from the sidebar. Maybe there should be a toolbar item?

**Comment by s4v4me** [comment]
> Have you tried this menu option?
> 
> View -> Show Read Feeds

usually they didn't disappeared but it works fine, thanks for the obvious answer.
