### ISSUE TITLE
Missing article statuses

### ISSUE THREAD

**Issue by vincode-io** [Ranchero-Software/NetNewsWire#2676]
I’m seeing a situation happen that has me baffled.  If I leave NNW running long enough on my desktop, end up with article records that don’t have status records.  I’m pretty sure that this invalid state is what caused my CloudKit crash the other day.  I created a sync record and when we tried to send the article, if failed because the fetcher wouldn’t retrieve it due to its missing status.

I had it happen to 4 different articles this evening.  I queried the database directly to make sure that the status records weren’t there.  As I was working on it, 2 of the articles got statuses from the CloudKit sync process.  The other two got cleared up when I was trying to recreate the problem.  I cleared the conditional get info, did a sync, and they created the missing statuses.

I can’t figure out how those articles are getting stored without statuses.  I don’t think the statuses are getting deleted by any of the clean up processes, or we would see a whole lot more deleted than we do.

**Comment by vincode-io** [comment]
This morning after letting NNW run all night, I had 10 missing statuses.  And got more information out of this instance.

I left NNW running and cleared the conditional get information so that it would try to recreate the statuses from the RSS feeds again.  I did this twice to be sure, but the statuses never got created.  I restarted NNW and cleared the conditional get info and all the statuses got created.

This leads me to suspect that the statuses are there in the internal cache when the problem happens, but not in the database.  I'm still not sure how we could possibly get into that state though.

**Comment by brentsimmons** [comment]
How are you noticing the missing statuses?

**Comment by vincode-io** [comment]
```sql
select * from articles 
where articleID not in
(select articleID from statuses)
```

**Comment by vincode-io** [comment]
I can confirm this to be a problem with local accounts as well as iCloud ones.

**Comment by vincode-io** [comment]
I verified that this is a problem in NNW 5.0.4 as well.  I added the following high volume feeds, set refresh to every 10 minutes, and let it run over night.  I ended up with about 180 missing statuses.

https://www.flickr.com/services/feeds/photos_public.gne
https://www.flickr.com/services/feeds/photos_public.gne?tags=beach
https://www.flickr.com/services/feeds/photos_public.gne?tags=car

@brentsimmons  The database compressed is 23MB.  I'll try to share it to you via iCloud if you want to take a look at it.

**Comment by brentsimmons** [comment]
I have tried and tried to reproduce this. Moving it to 6.1.

**Comment by vincode-io** [comment]
Ok, we finally caught this one in the act.

<img width="1897" alt="Screen Shot 2021-04-09 at 3 40 52 AM" src="https://user-images.githubusercontent.com/16448027/114157395-35a8f800-98e9-11eb-9bd2-111742f92501.png">

[console.txt.zip](https://github.com/Ranchero-Software/NetNewsWire/files/6284533/console.txt.zip)
[lsof.txt.zip](https://github.com/Ranchero-Software/NetNewsWire/files/6284536/lsof.txt.zip)

As best I can tell, we are holding open too many network connections and exhausting the number of allowed open file connections. That prevents us from opening the database and writing statuses to it.

**Comment by vincode-io** [comment]
This is probably unrelated, but I think we want to change this to a dedicated queue. It is probably doing a thread explosion. 

https://github.com/Ranchero-Software/RSParser/blob/0c575e1115149fe8ba324026aaf1784d15cb5ac9/Sources/Swift/Feeds/FeedParser.swift#L75

**Comment by vincode-io** [comment]
My working theory is that we need to release our references to the `URLSessionTask` faster in `DownloadSession`. Right now it is waiting until we have everything parsed and persisted before the reference to `URLSessionTask` is released. This is probably getting backed up due to the database serial queue and not closing the internet connections.

https://github.com/Ranchero-Software/RSWeb/blob/2f9ad98736c5c17dfb2be0b3cc06e71a49b061fa/Sources/RSWeb/DownloadSession.swift#L98

**Comment by michaeljtsai** [comment]
This seems like a good theory. I wonder if #2671 was masking this for me, i.e. when there was a thread explosion the whole app hung, which prevented it from committing too many status-less articles to the database. Maybe the number of connections should be even less than 500? (`ulimit -n` is only 256 for me.) I agree that it probably makes sense to use a dedicate queue that targets the global queue instead of using the global one directly.

**Comment by vincode-io** [comment]
Releasing the tasks quicker didn't do anything to solve the problem. I'm still not sure why NSURLSession is holding all those connections in a `CLOSE_WAIT` state.

I did notice a lot of duplicate TCP/IP addresses. All the ones I sampled seemed to have invalid certificates. Maybe NSURLSession never drops the connection if the certificate is bad?

I've been trying to do some research and I think we are using NSURLSession. One solution might be to create a new NSURLSession per sync session. I'd like to find a more surgical solution, but creating a new NSURLSession each time would probably get it done too.

**Comment by vincode-io** [comment]
I can't find what if anything we are doing wrong with NSURLSession.

I'm currently running a stress test where we recreate the NSURLSession on each refresh event. I can usually trigger this bug in less than 4 hours when refreshing every 10 minutes. For this test, I am refreshing every minute, so we should know soon if this issue has been mitigated.

**Comment by vincode-io** [comment]
Welp, that didn't work. We still exhausted the number of open files somehow. Back to the drawing board.

**Comment by brentsimmons** [comment]
Could this be an https keep-alive issue? Is there a way to turn that off?

**Comment by vincode-io** [comment]
I looked into the possibility that it was a keep-alive issue. I don't think that is the problem and besides, NSURLSession doesn't let you manipulate that HTTP header.

I spent a lot of time monitoring NetNewsWire as it did a refresh every minute using `lsof`. The number of files open climbed rapidly on each refresh. One thing that stood out when looking at the output from `lsof` was that there were a lot of connections in a TCP `CLOSE_WAIT` state. `CLOSE_WAIT` is when an application has received the command from the remote server to close the connection, but hasn't actually closed the port yet.

The ports with the `CLOSE_WAIT` state often had the same IP address of other ports in stuck in `CLOSE_WAIT`. I tried downloading from these suspicious IP addresses, but they all had invalid certificates. When I examined the certificates the ones I looked at all where for `api.twitter.com`.

At this point, I thought it might be a bug in `OAuthSwift` or a problem in how we were using it. So I copied all my feeds, except the Twitter and Reddit feeds, to a new local account. During stress testing of just the local account, the number of files open continued to climb, but at a much slower rate. I checked and again was seeing `CLOSE_WAIT` connections open. Again, the IP address had a bad certificate. This time the bad certificate belonged to Squarespace.

From what I understand, it is the job of the application to close the port when the remote server closes the connection. Managing the connection pool happens somewhere inside NSURLSession where we can't get to it (to the best of my knowledge). This looks to me like a Foundation bug in how it handles invalid certificates.

I guess next step for me is to create a sample project that recreates the bug. Through that process, I'll either figure out what we are doing wrong or have something to submit to Feedback Assistant. It also might be worth using a TSI for.

I think we should talk about crashing the app if we get a database error. I think it would be a rare occurrence and I think it is better than dealing with a corrupted database.

**Comment by brentsimmons** [comment]
What’s the lsof incantation you’re using? If I use it without arguments I get a ton of stuff, hard to filter.

**Comment by vincode-io** [comment]
You want to use `lsof -p` then the process number to only get the open files for the NetNewsWire process.

**Comment by vincode-io** [comment]
I tested this on macOS 12 and the problem doesn't exist there. It looks like this is a macOS 11 bug that we can't do anything about.
