### ISSUE TITLE
Release build is unnecessarily large

### ISSUE THREAD

**Issue by vincode-io** [Ranchero-Software/NetNewsWire#2680]
A couple things stand out.

Sparkle.framework is included 3 times in various places.  We also added Sparkle XPC Services to handle sandboxing, so that also added some size.

The Share Extension is 8mb.  This is because it includes the Account module so that it can share code between the main app and itself.  With a compiler directive, I think I can remove the dependency on the Account module while not changing much.  I think we can probably reduce the size of the extension down to next to nothing.

The main executable is much bigger.  That is partially because the the internal SPM modules aren't dynamic frameworks anymore and mostly because Account is much bigger than it used to be.

**Comment by stuartbreckenridge** [comment]
As part of the build phases, I added the following to the `Code Sign Sparkle` script to remove Sparkle in the places where it doesn't seem to be needed.

```shell
PLUGINS_DIR="${CODESIGNING_FOLDER_PATH}/Contents/PlugIns"
XPC_DIR="${CODESIGNING_FOLDER_PATH}/Contents/XPCServices"
find "${PLUGINS_DIR}" -name Sparkle* -execdir rm -rf {} \;
find "${XPC_DIR}" -name Sparkle* -execdir rm -rf {} \;
```

This doesn't seem to have any side effects and reduces the app size to 31.2 MB from 41MB.

**Comment by vincode-io** [comment]
Reopening, since we do have some more we can do.

**Comment by vincode-io** [comment]
I put the Share Extension on a serious diet and it is now down 7 MB from what it was.  Total app size is now under 25 MB.
