### ISSUE TITLE
NNW 6.0d1 - Unable to add feeds to iCloud account

### ISSUE THREAD

**Issue by stuartbreckenridge** [Ranchero-Software/NetNewsWire#2681]
<img width="1347" alt="Screenshot 2020-12-21 at 15 59 25" src="https://user-images.githubusercontent.com/7046652/102753294-f1c7cc80-43a5-11eb-8281-d05fcf3bc361.png">

**Comment by vincode-io** [comment]
@brentsimmons If this is built to sync against the Production iCloud, we will need to promote the schema to Prod.

**Comment by vincode-io** [comment]
We probably want to do some pruning of indexes before we do that.  CloudKit indexes stuff you don't need it to and that can get pushed to Prod when you promote.
