### ISSUE TITLE
Add Feed icons to notification content

### ISSUE THREAD

**Issue by stuartbreckenridge** [Ranchero-Software/NetNewsWire#2683]
![IMG_98BF425DFCFB-1](https://user-images.githubusercontent.com/7046652/102830865-3e9eb800-4425-11eb-99f1-56299bc3a518.jpeg)

**Comment by stuartbreckenridge** [comment]
This actually works out quite nice in the expanded view. The same problem exists with the globe appearing as a temporary icon every now and then. 


https://user-images.githubusercontent.com/7046652/102868684-6f0e4280-4475-11eb-8e82-c584f931ebf0.MP4

**Comment by stuartbreckenridge** [comment]
![9A832303-6FD6-4173-A6F5-74D2EF64A034](https://user-images.githubusercontent.com/7046652/102869063-0d9aa380-4476-11eb-8ec9-2c6232e4545c.png)

**Comment by vincode-io** [comment]
@stuartbreckenridge Is this something you still have some code around for that you can turn into a pull request?

**Comment by stuartbreckenridge** [comment]
I'm absolutely convinced this is already implemented.

**Comment by vincode-io** [comment]
The code looks like it is there to me. Closing this one.
