### ISSUE TITLE
iOS Feature Request: Presenting articles in different way

### ISSUE THREAD

**Issue by kevinm6** [Ranchero-Software/NetNewsWire#2684]
It would be nice to present articles when selected, as modal that can be dismissed by swipe down gesture o cover all the screen during scrolling.
Modal sheets appears even in Apple apps like Mail.

**Comment by vincode-io** [comment]
We use modal sheets where appropriate, but when navigating primary content you are supposed to use the navigation controller.  Sorry, but really like to stick with preferred platform conventions.
