### ISSUE TITLE
NNW 6: Error Loop

### ISSUE THREAD

**Issue by stuartbreckenridge** [Ranchero-Software/NetNewsWire#2692]
To recreate (using a Feedbin account):

1. Create a folder in your Feedbin account ("iOS Dev Directory")
2. Import the iOS Dev Weekly OPML (available [here](https://iosdevdirectory.com/opml/en/development.opml)) at the top level of your Feedbin account (i.e. not in the folder created in 1).
3. Drag the imported feeds to the folder in 1 
4. Feeds will move to the folder, however, after every 100 to 120 feeds this error will appear and cannot be resolved until you do a Force Quit
5. Once the app is restarted again, repeat the process from 3.

https://user-images.githubusercontent.com/7046652/103282716-98991200-4a11-11eb-877f-db1c3848fbb8.mov

**Comment by vincode-io** [comment]
I'm not sure what we should do with this one. It isn't in a loop. It is giving you an error for every network request that got timed out. There isn't any batch move API for Feedbin, so for each of those moves, there will be a network request.  

If Feedbin stop responding to network requests, what else are we supposed to do?

**Comment by brentsimmons** [comment]
Do we need to report an error for every failed network request? For the local account, we don’t alert the user for every feed that can’t be read for some reason.

**Comment by vincode-io** [comment]
Since this is a feed move, I think we need an error when it fails or the user is going to wonder why the move didn't work.
