### ISSUE TITLE
Bionic Reading© Integration

### ISSUE THREAD

**Issue by clivazpat** [Ranchero-Software/NetNewsWire#2695]
Would it be possible to integrate an additional option to activate [Bionic Reading©](https://bionic-reading.com/en/) to provide more visual comfort when reading articles?

> Bionic Reading®
A higher dimension of reading.
—
Bionic Reading wants to revolutionize reading. Our mission is: “A higher dimension of reading.” The eye is guided through text much more effectively with the aid of typographic highlights – thus creating a completely new reading experience. The Bionic Reading reading system is characterized by a specific interaction of the parameters “Fixation” and “Saccade”. More focus. Less distraction. More reading pleasure.

![EayksL-XQAAqB-9](https://user-images.githubusercontent.com/25901612/103412482-9354d800-4b75-11eb-8390-b772928c196e.jpeg)

Access to the API seems to be free and [instructions](https://www.notion.so/Bionic-Reading-API-v1-06a8507bceb848bfb2c6556b578aa1e0) are explained by the author.

**Comment by vincode-io** [comment]
See our comments in #2459 for why we don't add support for Bionic Reading.
