### ISSUE TITLE
Mac client not showing all Starred in Feedly, though iOS client does...

### ISSUE THREAD

**Issue by sck-nogas** [Ranchero-Software/NetNewsWire#2697]
Not sure if this is a Mac NNW or Feedly issue, but...
I checked the [GitHub repo Issues for Open and “Starred” ](https://github.com/Ranchero-Software/NetNewsWire/issues?q=is%3Aissue+is%3Aopen+starred) and did not see anything that matched this...

So, here’s some background...

I have 2 Feedly accounts (Acct #1 is via Feedly email/password, and Acct #2 is  via Google Auth) created
I have NNW installed on 2 devices...

Running MacOS 11.1, with NetNewsWire 5.1.3 (3018) (running Test builds)
Running iOS 14.3, with NetNewsWire 5.0.5 (56) via TestFlight

But, the views of the Starred items does not match between devices? Mac seems to not see all items it should.

[Feedly Acct_1 shows TWO “Read Later” items](https://nogas.org/nnw_github/Feedly%20Acct%20%231%20Read%20Later.jpg)

1. 	Acct_1 - CoolTool...
2. 	Acct_1 - UPS Holidays Promo...

[Feedly Acct_2 shows EIGHT “Read Later” items](https://nogas.org/nnw_github/Feedly%20Acct%20%232%20Read%20Later.jpg) (one is 3 months old so likely aged out)

1. 	Acct_2 - SolarWinds Attribution...
2. 	Acct_2 - I just published my first...
3. 	Acct_2 - I recently noticed the author...
4. 	Acct_2 - A first look at Chidra’s Debugger...
5. 	Acct_2 - Reverse Engineering for Everyone...
6. 	Acct_2 - Introducing ios_apt - iOS...
7. 	Acct_2 - SolarWinds Campaign Focuses...
8. 	Acct_2 - WIRE Buzz: Kodi Smit-McPhee... (3 months old)

[Mac shows THREE starred items](https://nogas.org/nnw_github/Mac%20NNW%20Starred.jpg)

1. 	Acct_2 - SolarWinds Attribution...
2. 	Acct_1 - CoolTool...
3. 	Acct_1 - UPS Holidays Promo...

[iOS shows NINE starred items](https://nogas.org/nnw_github/IOS%20NNW%20Starred.jpg)

1. 	Acct_2 - SolarWinds Attribution...
2. 	Acct_2 - I just published my first...
3. 	Acct_2 - I recently noticed the author...
4. 	Acct_2 - A first look at Chidra’s Debugger...
5. 	Acct_2 - Reverse Engineering for Everyone...
6. 	Acct_2 - Introducing ios_apt - iOS...
7. 	Acct_1 - CoolTool...
8. 	Acct_2 - SolarWinds Campaign Focuses...
9. 	Acct_1 - UPS Holidays Promo...

Maurice asked me "Could you write it up as a Github issue so that we don’t lose track of this?" 

I’ve uploaded images to my personal site and created links to the images showing the problem in this issue.

Wish I could be of more help on this. Thanks for the AMAZING software, have used NNW since 2.0!

**Comment by vincode-io** [comment]
@sck-nogas When you mark items as Starrred/Read Later do you typically do it using NNW or the Feedly website?

Let's try an experiment.  Could you delete Acct_2 from your Mac and then add it back in again?  I'm curious to see if it is just that particular account that got corrupted.

**Comment by vincode-io** [comment]
@sck-nogas Do your unread counts stay in sync between the devices and the website?

**Comment by sck-nogas** [comment]
Just did some more testing. 
1 - Opened feedly for both accounts and updated both iOS and Mac NNW feeds. (iOS matched Feedly website exactly, Mac has some unread counts slightly lower) 
> ![Feedly-Acct1](https://user-images.githubusercontent.com/2552839/104258695-ef044880-5434-11eb-9c55-e6d5df4329bf.jpg)
> ![iOS-Acct1](https://user-images.githubusercontent.com/2552839/104258706-f1ff3900-5434-11eb-99a4-f527d58d64a1.jpg)
> ![Mac-Acct1](https://user-images.githubusercontent.com/2552839/104258717-f62b5680-5434-11eb-89c2-749e497e4546.jpg)

Note: Gadgets has a different un-read count in Mac than Feedly/iOS
![Feedly-Acct2](https://user-images.githubusercontent.com/2552839/104258721-f9bedd80-5434-11eb-804f-ac31c97d15d7.jpg)
![iOS-Acct2](https://user-images.githubusercontent.com/2552839/104258723-fcb9ce00-5434-11eb-8155-d572056db604.jpg)
![Mac-Acct2](https://user-images.githubusercontent.com/2552839/104258736-004d5500-5435-11eb-96ab-65dfd2087543.jpg)
Note: Security-Blogs Security-News both have a lower un-read count as well on the Mac. 

I then read the 11 articles in Acct1 (10-Delica) folder on the Mac, synced the Mac, checked Feedly (it updated), synced iOS (it updated)

I then read the 86 articles in Acct1 (99-Deals) folder on iOS, synced iOS, checked Feedly (it updated), synced Mac (it updated)

I then checked the differences between the iOS/Feedly view and the Mac view of 40-Security-Blogs folder...
![iOS_Unread_40-Security-Blogs](https://user-images.githubusercontent.com/2552839/104259548-8027ef00-5436-11eb-9c71-af282ae38a69.jpg)
![Mac Unread_40-Security-Blogs](https://user-images.githubusercontent.com/2552839/104259561-84540c80-5436-11eb-9e15-5c6cc625f13b.jpg)

So, the problem seems real, but I can't seem to tie it down to any specifics yet.

Will delete the Acct_2 and re-add next.

**Comment by vincode-io** [comment]
@sck-nogas Do you leave your NNW on your Mac running all the time or do you close it when done?

**Comment by sck-nogas** [comment]
After deleting Acct2 and re-adding it to the Mac NNW, the counts between Feedly/Mac/iOS were the same.

I then deleted and re-added Acct1, and the counts between Feedly/Mac/iOS were also the same.

So, should I close this report?

No, I normally don't leave NNW on the Mac running. I open and close it a few times a day. Usually cuz if I see that there is something to read, I stop working and start reading. :)

**Comment by vincode-io** [comment]
If you are opening and closing NNW, then this isn't related to another known bug that I thought it might.

We should probably leave this open for now. I don't have any idea how we are going to figure out what happened to throw your unread counts and starred items off.  Just let us know if it happens to you again?

**Comment by sck-nogas** [comment]
Will do. And... Thank you to all the developers, testers, bug reporters, etc... NetNewsWire is AWESOME!!!!

**Comment by vincode-io** [comment]
@brentsimmons Can we consider this one a fluke and close it? It happened 9 months ago and we haven't heard any reports of anything similar since.

**Comment by brentsimmons** [comment]
Yes. Agreed.

**Comment by sck-nogas** [comment]
Thank you! Have NOT had ANY issues with this since switching to iCloud and am using it on iPhone/iPad/2 Macs/1 Partridge in pear tree. :) REALLY APPRECIATE ALL THE WORK!!!! Thank you!
