### ISSUE TITLE
Quoted bulleted lists display incorrectly

### ISSUE THREAD

**Issue by dgriffinjones** [Ranchero-Software/NetNewsWire#2701]
<img width="1131" alt="Screen Shot 2021-01-04 at 9 26 29 AM" src="https://user-images.githubusercontent.com/69601769/103584263-ff557a00-4eae-11eb-9969-4a1869b7afa4.png">
Quoted bulleted lists display as bulleted lists of individually quoted lines of text rather than a quote with a list inside it (Just look at the screenshot, I can't describe it well).

**Comment by vincode-io** [comment]
That's the way it is on the webpage too.  For some reason this is how the author wanted it to look.

<img width="492" alt="Screen Shot 2021-01-04 at 4 09 59 PM" src="https://user-images.githubusercontent.com/16448027/103584681-6707c700-4ea7-11eb-87e2-c38b8a4d8bca.png">
