### ISSUE TITLE
Code Signature Invalid Crash

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#2704]
Starting with macOS 10.15.4, we get crash reports from NetNewsWire users that reference `EXC_CRASH (Code Signature Invalid)`.

The code signature isn’t actually invalid, though.

And: the app must have launched okay on a subsequent try — because the crash report catcher runs on startup and it looks at crash logs on disk. If we have a crash log, that means a successful launch.

What worries me is that there are people for whom NetNewsWire crashes on launch every time, and we don’t get their crash logs.

NetNewsWire is not the only app to run into this problem. This search will reference more: https://www.google.com/search?q=code+signature+invalid+macos+10.15.4

Theory: the workaround for this is to reinstall NetNewsWire.

Here’s an example:

```
Process:               NetNewsWire [553]
Path:                  /Applications/NetNewsWire.app/Contents/MacOS/NetNewsWire
Identifier:            NetNewsWire
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           NetNewsWire [553]
User ID:               501

Date/Time:             2020-12-19 16:22:20.190 +0100
OS Version:            macOS 11.1 (20C69)
Report Version:        12
Bridge OS Version:     5.1 (18P3030)
Anonymous UUID:        230F1236-C122-458E-34AD-239D0B435041


Time Awake Since Boot: 120 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
   __TEXT                      106d4e000-106eb1000    [ 1420K] r-x/r-x SM=COW  

Thread 0 Crashed:
0   ???                           	0x000000010e1fb000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
 rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
 rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ffee8eb1b70
  r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
 r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
 rip: 0x000000010e1fb000  rfl: 0x0000000000000200  cr2: 0x0000000000000000

Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0

Thread 0 instruction stream not available.

Thread 0 last branch register state not available.


Binary Images:
      0x106d4e000 -        0x106eb0fff +??? (0) <8EA5FC4C-A908-3DF9-A66A-AA3A2BCEF75D> (null)
      0x10e1fa000 -        0x10e295fff +??? (832.7.1) <DEA51514-B4E8-3368-979B-89D0F8397ABC> (null)

External Modification Summary:
 Calls made by other processes targeting this process:
   task_for_pid: 0
   thread_create: 0
   thread_set_state: 0
 Calls made by this process:
   task_for_pid: 0
   thread_create: 0
   thread_set_state: 0
 Calls made by all processes on this machine:
   task_for_pid: 169
   thread_create: 0
   thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=2456K resident=0K(0%) swapped_out_or_unallocated=2456K(100%)
Writable regions: Total=8420K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8420K(100%)

                               VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
VM_ALLOCATE                          8K        2 
__DATA                             420K        4 
__DATA_CONST                        56K        2 
__LINKEDIT                         428K        3 
__TEXT                            2044K        2 
===========                     =======  ======= 
TOTAL                             66.9M       15
```

**Comment by georgesnow** [comment]
Not sure this helps exactly, and happen to have just read this, but it appears signature doesn't match or it's access something it doesn't have permissions for. The later seems more likely since some people may have granted access others not. 


"EXC_CRASH (Code Signature Invalid)
and a little further down the Termination Reason might be given as
Namespace CODESIGNING, Code 0x1
Those are typical for an app which no longer matches its own signature...access privacy-protected resources for which it doesn’t have appropriate settings"

Link: https://eclecticlight.co/2019/06/17/what-to-do-when-you-cant-launch-an-app/

**Comment by georgesnow** [comment]
This is similar crash that people experienced on Outlook.app. Microsoft reply indicates if reinstall of the app and removing the app specific container folder it relates to the device itself and not the app (NNW in this case)

And confirms the theory of reinstall tends fix it.

Link: https://answers.microsoft.com/en-us/msoffice/forum/msoffice_outlook-mso_mac-mso_o365b/unkknown-version-of-outlook-crashes-in-catalina/2544b225-1c02-4b77-a085-d59170cab1e5

**Comment by Unkaputtbar** [comment]
I did not look too much into the details of your crash here, but maybe Craig Hockenberry’s analysis of his code sign issue applies to you as well: https://furbo.org/2020/12/01/codesign-the-saga-continues/.
Please ignore this comment, if you have already looked into this.

**Comment by brentsimmons** [comment]
It sounds like Craig’s thing is probably our issue too — sounds like we need an updated Sparkle.

**Comment by brentsimmons** [comment]
Closing this as a NNW 6 issue. We’ll re-open it only if needed.

We’re ignoring this for NNW 5, because we think it’s a Sparkle issue and we don’t plan to do any more updates for 5.
