### ISSUE TITLE
Feedbin: update credentials dialog has Add Account button (should be Update instead)

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#2712]
When Feedbin refreshing fails, and the app asks you to update your Feedbin credentials, the dialog that appears has an Add Account button at the bottom. That button should say Update or Update Credentials instead (whichever looks right when you try it).

**Comment by vincode-io** [comment]
I can't find this.  Could you attach a screen shot?

![IMG_0009](https://user-images.githubusercontent.com/16448027/104049298-5ce90f80-51aa-11eb-84d3-b5e9e2d4cda7.PNG)

![IMG_0008](https://user-images.githubusercontent.com/16448027/104049311-62def080-51aa-11eb-85b4-90bbfa7a55ae.PNG)

**Comment by brentsimmons** [comment]
I’ll take a screenshot, and reopen this ticket, if it happens again.
