### ISSUE TITLE
Flickr feeds dragged from local account to iCloud account never sync to other Mac

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#2714]
On a Mac running Catalina, I had three Flickr feeds in a local account called “Test”…

https://www.flickr.com/services/feeds/photos_public.gne?tags=beach
https://www.flickr.com/services/feeds/photos_public.gne?tags=car
https://www.flickr.com/services/feeds/photos_public.gne

…I dragged those from there to my iCloud account. (They were in a folder — I may have dragged the folder.)

On another Mac (Big Sur), those feeds, and that folder, never appears in my iCloud account. (It’s been a week or two.)

**Comment by vincode-io** [comment]
I just tested this and the feeds instantly synced across all my devices.  I've been testing iCloud for 9 months now and haven't been able to get the feeds themselves out of sync that I can recall.

Is there anything more you can give me to go on?  Did you crash during a sync or quit while syncing or something?  That shouldn't matter, but at least it would give me a clue as to what happened.

@stuartbreckenridge Have you seen any feeds go out of sync while adding and changing them?

**Comment by stuartbreckenridge** [comment]
Nope

**Comment by vincode-io** [comment]
@brentsimmons Do you remember if you were moving a lot of feeds all at the same time?

**Comment by vincode-io** [comment]
I've been abusing the copy function this morning and can't get out of sync.  I've tried multiple folders full of feeds and they all move over ok and sync across my devices.

What may have happened is that your local sync token got updated, but that folder never got created.  This _shouldn't_ be possible, even if you crash mid-sync.  The sync token is a check-point used to determine which changes you get from CloudKit.  To find out if this is what happened, could you disable then re-enable the iCloud on the computer with the missing folder and feeds?

If they show up, then we know we have an issue with the sync token getting updated when it shouldn't have been.

**Comment by brentsimmons** [comment]
I tried disabling and then re-enabling, and it didn’t add the folder and feeds.

**Comment by vincode-io** [comment]
That helps.  The feeds never made it into CloudKit then.

I think this must have happened before I did c150d19 and you were having CloudKit issues.  You shouldn't be able to create Feeds locally anymore if you get an iCloud failure.  I also made it so that you can delete the incorrectly created local feeds and add them again if you want.

**Comment by brentsimmons** [comment]
I’ll close this, and reopen it if it happens again after doing up-to-date builds.
