### ISSUE TITLE
Feature Request: report unread/read status immediately to Feedly

### ISSUE THREAD

**Issue by ArttuLai** [Ranchero-Software/NetNewsWire#2718]
I noticed that if my Feedly articles are marked as read in NetNewsWire, I need to perform a full sync for the read status to sync with other RSS clients using Feedly  

I know it's possible to do because Reeder does this. It's pretty convenient to not have to remember to perform a sync at the end of a reading session, and to be able to continue where you left off on other device. 

Does anyone know if Feedbin sync works with this?

I realize I ca set the feed refresh interval to 10 mins and that would probably be pretty OK experience generally, but does the refresh work reliably if I quit NNW completely? Maybe reporting just the read status is a lighter operation which could be performed a lot more often than the full sync?

**Comment by vincode-io** [comment]
We automatically sync statuses every 2 minutes regardless of refresh interval.  We don't want to do a network request for every unread that happens, so we batch them in 2 minute intervals.

On iOS we do also sync when you switch away from the app.  Unfortunately, macOS doesn't give us a good way to do the asynchronous network calls our sync systems use when quiting the app.

**Comment by ArttuLai** [comment]
@vincode-io Okay that's great to hear! I didn't catch that as I was testing it immediately after marking it read in NNW.

I think I’ll close the issue then.

**Comment by vincode-io** [comment]
Leave it open.  I think I might have found a solution to the shutdown on macOS problem.

**Comment by ArttuLai** [comment]
OK great.

**Comment by vincode-io** [comment]
@ArttuLai I did get this figured out.  Unless I messed something up, this will be in the upcoming 6.0 release of NetNewsWire.

**Comment by ArttuLai** [comment]
Thank you
