### ISSUE TITLE
Feedwrangler Support

### ISSUE THREAD

**Issue by sgoodwin** [Ranchero-Software/NetNewsWire#272]
Some of us use Feedwrangler, would be cool if Evergreen supported it when it started supporting syncing services.

**Comment by clausTue** [comment]
I'd be happy to see Feedwrangler supported. The only reason is because this is what I'm using. 

What could be reasons in favour of (for me to switch to) FeedBin (see [this ticket](https://github.com/brentsimmons/Evergreen/issues/239))?

**Comment by chipotle** [comment]
I'd like to add a +1 to this. I don't have a sense of which services are the most popular and which to prioritize (I don't know if the "poll" in issue #423 is really a particularly good guideline), but I _suspect_ Feed Wrangler is fairly popular for the prosaic reason that it's cheaper than many of its competitors.

**Comment by ZevEisenberg** [comment]
@clausTue Feedbin is open source and [private by default](https://feedbin.com/blog/2018/09/11/private-by-default/), which is cool. Not necessarily a reason to switch, and if you primarily use these services via third-party clients, there's probably very little difference between them.

**Comment by clausTue** [comment]
@chipotle @ZevEisenberg while I would like some improvements to Feedwrangler it does its job. I agree with @chipotle the main reason I'm using it, is that it's less than 20€ per year, whereas feedbin is 50$ per year. That being said, it is quite basic. 

Maybe I'm coming to the conclusion, that syncing is not the most urgent thing. If I read my feeds once per day in netnewswire, that might be sufficient...

**Comment by eschaton** [comment]
Since all my feeds are in Feed Wrangler (and I have a lot of them) this is the primary thing holding me back from using NetNewsWire 5 as my main feed reader.

**Comment by rwgrier** [comment]
+1 for Feed Wrangler support here too. It's a great service and my feeds are all there.

**Comment by ragfield** [comment]
+1 for Feed Wrangler support.

**Comment by groomsy** [comment]
+1 for Feed Wrangler support.

**Comment by vincode-io** [comment]
FeedWrangler is shutting down so we don't have any further plans to support it.
