### ISSUE TITLE
Some folders don't delete already read articles

### ISSUE THREAD

**Issue by krabf** [Ranchero-Software/NetNewsWire#2722]
Articles from Pitchfork, IndieWire, Vox, Mubi, etc. since November 2020 are still in my folder and even in I mark them as read/unread all over again they don't somehow "disappear" or deleted. 

I am using Feedly to subscribe to RSS by the way.

Thank you!

**Comment by vincode-io** [comment]
For sync systems like Feedly we retain the articles for 90 days, so this is expected behavior.  After an article is read and older than 90 days, we will delete it unless it is starred.
