### ISSUE TITLE
Can’t delete Reddit feed from iCloud account

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#2723]
Feed URL is: https://www.reddit.com/r/popular/top

<img width="294" alt="Screen Shot 2021-01-12 at 9 26 36 PM" src="https://user-images.githubusercontent.com/1297121/104410335-f69f1c80-551c-11eb-8563-c82d5dee3b9b.png">

Issue happens on Big Sur Mac and Catalina Mac.

**Comment by vincode-io** [comment]
Is it possible that you added that feed while using a build that pointed at the Production CloudKit environment and then tried to delete it using a build that points to the Development CloudKit environment?

**Comment by brentsimmons** [comment]
Yes, absolutely possible.

**Comment by vincode-io** [comment]
I've changed it so that we are always using the Production iCloud environment so that this doesn't happen again.
