### ISSUE TITLE
Undo Delete Feed with iCloud account didn’t work

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#2724]
I deleted a feed (my own blog) from my iCloud account. Then did Undo Delete Feed — but it didn’t return.

**Comment by vincode-io** [comment]
I just did this a bunch of times and it worked each time for me.  I need more info on how you got this to happen to debug it.

Is it possible that you did this right after you did that big Programmers folder move?  If so, the app might have been busy syncing all the article statuses and the undo delete would have been queued up after that.

**Comment by brentsimmons** [comment]
I’ll close this — it might have been just me. We can open a new ticket if testers report it.
