### ISSUE TITLE
Dragging folder to iCloud results in multiple errors about a feed that can’t be found and can’t be added

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#2728]
I dragged my Programming folder from Feedbin to iCloud. The app read a bunch of feeds — I could tell because the unread count went way up.

But I got about a half-dozen error dialogs: “The feed couldn’t be found and can’t be added.”

Afterwards: I still see a Programming folder in Feedbin, and I don’t see that folder in iCloud.

But I _do_ see a bunch of unread articles in All Unread that would be coming from the Programming folder in iCloud.

**Comment by brentsimmons** [comment]
Later — I went to quit, and got the same long delay previously reported. I’ve put that sample in #2726.

**Comment by brentsimmons** [comment]
Here’s a screenshot of the error message:

<img width="290" alt="Screen Shot 2021-01-12 at 10 04 35 PM" src="https://user-images.githubusercontent.com/1297121/104412981-4af8cb00-5522-11eb-81c1-1321d035a15d.png">

**Comment by vincode-io** [comment]
You had a bunch of dead feeds in your Programming folder.  That is why you get that error message.  We've never copied dead feeds in any account type before.  Do we want to start copying dead feeds?

**Comment by brentsimmons** [comment]
When copying feeds in the sidebar to the iCloud account, all the feeds should copy. Even if they’re dead, even if they return 404 or whatever.

We should display that error message only when manually adding a feed to the iCloud account.

**Comment by vincode-io** [comment]
I assume you want this change for all account types?  This isn't an iCloud specific issue.

**Comment by brentsimmons** [comment]
Duplicate of #2725
