### ISSUE TITLE
Apple TV support

### ISSUE THREAD

**Issue by tpuschel** [Ranchero-Software/NetNewsWire#2732]
Hey people,

was wondering if a version of the app for Apple TV is somewhere on the roadmap.

One of the uses of RSS for me is subscribing to YouTube channels without having a Google account.

Having the app on Apple TV would allow one to directly watch a new video on their TV without needing AirPlay, which is finicky and has quality constraints.

Thanks for your work anyway! :)

**Comment by brentsimmons** [comment]
Thanks for the feature request! But we have no plans to do an Apple TV app.

**Comment by brentsimmons** [comment]
Since Apple TV doesn’t have a web browser, I can’t think of a way to share an article to Apple TV. If you have any ideas, let me know!
