### ISSUE TITLE
Search bar has low contrast on macOS

### ISSUE THREAD

**Issue by NilsEnevoldsen** [Ranchero-Software/NetNewsWire#2733]
The search bar has low contrast on macOS. This makes it hard to locate the draggable portion of the top bar at a glance.

<img width="953" alt="macos-light" src="https://user-images.githubusercontent.com/222743/104752268-7814cb80-5724-11eb-9811-d3929305c93d.png">
<img width="917" alt="macos-dark" src="https://user-images.githubusercontent.com/222743/104752262-76e39e80-5724-11eb-9fda-6d7722270fe6.png">

On the other hand, the contrast on iOS is fine.

![ios-light](https://user-images.githubusercontent.com/222743/104752260-74814480-5724-11eb-9f13-8530ed8f2396.PNG)
![ios-dark](https://user-images.githubusercontent.com/222743/104752257-73501780-5724-11eb-8a73-61ab9f63f598.PNG)

**Comment by DrTacoMD** [comment]
Looks like this is just using the system search bar, yes? I see the same (admittedly poor) contrast level in the Finder on macOS Big Sur.

![Finder Search Bar](https://user-images.githubusercontent.com/4934719/104762259-e358a080-5718-11eb-9c3f-6fda828b709e.png)

**Comment by NilsEnevoldsen** [comment]
Eesh. Looks like you're right. I prefer this style, but if the low- (kind of zero-, tbh) contrast box is the/another valid OS standard, then I guess I don't have much of a leg to stand on.

<img width="409" alt="Screen Shot 2021-01-15 at 1 06 03 PM" src="https://user-images.githubusercontent.com/222743/104762521-823dc680-5732-11eb-952d-6c4856f7e2b7.png">

**Comment by brentsimmons** [comment]
Yes, we use the standard system search bar. It’s worth filing bugs with Apple about their low-contrast design.

**Comment by NilsEnevoldsen** [comment]
That's the right call. And in case anybody who sees this thread has a _lot_ of trouble with contrast on Big Sur, there's always high contrast mode (System Preferences > Display > Increase contrast).

<img width="972" alt="Screen Shot 2021-01-15 at 1 52 14 PM" src="https://user-images.githubusercontent.com/222743/104766721-0a26cf00-5739-11eb-9469-53d835a77351.png">
