### ISSUE TITLE
[Q] transfering to the next non-zero topic quickly (feature)

### ISSUE THREAD

**Issue by kkdd** [Ranchero-Software/NetNewsWire#2735]
Hello,
I would like to transfer the selected site to the next non-zero one (see the image below), quickly by keyboard shortcut. Is this functionality available?

![netnewswire](https://user-images.githubusercontent.com/5372642/104810388-80a9f680-5837-11eb-871c-edf256cff9a2.jpg)

**Comment by vincode-io** [comment]
I think you are looking for the "n" keyboard shortcut.  There is a list of available keyboard shortcuts in the Help menu.

**Comment by kkdd** [comment]
Thank you for your suggestion.
But I should correctly describe my hope as "transferring to the next non-zero site", which seems to be realized by the "n" keyboard shortcut.
