### ISSUE TITLE
Mac: Can't connect to Inoreader when email address has "+"

### ISSUE THREAD

**Issue by gxwilso** [Ranchero-Software/NetNewsWire#2736]
My Inoreader email address includes a "+" character and I'm not able to connect: I repeatedly get a Network Error message. I changed my Inoreader account's email address to something without the special character and was able to connect.

**Comment by vincode-io** [comment]
@gxwilso Could you let me know which email service you are using?  I'm having trouble finding one that allows "+" in the email address and I'll need that for testing.

**Comment by gxwilso** [comment]
Any existing Gmail address will let you use a "+" address and email sent to that address is actually sent to the primary address. So, if I own foo@gmail.com I can use foo+bar@gmail.com and any email sent to that address will arrive in the foo@gmail.com mailbox. When I sign up on a web site I add the name of the service so I can track if I get junk email.

Greg
