### ISSUE TITLE
Check for Updates is not working

### ISSUE THREAD

**Issue by LitoFrame** [Ranchero-Software/NetNewsWire#2738]
On my iMac (masOS Big Sur) Update is not working both with 5.1.3 or with 6.0d4 versions. I got this message:

![Screenshot 2021-01-17 at 11 09 40](https://user-images.githubusercontent.com/42410142/104838737-c6f16b00-58b4-11eb-82c3-fe5df956e61e.png)

On my Macbook Pro (macOs Catalina) update is working. What could be the problem?
Thanks!

**Comment by kevinm6** [comment]
I don’t have any problems both on NNW 5.1.3 and 6.0d4 on macOS Big Sur. 
Be sure you don’t have any firewall that block the connection (like Little Snitch or LuLu).

**Comment by LitoFrame** [comment]
I have Little Snitch, but I don't block NNW. When I switch off Little Snitch I got the same error message.

**Comment by LitoFrame** [comment]
Is it possible that you block some IPs? I use VPN when I switched off the update is working. The strange thing, that when I switched the VPN on again, update is still working. Now I have a different IP, than before.

**Comment by kevinm6** [comment]
Search if Little is blocking or if your firewall is blocking this "/Applications/NetNewsWire.app/Contents/XPCServices/org.sparkle-project.Downloader.xpc”.
Because NNW use Sparkle framework for updates.

**Comment by kevinm6** [comment]
> Is it possible that you block some IPs? I use VPN when I switched off the update is working. The strange thing, that when I switched the VPN on again, update is still working. Now I have a different IP, than before.

It could be just a little bug of the vpn or firewall that for one moment it doesn’t allow the connection.

**Comment by LitoFrame** [comment]
> Search if Little is blocking or if your firewall is blocking this "/Applications/NetNewsWire.app/Contents/XPCServices/org.sparkle-project.Downloader.xpc”.
> Because NNW use Sparkle framework for updates.

Little Snitch don't block that

**Comment by LitoFrame** [comment]
> > Is it possible that you block some IPs? I use VPN when I switched off the update is working. The strange thing, that when I switched the VPN on again, update is still working. Now I have a different IP, than before.
> 
> It could be just a little bug of the vpn or firewall that for one moment it doesn’t allow the connection.

Yes, it could be. :)
Anyway, thanks for your help. It is working now, so I close this issue.
