### ISSUE TITLE
Disappearing unread count

### ISSUE THREAD

**Issue by kevinm6** [Ranchero-Software/NetNewsWire#2740]
On macOS Big Sur, with the pre-release NNW 6.0d4 and Feedly account, every refresh removes the badge of unread items, everywhere.

I didn’t check iCloud account because I’ll use it  as main account when the iOS test build is available.

Another thing that happens every time is that if NNW receive the command to quit takes a long time to exit completely from the app with the spinning wheel rotating.

**Comment by vincode-io** [comment]
@kevinm6 Could you please upload a recording of the problem you are seeing with disappearing unread item badges?  I just want to make sure we are talking about the same thing.

**Comment by kevinm6** [comment]
@vincode-io sure! Here we are… as you can see, with the iCloud account there’s no similar bug.
If you need some other test to do, ask me.

https://user-images.githubusercontent.com/72861758/105008535-a9014300-5a39-11eb-828e-1ba6a07bc2dd.mov

**Comment by kevinm6** [comment]
Sorry, is almost the same of #2727, but for me happens only with the Feedly account where I have linked even NNW 5.0.5 (Build 56) on the iPhone! Instead the iCloud one works fine for now, with only one device synced.

**Comment by kevinm6** [comment]
I don't know if this can help:
I've removed the Feedly account, close NNW (it's taking a lifetime to close), then open it again and sign in back to Feedly account and wait for the complete sync of all the feeds.
Now I don't have this bug for the unread badges on both Feedly and iCloud account.

**Comment by vincode-io** [comment]
@kevinm6 When the issue with you Feedly unread count badges was happening, did it persist after restarting NNW, but before you deleted your Feedly account?  I'm trying to determine if we got memory or the database into a weird state.

**Comment by kevinm6** [comment]
Yes, exactly!
Was happening even after restarting NNW.
I've tried after restart it and I've tried also deactivating all the accounts and enable them after the restart.

**Comment by kevinm6** [comment]
@vincode-io I think you are in the right direction, because now I remember it kept happening also after I tried to move all the feeds to the iCloud account, refresh the app and copy them back.
Maybe it could be some bug or conflict  that generated by the update.

**Comment by vincode-io** [comment]
What I think happened is that the `FetchAllUnreadCountsOperation` was failing or getting back zero results, but that selecting the articles themselves worked fine.  That is why when you click on a `Feed` the unread count would appear.  When articles are fetched, they update the `Feed` with the unread count from the fetched articles.

Why that is happening, is a mystery to me.  In retrospect I should have had you send me the database for your Feedly account.  It was probably corrupted in some way, but now we don't have a way to figure out how or if it was.

**Comment by kevinm6** [comment]
Could it be possible that maybe the exactly same name of the folders feeds on different accounts (same database) helps to create this problem?
Sorry, but I don't know how you developed the code about counting the unread badges

**Comment by brentsimmons** [comment]
Different accounts are stored in separate databases.

**Comment by kevinm6** [comment]
Got it.
I’m trying the new version @brentsimmons (6.0d5)! It seems much faster and all for now is working fine.
The only thing is that I didn’t found any updates from the previous one, in NNW > Settings > Advanced > Check For Updates (and the radio button is set to "Test Builds”), I don’t know if is intended.

**Comment by brentsimmons** [comment]
I just haven’t actually released it yet. :)

**Comment by brentsimmons** [comment]
We can revisit this if it comes up again.
