### ISSUE TITLE
Proper Folder Support with NewsBlur?

### ISSUE THREAD

**Issue by PBones** [Ranchero-Software/NetNewsWire#2741]
I just loaded up my NewsBlur account in NNW 6 - woo! I'm excited to use NNW and NewsBlur together.

However, NNW shows all my sites and then also all of my folders, with those same sites inside them. So, all of my sites are doubled up. 

<img width="222" alt="image" src="https://user-images.githubusercontent.com/1578556/104857657-071e1100-58e8-11eb-8579-40f3a11c0f6e.png">

**Comment by PBones** [comment]
(Reddit is in the Dismissible folder, so that's the same “6”)

**Comment by vincode-io** [comment]
Turns out we didn't test for the scenario that all feeds were all in folders and and we missed a clean up step because of it.
