### ISSUE TITLE
Error while creating Feedly feed (on NetNewsWire for Mac)

### ISSUE THREAD

**Issue by boborbt** [Ranchero-Software/NetNewsWire#2743]
I cannot activate the feedly account in NetNewsWire for Mac (I'm running Version 5.1.3 (3018) on Mac Os Big Sur Version 11.1).

Everything works smoothly up to when I confirm the login (I'm connected through the google signon). Then, instead of activating the account in feedly I get the following error message: "The operation couldn’t be completed. (Secrets.CredentialsError error 0.)".

After that point, the account is shown on the left sidebar, but it has empty contents. If I try again to create the account I get the error: "There is already a Feedly account with that username created.".

**Comment by vincode-io** [comment]
Is it possible that you changed the NetNewsWire.app name or had it changed at one time?  That is typically how that error gets triggered.  Please see this issue for instructions on how to clear it up.   #2419

**Comment by boborbt** [comment]
Yes, that was it!  I deleted the feedly items in the keychain, recreated the feed and all seems to work fine now!

Thanks for your help.
