### ISSUE TITLE
website icon sometimes visible, sometimes not

### ISSUE THREAD

**Issue by LitoFrame** [Ranchero-Software/NetNewsWire#2744]
I have 2 folders which contains several feeds from the same website. When I click to the folder I always can see the website icons left of the title of the article. Sometimes when I click from the folder to a separate feed I can see the website icon, but sometimes not.

![Screenshot 2021-01-18 at 17 36 53](https://user-images.githubusercontent.com/42410142/104947526-c8ee2380-59b3-11eb-9d6b-087a6bf04a63.png)
![Screenshot 2021-01-18 at 17 30 15](https://user-images.githubusercontent.com/42410142/104947549-ce4b6e00-59b3-11eb-9cd2-69d75a713994.png)

This is a separate feed in iCloud. I cannot do it with every feed, just a few.
NNW 6.04d, macOS Big Sur

**Comment by vincode-io** [comment]
This is by design.  We don't show the icons for individual feeds unless they contain additional author information.  This is to help increase information density in the Timeline when the feed icon would just all be the same thing for all entries.
