### ISSUE TITLE
Bug: Feed cannot be added

### ISSUE THREAD

**Issue by gferreroferri** [Ranchero-Software/NetNewsWire#2746]
I cannot add the following RSS feed
http://www.hel.fi/wps/wcmjspv2/filtered-news-listing.jsp?rss=rss
http://www.hel.fi/wps/wcmjspv2/filtered-news-listing.jsp?rss=rss&lang=en
Somehow netnewswire does not recognise it

**Comment by kevinm6** [comment]
I tried with both the feeds and they works on NNW 6.04d. I don’t think there are any difference with the previous version.
Be sure you don’t have any firewalls or others blocker.

**Comment by gferreroferri** [comment]
I have tried it with Feedly and it works, but I cannot move the feed to iCloud. For some reason the feed is not accepted in the iCloud side

**Comment by rex4539** [comment]
I have also experienced this bug on multiple feeds.

Add a feed "On My Mac" and then try to drag it to "iCloud".

Some feeds are not able to be dropped into iCloud.

**Comment by vincode-io** [comment]
@gferreroferri there is something wrong with the feed that is preventing our parser from working with that it. We'll figure it out as soon as we can.

**Comment by vincode-io** [comment]
@rex4539 if you have a feed that you are sure is still valid and can't be added to iCloud please open a separate bug report for it.

**Comment by dumprop** [comment]
> I have also experienced this bug on multiple feeds.
> 
> Add a feed "On My Mac" and then try to drag it to "iCloud".
> 
> Some feeds are not able to be dropped into iCloud.

I have same problem on FreshRSS

**Comment by gferreroferri** [comment]
now these feeds work on macOS app but not on iOS app...

**Comment by brentsimmons** [comment]
Is this still a bug?

**Comment by gferreroferri** [comment]
Not anymore
