### ISSUE TITLE
(macOS) same feed of YouTube gets less content on iCloud account

### ISSUE THREAD

**Issue by kevinm6** [Ranchero-Software/NetNewsWire#2749]
<img width="1440" alt="Schermata 2021-01-20 alle 12 56 42" src="https://user-images.githubusercontent.com/72861758/105172012-42eeeb80-5b1f-11eb-962b-04388b8ce3de.png">

**Comment by brentsimmons** [comment]
There may not be anything we can do, but we should check.

**Comment by vincode-io** [comment]
@kevinm6 Could you post the link to your Youtube feed so that I don't have to try and type it in from your screenshot?

**Comment by kevinm6** [comment]
Yes, sure!
Sorry for not doing it already, @vincode-io !
Here it is:

https://www.youtube.com/feeds/videos.xml?channel_id=UChjRM_qQAaOAiLNbOGbYcRA

**Comment by vincode-io** [comment]
It looks like we would have to extend NNW to use [Media RSS](https://en.wikipedia.org/wiki/Media_RSS) for us to get the data out of the Youtube RSS feed.  It looks like Feedbin [supports this](https://feedbin.com/blog/2021/01/21/youtube-embeds/).

**Comment by kevinm6** [comment]
Got it! I'm using Feedly as sync service but I'm going to switch definitely to iCloud account when even iOS version will be available.

**Comment by vincode-io** [comment]
This is basically the same as #2721 so I'm closing it as a duplicate.
