### ISSUE TITLE
Feature request: add all the items of a new feed

### ISSUE THREAD

**Issue by nhoizey** [Ranchero-Software/NetNewsWire#2750]
When I subscribe to a new feed, NetNewsWire sometimes lists only a few of the items from the feed, the most recent it seems.

I get only 4 items from https://blog.imgix.com/feed.xml for example.

It would be nice having all items from the feed, or maybe an option to chose the behavior.

**Comment by vincode-io** [comment]
What kind of account are you using?  If it is a sync account they most likely only carry articles from the last 90 days.

**Comment by nhoizey** [comment]
@vincode-io it is a Feedbin account, so you suggest that Feedbin is limiting the age of articles?

I'll check on their side, thanks.

**Comment by nhoizey** [comment]
Actually, I checked with Feedbin, and they get all items, even olders that are not in the feed anymore, as some of the users subscribed earlier:
https://twitter.com/feedbin/status/1352359436388458496

So I guess it's NetNewsWire that only keeps a few recent?

**Comment by vincode-io** [comment]
NetNewsWire pulls the last 90 days of posts from Feedbin. For high volume feeds like from a news organization, this can mean hundreds of posts. From a low volume one, that can mean only a handful get pulled.

Some people feel like 90 days is too much data and we are using too much local disk space. Some feel like it is too little. We think it is a fair compromise.

**Comment by nhoizey** [comment]
@vincode-io ok, I understand the balance you have to keep, thanks for the details! 👍
