### ISSUE TITLE
Description for iCloud account is cut off

### ISSUE THREAD

**Issue by jeffvautin** [Ranchero-Software/NetNewsWire#2751]
Adding a new 'iCloud' account, but the description is cut off in the UI.

<img width="512" alt="Screen Shot 2021-01-21 at 11 58 31 AM" src="https://user-images.githubusercontent.com/1116443/105384404-2a92d580-5be0-11eb-9985-59b316fd8f40.png">

**Comment by kevinm6** [comment]
I think it’s happening only in macOS Catalina.

<img width="624" alt="Schermata 2021-01-21 alle 18 25 37" src="https://user-images.githubusercontent.com/72861758/105387744-22ee2380-5c16-11eb-9ce0-779749359da6.png">
