### ISSUE TITLE
6.0d4: Hang on quit

### ISSUE THREAD

**Issue by blackketter** [Ranchero-Software/NetNewsWire#2754]
Quitting NNW 6.0d4 hangs with a spinning beach ball. 

Sample attached:
[Sample of NetNewsWire.txt](https://github.com/Ranchero-Software/NetNewsWire/files/5860612/Sample.of.NetNewsWire.txt)

**Comment by blackketter** [comment]
Note: My internet connection may have been in a bad state.  Reconnecting makes quitting work.

**Comment by kevinm6** [comment]
They've already fix it with the new pre-release NNW 6.0d5!
You can find the .zip file in the release section.

**Comment by blackketter** [comment]
So it is!  Thanks.
