### ISSUE TITLE
feed favicon can't be a jpeg?

### ISSUE THREAD

**Issue by jrus** [Ranchero-Software/NetNewsWire#2757]
I am trying to auto-generate some jsonfeed feeds based on users' posts, with their site avatars as favicons. As a test, I added my Github avatar to my feed:

    "favicon": "https://avatars3.githubusercontent.com/u/83411?v=4&s=64"

But it doesn't render, though I would expect any 64x64 pixel square image to work. If I change the "favicon" link to some square png image, that renders fine.

This is kind of an unfortunate limitation, as the user avatars on the site I am trying to autogenerate feeds from are typically jpeg images, often pulled from Github.

**Comment by brentsimmons** [comment]
What’s the URL of the feed?

**Comment by jrus** [comment]
Here is my current test URL: https://endpointservice.web.app/notebooks/@jrus/rsstest/deployments/preview but that is subject to change at any time

**Comment by jrus** [comment]
Hm, that's weird. I am now seeing an icon render. Let me do some more testing.
