### ISSUE TITLE
Incorrect error message when adding to Reader API source (FreshRSS)

### ISSUE THREAD

**Issue by dumprop** [Ranchero-Software/NetNewsWire#2759]
I cannot add the following RSS feed
https://arielkoren.com/blog/feed/
NNW hang out for 20 seconds and gets
![image](https://user-images.githubusercontent.com/34004367/105628420-dee56380-5e4d-11eb-95e0-c4cf19c04bea.png)
in fact it isn't
Same situation on
https://deniable.org/index.xml (but no 20 seconds timeout)
https://xlab.tencent.com/en/atom.xml
Successfully added to iCloud

FreshRSS logs:
2021-01-24 12:17:45
Unknown error for feed [https://xlab.tencent.com/en/atom.xml]
2021-01-24 12:17:20
Unknown error for feed [https://deniable.org/index.xml]
2021-01-24 12:16:21
Invalid action name for controller FreshRSS_index_Controller
2021-01-24 12:16:12
Invalid action name for controller FreshRSS_index_Controller
2021-01-24 12:16:08
Unknown error for feed [https://arielkoren.com/blog/feed/]
2021-01-24 12:16:03
Invalid action name for controller FreshRSS_subscription_Controller

So, looks like problem on FreshRSS side, but NNW returned that feed was added

**Comment by vincode-io** [comment]
Is this a bug related to iCloud or FreshRSS?  You seem to reference both.

**Comment by dumprop** [comment]
> Is this a bug related to iCloud or FreshRSS? You seem to reference both.

Bug related to FreshRSS, on iCloud all are ok. There no handling FreshRSS errors

**Comment by vincode-io** [comment]
https://deniable.org/index.xml has a certificate error.  That is probably why you couldn't subscribe to it.  We do correctly handle the error returned by FreshRSS.

<img width="1302" alt="Screen Shot 2021-01-24 at 12 06 53 PM" src="https://user-images.githubusercontent.com/16448027/105639241-adb06780-5e3c-11eb-81bb-efe76a26da0f.png">

I'm not having any problems with the other two feeds.  You can see them in the screenshot.  As mentioned in the FreshRSS issue, please make sure you are using a current version of FreshRSS.

**Comment by dumprop** [comment]
Yes, there only manual adding on FreshRSS without ssl verification (or disabling it)
There was problem w/ certificates on server side, fixed,thanks
Does https://pinkysplanet.net/rss/ parsed correct too?

**Comment by vincode-io** [comment]
That one fails for me with an incorrect error.  I'll reopen this ticket and investigate.

**Comment by vincode-io** [comment]
@dumprop You won't get the already subscribed message anymore.  You'll instead get a message that states that the feed couldn't be found.  The Google Reader API doesn't give us any more information than it didn't work.
