### ISSUE TITLE
Close notifications in NNW 6

### ISSUE THREAD

**Issue by LitoFrame** [Ranchero-Software/NetNewsWire#2760]
In the notifications system setting I have alerts for NNW. When I try to close the notification, it opens the related article in NNW 6. In NNW 5 when I closed a notification it didn't do that.
NNW 6.0d5, macOS Big Sur

**Comment by vincode-io** [comment]
We don't program any of the UI for the Notification dialogs. That is part of the macOS system itself and changed in Big Sur.  

Unfortunately in Big Sur it is more difficult to close the dialogs and people instead are opening the applications instead. Be sure to be clicking on the small "X" in the top left corner to dismiss the dialog.

**Comment by LitoFrame** [comment]
I clicked the small "X" and it always opened the app. I had no problem with NNW 5 on Big Sur...

**Comment by vincode-io** [comment]
I apologize for the misunderstanding.  

This bug will be fixed and in the next text version of NNW 6.

**Comment by LitoFrame** [comment]
no problem, thank you!
