### ISSUE TITLE
Sync with Inoreader 6.0d5

### ISSUE THREAD

**Issue by greggvm** [Ranchero-Software/NetNewsWire#2762]
Inoreader Tags are being imported/synced(?) when first connecting. As are Saved items as well. Saved items seem to be spot on. Subscriptions are also looking good. Unread count syncs with the web Inoreader count. But the Tags are an issue. They are included under the Inoreader heading in the subscription list but they are empty. In Inoreader they are a separate heading/item and are fully populated with items that had been tagged. I've attached two screenshots, one of NNW and one of Inoreader web interface.
![Screen Shot 2021-01-24 at 12 44 30 PM](https://user-images.githubusercontent.com/54709026/105638939-81e4b000-5e43-11eb-88e7-a96666893028.png)
![Screen Shot 2021-01-24 at 12 55 42 PM](https://user-images.githubusercontent.com/54709026/105638941-84470a00-5e43-11eb-8874-42bbbea60865.png)

**Comment by vincode-io** [comment]
Thanks for the bug report.  Unfortunately NNW doesn't support article tagging yet.  I'll make sure that the tags don't show up as folders any longer in the next test release.

**Comment by greggvm** [comment]
Yes, I wasn't expecting Tag support :) The Tag items not showing up is exactly how I would expect it to work. Thanks!
