### ISSUE TITLE
freshrss on iOS version available?

### ISSUE THREAD

**Issue by ksurl** [Ranchero-Software/NetNewsWire#2763]
is freshrss support still in testing only? I don't see it as an option on the iOS app for adding an account

**Comment by vincode-io** [comment]
We will be releasing a test version to TestFlight after we have the Mac version more stable.  This test version will support FreshRSS.

**Comment by bingoxo** [comment]
Any update on this :) ?

**Comment by ksurl** [comment]
the 6.0 mac version stable just released. probably will be coming soon. how do you get into testflight build for nnw?

**Comment by vincode-io** [comment]
We'll announce when we open up TestFlight testing for the iOS app again.
