### ISSUE TITLE
Copying feeds from Mac to iCloud updates

### ISSUE THREAD

**Issue by deverman** [Ranchero-Software/NetNewsWire#2764]
Hi I started copying feeds from local "Mac" to iCloud after upgrading to 6.0d5.

I copied one folder over and it and the list did not update right away after copying. I had to scroll up and scroll down.

Later I dragged another folder to iCloud and while it was copying I dragged a single feed to iCloud.

The previous folder seemed to stop copying. I switched apps and went back and then the progress bar for copying was gone but the folder I copied did not show up in iCloud. 

Only after I deleted the individual feed on the "Mac" did the folder disappear from Mac and show up on the iCloud.

Later on I copied a folder and it did move it and update the list immediately.

Then later trying to drag a single feed onto a folder from Mac to iCloud some of the folders would highlight but others would not. 

Dragging the single feed to iCloud moved it but then trying to drag that feed onto a folder some would take it and some would not.

BTW, before updating from 5.1 to 6.0 I marked everything as read. When Iaunched 6.0 there was about 2K items unread when there should have been zero.

Thanks for adding iCloud syncing it was my number 1 feature request.

**Comment by vincode-io** [comment]
I changed it so that the folder copy can't inadvertently clear the progress bar to make it more obvious that copies were still happening.

**Comment by deverman** [comment]
Thanks
