### ISSUE TITLE
Custom Text Brightness or Custom Text Color?

### ISSUE THREAD

**Issue by bibijaan** [Ranchero-Software/NetNewsWire#2766]
Hey!

Is this possible to have custom brightness for body text?
Or probably straight custom color option for body text? (and/or background color too?)

![image](https://user-images.githubusercontent.com/72033357/106019027-5f28f480-60ec-11eb-8aa1-18c7fcbcb93e.png)

Thanks

**Comment by vincode-io** [comment]
It isn't possible yet, but we do plan to implement it.  Duplicate of #19.

**Comment by bibijaan** [comment]
That issue was opened in "30 May 2017" : (

I hope this will be done quickly : )

Thanks anyway
