### ISSUE TITLE
Auto-refresh is not working

### ISSUE THREAD

**Issue by rex4539** [Ranchero-Software/NetNewsWire#2767]
NNW 6.0d5

Steps:
1. Preferences -> General -> Refresh feeds -> Every 10 minutes
2. Wait 10 minutes.

What happened:
Auto-refresh does not occur.

Expected refresh:
Auto-refresh occurs.

Notes:
I only have iCloud account active. Manual refresh works fine.

**Comment by vincode-io** [comment]
@rex4539 Are you saying that NNW never refreshes for you?

**Comment by vincode-io** [comment]
@kevinm6 Are you experiencing the same thing? If so any details about how you got into that state would be useful.

**Comment by rex4539** [comment]
I seems to be a hit and miss. Mostly miss.

I am subscribed to hundreds of feeds (a couple dozen are Nitter RSS feeds) so it is very common that I should have at least a few new articles every 10 minutes.

I usually find myself in a situation where I don't have any new article for hours. Then I refresh manually and I see 50-60 articles pop up.

**Comment by kevinm6** [comment]
> @kevinm6 Are you experiencing the same thing? If so any details about how you got into that state would be useful.

Yes @vincode-io!
I really don't know how I got into, because if I remember well the day when I downloaded and install NNW 6.0d5 it was working as expected, but not from the day after.
I didn't change settings for the refresh, it still automatic on every 2hrs.

**Comment by vincode-io** [comment]
Do either of you guys have the debug menu enabled?

**Comment by rex4539** [comment]
I don't.

**Comment by vincode-io** [comment]
Do me a favor.  Subscribe to this feed and let me know if it is refreshing regularly or not. It is an extremely high volume feed and you should get new articles every time you refresh.

https://www.flickr.com/services/feeds/photos_public.gne

**Comment by kevinm6** [comment]
@vincode-io It seems to be working as expected, I change to 10’, subscribe to that feed, close and reopen the app.
Thank you. (For me the issue is closed)

**Comment by vincode-io** [comment]
@rex4539 Did you have any luck testing refresh using that feed I provided?

**Comment by rex4539** [comment]
Sorry, I don't have time to test.
