### ISSUE TITLE
Feature request (mainly iOS): manage feeds

### ISSUE THREAD

**Issue by kevinm6** [Ranchero-Software/NetNewsWire#2768]
Is there any chance to see a way to manage differently all the web feeds I'm subscribed to?
I'll explain better: on iOS especially, it's hard manage more feeds one after another one (because requires more taps and gestures); on macOS It's possible to just show the Inspector and move between feeds with the arrows.
I was thinking like "Settings" app of iOS where you can find various info of an app going into the section where all the app installed are shown.
Another way could be a "edit mode" of the table view in the "Feeds controller" that shows the (i) button to show the info.

**Comment by vincode-io** [comment]
In version 6 on iOS you will be able to tap the feed icon to enter the feed settings.  I think that is what you asked for in your last sentence.

**Comment by vincode-io** [comment]
If it wasn't we'll reopen this issue and discuss more.

**Comment by kevinm6** [comment]
Perfect!
I'm ready for the Test Flight build!
