### ISSUE TITLE
Add Multireddit option to Reddit extension

### ISSUE THREAD

**Issue by gracjankn** [Ranchero-Software/NetNewsWire#2770]
The Reddit extension currently supports adding four types of feeds: Home, Popular, All and Subreddit.

It'd be helpful to also have a Multireddit option. This way the user doesn't need to add all subreddits individually and if they add more subreddits to the multireddit using the Reddit app/website, it's also reflected in the RSS feed without additional action.

**Comment by distrob** [comment]
+1 I'm also missing that feature.
