### ISSUE TITLE
Reader view problem?

### ISSUE THREAD

**Issue by LitoFrame** [Ranchero-Software/NetNewsWire#2771]
First of all, I'm not sure that the problem is with NNW 6 or with something else. I used NNW 5 for a couple of month, but I never found this issue. Now I see this problem once in every 1-3 days.
Most of my feeds I use "Always use reader view". Sometimes when I try to read a new article it didn't load, I can see "loading..." in the browser area and a "!" sign in the reader view icon. When I switch off the "Always use reader view" the article loads fine. Sometimes I switch off and on "Always use reader view" and the article load fine, sometimes I have to restart NNW 6, sometimes I have to wait 2-5 minutes to "solve" the problem. 
During this issue I can load other articles in the same feed or other feeds, so I don't have internet issue. I can double click to the article and open the website, so the article is exists.
Today when I found this issue and checked the website, I found 1 article (the latest one) which wasn't in NNW at all, but the article creation time was 5-6 hours earlier. I did a manually refresh, but it doesn't help. I restarted NNW without success. After a couple of minutes everything was fine, the latest article was in NNW and loaded in Reader view perfectly.
NNW 6.0d5, macOS Big Sur

**Comment by vincode-io** [comment]
The web service we use for Reader View has been having problems recently.  There really isn't anything we can do about it right now except wait for the service to come back when it goes out.
