### ISSUE TITLE
Slow refresh The Old Reader Account

### ISSUE THREAD

**Issue by aconachey** [Ranchero-Software/NetNewsWire#2772]
NNW 6.0d5 refresh time for a The Old Reader account is slow, refresh takes several minutes.

**Comment by vincode-io** [comment]
I just tried it and it completed in seconds for me.

How many feeds do you have?  Is it always slow or does it vary?

**Comment by aconachey** [comment]
I have 151 feeds. It's always slow for me.

**Comment by vincode-io** [comment]
Have you synced using another RSS reader before?  If so how does NNW compare?

If you feel comfortable sharing you OPML file with me, I can take a look and see how much data is being transferred. You can send it to mo@vincode.io.

**Comment by aconachey** [comment]
I've been using FeeddlerPro on iOS for the past 8-9 years. It synches
almost instantly.

Last time I used a desktop RSS reader was NNW back when Google Reader was
available.

I will send my OPML file under separate cover.

**Comment by vincode-io** [comment]
Thanks. Is it possible that you have a really high unread count number?  I'm just trying to figure out where the bottleneck is in the syncing process.

**Comment by aconachey** [comment]
My unread count is around 101,500 now.

Op ma 1 feb. 2021 om 12:17 schreef Maurice Parker <notifications@github.com>

**Comment by vincode-io** [comment]
Does your FeeddlerPro unread count match The Old Reader count?

**Comment by aconachey** [comment]
Yes, it does.

Op ma 1 feb. 2021 om 13:27 schreef Maurice Parker <notifications@github.com>

**Comment by vincode-io** [comment]
I did some research on this today and FeeddlerPro isn't actually doing any syncing.  It downloads you list of feeds and unread counts to display.  Only when you select a feed does it download the article for you to view.

NetNewsWire syncs with The Old Reader and always has your articles available on your computer. That is how we provide things like fast searching of articles.

Unfortunately the web services that The Old Reader provides doesn't allow us to only get the newest unread articles for your account.  We have to ask for all the unread articles for a user.  In this case, this over 100k in articles.  That takes network bandwidth and time to download.

My recommendation is to use The Old Reader's web interface to mark very old articles as read.  If you mark everything older than 1 month as read, you should see good syncing performance from NetNewsWire.

<img width="463" alt="Screen Shot 2021-02-01 at 4 40 17 PM" src="https://user-images.githubusercontent.com/16448027/106527164-75e49800-64ac-11eb-9dac-c9a20d857975.png">
