### ISSUE TITLE
iOS 13.7 — Crash when viewing articles

### ISSUE THREAD

**Issue by stuartbreckenridge** [Ranchero-Software/NetNewsWire#2773]
To recreate: 
- build and run the  current commit on `main` (55a9004) on an iOS 13.7 simulator with Xcode 12.4
- Navigate from the MasterTimelineViewController to the article list to an article

`PreloadedWebView` will crash during `init` here: 

```swift
let preferences = WKPreferences() // Thread 1: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
```

 It's not specific to any particular article and it's not reproducible on an iOS 14.x simulator.

**Comment by vincode-io** [comment]
Do you think there is something wrong with your simulator?  I can't recreate the problem.

<img width="487" alt="Screen Shot 2021-01-31 at 3 00 16 PM" src="https://user-images.githubusercontent.com/16448027/106397871-4ca50880-63d5-11eb-8156-1c3e3ec6375a.png">

**Comment by stuartbreckenridge** [comment]
I don't know. This happens on a fresh build on a fresh simulator.

**Comment by vincode-io** [comment]
This is a long shot, but are you using an M1 Mac?

**Comment by stuartbreckenridge** [comment]
This happened on an M1. I haven't retested on an Intel Mac yet.

**Comment by vincode-io** [comment]
I suspect that the older iOS SDK doesn't work well with the out of process WKWebView on M1 Macs.  You could be seeing a Rosetta bug or incompatibility.

**Comment by stuartbreckenridge** [comment]
Possibly. I will try again on Intel tonight and if it works, I'll close this.

**Comment by vincode-io** [comment]
According to the release notes for Xcode 12.5 this is a known issue with WKWebView, the simulator, and Apple Silicone.

https://developer.apple.com/documentation/xcode-release-notes/xcode-12_5-beta-release-notes/
