### ISSUE TITLE
Podcast support

### ISSUE THREAD

**Issue by xplosionmind** [Ranchero-Software/NetNewsWire#2780]
As of version 5.1.3, RSS feeds of podcasts do not display any playable content. is this my problem, therefore it is a bug, or it can be considered a feature request?

**Comment by brentsimmons** [comment]
NetNewsWire is not a podcast player.

Yes, some podcast feeds do provide some web UI to play the podcast, which then appears in NetNewsWire. That’s fine. But we have no interest in adding additional support for podcasts — that’s best left for podcast players.

**Comment by schackbrian2012** [comment]
For some historical perspective, the original NetNewsWire did support podcasts:

> Version 1.0 was released on February 11, 2003, and version 2.0 was released in May 2005. At that time it included custom feed views, custom **downloading and opening of podcasts**, synchronization of feeds and feed status between computers, Bloglines support, and a built-in tabbed browser.

https://en.wikipedia.org/wiki/NetNewsWire#History

**Comment by brentsimmons** [comment]
True! But I still want to keep NetNewsWire focused on reading, and leave podcast playing to dedicated podcasting apps.

**Comment by NoahTheDuke** [comment]
Would it be acceptable to show the mp3 link? For example, A Life Well Wasted's rss ([here](https://alifewellwasted.com/episodes/episodes.xml)) has `<enclosure url="https://traffic.libsyn.com/alifewellwasted/Ep_9_Final.mp3" length="155472939" type="audio/mpeg"/>` which is not visible anywhere in the article page. I'd love for there to be a little `"View enclosure: [Ep_9_Final.mp3](https://traffic.libsyn.com/alifewellwasted/Ep_9_Final.mp3) [audio/mpeg]"` button at the bottom of the article page, so I can download it manually and listen on my computer.
