### ISSUE TITLE
NNW 6: Main Thread Checker Warnings on iPad

### ISSUE THREAD

**Issue by stuartbreckenridge** [Ranchero-Software/NetNewsWire#2781]
<img width="297" alt="Screenshot 2021-02-05 at 06 23 45" src="https://user-images.githubusercontent.com/7046652/106963071-0526cf80-677b-11eb-802f-d12f4326098d.png">

**Comment by vincode-io** [comment]
@stuartbreckenridge Do you have any steps that you used to get this to happen?  I'm not having any luck getting the Main Thread Checker to find anything on my iPad.

**Comment by stuartbreckenridge** [comment]
Nothing specific. It happens just after launch on iPad Pro (physical device) but not on simulator.

**Comment by vincode-io** [comment]
What version of iOS is on your iPad?

**Comment by stuartbreckenridge** [comment]
14.4.

**Comment by vincode-io** [comment]
@stuartbreckenridge Can you figure out how this is happening? I can't recreate it. I'm willing to make the code changes if we can identify the root problem.
