### ISSUE TITLE
macOS NNW 6.0a1 - strange position of setting tabs

### ISSUE THREAD

**Issue by kevinm6** [Ranchero-Software/NetNewsWire#2782]
I just update NNW to the new alpha version (NNW 6.a1) and I’ve just noticed that in settings, the tabs are in a weird position.
Is this intended?

<img width="954" alt="Schermata 2021-02-05 alle 09 04 20" src="https://user-images.githubusercontent.com/72861758/107006656-c4868080-6791-11eb-896c-b211b77019ef.png">

**Comment by dumprop** [comment]
Same, looks like yes
