### ISSUE TITLE
Mac doesn't pick up read changes from iPhone for existing articles

### ISSUE THREAD

**Issue by billvinson** [Ranchero-Software/NetNewsWire#2785]
iPhone (iOS 14.4) 5.0.5
MacBook Air M1 (macOS 11.2) 6.0a1
Using Feedbin

This may just be a feature difference between platform versions...

If I'm reading feeds on my Mac and I leave it open and running and then for a period of time (greater than refresh time on the Mac) switch to reading on my iPhone, the Mac never picks up those changes with regard to what has been read. It doesn't matter if I refresh on either device, once the articles have been noticed on the Mac as unread, reading on the iPhone never leads to an existing known article on the Mac being marked as read. The iOS version has a "refresh to clear read articles" and I don't believe that option changes this behavior (same option is not on the Mac).

I don't believe the developer/alpha versions I have been running on the Mac influence this, as I think it has been working this way for a while, but I finally thought to bring it up.

**Comment by stuartbreckenridge** [comment]
I have tried to recreate this using the same setup, but not successfully. 

If I assume Feed `X` has 0 unread articles on both iPhone and Mac:
- When marking an article as unread on the iPhone, it will only show up as unread on the Mac once the iPhone NetNewsWire has been manually refreshed or put into the background, and then the Mac NetNewsWire is refreshed;
- When marking an article as unread on the Mac, it will only show up as unread on the iPhone once the Mac NetNewsWire has been manually refreshed or is refreshed automatically on the refresh schedule, and then the iPhone NetNewsWire is refreshed;
- If I mark an article as unread and don't allow for a refresh (either manual, placing into the background, or on schedule), Feedbin is not made aware of the changes, and the apps remain out of sync. 

This behaviour works with > 0 unread articles as well. 
- Marking _unread_ article `Y` as read on the Mac is only propagated to the iPhone once a refresh is completed;
- Marking _unread_ article `Z` as read on the iPhone is only propagated to the Mac once a refresh is completed

**Comment by billvinson** [comment]
Interesting. This morning I woke up to 50 or so articles on the iPhone. Read through them all and refreshed. Nothing unread. Sat down at the Mac and it showed now 62 articles unread it was the same articles with a hand full of truly new ones that came in. Refreshing the Mac did not update the existing already read on iPhone articles.

From my viewpoint, it appears that once the Mac refreshes and finds an unread article, further refreshes don't update it to be read, it just sticks around as unread. It seems to happen to me at least daily (reading on iPhone before sleep and then early in the AM before i make it to my desk).

**Comment by billvinson** [comment]
I'll keep trying to nail down a more concrete recreation scenario.

**Comment by billvinson** [comment]
just did some testing. refreshed both and had 6 unread articles across 5 feeds. Read all on iPhone, refreshed twice (for good measure). Refreshed Mac and they were all marked read. So, it is working. What I'm seeing makes me think there's either a weird time component or some other bug causing the specific behavior as you're right, in at least the short time period, everything works as it should.

**Comment by stuartbreckenridge** [comment]
On backgrounding, it _does_ do a status sync update. The only time it may not complete is if it doesn't have enough time, which is at the behest of the iOS Overlord. :-)

**Comment by billvinson** [comment]
Okay, checked and confirmed that that works on my end. Wow, I can't explain what I was seeing and the testing certainly points to some other oddness going on. I know I refreshed the Mac this morning multiple times to try to get the articles to show as read and restarted the app just in case. I'll keep a watch on it, but I can't explain it at this point and it doesn't seem to be this issue, so probably best to close this.

**Comment by stuartbreckenridge** [comment]
No worries.

**Comment by billvinson** [comment]
Small update here. I'm not going to report until I can find more concrete information, but what I'm seeing is after leaving the Mac app open all night, reading on the iPhone in the morning (refreshing and backgrounding) and then refreshing the Mac, the articles appear unread for a little while. Multiple manual refreshes and quitting/restarting the app does nothing to bring it in sync, but if you wait, 10-15 mins, the proper read status is reflected in the Mac. Not sure why the manual refreshes aren't causing that to happen when done.

**Comment by stuartbreckenridge** [comment]
@benubois is there a delay in syncing statuses from the Feedbin side of things?

**Comment by billvinson** [comment]
From my view, I checked Feedbin and it matched my iPhone, as far as read status goes. So far, the outlier seems to be just the Mac app, but I know this is still just imprecise recreate steps...

**Comment by benubois** [comment]
@stuartbreckenridge,

This sounds related to #2715 and I'm looking into it there. There shouldn't be any delay. Maurice suspects an HTTP caching issue so that's what I'm looking at now.

Thanks!
