### ISSUE TITLE
Safari extension doesn't always recognize feed

### ISSUE THREAD

**Issue by rex4539** [Ranchero-Software/NetNewsWire#2789]
I have seen multiple cases where the Safari extension doesn't recognize the feed but when I do it manually within the app, then the feed is found.

Check the following link as an example -> https://www.nativedsd.com/blog/

**Comment by brentsimmons** [comment]
NetNewsWire itself goes to great lengths to find feeds. In the case where the page does not declare the feed in the normal way, the Safari extension won’t see it.

We could have the extension go to the same lengths NetNewsWire does — but it would be doing this for just about every page you ever open, and it would be a performance and bandwidth hit.
