### ISSUE TITLE
macOS Fullscreen: Keyboard Shortcuts to Switch Views and Refresh Make Search Field Active

### ISSUE THREAD

**Issue by alexclst** [Ranchero-Software/NetNewsWire#2791]
I use NNW in fullscreen mode on my Mac. I also tend to use the keyboard shortcuts to switch between the **Today**, **All Unread**, and then **Refresh** commands when I get through everything that is the **All Unread** view. This is all done with the sidebar hidden from view. Ever since I started using the 6.0 development version this sequence has ended in the search field in the toolbar activating. In fullscreen, this in turn makes the toolbar visible. The below screen recording captures this behavior. I'm not sure if the bug here is exactly that the search field is made active after this sequence, or indeed that the toolbar is ever hidden, frankly. This may also be the intended behavior. But it feels a bit strange to me, so I guess I wanted to bring it up.

https://user-images.githubusercontent.com/2946567/107126076-54e8c200-6873-11eb-9819-50565cf575df.mov

**Comment by brentsimmons** [comment]
What keyboard shortcuts exactly are you using to navigate?

**Comment by alexclst** [comment]
Command-1, Command-2, Command-R. Starting on the **All Unread** view. Going to the **Today** view. Then back to**All Unread**. Then **Refresh** from the File menu.

**Comment by vincode-io** [comment]
@alexclst Are you able to recreate this on the latest A2 NetNewsWire release? If so, which version of Big Sur are you using?

**Comment by alexclst** [comment]
Yes, this still happens on the latest A2 release. I'm using Big Sur 11.2 (20D64) on an M1 Mac mini.

**Comment by vincode-io** [comment]
I am having zero luck getting the toolbar to hide like in the video.  Do you by any chance have any software running that helps you organize or size your windows?  Do you have any special accessibility settings enabled?

**Comment by alexclst** [comment]
I have no accessibility features enabled. Nor do I have tools to organize or size windows.

Actually, with further exploring just now, it seems that the toolbar is not staying visible only when the app launches to a normal window over a desktop (say, after a restart and I first launch NNW) and then I drag it to any fullscreen space. It is in this workflow that the toolbar disappears. If I then drag NNW back out of fullscreen and immediately back to fullscreen the toolbar sticks around. Hence, steps to reproduce seem to be:

1. Quit NNW if open
2. Launch NNW, if fullscreen toolbar is gone, if windowed toolbar seems to go away once put in fullscreen
3. Take NNW out of fullscreen
4. Put NNW back in fullscreen and the toolbar now stays around

**Comment by alexclst** [comment]
I just tested this on an Intel MacBook. Can't seem to reproduce the problem there. But now I seem to notice that the problem also doesn't appear on my desktop, every time or two. That is, quit and launch 1 it launches to fullscreen but no toolbar. Immediately quit and launch a 2nd time and it launches to a window, but with the toolbar sticking around when put in fullscreen. So, a bit more complex than I thought half an hour ago. To me this is starting to feel like it could easily be an OS bug... But, apps with a similar basic design (I tried Notes) don't exhibit the same behavior. So I don't really know.

**Comment by vincode-io** [comment]
Thanks for hanging in there.  I've tried everything to recreate this and just can't make it happen on my Intel MacBook.  Maybe someone with an Apple Silicon Mac could try?

**Comment by alexclst** [comment]
Since I run a bunch of stuff on my Mac, just none that should mess with windows, I just tried NNW in a different user on my M1 Mac. I see the exact same results when I'm in a user account with essentially just Finder and NNW running. I am, though, also seeing it in a similarly bare user account on an Intel Mac running macOS 11.2. So I guess that my testing on Intel yesterday was somewhat flawed, sorry... Although, seeing it on Intel makes it seem even stranger that you did not see it, @vincode-io. I'm baffled as to what is going on here. But if the intention is to have NNW always show the toolbar then it does seem like something is going wrong. The question is just where, NNW or macOS.

**Comment by alexclst** [comment]
Just FYI, though to be expected I'd think, the issue is still present under macOS 11.2.1.

**Comment by banaslee** [comment]
If testing on another M1 Mac is still relevant, I did and I was able to reproduce it.

Built from commit b47a1fac and running MacOS 11.3 Beta (20E5172i).

Same thing as @alexclst described: the toolbar is hidden during the first run only.

**Comment by vincode-io** [comment]
I was finally able to recreate this. Turns out it only happens when you have "Close windows when quitting an app" selected in the System Preferences. We'll have a fix in our next build.

**Comment by alexclst** [comment]
Good to hear you found a fix. But I have that setting unchecked on my Mac. So, doesn't that mean it isn't 100% related just to behavior when that setting is selected?
<img width="780" alt="Screenshot 2021-02-15 at 8 15 58 PM" src="https://user-images.githubusercontent.com/2946567/108010582-d0144b80-6fca-11eb-9438-04930d2faf57.png">

**Comment by vincode-io** [comment]
The fix itself isn't related to the setting, so we should be okay.

**Comment by alexclst** [comment]
@vincode-io, I just updated to 6.0a3 and after going to full screen and switching views then refreshing the feeds, the toolbar went away again. After going out and back in to full screen all is right again. So, it feels as if the fix described above didn't get in this build? Or was it supposed to be fixed in this build?

**Comment by vincode-io** [comment]
Sorry about that @alexclst. The fix was done on the wrong branch. It will be in the next test release.
