### ISSUE TITLE
Facebook Extension

### ISSUE THREAD

**Issue by zgosalvez** [Ranchero-Software/NetNewsWire#2792]
Glad to finally have the Twitter and Reddit extensions! 🚀 

Any plans on supporting Facebook, at least for Pages? Some smaller establishments only post updates on Facebook.

**Comment by brentsimmons** [comment]
I can see how it would be useful — but we won’t support Facebook even in this small way.

**Comment by Wseries** [comment]
Does this mean an extension for Instagram would be out of the question too?
