### ISSUE TITLE
Issues with lay-out cancel button

### ISSUE THREAD

**Issue by Jckpst** [Ranchero-Software/NetNewsWire#2794]
The word cancel is truncated in the cancel button of several of the accounts windows in the preferences - see screen shot.

jack
![CleanShot 2021-02-07 at 11 00 57@2x](https://user-images.githubusercontent.com/78682983/107143498-ab1e3980-6935-11eb-80bc-fc5719ae2aa2.jpg)

**Comment by stuartbreckenridge** [comment]
Are you running Catalina or Big Sur?

**Comment by Jckpst** [comment]
Catalina

jack
