### ISSUE TITLE
NNW 6.0a2: Sync set to manual only is not working

### ISSUE THREAD

**Issue by Thomas-U** [Ranchero-Software/NetNewsWire#2796]
NNW starts syncing immediately after start.

It also syncs instantly after a folder in iCloud account is deleted.

NNW 6.0a2, macOS 11.3 beta 1, M1

**Comment by brentsimmons** [comment]
Refreshing on start is by design. But it shouldn’t pull in new articles after deleting a folder.

**Comment by vincode-io** [comment]
We don't pull in new articles when deleting folders.  We show the progress indicator when doing network access like deleting items.  This can take some time as we have to delete the articles associated with the feed.
