### ISSUE TITLE
iOS: UIMenu very slow with 3D Touch

### ISSUE THREAD

**Issue by kevinm6** [Ranchero-Software/NetNewsWire#2798]
Could it be possible to disable the 3D Touch feature and leave just the long press, because the menu is very slow when calling it from 3D Touch, is a little bit faster with just long press.

I loved 3D Touch but now it's gone with the new devices, so I give up!

Here's a little screen record!
https://user-images.githubusercontent.com/72861758/107276556-7d2f1700-6a53-11eb-968c-2c31bd9b595c.mp4

**Comment by vincode-io** [comment]
Does disabling 3D touch it system wide make the menu appear faster?

https://www.howtogeek.com/400337/how-to-enable-or-disable-3d-touch-on-an-iphone/

**Comment by kevinm6** [comment]
With 3D Touch disabled it's the same!
It changes when 3D Touch is enabled and I try with 3DT and long press (is faster with long press)! 

I think could be a conflict between the calls of UIGestureRecognizer

**Comment by vincode-io** [comment]
We changed how we generate the menu in version 6 so that it works faster now.  I'm going to close this issue, but if you still find it slow after we start testing NNW 6, we can reopen it.

**Comment by kevinm6** [comment]
Okay @vincode-io, thank you so much!
I'll let you know if I'll find this in the first test builds.

**Comment by kevinm6** [comment]
@vincode-io I don't know if It could help but I've just noticed that this happens only if the UIMenu has to show even "Mark All as Read in…" (so if the folder or web feed has unread articles), otherwise is fast as expected.
