### ISSUE TITLE
Add vk.com feed provider (extension)

### ISSUE THREAD

**Issue by dumprop** [Ranchero-Software/NetNewsWire#2799]
I like twitter timeline (extension), but I need something like that for vk.com too

Something like that implemented as php script - https://github.com/woxcab/vkrss

But would be nice to have the ability to use it without any script, just out of the box as twitter

**Comment by brentsimmons** [comment]
We won’t be adding any feed provider extensions. Hopefully vk.com provides RSS feeds (or will in the future).
