### ISSUE TITLE
Add instagram.com feed provider (extension)

### ISSUE THREAD

**Issue by dumprop** [Ranchero-Software/NetNewsWire#2801]
I like twitter timeline (extension), but I need something like that for instagram.com too

RSSHub / rss-bridge have some issues (also w/ log in and timeline generating)

Would be nice to have instagram extension, out of the box as twitter

**Comment by brentsimmons** [comment]
I can totally see how that would be useful, but we won’t support Facebook, even in this way.

**Comment by dumprop** [comment]
Why?

**Comment by brentsimmons** [comment]
I believe that Facebook is harming democracy and has incited genocide. I will not integrate any Facebook code or services into the app.

**Comment by dumprop** [comment]
Me too, but using this extension would reduce the use of this service, as well as deprive them of revenue because will not view ads and any telemetry 
So, that is the reason (rn they get money because I am forced to watch their ads and to participate in collecting telemetry)
Only RSS feed can help w/ that

**Comment by murkomarko** [comment]
> I believe that Facebook is harming democracy and has incited genocide. I will not integrate any Facebook code or services into the app.

having support to it would harm Meta more than do any good to it
