### ISSUE TITLE
Stalled refresh

### ISSUE THREAD

**Issue by dumprop** [Ranchero-Software/NetNewsWire#2805]
I have ~500 feeds on FreshRSS and 5 on iCloud and NNW always stall on "8 of 9"
<img width="94" alt="image" src="https://user-images.githubusercontent.com/34004367/107609734-c2ac3980-6c37-11eb-8905-89e22ab25b2f.png">
Some feeds are updated, some not 
How to debug that?

**Comment by vincode-io** [comment]
Try testing with only one account enabled at a time.

**Comment by rex4539** [comment]
I'm also seeing this intermittently with just iCloud account enabled.

**Comment by dumprop** [comment]
When I drag-n-drop from iCloud to my mac -> it stuck for a few minutes
<img width="255" alt="image" src="https://user-images.githubusercontent.com/34004367/107859255-15504600-6e30-11eb-8db3-b98eb77c8579.png">
After that it stuck on that
<img width="255" alt="image" src="https://user-images.githubusercontent.com/34004367/107859264-39ac2280-6e30-11eb-81b9-ad6a25e8f1b6.png">

But after some time finally it disappeared (but feeds still in iCloud!), when i try it again

<img width="244" alt="image" src="https://user-images.githubusercontent.com/34004367/107860587-ea69f000-6e37-11eb-9f7c-d49df5aeea6e.png">

But after restarting NNW I found that it moved to my mac, but without moving data (so old posts are lost and now all posts are unread!)

After that in stuck on that for 10-20 seconds
<img width="243" alt="image" src="https://user-images.githubusercontent.com/34004367/107860781-3b2e1880-6e39-11eb-8449-cff37cd22df5.png">

But finally updated feed data :) But unfortunately old data was lost due to migration :(

**Comment by vincode-io** [comment]
What old data was lost?

**Comment by dumprop** [comment]
It looks like it just added feeds to mac and downloaded data (there no old posts/read status)
So, now I have only latest posts of twitter timeline and all of them are unread (but it isnt)

After restarting NNW there no any stuck on refreshing (5 seconds on NNW and 2 seconds on Vienna)

**Comment by vincode-io** [comment]
We don't copy read statuses or starred statuses when dragging between accounts. It isn't feasible because different sync services identify articles using different identifiers.

**Comment by dumprop** [comment]
But maybe some local cache for old posts?

And that was local mac, so NNW can select any identifiers

**Comment by dumprop** [comment]
<img width="341" alt="image" src="https://user-images.githubusercontent.com/34004367/107887338-56faf280-6efd-11eb-95be-c65bf3b0a5e4.png">
Probably the reason it that no free space on iCloud, but I'm not sure, only a tip

**Comment by vincode-io** [comment]
@dumprop Could you translate that to English for me?

**Comment by dumprop** [comment]
> @dumprop Could you translate that to English for me?

There no free space on iCloud
So, probably it stuck when there no free space, but Im not sure, its only a tip (a test case)

**Comment by dumprop** [comment]
@rex4539 do you have free space on icloud?

**Comment by rex4539** [comment]
Plenty. It's unrelated.

**Comment by dumprop** [comment]
Currently, all are ok
It stuck on "6 of 9" for 20 seconds, but the reason is that a few feeds banned my ip (tested w/ other ip and all are fast enough*)
*8s in NNW and 5s in Vienna

**Comment by brentsimmons** [comment]
Any remaining issue here is probably not something in our control — slow servers, network congestion, that kind of thing. So I’m closing it. We can revisit if this comes up again.
