### ISSUE TITLE
Add author to search results listing

### ISSUE THREAD

**Issue by banaslee** [Ranchero-Software/NetNewsWire#2807]
Now that users can search for author, it would be good to display that piece of information on the search result listing. That way a user can better understand the relevance of the result for their search. See screenshot to see how it looks like now.

![Simulator Screen Shot - iPhone 12 mini - 2021-02-12 at 00 47 49](https://user-images.githubusercontent.com/829224/107713657-08b2dd00-6ccc-11eb-8098-0ad7be80cb4a.png)

**Comment by vincode-io** [comment]
We don't want to change how the Timeline works to add a special case for Search, so I'm going to close this issue.
