### ISSUE TITLE
self created twitter app?

### ISSUE THREAD

**Issue by dumprop** [Ranchero-Software/NetNewsWire#2812]
Currently, NNW app have access to my twitter account
<img width="379" alt="image" src="https://user-images.githubusercontent.com/34004367/107876738-ad494080-6ebf-11eb-8d56-9e24604724d8.png">
 
Also, some other application support self-created twitter apps (for example https://github.com/huginn/huginn/wiki/Configuring-OAuth-applications#twitter )
So, I would like to create own twitter app and authenticate in that app

**Comment by vincode-io** [comment]
Why do you want to do this?

**Comment by dumprop** [comment]
Its more secure
https://thehackernews.com/2013/10/buffer-hacked-twitter-facebook-flooded.html
Fortunately here only read-only rights, so possible impact is not high, but anyway after that incidents I think will be better to use personal apps

**Comment by vincode-io** [comment]
If NNW got compromised and was spamming Twitter, wouldn't we want the ability to shut it off at the server by disabling the app on Twitter? If we encouraged people to create their own Twitter apps, we wouldn't have that ability.

**Comment by dumprop** [comment]
Anyway NNW would disable it only after some incidents, this could be a target for attackers
Fortunately currently it can only read, but still low impact (reading private posts)
And with the growing of popularity, this will only increase

**Comment by vincode-io** [comment]
We won't be adding this unnecessary complexity.
