### ISSUE TITLE
Battery drain from running in the background

### ISSUE THREAD

**Issue by cga00** [Ranchero-Software/NetNewsWire#2814]
iPhone 12 Pro
iOS 14.4
NetNewsWire 5.0.5 (Build 56)

Background App Refresh is completely turned off for all apps. Why is NetNewsWire running in the background?

![C853060E-6F77-4168-9CB8-031E2C1185D4](https://user-images.githubusercontent.com/28816404/108010893-37c69880-6fc3-11eb-926a-caaeb93370c8.jpeg)

**Comment by vincode-io** [comment]
What is that a screenshot of? Could you please include the full screen?

**Comment by cga00** [comment]
Here’s another screenshot from the Battery settings in iOS.

![293D44C2-0E14-4381-A1AD-142D8D555538](https://user-images.githubusercontent.com/28816404/108011746-fa630a80-6fc4-11eb-89aa-f440b1861f91.jpeg)

**Comment by vincode-io** [comment]
Do you think that number is accurate? It has 8 more hours of usage since the last screenshot.

**Comment by cga00** [comment]
Sorry, the first screenshot was a snapshot of a certain point in time within that 24 hour period. The latest screenshot is a snapshot of the full 24 hour period. Sorry for the confusion.

**Comment by vincode-io** [comment]
Do you have any idea what happened on Sunday? Is that the first day you had NNW installed? The usage for Sunday is very peculiar compared to the rest of the week.

**Comment by cga00** [comment]
I’m not sure what’s going on. I installed NNW last week. I’ll try uninstalling and reinstalling it.

**Comment by vincode-io** [comment]
Yeah, let's try that. Restart your phone too. It looks like something weird is happening with iOS.

On iOS the operating system determines when the background tasks run. We can request that we run every 15 minutes, but that never happens. It runs it when it thinks you will need the data. In your case, it shouldn't be running it at all, because you have it background tasks disabled. It isn't possible to bypass that setting.

**Comment by stuartbreckenridge** [comment]
Out of interest, what was the battery usage?

**Comment by cga00** [comment]
It says 21% for that time period.

**Comment by cga00** [comment]
I _think_ uninstalling and reinstalling, and restarting my phone resolved the issue. I checked this morning and it doesn't show NNW having run in the background throughout the night, which is good. I appreciate your help.
