### ISSUE TITLE
Moved subscriptions from Feedbin to iCloud only visible after restart

### ISSUE THREAD

**Issue by eivindml** [Ranchero-Software/NetNewsWire#2815]
Started testing NetNewsWire 6, by moving "drag and drop" a folder of subscriptions from Feedbin to iCloud. It shows sync status, and it finishes, but the folder never appears in iCloud. If I restart the app, it is then there, and everything works. 

I tried moving "Kan lese", but it doesn't show in iCloud:
<img width="1552" alt="Skjermbilde 2021-02-16 kl  20 45 15" src="https://user-images.githubusercontent.com/202450/108113969-7bd79d00-7098-11eb-8292-ae2fb27022fb.png">

**Comment by vincode-io** [comment]
We now show the folder as soon as it is created instead of at the end of the process. Look for this fix in the next test release.
