### ISSUE TITLE
Hangs (beachball) on opening, 0 feeds refreshed

### ISSUE THREAD

**Issue by wgroeneveld** [Ranchero-Software/NetNewsWire#2817]
Something stange happened yesterday. When opening NetNewsWire, as usual, it first refreshes RSS streams, but now it immediately hangs at 0 out of .... Beachball effect, in Activity Monitor it says not responding. 

I have no idea what is wrong. I used to run the stable 5.x version, upgraded to the latest 6.x bleeding edge, same result (replaced the program). I _think_ if I delete my data, it could work again. I would try, but I can't find the folder that https://netnewswire.com/help/mac/5.0/en/userdata-location claims to be in `~/Library/Application Support/NetNewsWire` 

I'm on a M1 silicon Mac, Big Sur 11.2 beta. 
In attach the sampled activity. 

Can I do anything more to help make this issue more clear?
Thanks!
[Sample of NetNewsWire.txt](https://github.com/Ranchero-Software/NetNewsWire/files/6001918/Sample.of.NetNewsWire.txt)

Edit: these are the details in the crash report:
[crash-details.txt](https://github.com/Ranchero-Software/NetNewsWire/files/6001944/crash-details.txt)

**Comment by vincode-io** [comment]
User data is now in `~/Library/Containers/com.ranchero.NetNewsWire-Evergreen/Data/Library/Application Support/NetNewsWire` for version 6.0.

Before you delete your accounts could you try:
`defaults delete com.ranchero.NetNewsWire-Evergreen`

That might clear up some state that is preventing you from launching. Only if that doesn't work, would I try deleting the account(s).

**Comment by brentsimmons** [comment]
The sample looks like WebKit code. I don’t think it’s our bug. Which is unfortunate, because it means we don’t have a way to fix it.

I’d like to be wrong — requires further investigation.

**Comment by wgroeneveld** [comment]
> User data is now in `~/Library/Containers/com.ranchero.NetNewsWire-Evergreen/Data/Library/Application Support/NetNewsWire` for version 6.0.
> 
> Before you delete your accounts could you try:
> `defaults delete com.ranchero.NetNewsWire-Evergreen`
> 

Does nothing.

> That might clear up some state that is preventing you from launching. Only if that doesn't work, would I try deleting the account(s).

Also does nothing! When opening up NetNewsWire again, my rss feeds are gone (of course), but it again immediately crashes...

**Comment by wgroeneveld** [comment]
I have no idea why, but a reboot solved it. Both 5.x and 6.x seem to work again. Of course I'd sleep better if anyone understood what the problem was but hey - in the meantime, I can enjoy my news again 🤓

**Comment by brentsimmons** [comment]
This reinforces my hunch that it wasn’t a NetNewsWire bug. If this happens to someone else, we’ll suggest a reboot. Thanks for reporting this and following up!

**Comment by hybras** [comment]
I had this issue until I updated to macOS 11.5.1, confirming Brent's hunch that it wasn't NNW's bug.
