### ISSUE TITLE
macOS: using keyboard shortcuts don’t change focus

### ISSUE THREAD

**Issue by kevinm6** [Ranchero-Software/NetNewsWire#2819]
When ‘a’ and ‘z’ are used to move between feeds on the sidebar and you move the focus on the various articles of that feed/folder (maybe just to open one), press again those keys, works fine because it goes to the next/previous web feed/folder, but it doesn’t change the focus, it remains greyed.
It requires the left arrow key to be pressed to change the focus and became blue as selected.

I don’t know if this behaviour is intended.

**Comment by brentsimmons** [comment]
It is intended — a and z shortcuts exist to change selection in the sidebar without changing the focused view.
