### ISSUE TITLE
iOS: is this expected?

### ISSUE THREAD

**Issue by kevinm6** [Ranchero-Software/NetNewsWire#2822]
I use NNW enough and I have several subscriptions with Feedly sync service.

![image](https://user-images.githubusercontent.com/72861758/108779878-dd4fae00-7567-11eb-8af0-b1cd30f005e5.png)

**Comment by brentsimmons** [comment]
Yes, that’s not unusual. Remember that NetNewsWire is storing locally a lot of articles! There is a time limit — it gets rid of old stuff, so it won’t just keep using more and more space forever.

**Comment by kevinm6** [comment]
Okay, thank you @brentsimmons !
I’ve just checked again and it drops of 200MB.

**Comment by 24fpsDaVinci** [comment]
where can I set time limit?
