### ISSUE TITLE
NNW6.0a4 on M1, BS 11.2: ad Reddit-feed creates blocking window...

### ISSUE THREAD

**Issue by Thomas-U** [Ranchero-Software/NetNewsWire#2827]
..."Finding feed" that reacts to nothing. NNW stays responsive but no command can get through.

You can see in the screenshot that the feed has been created and has synced.

Only way out is force-quit. After new start all is well. I wonder why NNW does not ask to comment on the force-quit.

The same had happened with the first feed (Thomas_U).

![Screen-Shot 2021-02-23 at 22 12 04](https://user-images.githubusercontent.com/171936/108909346-bacf9a80-7624-11eb-9481-41cd5715837e.png)

**Comment by Thomas-U** [comment]
The same happens when adding a twitter feed.

**Comment by Thomas-U** [comment]
6.0a4: I just created the same reddit-feeds plus a twitter-feed on my M1 11.3. beta 2 installation - only this time into the beta test account. No problem so far.

**Comment by Thomas-U** [comment]
I have dragged-dropped these 3 into the iCloud account. No problem.

**Comment by vincode-io** [comment]
Sounds like this is better. Closing the issue.

**Comment by Thomas-U** [comment]
I checked on the 6.0a4 on M1, BS 11.2 side:

The three feeds appeared instantly, no longer counter stalls, all ok.

I guess I'll wait for a5 now.
