### ISSUE TITLE
Feature Request: Mark all headlines as read when opening a subscription’s home page

### ISSUE THREAD

**Issue by gruber** [Ranchero-Software/NetNewsWire#2838]
NNW 3 had an option such that if you double-clicked a feed to open that feed’s home page in your browser, the feed would be marked as read. I do this for a lot of feeds that I think are best read on their website. It’s not a huge pain to just hit K before double-clicking, but I for one would love to see this preference come back.

Screenshot of NNW 3 preference attached. But I’d be happy with this as a hidden `defaults` preference in NNW 6.

<img width="597" alt="Screen Shot 2021-02-26 at 5 04 21 PM" src="https://user-images.githubusercontent.com/12223/109360999-251b5180-7856-11eb-8081-0ac7db63207b.png">

**Comment by brentsimmons** [comment]
Question: should this mark-all-as-read behavior extend to clicking on the feed name in the article view? Or is this only for opening via the sidebar?

**Comment by vincode-io** [comment]
I've implemented this with the assumption that it was Sidebar only that we were impacting. If we need to also do this for the article view, I'll reopen this issue.

`defaults write com.ranchero.NetNewsWire-Evergreen GruberFeedDoubleClickMarkAsRead -bool true`

**Comment by gruber** [comment]
I just went back to NNW 3 — it only worked in the sidebar there. I think it makes sense that way, to be honest. Double-clicking the item in the sidebar feels like your “clearing” that item. Clicking the home page link the article view feels like you’re just clicking a regular URL to that home page. I think Maurice has it correct as-is. (Good question though — made me think enough to go and check how NNW 3 worked.)
