### ISSUE TITLE
macOS: most recent item in Dilbert feed has tomorrows date

### ISSUE THREAD

**Issue by maartenh** [Ranchero-Software/NetNewsWire#2845]
The feed for the Dilbert comic shows dates that are 1 day further into the future than they should be.
Today's comic for March 2nd is listed as March 3rd, and yesterdays comic is listed as being from 08:59 today. The time is about correct, that is usually about the local time when the new comic appears in the feed.

The same feed in Reeder 3 on my phone does show the correct date.

Local timezone is Europe/Amsterdam (UTC +0100).

Feed url: http://feedproxy.google.com/DilbertDailyStrip?format=xml
Feed homepage: http://dilbert.com/

**Comment by brentsimmons** [comment]
The date for the March 2 comic appears in the feed as "2021-03-02T23:59:59-08:00" — which is equivalent to 3 March 2021 at 08:59 in UTC +0100.

It’s a bug in the feed, in other words.
