### ISSUE TITLE
NNW6 (macOS): There's an extra few pixels worth of separator between the timeline and the article

### ISSUE THREAD

**Issue by stuartbreckenridge** [Ranchero-Software/NetNewsWire#2848]
<img width="160" alt="separator" src="https://user-images.githubusercontent.com/7046652/110134085-fe39be00-7e07-11eb-82c6-1b0202b0ee8c.png">
<img width="451" alt="Screenshot 2021-03-05 at 23 11 22" src="https://user-images.githubusercontent.com/7046652/110134214-1ad5f600-7e08-11eb-8e6f-bc38fdebb7b4.png">

**Comment by vincode-io** [comment]
@brentsimmons This happens because we are wrapping the `WKWebView` in an `NSBox`. Getting rid of the `NSBox` fixes the problem, but I don't know if I would be breaking something else by removing it. Do you remember the reason for the `NSBox`?

**Comment by brentsimmons** [comment]
I don’t remember the reason for the NSBox.
