### ISSUE TITLE
Read articles on Mac not reflected on iOS without a Mac Refresh

### ISSUE THREAD

**Issue by dbarros** [Ranchero-Software/NetNewsWire#2851]
When I use NNW on the Mac, I tend to end a session my marking all articles as read. But when I then go to the iOS app, the same articles I just marked as read on the Mac still show up as unread on iOS.

The only way to rectify this is by doing a Refresh on the Mac first. Is there a setting or some-such that I can use to have the two apps be in sync, without manually refreshing on the Mac first? Or is there some amount of time I need to wait for the sync to come across to iOS?

**Comment by vincode-io** [comment]
In version 6 we now try to sync when closing the application, so this won't be as much of an issue in the future. The exception is if the network request can't be completed in 2 seconds we go ahead and quit anyway.
