### ISSUE TITLE
scrolling with up-arrow-key in article timeline

### ISSUE THREAD

**Issue by Thomas-U** [Ranchero-Software/NetNewsWire#2852]
There is one issue that I observed already in a4 and that I did not find reported on GitHub yet (maybe I don’t know how to search correctly).
Situation: The unread article list of a folder or feed is longer than fits in the column and I start scrolling from the bottom of the list using the up-arrow key.
When I reach the topmost article it is displayed only partially  in the column. After next click the list jumps - I would expect the jump earlier.
When I reach the top end of the list the topmost article is displayed only partially. I can only make it fully visible using mouse/touchpad scrolling.
I made a screen-recording using @cdevroe’s blog feed: http://www.tul8.de/Software/NNW-tests/NNW6.0a5-scrolling-up.mov

**Comment by vincode-io** [comment]
This was fixed by https://github.com/Ranchero-Software/NetNewsWire/pull/2853
