### ISSUE TITLE
Poor rendering of favicon in sidebar

### ISSUE THREAD

**Issue by adamjrice** [Ranchero-Software/NetNewsWire#2856]
Sidebar text and favicons are smaller in version 6 than previous versions. Favicons look pretty rough on standard-definition monitors compared to NNW 5 (admittedly this is how they appear in Safari's tab bar).

I'd be happy if the text and icons were reverted to their previous larger size, or the option were available to increase the size.

![Screen Shot 2021-03-08 at 10 54 26](https://user-images.githubusercontent.com/15695982/110353595-dd868980-7ffc-11eb-948d-291f6b38a404.png)

**Comment by vincode-io** [comment]
Feed icons now obey the "Sidebar icon size" preference in the General pane of System Preferences. They also match Apples Human Interface Guidelines for those sizes.

**Comment by adamjrice** [comment]
I'm not sure applying that preference in this context is the best idea. Monochrome line-art icons scale down better than complex, full-color icons do.
