### ISSUE TITLE
Strange case with feed (freshrss)

### ISSUE THREAD

**Issue by dumprop** [Ranchero-Software/NetNewsWire#2857]
Feed:
https://rsshub.app/telegram/channel/fintechhubcbr

When I try to add it to FreshRSS:
<img width="292" alt="image" src="https://user-images.githubusercontent.com/34004367/110369059-bc945780-8041-11eb-8d73-776f96df5d42.png">

When I try to add it to my mac:
<img width="260" alt="image" src="https://user-images.githubusercontent.com/34004367/110369085-c74eec80-8041-11eb-9de2-6d0c359c388b.png">

On FreshRSS side I successfully added it manually
<img width="941" alt="image" src="https://user-images.githubusercontent.com/34004367/110369129-d9c92600-8041-11eb-8997-be1b7e3f25a9.png">

Fixed by deleting it from FreshRSS via NNW (there was some stuck, restarting didnt help then)

**Comment by vincode-io** [comment]
I was able to successfully add this feed to my FreshRSS installation. Please make sure you are running the latest version of FreshRSS.

<img width="1421" alt="Screen Shot 2021-03-08 at 1 19 23 PM" src="https://user-images.githubusercontent.com/16448027/110370131-eda86400-8010-11eb-8a92-d766abfeaa78.png">

**Comment by dumprop** [comment]
Yes, I added it too, so there all are ok (it fixed)
But there was some stuck (probably in first time was error on rsshub side, so it cached invalid answer or smthg like that)
By that reason it just a case, not a bug
