### ISSUE TITLE
iOS bug when tapping the URL in top of article

### ISSUE THREAD

**Issue by anon238** [Ranchero-Software/NetNewsWire#2866]
When tapping the article URL in the top ‘In-App Safari’ opening with the home page of that feed, but when you open the ‘Share’ menu and ‘Open with Safari’ then it links to the correct feed. 

Edit: overall, i’m a huge fan and never used RSS that much although I really loved it since the begin, but all apps are crap and I love yours so I won’t have to travel to all websites.

**Comment by vincode-io** [comment]
When you click the name of the feed or the author, you will get taken to the home page of the feed. This is by design. If you want to go to the article, click the article title instead.

**Comment by anon238** [comment]
Ah thanks for this! Huge hassle for me. Didn’t saw that.
