### ISSUE TITLE
Convert wp-smiley to real emoji

### ISSUE THREAD

**Issue by j-f1** [Ranchero-Software/NetNewsWire#2868]
It seems like WordPress RSS feeds convert emoji (for example, 📰 becomes `<img alt="📰" src="https://s.w.org/images/core/emoji/13.0.1/72x72/1f4f0.png" class="wp-smiley">`). Since the emoji seem to be Twitter emoji, and since NNW only works on platforms that support emoji, it would make sense to turn these into real emoji by replacing the `img` with its alt text.

Example feed: https://www.matthewcassinelli.com/feed/

**Comment by vincode-io** [comment]
Mapping all the WordPress images to standard emoji would be a monumental task with very little reward. This simply isn't something that we should devote developer time to even if we had it. It is really up to WordPress to straighten this situation out.

**Comment by j-f1** [comment]
You don’t need to map the images — each image has the real emoji as its alt text, so you only need to replace the image with its alt text.
