### ISSUE TITLE
Feeds don't seem to refresh properly in 6.0b1 when all feeds are moved to iCloud

### ISSUE THREAD

**Issue by zellyn** [Ranchero-Software/NetNewsWire#2869]
Version: 6.0b1 (6012)

I dragged all my feed folders over to iCloud. Now feeds don't seem to refresh every hour: it's common for me to hit the manual refresh and see a bunch of feed entries show up. Happy to help debug if it helps.

**Comment by vincode-io** [comment]
Try testing with this feed.  https://www.flickr.com/services/feeds/photos_public.gne

It is a high volume feed that gets you new articles everytime.  Set your refresh interval for 10 minutes to make testing easier.

**Comment by zellyn** [comment]
Good suggestion. Added. We'll see what happens in 10 minutes!

**Comment by zellyn** [comment]
The flickr feed is updating. I'll wait for a while to see whether any of my existing feeds update too.

**Comment by zellyn** [comment]
Naturally, it's all working now 😂
