### ISSUE TITLE
Starred articles lost when moving feed folders from "On My Mac" to iCloud

### ISSUE THREAD

**Issue by zellyn** [Ranchero-Software/NetNewsWire#2870]
Version: 6.0b1 (6012)

Excited about the new iCloud sync functionality, which will let me sync between my iPhone and Mac, I eagerly dragged all my feed folders over from "On My Mac" to "iCloud".

All my starred articles disappeared 😞

**Comment by vincode-io** [comment]
We only copy the feed.  Not the read or starred statuses between accounts. How different syncing services identify articles is different and trying to match them up is next to impossible.

**Comment by zellyn** [comment]
In this case, the behavior was very surprising, since "On My Mac" and "iCloud" are both fully under NNW's control. I would have been less surprised if I lost favorites when dragging a feed from "On My Mac"/"iCloud" to a cloud feed service, or the reverse.

**Comment by vincode-io** [comment]
Sure, we could with much effort make it work between those two accounts. Then we would be getting bug reports about how it is inconsistently with other accounts. There really isn't much of a win here for a process that people do very rarely.

**Comment by zellyn** [comment]
Fair enough. Do you know if there are any logs or anything where I could possibly retrieve my starred articles? There were more than I can remember 😞

**Comment by vincode-io** [comment]
Did you lose them from your On My Mac account? It should have copied by default unless you held down the option key when dragging.

**Comment by zellyn** [comment]
I held down the option key 😞

**Comment by vincode-io** [comment]
I'm sorry about that. We changed that behavior in B1 so that the default when dragging between accounts is now to copy since so many people were losing their data in their original accounts. Holding down the option key when dragging between accounts is now a move.

**Comment by kevinm6** [comment]
> I'm sorry about that. We changed that behavior in B1 so that the default when dragging between accounts is now to copy since so many people were losing their data in their original accounts. Holding down the option key when dragging between accounts is now a move.

@vincode-io Why don't set the move with "command down" as Finder does?
