### ISSUE TITLE
feed not working in iCloud

### ISSUE THREAD

**Issue by gferreroferri** [Ranchero-Software/NetNewsWire#2874]
Hi,

This feed is not working with iCloud:
http://www.hel.fi/wps/wcmjspv2/filtered-news-listing.jsp?rss=rss&lang=en
However it works with any other online service like Feedly or FreshRSS

**Comment by kevinm6** [comment]
For me, on NNW Version 6.0b1 (6012) it returns an alert with the message “Forbidden” on Feedly service.

**Comment by gferreroferri** [comment]
I have added by importing from OPML and they show fine. But when I import the same OMPL to iCloud, the feed appears empty

**Comment by kevinm6** [comment]
Try to import it from url and not from opml, check if it works

**Comment by brentsimmons** [comment]
The feed has many bugs:

https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fwww.hel.fi%2Fwps%2Fwcmjspv2%2Ffiltered-news-listing.jsp%3Frss%3Drss%26lang%3Den
