### ISSUE TITLE
update error from 6.0b1 to 6.0b2

### ISSUE THREAD

**Issue by foss-** [Ranchero-Software/NetNewsWire#2880]
Took a look at `~/Library/Logs/SparkleUpdateLog.log`  but that had no entry from the time I did the update check in NetNewsWire

Next I used `log stream | grep -i sparkle` in terminal and well, as I was getting some data, the update went through.

Still filing to let you know about the hickup, just close this, should it already be obsolete.

And thanks so much for making NetNewsWire ❤️ - amazing software!

<img width="372" alt="update error" src="https://user-images.githubusercontent.com/5708172/111044446-1d100400-8449-11eb-83bf-91f34fe3ea23.png">

**Comment by brentsimmons** [comment]
Thanks! Fixed. It was just a copy-paste error in the appcast feed.
