### ISSUE TITLE
Disabling "Show unread count" for Dock icon requires me to enable notifications

### ISSUE THREAD

**Issue by radiocolin** [Ranchero-Software/NetNewsWire#2881]
Version 6.0b2 (6022)

Notifications for NNW are disabled in System Preferences.

"Show unread count" is checked when I open the preferences box. I try to uncheck it, and it prompts me to go to system preferences and allow notifications for NNW before it will let me uncheck the box.

https://user-images.githubusercontent.com/992033/111045032-eb337900-8419-11eb-807e-623502e4a136.mov

**Comment by vincode-io** [comment]
We've removed this preference and you should now manage this using the System Preferences.
