### ISSUE TITLE
The operation couldn’t be completed. (OAuthSwiftError error -11.)

### ISSUE THREAD

**Issue by asyraffff** [Ranchero-Software/NetNewsWire#2882]
I get this error when trying out the new `Twitter Feed` features. I try to click the `Twitter` button, this error came out;

<img width="533" alt="Screenshot 2021-03-14 at 19 48 40" src="https://user-images.githubusercontent.com/58986949/111067227-48a0f600-84fe-11eb-8d41-8dae17dbf36e.png">

But for `Reddit`, it works well.

**Comment by stuartbreckenridge** [comment]
That's an old version (an alpha I think). The latest betas fix this issue.

**Comment by asyraffff** [comment]
@stuartbreckenridge Thanks ;p, it works with the latest betas.
