### ISSUE TITLE
TheOldReader unread count goes out of sync

### ISSUE THREAD

**Issue by foss-** [Ranchero-Software/NetNewsWire#2883]
Using an TheOldReader account with

* NetNewsWire 6.0b2 on macOS 11.2.3

**Currently**

While all items are read in NNW it appears read state is not synced back to TOR. After logging in to TOR webview the items remain unread.

**Expected**

Read items should sync back to webservice and read items be marked as read.

**Comment by vincode-io** [comment]
I just tested this and it works for me. Do have any more details you can share to so that we can isolate this problem?

**Comment by foss-** [comment]
Thanks for looking into this and trying to reproduce. For testing I removed and re-added the The Old Reader account and ended up with all the unread items showing up in NNW as unread.
Marked them as read and synced. Items in TOR webview showed as read as well.

Everything back in order. Unsure what got stuck.
