### ISSUE TITLE
Incorrect URL encoding of password for The Old Reader

### ISSUE THREAD

**Issue by simon--taylor** [Ranchero-Software/NetNewsWire#2884]
Logging in to The Old Reader in NetNewsWire 6.0b2 on macOS 11.2.3 fails because my password containing non-alphanumeric characters isn't correctly encoded. The login dialog then displays the misleading message, "Network error. Try again later." even though the API has returned Error=BadAuthentication

**Comment by vincode-io** [comment]
Which specific characters are you using?

**Comment by vincode-io** [comment]
This is fixed and will be in the next beta release.
