### ISSUE TITLE
Window and dialog focus issues

### ISSUE THREAD

**Issue by tthkbw** [Ranchero-Software/NetNewsWire#2885]
M1 Mac mini running latest Big Sur.

Two focus issues:

1. When the app is started, most of the time it does not bring its window to the front. It's hidden behind other windows. And it is so fast (!!) that I don't see the app icon bounce in the dock and wonder if it really started.
2. when I select check for updates, the dialog appears, but, again, is not in front of other windows, including NewNewsWire itself. I have to go looking for it.

**Comment by vincode-io** [comment]
How are you launching NNW? From the dock or some other way? Do you have any window management software installed that we might need to take into consideration?

**Comment by tthkbw** [comment]
Fascinating. the problem appears related to the fact that I am of the habit of using a Keyboard Maestro macro to activate the Keyboard Maestro Application Switcher to launch NNW. I assign the macro to a hotkey (F8) and then invoke the hotkey by mapping it to a button on my Logitech MX Anywhere mouse using LogiOptions software. When I launch NNW in this manner, the window does not always appear at the front, although sometimes it does. The same problem occurs if I just use the hotkey directly instead of the mouse mapping, however.

I also launch other applications using this method, and I have not noticed this problem, but I could have missed it. I'll pay attention, now. NNW probably gets launched more frequently, because I tend to close it when I am done with it, while with other applications I tend to leave them open for days. 

In the Keyboard Maestro macro, I do invoke the Application Switcher, select "Display in icon grid"; and "Place switcher under mouse". The Keyboard Maestro Application Switcher can launch programs as well, if you include them in the "Always include these applications:" list.

If I instead invoke NNW using Alfred, it does appear at the front.

**Comment by vincode-io** [comment]
I'm not sure what we can do to help you. We launch just like every other Mac application. If you find some way that we can accommodate your workflow, please reopen this issue.
