### ISSUE TITLE
NNW 6.0b2 (6022): Unable to add NewsBlur account

### ISSUE THREAD

**Issue by jeffhunter** [Ranchero-Software/NetNewsWire#2886]
Steps to reproduce:

1. Open NetNewsWire preferences, go to Accounts tab.
2. Click + button, select NewsBlur, click Continue
3. Enter NewsBlur username and password.

Expected: NewsBlur account is added.
Actual: Red text message shows up: "Network error. Try again later."

NewsBlur is working fine in my browser, so I don't believe that the service is down.

Configuration: MacBook Pro running macOS Big Sur 11.2.3.

**Comment by vincode-io** [comment]
Are you still experiencing this problem? I just successfully added a NewsBlur account. If so, are there any special characters in your username or password?

**Comment by jeffhunter** [comment]
It's working now! So I guess there actually was some sort of NewsBlur outage this morning?
