### ISSUE TITLE
Dragging folders to iCloud results in strangeness

### ISSUE THREAD

**Issue by WanderingStar** [Ranchero-Software/NetNewsWire#2887]
I just configured 6.0b2 to add an iCloud account. I then selected all of my folders of subscriptions and dragged them from On My Mac in the sidebar to iCloud in the sidebar.

I was prompted with a large number of "XYZ can not be copied because it no longer exists" dialog boxes with varying numbers of subscriptions in each, which, fair, I haven't cleaned up my subscriptions in literal years. I clicked to acknowledge them all.

The result was only one folder (named after one of my folders), which seems to contain no subscriptions, yet has unread articles in it.

<img width="346" alt="image" src="https://user-images.githubusercontent.com/1622203/111088353-cb24b800-84f4-11eb-9770-f510f6b1d4ad.png">

I've expanded the `45 Mine` folder in the On My Mac section to show that it does contain discrete feeds there, but the expanded folder in iCloud does not. When I originally dragged the subscription folders, it was collapsed.

The app badge for NNW shows 3754 unread, which is much larger than the sum of what's shown in my sidebar. I haven't quit and restarted the app yet.

**Comment by vincode-io** [comment]
Did it ever finish for you?

**Comment by brentsimmons** [comment]
Closing — we will address this in #2888

**Comment by WanderingStar** [comment]
@vincode-io It didn't resolve by itself, but after quitting and relaunching, I see the expected folders, with the (very large) unread counts that I would expect if nothing had been read.

<img width="220" alt="image" src="https://user-images.githubusercontent.com/1622203/111102163-6af43d00-8519-11eb-8025-0d9f0740d38a.png">
