### ISSUE TITLE
Cannot log into NewsBlur

### ISSUE THREAD

**Issue by KTamas** [Ranchero-Software/NetNewsWire#2889]
Had this error since the alphas. Always the same: "Network error. Try again later."

Tried different networks etc. nothing fixes it.

**Comment by brentsimmons** [comment]
Which version of NetNewsWire are you running (according to the About window)?

**Comment by vincode-io** [comment]
Do you have any special characters in your username or password?

**Comment by KTamas** [comment]
yes there is a semicolon in my password. is that really it??

**Comment by KTamas** [comment]
> Which version of NetNewsWire are you running (according to the About window)?

6.0d5 (6005)

**Comment by KTamas** [comment]
> Do you have any special characters in your username or password?

Yes there is a semicolon in my password. is that really it??

**Comment by brentsimmons** [comment]
It’s a good idea to get the latest beta: https://nnw.ranchero.com/2021/03/13/netnewswire-b-for.html

**Comment by vincode-io** [comment]
That is probably the problem. It is the same as #2886. I fixed this for all services and the fix is coming in the next Beta.

**Comment by vincode-io** [comment]
Oops, I linked the wrong issue. This was actually fixed in #2884.

**Comment by jfdhuiz** [comment]
I'm getting the same error with 6.0.2. No special characters in password, but am using a custom port and https (both defined in API URL).

**Comment by jfdhuiz** [comment]
The problem was an incorrect base_url in config.php affecting the API URL. My base_url is non-standard cause of running behind a reverse proxy + SSL. FreshRSS logs just mentioned password was incorrect.

**Comment by brentsimmons** [comment]
It’s working for you now?
