### ISSUE TITLE
feature request: add twitter list as feedsourc

### ISSUE THREAD

**Issue by danieltomasz** [Ranchero-Software/NetNewsWire#2894]
If  this is possible to implement with Twitter AP, I would really like to have a possibility an add a specific user-created list as a  type of feed, I really  heavily on this function

**Comment by vincode-io** [comment]
You can use lists. Just paste the URL of the Twitter list into the Web Feed dialog after you have set up the Twitter extension. You can also use the new Share extension by going to the list on the web and sharing it with NetNewsWire.
