### ISSUE TITLE
Feature Request: iCloud sync

### ISSUE THREAD

**Issue by gaemarkus** [Ranchero-Software/NetNewsWire#2895]
First of all, I am very new to RSS so forgive me if I got something totally wrong.

At the moment I can sync my feeds using Feedbin or Feedly. I'd much prefer to sync my feeds between my devices using iCloud.

I am sure there has to be a reason why this is not possible yet, but from my perspective it seems like an obvious choice.

**Comment by stuartbreckenridge** [comment]
It's coming in the next [release](https://inessential.com/2021/03/17/new_in_netnewswire_6_icloud_syncing).

**Comment by gaemarkus** [comment]
Thank you! I did not see that.
