### ISSUE TITLE
macOS bug or misplaced? Add Item in the wrong side

### ISSUE THREAD

**Issue by gferreroferri** [Ranchero-Software/NetNewsWire#2896]
Should't the option to add item be located next to the sync on the folder and subscription column? All these functions are related to the items in that column (feed, folders) and have nothing to do with the article view.

**Comment by vincode-io** [comment]
Could you add a screenshot so that we can see what you are talking about?

**Comment by kevinm6** [comment]
> Should't the option to add item be located next to the sync on the folder and subscription column? All these functions are related to the items in that column (feed, folders) and have nothing to do with the article view.

I don't think it's possible, is the new style of macOS Big Sur top bar!
I think him is referring to this 👇🏻

![image](https://user-images.githubusercontent.com/72861758/111799032-edd71800-88ca-11eb-863c-0483f1051fae.jpeg)

**Comment by kevinm6** [comment]
> > Should't the option to add item be located next to the sync on the folder and subscription column? All these functions are related to the items in that column (feed, folders) and have nothing to do with the article view.
> 
> I don't think it's possible, is the new style of macOS Big Sur top bar!
> I think him is referring to this 👇🏻
> 
> ![image](https://user-images.githubusercontent.com/72861758/111799032-edd71800-88ca-11eb-863c-0483f1051fae.jpeg)


But I've changed mine. 
This is how my NNW looks like.
![image](https://user-images.githubusercontent.com/72861758/111799891-b87efa00-88cb-11eb-8f93-164603a3ad76.jpeg)

**Comment by gferreroferri** [comment]
Yes, that I what I meant

**Comment by vincode-io** [comment]
It is where we want it to be.

**Comment by stuartbreckenridge** [comment]
You can rearrange to toolbar, if the defaults aren't what you like.

**Comment by gferreroferri** [comment]
Not that >> icon. Somehow it cannot be rearranged
