### ISSUE TITLE
Removing a feed from Feedly displays an error message

### ISSUE THREAD

**Issue by michaelperrin** [Ranchero-Software/NetNewsWire#2897]
When deleting a feed (any works with any feed) from a Feedly account, the following error message is displayed:

> The data couldn’t be read because it is missing.

When clicking on the Refresh icon, the feed has successfully been deleted from the list.

OS Version: MacOS Big Sur 11.2.3 (20D91)
NetNewsWire version: 6.0b3 (6023)

<img width="1296" alt="Screen Shot 2021-03-19 at 2 00 56 PM" src="https://user-images.githubusercontent.com/344445/111830125-8cf41380-88bb-11eb-95d9-b78a2f84fdc0.png">

**Comment by kielgillard** [comment]
@michaelperrin Can you please share the name or URL for feed you're trying to remove?

**Comment by vincode-io** [comment]
This has been fixed and will be in the next release.

**Comment by michaelperrin** [comment]
Thank you very much 👍
