### ISSUE TITLE
sync read status back on window close

### ISSUE THREAD

**Issue by justme-1968** [Ranchero-Software/NetNewsWire#2898]
please sync the article read status back to the sync service used if the window is closed.

**Comment by vincode-io** [comment]
In NetNewsWire 6 we attempt to sync when the application is terminated.

**Comment by justme-1968** [comment]
please sync also on window close. not only on termination.

**Comment by justme-1968** [comment]
@vincode-io  i really meant window close. not application termination. please sync on window close.
