### ISSUE TITLE
mac os: feed refresh  does not start after login if window was closed on logout

### ISSUE THREAD

**Issue by justme-1968** [Ranchero-Software/NetNewsWire#2899]
if the net news wire window was closed (but the app still running) on logout then after the next login the feed refresh is not started before the window is manually opened for the first time.

**Comment by vincode-io** [comment]
How can you tell that NNW isn't refreshing if the window is closed?

**Comment by justme-1968** [comment]
the badge on the icon is not updated until the window is opened. also when opening the window for the first time it only shows the state from before the logout. then it will refresh the feeds and the badge is updated and the new articles are displayed.

if the window is closed then the refresh is happening in the background as expected and the page is updated even with a closed window.

**Comment by vincode-io** [comment]
We made a change in b4 that should have resolved what you are seeing.

**Comment by justme-1968** [comment]
confirmed still not working after my login just now.
