### ISSUE TITLE
Search behaving strangely

### ISSUE THREAD

**Issue by blackketter** [Ranchero-Software/NetNewsWire#2904]
I can't seem to reliably use the search feature in 6.0b3.

Search often comes up blank or no change to articles.  Often followed by spinny cursor.  Quitting and relaunching doesn't seem to help.  Sample screen capture below.  (Note that the capture doesn't capture the cursor spinning at the end...)

https://user-images.githubusercontent.com/131679/112051106-c5d7f680-8b0e-11eb-86a0-53ffeb656492.mov

**Comment by vincode-io** [comment]
@blackketter Could you do me a favor? Disable your Feedly account and then add a new one beside it. Call it Feedly 2 or something. Let's see if it has the same problem. I suspect that you are having some kind of database corruption issue.

**Comment by blackketter** [comment]
It's complaining with "There is already a Feedly account with that username created."  

Should I delete the existing one (don't want to lose any forensic information you might find useful) or create a new one?

**Comment by vincode-io** [comment]
Let's copy your account folder to a location we can get to it later if it looks like it is something we can debug. It will be in `~/Library/Containers/com.ranchero.NetNewsWire-Evergreen/Data/Library/Application Support/NetNewsWire/Accounts` and start with `16` followed by a random string.

After that, you should be ok to delete your old account and add it back again.

**Comment by blackketter** [comment]
Ok, once the account is deleted and re-added search is working ok.

I have a backup of the account directory saved in case you want to dig around.  The biggest noticeable difference is that the DB.sqlite3 file originally was 311MB and is now 95MB.

**Comment by vincode-io** [comment]
Does the bad DB.sqlite3 database compress down to something you could share with me?

**Comment by blackketter** [comment]
I've put it here: https://www.dropbox.com/s/lnsigwy1xfozry9/db.sqlite3.zip?dl=0

Let me know when you've grabbed it.

**Comment by vincode-io** [comment]
I got it. Thanks for sharing it. I'll see if there is anything we can find out from it.

**Comment by kevinm6** [comment]
Is this the desired behavior @vincode-io? Or it’s taking so much time?
For 3 times that I’ve tried, I had the same behavior of @blackketter, after that I’ve relaunch the app twice and refresh all the feeds.

https://user-images.githubusercontent.com/72861758/112445599-9a901a00-8d4f-11eb-8ada-2d0604d1e1e8.mp4

**Comment by Wevah** [comment]
Is there a full-text index over article contents?

**Comment by vincode-io** [comment]
@kevinm6 It looks like it is working, but taking more time than we would  like. We should look to see if we need to do some kind of periodic maintenance on the full text search.

**Comment by vincode-io** [comment]
@Wevah Yeah, we're using FTS.

**Comment by Wevah** [comment]
(I checked and the system-provided SQLite lib does have various FTSs enabled.)

**Comment by tqml** [comment]
Maybe also related: there is no UI feedback for iCloud Accounts if the article is starred or marked unread in the latest Version 6.0 (6026) on Catalina.

The video shows the difference between the article from the iCloud account (top) and the Local Account (bottom). 

https://user-images.githubusercontent.com/16613048/112749320-eea23500-8fc1-11eb-8d72-1514987d2ce5.mov

**Comment by vincode-io** [comment]
@tqml Could you please file a seperate bug report?

**Comment by tqml** [comment]
Sure, made a new issue for it

**Comment by blackketter** [comment]
It appears that this problem has gone away for me.  Possibly due to @vincode-io's suggestion in #3559 that I delete and re-add my Feedly account.  Search is responsive now.  Probably safe to close, unless you want to go with my suggestion to add some feedback while a search is processing.

**Comment by vincode-io** [comment]
I'm sure that is what fixed it. We need to get to the bottom of why our databases get corrupted sometimes.
