### ISSUE TITLE
Doesn’t Refresh on Launch

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#2905]
6.0b3 Mac. When I launch the app, it doesn’t refresh. (My only active account is iCloud.)

**Comment by vincode-io** [comment]
If you have the debug menu enabled, it isn't supposed to is it?

**Comment by brentsimmons** [comment]
I do have the Debug menu enabled — but I didn’t realize that that prevents refresh on startup. (Possibly something I knew and forgot.) What was our reasoning for that?

**Comment by vincode-io** [comment]
You put it in. I always assumed it was so that we could continuously launch the app while debugging it and not have it go straight into a refresh every time.

**Comment by brentsimmons** [comment]
Right — if running a DEBUG build, it should not refresh. But if the Debug menu is enabled, it should still refresh when running a production build.

**Comment by vincode-io** [comment]
It looks like this got changed sometime. Maybe I did it and don't remember doing it. Anyway, it is back to relying on the DEBUG build instead of the Debug menu to suppress the refresh.
