### ISSUE TITLE
Help menu > Release Notes

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#291]

**Comment by stuartbreckenridge** [comment]
@brentsimmons what can we do on this ticket?

**Comment by vincode-io** [comment]
It looks like we could generate a URL to the GitHub release page and open a web view for it.  https://github.com/Ranchero-Software/NetNewsWire/releases/tag/mac-5.0.4

We would just have to be strict about how we use tags, which we already are.

**Comment by brentsimmons** [comment]
Using GitHub release pages is a good idea.

**Comment by stuartbreckenridge** [comment]
This is setup and working on multi-platform builds. 

On Mac, it points to `/releases/tag/mac-versionNumber`
On iOS, it points to `/releases/tag/ios-versionNumber-buildNumber`

We may need to change how we use iOS release notes, i.e. the release notes for [iOS 5.0.2-49](https://github.com/Ranchero-Software/NetNewsWire/releases/tag/ios-5.0.2-49) just state the build number has been incremented.

**Comment by stuartbreckenridge** [comment]
Would it be fair to say that we should follow `/releases/tag/platform-versionNumber` for future releases?

`/releases/tag/mac-7.0`
`/releases/tag/mac-7.0.1`
`/releases/tag/mac-7.1`
`/releases/tag/ios-7.0`
`/releases/tag/ios-7.1`

**Comment by vincode-io** [comment]
@stuartbreckenridge Yes, that is the standard we should be following.
