### ISSUE TITLE
Release note link is 404

### ISSUE THREAD

**Issue by cortig** [Ranchero-Software/NetNewsWire#2912]
No the end of the world, but if you select to display the release notes in 60b4, the link is 404.
It points to https://github.com/Ranchero-Software/NetNewsWire/releases/tag/mac-6.0b4 instead of https://github.com/Ranchero-Software/NetNewsWire/releases/tag/mac-6.0beta4

Ultimately, it shouldn’t be much of an issue in the final release which shouldn’t have the beta tag in the link, but it might reflect an issue with the way the link is coded in the release note command int he app so I thought I should report it here…

**Comment by vincode-io** [comment]
Thanks for the heads up. It looks like we got this right in the final release, so I'm closing this issue.
