### ISSUE TITLE
Hide Expanded Group Unread Counts

### ISSUE THREAD

**Issue by rreinhardt** [Ranchero-Software/NetNewsWire#2913]
Hello! 

Feature request:

I wonder if this a totally non standard behavior for grouped lists, but I find myself wanting expanded groups to not include the total unread count. I scan the entire view to get a sense of whats got something new and find the group count distracting/redundant. 

It might also be nice to not show group unread counts when collapsed (if you want to maybe do less worrying about rss-read-zero).

**Comment by vincode-io** [comment]
It was a deliberate design decision to include unread counts on grouped items. If we changed it now, it would disappoint a lot of people who rely on them. We do appreciate the feedback, but this is a core piece of functionality not likely to change anytime soon. Sorry.

**Comment by rreinhardt** [comment]
C'est la vie. Cheers!
