### ISSUE TITLE
Strange Feedbin sync behaviour with Mac 6.0b4 (and iOS 5.0.5)

### ISSUE THREAD

**Issue by genmon** [Ranchero-Software/NetNewsWire#2915]
Could somebody else try to replicate this?

- I am subscribed to a number of feeds on Feedbin (~200) and there are a number of unread posts, e.g. 50
- I read these posts on iOS, then later switch to the Mac. I pull to refresh on iOS to ensure that it has synced with Feedbin
- The expected behaviour on the Mac is that the "read" status syncs for each post read on iOS, which is what happened correctly with v5
- However, the "read" status only syncs correctly if no other unread posts have come in the meantime. If the Mac sees any other unread posts, _none_ of the earlier posts are marked as read

Sorry about how convoluted this sounds. There's some broken behaviour, and I've been trying to figure out what it is.

**Comment by vincode-io** [comment]
I ran this scenario about 5 times today and can't recreate your results. The read status kept syncing correctly even when other unread posts were included in the sync.

There is something strange happening with Feedin and syncing read statuses. It has been hard to track down because it will eventually "heal" itself. I was hopeful that you had found the secret to it, but I don't think this is it.

I'll leave this ticket open. Please keep observing and let us know if you come up with any more clues.

**Comment by genmon** [comment]
Thank you for looking at this! It's just happened to me again, and seems to happen reliably every morning. So are there any databases that I could snapshot (on iOS or Mac) that would help pinpoint this? I would be happy to do that.

(I took screenshots this time, to make sure I'm not imagining things! I can supply if you think they would be useful.)

Given it always happens overnight, could it be a date issue? I don't touch my Mac between 7pm and 8am, and use the phone in-between. The posts that are incorrectly marked "unread" on my Mac, after it syncs at 8am, cover ones that I read over that whole period (before and after midnight). Refreshing on my Mac, at 8am, doesn't help. _But_ I can kick the Mac into action by waiting until a couple more articles pop up on my phone, reading those, then refreshing on the phone and then on the Mac.

I'm speculating now, so I won't say anything more until I have more concrete pointers.

**Comment by genmon** [comment]
Yes, I leave NNW running. I don't actively sleep my Mac, just walk away, and I haven't changed the Energy Saver defaults so the screen turns off after ~10 minutes and nothing stops it from sleeping automatically. It's a Mac mini M1 (so no lid to close), Big Sur 11.2.3.

**Comment by vincode-io** [comment]
What is your refresh interval for NNW set to?

**Comment by genmon** [comment]
Every hour.

**Comment by vincode-io** [comment]
Thanks. I was finally able to come up with a sequence to recreate this. We should be able to work out the problem now.

**Comment by genmon** [comment]
Thank you for putting your time into this! NNW is one of my most-used apps so I appreciate it.

**Comment by vincode-io** [comment]
I got it fixed. This will be resolved in the upcoming 6.0.1 release.

**Comment by vincode-io** [comment]
@genmon Could you test NNW 6.0.1b1 to make sure we got this issue resolved?

**Comment by genmon** [comment]
I will do! I don't know how to actively trigger the issue, but as it occurred most reliably in the mornings, the next opportunity is in 24 hours. I will report back.

**Comment by genmon** [comment]
@vincode-io Just to confirm that the issue did not reoccur for me this morning, so it appears to be resolved! (Version 6.0.1b1 (6028))

**Comment by vincode-io** [comment]
Thanks for the follow up. That was a tough one to track down and verify.
