### ISSUE TITLE
javascript in feed item html interpreted as text, shows as 'first sentence' in article list

### ISSUE THREAD

**Issue by jrus** [Ranchero-Software/NetNewsWire#2920]
Here's a screengrab:

<img width="307" alt="Screen Shot 2021-03-27 at 1 32 15 AM" src="https://user-images.githubusercontent.com/83411/112715262-77bf4c00-8e9c-11eb-9a32-58c3c9c99f50.png">

Here's my test feed, https://endpointservice.web.app/notebooks/@jrus/feedtest2/recent

(It might not last)

Feed item content is like:

```html
<img id="thumbnail" src="static.observableusercontent.com/thumbnail/59471d35447804ee4ef582dd97f30cb5f95772047ee5de9d41fa3dcde1332643.jpg"></img>
<iframe id="embed" width="100%" style="height: 85vh; display: none;" frameborder="0" src=""></iframe>
<script>
const thumbnail = document.getElementById('thumbnail');
const embed = document.getElementById('embed');
thumbnail.onclick = () => {
  thumbnail.style.display = 'none';
  embed.style.display = 'block';
  embed.setAttribute('src', 'https://observablehq.com/embed/@mkfreeman/canvas-noise-field?cell=*') };
</script>
```

The idea is I want to show the thumbnail initially (loads fast), but then replace it with an embedded notebook when the thumbnail gets clicked.

I can easily change the feed to whatever would work. Is there any way to get a script (or other content) into the html of feed items without NNW thinking it constitutes the text content and trying to use it in the article list? Ideally I'd like to have no text preview in the article list at all for this feed.

* * *

Including `"summary": "", "content_text": ""` in the feed items does not seem to help.

**Comment by jrus** [comment]
I worked around this by putting the javascript in a separately served file.

**Comment by vincode-io** [comment]
I'm going to close this since it looks like you got it worked out. If we start having problems with incorrect content in the Timeline again, we can reopen this issue.

**Comment by jrus** [comment]
Arguably this is a bug either way; something inside a `<script>` tag shouldn't be taken as text.
