### ISSUE TITLE
Feedly RSS pull fails silently

### ISSUE THREAD

**Issue by agregov** [Ranchero-Software/NetNewsWire#2922]
Feedly's site was down for maintenance this morning (3-27-21 10am-noon PST). On the website they have a page up alerting users that the site is down (attached). NetNewsWire makes its RSS pull request and simple stay's silent if there's no returned feeds. It would be better to throw up a an error that Feedly RSS is not available. Not sure if their API supports any such functionality. Perhaps... 

state
Optional string only returned if the feed cannot be polled. 

https://developer.feedly.com/v3/feeds/

<img width="1016" alt="Screen Shot 2021-03-27 at 11 00 09 AM" src="https://user-images.githubusercontent.com/1413566/112731287-8f75ef00-8ef3-11eb-9036-c10ad7c16f0f.png">

**Comment by vincode-io** [comment]
We intentionally don't show you the errors when a scheduled feed refresh fails. This is so that we don't constantly annoy the user with messages they can't do something about. We do notify if you manually refresh.
