### ISSUE TITLE
[FR iOS] Image shown next to article before reading it

### ISSUE THREAD

**Issue by Hukuma1** [Ranchero-Software/NetNewsWire#2923]
Just found this app and paired it with FreshRSS. Working great, thank you!

Wanted to suggest a new feature/new layout option.

Currently it looks like this on iOS:
![netold](https://user-images.githubusercontent.com/54511555/112732967-69a01880-8efa-11eb-9174-f8b8b19a7244.png)

A quick mock up with article thumbnail and article origin below:
![netnew](https://user-images.githubusercontent.com/54511555/112733043-e0d5ac80-8efa-11eb-845b-761a4d0ccadb.png)

**Comment by vincode-io** [comment]
Duplicate of #1551.
