### ISSUE TITLE
"The data couldn’t be read because it isn’t in the correct format." when refreshing

### ISSUE THREAD

**Issue by marcoskirsch** [Ranchero-Software/NetNewsWire#2924]
Started this morning: whenever I try to refres on iPad or iPhone, I get the same error as #2765.
I don’t doubt something is serving an ill-formed RSS, but I’d expect NetNewsWire to skip it and keep on trucking. But instead, nothing refreshes.
![IMG_0352](https://user-images.githubusercontent.com/8085768/112734445-66615880-8f0b-11eb-9038-41a0c675c628.jpeg)

**Comment by vincode-io** [comment]
Are you using Feedly? It is down for maintenance right now.

**Comment by vincode-io** [comment]
Unless you let us know otherwise, I am going to assume this is the Feedly problem. There isn't anything we can do to make this better. The Feedly API is completely offline and returning an HTML page instead of parsable JSON.

**Comment by marcoskirsch** [comment]
Yes, that’s it!
Can’t wait to switch to your iCloud implementation :)
