### ISSUE TITLE
The data couldn't be read because it isn't in the correct format

### ISSUE THREAD

**Issue by garethflynn** [Ranchero-Software/NetNewsWire#2925]
Just updated to the new 6.0 release, refreshed my feeds, and got the following error message:

<img width="256" alt="image" src="https://user-images.githubusercontent.com/15660853/112736531-59fcf000-8f4b-11eb-8ea2-9464a7d3462d.png">

Everything was working fine in the previous release (I wasn't using a beta, so the last official 5.x release).

Something cached from the old version that the new version doesn't like? I've quit and restarted it and still got the same.

**Comment by vincode-io** [comment]
Feedly is down and returning invalid API responses.
