### ISSUE TITLE
Feature Request: app icon options

### ISSUE THREAD

**Issue by inklesspen** [Ranchero-Software/NetNewsWire#2926]
I just got the update that adds the Big Sur style icon. However, I'm not fond of icons changing, and I particularly dislike Big Sur's icon language. Can you add a preference to restore the previous icon?

**Comment by vincode-io** [comment]
We can understand why some don't like Big Sur's design language. Regardless, the NetNewsWire team works hard to match platform conventions and be good citizens in the Apple ecosphere. We think we've struck a good balance by using the old icons on Catalina and the new on Big Sur. We don't have any plans to provide a preference to go against platform conventions at this time.
