### ISSUE TITLE
Mac: Right-To-Left support in the browser

### ISSUE THREAD

**Issue by dkaluta** [Ranchero-Software/NetNewsWire#2927]
The current release of NetNewsWire for macOS, 6.0, does not support Right-To-Left scripts in the article view.
By adding `dir="auto"` to the `article` tag in the file `template.html`, a pretty basic support for RTL scripts can be added to NetNewsWire.

Included are pictures of two articles, one in Latin script (English), and the other in Hebrew script. 

![RTL](https://user-images.githubusercontent.com/11197909/112747663-6d49a300-8fbf-11eb-8c7d-e2de46fb964c.jpeg)
![LTR](https://user-images.githubusercontent.com/11197909/112747662-6a4eb280-8fbf-11eb-83bc-be56b7bfe15a.jpeg)

Here are the contents of the `template.html` file:

~~~
<header class="headerContainer">
	<table cellpadding=0 cellspacing=0 border=0 class="headerTable">
	<tr>
		<td class="header leftAlign"><span class="feedlink">[[feedlink]]</span><br />[[byline]]</td>
		[[avatars]]
	</tr>
	</table>
</header>

<article dir="auto">
<div class="articleTitle"><h1>[[title]]</h1></div>
<div class="[[dateline_style]]">[[date_medium]]</div>
<div class="externalLink">[[external_link]]</div>
<div id="bodyContainer" class="articleBody [[text_size_class]]">[[body]]</div>
</article>
~~~

**Comment by j-f1** [comment]
Feed URL: https://www.ha-makom.co.il/feed/

With a few minor tweaks to the CSS, it’s possible to automatically lay out the entire article section as RTL where relevant:
<img width="1274" alt="Screenshot_2021-03-28 17 27 11" src="https://user-images.githubusercontent.com/25517624/112768656-fd511200-8fea-11eb-9ae3-30a47e9ef674.png">


Would this be good to do or would the inconsistency of the header be annoying if you switch between RTL and LTR sources frequently?

**Comment by dkaluta** [comment]
Looks good actually. This pretty much exactly replicates Reeder's new RTL support (as seen here)

<img width="706" alt="Screen Shot 2021-03-29 at 9 45 25" src="https://user-images.githubusercontent.com/11197909/112797146-a4798c00-9073-11eb-8126-97264b4dac44.png">

Judging from the fact the iOS version also includes a `styleSheet.css`, a similar change can probably also be implemented in the iPhone build. 

With these changes, it would be possible for me to switch full-time from Reeder to NNW on all my devices.
