### ISSUE TITLE
Feed Issue: Objective-See

### ISSUE THREAD

**Issue by coffeewhisky** [Ranchero-Software/NetNewsWire#2928]
This has been a problem for some time, (not specifically NNW6) but whenever I add the Objective-See RSS feed, (macOS security software), all entries are retrieved with the same data/time; specifically the date and time I import the feed. This results in all the entries appearing in a somewhat random order.

I can't see anything obviously wrong with the feed itself: https://objective-see.com/rss.xml

It doesn't help the the two most recent entries have exactly the same published date, however the pubDates of the last couple of entries are:

- Sun, 14 Feb 2021 00:00:00 EST
- Sun, 14 Feb 2021 00:00:00 EST
- Tue, 5 Jan 2021 00:00:00 EST
- Fri, 1 Jan 2021 00:00:00 EST
- Thu, 10 Dec 2020 00:00:00 EST

From NetNewsWire 6:
<img width="370" alt="Screenshot 2021-03-28 at 13 31 58" src="https://user-images.githubusercontent.com/45566177/112752324-712ef280-8fca-11eb-8d7b-41851c28dcc1.png">

The feed xml:
<img width="335" alt="Screenshot 2021-03-28 at 13 36 37" src="https://user-images.githubusercontent.com/45566177/112752368-aafff900-8fca-11eb-84ac-b7b3485a29e7.png">

**Comment by stuartbreckenridge** [comment]
If you go further down that feed you'll come across some entries that have no `pubDate`, e.g.

```xml
  <item>
    <title>Weaponizing a Lazarus Group Implant</title>
    <link>https://objective-see.com/blog/blog_0x54.html</link>
    <description>The Lazarus group's latest implant/loader supports in-memory loading of 2nd-stage payloads. In this post we describe exactly how to repurposing this 1st-stage loader to execute *our* custom 'fileless' payloads!</description>
    <guid isPermaLink="true">https://objective-see.com/blog/blog_0x54.html</guid>
  </item>
```

In these cases, NNW uses the date the article _arrived_ in the app. That's why old articles appear new (or newer that actual new post). It's not so much an issue with NNW than it is an issue with the feed.

**Comment by coffeewhisky** [comment]
Ah, well spotted. I'll see if I can contact the feed owner. Thanks!
