### ISSUE TITLE
Slow update for some feeds in Mac 6.0 release (6026) on Intel with iCloud sync

### ISSUE THREAD

**Issue by dfsweeney** [Ranchero-Software/NetNewsWire#2929]
I installed 6.0, deactivated the local account, and set up iCloud sync, then imported an opml exported from the local account on iOS. When I refresh the refresh seems to be very slow for certain of the feeds. It will sit on "802 of 809" or whatever. 

There's nothing obvious in the system logs. 

Is it possible to view the log of what feeds are being refreshed when? I can't find any logs in like ~/Library/Application Support but I might be confused about this. Or is it possible to put the app in test mode? I updated it from the last beta using the in-app update and relaunch. 

The update eventually succeeds but after a long time. I am assuming that some of the feeds are timing out and that the timeout is just long, but that's still speculation because I can't really see what feed is what. (I guess I Gould watch the number change and then wait with a stopwatch to figure out the timeout.) The iOS version with local storage does not seem to hang like this. 

I have the source and have compiled the app in the past although I'm doing this with the released app. 

It might not be related to iCloud sync, I have not verified that yet. 

Any ideas to see what's going on to drill into this more would be helpful. I will keep looking at it. 

Thanks!

**Comment by vincode-io** [comment]
We now timeout the feeds after 30 seconds. Currently we don't support any analytics on feed responsiveness. With the large number of feeds you have, you might be seeing the uploads to iCloud take some time. Unfortunately they are restricted to a single connection and what ever speed Apple feels like giving us.

**Comment by dfsweeney** [comment]
This might be the issue, it is definitely taking more than 30 seconds for some of the feeds. Now that I have a complete refresh, a manual refresh (a few minutes after the beginning-of-day refresh) runs quickly. 

I will turn the app off and start it again tomorrow morning and see if it slows up again. It might be an artifact of having a lot of initial data to populate when refreshing iCloud from the empty condition. 

If this resolves itself I will follow up and close the bug, if it slows up again after 24 hours I will try to think about how to fix it up. I was thinking that there might be a bad feed in my list but after you say that and I get some fast clean refreshes I'm thinking it's more likely to be iCloud running slow.

**Comment by Thomas-U** [comment]
It also might be worth the effort to manually check all feeds for dead and unresponsive ones. I did that before migrating from local to iCloud on my production system.

**Comment by dfsweeney** [comment]
Ok, this looks good after leaving it for 24 hours and then refreshing this morning. The feeds refresh at normal speed now. I left it for 24 hours to make sure I had a significant number of new articles. This must be an issue with the initial refresh when there are a lot of feeds and a lot of data. I have about 800 feeds, I'm sure some of them are dead but some of them are also probably generating large responses also.

I'll close this one. Thanks for listening!
