### ISSUE TITLE
Feature Request: Add setting to disable the unread count in the Dock

### ISSUE THREAD

**Issue by superlopuh** [Ranchero-Software/NetNewsWire#2931]
It would be nice to have the app be open but not attract attention, a red badge on a messaging application is strongly associated with needing to check what the message was about, whereas NNW often hovers in the double-triple digits unread until there is time to go through whatever I've missed, it would be nice to have a toggle for the badge to disappear.

**Comment by brentsimmons** [comment]
System Preferences > Notifications > NetNewsWire - turn off “Badge app icon”
