### ISSUE TITLE
Starred and Unread UI indicators are not updated in search results or smart feeds on Catalina

### ISSUE THREAD

**Issue by tqml** [Ranchero-Software/NetNewsWire#2932]
I noticed that the unread/starred indicators are not updated in the UI if the selected article is displayed as a search result or displayed in the "Smart Feeds" section if

1. A local and an iCloud account is activated at the same time
2. The selected article is part of a feed which is contained in __both__ accounts

If this is the case, then the UI indicators only work for __one__ article - in my case it updates the article of the local account just fine, but refuses to update it for iCloud. However the in the underlying database the article gets marked accordingly only the UI stays out of sync with the data.

If the conditions above do not apply (e.g. if the local account is disabled in preferences) everything works just fine. I only noticed it when I tried to transfer all my Feeds to the iCloud account. First I exported my subscriptions from the local account to a file and then re-imported it into the iCloud account (maybe there is a better way to do that). I wanted to delete the local account but noticed that all starred articles were gone which I wanted to keep and hence discovered the bug.

## Steps to Reproduce

1. Make sure a local and iCloud Account is active at the same time
1. Type in a search query or select an article from the smart feeds section
1. make sure the article is part of a feed which is subscribed by both accounts (so there should be two articles with the same name)
1. The unread/starred indicators should only update for one of the two articles

## System Infos

NetNewsWire Version 6.0 (6026)
macOS Catalina 10.15.7 (19H524)

## Demo

The video demonstrates the bug. The iCloud article (top) does not update the UI indicators while the article stored in the local account (bottom) reflects the changes accordingly.

https://user-images.githubusercontent.com/16613048/112766704-31402d80-9013-11eb-9dc6-a3eacd2d0afd.mov

**Comment by vincode-io** [comment]
Thanks for the excellent bug report. We've identified the issue and there is a fix for this coming in the 6.0.1 release.

**Comment by tqml** [comment]
Happy to help! Thank you for NetNewsWire!
