### ISSUE TITLE
NetNewsWire 6.0 for Mac: Newly added feeds show as "Untitled" until feeds are refreshed

### ISSUE THREAD

**Issue by stefandesu** [Ranchero-Software/NetNewsWire#2939]
After adding a new feed, the name is first shown as "Untitled" until the feeds are refreshed or the application restarted. See screen capture below:

https://user-images.githubusercontent.com/3275148/112796755-b4d93900-906a-11eb-95cb-2f8deb61fba0.mov

By the way, NNN is a wonderful app! I've procrastinated on trying it out because I wanted iCloud sync, but I didn't have that excuse anymore now that 6.0 is out. Great job!

**Comment by vincode-io** [comment]
What is the URL of the feed that this is happening with?

**Comment by stefandesu** [comment]
> What is the URL of the feed that this is happening with?

Hmm, I assumed it was happening with all feeds, but I guess it's an issue with my feeds:
- https://coli-conc.gbv.de/rss/blog.xml (work project)
- https://exo.pm/feed.xml (personal blog)

It's still kind of weird that the name shows up after a refresh, so it might still be worth looking into it. (I tried other feeds, but it doesn't happen then. Or rather, it shows "Untitled" for a split second before it changes to the actual feed name.)

**Comment by vincode-io** [comment]
I found the bug that was causing this and the fix is coming in 6.0.1.
