### ISSUE TITLE
Enhancement request: No unread count on dock icon

### ISSUE THREAD

**Issue by joncallas** [Ranchero-Software/NetNewsWire#2940]
That's pretty much it -- it would be nice not to have the number of messages unread.

**Comment by vincode-io** [comment]
System Preferences > Notifications > NetNewsWire - turn off “Badge app icon”

**Comment by groue** [comment]
Is it possible to hide the unread count badge on the iOS app icon as well?

**Comment by kevinm6** [comment]
> Is it possible to hide the unread count badge on the iOS app icon as well?

The same like on macOS:
 1. Open NNW
 2. Settings NNW (gear icon on bottom left)
 3. Open System Settings (first menu item)
 4. Notifications
 5. Badges -> OFF
 
![IMG_5894](https://user-images.githubusercontent.com/72861758/126754325-666ae120-6c05-4cc2-8841-3195ec0a1b89.PNG)

**Comment by groue** [comment]
Thank you very much!
