### ISSUE TITLE
Enhancement request: Reader view on by default

### ISSUE THREAD

**Issue by joncallas** [Ranchero-Software/NetNewsWire#2941]
Right now it's off by default. Reader view is amazing and wonderful. I have wanted it for years and it keeps me from having to go to the browser. I'd like to have that be my normal way of reading.

**Comment by vincode-io** [comment]
We don't encourage people to use it unless it is necessary. It puts a strain on the Reader View service we use and unnecessary does network requests for most blogs. You can enable it on a per feed basis if you want to.
