### ISSUE TITLE
Next Unread no longer wraps around

### ISSUE THREAD

**Issue by Alfred-von-Campe-Bose** [Ranchero-Software/NetNewsWire#2942]
Since upgrading to version 6.x, the Next Unread keyboard short cut no longer wraps around when you get to the end of the (alphabetical) list of feeds.  This worked in all prior versions (5.x and 4.x) that I've previously used.

**Comment by MrNoodle** [comment]
To add to this, the menu item is greyed out. Screenshot demonstrating the issue:

<img width="284" alt="nnw" src="https://user-images.githubusercontent.com/132801/112852135-a1819a00-9079-11eb-815e-05df6972f955.png">

**Comment by vincode-io** [comment]
Found the bug and it will be fixed in 6.0.1.
