### ISSUE TITLE
Folder with Twitter and Reddit feeds shows read articles in timeline

### ISSUE THREAD

**Issue by Thomas-U** [Ranchero-Software/NetNewsWire#2944]
I have all my Twitter and Reddit feeds in one folder.

When I select this folder in the sidebar all articles are shown, including the read (dating back to when I added the feeds in February).

All other folders show just the unread articles when selected.

NNW 6.01b1, macOS 11.2.3  · MacMini M1

**Comment by vincode-io** [comment]
Did you toggle off the Read Articles Filter?

**Comment by Thomas-U** [comment]
my bad, I had forgotten that that exists, sorry!
