### ISSUE TITLE
After updating to 6.0 no article content shown

### ISSUE THREAD

**Issue by raudpats** [Ranchero-Software/NetNewsWire#2948]
After updating to 6.0 article content is not shown any more. Sidebar and articles list work properly, but no articles shown. Tried to update to 6.0.1b2 and downgrade to 5.1.3 but still nothing. Before upgrading all worked just fine.
I'm on MacOS 10.15.7

**Comment by vincode-io** [comment]
Could you do me a favor please and post a screenshot of what this looks like?

**Comment by raudpats** [comment]
<img width="579" alt="image" src="https://user-images.githubusercontent.com/16715875/112990529-d91e3e00-916e-11eb-9c5f-45543f19be43.png">
Just grey area.

**Comment by vincode-io** [comment]
Have you tried rebooting your computer?

**Comment by brentsimmons** [comment]
Is this in fullscreen mode?

**Comment by raudpats** [comment]
No, this is window. But in fullscreen same.

**Comment by vincode-io** [comment]
@raudpats Did you ever get this resolved?

**Comment by raudpats** [comment]
No. This is working just fine on another computer but here still same situation.

**Comment by raudpats** [comment]
So I tried once more different moves, including removing app totally and reinstalling and then this started to work. So right now all good.
