### ISSUE TITLE
Twitter feed in Reader view shows Javascript warning message

### ISSUE THREAD

**Issue by antwake** [Ranchero-Software/NetNewsWire#2949]
If I toggle the reader view when viewing a tweet, it says "We’ve detected that JavaScript is disabled in this browser. Please enable JavaScript or switch to a supported browser to continue using twitter.com. You can see a list of supported browsers in our Help Center."

MacOs Catalina 10.15.7 / NetNewsWire 6.0 (6026)

<img width="702" alt="Screen Shot 2021-03-30 at 10 12 06" src="https://user-images.githubusercontent.com/630800/113003620-e6bccf00-9140-11eb-86ec-7477ed608b75.png">

**Comment by vincode-io** [comment]
Right. Twitter is strict about how its website is accessed and doesn't work with Reader View.

What are you trying to accomplish by using Reader View with a tweet? The full text of the tweet is right there.

**Comment by antwake** [comment]
I wasn't trying to accomplish anything 🙂
You're right, we don't need the reader view for Twitter. I was just walking around the new UI.
