### ISSUE TITLE
Add support for Twitter feeds that include replies

### ISSUE THREAD

**Issue by peternlewis** [Ranchero-Software/NetNewsWire#2950]
I would like to get all the tweets from a specified user **including tweets that are replies to other people**.

Currently, the feed does not seem to include replies, and I'd like to see all tweets from the user.

Thanks.

**Comment by peternlewis** [comment]
It looks like a Twitter Search feed for `(from:USERNAME)` will result in the tweets including replies, so that seems like an interim solution.

**Comment by GymRat102** [comment]
Thanks for this quick solution. But it's really sad non-default url won't bring the profile pic to the feed when subscribe, which I think is a big loss interms of experience.

**Comment by brentsimmons** [comment]
Since Twitter integration will stop working soon — as soon as Twitter ends free Twitter API access — I’m closing this.
