### ISSUE TITLE
The "l" key now acts inconsistently in version 6 (6.0.1b2 (6029))

### ISSUE THREAD

**Issue by proteanswamp** [Ranchero-Software/NetNewsWire#2952]
In Version 5 striking the "l" key would mark all posts as read and move to a new subgrouping. It now works *sometimes*, often moving to the next unread message instead, and requiring a second keypress. This appears inconsistently.

**Comment by vincode-io** [comment]
This has been fixed and will be in the upcoming 6.0.2 release.

**Comment by ednl** [comment]
Thanks for the fix. It is now broken in a different way, though: when there are no more unread articles in a feed, L doesn't jump to the next feed.
