### ISSUE TITLE
Article repeatedly marked as read on sync

### ISSUE THREAD

**Issue by mcclurgm** [Ranchero-Software/NetNewsWire#2953]
I've come across an issue today where one article (at least only one that I've noticed) is repeatedly marked as read by NetNewsWire every time the app syncs. I can mark it as unread, but then as soon as I back out of the list I'm viewing and back in, or I manually refresh the feed, or NNW refreshes itself in the background, the article gets marked as read again. Here's a video of what happened:

https://user-images.githubusercontent.com/29022469/113185697-feb15300-9213-11eb-9d4e-5fbbc7473747.mp4

I have only noticed it happening to this one article, although it's possible that it's affecting other articles that I just didn't notice (I spend almost all my time in the unread filter, so any articles marked as read are out of sight out of mind for me).

This feed is in my Feedly sync account, running NNW for iOS version 5.0.5 (build 56). I have verified that in Feedly's web view, the offending article is marked as read.

**Comment by mcclurgm** [comment]
I just deleted and re-added my Feedly account from the app, following a suggestion on the Slack. I tried this a few times and the article always went back to unread, but I backed out of the list and marked a few other articles in other feeds (also Feedly) as read or unread to test. When I came back, the article is behaving as expected.

**Comment by brentsimmons** [comment]
Is this still a bug?

**Comment by mcclurgm** [comment]
I'm not sure. I haven't seen it since, but I only ever saw it in this one case, and the article has long since fallen off the end of the feed. Sorry I can't be more helpful there!
