### ISSUE TITLE
Add new account dialog too tall (covered by Dock)

### ISSUE THREAD

**Issue by mattgarber** [Ranchero-Software/NetNewsWire#2955]
The popover dialog that appears after clicking the "+" button in Preferences > Accounts seems too tall, as the bottom runs under the Dock at the default resolution on a retina MacBook Pro 13" (1600px tall). This is exacerbated by the fact that since it's a window-modal popover, it can't be resized or dragged out of the way to use.

NetNewsWire Version 6.0 (6026) on macOS Big Sur (11.2.3), MacBook Pro (Retina, 13-inch, Mid 2014).

<img width="887" alt="nnw-add-account" src="https://user-images.githubusercontent.com/11002754/113209701-616d1380-9241-11eb-9777-5e100de814b0.png">

**Comment by vincode-io** [comment]
This was fixed in 6.0.1.
