### ISSUE TITLE
macOS: SmartFeed icons are incorrectly sized when sidebar icon size is set to Large

### ISSUE THREAD

**Issue by stuartbreckenridge** [Ranchero-Software/NetNewsWire#2957]
When the sidebar icon size is set to Large via System Prefs, the Today and All Unread icons are displayed as their Small equivalent. (When sidebar icon size is Small or Medium everything seems OK.)

![sidebar-icons-large](https://user-images.githubusercontent.com/7046652/113264266-5aa7d480-9305-11eb-8768-552f77c976ff.jpg)

**Comment by vincode-io** [comment]
This has been fixed and is in the 6.0.1 upcoming release.
