### ISSUE TITLE
Feature request: Per-feed refresh times

### ISSUE THREAD

**Issue by dlnash18** [Ranchero-Software/NetNewsWire#2959]
I joined GitHub just to submit this feature request, so please excuse any noob-iness.

I have one feed that I'd like refreshed very often (it's for important, time-sensitive notifications), with all the others refreshed in a more leisurely manner. There doesn't seem to be a per-feed refresh setting, or if there is I can't find it. And I also couldn't find any issue tagged with "feature request" about it, which strikes me as a bit unexpected for what seems like a pretty obvious feature.

In case it matters, I'm using the Mac version (6.0, of course), but I see no reason why this should be a Mac-only feature. And the important feed in question is Twitter rather than RSS.

**Comment by vincode-io** [comment]
Thanks for the suggestion and thanks for joining GitHub to make it.

I can see how this might be useful in this one edge use case. However, it would cause all kinds of additional complexity in the application. We would have to have individual timers for each feed to know when they are scheduled to go off. This could number in the thousands where as we have only one right now.

We would also have to change the user interface to allow you to change each feed's refresh interval. This setting, which would only in the rarest of occasions, could confuse new users. One design goal with NetNewsWire is to make it as stress free as possible for users. We don't want novice users to be struggling with the question of if they should be going through all their feeds to set this or not.

Finally, we have to do a cost/benefit analysis. This is a completely volunteer effort and time is cost. We need to focus on features that provide benefit to the most users. I don't think this one fits that description.

In the most long winded way, I think I've communicated that we probably aren't ever going to implement this. I hope this doesn't discourage you from making bug reports and feature requests in the future. We always welcome community engagement.

**Comment by dlnash18** [comment]
I was thinking that the per-feed timer would be optional, not mandatory. In the absence of a timer on a feed, the default timer would be used. So you only need as many timers as there are feeds with individual timers set on them. This isn't something I'd expect to get applied to very many feeds.

Regarding the UI and user confusion issues, since the per-feed timer is optional, you simply don't expose it in the new feed dialog. Put it only in the info panel and clearly label it as optional. People who don't need it won't go looking for it. People who stumble across it in the info panel will see it labeled as optional, and will hopefully have the good sense not to mess with it if they don't need it.

**Comment by dlnash18** [comment]
Alternatively, you could have just two timers: default and high priority. Again, you leave it out of the new feed dialog, and put a pop-up menu (or whatever widget you think appropriate), in the info panel to select which timer to use. Now you're managing only two timers instead of one, not a potentially unlimited number.
