### ISSUE TITLE
Scroll Bars Disappear When Resizing NNW Window in Mac OS

### ISSUE THREAD

**Issue by dvincent747** [Ranchero-Software/NetNewsWire#2961]
On my Mac, I have the system preferences set to always show scroll bars (versus the default of hiding them and only displaying them on mouse over). In Mac OS, NetNewsWire 6.0's scroll bars disappear while the window is being resized. Once you're done resizing and release the mouse button, they will reappear. It's admittedly a very minor flaw, but it is distracting when resizing the window. If scroll bars are "always on," they should stay visible when dragging to resize the window like other Mac OS apps.

**Comment by stuartbreckenridge** [comment]
This is intentional behaviour.

**Comment by dvincent747** [comment]
Fair enough!
