### ISSUE TITLE
Clear All Unread list

### ISSUE THREAD

**Issue by jbrodriguez** [Ranchero-Software/NetNewsWire#2962]
When I've read all the items in the list, I'd like no article to display

I'm using `cmd+'` but it still displays the current (last) item

![Screen Shot 2021-04-02 at 09 13 04](https://user-images.githubusercontent.com/1305422/113423321-e5cfab80-9393-11eb-9b6d-15e37c0ae3f6.png)

Ideally, when `down arrow` wants to go past the last unread item, it should clear the list

Thoughts/suggestions ?

**Comment by vincode-io** [comment]
We never clear the selected article because the user is probably reading that article and it is super annoying to lose an article that you are reading. If you want an empty Timeline, you can click the selected article while holding command to deselect it before hitting `cmd+'`.

**Comment by kevinm6** [comment]
> We never clear the selected article because the user is probably reading that article and it is super annoying to lose an article that you are reading. If you want an empty Timeline, you can click the selected article while holding command to deselect it before hitting `cmd+'`.

It could be possible add even “esc” press to clean the selection of an article?
