### ISSUE TITLE
NetNewsWire doesn’t honour default iOS browser

### ISSUE THREAD

**Issue by OddHouseGames** [Ranchero-Software/NetNewsWire#2963]
Unless I missed it, clicking on an article title in iOS opens Safari instead of honouring default browser, which I use the DuckDuckGo browser.

**Comment by vincode-io** [comment]
Clicking on the title will alway open the in-app browser which is Safari based.

If you want to open an external browser, you can do that through the share menu. Just pick the "Open in Safari" option and it will open the default browser. We have renamed this option to "Open in Browser" in the upcoming 6.0 NNW for iOS release.
