### ISSUE TITLE
Search with Google opens wrong browser

### ISSUE THREAD

**Issue by yaronf** [Ranchero-Software/NetNewsWire#2964]
Running NNW 6.0.1 on Big Sur. Right click on a word in an article, and press "Search with Google". This opens Safari instead of my default browser (Firefox).

**Comment by vincode-io** [comment]
This is just how the Mac works and doesn't have anything to do with NetNewsWire.

If you want to change this behavior, here are some options. 

https://apple.stackexchange.com/questions/10999/search-in-google-always-open-safari-instead-of-default-browser

https://stackoverflow.com/questions/17935301/how-to-force-mac-os-to-open-search-with-google-in-chrome
