### ISSUE TITLE
Long press menu on folders is cut off in zoomed mode on iOS

### ISSUE THREAD

**Issue by OddHouseGames** [Ranchero-Software/NetNewsWire#2965]
When using iOS 'zoomed' mode for accessibility, the long press menu when you hold on a folder is cut off![image](https://user-images.githubusercontent.com/62911518/113465361-624ca380-9401-11eb-8f7f-032d84d67ac1.jpeg)

**Comment by stuartbreckenridge** [comment]
This appears to be fixed in the upcoming 6.0 release.

![8C488D43-5A6E-4019-B556-0411DB2292FB](https://user-images.githubusercontent.com/7046652/113474707-261e4f00-94a4-11eb-92d1-d110b4228103.jpeg)
