### ISSUE TITLE
(ios) app has cache problem

### ISSUE THREAD

**Issue by zmulk** [Ranchero-Software/NetNewsWire#2969]
The app downloads alot of cache on the iphone. There should be a way to remove or empty the cache?

**Comment by vincode-io** [comment]
iPhone's automatically clears up application caches as needed. 

If you are talking about the articles database, that gets cleaned up automatically as well. We spent a lot of time working out the best way to clean up the articles database and feel this is the best balance between article availability and storage consumed.

https://github.com/Ranchero-Software/NetNewsWire/blob/main/Technotes/RetentionPolicy.markdown
