### ISSUE TITLE
Article view stops rendering

### ISSUE THREAD

**Issue by mpolden** [Ranchero-Software/NetNewsWire#2971]
Steps to reproduce:
1. Select "All Unread" (with approximately 50-100 unread items).
2. Select top-most article,
3. Navigate to next article with down arrow.

This works fine for maybe 10-30 articles, but then article view stops rendering the selected article. It keeps showing the last selected article before the bug triggered. The only workaround is to restart NetNewsWire.

Edit: It may happen because I navigate to the next article without letting the previous one completely load (e.g. article has big images that load slowly).

NetNewsWire 6.0.1 (but I also observed this on the last 5.x release)
macOS 11.2.3

**Comment by Thomas-U** [comment]
I tried to reproduce this but could not. 

NNW 6.0.1, 11.2.3 on M1

**Comment by brentsimmons** [comment]
Could we get a screenshot of what it looks like when this happens?

**Comment by mpolden** [comment]
Sure, I can take a screenshot the next time it happens.

**Comment by mpolden** [comment]
I managed to trigger the bug again:

![Screenshot](https://mpolden.no/2021-04-10_nnw_bug.png)

 I also [recorded my screen](https://mpolden.no/2021-04-10_nnw_bug.mov).

**Comment by mpolden** [comment]
I can no longer reproduce this issue.
