### ISSUE TITLE
[Mac] [6.0.1] Feature request: a way to prevent autoplay video and/or auto-mute them

### ISSUE THREAD

**Issue by ednl** [Ranchero-Software/NetNewsWire#2973]
I don't think there is a way right now to prevent HTML5 videos from autoplaying. I encountered this today on https://www.raspberrypi.org/feed/ which has two video tags with an autoplay attribute in the article tagged as

```
<pubDate>Thu, 08 Apr 2021 08:19:30 +0000</pubDate>
<guid isPermaLink="false">https://www.raspberrypi.org/?p=69281</guid>
```

The video tags are like:` <video autoplay controls loop src="https://link-to-video-mov"></video>`. I would very much like a way to prevent videos autoplaying in NetNewsWire, like Safari does. Thanks for your work!

**Comment by vincode-io** [comment]
This is fixed. It will be in the 6.1 release of NetNewsWire.

**Comment by ednl** [comment]
Thanks!
