### ISSUE TITLE
Disable Reader View for Feed Provider sourced WebFeeds

### ISSUE THREAD

**Issue by stuartbreckenridge** [Ranchero-Software/NetNewsWire#2976]
Disabling Reader View for Feed Provider feeds will stop the Twitter JavaScript warning message from appearing.

In `WebFeed`: 

- [x] Add a property to determine if `WebFeed` is a `FeedProvider`
- When the above property is `true`, the below behaviours should be observed: 
- [x] `isArticleExtractorAlwaysOn` should always return `false` and cannot be set to `true`

On macOS:

- [x] Remove Reader View from Sidebar Context Menu
- [x] Disable Reader View in Feed Inspector
- [x] Disable Reader View in Toolbar when first selected timeline item is a Feed Provider article

On iOS

- [x] Disable Reader View in Feed Inspector
- [x] Disable Reader View in Toolbar when selected article is a Feed Provider article

**Comment by vincode-io** [comment]
Looks like we forgot to close this one.
