### ISSUE TITLE
Adding Twitter extension from NNW 6.0 Settings resulted in a modal error message

### ISSUE THREAD

**Issue by heckj** [Ranchero-Software/NetNewsWire#2984]
I just jumped on the TestFlight beta for 6.0 (600), and did the following:
1) disabled the "On My iPhone" account
2) enabled iCloud (and confirmed "Use iCloud")
3) noticed "Extensions" underneath there, and selected "Add Extension"
4) choose Twitter
5) read the content and choose "Enable"

I get a modal error message at that point (screenshot included):

**Error**
The operation couldn't be completed. (OauthSwiftError -11.)

![IMG_3449](https://user-images.githubusercontent.com/43388/114318449-d0f4c580-9ac1-11eb-8a45-93f95c7a8093.PNG)

I have twitter on this phone, with background refresh disabled - not sure what else might impact it, but happy to connect to Xcode, capture and share logs, etc, if that would help.

Apologies if this is a known issue, I didn't spot it when I checked a second ago, but I didn't search exhaustively

**Comment by brentsimmons** [comment]
I think it’s a configuration issue on my build machine.

**Comment by calebhailey** [comment]
Sounds like you might already have an idea what the issues is, but just in case it helps I'm seeing this as well on iPad and iPhone. 

Thanks for NNW! ❤️

**Comment by rizwankce** [comment]
Works fine on Test flight build 601 👍🏽
