### ISSUE TITLE
Updated x m/h ago: when last refreshed

### ISSUE THREAD

**Issue by Duckbilled** [Ranchero-Software/NetNewsWire#2988]
The new iOS app shows the updated time as when an article was last fetched, but this feels a bit strange as I want to know when it was last checked for new articles.

**Comment by vincode-io** [comment]
The updated field shows the time the account successfully updated, not the last time we attempted a sync. It is this way so that it doesn't look like you have been successfully updating if you weren't. For instance if you didn't have an internet connection.
