### ISSUE TITLE
Request Feature: Add feature to enable sync between web feed options

### ISSUE THREAD

**Issue by kevinm6** [Ranchero-Software/NetNewsWire#2989]
I think could be useful add the feature to enable/disable sync of options for a web feed, at least with iCloud Sync.
I’m speaking about “Show Notifications…” and “Always Use Reader View” that sync between iOS and macOS.

**Comment by vincode-io** [comment]
Duplicate of #2739

**Comment by kevinm6** [comment]
Sorry, I didn't see it. 
The request is the same one.
