### ISSUE TITLE
Command to mark as read articles newer than selected article

### ISSUE THREAD

**Issue by jsit** [Ranchero-Software/NetNewsWire#299]
I read in reverse order (newest first), so often I want to mark as read all the articles "above" (newer than) where I'm currently scanning.

**Comment by jsit** [comment]
It would be great if this were in the right-click menu while holding "Option" -- turn "Mark Older as Read" to "Mark Newer as Read".

**Comment by brentsimmons** [comment]
We should be able to mark articles above and below.

**Comment by vincode-io** [comment]
@brentsimmons Isn't this one the same as #1485?

**Comment by brentsimmons** [comment]
Yes, it’s the same.
