### ISSUE TITLE
iOS > NNW6 > iCloud Sync : delay on mark all as read

### ISSUE THREAD

**Issue by kevinm6** [Ranchero-Software/NetNewsWire#2992]
As shown in the screen recording, there’s a small delay until the badge of Unread items disappear (or it’s updated?) with iCloud Sync on iOS.
This is not happening on macOS version with the same account.

https://user-images.githubusercontent.com/72861758/114431653-08499c00-9bc0-11eb-8a94-60faa1f14515.mp4

**Comment by kevinm6** [comment]
For now it isn't creating a usability problem!
I just wanted to report a strange behavior, maybe related to something in the iOS version.

**Comment by vincode-io** [comment]
The iOS and Mac versions are architected differently. Some differences in performance should be expected. I'm going to close this since it is more of an observation than an issue.

**Comment by brentsimmons** [comment]
I’m re-opening this. I’d like to get this faster.

**Comment by vincode-io** [comment]
If we make it faster the cell reload cancels our selection fade animation and the row stays blue.

**Comment by vincode-io** [comment]
That or the selection fade animation doesn't happen. I can't remember which. I do know that we have problems with the cell fade animation hanging around if we don't serialize access to the `UITableView` using `MainThreadOperation` which is why you are seeing a slight delay.

**Comment by kevinm6** [comment]
@vincode-io I think in that way, it emulates macOS (that okay has a pointer) so it doesn't clear the "selection" when "mark all as read" is invocated for a folder or web feed or smart feeds

**Comment by kevinm6** [comment]
> That or the selection fade animation doesn't happen. I can't remember which. I do know that we have problems with the cell fade animation hanging around if we don't serialize access to the `UITableView` using `MainThreadOperation` which is why you are seeing a slight delay.

How much possible can you increase the fade out animation?

**Comment by vincode-io** [comment]
None. Changing the layer speed causes other rendering artifacts.

**Comment by kevinm6** [comment]
How is possible that now trying this, on almost 10 folders, on 2 it updates the badge instantly on "Feeds" page?

Probably a stupid idea/question: could it be possible to add the fade animation even to the unread badge?
