### ISSUE TITLE
L key not marking all items in timeline as read

### ISSUE THREAD

**Issue by karan301** [Ranchero-Software/NetNewsWire#2993]
Summary:
L key not marking all items in timeline as read.

Steps to Reproduce:
1. Connect keyboard to iPad.
2. Open NNW.
3. Go to a feed with multiple articles.
4. Press the L key.

Expected Results:
The L key is supposed to Mark All as Read in Timeline and Go to Next Feed.

Actual Results:
Current article is marked as read, and next article _in the same feed_ is selected.

Regression:
I’m noticing this issue on the NNW 6.0 beta. It did not reproduce with the App Store version.

**Comment by Thomas-U** [comment]
iOS or Mac?

on Mac: K is the key you want.

**Comment by karan301** [comment]
I’m seeing this on iPadOS - should have specified. I use the L key pretty consistently with NetNewsWire on iPad, so I’m confident it’s a recent regression with the TestFlight beta.

**Comment by brentsimmons** [comment]
Thanks, Karan. L is defined as “Mark all as read, go to next unread” — and so this sounds like a regression..

**Comment by vincode-io** [comment]
This regression had been fixed and will be in the next TestFlight beta.

**Comment by karan301** [comment]
I updated to the latest TestFlight beta (601) and confirmed that this is resolved. Thanks!
