### ISSUE TITLE
Extensions Auth Dialogue When Adding iCloud to a Device For the First Time

### ISSUE THREAD

**Issue by stuartbreckenridge** [Ranchero-Software/NetNewsWire#2998]
**Scenario**:

- The user enables the iCloud account on their Mac
- The user enables and authorises one of the Twitter/Reddit extensions
- The user adds a feed from one of the extensions (e.g. Reddit Popular)
- Reddit Popular starts syncing happily on their Mac

Then:

- The user enables the iCloud account on their iOS device
- On the face of it, Reddit Popular will appear to be working because a) it appears; and b) new posts will appear because it’s syncing Reddit posts via their Mac, until the Mac is turned off or NetNewsWire is closed
- The user will not be aware that their Twitter or Reddit feeds are not authorised on their iOS device

I think we need to display an authorisation alert when the app detects that a feed provider feed has been added and it’s not been authorised for use.

**Comment by vincode-io** [comment]
How will we determine the difference between a feed provider feed and a regular one when the Extension isn't enabled? A valid Reddit RSS feed will come up as a false positive if we use inactive Extensions to test the feeds.

**Comment by stuartbreckenridge** [comment]
If I understand Reddit correctly, any feed URL that contains both `www.reddit.com` and `.rss` can be added to NetNewsWire and doesn't require authorisation. (If that's wrong, then the below won't work.)

```swift
let redditURL1 = "https://stuarticus@www.reddit.com/best" // requires authorisation
let redditURL2 = "https://www.reddit.com/r/flightsim/best" // requires authorisation
let redditURL3 = "https://www.reddit.com/r/flightsim/best/.rss" // does not require authorisation

let arr = [redditURL1, redditURL2, redditURL3]

let redditRegex = try! NSRegularExpression(pattern: "(www\\.reddit\\.com(?!.*\\.rss))", options: .caseInsensitive)

func requiresAuthorisation() -> [Int] {
    var results = [Int]()
    for u in arr {
        results.append(redditRegex.numberOfMatches(in: u, options: [], range: NSRange(location: 0, length: u.count)))
    }
    return results
}


print(requiresAuthorisation()) // expected [1,1,0]
// results = [1,1,0]
```

**Comment by vincode-io** [comment]
I think that will work. If Twitter ever add RSS feeds, we can probably add something similar.

**Comment by stuartbreckenridge** [comment]
@vincode-io I am actually thinking that this validation should be run on each refresh because a user can remove an extension and its associated feeds will continue to exist (but not update). So it would be tracked during a refresh and something could be presented to the user after `AccountRefreshDidFinish`...
