### ISSUE TITLE
iOS & macOS: strange sync behavior with iCloud account

### ISSUE THREAD

**Issue by kevinm6** [Ranchero-Software/NetNewsWire#3000]
Devices specs:
 • iOS       14.4.2   |   **NetNewsWire 6.0**   (build 601)
 • macOS 11.2.2   |   **NetNewsWire 6.0.1** (build 6030)
 • NetNewsWire sync with **iCloud Account**

Steps I’ve done to create the issue:
  - iOS       > Rename a Folder
  - iOS       > Refresh all the Feeds
  - macOS > Delete iCloud Account
  - macOS > Re-add iCloud account
  - macOS > Refresh all the Feeds

As is visible in the screenshots below, on macOS version of NNW, it shows two folders (with the previous and updated name) but one of them is not increasing the unread count and is not present on iOS.
It stays there even after a relaunching the app.

**NNW iOS**
![IMG_5669](https://user-images.githubusercontent.com/72861758/114674190-43a2b280-9d07-11eb-9992-c078ea850a57.PNG)

**NNW macOS**
![Screenshot 2021-04-14 at 09 30 07](https://user-images.githubusercontent.com/72861758/114674195-456c7600-9d07-11eb-9fe5-e5d0130e2fd5.jpg)

**Comment by nano9g** [comment]
I'm seeing something very similar - my folders and feeds are different on Mac and iOS. In case it's significant, I just migrated from Feedbin to iCloud today:
1. On iPhone:
     1. Exported Feedbin subscriptions
     2. Disabled Feedbin
     3. Enabled iCloud
     4. Imported subscriptions
     5. Moved to folders
2. On Mac, after iPhone:
     1. Disabled Feedbin
     2. Enabled iCloud
     3. Folders showed up but one that didn't match iPhone remained. That folder also contains feeds that aren't on iPhone.

**iOS**
![DAC39BB5-FD65-4259-9052-C62DD10AF0D4](https://user-images.githubusercontent.com/11694945/115084439-c3727d80-9ebd-11eb-8115-37bcf8e63aaa.jpeg)

**Mac**
![BCA1428F-781D-4BE7-A0EC-7B488303C34F](https://user-images.githubusercontent.com/11694945/115084814-41cf1f80-9ebe-11eb-8797-3edd7fe9f757.jpeg)

Let me know if this is the same issue or if I should open a new one.

**Comment by nano9g** [comment]
I activated iCloud on my iPad and it picked up the same feeds and folders as the Mac. I then removed and re-added iCloud on my iPhone and it now matches the other two, and changes are being synced properly.

**Comment by vincode-io** [comment]
@kevinm6 Are you still able to recreate this? I just tried it and wasn't able to in the latest builds.

**Comment by kevinm6** [comment]
@vincode-io Yes, I’ve just tried and I’m able to recreate it. 
iOS        : NNW 6.0 (b 602) 
macOS : NNW 6.0.2 (b 6032)

1. iOS > Rename a Folder
2. iOS > Refresh all the Feeds
3. macOS > Delete iCloud Account
4. macOS > Close NNW 
5. macOS > Re-add iCloud account
6. macOS > Refresh all the Feeds

**Comment by vincode-io** [comment]
@kevinm6 Do you still have the duplicated folders on your Mac? If so, could you please deactivate then activate your iOS account? That should tell us if we have duplicate folders in the iCloud account.

**Comment by kevinm6** [comment]
iOS : NNW 6.0 (b 603)
macOS : NNW 6.0.3b1 (6033)

I don’t have now, because the other times I remove them manually.
But I’ve just did what you ask for and I’m not seeing any duplicate.

Now I remember one thing, sorry for didn’t tell you before: 
I’ve notice that if I delete the duplicate without unread badge it removes after both the duplicates, even the one with unread badge after a refresh on both macOS and iOS.
Fortunately I have always a “opml” backup.

**Comment by kevinm6** [comment]
@vincode-io 

iOS 15.1 - NNW 6.0.2 (Build 610)
macOS 12.0.1 - NNW 6.0.3 (Build 6035)

I’ve just tried again to reproduce this issue but is not happening anymore.
For me it can be closed.

**Comment by vincode-io** [comment]
Yeah, I'm not sure what was happening there. If we see it again, maybe we can track it down.
