### ISSUE TITLE
Getting "Too Many Requests" error with Inoreader

### ISSUE THREAD

**Issue by DrTacoMD** [Ranchero-Software/NetNewsWire#3001]
I added my Inoreader account to NNW 6 on my Mac yesterday, and all was going well until this morning when I tried doing the same from my iPad (running the NNW 6 TestFlight). At first it successfully synced all of my feeds, but now NNW on all of my devices show some variant of the "Too many requests" error:

<img width="372" alt="Screen Shot 2021-04-14 at 9 09 02 AM" src="https://user-images.githubusercontent.com/4934719/114742983-16eb9c80-9d01-11eb-9673-993f4a19121b.png">

I only have ~30 feeds, so I don't think I'm really pushing the boundaries of usage patterns.

**Comment by vincode-io** [comment]
That error happens when all users of NetNewsWire combined have exceeded the API limit. I just tested it and it seems to be working fine now. In the past Inoreader has had to bump that limit up for us.

Is it working for you now?

**Comment by Lotz0711** [comment]
I'm getting the same error with Inoreader right now. 

![4A39D255-143F-4B9A-839C-5AAF7D5A4204](https://user-images.githubusercontent.com/82537582/114760676-e129d080-9d5f-11eb-8adf-ecd4553e6223.jpeg)
![B4BFA336-13AD-4186-8D21-664049CA3699](https://user-images.githubusercontent.com/82537582/114760695-e6871b00-9d5f-11eb-910f-55b09678aebd.png)



![0FA56F26-3121-49BF-94E8-13142B36C9CF](https://user-images.githubusercontent.com/82537582/114760692-e5ee8480-9d5f-11eb-9219-04cc4048b03c.jpeg)

**Comment by Lotz0711** [comment]
I'm getting the same error with Inoreader right now. 

![8EE1381F-5C06-4400-BF46-9F78BBFDD133](https://user-images.githubusercontent.com/82537582/114760887-1f26f480-9d60-11eb-8918-8384e10e1e97.png)

**Comment by vincode-io** [comment]
Oops. My successful test was invalid. I forgot that I have a different set of API keys for Inoreader than the public build of NetNewsWire has. 

@brentsimmons I think we need to contact Inoreader about getting our API limits increased.

**Comment by DrTacoMD** [comment]
FWIW it's working as expected for me now. Not sure if Brent/someone was able to talk to Inoreader and get the API limit bumped, or if we're running into some 24 hour rotating window based on UTC or something. I guess if it's broken again tomorrow morning (PST) then that'll be a strong hint.

**Comment by DrTacoMD** [comment]
Confirmed: at around 15:30 UTC today I’m seeing the same “Too many connections” error message, while it was fine when I last commented at around 05:00 UTC.

**Comment by vincode-io** [comment]
Inoreader has increased our API limit, so this should be resolved (for now).

Additionally, we've made a change that is coming in 6.0.2 for Mac and the next iOS beta that reduces API usage for Inoreader.

**Comment by mischreiber** [comment]
Looks like this issue may be back, unfortunately. Just started seeing the same error this morning on my Inoreader-synced devices.

<img width="590" height="1278" alt="Image" src="https://github.com/user-attachments/assets/75a4c833-5505-45da-8e15-c6fb10ea7e0d" />

**Comment by brief** [comment]
Same here.

**Comment by mischreiber** [comment]
I hadn't checked in a few hours, but I just reloaded NNW and, as of this writing, the issue is resolved. I'll keep an eye open to see if it crops up again and will comment here if so.

Is there anything additional that would be helpful? Any logs to collect or such?

**Comment by droggs** [comment]
I was seeing this earlier today, but it has since resolved.

**Comment by brentsimmons** [comment]
In 7.1.3 we’ve made a bunch of changes to use less Inoreader bandwidth and to back off when near the quota and when getting 429 responses.
