### ISSUE TITLE
Feature request: Following Twitter lists

### ISSUE THREAD

**Issue by bzigterman** [Ranchero-Software/NetNewsWire#3002]
Hi,

I'd like to request the ability to subscribe or follow Twitter lists. The Twitter home feed is nice, but I like using lists for particular topics. Not sure if this is possible, but it would be nice. 

Thanks!

**Comment by vincode-io** [comment]
You actually can subscribe to Twitter lists, there just isn't a UI for it.

All you have to do is take the URL for the Twitter list and add it like a regular Web RSS feed. The easy way to do it is to use the NetNewsWire Share Extension to share it from the Twitter app directly to NetNewsWire.

**Comment by bzigterman** [comment]
Interesting! Just tried it and it worked perfectly. Thanks!

**Comment by j-f1** [comment]
Maybe add some text in the footer prompting users to add lists via the regular feed input?

![image](https://user-images.githubusercontent.com/25517624/114893696-f7757200-9ddb-11eb-9610-de7ef8a3fe7c.jpeg)

Or as another table view cell that pushes the regular add web feed screen?

**Comment by Niels-NTG** [comment]
Or a slightly different approach: when adding a Twitter list, NetNewsWire could offer an option to add accounts on the list as their own feeds.
