### ISSUE TITLE
iCloud: NY Times feed results in rerun articles

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#3009]
Doesn’t appear to happen with On My Mac. Just with iCloud. (Haven’t checked on iOS.)

https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml

**Comment by vincode-io** [comment]
The feed is kind of weird. It looks like it has today's news articles in it and then a handful from March 24th and some from April 14th & April 15th. Did those old articles in the RSS feed just pop up today?

**Comment by brentsimmons** [comment]
What happens in iCloud if an article drops out of a feed and then comes back later?

**Comment by vincode-io** [comment]
When we delete an article in the retention code it also gets deleted from iCloud. If it comes back we would add it again in iCloud.

**Comment by brentsimmons** [comment]
![Screen Shot 2021-04-16 at 5 29 56 PM](https://user-images.githubusercontent.com/1297121/115096314-64226680-9ed9-11eb-9375-a84d79dbec5d.png)

Looks like a duplicate. I’ll check the XML…

**Comment by brentsimmons** [comment]
…different guids in this case.

https://twitter.com/karaswisher/status/1383209552355717124

vs.

https://twitter.com/nytopinion/status/1383210475328966656

**Comment by vincode-io** [comment]
I'm seeing old articles popping up in this feed, but I can't find any reruns.

**Comment by brentsimmons** [comment]
I’ll keep an eye on it — could be a mix of old articles out of the blue and the occasional guid change like the above.

**Comment by pdokas** [comment]
This happens with specifically NYT feeds via Feedly sync as well (all RSS clients, including but not limited to NNW). It's been this way for a few years, I suspect their CMS republishes articles in the feed with similar content but different GUIDs for some reason.
