### ISSUE TITLE
beta release offered despite download option being set to Release builds

### ISSUE THREAD

**Issue by foss-** [Ranchero-Software/NetNewsWire#3011]
Assuming `Release builds` are stable releases while `Test builds` are beta builds there is some inconsistent behavior as 6.0.2b1 was offered although `Preferences > Advanced > Download` is set to `Release builds`.

<img width="508" alt="test build offered" src="https://user-images.githubusercontent.com/5708172/115108660-f7a77600-9f71-11eb-98f7-993df5e805e4.png">

**Comment by brentsimmons** [comment]
I think I know why. Should be fixed for next build. Please re-open this if, when the time comes, it turns out I’m wrong.
