### ISSUE TITLE
Feedbin account refresh fails with “The data couldn’t be read because it isn’t in the correct format.”

### ISSUE THREAD

**Issue by ghslp** [Ranchero-Software/NetNewsWire#3013]
In 6.0.1 on macOS 10.15.7 and 5.0.5 on iOS 14.14.2 I’m unable to full refresh my Feedbin account. 10/309 feeds have updated, but the rest have no articles.

This is with a new Feedbin account, and a new installation of NetNewsWire (in the process of trying different RSS options).

The same Feedbin account is able to sync in the latest version of Reeder, so I don’t think this is a temporary issue with the Feedly API unless you’re using different endpoints than Reeder.

Please let me know if there’s any more information I can provide, and thanks for developing NetNewsWire!

---

Full error:

> An error occurred while processing the “Feedbin” account: The data couldn’t be read because it isn’t in the correct format.
>
> Please try again later.

I’m not sure if this is related, In the macOS console I see several errors like this during the refresh:

> Task <DBBD16F4-6891-43D1-A995-892C632D248B>.<135> finished with error [-1002] Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSUnderlyingError=0x600001842d60 {Error Domain=kCFErrorDomainCFNetwork Code=-1002}, NSErrorFailingURLStringKey=<private>, NSErrorFailingURLKey=<private>, NSLocalizedDescription=unsupported URL}

**Comment by brentsimmons** [comment]
Is this happening on iOS as well as on your Mac?

If it’s happening on iOS, does it work there if you switch from wi-fi to cell?

**Comment by ghslp** [comment]
> Is this happening on iOS as well as on your Mac?

Yes, this is happening on both iOS (iPhone) and macOS. On iOS the error is a modal that says:

> **Error**
>
> An error occurred while processing the “Feedbin” account: The data couldn’t be read because it isn’t in the correct format.

> If it’s happening on iOS, does it work there if you switch from wi-fi to cell?

Just checked and it also happens when I’m on LTE (with Wi-Fi disabled).

One other thing I forgot to mention in the original issue: this is a Feedbin trial account.

**Comment by ghslp** [comment]
This issue resolved itself today on both macOS and iOS — turns out the problem was on Feedbin’s end after all. Sorry for the false alarm!
