### ISSUE TITLE
Autoplay video?

### ISSUE THREAD

**Issue by peternlewis** [Ranchero-Software/NetNewsWire#3025]
In this feed: 

https://www.teslarati.com/feed/

This article: “Tesla alleged “driverless” crash in Texas: What is known so far” URL: https://www.teslarati.com/tesla-texas-autopilot-crash-facts-videos/

Autoplays an ad video, with sound.

That was entirely unexpected, and I've never seen it happen anywhere else.

I don't know if this is supposed to be allowed, or some sort of failing to avoid it, but certainly it is undesirable.

**Comment by stuartbreckenridge** [comment]
I've confirmed this behaviour for this feed in NetNewsWire and other RSS readers. It looks like they've gone to some length to include this in a feed.
