### ISSUE TITLE
Suggestion: Feed info page should show which folder it is in

### ISSUE THREAD

**Issue by OddHouseGames** [Ranchero-Software/NetNewsWire#3026]
Since the iOS version of NetNewsWire doesn't have a search capability, it would be great if the feed info page showed which folder it was contained in.

**Comment by stuartbreckenridge** [comment]
You can search by going to All Unread and pulling down slightly to reveal the search bar. You can the search All Articles.

**Comment by OddHouseGames** [comment]
Thanks, that works!
