### ISSUE TITLE
Feed not found on valid feed

### ISSUE THREAD

**Issue by distantnative** [Ranchero-Software/NetNewsWire#3027]
Hi guys,

thanks so much for NNW!

We're facing the problem that we'd like to add https://getkirby.com/kosmos.rss to NNW.
Both iOS and Mac throw the error "feed not found".

But the feed validates just fine https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fgetkirby.com%2Fkosmos.rss

Other RSS apps can add it. So I was wondering if something else is wrong about the feed or it's a NNW bug.

Thanks!

**Comment by babbage** [comment]
Worked fine here. Perhaps this was a server/DNS error at the feed end, at the time of your initial attempt to add the feed?

If you're the feed owner, one piece of feedback. You have the item title in both the title tags and repeated in the description marked as a heading. This results in it appearing twice when the items are displayed. The title should not be repeated in the item description in your feed. 😌

**Comment by vincode-io** [comment]
@distantnative What kind of account are you using?

**Comment by distantnative** [comment]
Tried again and now it's working. Sorry guys. Thanks a lot
