### ISSUE TITLE
Code Sign Issues on Xcode 12.5

### ISSUE THREAD

**Issue by stuartbreckenridge** [Ranchero-Software/NetNewsWire#3031]
The Mac target cannot build due to a Code Signing error related to the Share Extension:

```
/Users/stuart/Library/Developer/Xcode/DerivedData/NetNewsWire-gdvxpmwdeprglrcuiptwdqhzimnb/Build/Products/Debug/NetNewsWire Share Extension.appex/Contents/Frameworks/SyncDatabase.framework/Versions/A: code object is not signed at all
In subcomponent: /Users/stuart/Library/Developer/Xcode/DerivedData/NetNewsWire-gdvxpmwdeprglrcuiptwdqhzimnb/Build/Products/Debug/NetNewsWire Share Extension.appex/Contents/Frameworks/SyncDatabase.framework/Versions/A/Frameworks/RSCore.framework
Command CodeSign failed with a nonzero exit code
```

**Comment by stuartbreckenridge** [comment]
Potential solution is to add the following to the DeveloperSettings file:

`OTHER_CODE_SIGN_FLAGS = --deep`

I am not sure of the side effects, however.

**Comment by heckj** [comment]
FWIW:

`--deep` recursively signs code and libraries within a framework - it's actually specifically meant for this sort of scenario: where you have multiple layers in a framework that all need to be signed for execution validation. What changed in 12.4 -> 12.5 is a definitely curious scenario (worthy of a FB as a regression). But in general, I think adding in `--deep` is pretty safe for the project overall. Worst case scenario, you're signing more code that gets explicitly included into the built framework. (Only docs I could find for this from Apple were at <https://developer.apple.com/library/archive/technotes/tn2206/_index.html#//apple_ref/doc/uid/DTS40007919-CH1-TNTAG404>) 

My suspicion is that the advice in that TN article to not use `--deep` as a general action is to prevent someone from slipping in code on a developer, and then you "accidentally" sign it, as a potential security hole.
