### ISSUE TITLE
An error occurred while processing the “Feedbin” account: The data couldn’t be read because it isn’t in the correct format.

### ISSUE THREAD

**Issue by fma16** [Ranchero-Software/NetNewsWire#3034]
Hello everyone,

I am currently encountering an error while adding my Feedbin account in NetNewsWire on macOS :
`An error occurred while processing the “Feedbin” account: The data couldn’t be read because it isn’t in the correct format.`

I tried on a fresh install of NNW, version 6.0.2 (6032), on macOS Big Sur 11.2.3.

However, this is not the first time I get this error. I got the same one with NNW 5 (sorry, I don't recall the correct version) on my personal mac on Catalina. I also get this issue on iOS (v5.0.5).

My feedbin account works perfectly fine with other apps (Fiery Feeds on iOS, Reeder, ...)

I saw that there were other issue opened regarding this error, however, I did not find any steps to help me solve it.

Does anyone can help me with this? Please tell me if you need any more informations!

Thanks a lot!

**Comment by vincode-io** [comment]
@fma16 Can you think of anything unusual about your Feedbin account? Is there special characters in the username or password that we might not be taking into consideration?

**Comment by fma16** [comment]
@vincode-io Thanks for your help! :)
Not really, my username is an email address (feedbin at laugier dot co). Noting in particular in my password too.

I do use Feedbin [newsletter feature](https://feedbin.com/blog/2020/02/06/newsletter-news/), but nothing exotic. I can of course provide you with an OPML export if needed.

On the syncing issue, what seems to happen is that NNW is able to sync some data, but is faced with a bug mid-process. Here is when I get the error :
![image](https://user-images.githubusercontent.com/1146233/117107782-70843b80-ad82-11eb-8493-7916f333262a.png)

I can provide you with an extract from the macOS console if needed.
Thanks a lot!

**Comment by vincode-io** [comment]
An OPML file would be useful. There might be something in a specific feed that causing the bug to trigger.

**Comment by fma16** [comment]
Here you go (I had to add it as a zip since Github refuses to upload .xml files).

Thanks again for your time.
[subscriptions.xml.zip](https://github.com/Ranchero-Software/NetNewsWire/files/6432460/subscriptions.xml.zip)

**Comment by vincode-io** [comment]
I don't have a fix for your problem yet, but if you delete your "Hacker News: Front Page" feed it will start syncing for you again.

**Comment by vincode-io** [comment]
The problem with the "Hacker News: Front Page" feed is that it doesn't conform to the JSON 1.0 spec. We now handle this more gracefully and don't fail to parse the entire JSON feed. Look for this fix in the next Mac release.

**Comment by fma16** [comment]
Thanks a lot for your help @vincode-io . It is very much appreciated. I will switch the feed in Feedbin from jsonfeed to the classic XML version, but looking forward to your fix!
