### ISSUE TITLE
BazQux sync incomplete

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#3044]
App Store Connect report:

“BazQux sync is always incomplete, showing only a few new items while others readers can get all of them.”

![fits1024x1024-1](https://user-images.githubusercontent.com/1297121/115946777-42e0ed80-a478-11eb-94ad-85e7957cf111.jpg)

**Comment by DavidMunch** [comment]
I have a hunch that this is a Bazqux issue, as I've seen the same problems with Feedler on iOS and Vienna on macOS. They do seem to have disappeared the last month or so, after having been present for 3+ months.

**Comment by vincode-io** [comment]
Is it possible that this was a temporary problem with BazQux? I just tested and all my unread counts match and I am receiving new articles as they come in.

**Comment by vincode-io** [comment]
I validated this again today and got all the new articles and was fully in sync with the BazQux web app.

**Comment by DavidMunch** [comment]
In that case it has been a temporary issue that lasted several months, and was active until 2 weeks ago, when I saw it happen the last time.

**Comment by vincode-io** [comment]
@DavidMunch does the issue come and go? Is this always the case with BazQux for you? I need more info to track down this problem.

**Comment by DavidMunch** [comment]
It was quite consistent for several months, but now it seems to be changing, so most of the time it works right now, but as mentioned above, I saw it happen 14 days ago.

**Comment by vincode-io** [comment]
@DavidMunch Do you think that this is the same issue that we fixed in #3210?

**Comment by DavidMunch** [comment]
I do not think they are related. At least for me, #3210 simply had NWW loose its credentials for logging in on Bazqux on a semi-regular basis, and was easily fixed by re-entering my password. This seems to be a sporadic issue, which results in some feeds being improperly synced across units. 

As mentioned above, I definitely feel that this is a Bazqux issue, and not a NWW issue. I can update the ticket with some screenshots, the next time I see the problem.

**Comment by vincode-io** [comment]
I think that this was resolved in the #3210 fix.

**Comment by DavidMunch** [comment]
I haven't seen the issue for quite some time, so you are properly right. Close it!
