### ISSUE TITLE
Embedded audio in 512 Pixels feed doesn’t play

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#3045]
App Store Connect report:

“The embedded audio in the latest 512 Pixels post (https://512pixels.net/2021/04/mac-chimes-of-death/ ) doesn’t play in NetNewsWire. If I press the play button, it changes to a pause icon as if it’s playing, but the time doesn’t advance and nothing plays.”

![fits1024x1024-2](https://user-images.githubusercontent.com/1297121/115946802-71f75f00-a478-11eb-9dbe-1eee5c3a81b7.jpg)

**Comment by vincode-io** [comment]
This article has rolled off the RSS feed, so I can't determine if the sound URL was valid in the feed or not.
