### ISSUE TITLE
Today feed showing old articles

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#3050]
Maybe it’s just not re-fetching periodically? We should handle the case where a person just stays on that view.

App Store Connect report:

“Today view is showing items from two days ago. See example in screenshot - today is 13 April, Daring Fireball article is from 11 April. These are feeds added to an iCloud account.”

![original](https://user-images.githubusercontent.com/1297121/115947077-36f62b00-a47a-11eb-8dfa-2aaf3b30ef50.jpg)

**Comment by stuartbreckenridge** [comment]
@brentsimmons Rename it to "Recent" ;-)?

**Comment by brentsimmons** [comment]
I still like Today. I think the bug is just that it needs to re-fetch periodically to get rid of older items.

**Comment by vincode-io** [comment]
We've long held the design philosophy that we don't remove items from the timeline while users are viewing it. (The exception is if they issue the Clean Up command). If we are going to make a special case for Today, we will need to come up with some kind of criteria for it.
