### ISSUE TITLE
Reddit links issue

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#3053]
App Store Connect report:

“Hi, with the introduced support for Reddit links I am unable to add the feed successfully because the detected urls aren’t correct by the app. The URL I believe I should use: https://www.reddit.com/r/TestFlight/ The necessary address to achieve functional feed: https://www.reddit.com/r/TestFlight.rss The screenshot attached is the result when attempting to use the first URL.”

![original](https://user-images.githubusercontent.com/1297121/115947630-c94bfe00-a47d-11eb-8d9f-2208304b503f.jpg)

**Comment by stuartbreckenridge** [comment]
To add a Reddit feed with the provided functionality should be done through the Add Reddit Feed. 

So:
- Tap +
- Tap Add Reddit Feed
- Tap Subreddit
- Enter "TestFlight"
- Tap Next
- Tap New

**Comment by stuartbreckenridge** [comment]
There's a flip side to this...if we detect a reddit.com url added through Add Web Feed, we could optimistically append `.rss` to see if there's a feed there.

**Comment by vincode-io** [comment]
This person probably didn't have the Reddit Extension enabled. I had no problem adding https://www.reddit.com/r/TestFlight/ using Add Web Feed.

<img width="1351" alt="Screen Shot 2021-05-06 at 6 59 32 PM" src="https://user-images.githubusercontent.com/16448027/117379587-6014b380-ae9d-11eb-8900-47d156bc35ac.png">
