### ISSUE TITLE
Internal browser doesn’t allow scrolling with a specific feed’s articles

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#3057]
App Store Connect report:

“When opening any feed in the internal browser for further reading from the source : t3n.de The internal browser from NetNewsWire freezes and I am not able to scroll. This does not happen in safari.”

**Comment by stuartbreckenridge** [comment]
I tested multiple articles on this site but wasn't able to reproduce. 

The closest I could get was when I didn't accept the cookie preference pop-up, which had appeared out of view.

**Comment by babbage** [comment]
Likewise could not reproduce.
