### ISSUE TITLE
Top-level iCloud feeds don’t appear on Feeds screen

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#3058]
This is actually happening on my iPhone.

**Comment by vincode-io** [comment]
Are your unread counts not matching as well?

**Comment by brentsimmons** [comment]
Right now there’s only 1 unread article, and that matches, but that’s not much to go on. I’ll check again tomorrow before I’ve gone through and read everything.

**Comment by brentsimmons** [comment]
Unread counts are consistent — it’s just that top-level feeds are missing on iOS.

I just added a top-level feed on Mac 1. It synced immediately to Mac 2. It has not appeared on my iPhone. My iPhone shows no top-level feeds, even though it should show four.

**Comment by vincode-io** [comment]
If your unread counts are staying in sync, you must have the feeds, but they aren't being displayed. Could you check in the debugger to see if the feeds are associated with the Account or not? That will help us narrow down where the problem is.

**Comment by vincode-io** [comment]
In that case the feeds must not be getting synced.

**Comment by vincode-io** [comment]
It is acting as if your `Account.externalID` is corrupted on your iPhone. One way to know for sure is to inspect that property on your iPhone and one of your Macs to make sure it is the same value. If it is different, then we would need to track down how it happened.

Is it possible that you deleted your iCloud data and didn't recreate the the account on your iPhone?

**Comment by brentsimmons** [comment]
I started over on my Macs, and know this is working fine. I suspect it was just me, and it was an artifact of some kind left over from testing early versions of iCloud sync. We can always re-open this if it comes up again.
