### ISSUE TITLE
On dragging feeds into iCloud from On My Device, display alert that read and starred statuses are not copied over

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#3060]
People keep expecting that the statuses will all be carried over. We should let them know — once, with a dialog of some kind — that they won’t be carried over.

**Comment by vincode-io** [comment]
Shouldn't we do this for all account to account copies?

**Comment by brentsimmons** [comment]
I’ve decided against doing this alert. We’ll cover it in the FAQ so we have a place to link to an explanation.
