### ISSUE TITLE
Better error message on adding FreshRSS account

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#3061]
App Store Connect report:

“Error when try to add a FreshRss account”

The error message should better explain what happened.

![fits1024x1024-1](https://user-images.githubusercontent.com/1297121/115948049-935c4900-a480-11eb-90b6-99cbfb1f24ca.jpg)

**Comment by vincode-io** [comment]
We now specify that it was the API URL that wasn't found.
