### ISSUE TITLE
Sharing doesn’t work with specific feed

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#3069]
App Store Connect report:

“For some reason I have one feed t3n (https://t3n.de/tag/gadgets-lifestyle/rss.xml) where I could not use the share function. In the list view the share button is missing entirely and in the article view the share button has no function.”

![original](https://user-images.githubusercontent.com/1297121/115969626-a4de3900-a4f2-11eb-8f4a-b7a130599fe8.jpg)

**Comment by babbage** [comment]
Many articles in this feed contain malformed URLs that include spaces that have not been percent encoded between query parameters if they have multiple attached keywords. For instance:

> <a href="https://t3n.de/news/imac24-ipad-pro-m1-airtags-apple-podcast-1372021/?utm_source=rss&amp;utm_medium=feed&amp;utm_campaign=gadgets &amp; lifestyle">

This string returns nil when NetNewsWire attempts to create a URL for it:

`guard let preferredLink = currentArticle?.preferredLink, let url = URL(string: preferredLink) else {
	return
}`

It would be possible to fix this bug by explicitly fixing any extant spaces in strings that are supposed to already be URL encoded:

`let sanitizedLink = preferredLink.replacingOccurrences(of: " ", with: "%20")`

The best way to do this I think would be to centralise it as a new `article?.preferredURL` property as there are multiple places in the iOS app where the same guard statement above is used and so must be failing with these same feeds.

I'd be happy to implement that, a simple fix. The question is—does the team have a view on whether NetNewsWire should be fixing broken URLs in feeds?
