### ISSUE TITLE
Timeline scrolling sometimes glitchy

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#3070]
I’ve noticed this when first opening a smart feed or folder timeline — it looks like it’s related to loading images, and it appears to go non-glitchy once finished.

That’s just a guess, though. We should use the Profiler to figure out the real problem.

**Comment by brentsimmons** [comment]
Part of this — possibly all (not sure yet) — was done in 9d2c8f00

**Comment by brentsimmons** [comment]
I think there’s more to do, but we did a nice chunk of it already. We can revisit for 6.1.

**Comment by vincode-io** [comment]
By glitchy, do you mean that it is hitching?

**Comment by brentsimmons** [comment]
Closing this because I haven‘t seen it a long time.
