### ISSUE TITLE
Underline styling stripped

### ISSUE THREAD

**Issue by j-f1** [Ranchero-Software/NetNewsWire#3077]
Feed URL: http://blog.nuclearsecrecy.com/feed/atom/
Article: In Memoriam: John Coster-Mullen (1946-2021)

In this article, about ¾ of the way down, the phrase “spectacular and hitherto unseen” is underlined on the website, and the Atom feed includes the HTML code `<span style="text-decoration: underline;">spectacular and hitherto unseen</span>`. However, in the article viewer, the `style` attribute is stripped, leaving only `<span>spectacular and hitherto unseen</span>`. This removes the underline.

**Comment by vincode-io** [comment]
It is there for Local and iCloud accounts. Are you using a syncing service that might be mangling it?

<img width="1286" alt="Screen Shot 2021-09-12 at 9 40 49 PM" src="https://user-images.githubusercontent.com/16448027/133016016-604d379f-b248-433f-91da-b3e7f8605235.png">

**Comment by j-f1** [comment]
I was using Feedly at the time I encountered this issue. I am now using iCloud and the underline shows up just fine.

**Comment by vincode-io** [comment]
Feedly mangles its articles pretty badly. Closing since this isn't a NetNewsWire bug.
