### ISSUE TITLE
[mac] [6.0.2] Key ```l``` doesn't jump to next unread when feed is all read

### ISSUE THREAD

**Issue by ednl** [Ranchero-Software/NetNewsWire#3092]
The keyboard shortcut ```l``` (lowercase letter L) for "mark feed as read, jump to next unread" in NNW version 6.0.2 on the Mac no longer jumps to the next unread message when all messages in a feed are already marked read.

Another way that it is broken: when pressing ```l``` on a folder, focus jumps to the first feed inside the folder which by then is (rightly) marked all read. Instead, it should jump to the next folder.

**Comment by vincode-io** [comment]
This is fixed and will be in the next release.
