### ISSUE TITLE
Feed sorts itself not by name, but by the most recent post

### ISSUE THREAD

**Issue by joncallas** [Ranchero-Software/NetNewsWire#3101]
The MacWorld feed, <http://rss.macworld.com/macworld/feeds/main> sorts itself into the side bar based on the name of the most recent article.

For example, right now, it's under W for "What is App Tracking Transparency..." but earlier in the day it was under A for "Apple Maps: how to report accidents..."

**Comment by stuartbreckenridge** [comment]
This is because Macworld are renaming their feed with the latest article. 

As a workaround, if you rename the feed in NetNewsWire it should stop it being renamed.

**Comment by babbage** [comment]
> This is because Macworld are renaming their feed with the latest article.

🙄That is so wacky. 🤣
