### ISSUE TITLE
Copy URLs using repaired rather than raw feed links

### ISSUE THREAD

**Issue by babbage** [Ranchero-Software/NetNewsWire#3103]
Looking at #3102 today made me reflect that we have recently added the capacity to repair article URLs that are malformed through containing strings that are not percent encoded, and we are considering whether to also extend this to removing `CDATA` tags from these fields too in how to fix #3043. 

We are only fixing link strings where they cannot be converted into a valid URL. If we use the raw feed url string when the user is copying or sharing URLs, we are handing to the user a link we know is invalid. In some cases the destination app will resolve the issue—such as when pasting into Safari a link that contains spaces that have not been percent encoded. But in other cases the user ends up with something that does not work, even though the outgoing link works in NetNewsWire.

I suggest a patch that converts the various copy URL and share facilities to use the string-correcting pipeline that was established in #3079. This will involve adding a URL.init guard step into some places where previously the raw feed string was just being passed without that, so we would want to be mindful of performance and only use it where required.

Would make sense to wait for #3102 to land then I'd be happy to take a look at this.

**Comment by vincode-io** [comment]
@babbage I've now merged #3102. Do you still have time to work on this?

**Comment by babbage** [comment]
Can't start on this until tomorrow at the earliest, but yes, I'd be happy to take a look at this. :)

**Comment by vincode-io** [comment]
Sweet! It is good to see that you are still around. 😄

**Comment by robmathers** [comment]
Thanks for the work on this one and merging in my #3102!
