### ISSUE TITLE
$WORD in tweet seems to get elided in NNW UI

### ISSUE THREAD

**Issue by zellyn** [Ranchero-Software/NetNewsWire#3104]
Version: Version 6.0.2 (6032)

Tweet URL: https://twitter.com/bradfitz/status/1389410816890269697

How it looks in twitter:
![image](https://user-images.githubusercontent.com/33625/117002537-aa394180-acb1-11eb-9a3e-44d1d7fd521e.png)

How it looks in NNW:
![image](https://user-images.githubusercontent.com/33625/117002640-cf2db480-acb1-11eb-8717-b9c2688a1ae0.png)

**Comment by brentsimmons** [comment]
Since Twitter integration will stop working soon — as soon as Twitter ends free Twitter API access — I’m closing this.
