### ISSUE TITLE
Messaging about iCloud performance

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#3105]
Design needed. When and where do we warn the user about how iCloud may be slow, and what does that text say?

**Comment by stuartbreckenridge** [comment]
Suggestion: follow Mail’s example:

![1F6E05E9-C8DB-49E1-9667-AC26C7D57941](https://user-images.githubusercontent.com/7046652/117105239-316cdf00-adb0-11eb-90b7-105c3b9a36c6.jpeg)

**Comment by j-f1** [comment]
The app could suggest users move over gradually. I’ve been moving from Feedly to iCloud folder-by-folder and and letting it sync after each move and haven’t encountered any issues.

**Comment by rnetter** [comment]
On my Macs the sync with iCloud stops working for days but can start up all of the sudden and can keep working on any of my other 2 Macs. Please help. It happens so intermittent that gradually moving over feeds from another account might not work.
