### ISSUE TITLE
UI should disallow iCloud accounts when iCloud Drive is disabled

### ISSUE THREAD

**Issue by meissnem** [Ranchero-Software/NetNewsWire#3106]
Two scenarios with two Macs -- my personal one ("MyMac") and one issued by my employer ("WorkMac"). In both scenarios,I sign into the same iCloud account on both machines.  On MyMac, I enable iCloud Drive globally, enable iCloud Drive for NNW, and successfully set up iCloud syncing in NNW.

1) On WorkMac, I leave iCloud Drive globally disabled. NNW still lets me set up an iCloud syncing account on WorkMac but nothing is synced. There are no warnings and the UI gives me no indication why the account I set up on MyMac is not syncing to WorkMac.
2) On WorkMac I have iCloud Drive globally enabled but I uncheck NNW in the iCloud Drive system preference pane. NNW still lets me set up an iCloud syncing account but nothing is synced.

In both scenarios, if I attempt to add a feed to the iCloud account an error is produced.
<img width="372" alt="Screen Shot 2021-05-06 at 11 51 02 AM" src="https://user-images.githubusercontent.com/868308/117336054-68e79400-ae61-11eb-918d-71769b22d66e.png">

It would be great if NNW could more gracefully handle the iCloud Drive-disabled situations and issue warnings or disallow iCloud sync account creation.

**Comment by meissnem** [comment]
Thanks for the attention, @vincode-io!

**Comment by vincode-io** [comment]
@meissnem I think it was probably pure laziness that I didn't put this in before! Thanks for kicking me into gear.
