### ISSUE TITLE
Moving feed to different folder resets custom name

### ISSUE THREAD

**Issue by petebocken** [Ranchero-Software/NetNewsWire#3109]
When moving a feed between folders, your custom set feed name gets reset.

https://user-images.githubusercontent.com/1580388/117591282-728b2900-b0f9-11eb-9658-55f2167b42fc.MP4

**Comment by vincode-io** [comment]
@kielgillard If we add the feed name to `FeedlyAddFeedToCollectionOperation` in the `FeedlyAddExistingFeedOperation` initializer, do you think it will fix this bug?

**Comment by kielgillard** [comment]
@vincode-io I think it will, too. I'll implement, test and submit a PR in a day or so with this fix.

**Comment by kielgillard** [comment]
@vincode-io I haven't forgotten just been busy. Within the next week for sure.

**Comment by brentsimmons** [comment]
Moving this to 6.1 milestone. If it gets in for 6.0, then that’s awesome, but it’s not required.

**Comment by kielgillard** [comment]
Moving this to the 6.0 milestone because I have a PR #3139 for the iOS fix.

**Comment by kielgillard** [comment]
PR #3140 for the macOS fix.

**Comment by kielgillard** [comment]
Thanks for reporting this @petebocken! It should be fixed in the next iOS and macOS releases.
