### ISSUE TITLE
MacOs Screen Time Issue

### ISSUE THREAD

**Issue by tmytro** [Ranchero-Software/NetNewsWire#3117]
I had a problem that Screen Time statistic on my MacBook(M1) show that I use device 24/7, but this was wasn't true, I at least sleep at night and close the lid of the macbook!

Screen Time didn't tell what is the program that doesn't sleep, just day "Other":
<details>
<summary>Screenshot</summary>  

![2021-05-14 11 25 34](https://user-images.githubusercontent.com/40320374/118258015-3f54eb00-b4a7-11eb-8980-3ace51b37d55.jpg)
</details>

But from iPhone I was able to see what was taking up screen time. This is a website that I added to my RSS feed in NNW. It wan't opened in any browser or something like that, I only added it to my feed. 
<details>
<summary>Screenshot</summary>  

![telegram-cloud-photo-size-4-5834649369117308178-y](https://user-images.githubusercontent.com/40320374/118258753-2ef14000-b4a8-11eb-8898-9bd70e76bc50.jpg)
</details>

I just installed NNW a few days ago when I started having problems with the screen time. In the preferences "refresh feed" is set to 1H. So, for me it's look like a bug, I don't know yet if the problem is only with this particular website's feed or with NNW in general.

**Comment by Altair-Bueno** [comment]
This is a Big Sur bug. Happens with every single app that is kept open (dot under Dock icon). I disabled screen time on my macs for that reason, I suggest you do the same until Apple solves this problem (maybe Monterrey, maybe never)

**Comment by AnneMerrill** [comment]
I have the same problem. If I click through on an article inside NetNewsWire, the site that it goes to gets counted in my screentime from when I click on it until I restart my phone.

**Comment by brentsimmons** [comment]
Are you still seeing this bug?
