### ISSUE TITLE
Crash when creating a new account

### ISSUE THREAD

**Issue by equivocates** [Ranchero-Software/NetNewsWire#3118]
Updated to 6, but crashes whenever I create a new local or iCloud feed.

[Here's a video of what happens](https://user-images.githubusercontent.com/19939696/118277164-183def80-b48e-11eb-9d6b-f154fb292c71.mp4)

[icloud crash.txt](https://github.com/Ranchero-Software/NetNewsWire/files/6479009/icloud.crash.txt)
[local crash.txt](https://github.com/Ranchero-Software/NetNewsWire/files/6479012/local.crash.txt)

I'm running Version 6.0.2 (6032) on MacOS 11.3.

**Comment by vincode-io** [comment]
What we've seen in the past is that the user doesn't have permissions to create the account file. If I'm remembering correctly, they had tried symlinking the NetNewsWire folder to another location.

Is it possible that you've done something that could have impacted the permissions in the NetNewsWire folder?

**Comment by equivocates** [comment]
Yes -- I had previously used symlinks to sync across multiple computers. Is there a fix?

**Comment by vincode-io** [comment]
Delete `~/Library/Containers/com.ranchero.NetNewsWire-Evergreen`. I don't know what process you are using to migrate your accounts, but hopefully you've created an OPML file so that you can save your feeds.

**Comment by vincode-io** [comment]
It looks like this got resolved. We can reopen if that isn't the case.
