### ISSUE TITLE
Spurious "https:/" in tweet text

### ISSUE THREAD

**Issue by zellyn** [Ranchero-Software/NetNewsWire#3120]
Version: Version 6.0.2 (6032)
Tweet URL: https://twitter.com/FogleBird/status/1394121686396686336

How it looks in twitter:
![image](https://user-images.githubusercontent.com/33625/118498974-884daf00-b6f4-11eb-803a-a5743619eb18.png)

How it looks in NNW: 
![image](https://user-images.githubusercontent.com/33625/118499035-93084400-b6f4-11eb-9745-1e80d656e93a.png)

**Comment by vincode-io** [comment]
I got this fixed and it will be in the upcoming release.
