### ISSUE TITLE
"Network error" when trying FreshRSS

### ISSUE THREAD

**Issue by Krinkle** [Ranchero-Software/NetNewsWire#3125]
* FreshRSS 1.18.0 (latest) at `https://news.timotijhof.net/`. I've enabled the "Allow API access" option.
* NewNetWire for Mac 6.0.2 (6032).

Based on https://github.com/Ranchero-Software/NetNewsWire/issues/3055, I figured out that the API url is meant to be `https://news.timotijhof.net/api/greader.php`. This endpoint returns 200 OK when I try it directly so it seems to be exposed correctly.

However, entering it in NNW says "Network error. Try again later."

I also tried adding `?` and `?api` to the URL, and without `https://` (based on https://github.com/Ranchero-Software/NetNewsWire/issues/2930), but none of those combinations seem to work either.

Ref https://github.com/Ranchero-Software/NetNewsWire/issues/2930.
Ref https://github.com/Ranchero-Software/NetNewsWire/issues/2886.

**Comment by Krinkle** [comment]
My bad. In FreshRSS, under "Settings > Logs" I found an entry `Password API mismatch for …`, which suggests there may be a different password for the API than for the web form.

Under "Admin > Manager users" there is only a single password field to be set. The API password can be set under "Config > Profile" instead, which is required to be done before one can use the API.

After that, all good!

**Comment by Krinkle** [comment]
Perhaps it is worth clarifying in the interface that one must enter an "API password" (as opposed to the regular password, which they label "Web-form password").

**Comment by kara-ryli** [comment]
Thank you for documenting this! I got stuck by it too; I created a feature request ^ for FreshRSS to make this more obvious.
