### ISSUE TITLE
Image not displaying in feed

### ISSUE THREAD

**Issue by DavidWJ19** [Ranchero-Software/NetNewsWire#3127]
I am subscribing to the RSS feed of [this site](https://somewherein.jp/). Each post has an image associated with it. The image does not appear in NNW (I’m using the latest version on OS and beta on iOS, synchronizing via iCloud).

I have experienced the same with [this site](https://craigmod.com/huh/) as well where the image is integral to the post but the feed does not display it in NNW.

I don’t know enough about websites/ feeds/ etc to know if this is an issue with NNW or just how it is because of the website?

**Comment by brentsimmons** [comment]
The feed doesn’t include the images, unfortunately. You could consider contacting them and letting them know that it would be nice if the feed included the images.

**Comment by babbage** [comment]
Brent beat me to it! Just to confirm the same thing is true for the second feed you linked to—the images aren't included in the feed unfortunately, so what NNW is displaying is already the full content the site is providing for their feed.

**Comment by DavidWJ19** [comment]
Thank you both for the quick responses and explanation.
