### ISSUE TITLE
Consider Making Swipe Action Wording More Consistent

### ISSUE THREAD

**Issue by jalexandratos** [Ranchero-Software/NetNewsWire#3133]
Please consider changing the wording for the *Read/Unread swipe action* from **Mark as Read/Unread** to **Read/Unread**.

This would make it consistent with the other swipe actions (**Star**/**More**) - which are also single words.

Thanks

**Comment by brentsimmons** [comment]
Those labels double as accessibility labels. We changed Read to Mark as Read so that it’s more clear for people using accessibility.
