### ISSUE TITLE
(UX design idea) Filter Twitter Feeds

### ISSUE THREAD

**Issue by w4rner** [Ranchero-Software/NetNewsWire#3135]
Current issue: Twitter feeds are generally higher-volume, and contain more (let's be honest) discardable posts than average blog.
Usually people are using RSS feeds to try to get away from overwhelming nature of social feeds (which do nefarious algoritmic filtering to overcome this problem)

---

Though I know long-term @brentsimmons discussed with Jason Snell beefing out in-NNW custom filtering.
But here's a couple of simple but effective methods to filter Twitter feed subscriptions to cherry-pick the best content, in order of amount of filtering, which I believe should be offered when setting up a new Twitter feed sub out of the box:

**1). Exclude ReTweets**
(especially when they are just pure ReTweets with no original info added on a Quote Tweet)

**2). Subscribe to Pinned Post updates only**
(@vincode-io confirmed on Slack this should be technically feasible)
This one is quite an ingenious way of keeping an eye on only the most vital updates, e.g. for a company: a new product | artist: a new release.
If NNW offered this it could really stand-out in the market for 3rd party Tweet viewing.

--

Overall I'm really excited to craft a RSS-first future for info consumption in which we can step out of social silos, but still keep an eye on the most vital info coming out of them from those unlucky enough to still be stuck inside them in the shorter term.

W4RNER

**Comment by brentsimmons** [comment]
Since Twitter integration will stop working soon — as soon as Twitter ends free Twitter API access — I’m closing this.
