### ISSUE TITLE
Add Widgets & Notification for Mac & iOS

### ISSUE THREAD

**Issue by shaonianruntu** [Ranchero-Software/NetNewsWire#3150]
Need Widgets & Notification feature for Mac & iOS，seems like Reeder5.

And looking forward to the update of iOS App to version 6.0

**Comment by vincode-io** [comment]
We do already have Notifications on Mac and iOS. Look in the per feed settings to enable them. We also have Widgets coming in version 6 of the iOS app. We don't have any plans to create Widgets for macOS at this time.

**Comment by Duckbilled** [comment]
> We don't have any plans to create Widgets for macOS at this time.

Could it be relevant to add widgets to macOS, now they can be used on the wallpaper? I would love to see that, and while I could add the iOS widget, it seems not to work properly.
