### ISSUE TITLE
Release Notes link leads to a 404

### ISSUE THREAD

**Issue by j-f1** [Ranchero-Software/NetNewsWire#3153]
The "Release Notes” button in the Settings screen of NNW iOS v6.0 (Build 604) leads to https://github.com/Ranchero-Software/NetNewsWire/releases/tag/ios-6.0, which is a 404 page.

**Comment by stuartbreckenridge** [comment]
This is ok. When 6.0 is released, the 6.0 release notes will be at that URL.

**Comment by doamatto** [comment]
This should be re-opened as the the tag is `iOS-6.0`, not `ios-6.0`

cc @brentsimmons @stuartbreckenridge
