### ISSUE TITLE
Swipe to next article

### ISSUE THREAD

**Issue by mrleblanc101** [Ranchero-Software/NetNewsWire#3158]
Hi 👋 
Not sure if this is the right place, but here is my feature request. It's quite simple actually and would be very convenient:

Currently, the is a next/previous article arrow in the navigation bar. It would be nice if when we scroll to the bottom of an article, if we force the rubber band effect, we jump to the next article. This is like a reverse pull-to-refresh.

Here's an example from a French News reader app I use (iGeneration), but it's for a specific site, it's not an RSS app.
![image](https://user-images.githubusercontent.com/17392251/122130419-9717a680-ce05-11eb-905b-7f8dcb2faa45.gif)

**Comment by vincode-io** [comment]
Were you aware that you can swipe left to right to go to the next article? We prefer this gesture since you don't have to scroll all the way through the article to get to the next one if you don't like the current article.

**Comment by mrleblanc101** [comment]
No I was not. It's a bit confusing since the arrow in the navigation bar point up and down.

**Comment by vincode-io** [comment]
The arrows match the direction of the timeline. Left and right arrows would look weird on the iPad.
