### ISSUE TITLE
Links don’t work in two aktuality.sk feeds

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#3164]
https://www.aktuality.sk/rss/domace/

https://zive.aktuality.sk/chronologicky-vypis/

**Comment by stuartbreckenridge** [comment]
I tried with the feeds downloaded from the [/rss/domance](https://www.aktuality.sk/rss/domace/) feed, and the links seemed to work fine.

**Comment by vincode-io** [comment]
@stuartbreckenridge Did you try with a local or iCloud account? Those look like the permalink isn't being detected.

**Comment by stuartbreckenridge** [comment]
Feedbin. I’ll try with local.

**Comment by no0ID** [comment]
The feed download the articles, but those cannot be opened by tapping the titles, actually cannot be opened at all.

**Comment by no0ID** [comment]
> The feed download the articles, but those cannot be opened by tapping the titles, actually cannot be opened at all.

Bump...!

**Comment by no0ID** [comment]
I purchased the News Explorer just to test if its possible to open the loaded articles in viewer by tapping on titles.
It works! Maybe I return to NNW if this long lasting problem is fixed.

**Comment by brentsimmons** [comment]
Is this still a bug? I wasn’t able to reproduce it.

**Comment by brentsimmons** [comment]
These seem to be working fine. Tested with On My Mac account.
