### ISSUE TITLE
Accounts, extensions lists should be full-width (or plain), not inset

### ISSUE THREAD

**Issue by drgvond** [Ranchero-Software/NetNewsWire#3171]
The _Table Views_ section of the [macOS HIG](https://developer.apple.com/design/human-interface-guidelines/macos/overview/whats-new-in-macos/) states:

> The full-width style works best for tables that already have a visual margin around them, such as a table embedded in a preferences pane.

In the accounts tabs of the preferences, the table view is inset, as visible on the screenshot below. Same goes for the extensions table view.

<img width="624" alt="Screen Shot 2021-06-21 at 8 27 59 PM" src="https://user-images.githubusercontent.com/15913/122858550-4c979d80-d2cf-11eb-9d43-72276eb8ba3a.png">

Compare to similar table in System Preferences, Mail account prefs, etc. See below the example from the same macOS HIG section mentioned above.

![](https://developer.apple.com/design/human-interface-guidelines/macos/images/table-views-full_2x.png)

Since, I assume, these table views are those from [Preferences.storyboard](https://github.com/Ranchero-Software/NetNewsWire/blob/main/Mac/Base.lproj/Preferences.storyboard), the fix is as easy as selecting "Full-width" from the style property in the inspector in IB.

**Comment by drgvond** [comment]
Unless I'm misreading the changes in #3184, you also need to do this for the extensions table view.

**Comment by vincode-io** [comment]
Good catch. I was just validating that, and yes, the change also has to be done to the Extensions table.
