### ISSUE TITLE
iCloud Web Feeds are Per-Device Exclusive

### ISSUE THREAD

**Issue by briantkelley** [Ranchero-Software/NetNewsWire#3172]
I set up iCloud account today with the new iOS release:

1. On iPhone, copy the URL of some feed from the iPhone account
2. Add a new Web Feed to iCloud account using copied URL
3. Delete feed from iPhone account
4. Repeat 1-3 a few times
5. Install NetNewsWire on iPad
6. Add iCloud account; iCloud account appears empty
7. Copy some feed URL from iCloud account on iPhone
8. Add a new Web Feed to iCloud account on iPad using copied URL
9. Feed appears on iPad and read state is synced correctly; feed immediately disappears from iPhone
10. Add a new Web Feed to iCloud account on iPhone using the same URL; feed reappears but immediately disappears from iPad

I didn’t find any diagnostics in the app I could attach to help debug, but please let me know I can provide more actionable information. Thank you so much for your work on iCloud sync. I’m really excited!

**Comment by vincode-io** [comment]
I was just going through old issues and came across this one. Sorry we didn't get back to you sooner.

Were you ever able to get this to work for you?

**Comment by vincode-io** [comment]
I'm closing out this issue since this it is so old and we don't have any other reports of this happening. If anyone is able to provide more information about how we can recreate this, we can reopen this issue.
