### ISSUE TITLE
I often see unparseable strings in this.

### ISSUE THREAD

**Issue by yuluod** [Ranchero-Software/NetNewsWire#3183]
<img width="805" alt="ScreenShot 2021-06-23 at 14 19 53@2x" src="https://user-images.githubusercontent.com/9930784/123045974-250b1700-d42e-11eb-8047-d0c520243231.png">

<img width="704" alt="ScreenShot 2021-06-23 at 14 21 06@2x" src="https://user-images.githubusercontent.com/9930784/123046109-47049980-d42e-11eb-9fc2-4662ea1bd803.png">

**Comment by brentsimmons** [comment]
Are you still seeing this bug?

**Comment by yuluod** [comment]
Recently, I have not encountered any similar problems while using it, so it appears that it has already been resolved. Thank you.
