### ISSUE TITLE
can't add FreshRSS account

### ISSUE THREAD

**Issue by HOMMEEN** [Ranchero-Software/NetNewsWire#3190]
![IMG_0141](https://user-images.githubusercontent.com/49138691/123225163-0461c080-d505-11eb-9bad-e0cef8c60149.jpeg)

**Comment by doamatto** [comment]
Are there any errors in your FreshRSS logs? Make sure that the URL goes to your Greader endpoint, the password is using your API password, and ensure that the username is type properly

**Comment by HOMMEEN** [comment]
> Are there any errors in your FreshRSS logs? Make sure that the URL goes to your Greader endpoint, the password is using your API password, and ensure that the username is type properly

I use the same configuration in another software and it works, but I think your software is better and I have been waiting for this function for a long time hahaha😗

**Comment by vincode-io** [comment]
@HOMMEEN Is there an entry in your Keychain that references your FreshRSS domain? If so could delete your FreshRSS account from NNW, then delete the Keychain entry, and then try adding the account to NNW again?

**Comment by HOMMEEN** [comment]
> @HOMMEEN Is there an entry in your Keychain that references your FreshRSS domain? If so could delete your FreshRSS account from NNW, then delete the Keychain entry, and then try adding the account to NNW again?

It sounds a bit complicated, let me learn

**Comment by doamatto** [comment]
> @HOMMEEN Is there an entry in your Keychain that references your FreshRSS domain? If so could delete your FreshRSS account from NNW, then delete the Keychain entry, and then try adding the account to NNW again?

Afaik this isn't possible on iOS, only on macOS. I could be wrong, but it looks like @HOMMEEN is using the mobile version of NNW.

**Comment by vincode-io** [comment]
Sorry, I wasn't paying close enough attention to the screen shot.

@HOMMEEN Could you instead remove your FreshRSS account and try to add it again?

**Comment by vincode-io** [comment]
@HOMMEEN  Never mind. I see now that is what you are trying to do.

I see that you have nothing in the password field. Are you using a blank password?

**Comment by doamatto** [comment]
I had assumed it was scribbled over in the screenshot, but that would be a good thing to check. I don't think FreshRSS requires passwords, but I imagine NNW does, which could be the culprit of this

**Comment by HOMMEEN** [comment]
> @HOMMEEN  Never mind. I see now that is what you are trying to do.
> 
> I see that you have nothing in the password field. Are you using a blank password?

Yes I am actually trying to add freshrss account And in fact i did enter the password, And the parameters is nothing wrong

**Comment by vincode-io** [comment]
What version of FreshRSS are you using?

**Comment by HOMMEEN** [comment]
> What version of FreshRSS are you using?

latest version in Appstore

**Comment by vincode-io** [comment]
FreshRSS isn't in the Appstore. Aren't you self-hosting your FreshRSS server?

**Comment by HOMMEEN** [comment]
> FreshRSS isn't in the Appstore. Aren't you self-hosting your FreshRSS server?

Sorry i didn't read your reply carefully, 
my freshrss version is 1.18.1

**Comment by HOMMEEN** [comment]
> I had assumed it was scribbled over in the screenshot, but that would be a good thing to check. I don't think FreshRSS requires passwords, but I imagine NNW does, which could be the culprit of this

sorry, i can't Quite understanding what NNW means☹️

**Comment by kevinm6** [comment]
> sorry, i can't Quite understanding what NNW means☹️

NNW -> **N**et**N**ews**W**ire

**Comment by vincode-io** [comment]
@HOMMEEN I'm not having any problems on FreshRSS 1.18.1.

Could you please set up a test account for me on your FreshRSS server and send me the connection information? My email is mo@vincode.io. With this information I will be able to analyze the network traffic between NetNewsWire and FreshRSS to see where the problem is.

**Comment by HOMMEEN** [comment]
so patient and help me out! thank you very much!
