### ISSUE TITLE
Maximum Article Text Size Too Small; Column Too Narrow

### ISSUE THREAD

**Issue by francoislaflamme** [Ranchero-Software/NetNewsWire#3192]
#### 1-) Maximum Article Text Size Too Small

On the macOS version of NetNewsWire, **the maximum article text size is** "Extra Extra Large", but that is **way too small** for my setup. 

#### 2-) Column Too Narrow

**The article text is displayed in a fixed-width column that is way too narrow** relative to the screen real estate available, especially when the sidebar is hidden.

#### Context

I keep my RSS reader on a 43-inch portrait 4K screen running at 2160 x 3840 points (at 1 pixel per point), which is quite nice because the monitor has the same point density as my 27-inch 5K iMac running in retina mode, so I move windows between monitors without the content changing physical size. (The content is simply sharper on the iMac's (retina-mode) internal monitor.) I understand that my setup is a weird and uncommon one, but it works wonderfully when apps don't limit text size arbitrarily. 

#### Fix for Problem 1

NetNewsWire could **allow the user to pick an arbitrary font size.**

#### Fix for Problem 2

NetNewsWire could **allow the user to pick an arbitrary column width.**

#### Benefits of the Changes

More flexible font-size and line-width settings would **allow all users to configure NetNewsWire in a way that feels optimal** for their particular setup.

**Comment by vincode-io** [comment]
We are in the process of implementing #19 which will allow you full control of the that will give you full control of the Article rendering code. You will be able to create a stylesheet that gives you full control of fonts and column width.

I'm going to close this one as I'm pretty sure that will handle your problem. If you disagree, we can reopen this issue.
