### ISSUE TITLE
iOS: switch back to app: feed view changed, all unread are now read

### ISSUE THREAD

**Issue by johnnydecimal** [Ranchero-Software/NetNewsWire#3194]
Hey there. I’m on iPad (Pro 9.7”), latest iOS, NNW 6.0 (606).

- Browse feeds from ‘All Unread’. Pick article, read [article](https://www.profgalloway.com/space/).
- Get curious about Teterboro Airport, head over to Safari & Maps for a minute or so.
- Switch back to NNW.
- Am now I’m in the list for a *specific* feed – not the one whose article I was reading – and all of my unreads are now marked read.

**Comment by vincode-io** [comment]
Are you able to recreate this consistently or did it just happen one time?

**Comment by johnnydecimal** [comment]
Just the once, alas. Doesn’t look reproducible.

**Comment by brentsimmons** [comment]
Have you seen this happen again?

**Comment by johnnydecimal** [comment]
Oh sorry, I forgot this was open. GitHub should send you some sort of weekly digest of all of your old issues.

No, never again, all good. Thanks!
