### ISSUE TITLE
Internal server error upon sync with Feedbin

### ISSUE THREAD

**Issue by jzilske** [Ranchero-Software/NetNewsWire#3197]
I’m getting an internal server error while attempting to sync my Feedbin account. Their website seems to work just fine, though. I’m on v6.0 btw.

**Comment by somethingsomethingburtward** [comment]
I have the same issue. (Thanks for all the work on the app!)

**Comment by jzilske** [comment]
> Thanks for all the work on the app!

Seconded!

**Comment by boctor** [comment]
I’m also having the same issue with feedbin. (+1 on the all the effort that goes into the app!)

**Comment by boctor** [comment]
It's working properly now

**Comment by jzilske** [comment]
Yes, for me as well. Closing this.
