### ISSUE TITLE
Feature request: enhance twitter extension to display list of articles rather then tweets

### ISSUE THREAD

**Issue by markcartertm** [Ranchero-Software/NetNewsWire#3205]
I really like netnewswire. It would be great if the twitter integration would show a list of articles based on links in my twitter feed rather then the tweets themselves. I can read tweets in the twitter app. What I love about net news wire is that it gives me a list of articles based on rss. I want to read the articles on my twitter feed. This functionality was supported in an app called Nuzzle until twitter bought the company and killed the app and left the users with no alternative.

**Comment by brentsimmons** [comment]
Since Twitter integration will stop working soon — as soon as Twitter ends free Twitter API access — I’m closing this.
