### ISSUE TITLE
iOS Error - Renaming a web feed

### ISSUE THREAD

**Issue by kevinm6** [Ranchero-Software/NetNewsWire#3207]
Hi, it just happened this when I was trying to rename a feed.
Is related to something other?

![image](https://user-images.githubusercontent.com/72861758/123751191-bad3f580-d8b7-11eb-9cc2-5a731e9b105b.png)

**Comment by vincode-io** [comment]
How did you create the feed you were trying to rename? Was it dragged over from an old account or added using the dialog?

**Comment by kevinm6** [comment]
@vincode-io If I remember well was created by importing the .opml file.
I have iCloud sync enabled.
Another thing: I'm almost sure that the opml was imported on macOS, probably on a beta version.

I've noticed that I'have no problem to rename every feed on macOS, and after that I can rename it again on iOS, but it doesn't work if I do it previously on iOS.

I don't know if this can help, ask me if you need some other infos or everything

**Comment by vincode-io** [comment]
I'm not sure what happened to your iOS iCloud account, but we've seen in this issue and others that it is corrupted. Would you please remove your iOS iCloud account and add it again to see if that resolves the issue?

**Comment by kevinm6** [comment]
Ok, I'll do it and I'll let you know!
