### ISSUE TITLE
Article titles lose their link after scrolling

### ISSUE THREAD

**Issue by flxkid** [Ranchero-Software/NetNewsWire#3209]
I've been having a problem in 6.0.2 where titles of articles lose their link when I scroll. I've recorded a screen capture showing the behavior. I'm also not sure why for slashdot specifically I have that large gap at the top. Seems to be something that only happens on my slashdot feed. Maybe it's related, I don't know.

https://user-images.githubusercontent.com/6728918/124311188-36d17600-db22-11eb-94e4-1e163a56a0ee.mov

**Comment by brentsimmons** [comment]
What’s the URL of the Slashdot feed you’re using?

**Comment by flxkid** [comment]
> What’s the URL of the Slashdot feed you’re using?

rss.slashdot.org/Slashdot/slashdotMain

**Comment by brentsimmons** [comment]
I can’t reproduce this using that feed (using Feedbin and dark mode too).

Here’s an experiment to run: try making the NetNewsWire window smaller — inset from the edges on all four sides. Then select a different Slashdot article. Does the problem go away?

**Comment by flxkid** [comment]
Brent,

> I can’t reproduce this using that feed (using Feedbin and dark mode too).
> 
> Here’s an experiment to run: try making the NetNewsWire window smaller — inset from the edges on all four sides. Then select a different Slashdot article. Does the problem go away?

Yeah, looking at it more it doesn't seem to be related to a specific feed or anything, happens on all of 'em. I'm just on slashdot's feed quite a bit.

I move between a dock with a big external monitor and the laptop screen quite a bit. I think it has more to do with that. Resizing the window (in any direction) seems to fix it until it gets into that bad state again after using my dock.

**Comment by kevinm6** [comment]
Sorry @flxkid, but it seems weird that the article scroll so much from the top toolbar. 
Have you got some particular "window manager" or something other enabled when this is happening?
Or this happens always, even if NNW is the only app open?

**Comment by billsaysthis** [comment]
This issue happens for me for all feeds (using NNW 6.0.2). I can right click the title and copy the link but plain clicking the title does nothing.

**Comment by brentsimmons** [comment]
Is this still a bug?

**Comment by billsaysthis** [comment]
Not for me
