### ISSUE TITLE
Ipad Bazqux feeds not updating

### ISSUE THREAD

**Issue by twilight-moon** [Ranchero-Software/NetNewsWire#3210]
Hi, I’m using an iPad Pro and iOS NetNewsWire, using Bazqux for news feeds. I was able to add Bazqux and my feeds synched a few days ago but now it’s not synching. I can use Unread on my phone or Vienna on MacOS without issue. Thanks.

**Comment by vincode-io** [comment]
If you do a manual refresh, do you get an error?

**Comment by twilight-moon** [comment]
No error message. The progress bar moves but no new updates.

**Comment by vincode-io** [comment]
Did this clear up for you @twilight-moon? I think we must have some incompatibility with BazQux that we should talk to their team about. It seems that every once in a while it temporarily stops syncing.

**Comment by twilight-moon** [comment]
It hasn't cleared up yet. Thanks.

**Comment by DavidMunch** [comment]
Try and input your Bazqux password again, in the settings. I've had macOS NNW loose mine on several occasions.

**Comment by danieljhill** [comment]
I'm getting the same issue, but on the iPhone. If I log out and back in using my credentials the issue will temporarily correct itself and feeds will be fetched. However, a few hours later the issue starts again with no feeds being synced.

**Comment by vincode-io** [comment]
We are looking into this problem. I'm having trouble recreating it, but haven't stopped working on it.

**Comment by DavidMunch** [comment]
Any way we can help? I've seen it once on iPad OS, and about ten times on macOS. Strangely, when it happens for me, the iPad retains the password in the preferences dialog, while the macOS version doesn't. They both retain the username.

**Comment by vincode-io** [comment]
I was finally able to successfully recreate this. We had thought we were losing the API token, but that doesn't seem to be the case. It looks like BazQux expires it's API token every 14 days. We need to add code to automatically reauthorize if the API token is expired to fix this.

**Comment by vincode-io** [comment]
This has been fixed and will be in the next releases for both iOS and the Mac.
