### ISSUE TITLE
iCloud-sync not working properly when other device has not been used for several days

### ISSUE THREAD

**Issue by Thomas-U** [Ranchero-Software/NetNewsWire#3213]
In the past 3 weeks, I have experienced this several times. For this report, I set up a test and recorded it.

1. On Mac Big Sur in NNW 6.0.3b1 I had read everything, did one more manual sync and quit NNW. (screen-video)

2. On iPad I opened NNW 6.0 (not used for a week). After syncing for a while the Unread count showed 2824. (screen-video)

3. Back on the Mac, NNW showed 1702 Unread after sync. (screen-video)

4. The timeline on Mac shows that only 5 articles were really unread since I started the test at 1800 h. (screenshot)

Expected behaviour: The read status from Mac should have been synced to iPad. Instead, lots of unreads were synced back to NNW Mac. - In the past, I experienced the same with NNW on iPhone and NNW on Monterey beta.

I'll send the link to the recordings to Maurice per PM.

**Comment by vincode-io** [comment]
This was due to the sync database having records in it that it couldn't find in the regular database, so it would give up and stop the sync process. We now continue to process even when the sync database can't find records in the regular database.
