### ISSUE TITLE
iOS: Open in browser keyboard doesn't do anything

### ISSUE THREAD

**Issue by surfmonkey89** [Ranchero-Software/NetNewsWire#3215]
Choosing 'b' or "B" doesn't do anything. Appears to be the only shortcut that doesn't work. I'm on an iPad with an Apple keyboard cover, if that makes any difference.

**Comment by vincode-io** [comment]
I just tested this and it worked. Are you having problems with a specific feed or article?

**Comment by surfmonkey89** [comment]
When I hit b from:
- my list of feeds, it goes to the main page of the site/blog, and not the specific article
- any of the Smart Feeds, nothing happens at all

Hope that helps. Let me know if you want me to try anything else,

Paul

**Comment by vincode-io** [comment]
If you want the `b` shortcut key to work on a specific article, you need to select that article first.

**Comment by vincode-io** [comment]
I think I see what you are saying now. Selecting the individual article isn't working, you always go to the feed page.

**Comment by surfmonkey89** [comment]
I’m doing that. It never goes to the article, just the main page. I even deleted and re-added a feed just now to make sure - same behavior. I’m on an iPad Pro 10.5 inch, running 14.6.

**Comment by surfmonkey89** [comment]
Right. Except for in the smart feeds, which don't respond to "b" at all.

**Comment by vincode-io** [comment]
I've implemented the fix and it will be in the upcoming 6.0.1 release.

**Comment by surfmonkey89** [comment]
Thank you for the fast turnaround!

Paul
