### ISSUE TITLE
Unable to find favicon for gp.se subfeeds

### ISSUE THREAD

**Issue by celebrion** [Ranchero-Software/NetNewsWire#3216]
Especially for this one:
https://www.gp.se/nyheter/g%C3%B6teborg?rss

However, it works for their main feed - https://www.gp.se/?rss

**Comment by doamatto** [comment]
As far as I know, this isn't a bug with NNW, but rather an issue with that feed. Göteborgs would have to add an « old-fashioned » favicon on the site, which [they don't have](https://www.gp.se/favicon.ico).

**Comment by Wevah** [comment]
If I remember correctly, NNW tries to find an icon based on the meta tags of the feed's homepage URL if there isn't one referenced in the feed itself, so it shoudl probably be finding these.

**Comment by celebrion** [comment]
It works via both Reeder 5 and ReadKit on iOS though.

**Comment by Wevah** [comment]
Good to know. Looks like this should be fixed for sure, then.

**Comment by Wevah** [comment]
Taking this one to make myself do it.

**Comment by Wevah** [comment]
I think I see what's going on; the ö in the URL path is coming through unescaped and so it's turning into a `nil` `URL`.
