### ISSUE TITLE
Sync between iOS and macOS versions

### ISSUE THREAD

**Issue by jwsapp** [Ranchero-Software/NetNewsWire#3218]
I have NetNetsWire on both my Mac and my iPhone. I’ve looked, but can’t find a way to sync them. Please show me how, or if that’s not a feature, please add it.

**Comment by vincode-io** [comment]
You need to add an account with syncing capabilities. We support paid syncing services as well as free syncing using iCloud. Just go into Settings and add the account type you want.

**Comment by jwsapp** [comment]
Thanks. 

Jon

**Comment by jwsapp** [comment]
Maurice,

The iOS app isn’t showing the sync. It still has as unread articles that have been read on my Mac. I realize that there’s an iCloud lag, but it should have updated since yesterday. 



Jon

**Comment by vincode-io** [comment]
When you pull to refresh, do you let the progress bar fully finish?

**Comment by vincode-io** [comment]
Did you disable the On My iPhone account so that those articles no longer are being fetched?

**Comment by jwsapp** [comment]
Yes. Here’s a screenshot video. 



Jon

**Comment by vincode-io** [comment]
@jwsapp You need to attach video using the GitHub web interface.
