### ISSUE TITLE
Feature request for iOS: Ability to receive push notifications instantly via server rather than background refresh

### ISSUE THREAD

**Issue by Asadb123** [Ranchero-Software/NetNewsWire#3219]
NetNewsWire is a great app, it's very slick. However, using background refresh to push notifications to the device is too unpredictable and receiving notifications for a new article can take too long. It would be really great to be able to receive instant alerts when a new article is published to a feed, without the need for background refresh, especially when used for news updates. I am sure many would agree that adding this feature would make NNW more complete than it already is.

**Comment by vincode-io** [comment]
Duplicate of #2616.
