### ISSUE TITLE
Safari Extension toolbar icon color

### ISSUE THREAD

**Issue by mdzierzkowski** [Ranchero-Software/NetNewsWire#3221]
Hi. 

It is possible to change a color of Safari Extension icon on Safari toolbar? Blue is a bit too "sticking out" for me. 
Maybe use default Safari colors: light gray for active and dark, faded gray for inactive so it is consequent with the other buttons?

Regards,
Marcin Dzierzkowski

PS: Thank you for that great software! 👍🏻 M.
PPS: Looks like it has something to do with Safari 14. M.

**Comment by pdokas** [comment]
Safari colors all third party extensions with your system accent color.

**Comment by vincode-io** [comment]
As @pdokas says, this is a Safari behavior that we don't have control over.

**Comment by mdzierzkowski** [comment]
Oh, ok. Thank you.
