### ISSUE TITLE
App crash when long-pressing a feed (iOS Public Beta 3)

### ISSUE THREAD

**Issue by kepstein** [Ranchero-Software/NetNewsWire#3222]
It appears that any long-press action causes the app to crash. The intended action I'm looking for (usually clearing a feed to marking an article as read / unread works just fine it I use a menu option without long-pressing, so I'm fairly certain it's the long-press action it's self. I'm using iOS Public Beta 3.

**Comment by vincode-io** [comment]
This is already fixed in the upcoming 6.0.1 release.
