### ISSUE TITLE
Chinese need

### ISSUE THREAD

**Issue by 2ndMan** [Ranchero-Software/NetNewsWire#3229]
Translated version:
I wonder if you have any plans to launch a Chinese version. I learned about your application in the Chinese media, which has received many recommendations in China.
原文：
我想知道，您是否有计划推出中文版本？我是在中文媒体上得知了该应用，这款应用在中国获得了不少推荐。

**Comment by xingyucat** [comment]
这个功能也不复杂，感觉看久了就都认识了
