### ISSUE TITLE
Arrow keys stop working after interacting with a notification

### ISSUE THREAD

**Issue by rainwadj** [Ranchero-Software/NetNewsWire#3231]
I’m using NNW 6.0.2 on macOS Monterey beta 3.  If I’m reading articles and get a notification, then click on an action in that notification (like deleting a mail message or snoozing a calendar alert), the arrow keys in NNW no longer work (hitting them just gives me a beep), even though NNW never stopped being the foreground applications.  Not sure if this would be something you could resolve, or if it’s a bug with the macOS notification system.

**Comment by danielpunkass** [comment]
I was able to reproduce this by creating a script-based notification and invoking it with a keyboard shortcut while running NNW. The main window in NNW seems to be losing key focus, hence the selected table row, for example, is drawn in gray, as is the main window title bar. Tomorrow I'll take a closer look at whether it's something that seems like NNW could work around, or be causing somehow.

Hmm, I might have just reproduced something similar in Safari, so maybe it's bigger than NNW. I'll play around some more and see.

**Comment by danielpunkass** [comment]
@rainwadj It turns out I am only able to reproduce this by clicking on the notification itself, which causes it to activate the application that originated the notification. Can you please take a screencast of your example reproducing the bug so I can get a better sense of how it's happening for you? Thanks!

**Comment by rainwadj** [comment]
Hmm…. I swear I’m not the “cry wolf” type.  :-)

I was able to reliably reproduce this yesterday.  After I noticed it was happening, I tested it several more times to make sure.  And now that I have someone else looking at it, it’s not happening to me anymore.  :-/

If it happens again, I’ll try to get more details on the conditions, and see if I can get a screencast.

**Comment by danielpunkass** [comment]
Cool, thanks! No worries, I know how it goes with intermittent bugs. Hopefuly it was a fluke.
