### ISSUE TITLE
Feature Request: Feed Activity Dashboard

### ISSUE THREAD

**Issue by MDWolinski** [Ranchero-Software/NetNewsWire#3233]
One feature I miss from using Feedbin is the ability to see a dashboard of feeds with an activity line chart of when articles were last received.  This was a great way to see how active (or not) a feed was and to be able to clean-up feeds that haven't been updated in awhile.

Think this could be a great feature to have

**Comment by brentsimmons** [comment]
NetNewsWire of Yore has had features for helping to find dinosaurs.

**Comment by vincode-io** [comment]
Do we want to mark this as a duplicate of #1107?

**Comment by MDWolinski** [comment]
I’m cool with this being a duplicate. Didn’t see it in my search but obviously different view on what to call it.

**Comment by vincode-io** [comment]
Duplicate of #1107.
