### ISSUE TITLE
Reddit user RSS feeds don't work when Reddit extension is enabled

### ISSUE THREAD

**Issue by jgordon** [Ranchero-Software/NetNewsWire#3234]
If you try adding a Reddit user's RSS feed (i.e., https://www.reddit.com/user/NAME.rss) when the Reddit extension is enabled, NNW reports no feed is found. Disable the Reddit extension and it works again.

**Comment by kemayo** [comment]
I'll confirm this is still happening.

I *think* that a fix could be to add an exception to [RedditFeedProvider.ability](https://github.com/Ranchero-Software/NetNewsWire/blob/b52292d4590ab07616981dffd5956aec6deea15f/Account/Sources/Account/FeedProvider/Reddit/RedditFeedProvider.swift#L90)] which just stops it from saying it can handle any URL ending in `.rss`? An alternative, though more complicated, would be to make sure the feed provider understands the `.rss` URLs and translates them into the API-fetchable feeds it knows about...

**Comment by andrewkarch** [comment]
I am having the same issue. I can confirm that disabling the reddit extension does let you add reddit user's rss feeds.

**Comment by alltom** [comment]
Will disabling the reddit extension delete my existing reddit feeds, or is it safe for me to disable it just long enough to add a user feed? If not, is there any workaround?

**Comment by vincode-io** [comment]
@alltom That won't work. The feed will still be ignored when you reenable the extension. We do plan to fix this in the 6.3 release.

**Comment by andreiglingeanu** [comment]
Even if I don't have the Reddit extension anymore (I'm on 6.1.4), it seems like I'm not able to import any feeds from Reddit. I'm getting this:

https://github.com/Ranchero-Software/NetNewsWire/assets/2979628/128dd09e-5d3b-4e02-b409-43dfb729dbd6

Does it work you?
