### ISSUE TITLE
Any ETA for playing videos inside the app?

### ISSUE THREAD

**Issue by anon238** [Ranchero-Software/NetNewsWire#3238]

**Comment by brentsimmons** [comment]
It does play videos. (From YouTube, for instance.) Would you be more specific about what bug you’re seeing or feature you’d like?

**Comment by 2stepbay** [comment]
I suspect OP is referring to videos playing in the preview window.

**Comment by vincode-io** [comment]
Videos do play in articles if they have been embedded in them. I'm closing this issue, but will reopen it if we get clarification on where videos aren't playing.
