### ISSUE TITLE
JSON feeds synced through Feedbin may not retain all feed properties in NNW

### ISSUE THREAD

**Issue by nickheer** [Ranchero-Software/NetNewsWire#3239]
I [reported this bug with Feedbin](https://github.com/feedbin/feedbin/issues/647), but it appears to be a NNW issue…

I am seeing a problem with the `external_url` property when Feedbin is used as the syncing back-end.

Here's my feed and headers: https://gist.github.com/f66485073115b990ec0bafb1daec6c61

The relevant section of a sample item looks like this:

```json
"external_url" : "https://techcrunch.com/2021/07/28/calgarys-parking-authority-exposed-drivers-personal-data-and-tickets/",
"id" : "https://pxlnv.com/linklog/calgary-parking-security/",
"title" : "Calgary Parking Authority Exposed Drivers’ Personal Data and Tickets",
"url" : "https://pxlnv.com/linklog/calgary-parking-security/"
````

If I add my feed to NetNewsWire in my Mac-only feeds, the post title will go to the pxlnv.com… blog post, and it will also surface the techcrunch.com… URL that I am linking to:

![NetNewsWire screenshot](https://i.imgur.com/tfu23gM.png)

However, when I use JSON feeds with my Feedbin account in NNW, the techcrunch.com… URL is not visible in NetNewsWire. The line beginning "Link:" simply does not show up.

This happens in all similarly-formatted JSON feeds when using Feedbin as a syncing back-end. As such, I thought this was a Feedbin problem, but it appears that [Feedbin correctly parses the feed](https://github.com/feedbin/feedbin/issues/647#issuecomment-889480521), so it seems like a NNW issue.

Please let me know if I can provide anything else to help track down this bug or resolve it.

**Comment by vincode-io** [comment]
This is fixed and will be in the next iOS and Mac releases.

@nickheer We also recently added a `x-netnewswire-hide` class that will hide your Permalink that you put at the bottom of all your articles if you add it to the element. That way it won't be both at the top and bottom of your article, but will still be there for other RSS readers. This feature will also will be in the next releases of Mac and iOS.

**Comment by nickheer** [comment]
Well that was a wicked-fast response. Thanks @vincode-io!

I noticed that discussion in Slack. Much appreciated, and it reminded me to file this bug anyhow!
