### ISSUE TITLE
Summary card elides html-looking content in tweets

### ISSUE THREAD

**Issue by zellyn** [Ranchero-Software/NetNewsWire#3242]
Version 6.0.2 (6032)
Tweet: https://twitter.com/simonw/status/1422321167801610241

Expected summary:
> `TIL you can use <form enctype="text/plain"> followed by <input name='{"foo": "' value='bar"}'> to construct…etc…`

Got summary:
> `TIL you can use followed by to construct…etc…`

Image:
<img width="1099" alt="image" src="https://user-images.githubusercontent.com/33625/127942554-988b1ead-aa3f-41f3-87a0-9b572c071546.png">

**Comment by brentsimmons** [comment]
Yes. This is a super-hard problem, because if we don’t do this we end up with HTML in the timeline that shouldn’t appear.

**Comment by brentsimmons** [comment]
Since Twitter integration is going away, I’m closing this one.
