### ISSUE TITLE
Crashes on launch

### ISSUE THREAD

**Issue by splobsterman** [Ranchero-Software/NetNewsWire#3243]
MacOS, Bug Sur
NNW 6.0.2
Mac mini M1

Launch NNW and it crashes after about 5 seconds.

Crash log attached.

[NNW_Crash_log.txt.zip](https://github.com/Ranchero-Software/NetNewsWire/files/6927290/NNW_Crash_log.txt.zip)

**Comment by brentsimmons** [comment]
This is with NetNewsWire 4 by Black Pixel (not by us) which we don’t support. You can download a newer version here: https://netnewswire.com/
