### ISSUE TITLE
Pressing tab when an article is select causes selection to disappear, navigation disabled

### ISSUE THREAD

**Issue by blackketter** [Ranchero-Software/NetNewsWire#3244]
Version 6.0.2 (6032)

If I have an article selected (middle column) and press the tab key or right arrow key, the selection becomes greyed out.  At that point I can no longer use the other shortcut keys (N, R, K etc) or arrow keys to navigate.  (I prefer using the arrow keys to read my feeds because it's very quick to go back and navigate around.)

I _can_ press the tab key again and tab through the menu bar icons (in a very strange order and including some invisible ones!, see attached movie) and eventually I can tab back to the columns.

I would expect that I can navigate with tab and arrows to navigate forward and backward without getting stuck. (And that secret invisible controls would not be selected.)

https://user-images.githubusercontent.com/131679/128188184-ded2f546-c281-4449-9d73-3bc321bf0e0d.mov

**Comment by kevinm6** [comment]
When you press tab or right arrow key on an article, the focus is on the article view, you can use up and down arrow to scroll it!

**Comment by blackketter** [comment]
That's not what I'm seeing. The arrow keys don't scroll for me nor does the left arrow does take me back to the article list.  And shift-tab starts highlighting the icons at the top.  

(If I have an item selected in the article list and hit tab shift-tab will reselect the article.)

**Comment by vincode-io** [comment]
@blackketter I just verified that this works as designed and that the shortcut keys and arrow keys do work when the article has focus. Do you have an accessibility settings enabled or an other thing that could be intercepting your keystrokes?

**Comment by blackketter** [comment]
Could be. I was unable to reproduce this on a second Mac. I’ll continue to dig in and see if I can find what setting is causing this, but for now it looks like it’s specific to my machine.

**Comment by vincode-io** [comment]
Thanks for the follow up. I'm going to close this and we can reopen it if we find that there is something we can do to mitigate it.
