### ISSUE TITLE
Missing images in Reader View

### ISSUE THREAD

**Issue by rsalmei** [Ranchero-Software/NetNewsWire#3246]
Hey please, why Reader View does not display any images in several blogs?
Here is an example: http://jakevdp.github.io/blog/2012/10/07/xkcd-style-plots-in-matplotlib/

Original:
<img width="799" alt="image" src="https://user-images.githubusercontent.com/6652853/128409597-af95e629-32c8-48f4-8645-adfe8924c665.png">

In NetNewsWire's Reader View:
<img width="765" alt="image" src="https://user-images.githubusercontent.com/6652853/128409672-ababeca9-3bef-40c3-89cd-1a4854c955dc.png">

Thanks!
Awesome piece of software you have here! 👏

**Comment by rsalmei** [comment]
On the same theme, probably related, it is also missing:
- syntax highlighting on codes, which is very annoying since I mostly follow coding blogs [source](https://blog.rust-lang.org/2021/08/03/GATs-stabilization-push.html):
<img width="774" alt="image" src="https://user-images.githubusercontent.com/6652853/128411765-9efeac0c-35fd-4731-9ad8-d5490856e319.png">
<img width="738" alt="image" src="https://user-images.githubusercontent.com/6652853/128411805-8c36c0fe-f0e6-4770-97fe-a3d6b79e61ea.png">

- MathJax ([source](http://jakevdp.github.io/blog/2012/09/05/quantum-python/)):
<img width="656" alt="image" src="https://user-images.githubusercontent.com/6652853/128410701-d444f856-3547-4c84-b0ea-ee33bd8deabc.png">
<img width="721" alt="image" src="https://user-images.githubusercontent.com/6652853/128410764-5a515483-4a80-4e65-8a0f-7dc383229056.png">

- animations ([source](http://jakevdp.github.io/blog/2012/09/05/quantum-python/)):
<img width="723" alt="image" src="https://user-images.githubusercontent.com/6652853/128410939-b083b6dc-9b68-424b-8664-ec15adbeb8dd.png">
<img width="723" alt="image" src="https://user-images.githubusercontent.com/6652853/128411018-a71b3bcf-60a9-44b3-8a61-fdb7fc8d880e.png">

**Comment by vincode-io** [comment]
Reader View is a service we use and which works quite well considering what it does. It isn't perfect though and sometimes makes mistakes, thus the missing images.  The syntax highlighting is a the same thing. Reader View doesn't include the original site's CSS so the syntax highlighting won't appear.

I wish there was something more we could do for you, but Reader View works about as well as we can get it to at this time.

**Comment by rsalmei** [comment]
That's unfortunate, thanks.
