### ISSUE TITLE
Lockup after viewing video on web

### ISSUE THREAD

**Issue by joshhudnall** [Ranchero-Software/NetNewsWire#3249]
I clicked through the link in [this article](https://daringfireball.net/linked/2021/08/10/cnbc-apple-child-safety) and watched the video. When the video ended the screen dimmed and never released. I had to force quit the app. I’m not sure if it was a web glitch or something in the app, so I’m reporting it in case it’s helpful. 
![437AEDE6-E1D5-416E-9C02-0A8FDEEC7028](https://user-images.githubusercontent.com/667833/128956134-d0e36e3e-cd03-452a-8ef1-9ddb3568c449.png)

**Comment by vincode-io** [comment]
Thanks for the report. I just tested this and it didn't happen for me. I think `SFSafariViewController` must have crashed and taken down NetNewsWire. There really isn't anything we can do once we hand off control to `SFSafariViewController` and it is displaying web content for us. I'll reopen this issue if we start getting more reports and see if we need to file a bug with Apple or if there is indeed something we can do about it.
