### ISSUE TITLE
Unable to Set Browser

### ISSUE THREAD

**Issue by hybras** [Ranchero-Software/NetNewsWire#3255]
The browser dialog only allows Safari and the default browser to be set. Anything else reverts to the default browser. I have rotated my default browser amongst the options shown in the video to confirm it is not a problem with any of my browsers. 

Are there logs or debugging information I can attach?

OS: Big Sur 11.5.1

https://user-images.githubusercontent.com/24651269/129509722-89947761-d942-427b-be33-e505aa997fa7.mov

**Comment by vincode-io** [comment]
I'm not able to recreate this, but I am on Monterey. Could someone verify this problem on Big Sur?

**Comment by hybras** [comment]
Oh yes, I shouldve included that info. im on big sur

**Comment by kevinm6** [comment]
macOS: Big Sur 11.3 (20E232)
NNW   : 6.0.2 (6032)

I’m not able to recreate this.
But @hybras , could you try one thing?
1.  Quit NetNewsWire
2. Change default browser to Safari on System Preferences > General > Default Web Browser
3. Open NNW
4. Try to change default browser in NNW Settings

If this don’t reproduce this issue, on System Preferences > General > Default Web Browser set again Brave Browser and check again with NNW.

**Comment by hybras** [comment]
I have rotated through my browsers again, getting the same results as before. When Safari is the default browser, it can be set independently or with the "system default" option. When Brave / Tor / Chrome is the system default, I can _only_ use it as such, ie I can't set it independently. 

I can open links using whatever browser is currently set.

**Comment by hybras** [comment]
Unable to fix this myself. I switched my default browser to a "browser" that lets me pick which actual browser I want ([browserosaurus](https://github.com/will-stone/browserosaurus))
