### ISSUE TITLE
Twitter new lines are just a single space

### ISSUE THREAD

**Issue by ashishgandhi** [Ranchero-Software/NetNewsWire#3258]
Tweet used for example: https://twitter.com/MKBHD/status/1427404596364861443

### NNW
<img width="626" alt="image" src="https://user-images.githubusercontent.com/970540/129693867-f6f584ee-05f5-4c32-ab51-f7f6c90d60c7.png">

### Twitter
<img width="558" alt="image" src="https://user-images.githubusercontent.com/970540/129693981-8c004390-6676-44f6-af41-715ba13bc4f6.png">

### iMessage
<img width="330" alt="image" src="https://user-images.githubusercontent.com/970540/129694064-c94e87fe-6fa0-43e8-b80d-f1641706e920.png">

**Comment by vincode-io** [comment]
This has been fixed and will be available in the next releases.
