### ISSUE TITLE
Unable to find favicon for swebowl.se feeds

### ISSUE THREAD

**Issue by celebrion** [Ranchero-Software/NetNewsWire#3271]
The app (on iOS at least) is unable to find the favicon for the feed available at [https://www.swebowl.se/Lastasidor/IONF](https://www.swebowl.se/Lastasidor/IONF).

The favicon works in for example Reeder 5 on iOS, so it'd be great if this was fixed in NetNewsWire as well.

**Comment by brentsimmons** [comment]
Closing — this feed no longer exists.
