### ISSUE TITLE
Enhancement MacOS: "Screen Name" as first option when adding Twitter feed

### ISSUE THREAD

**Issue by Niels-NTG** [Ranchero-Software/NetNewsWire#3274]
I know this is the smallest of paper cuts, but when I add a Twitter feed, I usually want add another Twitter user's timeline. It would be most convenient if this was the first and default option in the "Type" list. My "Home Timeline" I will likely only add once.
<img width="340" alt="Schermafbeelding 2021-09-03 om 13 18 10" src="https://user-images.githubusercontent.com/6061595/131997367-f315a289-83ef-42c8-929b-026b097414ca.png">

My proposal: the Add Twitter Feed dialog should have the "Type" selection field in this order:
- "Screen Name" (default option)
- "Search"
- "Home Timeline"
- "Mentions"

Or alternatively: the app should remember which option is selected last time I added a Twitter feed.

**Comment by brentsimmons** [comment]
Since Twitter integration will stop working soon — as soon as Twitter ends free Twitter API access — I’m closing this.
