### ISSUE TITLE
Legacy feeds in iCloud on iOS

### ISSUE THREAD

**Issue by VilhelmR** [Ranchero-Software/NetNewsWire#3275]
Hello,

I've found an issue with syncing via iCloud, that I haven't been able to find elsewhere: When I added iCloud syncing on my iPhone (X, latest iOS), there were feeds I didn't have in iCloud syncing on my Mac anymore, that I had long since removed. I deleted all feeds from my Mac, and all feeds disappeared from my iPhone, including the ones not present on my Mac. I readded all the feeds on my Mac (imported the OPML file), and the correct feeds appeared on my iPhone. I then uninstalled and reinstalled NetNewsWire on my iPhone, and the old feeds in iCloud not present on my Mac reappeared. I redid the whole thing except importing the OPML file on my iPhone, but everything else went exactly the same.

Thank you

**Comment by vincode-io** [comment]
I'm not sure how, but it looks like your iCloud database is somehow corrupted. I'll look into it.

In the meantime, if you are ok with starting over from scratch, here is what you can do to clean things up.

1) Remove the iCloud account from NetNewsWire on all devices including your Mac
2) Delete the NetNewsWire iCloud database in System Preferences -> Internet Accounts. Select iCloud and click the Manage button in the bottom right. You can then select NetNewsWire and delete its data.

<img width="780" alt="Screen Shot 2021-09-03 at 4 43 51 PM" src="https://user-images.githubusercontent.com/16448027/132068206-c8a066a0-4fe6-4729-a331-8eb9f48d1ecf.png">

3) Add the iCloud account in NetNewsWire again on your Mac and import your OPML file
4) After your Mac is done syncing, go ahead and add back your iCloud account(s) on any device(s) you have.

**Comment by VilhelmR** [comment]
Hi,

Thank you for replying, and I followed your steps, but now I get the following:
![Screenshot 2021-09-04 at 09 33 06](https://user-images.githubusercontent.com/10095980/132086871-1ff19868-dc38-41ed-9984-e726072fb1a6.png)

Following the steps doesn't work, so for now I'm just using a local account on my Mac 👍.

Thank you 😊

**Comment by vincode-io** [comment]
You aren't able to remove and add the iCloud account in NNW?

**Comment by VilhelmR** [comment]
I think I misunderstood, sorry, I was disabling, and not removing. My bad 😔.

**Comment by vincode-io** [comment]
@VilhelmR , I'm just checking back in. Did you ever get this issue resolved?

**Comment by VilhelmR** [comment]
@vincode-io Yes, thank you :). There was an error with the data in iCloud, so with a guide on how to wipe my NWW data, I could start over :).
