### ISSUE TITLE
Slow to close with cmd + q

### ISSUE THREAD

**Issue by leonp** [Ranchero-Software/NetNewsWire#3276]
If I open NetNewsWire and read some feeds, closing the program with cmd + q results in it hanging, and often the SBOD. I can still use other programs. It does close on its own after around 5-10s.

If I open it and close without reading feeds it behaves as expected.

Early 2014 Macbook Air
Big Sur 11.5.2
Model Name:	MacBook Air
  Model Identifier:	MacBookAir6,1
  Processor Name:	Dual-Core Intel Core i5
  Processor Speed:	1.4 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	3 MB
  Hyper-Threading Technology:	Enabled
  Memory:	4 GB
  System Firmware Version:	431.140.6.0.0
  SMC Version (system):	2.12f143

**Comment by brentsimmons** [comment]
What version of NetNewsWire? (Open NetNewsWire’s About window to get the version.)

**Comment by leonp** [comment]
Sorry @brentsimmons, my bad:

Version 6.0.2 (6032)

**Comment by vincode-io** [comment]
What kind of account(s) are you using? We try to sync article read statuses on close, but that should at most take 2 seconds.

**Comment by leonp** [comment]
All my feeds come via Feedbin – no local feeds at all.

**Comment by vincode-io** [comment]
Could you provide us with a screen recording of this happening? Maybe there is something in there that we haven't accounted for.

**Comment by leonp** [comment]
WIll do. I’ll add that simply moving the cursor gets the program to quit.

**Comment by leonp** [comment]
https://user-images.githubusercontent.com/2016649/132252881-1e260c82-796c-4fd3-8dba-10a6045931e7.mov

So, at 9-10s I hit cmd+q (you’ll see the NNW menubar item change background colour). What I actually see is the SBOD. I move the cursor at about 29s, and the program quits.

**Comment by vincode-io** [comment]
I found a way to process the run loop without an event, so you shouldn't have to move your mouse anymore. This fix will be in the 6.1 release for Mac, but not the upcoming 6.0.3 release.
