### ISSUE TITLE
First articles are lost when feed updates??

### ISSUE THREAD

**Issue by rsalmei** [Ranchero-Software/NetNewsWire#3277]
In my understanding, a feed reader fetches the current feed file and parses it as posts, or articles.
In the next feed update, these articles are deduplicated and merged with the ones already fetched previously.

But what I'm seeing is, it is losing the first articles of feeds!!
For very small feeds, which return just 4 or 5 of the latest, this is a disaster...
Is this intended or a bug? If it's intended, can it be fixed?

For  example [This Week in Rust](https://this-week-in-rust.org/), which has 1 new article per week. I didn't have time to catch with it yet.
When I started it was on 400, it lost 400, 401 and 402 😞 
![image](https://user-images.githubusercontent.com/6652853/132130765-2599851b-9e3b-412b-b695-fe6f149d774f.png)

**Comment by vincode-io** [comment]
This is functioning as designed. https://github.com/Ranchero-Software/NetNewsWire/blob/main/Technotes/RetentionPolicy.markdown#local-and-icloud-accounts

We have to balance local database size with article availability and feel like we have come up with a good solution. Apologies if this doesn't work for you. We can't make everyone happy. Some people already feel like we take up too much disk space when caching articles.

**Comment by rsalmei** [comment]
When an article drops off the feed, it is dropped here too?? That's really a shame.
So the site maintainer gets to decide which articles my machine will have?
The worst part of it is, NNW is dropping UNREAD articles!! If it dropped read ones that would be OK.
Can't we get at least a preference for this? To only drop READ articles that dropped off the feed?? Please?

**Comment by rsalmei** [comment]
I just found [News Explorer](https://betamagic.nl/products/newsexplorer.html)!! Look how nice the way they do, you can't delete UNREAD ARTICLES!!
<img width="657" alt="image" src="https://user-images.githubusercontent.com/6652853/132584429-e6148f27-76fa-4c4a-b536-fb55dc42aae3.png">

This is the default config, I didn't touch it.
Unread items should have a FOREVER retention policy, or it doesn't make much sense to use a tool like this.
