### ISSUE TITLE
NetNewsWire for macOS: CloudKitAccountDelegate crash

### ISSUE THREAD

**Issue by lawgimenez** [Ranchero-Software/NetNewsWire#3283]
After running the macOS project on my machine (macOS version 11.5.2 20G95), I tried to add my iCloud account but after I canceled the accounts dialog the app stopped responding. Including the Preference dialog. So I Force Quit and then when I opened again it crashed on CloudKitAccountDelegate on line 38. It does not open anymore too.

<img width="1038" alt="Screen Shot 2021-09-13 at 11 51 57 AM" src="https://user-images.githubusercontent.com/7910468/133021411-4a0b8598-fb8c-4e3c-b8f2-bbce9e9f224e.png">

**Comment by vincode-io** [comment]
This isn't a bug in NetNewsWire. You don't have your development environment set up correctly. Please follow these instructions to get it building correctly. https://github.com/Ranchero-Software/NetNewsWire#building

You won't be able to use an iCloud account with that build configuration. If you want to contribute to the iCloud development, please sign on to our Slack and go into the #work channel. I'll help you out there.

**Comment by vincode-io** [comment]
To get NetNewsWire to launch again, you will have to manually remove the iCloud account from the Accounts folder.
