### ISSUE TITLE
Shaded toolbar on scroll for article panel?

### ISSUE THREAD

**Issue by danritz** [Ranchero-Software/NetNewsWire#3284]
Love NNW so much! Keep noticing this and wondering if it's intentional.

![CleanShot 2021-09-13 at 09 37 27@2x](https://user-images.githubusercontent.com/64102/133095557-0364032e-a981-4fc9-b9c8-b859d88ead58.png)

(shadow below toolbars when scrolling for feed listing panel and article listing panel, but not for individual articles)

Quite possible the most obnoxious request I've ever made.

My designer eye can't NOT notice stuff like this. 😬 

(I dug into what it might take to try doing this myself, but native stuff is still way outta my league)

**Comment by vincode-io** [comment]
Good eye! This is a bug in macOS Big Sur that is fixed in Monterey. Nothing we can do about it.
