### ISSUE TITLE
Cease confirmations to add to Safari Reader

### ISSUE THREAD

**Issue by john-catalano** [Ranchero-Software/NetNewsWire#3285]
I use Safari Reader. When I add articles from NetNewsWire to Safari Reader, via the share button, I am asked to confirm adding that article to Safari Reader. 

I wish there was no confirmation. Or, that I could disable such confirmation in settings.

**Comment by vincode-io** [comment]
We would love to help you out, but there isn't anything we can do about it. That dialog comes from iOS after we've handed off the URL to it. Sorry.
