### ISSUE TITLE
Support for ios12/macos10.14?

### ISSUE THREAD

**Issue by acagastya** [Ranchero-Software/NetNewsWire#3288]
Hi, I was trying netnewswire today on macos 10.14 (mojave).  Most recent versions don't work on that, iirc, it is v5.0.4 which works.  I was wondering if it is possible the newer versions can be run on macos 10.14 and ios 12?  I could use the older version for desktop, but I can't even try it on ios as it demands v13 at the very least.  If it does not depend on newer APIs, could it possibly be ported to older versions too?

**Comment by vincode-io** [comment]
We do rely on lots of API that aren't available in older versions of the OS's.

This article about OS support is a little out of date, but the essence is still accurate.
https://inessential.com/2019/10/14/netnewswire_os_compatibility_strategy

**Comment by kupietools** [comment]
It'd be nice if there was some sort of easy way to look up what the last version that works with Mojave is. Some of us still rely on 32-bit apps that were never replaced. 

I keep going further and further back and downloading and downloading and none of them seems to work. Having found this thread, I'll give 5.0.4 a try, but if that doesn't work I'm going to find some other reader.

**Comment by brentsimmons** [comment]
https://netnewswire.com/old-versions
