### ISSUE TITLE
Special case micro-blog feed discovery — add .json extension when omitted

### ISSUE THREAD

**Issue by seeegs** [Ranchero-Software/NetNewsWire#329]
Steps:
1. Click File > New Feed
2. enter `micro.blog/feeds/<yourUsername>` (or `micro.blog/feeds/<otherUsername>`)
3. click the Add button

expected: subscribe to the feed
actual: I see an error that the feed was not found.

**Comment by seeegs** [comment]
Thanks @brentsimmons, I was just wondering about adding `.json` if missing.

**Comment by vincode-io** [comment]
This is fixed and is coming in the NNW 6.0 release.
