### ISSUE TITLE
Add option to hide retweets from a Twitter feed

### ISSUE THREAD

**Issue by j-f1** [Ranchero-Software/NetNewsWire#3291]
Me [from Slack](https://netnewswire.slack.com/archives/CPNED2D7Y/p1631810543052400):

> Is there a way to remove retweets from a Twitter feed (but keep quote tweets)? It gets annoying to see the same exact tweet retweeted by a bunch of people. (Twitter’s search UI doesn’t display rewteets)

**Comment by brentsimmons** [comment]
Since Twitter integration will stop working soon — as soon as Twitter ends free Twitter API access — I’m closing this.
