### ISSUE TITLE
Systematic crash on open

### ISSUE THREAD

**Issue by lucpotage** [Ranchero-Software/NetNewsWire#3292]
When I open the app on iOS, it crashes systematically.
I need to restart my device to get a stable app. But the moment I open a link in Safari for instance, returning to the app will crash again. How can I help you find a solution to that issue?
- I sync the app with Feedly
- I added a Twitter extension synced with iCloud (4 Twitter feeds).

**Comment by vincode-io** [comment]
Which version of NNW and which version of iOS are you using?

Have you tried restarting your device? That sometimes fixes this issue.

**Comment by lucpotage** [comment]
I use it on iOS 14.7.1. I just updated NNW and it seems I don't have issues anymore. Thanks!

And yes, after restarting the device, I continued to have crashes when app is in background. I had to mark all as read to fix the issue.

I will reopen a new issue if needed. Thank you!
