### ISSUE TITLE
Suggestion: NNW during refreshing feeds

### ISSUE THREAD

**Issue by kevinm6** [Ranchero-Software/NetNewsWire#3293]
I've noticed that on my iPhone during NNW refreshing is impossible to use some buttons, I suggest to disable them during refresh:
 - Mark all as Read
 - Filter Unread

**Comment by vincode-io** [comment]
You can use those buttons during refresh. What can happen while doing a lot of database access, like during a refresh, is that these features are slower. They will happen, but they are delayed because they are asynchronous and waiting for the database to free up.
