### ISSUE TITLE
ios version can't sync twitter's picture which stared

### ISSUE THREAD

**Issue by W4J1e** [Ranchero-Software/NetNewsWire#3298]
Thanks for what a great app and what you worked  for it.

I installed NetNewsWire both my iPhone and iPad, and use icloud account. A feed which I stared on my phone, I can watch 
it(include picture) on my iPad even the source item has been deleted but not Twitter.

Such as I stared a feed from Weibo (a site like Twitter in China), even that item has been deleted but I can also watch it's picture.
It seems the loaded pictures synced with iCloud.

But as you know, we can't visit Twitter directly in China, I have to use VPN again to show pictures from twitter on my iPad which I stared and loaded those pictures on my iPhone.

It seems loaded tweets' pictures haven't sync with iCloud?

**Comment by vincode-io** [comment]
Correct. An articles images are served from the hosting web server, so if those get deleted, you won't be able to view them. They aren't cached locally and aren't synced with iCloud.

If you are seeing a difference with Twitter, please make sure you have the Twitter extension enabled in NetNewsWire on all your devices.

**Comment by W4J1e** [comment]
> 正确。. 文章图像是从托管Web服务器提供的,因此,如果这些图像被删除,您将无法查看它们。. 它们不在本地缓存,也没有与iCloud同步。.
> 
> 如果您发现Twitter有所不同,请确保在所有设备上的NetNewsWire中启用了Twitter扩展名。.

Thanks for your reply.

I tested that, iPhone get this feed with images and I stared, then I deleted the source article, both iPhone and iPad can view those pictures.

I installed twitter extension both iPhone and iPad's NetNewswire, and I will keep focus on it.

Best regards.
