### ISSUE TITLE
Feature request: Pause a subscribed feed

### ISSUE THREAD

**Issue by erik-visser** [Ranchero-Software/NetNewsWire#3304]
I would love to be able to pause a feed. Having feeds that are still there but don't update. Of course there is unsubscribing, but then it's gone from the list and the internet is a big place, finding it again when I crave it is difficult and keeping a list outside NetNewsWire is an ugly hack.

**Comment by kevinm6** [comment]
> I would love to be able to pause a feed. Having feeds that are still there but don't update. Of course there is unsubscribing, but then it's gone from the list and the internet is a big place, finding it again when I crave it is difficult and keeping a list outside NetNewsWire is an ugly hack.

Hi, I think this issue could be similar or the same as [one that](https://www.github.com/ranchero/netnewswire/issue/2837) I open some months ago, and NNW Devs reply me already

**Comment by vincode-io** [comment]
Duplicate of #2837
