### ISSUE TITLE
Subscription fails for Washington Post on Mac

### ISSUE THREAD

**Issue by mikesplaces** [Ranchero-Software/NetNewsWire#3305]
I found the RSS feeds so I can subscribe to Washington Post since I have a subscription there but each time I try to add from the RSS page, the Mac app says there is no RSS feed there. I am starting from this page.

https://www.washingtonpost.com/discussions/2018/10/12/washington-post-rss-feeds/

I also have News Explorer installed but with this app on my Mac, I can add the subscription with no problems. I have the extension for Safari activated and it will not "light up" to show I can add from there either. I would prefer to use Netnewswire if I could get Washington Post to be added.

**Comment by vincode-io** [comment]
That page has multiple RSS feeds on it. When you click on one doesn't it try to open NetNewsWire for you? For example, when I click on "Politics" on that page for that RSS feed, it prompts me to open it in NetNewsWire and I can subscribe to that RSS feed then.

**Comment by vincode-io** [comment]
Since clicking on the individual feeds works and is how that page is intended to be used, I'm going to close this issue.
