### ISSUE TITLE
Reddit video preview issue on iPadOS15

### ISSUE THREAD

**Issue by satishev** [Ranchero-Software/NetNewsWire#3309]
Since updating to iPadOS15 on iPad Air 4, when I preview videos through the Reddit extension feed - I get no picture, only sound. This is a Reddit feed of top posts (subscribed to after adding the Reddit extension) for which NNW 6.0.1 blessedly previews the images/videos directly in the app. Feeds are synced through iCloud. 
Tried:
- deleting and reinstalling NNW on iPad
- removing Reddit feeds and extension and re-adding

Videos in this feeds play fine (both sound/video) in NNW on iOS 15 on iPhone.

Any ideas?

p.s. don’t know if I have ever professed my love for this feature. SO much more efficient and useful :)

**Comment by vincode-io** [comment]
I've seen this bug too and don't know what is going on. It only happens with Reddit videos, on the iPad, with iOS 15. Even more weird, it only impacts videos that you have to manually start. Gif style videos that auto start work fine.

You can sometimes rewind the video to get it to appear. Which makes me think there is nothing wrong with the video feed. 

There isn't much we can do to influence video playback in a web view, so I'm at a loss as to how to work around this one.

Maybe there is a alternate source in the Reddit feed I can use that doesn't trigger this bug. I'll look into it.

**Comment by vincode-io** [comment]
This has been resolved in the latest versions of iOS. Please upgrade iOS if you are still seeing this issue.
