### ISSUE TITLE
[new request] local cert

### ISSUE THREAD

**Issue by dnavarrog** [Ranchero-Software/NetNewsWire#3311]
There is any possibility to sync with a self hosted freshrss server (in local lan) ?
When i try to establish a connection between NetNewsWire on iOS and my server give me an error, because i am using self signed cert 
Thanks in advace

**Comment by dhoepfl** [comment]
Copy your custom root certificate onto your device (e.g. put it on a webserver or copy it into iCloud Drive), then download/open it. iOS should offer you to install it as profile/root certificate which you can trust once it is installed.

**Comment by vincode-io** [comment]
I don't think this is a NetNewsWire issue, so I'm going to close it.

**Comment by dnavarrog** [comment]
> Copy your custom root certificate onto your device (e.g. put it on a webserver or copy it into iCloud Drive), then download/open it. iOS should offer you to install it as profile/root certificate which you can trust once it is installed.

it works! awesome!
