### ISSUE TITLE
ios app switched to starred with no user input 

### ISSUE THREAD

**Issue by crun** [Ranchero-Software/NetNewsWire#3318]
this has happened several times only this time i can vouchsafe that there was no pilot error. reading an article. not touching the ipad screen at all. app just switched to starred. as my config hides read articles, it’s difficult to impossible to get back to where i was so rudely disrupted.

not at all wanted behaviour.

my request is that you make it possible for users to remove starred entirely. it’s a feed that i’ve never used. my experience is that it just results in unwanted failures.

no idea how to duplicate this failure: it’s random best i can tell. any suggestions on how to troubleshoot welcome.

**Comment by brentsimmons** [comment]
Thanks for the report. We haven’t seen any other reports like this, but we will investigate.

**Comment by brentsimmons** [comment]
Are you still seeing this bug?

**Comment by crun** [comment]
my apologies, but i mostly stopped using the app. lost interest in the newsfeeds i was following. more to the point, lost interest in the ipad. hardly ever use the thing.

i did try the app again after getting notified by your comment the other day and didn't see the reported error. but as i said in the original report, it seemed random behaviour. i'd no idea what triggered it so i was never able to reliably duplicate it.

btw: still suggest making it possible to remove/disable the starred feed. (if that's been done, i didn't find it – sorry)
