### ISSUE TITLE
Networking?

### ISSUE THREAD

**Issue by anon238** [Ranchero-Software/NetNewsWire#3334]
I wonder how NetNewsWire - it’s my number one RSS app since launch btw - is pulling up articles. I use Private Relay and it’s not clear for me whether RSS-apps are protected by it or not.

**Comment by vincode-io** [comment]
Private Relay only works in Safari. https://support.apple.com/en-us/HT212614

**Comment by vincode-io** [comment]
Some networking traffic might be impacted in third party apps like NNW. https://developer.apple.com/forums/thread/683957?answerId=680484022#680484022

This isn't a NNW specific issue.

**Comment by vincode-io** [comment]
So reading about this some more, it does look like NNW is protected from third party trackers when iCloud Private Relay is enabled.. This is because third-party trackers rely on unsecured HTTP traffic which is protected in apps by Private Relay.

**Comment by anon238** [comment]
Thanks for that, so how does NNN retrieve their articles? When I enable Private Relay and go for example to a website that’s blocked by one of the CDNs I can read the article with reader mode, but when I click the headline to get to the website it’s routed by Private Relay. That’s because of Safari’s In-App, but it looks like that it’s still downloading it’s articles through my “normal” connection. Or am I completely wrong?

**Comment by vincode-io** [comment]
NNW works just like any other third-party application. This thread that I linked to earlier explains it better than I ever could. Pay special attention to the answers given by the Apple engineer. He knows more about this than we possibly ever could.

https://developer.apple.com/forums/thread/683957?answerId=680484022#680484022
