### ISSUE TITLE
Arow keys not accepted

### ISSUE THREAD

**Issue by shoantel** [Ranchero-Software/NetNewsWire#3337]
v6.0.3 (6035) on macOS 12.0.1

when clicking in the middle column, the whole list gets a blue highlight border but arrow keys no longer work. instead of selecting the item and loading it, the arrow key moves the highlight (blue fill) over the selected item but the item can't be selected, i.e. loaded in the right-most pane.

An app restart does not clear the bug.

**Comment by vincode-io** [comment]
@shoantel Do you have voice over or any navigation assisted technologies enabled?

**Comment by shoantel** [comment]
Not that I'm aware of.  How would I know of things I didn't knowingly enable?

**Comment by shoantel** [comment]
Ah. For some unknown reason 'full keyboard control had been enabled (not idea by what). Disabling this seemed to fix the issue, so sorry for well-intentioned—but false—alert.

**Comment by vincode-io** [comment]
I'm glad you got it figured out!
