### ISSUE TITLE
New feed articles won’t download, loading bar stuck empty

### ISSUE THREAD

**Issue by Nezteb** [Ranchero-Software/NetNewsWire#3343]
NNW iOS 6.0.2 (Build 610)

![image](https://user-images.githubusercontent.com/3588798/140867136-6ecf48d2-3845-4df2-aa28-ead40e0b6e7e.jpeg)

See above screenshot. I've tried restarting the app and restarting the phone. I've verified that I have enough storage on my phone and iCloud.

I can't find any logs or clearance local cache. This only started happening today; the last few weeks since the latest release have been fine.

Any ideas?

**Comment by stuartbreckenridge** [comment]
I think this is an iCloud issue as I am having the same issue just now.

**Comment by Nezteb** [comment]
Within five minutes of posting this, the issue has magically resolved itself despite not working all day. 😭

Closing. Have a lovely day!

**Comment by brentsimmons** [comment]
That’s the power of filing a bug!
