### ISSUE TITLE
Unable to Remove Feed from iCloud Account

### ISSUE THREAD

**Issue by stuartbreckenridge** [Ranchero-Software/NetNewsWire#3344]
I have a feed in iCloud that, when deleted, will reappear every time the iCloud account is re-enabled. I'll post the video in Slack.

**Comment by vincode-io** [comment]
Could you run this in the debugger and let me know if you are hitting this line when you delete the feed?  https://github.com/Ranchero-Software/NetNewsWire/blob/19055afeb176a4ce9714550372471c2fa9d9ed22/Account/Sources/Account/CloudKit/CloudKitAccountDelegate.swift#L222

**Comment by brentsimmons** [comment]
@stuartbreckenridge Is this still reproducible?

**Comment by stuartbreckenridge** [comment]
It’s gone for now
