### ISSUE TITLE
theringer.com items freeze the article pane

### ISSUE THREAD

**Issue by b-derosa** [Ranchero-Software/NetNewsWire#3348]
Viewing an item from theringer.com's feed often results in the article pane freezing. Requires restart to fix. Haven't seen this issue with any other feed.

feed url: https://www.theringer.com/rss/index.xml

<img width="1621" alt="Screen Shot 2021-11-10 at 9 56 44 AM" src="https://user-images.githubusercontent.com/94062471/141136815-b9a5225a-9476-412d-b487-cea7b9a5b50b.png">

**Comment by brentsimmons** [comment]
This looks like it might have something to do with Reader view.

**Comment by brentsimmons** [comment]
I’m not able to reproduce this. Maybe something has changed at theringer.com so that this bug doesn’t get tripped.
