### ISSUE TITLE
Can't Add Subreddit Feed

### ISSUE THREAD

**Issue by brijazz** [Ranchero-Software/NetNewsWire#3350]
I'd noticed that the one subreddit feed that I have in NNW wasn't updating. I deleted it and tried to re-add but I'm getting an error (note that I tried using other subreddits but got the same error). The Reddit extension is enabled, and I'm using an iCloud account.

<img width="302" alt="Screenshot_2021-11-12 08 33 53_FCcDTM" src="https://user-images.githubusercontent.com/10696709/141475713-c9529e1b-1fbd-4e8c-ba3a-e1fe9b15acad.png">

<img width="252" alt="Screenshot_2021-11-12 08 33 59_RSj8YO" src="https://user-images.githubusercontent.com/10696709/141475724-84bbd5f5-f63c-4140-8b4b-53db2c073886.png">

**Comment by vincode-io** [comment]
What happens if you remove the Reddit extension and add it again?

**Comment by brijazz** [comment]
That worked, thanks. I should mention that when I first tried to authorize my Reddit account, clicking the "Continue" button did nothing - the dialog disappeared but no authentication took place. Logging out and back into my Mac solved the issue.

**Comment by stuartbreckenridge** [comment]
@vincode-io Is this the same issue as Feedly losing its authentication?

**Comment by vincode-io** [comment]
Not likely. They use two different ways of doing OAuth.

**Comment by doctored** [comment]
got this one today too still able to add as a web feed

**Comment by dawnerd** [comment]
Could it auto add .rss if we don’t have the Reddit extension enabled?
