### ISSUE TITLE
Timeline Feed Icon sometimes fails to load on iOS

### ISSUE THREAD

**Issue by vincode-io** [Ranchero-Software/NetNewsWire#3352]
I don't know why yet, but sometimes we get the default globe icon instead of the correct Feed one. You can see in this screenshot some cells got the correct CarBuzz icon, but one didn't.

![Screen Shot 2021-11-13 at 10 14 51 AM](https://user-images.githubusercontent.com/16448027/141651134-6baaa7e8-8899-411a-9283-241f5be15624.png)
.

**Comment by stuartbreckenridge** [comment]
I’m wondering if this cascades to the widget? On occasion, it gets the globe icon as well even though favicons are available.

**Comment by vincode-io** [comment]
I don't think it is related. The Widget doesn't have a chance to get the Notifications when the images become available like the Timeline does. That's why the Widget gets the globe sometimes. Even disk access is asynchronous and the first hit will miss, but there is no Notification to tell the Widget that it was read from the disk.

It is like the Timeline is missing that initial Notification too, but it looks like it is observing it to me and handling it correctly. I might be missing something.

**Comment by vincode-io** [comment]
Read [this](https://twitter.com/smileyborg/status/1406769460032114689) for the details of the iOS 15 UITableView prefetching changes.
