### ISSUE TITLE
Not parsing this feed correctly?

### ISSUE THREAD

**Issue by iJKTen** [Ranchero-Software/NetNewsWire#3356]
Is it not parsing this feed correctly? https://formidable.com/rss.xml I see some missing posts in the app but RSS shows that those entries are present.

**Comment by vincode-io** [comment]
Are you using a syncing service or the On My Device account?

**Comment by brentsimmons** [comment]
Do you have it set to hide read items? Any read items wouldn’t appear, if so

**Comment by brentsimmons** [comment]
Do you have it set to hide read items? Any read items wouldn’t appear, if so

**Comment by iJKTen** [comment]
I am using On My Device!
Nope, haven't turned on Hide Read Articles.

**Comment by vincode-io** [comment]
This isn't a valid feed and is duplicating its GUID which is most likely causing NNW to drop some articles. I recommend contacting the site administrator to see if they can correct their RSS feed.

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fformidable.com%2Frss.xml
