### ISSUE TITLE
Feeds not syncing between desktop and phone via iCloud

### ISSUE THREAD

**Issue by trijste** [Ranchero-Software/NetNewsWire#3358]
Hi, I've noticed an issue but am unsure if it's reproducible. I added a feed (MacSparky) to my desktop iCloud folder, but it didn't appear on my phone. I added it to my phone, and it disappeared from my desktop. I added it to my desktop, and it disappeared from my phone—a bit of a cat and mouse. So far, I've decided to keep it on my phone, but I would like my lists to sync. Is this known and fixable?

**Comment by vincode-io** [comment]
I haven't seen this issue before. Are you sure you don't have Hide Read Feeds enabled?

**Comment by trijste** [comment]
Hi, Thanks for replying. When I was first investigating, I left to show all feeds on and watched as the feed disappeared after adding it on my phone.
