### ISSUE TITLE
404 for release notes tag/ios-6.0.2

### ISSUE THREAD

**Issue by idodeclare** [Ranchero-Software/NetNewsWire#3365]
https://github.com/Ranchero-Software/NetNewsWire/releases/tag/ios-6.0.2

**Comment by AndrewHaglund** [comment]
Tapping “Release Notes” in Setting goes to GitHub 404 as of version 6.1 for iOS. It currently points to https://github.com/Ranchero-Software/NetNewsWire/releases/tag/ios-6.1

**Comment by brentsimmons** [comment]
Here’s where it should go: https://github.com/Ranchero-Software/NetNewsWire/releases/tag/iOS-6.1-6110

**Comment by vincode-io** [comment]
@brentsimmons Since you changed to adding the build to the tag, do you want us to change how we generate the Release notes URL in the Mac and iOS apps?

**Comment by brentsimmons** [comment]
Yes — let’s add the build number to the release notes URL.

**Comment by vincode-io** [comment]
Done. Since this is shared code we need to also include the build number in the Mac builds.
