### ISSUE TITLE
Why would NNW iOS need to access the local network?

### ISSUE THREAD

**Issue by dbarros** [Ranchero-Software/NetNewsWire#3366]
When opening the iOS (6.0.2 (610)) app today, I saw the following alert. I'm just curious as to why the app would need to access the local network?

<img width="373" alt="image" src="https://user-images.githubusercontent.com/1286/145306723-eb6fb091-5eae-4684-acf5-c2ae533fc478.png">

**Comment by brentsimmons** [comment]
I wonder if this is iCloud syncing? (Meaning that this is in Apple’s code.) I don’t think there’s anything else in the app that would ask for that.

@vincode-io what do you think?

**Comment by kielgillard** [comment]
My team has seen this issue before. We never quite figured out why [but we found this](https://developer.apple.com/forums/thread/663874) in our adventure and our best guess is something deep within the system is making this alert bubble up.

**Comment by vincode-io** [comment]
@brentsimmons I'm sure it iCloud that is triggering it. My suspicion is that we are loading some content in WKWebView that might be trying to find things on the local network.

@dbarros This isn't something that we are accessing intentionally. Please click "Don't Allow" if you ever see it again. Could you also let us know what version of iOS you are using and what type of Account you are using?

**Comment by dbarros** [comment]
> @dbarros This isn't something that we are accessing intentionally. Please click "Don't Allow" if you ever see it again. Could you also let us know what version of iOS you are using and what type of Account you are using?

@vincode-io I have not security concerns. or anything of the sort, with this app and seeing that alert. It was just something curious.

I have a Feedly account, and my version of iOS is 15.1.

**Comment by stuartbreckenridge** [comment]
Could it be Handoff/Continuity that is doing it?

**Comment by stuartbreckenridge** [comment]
I'll answer my own question: no.

**Comment by kevinm6** [comment]
@vincode-io I don’t think it comes from NNW, I think is automated from Apple.

I’ve seen the “Local Network Request” alert today when I was trying to add a LAN IP on NNW.
@dbarros could it be possible that you click or open an url or add a web feed with a local IP inside NNW?

**Comment by dbarros** [comment]
> I’ve seen the “Local Network Request” alert today when I was trying to add a LAN IP on NNW. @dbarros could it be possible that you click or open an url or add a web feed with a local IP inside NNW?

@kevinm6 Not to my knowledge. But I'll keep this in mind if I see the alert again.

**Comment by vincode-io** [comment]
@dbarros Are you still using NetNewsWire and if so, are you still getting this alert?

**Comment by dbarros** [comment]
> @dbarros Are you still using NetNewsWire and if so, are you still getting this alert?

@vincode-io I've not seen this for a long while now. Thanks.
