### ISSUE TITLE
Feature request : delete old articles automatically

### ISSUE THREAD

**Issue by F3000** [Ranchero-Software/NetNewsWire#3368]
create an option to delete feed automatically e.g. when a specific amount of unread items is reached

**Comment by vincode-io** [comment]
We do delete articles automatically. Have you seen our [Retention Policy](https://github.com/Ranchero-Software/NetNewsWire/blob/main/Technotes/RetentionPolicy.markdown)?

**Comment by farmostream** [comment]
> We do delete articles automatically. Have you seen our [Retention Policy](https://github.com/Ranchero-Software/NetNewsWire/blob/main/Technotes/RetentionPolicy.markdown)?

While some feeds do delete, others do not.

**Comment by vincode-io** [comment]
Are you saying that the retention policy isn't being followed by the application?

**Comment by gaemarkus** [comment]
Slightly off topic, but could this be optional? 
I use NNW as an instagram client among other things and it feels off that I can't see posts older than three months.

**Comment by vincode-io** [comment]
@gaemarkus NetNewsWire is designed to be a news reader. We don't consider it appropriate to use as an internet archive, which is why we have the Retention Policy that we do.

I'm glad that you can use NNW to view Instagram, but it isn't intended to be an Instagram client, which is why it doesn't work perfectly in that capability.

**Comment by gaemarkus** [comment]
@vincode-io thanks for the answer, I understand that.
If anyone is interested in my usecase, I'll just Star every post I want to keep ^^

**Comment by vincode-io** [comment]
Closing this issue since we do delete articles automatically.
