### ISSUE TITLE
Unable to add Twitter Developer RSS feed

### ISSUE THREAD

**Issue by amadejpapez** [Ranchero-Software/NetNewsWire#3370]
Hi! I am trying to add Twitter Developer Announcements RSS feed that they reference [here](https://developer.twitter.com/en/updates/stay-informed): https://twittercommunity.com/c/announcements/22.rss

When adding it to NetNewsWire as a web feed I get that it is unable to find the feed.

The URL is working, so I am not sure if the issue is on the app's or Twitter's side.

**Comment by vincode-io** [comment]
This URL is returning a 403 Forbidden response code with a message in the body that says, "Crawler is not allowed!". They probably are whitelisting the User Agent string and don't like the NetNewsWire one.

**Comment by vincode-io** [comment]
I've posted a feedback to Twitter about their developer portal. There isn't anything more we can do about this. We just have to wait for the Twitter to fix it on their end.

https://twitterdevfeedback.uservoice.com/forums/930250-twitter-api/suggestions/44588205-allow-rss-readers-to-read-the-rss-feed

**Comment by amadejpapez** [comment]
Thank you very much for looking into this. I never had an issue with adding a feed to NetNewsWire, so I assumed that Twitter is the problem. Well let's hope they change this.
