### ISSUE TITLE
Images are not downloaded from one of the feeds that I follow

### ISSUE THREAD

**Issue by kunaguvarun** [Ranchero-Software/NetNewsWire#3371]
Hi,

I follow [Of Dollars and Data](https://ofdollarsanddata.com/feed/). The articles that appear are short and if I select always use reader view then images are not downloaded from the articles. The app gets only text. This happens on both iOS and on MacOS.

**Comment by vincode-io** [comment]
The Reader view will tries to extract the article from the page using some complicated heuristics that will ignore advertising images. Sometimes it will mistake valid images for advertising images and not include them in the extracted article.

Unfortunately there isn't anything we can do about this. The Reader view is a service we use that is using code that we don't control. For this feed you will want to open the article in Safari to get the full page contents.
