### ISSUE TITLE
iOS: folder sorted by feed, not chronologically

### ISSUE THREAD

**Issue by felibb** [Ranchero-Software/NetNewsWire#3374]
When I open a folder in iOS client, I see all available items from the first feed in the folder, then scrolling down a lot, I see items from the second feed, etc. This is quite a useless way to sort — if one wants to see a full feed, they can just un-collapse the folder and find that feed. I did not find a way to change the sorting.

Conversely, In macOS client opening a folder displays items from all feeds in that folder chronologically. This is the way it should be by default IMO.

**Comment by vincode-io** [comment]
Did you check the Group by Feed option in the Settings by mistake?

**Comment by felibb** [comment]
Yes. That was it. Damn.

Thanks!
