### ISSUE TITLE
Article in feed displayed multiple tomes

### ISSUE THREAD

**Issue by no0ID** [Ranchero-Software/NetNewsWire#3376]
When using this feed: https://www.janes.com/feeds/news each selected article is displayed many times - continuously is repeated underneath

**Comment by vincode-io** [comment]
What kind of account are you using? On My Mac, Feedbin, or something else?

**Comment by brentsimmons** [comment]
Is this still happening with this feed?

**Comment by brentsimmons** [comment]
I can’t reproduce this. Kept the feed in my On My Mac account for a few days. The feed updated multiple times without any seeming reruns.
