### ISSUE TITLE
Can't Add Feedly Account on Monterey

### ISSUE THREAD

**Issue by jesusdeveloper** [Ranchero-Software/NetNewsWire#3378]
Running macOS Monterey 12.1
Running NetNewsWire Version 6.0.3 (6035)

1 - Open "Preferences", then "Accounts".
2 - Click "Feedly" to add Feedly account.
3 - "Waiting For Access To Feedly" dialog appears in NNW.
4 - "NetNewsWire wants to use Feedly.com to sign in." dialog appears w/Safari logo.
5 - Click continue on the Safari dialog, but then nothing happens.

Preferences remain open, but Feedly account not added because Safari never opens the Feedly login page.

I switched my default browser to Microsoft Edge for Mac (in both NNW and System Preferences) but step 4 always shows the Safari logo in the dialog box. Default browser is not being honored during this request, but is honored for options under the NNW "Help" menu. ("Website", "Bug Tracker", etc).

Same problema like here: https://github.com/Ranchero-Software/NetNewsWire/issues/2480 

Is there a macOS workaround? Or does this require an NNW change?

![alt text](https://i.ibb.co/nzJ10zR/Captura-de-pantalla-2021-12-26-a-las-16-47-14.png "Logo Title Text 1")

![alt text](https://i.ibb.co/gRrLj2d/Captura-de-pantalla-2021-12-26-a-las-16-47-22.png "Logo Title Text 1")

**Comment by vincode-io** [comment]
Monterey has a bug that requires you to sometimes reboot to get the OAuth windows to appear. Please reboot and try again.

**Comment by jesusdeveloper** [comment]
> 

this is correct!
I rebooted my mac and tried again and then opened Safari for authentication.
Now it works great!
Thanks!

One last thing, I can't find the light mode, it's only in dark mode and in preferences I can't see to change dark mode or light mode. Is there that option?

Thanks!

**Comment by vincode-io** [comment]
Light/dark mode isn't a configuration option on the Mac. Sorry.

**Comment by jesusdeveloper** [comment]
> Light/dark mode isn't a configuration option on the Mac. Sorry.

Thank you for your very quick response !!
Hopefully this feature can come in the future.

Thanks and fantastic program !! =)
