### ISSUE TITLE
Can’t add a feed because no feed was found.

### ISSUE THREAD

**Issue by zkd8907** [Ranchero-Software/NetNewsWire#3379]
I have a feed: `https://www.solidot.org/index.rss`, and it cannot be added to NetNewsWire. App says "Can’t add a feed because no feed was found.". I cannot get more information or log from the dialog.

**Comment by Thomas-U** [comment]
I tried it with the same result. That means to me: There is no working feed under this address.

I opened index.rss in BBEdit and it contains a lot of asian characters.

Maybe that is the cause or there is a mistake in the file-header.

[index.rss.zip](https://github.com/Ranchero-Software/NetNewsWire/files/7781047/index.rss.zip)

**Comment by brentsimmons** [comment]
When I try to download the feed from NetNewsWire or via the command line, the server returns a 403 Forbidden response instead of the feed.

The server is probably looking at the user-agent string and deciding only to serve the feed to some apps and not others.

In other words — it’s a bug on their server, not in NetNewsWire.

**Comment by zkd8907** [comment]
@brentsimmons 
Thanks a lot. Is there a way to allow me to check the log from app, so that I can locate the reason by myself?

**Comment by brentsimmons** [comment]
There isn’t a log. What I did to debug this was to use curl on the command line, and then I used the Mac app Proxyman to see the traffic to/from NetNewsWire.

**Comment by zkd8907** [comment]
Got it, thanks again. I will try to contact the provider of this rss to locate the issue.

**Comment by UjuiUjuMandan** [comment]
@brentsimmons Excuse me, but what's the UA of NetNewsWire? Maybe an option to modify it? It seems the server would properly response for any `Mozilla/5.0` UAs, that's why my Thunderbird can fetch it.

**Comment by brentsimmons** [comment]
The user agent is `NetNewsWire (RSS Reader; https://netnewswire.com/)`. We don’t plan to make that configurable (we have too many settings as it is). Instead we encourage people to report bugs to feed providers.

**Comment by UjuiUjuMandan** [comment]
They seem removed restrictions recently.
