### ISSUE TITLE
CSS not applied to feed item content

### ISSUE THREAD

**Issue by nogira** [Ranchero-Software/NetNewsWire#3380]
If the HTML content contains CSS styling in `<style>` tags (used to style the feed item's content), none of the CSS is applied to the HTML content.

While this probably happens with all feed formats, the feed format I used is [JSONFeed](https://www.jsonfeed.org/version/1.1/), with the content being formatted as HTML as the `content_html` JSON property.

I have confirmed the content renders correctly if I copy the HTML directly from the feed to a HTML file and open the HTML file in a web browser.

**Comment by vincode-io** [comment]
We intentionally strip styling that will interfere with our built in styles and create readability problems.

Could you provide a feed URL and let us know which styles you see being ignored? I'll verify that we are in fact doing this to improve the legibility of the rendered article.
