### ISSUE TITLE
Clicking on links opens 2 Firefox windows

### ISSUE THREAD

**Issue by OddHouseGames** [Ranchero-Software/NetNewsWire#3383]
Steps to reproduce:
1. Click on a link in NewNewsWire with Firefox as your default browser and without having Firefox open yet.

Expected action:
1. A single Firefox window will open

Actual action:
1. 2 Firefox windows open, a blank one, and one with the content.

macOS Monterery 12.1
NetNewsWire 6.0.3 (6035)

**Comment by vincode-io** [comment]
All we can do is ask Firefox to open a URL. We can't control how it does it or how it launches. This is a Firefox issue and there is nothing we can do to help here.
