### ISSUE TITLE
Feature Request [Remove title from article text]

### ISSUE THREAD

**Issue by jaddel** [Ranchero-Software/NetNewsWire#3384]
Example:

Title: The engineering behind the James Webb Teleskop is...

Text: The engineering behind the James Webb Teleskop is so amazing thats it should be shown to alien live if it exists.

I'm following an RRS feed and since there are no proper titles the first few lines of the article text will be used. This is not a problem if you just read a few posts but after a while it becomes very frustrating to always search for the point to skip the "title" so that you don't have to read it twice. 
I'd like to suggest a feature to remove the words being used for the title from the article to make the reading experience more fluent.

**Comment by vincode-io** [comment]
Could you share the feed URL that you are seeing this with and what kind of account you are using?

**Comment by jaddel** [comment]
> Could you share the feed URL that you are seeing this with and what kind of account you are using?
sure. 

http://blog.fefe.de/rss.xml?html

**Comment by brentsimmons** [comment]
NetNewsWire is displaying it as it is in the feed. I don’t want to do a work-around for every weird feed.
