### ISSUE TITLE
Feedly sign in issue on M1

### ISSUE THREAD

**Issue by ironicmoka** [Ranchero-Software/NetNewsWire#3387]
OS: macOS Monterey 12.1
Machine: M1 apple silicon
Software version: 6.0.3 (6035)

I tried today to install NetNewsWire on my new machine. Everything seems to work fine except for the Feedly integration in the Accounts tab: looks like no browser window is opening after the _“NetNewsWire.app” wants to use “feedly.com” to sign in_ dialog. I clicked on Continue with no luck.

I also tried to quit the app and change the default system browser (tested with Safari and Brave) but nothing changed.

**Comment by vincode-io** [comment]
This is a Monterey bug. You can reboot your computer to resolve it.

**Comment by ironicmoka** [comment]
You were right! It worked.
