### ISSUE TITLE
Cannot add either Twitter or Reddit extension

### ISSUE THREAD

**Issue by distrob** [Ranchero-Software/NetNewsWire#3394]
When trying to add one of those extensions (M1 Pro, latest official releases of Monterey and NetNewsWire), after pressing continue on the adding screen, nothing happens. Tried to reinstall NNW, but it didn't work. 
![Screenshot 2022-01-09 at 10 12 43](https://user-images.githubusercontent.com/18249849/148676706-13ca48e1-d977-447e-b8a9-1ce86ea4e913.jpg)

**Comment by brentsimmons** [comment]
I think this is that Apple bug — restarting your Mac should fix it.

**Comment by distrob** [comment]
Thanks, restarting fixed the issue.
