### ISSUE TITLE
Feed cannot be added in iOS app

### ISSUE THREAD

**Issue by thombet** [Ranchero-Software/NetNewsWire#3396]
Hello,

First of all thanks for the great work on the iOS app!

I am not able to add the feed `https://ledrenche.ouest-france.fr/feed/` in the iOS app (version 6.0.2 Build 610 - iOS 15.0.2) whereas the feed is displayed correctly in my browser (Firefox with [Want my RSS](https://addons.mozilla.org/fr/firefox/addon/want-my-rss/) extension).

The error message is: `The feed couldn't be found and can't be added.`.

Is it a known bug?

Thank you in advance!

**Comment by vincode-io** [comment]
What kind of account are you using to sync with?

**Comment by thombet** [comment]
None. I try to add the feed in a folder which is in the category "On my iPhone".

**Comment by vincode-io** [comment]
It will add the feed if you remove the trailing slash.

**Comment by thombet** [comment]
I'm sorry but it didn't work even without the trailing slash. (You meant ˋhttps://ledrenche.ouest-france.fr/feed` right?)

**Comment by vincode-io** [comment]
Yeah, but without the trailing space.

**Comment by vincode-io** [comment]
![image](https://user-images.githubusercontent.com/16448027/148843311-58773506-8ec9-404a-8883-472383bb7621.png)

**Comment by thombet** [comment]
Very strange that it worked for you whereas it didn't for me.

The value I tried:
- https://ledrenche.ouest-france.fr/feed (without trailing space)
- https://ledrenche.ouest-france.fr/feed/

The same error is reported for each of them.

**Comment by thombet** [comment]
@vincode-io any idea what I could try to solve my problem?

Would reinstalling the app help?

Thanks in advance!

**Comment by vincode-io** [comment]
The only thing I can think of is that the server is redirecting you based on your locale or language settings. If you set your locale and language on your iPhone to US English are you able to add it then?

This is a real long shot, but I'm grasping at straws here. I've been able to add that feed multiple times without problem on the exact same version of NNW that you are using.

**Comment by thombet** [comment]
Thanks for the new suggestion but it didn't help to set region and language to US English...

Is there a way to turn on debug logs or something similar to get more information about the error?

**Comment by vincode-io** [comment]
Have you tried the new 6.1 Beta yet? Maybe it will help. Again, I am just grasping at straws here.

We don't have any way to capture that kind of info via logs at this time.

**Comment by thombet** [comment]
Thanks again to keep on trying to fix my problem!

I installed 6.1 beta but I was still not able to add the feed.
Then I deleted the app completely (with all its data), reinstalled the 6.1 beta but still no luck 🙁

I will try on other devices and I will post back here.

(By the way it was not easy to find the Test Flight link to install the beta: I used a link in an old blog post (from September). Maybe you should add the Test Flight link to subscribe to beta versions in the Readme of this repository as people checking the source code are usually also interested in installing beta versions 😉)

**Comment by thombet** [comment]
I tested on another iPhone running on iOS 15.0.1 with NetNewsWire 6.0.2 and I got the same error as on my phone. This iPhone is configured with French as language and France as region so maybe it is related to locale as you guessed since it works on your phone.

But it is very strange that it doesn't work with French locale as it is a French-only feed.

**Comment by vincode-io** [comment]
Language and region don't seem to be the problem. I changed them to French/France and was able to still subscribe to the feed. 

You mentioned that you might be browsing the code. Are you a developer? If so, can you snoop the http requests using Proxyman, Charles, or some other kind of http monitor? That could tell us what we are getting back from the server. It might be blocking you based on IP or something.

**Comment by vincode-io** [comment]
@thombet Did you ever get a solution to your problem?

**Comment by thombet** [comment]
Nope. Just tried again with 6.1 build 6104 and there is still the problem on my phone.

I didn't take the time to try what you suggested in your last comment.

**Comment by brentsimmons** [comment]
Are you still seeing this bug?

**Comment by thombet** [comment]
Yes.
I tried again with version 6.1.1 (build 6114) and iOS 15.4.1 and the same error appears.

**Comment by brentsimmons** [comment]
Would you go into Terminal, copy-and-paste the following, then hit return…

```curl -I https://ledrenche.ouest-france.fr/feed/```

…then reply here with what it says?

(The above command gets the HTTP response header from the server for that feed.)

**Comment by thombet** [comment]
This is the response:

```
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Thu, 09 Mar 2023 23:18:45 GMT
Content-Type: text/html
Content-Length: 162
Connection: keep-alive
Location: https://ledrenche.fr/feed/
```

But how does it relate to the iOS app?

**Comment by brentsimmons** [comment]
The redirect response is not surprising (and is fine). Let’s try it again with the new URL:

```curl -I https://ledrenche.fr/feed/```

**Comment by thombet** [comment]
It returns:

```
HTTP/1.1 403 Forbidden
Date: Fri, 10 Mar 2023 08:04:31 GMT
Content-Type: text/html; charset=iso-8859-1
X-Request-ID: 575963303
Cache-Control: no-cache
Vary: Accept-Encoding
X-CDN-Pop: rbx1
X-CDN-Pop-IP: 51.254.41.128/25
X-Cacheable: Cacheable
Connection: keep-alive
```

May I ask how the response on my machine may be different than the response on your machine?

**Comment by brentsimmons** [comment]
When I try that on my Mac, I get:

```HTTP/2 403 
date: Sat, 11 Mar 2023 04:30:49 GMT
content-type: text/html; charset=iso-8859-1
server: Apache
```

…but I can also add the feed to NetNewsWire on my Mac! And I can add it to NetNewsWire on iOS.

Here’s my theory: their server is looking at some combination of things — user agent, IP address (maybe determining location), and who knows what else — and is returning a 403 in some cases.

There’s nothing we can do about it — it’s a bug on their end, unfortunately. I wish I could help more!
