### ISSUE TITLE
Possible license violation by App Store App (FeedIt)

### ISSUE THREAD

**Issue by joshqou** [Ranchero-Software/NetNewsWire#3403]
Hi, it seems that the App Store App [FeedIt](https://apps.apple.com/gb/app/feedit/id1527181959) is using code from NetNewsWire (likely is a fork of an older version) without respecting the MIT license

### NetNewsWire
![Screenshot 2022-01-17 at 14 06 50](https://user-images.githubusercontent.com/97894002/149783253-4b830672-a57a-4c44-9ff1-7e7cbbb1980d.png)

### FeedIt
![Screenshot 2022-01-17 at 13 41 23](https://user-images.githubusercontent.com/97894002/149782909-23f8b354-7373-4c4a-965e-98e72bbb9204.png)

### NetNewsWire
![Screenshot 2022-01-17 at 13 46 34](https://user-images.githubusercontent.com/97894002/149780920-020e90a3-a277-4da4-b18e-c5a200aedb53.png)

### FeedIt
![Screenshot 2022-01-17 at 13 45 48](https://user-images.githubusercontent.com/97894002/149780979-a144f553-4f0a-4f6c-b379-a84ed2a2b398.png)

### NetNewsWire
![Screenshot 2022-01-17 at 14 08 47](https://user-images.githubusercontent.com/97894002/149784347-60b14602-e3b7-4d67-be6d-d00fa913914d.png)

### FeedIt
![Screenshot 2022-01-17 at 14 08 24](https://user-images.githubusercontent.com/97894002/149784404-f42f27f2-c8b6-4e41-b4ce-c41f41d76c05.png)

### NetNewsWire
![Screenshot 2022-01-17 at 13 45 03](https://user-images.githubusercontent.com/97894002/149781396-b894c9b6-f7ab-4d3d-ae99-cc803c0069c3.png)

### FeedIt
![Screenshot 2022-01-17 at 13 55 29](https://user-images.githubusercontent.com/97894002/149781522-a035ff22-d18d-48d0-a281-96134094442a.png)

As the MIT license requires given credit, the app is in violation of NetNewsWire's licence.

## Additional notes
- The User-Agent is not changed, still reports as `NetNewsWire (RSS Reader; https://netnewswire.com/)` to servers.
- The [Developer's Website](https://tylerdlawrence.net) [(archive)](https://archive.is/Ep5j8) does not mention that the app is a fork of NetNewsWire, nor is NetNewsWire mentioned at all.
- About App dialog has been modified to remove contributor's credits, and to change the copyright author.
- [App Store Page](https://apps.apple.com/gb/app/feedit/id1527181959) [(archive)](https://archive.is/GWCdv)
- No "Tyler Lawrence" has contributed to NetNewsWire from a quick search through the NetNewsWire contributors
- An inactive [Tyler Lawrence](https://github.com/tylerdlawrence) GitHub account exists, which hosts a [FeedIt repository (iOS?)](https://github.com/tylerdlawrence/Feedit-RSS-Reader), and a fork of NetNewsWire.
- All "Help" menu links have been scrubbed, potentially because they would otherwise all direct to NetNewsWire
![Screenshot 2022-01-17 at 13 41 34](https://user-images.githubusercontent.com/97894002/149786100-ea220881-2294-4f27-883c-6407ddc81dcb.png)
![Screenshot 2022-01-17 at 13 27 38](https://user-images.githubusercontent.com/97894002/149786060-0b86f654-3ca4-4c8a-9e95-074b971f5c76.png)

**Comment by brentsimmons** [comment]
Thanks so much for reporting this!

I’m considering the best first step, and it’s probably to report this to Apple. I’m prepared to take additional steps, of course. I have many options.

**Comment by brentsimmons** [comment]
I have reported this to Apple.

**Comment by joshqou** [comment]
FeedIt no longer appears on the App Store. [(archive)](https://archive.ph/mU5W7)
