### ISSUE TITLE
Occasional hangs with shares to Messages

### ISSUE THREAD

**Issue by bluefacedpixie** [Ranchero-Software/NetNewsWire#3405]
Sometimes this works, sometimes it doesn't (sorry no pattern I can see).

0. Mac (M1, Air and mini), Version 6.0.3 (6035), OS 12.0, 12.0.1, 12.1
1. Browsing feeds, go to share, choose one of the "recent" messages share contacts (near bottom of share menu)
2. Message box pops up, to field filled, URL in message, Cancel and Send buttons unresponsive and won't dismiss
3. Some Mac menu things work, Help, About, New Folder etc

Note:
4. quit NetNewsWire (this works)
5. relaunch and reshare works...

<img width="1027" alt="image" src="https://user-images.githubusercontent.com/57326256/150199761-5fd97ffa-8a77-405f-8d35-0311ea56f657.png">

**Comment by vincode-io** [comment]
This dialog is provided by macOS and the problem with the buttons is probably another Monterey bug.

**Comment by vincode-io** [comment]
What do you think could be different? We don't even have control over which application is selected in the share sheet. All we do is tell the operating system to share this URL and it handles the rest.

**Comment by bluefacedpixie** [comment]
Not sure. Is it possible the url packaging? Is that all you send? Or
something to do with the return of the first one.  It is super strange. And
it’s pretty obvious something Apple as NNN is still working and responding
to menu in the background but the semi-modal has captured the mouse and
doesn’t work.

Maybe it is a Radar but it does seem to only be NNN.

G

**Comment by bluefacedpixie** [comment]
I can dump something if needed.

**Comment by brentsimmons** [comment]
It’s not every day I run across another person who subscribes to My Ballard. NetNewsWire itself calls Ballard home. :)

Is this is a bug that you’re still seeing?

**Comment by bluefacedpixie** [comment]
Brent

Without being cyber-stalky I’ve known of the similarities for a while, can’t remember when initially, maybe Vesper (or before). Have seen you speak at CocoaConf in the past.  I’m also in tech but am now one of those software execs who vaguely remembers coding.

As for this bug I trained myself out of trying this (sharing from phone or doing the olde copy and paste) but I will certainly give it a try in the next week or so and let you know.

-g

**Comment by bluefacedpixie** [comment]
Folks

I e tried this for the last few weeks when I’ve remembered and not had the
bug, so whatever it was I think you can call it closed!

Happy times.

G

**Comment by brentsimmons** [comment]
Reopening because this needs additional verification.
