### ISSUE TITLE
Does NNW Sanitize HTML?

### ISSUE THREAD

**Issue by teddybradford** [Ranchero-Software/NetNewsWire#3410]
Does NetNewsWire sanitize raw HTML content from feeds? And if not, should it?

From Mozilla’s [Readability docs](https://github.com/mozilla/readability#security):

> If you're going to use Readability with untrusted input (whether in HTML or DOM form), we strongly recommend you use a sanitizer library like DOMPurify to avoid script injection when you use the output of Readability. We would also recommend using CSP to add further defense-in-depth restrictions to what you allow the resulting content to do. The Firefox integration of reader mode uses both of these techniques itself. Sanitizing unsafe content out of the input is explicitly not something we aim to do as part of Readability itself - there are other good sanitizer libraries out there, use them!

**Comment by vincode-io** [comment]
Could you explain more why an RSS reader would need to protect against XSS attacks? They are usually addressed using server side validation. I'm not sure that we would want to run an XSS sanitizer against every article in the off chance that it would contain unverified content.

**Comment by teddybradford** [comment]
I wasn't sure how NNW renders HTML. If a malicious script was added to an item's content field in a subscribed RSS feed, would that script execute when NNW renders that post?

**Comment by brentsimmons** [comment]
I don’t know what a script could do in NetNewsWire that would be malicious. I don‘t think it could even show an alert. It’s a very different sandbox than a browser.

**Comment by teddybradford** [comment]
I did not realize that. Okay, makes sense. Thank you!

**Comment by brentsimmons** [comment]
There is a pref to turn off JavaScript for Mac. We’ll be bringing that to iOS soon.
