### ISSUE TITLE
Keyboard not appearing in integrated browser on iPadOS

### ISSUE THREAD

**Issue by roefer** [Ranchero-Software/NetNewsWire#3416]
When opening a webpage on iPadOS, the integrated browser does not open the touch keyboard if a text field is selected. For instance, it is not possible to open the bugtracker (basically this page) and edit the filter text. This is only possible using an external keyboard. However, I am pretty sure that the touch keyboard appeared in the past in these situations.

**Comment by waiemwor** [comment]
I got this issue too. But the keyboard is back to work normally after I updated iPadOS to 15.3.

**Comment by vincode-io** [comment]
@roefer Could you please verify that this issue is resolved in iPadOS 15.3? If it is not, I will reopen this issue.

**Comment by roefer** [comment]
Yes, it works again. Thank you.
