### ISSUE TITLE
iOS 6.2 | UI | Centralise New Article Notification Management

### ISSUE THREAD

**Issue by stuartbreckenridge** [Ranchero-Software/NetNewsWire#3418]
Allow notifications to be managed centrally, instead of feed-by-feed, via the inspector. This would remove the need to either go via the Inspector or via the feed context menu to change notification preferences.

![Monday, 24 Jan 2022 06:54:50](https://user-images.githubusercontent.com/7046652/150703820-8137b7a2-fb76-4ef9-9751-a4b458635d25.png)

**Comment by vincode-io** [comment]
What would this look like on macOS?

**Comment by stuartbreckenridge** [comment]
@vincode-io I **wouldn't** look at News on the Mac for inspiration. Instead, I am thinking of an additional preference pane (like the right-hand side here). The _currently open websites_ section would be replaced with an account name and then underneath each feed, with a toggle on the right...

<img width="904" alt="Screenshot 2022-01-25 at 21 22 47" src="https://user-images.githubusercontent.com/7046652/150984979-3bae5231-0006-4fd3-a629-eb501c7aae82.png">
