### ISSUE TITLE
Is TestFlight supposed to be open for iOS?

### ISSUE THREAD

**Issue by deviantintegral** [Ranchero-Software/NetNewsWire#3419]
I wanted to try a development build to try out the new feature to open feed links in Safari and not the in-app browser. https://netnewswire.com/test-ios links to https://testflight.apple.com/join/wpedPMRR, but that link says the app isn't accepting new users. Is there another link to join, or is it intentionally closed?

**Comment by brentsimmons** [comment]
That message was incorrect. It was just that there wasn’t a current TestFlight build — now there is. If you try it again, it should work.
