### ISSUE TITLE
Reader View Symbol

### ISSUE THREAD

**Issue by stuartbreckenridge** [Ranchero-Software/NetNewsWire#3424]
The Reader View symbol has inconsistent line thickness when compared to other characters in the tab bar. 

Should we switch to the SF newspaper symbol for consistency? 

![image](https://user-images.githubusercontent.com/7046652/150964312-92df6201-3da8-4869-8ca8-78221aaa4d90.jpeg)

**Comment by vincode-io** [comment]
The line thickness looks the same to me. What am I missing?

**Comment by stuartbreckenridge** [comment]
It's more obvious in dark mode 

![image](https://user-images.githubusercontent.com/7046652/151069522-a9039655-1d2b-423c-8d26-7121821905ff.jpeg)

**Comment by vincode-io** [comment]
If you are using `AppAssets.articleExtractorOffSF` for that new menu you should be fine.

**Comment by stuartbreckenridge** [comment]
That fixed it.
