### ISSUE TITLE
Twitter Extension Limits

### ISSUE THREAD

**Issue by konopielko** [Ranchero-Software/NetNewsWire#3427]
Hi, is there a limit of how many tweets the twitter extension pulls in a given time? I added multiple twitter feeds via screen name and now its taking ages to load the contents - some of the feeds are still empty and once in a while it loads about 20 tweets from one of them. In the meantime the home timeline twitter feed is working flawlessly. I am using icloud account and I tried re-adding the extension. On my mac it also happens but the amount it loaded is different.
Is it a bug? Or is it supposed to work this way?

**Comment by vincode-io** [comment]
The Home feed is limited to the last 100 entries and all other types of Twitter feeds are limited to 20 entries. This is the same on iOS as it is on the Mac.

**Comment by konopielko** [comment]
I am not talking about the amount of entries but about the rate limits - it takes much longer for new tweets to appear via screen name than via home timeline

**Comment by vincode-io** [comment]
There aren't any rate limits on out side. We are dependent on when the Twitter API gives us the data.
