### ISSUE TITLE
Support twitter links in feeds

### ISSUE THREAD

**Issue by Kamik423** [Ranchero-Software/NetNewsWire#3428]
So, this is a very specific issue I am having…

I am subscribed to a HackerNews RSS feed (for reference: https://hnrss.org/frontpage?points=300). It’s default content is formatted like this

```
Article URL: https://twitter.com/RealSexyCyborg/status/1486526916433641472

Comments URL: https://news.ycombinator.com/item?id=30095733

Points: 330

# Comments: 308
```

Linking to both the HackerNews discussion as well as the article they are discussing. The URL however goes to the article, not the discussion. I use reader mode here because then I get the article’s content — the thing I actually care about. Frequently however the referenced “articles” are tweets. The reader-mode online tool then fails due to Twitter blocking things (see attached screenshot). It would be cool if in this particular use case (twitter link + reader mode) it could just use the Twitter extension to show the tweet’s content.

![8E637B26-F871-4433-A012-FBD3FE199B06](https://user-images.githubusercontent.com/16278233/151352100-3b641e63-0ec3-4c90-b59b-09df9f756782.jpeg)

**Comment by brentsimmons** [comment]
Since Twitter integration will stop working soon — as soon as Twitter ends free Twitter API access — I’m closing this.
