### ISSUE TITLE
Images in Twitter quote tweets [Bug]

### ISSUE THREAD

**Issue by konopielko** [Ranchero-Software/NetNewsWire#3429]
If there is an image in a quote tweet it doesn't load - only the quoted tweet contents and the text from the comment - not the commented image

**Comment by vincode-io** [comment]
What version and on what platform are you using? Could you provide the Feed URL so that I can verify what you are seeing?

**Comment by konopielko** [comment]
I am using version 6.0.2 on iOS. I created an example:
https://twitter.com/sycx4wswtm
![image](https://user-images.githubusercontent.com/61689919/151481062-2b377f83-0841-409c-916c-61b090d317f9.jpeg)
![image](https://user-images.githubusercontent.com/61689919/151481131-2458a59c-c44b-4fa1-b170-06dd60a6b477.jpeg)

**Comment by vincode-io** [comment]
This has been fixed in the upcoming 6.1 release. You can verify it using TestFlight or wait until 6.1 is released.

**Comment by vincode-io** [comment]
Thanks for the good error report. I thought it was fixed, but wanted to verify that we were talking about the same bug.

**Comment by konopielko** [comment]
I just checked out the testflight version and it is indeed fixed - thanks!
