### ISSUE TITLE
Custom fonts for themes in iOS

### ISSUE THREAD

**Issue by nicksherman** [Ranchero-Software/NetNewsWire#3443]
First of all, I would like to say how ecstatic I am that custom themes are now back in NetNewsWire. It was the main feature I had missed from the old NNW. Testing it out so far it seems to work wonderfully. It's especially nice to be able to use custom fonts via @font-face, but I noticed the iOS app doesn't seem to support @font-face rules the way that the desktop app does. I've tried referencing font files on a server via a typical web URL, as well as bundling the font files directly in the .nnwtheme file, but nothing seems to work.

Is it possible to use custom fonts in themes on the iOS app? And if not is there a way to allow for that?

Thanks again!

**Comment by stuartbreckenridge** [comment]
Fonts can be included as base64. See this repo for an example: https://github.com/stuartbreckenridge/NewsFax/releases/tag/1

**Comment by nicksherman** [comment]
Ah, good to know, thanks for the tip! Is it possible to also allow for normal linked files, either bundled in the theme package or – better yet – on a server, the way it works on the desktop app?

**Comment by stuartbreckenridge** [comment]
I haven't tried, but I don't believe so.

**Comment by vincode-io** [comment]
Closing this since we have a solution.

**Comment by nicksherman** [comment]
That might be premature … When I just tried base64 encoded fonts in the theme CSS it still doesn't work on iOS. I've tested with both WOFF and TTF variants with no success. I also tried installing the theme from the repo linked above but it only results in a  error (The file "info.plist" couldn't be opened").

**Comment by nicksherman** [comment]
(I would also argue that only supporting base64 encoded fonts isn't a full solution, but I'll be happy with anything at this point :)

**Comment by nicksherman** [comment]
PS: In case, like me, you were suspicious that maybe I didn't do my base64 encoding properly, I don't think that is the issue because it works as expected on the desktop app.

**Comment by brentsimmons** [comment]
Apple has considered fonts as a possible security threat, and it’s possible we may be stymied on iOS.

**Comment by stuartbreckenridge** [comment]
We have two themes using custom fonts with base64 encoding and they are working fine on both iOS and macOS. What font is it that you're trying to use?

**Comment by nicksherman** [comment]
The font I'm trying to use is called [HEX Franklin](https://hex.xyz/HEX_Franklin/). It’s an in-progress variable font I'm working on. As a fun side note, the `font-variation-settings` I've specified in my CSS seem to be working as intended on the backup system font (because the iOS system fonts are implemented as variable fonts).

**Comment by nicksherman** [comment]
I also just did a test using Source Sans from Adobe to make sure it wasn't my font that was the issue, and that didn't work either. Attaching that here for reference:
[Custom_Font.nnwtheme.zip](https://github.com/Ranchero-Software/NetNewsWire/files/8006807/Custom_Font.nnwtheme.zip)

If it makes it easier to test, this link should theoretically prompt you to install the theme from that zip:
[netnewswire://theme/add?url=https://github.com/Ranchero-Software/NetNewsWire/files/8006807/Custom_Font.nnwtheme.zip](netnewswire://theme/add?url=https://github.com/Ranchero-Software/NetNewsWire/files/8006807/Custom_Font.nnwtheme.zip)

**Comment by stuartbreckenridge** [comment]
Custom font seems to work for me...

![image](https://user-images.githubusercontent.com/7046652/152616898-24e023d8-0e74-4550-89a2-13a67a850ccd.png)

**Comment by nicksherman** [comment]
The custom font you are seeing there is the system fallback font (San Francisco). Compare it to [Source Sans](https://fonts.adobe.com/fonts/source-sans) and you will see it is definitely not Source Sans.

**Comment by nicksherman** [comment]
It should look something more like this (from a screenshot of the same theme on the desktop app)

![Screen Shot 2022-02-04 at 18 36 51](https://user-images.githubusercontent.com/1265313/152617172-2d1932c8-7c19-4f3e-8302-8ee6a87964ec.png)

**Comment by stuartbreckenridge** [comment]
ok. I will play around and see if I can see anything wrong.

**Comment by nicksherman** [comment]
Thanks, I appreciate it!

One thought that just crossed my mind: Maybe the two themes you mentioned that use custom fonts aren't actually using @font-face rules but are just referencing the names of local system fonts?

**Comment by stuartbreckenridge** [comment]
No. They are both custom and not available via the system.

**Comment by nicksherman** [comment]
Ah, so there is hope yet!

Are those themes you mentioned available anywhere? I looked under the hood of the themes that come with the app (Appanoose, Promenade, and Sepia), and they all seem to be using standard macOS/iOS system fonts like Charter and Avenir without any @font-face rules, base64-encoded or otherwise.

**Comment by stuartbreckenridge** [comment]
https://mynameisstuart.com/netnewswire-themes/

Scroll to the bottom of this page and download newsfax.

**Comment by stuartbreckenridge** [comment]
@nicksherman 

Your issue is in lines 492 to 495 of your `stylesheet.css`:

```css
.fontSize {
        font: -apple-system-body;  /*  Remove this line and fonts will behave as expected on iOS. */
	font-size: [[font-size]]px;
}
```

**Comment by stuartbreckenridge** [comment]
![Simulator Screen Shot - iPhone 13 Pro Max - 2022-02-05 at 09 47 48](https://user-images.githubusercontent.com/7046652/152624125-8ddf3426-ce59-454a-a1ba-55e9200806ca.png)

**Comment by stuartbreckenridge** [comment]
As always - toy around with CSS until it works, then run fast and run far!

**Comment by nicksherman** [comment]
Ah ha! I had only been searching for the `font-family` property to change and hadn't considered the `font` shorthand property. Not only does this work now, but it also seems to work with remotely hosted web fonts. Thanks so much!
