### ISSUE TITLE
Twitter feeds not auto or manually updating

### ISSUE THREAD

**Issue by climardo** [Ranchero-Software/NetNewsWire#3450]
NetNewsWire 6.1 Build 6103
I am using iCloud but have also tried using 'On My iPhone' and the result is the same. After ~ 2pm, most of my Twitter Feeds stop updating. Manually updating does not resolve the problem. Whether feeds are in folders or root does not matter. I also tried deleting the app and installing the stable version from the app store but the problem continues.
The next day the feeds begin updating normally. **Am I hitting a limit?** I have 16 Twitter feeds in here, some of them are searches, but most are individual accounts.

**Comment by vincode-io** [comment]
Those look ok to me, but I see that not all of them have enough volume to know for sure that they have stopped updating at a certain time.

Are you sure you are seeing Tweets on the Twitter website that aren't appearing in NetNewsWire?

**Comment by climardo** [comment]
I am sure. The next time I see the issue (likely later today), I will add another comment here with a link to the the tweet and the feed URL. Anything else that I should add?

**Comment by vincode-io** [comment]
That should do it. Thanks for your help with this.

**Comment by vincode-io** [comment]
One thing to note is that we only pull 20 Tweets on each refresh. That Walter Bloomberg account is Tweeting out so fast that you could end up missing Tweets if you aren't syncing often enough.

**Comment by vincode-io** [comment]
I'm just saying that you could end up with skipped Tweets on that account. You should still get new ones if you manually refresh.

**Comment by climardo** [comment]
It's happening. Latest example:
Tweet: https://twitter.com/txmctrades/status/1491143726877790208?s=21
Feed: https://twitter.com/txmctrades
Screenshot: 
![1AF6B09C-13A8-44E3-9309-AB5858491E70](https://user-images.githubusercontent.com/19438277/153069455-a3c7eb13-ca73-465f-b316-87309208e019.jpeg)

**Comment by vincode-io** [comment]
It could be that Twitter feed timed out when accessing it. Did you try more than once to manually refresh?

(I did test that Twitter feed and the Tweet showed up for me.)

**Comment by climardo** [comment]
I tried refreshing multiple times, I force closed the app, I restarted my iPhone, I deleted and redownloaded the app (beta, test flight) and the problem continues. The problem even appears on the stable (App Store) app. Here is my exported OPML: https://github.com/climardo/personal/blob/main/Subscriptions-iCloud.opml

**Comment by vincode-io** [comment]
So that Tweet never showed up?

**Comment by climardo** [comment]
Right, none of my Twitter articles are newer than 1:58pm EST right now except for this one from feed URL: `https://twitter.com/search?q=from:whale_alert btc OR eth "🚨🚨🚨" -"unknown wallet to unknown"`
Article: https://twitter.com/whale_alert/status/1491155779713437696

**Comment by vincode-io** [comment]
If you switch off your WiFi and use cellular data, what happens?

**Comment by climardo** [comment]
No real change. I refreshed a bunch of times and got 2 more articles.
![Uploading C436683C-B5C8-4DA0-80EC-988DD2A30431.jpeg…]()

**Comment by vincode-io** [comment]
Was one of them the missing TXMC one?

**Comment by climardo** [comment]
Nope, see attached (didn't work last time)
![CBA83BA7-FA35-4276-A117-01EF259DCCB3](https://user-images.githubusercontent.com/19438277/153077943-4044cf20-aadc-417d-9a0b-62ef1390a3c7.jpeg)

**Comment by vincode-io** [comment]
That screenshot isn't of the TXMC feed. Did that feed ever catch up?

**Comment by vincode-io** [comment]
Are you able to use the official Twitter app to see new Tweets? I'm trying to figure out where your API calls are getting blocked at.

**Comment by climardo** [comment]
Yes, I can see new tweets on Twitter without issue. Today I created a list
for just these accounts to verify what I've been telling you.

**Comment by vincode-io** [comment]
I'm not sure what is happening, but I suspect it might be something with your Twitter account. Do you have other apps that can possibly be accessing your Twitter account (other than the official app) that might be using up your API limits?

To see if it is something related to your Twitter account, you could create a test account. Then disable your current Twitter extension and enable a new one with the new test account.

**Comment by climardo** [comment]
![B9BC5437-7F5E-4CF8-93E6-31830B9FA116](https://user-images.githubusercontent.com/19438277/153082449-7f7c7991-cf16-456e-a269-fb94c86e101d.png)
Nothing else. Also just tried another account (extension) and no difference.

**Comment by vincode-io** [comment]
I've got no idea what is happening at this point. I'm sure that it isn't our API keys. I'm having no problem getting updates on the Twitter feeds from the OPML file you supplied.

If you are able to use something like Charles Proxy or Proxyman to see what the Twitter API are doing that would be helpful. No worries if you don't know what that means.

If I think of anything else to try to diagnose this, I'll let you know.

**Comment by climardo** [comment]
I will try to use proxman (never used it before, looks easy enough) later and give an update. Thanks for looking into this and responding as much as you have

**Comment by climardo** [comment]
1. Proxyman is pretty awesome, thanks for mentioning it. I'm familiar with packet captures and headers and this is really neat. Will probably use it again at some point in the future. 
2. Getting 429 too many requests error for all /1.1/statuses/user_timeline.json API calls. Searches continue to work.
3. There appears to be an app-level rate limit for this, not sure how it's applied. https://developer.twitter.com/en/docs/twitter-api/v1/tweets/timelines/api-reference/get-statuses-user_timeline
4. See screenshot, I can share more if needed but prefer to keep the oauth and sensitive data private 
![373A0028-0858-470E-858F-39A1B986A3E4](https://user-images.githubusercontent.com/19438277/153113317-eaa915f2-3e60-4535-86cb-da4905a1e68f.png)

**Comment by vincode-io** [comment]
Yeah, Proxyman is pretty awesome.

Thanks for debugging this. It does indeed look like we are hitting the API resource limits. I'll see if we can apply for elevated limits. I'm still at a loss as to why we weren't seeing the same 429 response codes.

**Comment by climardo** [comment]
And just to make sure my phone isn't doing something I'm not aware of, settings > privacy > app privacy report > app network activity / netnewswire:
![6CFD0EE1-CED4-4467-8945-A59AB3710565](https://user-images.githubusercontent.com/19438277/153118177-ea50a689-fd23-4593-928c-43ae231ef660.png)

This is probably higher than usual thanks to today's testing. Will have to check another day.

**Comment by climardo** [comment]
![A02962F8-FD09-4839-BF63-0B52B3544BD9](https://user-images.githubusercontent.com/19438277/153118389-7369682e-05b4-4204-879d-0f51281ad0aa.png)
Correct screenshot ^

**Comment by climardo** [comment]
I can't find anything in my phone that would be making additional requests. I'm going to delete the app for now and get back to it on Monday. Hopefully the 24 hour rolling limit is all the way back to 0 by then

**Comment by climardo** [comment]
Thanks for your time with this. I reached out to Twitter too but got no response 🤷‍♂️

**Comment by daiwei43211** [comment]
I am same to you!
Ipados ios do not work auto/mannual
I just do not know why!
Macos is ok

**Comment by climardo** [comment]
I haven't found the culprit yet and Twitter Support has not responded to my request for help. As stated by @vincode-io , I think it must be related to my IP address, even if it failed while on cellular data.

**Comment by vincode-io** [comment]
@daiwei43211 Try disabling and reenabling your Twitter extension on your iPad.

**Comment by climardo** [comment]
No change on this issue, but I added the accounts to a list and subscribed to the list as a Twitter feed. Problem solved.

**Comment by vincode-io** [comment]
I'm going to close this one as we didn't make any progress on it and it doesn't seem to be happening to anyone else.

If we get more info on it or can recreate it again, we can reopen this ticket.

**Comment by climardo** [comment]
Thanks for your help!

**Comment by quinncomendant** [comment]
FWIW, I'm experiencing this issue too.

**Comment by brentsimmons** [comment]
NetNewsWire has been suspended by Twitter. We will no longer be able to download Twitter feeds.

**Comment by brentsimmons** [comment]
https://nnw.ranchero.com/2023/04/07/twitter-has-stopped.html
