### ISSUE TITLE
netnewswire Feedly  login in 

### ISSUE THREAD

**Issue by song-dq** [Ranchero-Software/NetNewsWire#3452]
this is a bug, which doesn't login in feedly;

iPhone : ISO 15.0
version: 6.0.2

**Comment by vincode-io** [comment]
I understand that English probably isn't your first language, but I need more details to understand the problem you are having. 

I just tested the Feedly sign on and it was working fine. At what point in the process is it failing for you?

**Comment by song-dq** [comment]
Thank you
the problem has been solved, due to network problems
