### ISSUE TITLE
Font in new theme is missing accented letters

### ISSUE THREAD

**Issue by schriftgestalt** [Ranchero-Software/NetNewsWire#3469]
As you can see in the attached screenshot, the umlauts (Ä, Ü) are rendered with a fallback font.
<img width="687" alt="Screen Shot 2022-02-14 at 11 43 26" src="https://user-images.githubusercontent.com/174660/153849307-c410ab5c-4991-47d8-a4b6-7c73c9a41a09.png">

I quickly added the accents for (most) western European languages. I can add some more to cover at least the common European Latin based languages.
[ModeSeven.ttf.zip](https://github.com/Ranchero-Software/NetNewsWire/files/8060285/ModeSeven.ttf.zip)

**Comment by stuartbreckenridge** [comment]
If you have the time, @schriftgestalt, it'd be appreciated. Otherwise, I'll look to include what you've attached.

**Comment by stuartbreckenridge** [comment]
And thank you for testing NetNewsWire.

**Comment by schriftgestalt** [comment]
Here is a version that has fairly good coverage:
[ModeSeven 2.ttf.zip](https://github.com/Ranchero-Software/NetNewsWire/files/8061330/ModeSeven.2.ttf.zip)
