### ISSUE TITLE
Cannot use "Extensions" on the Mac with Safari, never opens auth page

### ISSUE THREAD

**Issue by tjluoma** [Ranchero-Software/NetNewsWire#3470]
Basically, whenever I try to add either Twitter or Reddit via the "Extensions", NNW acts like it is going to open a page in Safari but it doesn't. The only way that I can add Twitter or Reddit is via the iOS app.

[I made a screencast of this problem](https://user-images.githubusercontent.com/26965/154189693-76834a91-31eb-4a82-b4b5-e7597dd9ecea.mp4) because I'm not sure how to explain it any better than what I have above, and I thought it might be useful to see the problem in action.

This is on an M1 Mac mini running macOS version 12.2.1 (21D62) and the latest version of NNW for Mac.

If I have left out any useful information, please let me know.

**Comment by tjluoma** [comment]
Strangely, I found that if I changed my default browser to Microsoft Edge, NNW was able to open the page and add Twitter and Reddit.

I'm not sure why it didn't work in Safari.

**Comment by vincode-io** [comment]
This is a known problem in macOS 12. Restarting the operating system also works.
