### ISSUE TITLE
Incorrect feed list layout when going from post list to feed list

### ISSUE THREAD

**Issue by jaanus** [Ranchero-Software/NetNewsWire#3475]
NNW 6.1 (Build 6103), iPhone 11 Pro.

## How to reproduce

1. Make sure you are looking at the article list of any feed.
2. Force quit the app.
3. Restart app. It opens to the same article list as before, as expected.
4. Tap top left back button OR use left edge swipe, to go from article list to feeds list.

## Observed

Layout is incorrect. The icon of the feed you were looking at is visible, feed title is blank, and the feed title is used incorrectly as folder title.

![IMG_8875](https://user-images.githubusercontent.com/184253/154426454-0dd45825-b592-460c-a56c-92c1e3030152.PNG)

## Expected

![IMG_8876](https://user-images.githubusercontent.com/184253/154426470-541ccd60-9c41-41dc-b02e-655fab7de4e3.PNG)

Correct layout. In my case, I can fix this by collapsing and expanding the “Feedbin” container that contains all the feeds.

**Comment by stuartbreckenridge** [comment]
This is not reproducible in 6.2 (where we've modernised the UI).

**Comment by kevinm6** [comment]
@jaanus Sorry, but I can’t reproduce on 6.1 (Build 603) with iCloud sync.

**Comment by jaanus** [comment]
I can reproduce it 100% with Feedbin.

**Comment by vincode-io** [comment]
State restoration animation was interacting with building the sidebar. I fixed this and it should be resolved in the next 6.1 beta release.
