### ISSUE TITLE
Request: Image Previews from Articles

### ISSUE THREAD

**Issue by noahmaranesi** [Ranchero-Software/NetNewsWire#3476]
### Hello!

One of my favourite 'features' (not necessarily a feature) from the Reeder apps is the ability to show — and change the size of — image previews in the article list.

Here's how the latest version of Reeder 5 handles this:

| None | Small |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/12670516/154526725-296f6028-6cb1-46ec-997f-460b546f2f9f.png" /> | <img src="https://user-images.githubusercontent.com/12670516/154524406-66937a18-5832-47f1-8ade-8ba8a5699a43.png" /> |

| Medium | Large |
| --- | --- | 
| <img src="https://user-images.githubusercontent.com/12670516/154524409-13481240-23aa-4e65-a933-dca6beaedd11.png" /> | <img src="https://user-images.githubusercontent.com/12670516/154524411-44daa484-3469-46e5-ae09-a164b3fe6f3d.png" />

Would this be something you would consider implementing into NNW? I understand it would be low priority.

Thanks for your time.

**Comment by kevinm6** [comment]
Are you asking for the same feature of this #1551 ?
Could it be a duplicate issue of that?

If yes, NNW developers already reply there

**Comment by noahmaranesi** [comment]
Yes, thank you. Sorry for wasting time.
