### ISSUE TITLE
Add Account fails when Brave Browser is system default

### ISSUE THREAD

**Issue by markbrownsword** [Ranchero-Software/NetNewsWire#3478]
Trying to add Feedly account fails on `Continue` (nothing happens) when Brave Browser is system default.
<img width="372" alt="AddAccount" src="https://user-images.githubusercontent.com/10730429/154618337-fd1ecfb8-c93f-4083-8534-6fd5c4d58871.png">

**Comment by kielgillard** [comment]
There's an issue with macOS Monterey where you need to restart your Mac for this to work. At the risk of sounding like a jerk, I wonder: if you turn it off and on again, does it work?

**Comment by vincode-io** [comment]
Thanks for the heads up. We're away of the macOS Monterey bug.
