### ISSUE TITLE
Retention Policy Clarification

### ISSUE THREAD

**Issue by Alex-Vasile** [Ranchero-Software/NetNewsWire#3480]
Here is our policy for future reference. 

https://github.com/Ranchero-Software/NetNewsWire/blob/main/Technotes/RetentionPolicy.markdown

_Originally posted by @vincode-io in https://github.com/Ranchero-Software/NetNewsWire/issues/961#issuecomment-1049097858_

Under "Local and iCloud Accounts" it says:
"as with sync systems, starred articles are kept forever."

But under "Database cleanups to do while running". It says "When processing a feed, delete articles that no longer appear in the feed — unless a feed comes back empty (with zero articles); do nothing in that case".

This does not explicitly mention starred articles. Are starred (read or unread) articles from a feed kept by NetNewsWire, even if the feed no longer contains them?

**Comment by pdokas** [comment]
Yep:

<img width="382" alt="Untitled" src="https://user-images.githubusercontent.com/190134/155395116-6e0ab859-ba56-4784-8a64-ffa4139ae8cd.png">

**Comment by Alex-Vasile** [comment]
May be worth updating that policy to make it explicit for Local/iCloud sync in the same way it's explicit for web-based sync systems.
