### ISSUE TITLE
Links to the full article

### ISSUE THREAD

**Issue by schriftgestalt** [Ranchero-Software/NetNewsWire#3488]
Some articles on some feed contain a link to read the full article on their website. (https://www.loopinsight.com/feed/, https://boingboing.net/feed). Every time I click that link, specially on the iPhone, I think it would be nice if that could be a button below the text. I understand that there is no standard how those links are not standardized so it might be a bit tricky. 

Maybe if there is a link at he end of the article and that links to a page with the same domain as the feed it could add a class to it and then a theme could style it as needed? I played around with the CSS a bit and this is what I came up with (my CSS is a bit rusty so I didn't manage to center the button). 
![Simulator Screen Shot - iPhone 13 mini - 2022-02-28 at 11 23 10](https://user-images.githubusercontent.com/174660/155966529-96b9a5e9-55cc-4b07-b592-72bfa9468073.png)

And I had a look at the code but didn't find a good spot where to do the html manipulation.

**Comment by stuartbreckenridge** [comment]
You can tap the article title to get to the full article.

**Comment by stuartbreckenridge** [comment]
This is something that will largely be resolved in the upcoming Themes feature. Theme developers can put links where they want them.
