### ISSUE TITLE
Highlight quotes

### ISSUE THREAD

**Issue by gerwitz** [Ranchero-Software/NetNewsWire#349]
I would love to have integrated highlight management. Problem is, I know of three good services for this, and none seems to have API support for creation:

- Instapaper notes ("[highlights](https://www.instapaper.com/api)")
- [Highly](https://www.highly.co/) (no documented API, but could be reverse-engineered and they seem open to evolving)
- Clippings.io (Kindle-specific)

In an ideal "indie" world, I'll be able to highlight text and generate a Micropub [quotation](https://indieweb.org/quotation) request to an endpoint of my choosing.

**Comment by brentsimmons** [comment]
If there is ever some kind of service for this, we could consider it. We can create a ticket specifically for that service when that happens.
