### ISSUE TITLE
Unable to add Feedly/Twitter/Reddit account via webpage on M1 Mac

### ISSUE THREAD

**Issue by proinsias** [Ranchero-Software/NetNewsWire#3494]
I'm trying to add my Feedly account to NetNewsWire, and I cannot get the authentication to work. I expect to be brought to the Feedly.com website to give my permission to use my Feedly account, but nothing happens.

Feedly is the only account where I don't just enter my credentials. Instead when I click on the Feedly icon, I get the following popup message (see screenshot below):

Waiting for access to Feedly
A web browser will open the Feedly login for you to authorize access.

And then right away I get another popup:

“NetNewsWire” wants to use “feedly.com” to sign in.
This allows the app and website to share information about you.

When I click on 'Continue' in the second popup window, nothing happens.

I expect to be brought to the Feedly.com website to give my permission to use my Feedly account, but nothing happens.

I'm using v6.0.3 (6035) on macOS Monterey 12.2.1 (21D62) on an M1 Mac. I also tried the latest beta build v6.1b4.

<img width="664" alt="image" src="https://user-images.githubusercontent.com/2073530/157907380-704b72f6-2c70-474e-884e-51d9d8728276.png">

**Comment by proinsias** [comment]
Actually, I just tried to add the Twitter and Reddit extensions and have the same issue. I see a relevant popup, but 'Continue' has no effect.

**Comment by proinsias** [comment]
I just tested this on my Intel Mac with the same versions for macOS and NetNewsWire, and it works as expected.

So maybe it's a M1-specific issue?

**Comment by proinsias** [comment]
Never mind. Quitting both Safari and Netnewswire multiple times did the trick.

**Comment by dng2403** [comment]
Hi, I'm having a similar issue, the difference is there is a pop-up window open (MS Edge) but it is blank. The address bar show: about:blank as well.
I tried this with adding Feedly and Twitter. Same issue. Have tried restart multiple time
