### ISSUE TITLE
Can’t ass RT news (possibly due to DDoS protection) 

### ISSUE THREAD

**Issue by arekscode** [Ranchero-Software/NetNewsWire#3495]
Adding any feed from the RT website (https://www.rt.com/rss-feeds/) results in an error about the feed not being found. 

If you go to one of the URLs in a clean browser you get a DDoS check, I think that might be why. 

Is there any way around it?
![Uploading F1186574-E579-4477-AA9B-D3016821173E.png…]()

**Comment by brentsimmons** [comment]
I was able to add a feed to my Feedbin account. I bet they work with most of those systems.

But reading directly from NetNewsWire (via on my device or iCloud accounts) doesn’t have a way around the DDoS check.
