### ISSUE TITLE
Look at Reading.am etc.

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#350]
See https://jonmitchell.net/micro/qkbnq844slbzxw6rrcq13e3j68r9jq

**Comment by chrisaldrich** [comment]
Additional thoughts here: http://boffosocko.com/2018/02/19/reply-to-jon-mitchell-on-reading-bots/

**Comment by brentsimmons** [comment]
Reading.am seems to be gone. If anyone knows of a service we could use that would let people create a what-I’m-reading list, then please open a ticket for that specific service.
