### ISSUE TITLE
Unable to build NetNewsWire (Mac and iOS targets) in Xcode 13.3 

### ISSUE THREAD

**Issue by stuartbreckenridge** [Ranchero-Software/NetNewsWire#3500]
There appears to be an issue with the Swift Packages. I thought I'd narrowed it down to `RSSparkle`—where the binary target needs to have the same name as the package—but the remaining packages still have issues once that is resolved. 

<img width="600" alt="Screenshot 2022-03-18 at 20 54 59" src="https://user-images.githubusercontent.com/7046652/159006733-ce7cda43-2262-46d7-a4b6-253d25f7998a.png">
<img width="620" alt="Screenshot 2022-03-18 at 20 55 28" src="https://user-images.githubusercontent.com/7046652/159006749-32727b19-122b-47f5-84be-3104a245e3c4.png">

**Comment by GetToSet** [comment]
I applied this patch for my own project. After resetting caches, I'm able to build without any errors.
Would you have a try by replacing RSSparkle into `https://github.com/GetToSet/Sparkle-Binary` (main branch).
