### ISSUE TITLE
NetNewsWire on macOS looses item order when multiple items are copied.

### ISSUE THREAD

**Issue by vruyr** [Ranchero-Software/NetNewsWire#3502]
When copying multiple selected articles from the timeline using `Edit » Copy`<kbd>⌘C</kbd>, the order of the articles is not preserved, and the pasteboard gets what looks like a random order. Also the order is not preserved between copies of the same set - order is changed every time.

**Comment by vruyr** [comment]
I am using the copy feature to add articles to [Pocket](https://www.getpocket.com) from keyboard using a simple Python script that monitors the pasteboard and parses out the URLs. Of course it would be much better to have Pocket integration with a keyboard shortcut to add articles to Pocket without an external script, but the multiple article copying, I believe, still should be more consistent with the rest of the UI.

**Comment by vruyr** [comment]
I am not familiar with the codebase, but if the underlying Array keeps the items not in the order they are rendered (e.g. in the order they were in the xml fetched), the copied items might be reveres. Perhaps just sorting the Set according to the current UI preference, is a safer approach.

**Comment by vruyr** [comment]
Another thing is the formatting – when multiple items are copied, it is hard to figure out where one item ends and the second begins because the url, date, etc. are at the end. Parsing those programmatically would be even more challenging to do reliably. The new `Copy Article URL` is great though! No more fishing out the url!

**Comment by Wevah** [comment]
Doesn't seem like theres a reason not to return an Array instead of a Set as it's only used in this one place (aside: I kind of think the Array-phobia in certain places is unwarranted).
