### ISSUE TITLE
 Can the APP set the source to not respond within 2 minutes, and then judge it as a timeout

### ISSUE THREAD

**Issue by weijingcheng4** [Ranchero-Software/NetNewsWire#3503]
Hello developers, this is a feature suggestion.   My crawler server is not always on, it only starts when I visit, so it need 2 minutes to respond. Currently,The APP needs me to refresh multiple times to get the content.

**Comment by vincode-io** [comment]
We currently timeout feeds after 30 seconds to improve refresh times. Sorry, changing that to 2 minutes would degrade syncing time and be a worse experience for most users.
