### ISSUE TITLE
Subscribed feeds don't show new posts even though new posts exist in feed for hours

### ISSUE THREAD

**Issue by michaelnordmeyer** [Ranchero-Software/NetNewsWire#3505]
I have a couple of feeds from the same site which won't update in NNW even though a `curl <feed-url>` would display new posts. Manual reloading helped in the past, but ceased to work over time. Now I cannot update those feeds on iOS anymore, and on macOS I only get updates every couple of hours.

This happens with NNW 6.0.2 iOS 15.4 and 6.0.3/6.1b4 macOS 12.3. Syncing is done via iCloud and works flawlessly if those feeds have been updated on one system. I don't think I have these problems with other feeds, but the handful of other feeds are low-traffic ones.

It only happens to a number of feeds from www.heise.de (sorry, only German). The feeds subscribed to in NNW are:

1. https://www.heise.de/rss/heise.rdf (~100-150 posts per day between 7am and 8pm UTC, includes those below)
2. https://www.heise.de/developer/rss/news-atom.xml
3. https://www.heise.de/thema/Netze?view=atom
4. https://www.heise.de/thema/Linux-und-Open-Source?view=atom
5. https://www.heise.de/security/rss/news-atom.xml

All those feeds can be viewed as a combined web feed at https://www.heise.de/newsticker/archiv/. The first feed is the one with the most problems.

FWIW I don't think I'm rate-limited, because `curl` from the same IP works. Also they're hosting directly at Frankfurt's [DE-CIX](https://en.wikipedia.org/wiki/DE-CIX), which one of the largest exchange points in terms of average traffic. Therefore I don't expect performance problems of any kind.

**Comment by brentsimmons** [comment]
Could this be related to the iCloud outage?

**Comment by michaelnordmeyer** [comment]
No, this behavior started a couple months ago and got gradually worse. I noticed it on iOS first, a manually reload here and there, until over the weeks I had to use the macOS version to reload the feeds. And in the last week or two no feed updates on iOS and only occasional updates on macOS.

And, as I mentioned, iCloud syncing works flawlessly as soon as one of those feeds or others have been updated.

**Comment by michaelnordmeyer** [comment]
Another test:

I disabled the iCloud account of NNW yesterday, enabled the On My Mac account, and added the first non-updating feed. It loaded without problems.

Today I opened NNW and the feed immediately updated. Then I deleted the feed, disabled On My Mac, re-enabled iCloud and manually reloaded all feeds. The broken feeds won't update.

**Comment by michaelnordmeyer** [comment]
Okay, I install [miniflux](https://miniflux.app) locally on the same computer I'm running NNW on and imported all my feeds from NNW. All feeds updated correctly. Then I waited 15 minutes, checked the webpage of the first broker heise feed for updates, subsequently manually reloading feeds in both NNW and miniflux. NNW didn't update the feed, but miniflux did. Both apps obviously requested the feed from the same IP address.

BTW, NNW is set to manually update feeds. So no chance of being rate-limited or blocked, unless they check for the user agent.

**Comment by michaelnordmeyer** [comment]
Another test: I ran NNW continuously throughout the day (sleeping at night) with automatic feed updates set to a 10 minute interval. It took two days until one morning all those broken feeds got all missing posts from two days back.

**Comment by michaelnordmeyer** [comment]
Another test: I ran NNW continuously for 48 hours with automatic feed updates set to a 10 minute interval. I duplicated my iCloud subscriptions to "On My Mac". My assumption is that both storages will fetch feed updates at the same time or only differ less than above interval.

After making sure both storages had the same number of unread posts, I checked the number of unread posts every once in a while for the aforementioned 48 hours. Most of the time the feeds had the same number of unread posts, while sometimes a feed had some newer ones missing  (at least one hour, some times more).

I only used NNW on a single Mac to make sure no syncing or feed updates from another device would interfere.

**Comment by dbarros** [comment]
I'm also experiencing this issue with this feed https://www.cyberciti.com/atom/atom.xml

NNW (6.1 (6106)) shows an error dialog the there is no feed to be found, but I can add it just fine in Feedly (which is what I'm using). NNW does show an entry in the list of feeds, just doesn't show any articles.

**Comment by brentsimmons** [comment]
I just tried adding https://www.cyberciti.com/atom/atom.xml to my On My Mac account with NetNewsWire 6.1 and it worked normally. What happens if you try it again? Could have been a short-lived issue with the feed or its server.

**Comment by dbarros** [comment]
@brentsimmons OK, my apologies. I just tried this just now, and it worked. Believe me that this was not working for me for days. But, as you say, it may well have been because of the feed being up and down. Thank you, nonetheless.

**Comment by vincode-io** [comment]
It looks like this issue resolved itself.
