### ISSUE TITLE
iphone has trouble loading content

### ISSUE THREAD

**Issue by lsinrc** [Ranchero-Software/NetNewsWire#3506]
My primary NNW device is an iPad with iCloud connections for my Mac and iPhone 12 Pro Max. My iPhone will not load content. It shows the progress bar never moving from the initial start. It will load iPhone content but bogs on the iCloud content. I have deleted the app and reinstalled multiple times. My iPhone is as beefy spec-wise as my iPad, so I am unsure why it won't load when the other two devices have no problems. 

The content is a significant list, producing about 2000 new articles/items a day, so it is possible that contributes to the problem.  Are there limits on the iPhone NNW compared to the iPad NNW (volume of feeds or articles, or memory needs)? Is there a way to diagnose what is bogging down the iPhone NNW, feeds or otherwise?

**Comment by lsinrc** [comment]
This has been ongoing for awhile.

**Comment by lsinrc** [comment]
In the past I tried leaving using NNW and not use my phone for hours and it would not update (I know IOS has issues with background processes, so I would keep NNW on top). Typically I have been doing most of the daily reading/updating on my iPad; after a few days I then come back to the iPhone and that's when I have trouble (same reading/updating pattern with the Mac doesn't produce this problem). This last time NNW was unresponsive on the iPhone for at least a couple weeks of trying to get it to update without success (every time I woke up my iPhone it showed the same no progress screen), that is when I deleted the app and started over.  

Today I tried leaving NNW open (no other apps) while preventing my phone from sleeping, and after nearly an hour it finally updated.  I suspect if I used each device equally, it would update just fine. It appears when the iPhone has to catch up from several days/weeks of content updates on a large rss list, it takes uninterrupted (non-sleeping) time to "get over the hump" of updating.

This might be an issue of my not understanding how IOS handles apps updating--if I leave NNW and auto-lock kicks in, does the app stop updating? Is auto-lock the culprit?

**Comment by vincode-io** [comment]
Yes, if auto-lock kicks in we only have 30 seconds to complete syncing which isn't long enough for large iCloud downloads. As you found out, the longer you go between syncs the larger the iCloud download. Your best bet when this happens is to disable auto-lock and just let NNW do it's thing.

**Comment by lsinrc** [comment]
Thank you!
