### ISSUE TITLE
Profile pic for twitter feed

### ISSUE THREAD

**Issue by GymRat102** [Ranchero-Software/NetNewsWire#3508]
Adding twitter feed through a user's home page url will bring its profile pic to the feed, which is so good!

However, home page twitter feed won't include replys tweet (even replies to its own tweets). @peternlewis provided a quick solution in this issue to use search term as a feed to get complete content: https://github.com/Ranchero-Software/NetNewsWire/issues/2950#issuecomment-811579639 but it won't give us avatar :(

I checked the export OPML and saw there are htmlUrl and xmlUrl, and I am thinking that profile pic is brought by xmlUrl. So if that's the case, could you change htmlUrl to be the one that provide avatar to the feed. Then, even I use search term as a feed, I can also change homeUrl to home page url mannually to achieve both goals.

Or it would be better to include replies tweets in the first place.

Thanks

**Comment by vincode-io** [comment]
We don't scrape webpages to find the Twitter profile pic. We have to use the Twitter API because profile pics are only available to signed in users. Your idea to use the `htmlURL` simply won't work.

**Comment by GymRat102** [comment]
Oh thank you. I guess not including replied tweets is because of Twitter API's limit.

**Comment by vincode-io** [comment]
No, it is because we have't implemented it as a feature yet. I'm saying that your idea about hacking the OPML file won't work because of how we retrieve profile pics.

**Comment by GymRat102** [comment]
I get it. Looking forward to that feature.
