### ISSUE TITLE
Starred "smart feed" count doesn't reflect reality

### ISSUE THREAD

**Issue by crgmrgn** [Ranchero-Software/NetNewsWire#351]
Now that 1.0d40 supports star/unstar of articles it is slightly out of step with other smart feeds in that the displayed count of articles is not dynamically displayed. 

This may be expected behaviour, given its somewhat different nature but given "Today" and "All Unread" behaviour it seems odd. Marking an article "unread" for instance causes a dynamic update of that item count.

**Comment by brentsimmons** [comment]
This is a tricky one. The Today and All Unread feeds show their respective unread counts — same with feeds and folders.

The unread count for the Starred feed is probably zero most of the time (it doesn’t have to be, of course, but it’s most likely).

Should the Starred feed be the one exception to the unread count rule? If so, should the count be displayed somewhat differently (different chiclet color, for instance) to distinguish it from an unread count?

**Comment by crgmrgn** [comment]
Interesting, definitely a perspective difference then … I personally don't see the count as an "unread" counter per se, rather a plain count of items in the set, in this case the "starred" set, hence I expect to see it reflect membership totals, not membership "unread".

By the existing reasoning surely the "starred" item would not (generally) ever gain a count then, as per se you must opt-in an item by starring it and hence it gets read status. I appreciate you can manipulate it back to an unread status manually, but that would obviously not be the normal operation for most.

A different chiclet colour, indicating membership (irrespective of read/unread status) would be excellent from my perspective but I can fully apreciate why you'd chose not to possibly confuse others with this behaviour. I'll bow down to your experience and greater aesthetic experience (why I loved/used NNW from beta onward ;-)

**Comment by vincode-io** [comment]
For now we won't be changing this behavior.  If we do add a special count for Starred, we'll add that as a new GitHub issue.
