### ISSUE TITLE
Feature request: “All Articles” smart folder

### ISSUE THREAD

**Issue by simX** [Ranchero-Software/NetNewsWire#3515]
The other day I was searching for an article I had read the day before.  I was surprised to find that there doesn’t seem to be a way to search through ALL articles downloaded to NetNewsWire 6 for iOS.  I couldn’t remember which feed it came through, so I couldn’t find it.

Can there be an “All Articles” smart folder added to NetNewsWire, so we can easily browse through all articles (not just today’s), and search through them as well?

**Comment by stuartbreckenridge** [comment]
You can go into All Unread, scroll down a bit to reveal the search bar, and the tap the "All Articles" option on the scope bar.

**Comment by vincode-io** [comment]
We can't create an "All Articles" smart folder because it would load the entire articles database into memory. We would never get this to perform satisfactorily.

As @stuartbreckenridge points out, you can search all articles on iOS.
