### ISSUE TITLE
hyphenation?

### ISSUE THREAD

**Issue by erikmh** [Ranchero-Software/NetNewsWire#3521]
I’m not sure I’d want to turn hyphenation off altogether, but is there a way to get it to hyphenate less stupidly?
![9E788EA0-EEC6-4CAB-B5ED-BB159CAC6394](https://user-images.githubusercontent.com/8137726/162009431-e64e70e5-e0c9-42eb-b6ec-3217d612938a.jpeg)

**Comment by brentsimmons** [comment]
WebKit does the hyphenation — I don’t think there’s anything we can do to affect it (besides turning it off).

**Comment by GetToSet** [comment]
I can't see any hyphenation occurring inside the article view of NetNewsWire. Could you describe how to reproduce it or attaching a complete screenshot?
