### ISSUE TITLE
Invisible scroll bars in article view on external non-retina screen

### ISSUE THREAD

**Issue by vegarnilsen** [Ranchero-Software/NetNewsWire#3523]
I use my Macbook in clamshell mode, with an external non-retina screen as the only display.

In this configuration NNW doesn't display any scroll bars in the article view, regardless of length. If I instead open the laptop and move the window to that screen, the scroll bars are visible again. Both the list of feeds and the list of articles will show scroll bars if there's enough items to warrant it.

NNW has behaved this way on both macOS 11 and macOS 12, and across both Intel and Apple Silicon laptops.

Since NNW shows the scroll bars (in the way I've configured in System Preferences) on the laptop screen, I would also expect it to behave the same on the external screen.

With the 6.1 release I tested all of the included themes just to see if that would change anything, but I got the same behaviour with all of them.

**Comment by brentsimmons** [comment]
I’m 99.9% sure this is an Apple bug. I don’t have any idea what we could to fix this.

**Comment by vegarnilsen** [comment]
> I’m 99.9% sure this is an Apple bug. I don’t have any idea what we could to fix this.

Ok. I'll cross my fingers for a future Apple update. 🤞Thanks for the quick response.

NNW works great otherwise, so no worries.

**Comment by GetToSet** [comment]
macOS normally determines if scroll bars should be shown according to the following aspects.
1. This option you choose in System Preferences
	<img width="439" alt="Screen Shot 2022-04-11 at 04 45 47" src="https://user-images.githubusercontent.com/8158163/162639047-29f1192b-7b19-4c63-82b0-654fb3eb1665.png">
2. If you're using a mouse or trackpad. Scroll bars are default hidden if you're using a trackpad with the preceding option not set to 'Always'.

I've tested with an external monitor with a mouse and the behavior of scroll bars seems to work well. Could you observe how the scroll bars on other apps behave?

**Comment by vegarnilsen** [comment]
As I mentioned, the scroll bars work as expected in the list of feeds and the list of articles. It's just the article view where the scroll bars disappear. NNW is the only app I have where this happens, scroll bars behave as expected (I use the "show scroll bars when scrolling" setting) in all other apps I use.
