### ISSUE TITLE
Unable to connect to FreshRSS account

### ISSUE THREAD

**Issue by klodeckl** [Ranchero-Software/NetNewsWire#3524]
I tried the Mac OS client and the ios client. 
On the Mac OS client I get the error: Network error. Please try again later.
The ios client says: The operation couldn’t be completed. (Secrets.CredentialsError error 1.)

I tried PHP 7.4,  8.0 and 8.1.
API is activated in FreshRSS. API test says OK.

**Comment by klodeckl** [comment]
Problem solved. FreshRSS needs Apache.

**Comment by ecwyne** [comment]
@klodeckl I'm experiencing this issue. Can you describe the steps you took to resolve?
