### ISSUE TITLE
Timeline is missing row separators

### ISSUE THREAD

**Issue by drgvond** [Ranchero-Software/NetNewsWire#3528]
This is the same separator as on Mail's message list.

If I'm recalling this correctly, it should be enough to set `gridStyleMask = . solidHorizontalGridLineMask` on the table view.

The logic related to the separator in `TimelineTableRowView` can also (should?) be removed.

**Comment by GetToSet** [comment]
Apple's three column apps (Mail.app & Notes.app) has row separators on the second column. It might be reasonable to add it on NetNewsWire. I'll spend some time on this topic.

**Comment by brentsimmons** [comment]
We have a hidden preference to turn these on. They’re not on by default just because I don’t like them.

**Comment by vincode-io** [comment]
Closing since this is functioning as it should.

**Comment by drgvond** [comment]
> We have a hidden preference to turn these on. They’re not on by default just because I don’t like them.

Fair enough.

In any case, I would suggest to remove the separator code from `TimelineTableRowView` since it’s doubly unnecessary.
