### ISSUE TITLE
URL sometimes are not tappable where they are rendered

### ISSUE THREAD

**Issue by mattsheppard** [Ranchero-Software/NetNewsWire#3529]
I see an issue occasionally on iOS where a feed item shows its url, but if I tap it nothing happens. However if I tap one line down, in what appears to be blank space, the url suddenly redraws and is triggered.

It’s a bit hard to describe in words, so I recorded a video which hopefully makes it clear. Just before the url is loaded you can see the url jump, and tapping on it in the line above had no effect.

https://user-images.githubusercontent.com/12991/163494200-1dcb3289-22a7-4c08-9c1d-a260f741242b.MOV

Thanks for a fantastic app regardless!

**Comment by mattsheppard** [comment]
The feed URL is https://hnrss.org/frontpage?points=10&comments=3 if that's helpful, and that was captured from an iPhone 11.

**Comment by mattsheppard** [comment]
Ah, I was going to also snag a downloaded copy of the feed, but it looks like that item has already rolled off.

Assuming it's of interest I'm happy to grab an example next time I happen to run into it (I'd say I see this several times per week in various feeds).

**Comment by brentsimmons** [comment]
Very weird! That interaction is happening inside a web view — it’s managed by the system (WebKit, specifically).

I wonder if there’s some JavaScript in there doing something weird. Or maybe it’s just a WebKit bug.

**Comment by brentsimmons** [comment]
Are you still seeing this bug?

**Comment by mattsheppard** [comment]
Good question - I don't think I have seen it happen in some time now, so perhaps it has been solved.

Happy for it to be closed and I'll reopen if I do see it reoccur.
