### ISSUE TITLE
Feature request: Standardize handling of marking All Unread as read

### ISSUE THREAD

**Issue by vr8hub** [Ranchero-Software/NetNewsWire#3536]
NNW 6.1 on Mac, 6.0.2 (Build 610) on iOS.

I use NNW on all three types of devices: Mac, phone, iPad. The results of marking all articles as read and clearing the All Unread smart feed is different on every device. All of the below is when in the "All Unread" smart feed.

On the phone, tapping the "mark all read" button (circle with two circle shadows above it, in the lower left-hand corner) takes you back to the Feeds page. Subsequently tapping on the All Unread smart feed again shows an empty list, so it was apparently cleared when exiting and going back to Feeds. But I didn't want to exit, I just wanted to mark the articles as read.

On the iPad, tapping the "mark all read" button marks everything as read, but leaves you in the "All Unread" list, with all of the articles still there, but marked as read. A pull-to-refresh will then clear the list of everything except the article that the cursor was on when the pull-to-refresh was performed. Of the three behaviors, this is the best one, IMO.

On the Mac, clicking the "mark all read" button also marks everything as read and leaves you in the "All Unread" list, with all of the articles still there, but marked as read. But a pull-to-refresh does nothing. The only way I've found to clear the list is to click on "Starred" (or Today, but I use Starred since I don't have anything in it) and click back on All Unread.

Why are there three different behaviors instead of one? Why can't all three devices support the iPad's behavior?
* I would like to stay in the "All Unread" list. I can do this on iPad and Mac but not iPhone. As stated above, marking unread automatically takes you back to the Feed page. Can it be made to work like the other two and leave us in the folder, just marking everything as read? And then make pull-to-refresh clear the list (with the highlighted one kept), as it does on iPad?
* Could the Mac also support pull-to-refresh on the mouse/trackpad to clear the list?
* Alternatively, an option to have "mark all as unread" also clear the list would be OK (I personally always want to clear the list when I mark everything as unread, but I realize that might be a minority opinion).

With the above two changes, the behavior would be the same across the app and all devices. Easier to remember, easier to understand, easier to use.

Thanks for considering!

**Comment by SamSandq** [comment]
I have found exactly the same. Very annoying, please fix.

**Comment by vincode-io** [comment]
The reason these behaviors are different is because NetNewsWire runs on 3 different devices, each of which has different design considerations.

For example, on the iPhone we take you back to the Feeds scene when you indicate that you are done reading by clicking on Mark All As Read. We don't do that on the Mac or iPad because the Feeds scene is already visible. 

We don't have Pull To Refresh on the Mac because it isn't a standard Mac control or feature. 

For each variant of NetNewsWire we work hard to match the platforms conventions and in this case we think we've done a good job of that.

**Comment by vr8hub** [comment]
Since the first thing I said was that "I run NNW on three devices…", telling me it runs on three devices is kind of redundant. The handling of this issue is also the opposite of "good," which is another reason for the issue.

A cross-device app has much higher affiliation with itself on the other device(s) than it does with completely different apps on the various devices. Cross-device apps should provide a common way to perform common functions. Pull to Refresh may not be "standard" on the Mac (yet), but it is standard for NNW. There aren't _that_ many apps that run on all three platforms, and those that do have common characteristics. If you want to use a button (as an example) to mark unread and clear everything, because you don't like the platform features, then fine. But, again, there should be a _common_ way to perform a _common_ function across all the devices.

Aside from that, there are also questionable (at best) decisions in the process on all of the platforms.
On the iPhone, why does it force you back to the Feeds scene? We don't need to be on the Feeds scene if we spend all of our time on the Unread feed. I don't use the Feed scene for any purpose on any of the three devices, and I don't think that's uncommon.
For the iPad/Mac, It's silly that it's a two-step process to mark everything unread and then clear the list of those now read items. The former should also do the latter, or at the very least should have the _option_ for doing the latter.
