### ISSUE TITLE
Feature Request: Support jumping to footnotes inside the app

### ISSUE THREAD

**Issue by Alex-Vasile** [Ranchero-Software/NetNewsWire#3538]
Currently hyperlink footnotes (which link to the bottom of the article) show up properly in the view of the article inside the app.

However, clicking on any of them opens a webpage.

Instead, it would be great if the link was recognized as a footnote and took me to it within the app, rather than kick me to the website.

**Comment by Wevah** [comment]
Clicking footnote markers should be showing the footnote contents in a custom popover.

**Comment by Alex-Vasile** [comment]
#3564
