### ISSUE TITLE
Feature Request: Reddit subreddit setting change without replacement

### ISSUE THREAD

**Issue by doctored** [Ranchero-Software/NetNewsWire#3539]
currently, you have to choose between new, rising, hot and best when you set up the feed. these settings are more or less post volume settings. as such i find myself needing to "turn the volume" up or down on certain subreddits from time to time based on my bandwidth but also subreddit popularity trends. currently, in order to do this, i need to recreate the feed and change the setting for the new version and erase the one with the previous setting. it would be nice if you could just "adjust the volume" without going through all of that.

**Comment by afheisleycook** [comment]
I think your spot on
