### ISSUE TITLE
The Favicon for the wired.com site changes to an image associated with the article 

### ISSUE THREAD

**Issue by sgraesser** [Ranchero-Software/NetNewsWire#3549]
I have noticed the favicon for the wired.com site displayed in the Starred View will change to an image associated with the article. See attached image: 
<img width="729" alt="Screen Shot 2022-04-30 at 3 16 26 PM" src="https://user-images.githubusercontent.com/1928823/166124456-66fcaadc-95af-4843-9750-109a6e7a3958.png">
 
I don't know why or which article image is chosen to be the update web site favicon, but it definitely changes on what seems like a daily basis.

**Comment by Cauchon** [comment]
@brentsimmons Hi Brent, Justin from WIRED's product team. Curious to hear your thoughts on this and if it is something we can fix on our end.

**Comment by brentsimmons** [comment]
What’s the URL of the feed you’re using?

**Comment by sgraesser** [comment]
http://www.wired.com/feed/

**Comment by brentsimmons** [comment]
Are you still seeing this bug?

**Comment by sgraesser** [comment]
No. It seems to have fixed itself.
I'm using NetNewsWire 6.1 (6106)
