### ISSUE TITLE
Using an inordinate amount of screen time (associated with 'videopress.com'?)

### ISSUE THREAD

**Issue by mvonballmo** [Ranchero-Software/NetNewsWire#3550]
**Observed**

NetNewsWire seems to be taking an inordinate amount of screen time. It also seems to be associated with an "app" called "videopress.com".

<img width="424" alt="NetNewsWire and videopress com" src="https://user-images.githubusercontent.com/1214927/166199809-ce43e426-1e0d-44f9-a9b1-6afab8995401.png">

**Expected**

NetNewsWire isn't taking screen time whenever the machine is on. It's determined whether the "videopress.com" app is associated with it.

**Analysis**

The association with "videopress.com" is only a hunch because they two "apps" are using the exact same amount of screen time (i.e. an inordinate amount). Videopress.com seems to be a video-uploading tool for WordPress. I can't imagine what it has to do with NetNewsWire.

I'd appreciate any tips or hints on how to address this situation. Thanks!

**Comment by brentsimmons** [comment]
Guessing that you had a story from videopress.com open in the article view in NetNewsWire, and it stayed there for 9h 20m. (Just a guess, but likely.)

**Comment by kielgillard** [comment]
Could it have something to do with something like redirects attempting to fetch a favicon?

**Comment by brentsimmons** [comment]
Could also be some JavaScript in that story that kept running.

**Comment by Wevah** [comment]
Or an embedded video (or something) from that domain, if it's for hosting videos for Wordpress.

**Comment by mvonballmo** [comment]
Thanks for all of the comments and ideas. I _usually_ have the reader "parked" on an empty topic, with no article focused, but sometimes I don't.

Some notes:

- I rarely shut down or restart the OS
- I rarely restart NetNewsWire

Yesterday, I replaced the version of NetNewsWire with a freshly downloaded copy (desperate times...) and now I see that today it's much more well-behaved -- and videopress.com is gone.

<img width="430" alt="image" src="https://user-images.githubusercontent.com/1214927/166482228-ad9b1e2b-0cad-4911-8b81-a1cad062fee6.png">

Yesterday's (May 2nd) is shown below. May 1st is bad:

<img width="428" alt="image" src="https://user-images.githubusercontent.com/1214927/166482417-69c17895-3ebd-40ed-8e20-75e19fbf64ae.png">

I scrolled back through the historical energy-usage data and found the last "normal" day:

- April 3rd (41m NetNewsWire)
- April 4th (16h 24m NetNewsWire / videopress.com)
- April 4th (16h 24m NetNewsWire / videopress.com)
- April 5th - May 1st (24h NetNewsWire / videopress.com)
- May 2nd (9h NetNewsWire / videopress.com)
- May 3rd (10m NetNewsWire)

It looks like I "fixed" it yesterday, but I'll keep you posted.

**Comment by mvonballmo** [comment]
Thinking about it some more, I feel like that web site was "hung up" in NetNewsWire until I'd restarted it.

Because I use NetNewsWire every day and there's no way I had a single page open for a month. It's honestly pretty cool that it was running the background and I didn't notice anything. 👍 

I just hadn't restarted it in over a month and didn't notice it was using energy until MacOS told me I was on the machine 24h per day. At first, I thought the energy report was buggy and ignored it.

**Comment by stuartbreckenridge** [comment]
Why is it identified as NetNewsWire 5?

**Comment by mvonballmo** [comment]
> Why is it identified as NetNewsWire 5?

I'd upgraded from NetNewsWire 4 long ago and renamed the new app while I was verifying that I liked the upgrade. I'd never changed it as I upgraded through the major-version-change to 6.

The new copy I've made is now called the standard name.

**Comment by mvonballmo** [comment]
After a couple more days of keeping an eye on it, NetNewsWire is back to normal.

I suppose it really was that a "viewer thread" (or whatever) got hung up ... and I just never noticed it (running on an iMac desktop).

Once I'd restarted NetNewsWire, the problem went away.

Thanks for your comments and quick replies!
