### ISSUE TITLE
Renaming Feed from GitHub Releases Throws iCloud Error

### ISSUE THREAD

**Issue by mzagaja** [Ranchero-Software/NetNewsWire#3551]
When attempting to rename a feed I subscribed to from GitHub releases for an app I get the following error:
<img width="1904" alt="image" src="https://user-images.githubusercontent.com/565647/166251350-a4c6bdb7-9130-48fe-b3d5-499b64842205.png">
<img width="372" alt="image" src="https://user-images.githubusercontent.com/565647/166251415-ab0ba930-e459-4e24-80cf-48bcb74dc14a.png">

I can rename other feeds without issue and iCloud is enabled in my preferences.

**Comment by mzagaja** [comment]
This appears to have gone away after a restart 🤷🏻‍♂️

**Comment by brentsimmons** [comment]
We’ll just assume it’s a glitch. We can reopen it if it comes up again.
