### ISSUE TITLE
Clipped toolbar items are always disabled on macOS

### ISSUE THREAD

**Issue by fheidenreich** [Ranchero-Software/NetNewsWire#3556]
Using NetNewsWire 6.1 (6106) I've noticed that if the main window is resized so that the toolbar shows clipped items as menu, all menu entries are always disabled, even if they'd be enabled when shown as normal toolbar items.

<img width="706" alt="grafik" src="https://user-images.githubusercontent.com/2421992/167360120-f9185f98-7664-4560-ac96-d4d0389d38eb.png">

**Comment by Wevah** [comment]
The only one I'd sort of expect that for is the "Share" item, since it pops a menu. AppKit should be taking care of the `menuFormRepresentation`s of the rest.

**Comment by fheidenreich** [comment]
I had a look at the code in the meanwhile and it seems that `view.window` is `nil` in this line when the item is represented as menu.

https://github.com/Ranchero-Software/RSCore/blob/69d79ab8c1a9f993913f3246a5664564bcf86b05/Sources/RSCore/AppKit/RSToolbarItem.swift#L15

**Comment by Wevah** [comment]
Aha; I didn't realize (forgotten?) they were a custom subclass with that overridden.

**Comment by fheidenreich** [comment]
I've added a PR to RSCore which should fix the issue.

**Comment by Wevah** [comment]
https://github.com/Ranchero-Software/RSCore/pull/65 for reference

**Comment by Wevah** [comment]
> I've added a PR to RSCore which should fix the issue.

https://github.com/Ranchero-Software/RSCore/pull/65 for reference.

**Comment by brentsimmons** [comment]
I merged the PR. Leaving this open till we pull in the latest RSCore and test to make sure the fix is working.

**Comment by vincode-io** [comment]
Pulling in the latest RSCore resolved this issue.
