### ISSUE TITLE
Open in browser shortcut doesn't work after refresh in All Unread

### ISSUE THREAD

**Issue by blackketter** [Ranchero-Software/NetNewsWire#3559]
To reproduce:

1. View an article in All Unread smart feed.
2. Refresh manually or automatically.
3. Article in main pane is still visible but does not appear in Timeline
4. Pressing B or return does not open article anymore.  Clicking on title still works.

**Comment by brentsimmons** [comment]
Mac, iPhone, or iPad?

**Comment by blackketter** [comment]
whoops...

macOS Version 6.1 (6106)

**Comment by vincode-io** [comment]
I'm not able to recreate this. Refreshing doesn't deselect the article in the timeline when I do it. Could you post a video of this happening so that we can see why I can't recreate it?

**Comment by blackketter** [comment]
Hard to show keyboard events in a screen capture, but I'm guessing that it's related to the "Open in Browser" button also becoming unavailable when the current article isn't in the unread list.  Here's a video of that behavior.  Pressing B at the end also has no effect.

https://user-images.githubusercontent.com/131679/170589663-5b62b27b-1e42-463f-9669-40a9687cf59e.mov

.

**Comment by vincode-io** [comment]
@blackketter What keyboard events are you triggering? Just using the mouse events that are shown in the movie don't clear the timeline. Are you hitting the Clean Up shortcut in there somewhere?

**Comment by blackketter** [comment]
If I click the refresh button (or hit command-R) while viewing the All Unread smart feed, the currently displayed article disappears from the timeline.  The article contents are still visible.

At that point the Open In Browser button or B keypress have no effect.

I also notice this while reading the All Unread feed and an automatic refresh happens in the background.  

At that point the article I’m viewing doesn’t respond to the B keyboard event (or clicking on the Open In Browser button).

**Comment by vincode-io** [comment]
I'm not sure how your timeline is getting cleared. We have a policy of never removing items from the timeline unless you use the Clean Up command.

Just to make sure we have all our bases covered, could you let me know what kind of account you are using?

**Comment by vincode-io** [comment]
@blackketter The real bug is that the Timeline is getting cleared somehow. That is why you can't use the Open in Browser button. There isn't an article selected even though there is still a visible Article. The Article View just didn't get cleared like it should have.

It looks like you are using Feedly. I tried all your steps multiple times using a Feedly account. I even did it with just two items in the Timeline. The only thing I couldn't test is that a new article appeared when you did the refresh.

If you do the same steps and an article doesn't come in, do you get the same effect? Knowing this can help us track down what in the sync process is causing the Timeline to get cleared.

**Comment by blackketter** [comment]
Doing this:

1. Mark one item unread
2. Select the All Unread smart feed
3. Select that single item in the timeline
4. Hit command-R, click on the refresh icon, or choose Refresh from the File menu
5. The selected item disappears from timeline, the article is still visible.

This does NOT happen if I disable Feedly and just use an article from On My Mac.
If I enable Feedly and have an unread article from On My Mac, the timeline gets cleared.

Is this helpful?

**Comment by vincode-io** [comment]
What does it look like I am doing wrong?

https://user-images.githubusercontent.com/16448027/190875402-01ed3095-f525-4d2c-9afa-ba6a1b2dd4c6.mov

**Comment by blackketter** [comment]
Golly, no idea!  Trying to copy you (I'm on Version 6.1 (6106)):

https://user-images.githubusercontent.com/131679/190877774-7910985e-564b-46f2-abef-afea2448a21f.mov

**Comment by vincode-io** [comment]
If you do that and go back to the same article in the Daring Fireball feed is it still there? I wonder if Feedly is giving us some weird data that is causing us to clean up the article and when we reload the Timeline it is gone.

**Comment by blackketter** [comment]
> If you do that and go back to the same article in the Daring Fireball feed is it still there?
It is and it's marked read.

**Comment by blackketter** [comment]
Not a Mac programmer, but I was able to get NNW built and running in Xcode.  Would a breakpoint and backtrace be helpful here?

**Comment by vincode-io** [comment]
I think your SyncStatus database is corrupted. Could you please remove your Feedly account and add it again to see if it fixes the problem?

**Comment by blackketter** [comment]
That seemed to do it!  Thanks so much.  

Now I'll have to get used to my All Unread timeline not clearing itself spontaneously. :)

**Comment by vincode-io** [comment]
I really don't understand how those SQLite databases end up getting corrupted, but sometimes it happens. Sorry for bother.

**Comment by blackketter** [comment]
Thanks.  I’m using a Feedly account.  

Hm, I never noticed Clean Up Articles before. 

 I’m definitely seeing read items disappear from the middle column (I guess this is called the timeline) after a manual or automatic refresh if Show Read Articles is off or in the All Unread smart feed.
