### ISSUE TITLE
Feature request: Media enclosure support

### ISSUE THREAD

**Issue by Zodiac1978** [Ranchero-Software/NetNewsWire#3571]
It would be great if NNW would support media enclosures. For example MP3s from Podcast feeds.
https://en.wikipedia.org/wiki/RSS_enclosure

**Comment by vincode-io** [comment]
NetNewsWire isn't intended to be used as a podcast player. There are many great podcast players that are much better suited for this role. We've also addressed the use of enclosures in #2380 and don't plan on adding support for them at this time.
