### ISSUE TITLE
In-app browser counts towards Screen Time even if iPhone is locked

### ISSUE THREAD

**Issue by tewe** [Ranchero-Software/NetNewsWire#3574]
On some days my Most Used things in Screen Time are individually way longer than I ever use the phone, and add up to more than 24 hours.

![Screen Time](https://user-images.githubusercontent.com/645412/169914457-05d8772c-658f-48ef-a545-2fd8a5c95916.png)

I know (and checked by searching Safari's history) that I only looked at the web sites from the screenshot above in the browser built into NetNewsWire, after tapping a feed item.

NetNewsWire 6.0.2 on iOS 15.4.1

Possible duplicate of #3117, which is about macOS, where I never turned Screen Time on.

**Comment by brentsimmons** [comment]
I don‘t know that there’s anything we can do about this. The system figures out screen time.

**Comment by tewe** [comment]
I'm no Apple Developer, but can imagine changing something to do with the WebView to a WeakRef. Of course that would take ages to find. I'll just disable Screen Time 🙂

**Comment by brentsimmons** [comment]
Are you still seeing this bug?

**Comment by tewe** [comment]
I re-enabled Screen Time and the built-in browser and couldn't reproduce it with an up-to-date iOS and NNW.
