### ISSUE TITLE
Could Netnewswire encrypt its data on iCloud?

### ISSUE THREAD

**Issue by daf121** [Ranchero-Software/NetNewsWire#3579]
iCloud data is not end-to-end encrypted. 
Would it make sense to make Netnewswire add an encryption layer to the sync process so only encrypted data is stored on iCloud ?

**Comment by brentsimmons** [comment]
It’s probably possible, sure. The problem with this feature is that it’s a support problem — people will lose their keys, and we wouldn’t be able to help them, but we’d have to respond to them and handle them being upset.

**Comment by vincode-io** [comment]
@daf121 Could you please explain better the motivation for wanting the iCloud data to be end-to-end encrypted?

The contents of the RSS feeds that NetNewsWire accesses are publicly available, so you really can't hide the contents of the feeds. As for which feeds you are accessing, this isn't hidden even by https unless you are using a VPN.

**Comment by daf121** [comment]
@vincode-io sure, I'd say it's a personal privacy principle, I don't like my clear data on what I read on Apple's servers, or on any remote sever for that matter; I use a VPN too yes.

**Comment by brentsimmons** [comment]
I’m extremely sympathetic to privacy issues — that’s part of why NetNewsWire exists in the first place. (It’s better for privacy than getting news via Facebook and Twitter, for instance.)

But, despite that, we just don’t have the capacity to handle support for this.

**Comment by vincode-io** [comment]
In addition to @brentsimmons comment, encrypting everything that gets put into iCloud would have a performance impact on all users, but only protect the one's that are using VPN's 100% of the time. To me at least, it doesn't have a very good tradeoff.

**Comment by michaeljtsai** [comment]
Can we revisit this now that Apple offers [Advanced Data Protection for iCloud](https://support.apple.com/en-us/HT202303#advanced)? Since they are handling the end-to-end stuff, which affects the entire iCloud account, it shouldn’t affect the support burden. From the NNW side, it seems like just a matter of using [encryptedValues](https://developer.apple.com/documentation/cloudkit/ckrecord/3746821-encryptedvalues) for the keyed values rather than the record itself. The main issues I see are migration of existing data and that it requires macOS 12.0/iOS 15.

**Comment by michaeljtsai** [comment]
I also think that the privacy benefits are greater than stated above:

- Which posts you have starred and how you have organized your feeds are personal data.
- With HTTPS, the feed content is hidden, as is the URL. So without a VPN you are really only leaking the domain, which may not mean much if it’s a popular one hosting many different feeds or a something like FeedBurner.
- The Twitter API provides access to content in private accounts.
- Feeds with access tokens in the URL are technically public but should be treated as private.
- Encryption would be important if support for actual private feeds is ever added (#502, #2106).
- I have used NetNewsWire with feeds from my local network (e.g. issue tracker, Jenkins) that are not publicly available.

More generally, I think there’s a big difference between “someone could see what you’re accessing if they are in a position to snoop on your network connection” vs. “everyone’s data is all nicely available on Apple’s server.”
