### ISSUE TITLE
"Open in browser" uses localhost as hostname

### ISSUE THREAD

**Issue by nabn** [Ranchero-Software/NetNewsWire#3588]
Platform: iOS

recording:
https://user-images.githubusercontent.com/1693287/172151312-27959b00-23a4-42d8-aa29-cf608b09adc4.MOV

**Comment by nabn** [comment]
I don't think it was specific to a feed, but it was https://blog.jez.io/atom.xml

The issue fixed itself after reopening the app. This has happened a couple times in the past.

**Comment by vincode-io** [comment]
The next time this happens, could you please post a screenshot that shows the address field?

**Comment by nabn** [comment]
Can do. Last time it happened, it showed up as localhost/<path> in the share sheet and in safari. Is there a way to check the url within the app?

**Comment by vincode-io** [comment]
Long pressing the article datetime should bring up a context dialog that shows it.

**Comment by nabn** [comment]
never mind, it happened again:

|||
|-|-|
|<img width=300 src=https://user-images.githubusercontent.com/1693287/172266055-597f0936-3275-462a-9ae4-abdd1aaa44c1.PNG>|<img width=300 src=https://user-images.githubusercontent.com/1693287/172266070-39ccff32-baf7-4577-af27-31309c94f768.jpeg>|

**Comment by nabn** [comment]
Unparsed markdown:
<img width=300 src=https://user-images.githubusercontent.com/1693287/172266433-7c557a73-4363-41a7-809b-e6e344f44831.jpeg>

**Comment by nabn** [comment]
tried a bunch of other feeds, at the moment seems to be specific to this feed

**Comment by vincode-io** [comment]
Which versions of iOS and NetNewsWire are you using?

**Comment by nabn** [comment]
NNW 6.0.2 (Build 610)
iOS 15.4.1

**Comment by vincode-io** [comment]
What kind of account are you using? Is it just the On My iPhone account?

**Comment by nabn** [comment]
This one is on Feedly

**Comment by vincode-io** [comment]
This is definitely a Feedly problem. It doesn't happen with the On My iPhone account. It looks like it is either a random Feedly bug or a bug in the feed that later got corrected and Feedly has cached. 

There isn't anything we can do to fix this, so I'm going to close out this bug report.

**Comment by nabn** [comment]
No worries, appreciate you looking into it 🙏🏼
