### ISSUE TITLE
macOS 13 Could Not Fetch Feeds

### ISSUE THREAD

**Issue by EvanLuo42** [Ranchero-Software/NetNewsWire#3591]
<img width="260" alt="image" src="https://user-images.githubusercontent.com/62578958/172749690-08ab0403-350f-4ae4-a104-3f3528896f4d.png">

After I upgraded to macOS 13, I found that NetNewsWire failed to fetching feed.

<img width="1234" alt="image" src="https://user-images.githubusercontent.com/62578958/172750019-a8f749b2-4c82-4185-9890-8ec3da0466c8.png">

I don't know whether these logs will help you, if you need more logs or other information please tell me.

**Comment by brentsimmons** [comment]
Thanks for the report. We expect that Apple will be fixing bugs in macOS 13.

**Comment by brentsimmons** [comment]
Are you still seeing this bug?

**Comment by EvanLuo42** [comment]
> Are you still seeing this bug?

No more bugs. Thank you.
