### ISSUE TITLE
Unable to open on MacOS.

### ISSUE THREAD

**Issue by jocago** [Ranchero-Software/NetNewsWire#3596]
Downloaded app version 6.1
Error: The application “NetNewsWire” can’t be opened.

MacBook Pro (15-inch, 2017)
MacOS Version 12.4 (21F79)

Log:
error	14:17:41.850003-0400	Dock	LAUNCH: RBSLaunchRequest FAILURE <private> com.ranchero.NetNewsWire-Evergreen <private> 0x0-0x6b96b9 failed with error Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x600001f60660 {Error Domain=NSPOSIXErrorDomain Code=111 "Unknown error: 111" UserInfo={NSLocalizedDescription=Launchd job spawn failed}}}

error	14:17:41.850064-0400	Dock	LAUNCH: Runningboard launch of com.ranchero.NetNewsWire-Evergreen <private> returned RBSRequestErrorFailed, error Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x600001f60660 {Error Domain=NSPOSIXErrorDomain Code=111 "Unknown error: 111" UserInfo={NSLocalizedDescription=Launchd job spawn failed}}}, so returning -10810

error	14:17:41.850178-0400	Dock	LAUNCH: request execute thru runningboard of 0x0-0x6b96b9 com.ranchero.NetNewsWire-Evergreen/<private> failed with error=Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x600001f60660 {Error Domain=NSPOSIXErrorDomain Code=111 "Unknown error: 111" UserInfo={NSLocalizedDescription=Launchd job spawn failed}}}

error	14:17:41.860243-0400	CoreServicesUIAgent	handle LS launch error: {\n    Action = oapp;\n    AppMimimumSystemVersion = "10.15";\n    AppPath = "/Applications/NetNewsWire.app";\n    ErrorCode = "-10810";\n}

**Comment by jocago** [comment]
I just tried. Same result.

**Comment by haikusw** [comment]
Possibly relevant: https://developer.apple.com/forums/thread/676627?answerId=667863022#667863022

**Comment by vincode-io** [comment]
@jocago did you try the suggestions from @brentsimmons or @haikusw?

This [Apple Support Document](https://support.apple.com/en-us/HT202491) may help.

**Comment by gingerbeardman** [comment]
I recommend checking SIP settings.

SIP needs to be on Full or Reduced, if it is set to Permissive then in some situations apps won't run on macOS with no visible error other than some cryptic log messages.

**Comment by brentsimmons** [comment]
Are you still seeing this bug?
