### ISSUE TITLE
[feature request] Add gesture navigations on iOS

### ISSUE THREAD

**Issue by madcommit** [Ranchero-Software/NetNewsWire#3600]
Can you do gesture navigations simile to Mail application on iOS. It’s easier to use one hand when operating on an iPad in portrait mode. This is to bring up the feeds navigation when I reading an article.

**Comment by madcommit** [comment]
In portrait mode, when you're reading an article in full screen mode, to bring up the feeds side bar you need to tap on < and tap on double arrow to go full screen again. Instead of that I was wondering if it is easier to implement the way stock mail app does when you're reading an email in portrait mode to bring up the inbox you can swipe from outside on the left side, select something and swipe again to close. It's more like an overlay on top of the full screen instead of moving the content to the right.

**Comment by vincode-io** [comment]
In version 6.2 of NNW for iOS we have moved to using the new 3 panel split view controller. This uses the built in navigation gestures and should match other apps in the system.
