### ISSUE TITLE
Move Marked as Stare items to iCloud.

### ISSUE THREAD

**Issue by blindasabat** [Ranchero-Software/NetNewsWire#3602]
Currently my subscriptions are On My MAC. I would like to move them to the iCloud. Many items are Marked as Stared. I move one subscription but none have the Marked as Stared assignment. Is it possible to migrate this designation to iCloud?

**Comment by vincode-io** [comment]
It isn't possible to move started items between accounts. The solution is super complicated and probably can't be implemented successfully because different account types uniquely identify articles using different schemes.
