### ISSUE TITLE
Aviationist feed always shows blank page when link clicked

### ISSUE THREAD

**Issue by grempe** [Ranchero-Software/NetNewsWire#3604]
For this feed:

http://theaviationist.com/feed/

The feed data displays correctly, but clicking any link to display feed article content results in a blank screen. Always. 

If I copy the article link and open it in safari directly it works fine. 

So there seems to be some kind of internal rendering issue. They have lots of ads on their site which perhaps plays a role?

**Comment by brentsimmons** [comment]
Mac? iPad? iPhone? What account type (On My Mac, iCloud, Feedly, etc.)? Are you clicking on the title of the article to open the page, or…?

**Comment by vincode-io** [comment]
@grempe are you still seeing this issue?  If so, could you please restart your phone and see if the problem persists. It is probably was either a temporary problem with the feed or iOS since I'm not able to recreate the problem.

**Comment by grempe** [comment]
I have been seeing this issue for many months. Across many iPhone restarts. 

Just finally got annoyed enough to file the issue.

If there are steps I can take to help debug please let me know.

**Comment by vincode-io** [comment]
Does this happen randomly or consistently? Are you only seeing it with one feed or with others?

The next time you see it, could you please copy the URL from title you clicked by long pressing it and the pasting it into this issue?

**Comment by grempe** [comment]
If that was the case, how do you explain that it works in iPadOS which presumably uses the same embedded Safari as both iOS and iPadOS are on latest version?

It also works in native Safari on both platforms.

**Comment by vincode-io** [comment]
NetNewsWire is the same code for iPhone and iPad. By your logic, how is this bug in NetNewsWire?

The website owner on the other hand might be doing something based on the agent string or viewport. It just isn't possible for use to debug server side code that we don't have access to.

**Comment by grempe** [comment]
Because only you have access to the viewport console which would likely
display rendering/URL permission/etc errors.

Its certainly possible that something they are doing server side is
triggering it, but the issue, by all indications, is only present in your
viewport on iOS.

You may be using the same code for iOS and iPadOS builds, but clearly there
are conditionals based on platform attributes. So they code path may not be
the same on both platforms. No?

Even if it is something beyond your control, you might be able to provide
the clue. That would allow them to fix (and i would happily file the report
with them).

**Comment by vincode-io** [comment]
Here is the site rendering fine on my iPhone. My guess is that there is a targeted advertising bug in that site.

![image](https://user-images.githubusercontent.com/16448027/174654954-98c9cd32-8e5e-4523-8f74-4200b65c6553.png)

**Comment by grempe** [comment]
I've installed iSource Browser from the app store. 

It allows you to see the web console of a webview trying to render a URL. This is the type of output that I'm sure you would have had access to to assist with identifying the issue.

You should expose this console within NNW to assist with similar issues in the future.

https://theaviationist.com/2022/06/19/norway-permanently-terminates-nh90-ops/

Here is the output. 

![image](https://user-images.githubusercontent.com/117/174651590-f13f57ea-b03f-4ed0-b65b-3bc91acee9a7.png)

I'll follow up with the website owner.
