### ISSUE TITLE
Reproducible read-after-free crash when adding iCloud account

### ISSUE THREAD

**Issue by winniequinn** [Ranchero-Software/NetNewsWire#3606]
After installing NetNewsWire on iOS and adding an iCloud account there, I installed 6.1 on macOS and attempted to do the same. Each time I attempt to do so, I immediately crash just as the "Use your iCloud account." dialog begins to show up.

Deleting all NetNewsWire data in "~/Library/Containers" and deleting all NetNewsWire data in iCloud does not resolve the problem. This is my first time ever attempting to use the application, so lingering data from a previous version cannot be an issue.

See [the crash report](https://github.com/Ranchero-Software/NetNewsWire/files/8934297/report.txt) for more info.

----

**Update:** It appears that I receive the same crash when attempting to add _any_ type of account.

**Comment by vincode-io** [comment]
Thanks for the crash report. It looks like it might be some kind of SwiftUI bug.

Have you tried rebooting and then adding the iCloud account then? We've seen in recent versions of macOS that rebooting will sometimes clear up weird macOS bugs.

**Comment by winniequinn** [comment]
@vincode-io: Restarting did not resolve the issue, I'm afraid.

**Comment by winniequinn** [comment]
- No luck deleting everything in Containers.
- I'll try updating to 12.4 and will report back.
- I _do_ have iCloud Drive enabled, although I do have it _disabled_ specifically for "Desktop & Documents Folders". I would assume that's not the problem though.

**Comment by winniequinn** [comment]
Thanks for trying to get to the bottom of this! I'll post again after I update to 12.4.

**Comment by vincode-io** [comment]
I'm keeping my fingers crossed that the upgrade fixes it for you.

You shouldn't need the iCloud Drive folders stuff, so that isn't likely the problem.

**Comment by winniequinn** [comment]
I'm getting the same crash with 12.4, unfortunately.

**Comment by vincode-io** [comment]
The crashlogs looks the same then?

**Comment by vincode-io** [comment]
Just to be clear, it is when you hit "Continue" in the below screenshot that you briefly see the dialog and then it crashes, right?

<img width="624" alt="Screen Shot 2022-06-20 at 2 38 23 PM" src="https://user-images.githubusercontent.com/16448027/174674877-6ac4b0c0-594c-4d56-9cdd-bd4a3190f405.png">

**Comment by winniequinn** [comment]
That is correct. It crashes just as the dialog starts to fade in; I managed a screenshot after a few attempts:

<img width="419" alt="Screen Shot 2022-06-20 at 5 15 14 PM" src="https://user-images.githubusercontent.com/10768108/174678643-7840b0a7-5ded-415d-8468-75eeff9c7895.png">

**Comment by winniequinn** [comment]
I can imagine this might be a tough one to debug given the stack trace. If you don't have anything to go on, I'll try to build the app and debug it with zombies enabled to see if I can't get you more info.

**Comment by vincode-io** [comment]
Wow. I'm at a loss as to what could be happening. It looks specific to your environment, but what is different?

Do you want to try running this in Xcode to see if you get stopped in the debugger someplace helpful? It is a real pain to get NetNewsWire set up to use full iCloud capabilities, but I can give you a simple change that will at least get the dialog to show.

**Comment by vincode-io** [comment]
We crossed comments. Give a second and I'll let you know what to change in NetNewsWire so that you can test this with the standard build instructions.

**Comment by vincode-io** [comment]
Just remove the `.cloudKit` entry from this line to allow you to click the iCloud option in the `-dev` build.

https://github.com/Ranchero-Software/NetNewsWire/blob/876b03340012f3aa231ee2f33bf29ec4ff834df3/Account/Sources/Account/Account.swift#L49

Good luck and let me know if you need. any help. If I'm not responding, you can ask for help in the #work channel of our Slack.

**Comment by winniequinn** [comment]
It seems that I get the same crash when I try to add _any_ type of account, it turns out. I also get it simply by clicking "Cancel" on the "Choose an account type to add…" screen.

I was able to fix it by holding the `NSHostingController` created in the `addAccount` method of `AccountsPreferencesViewController` in a new instance variable—one which would seem to serve a role similar to the existing `addAccountWindowController` instance variable. Whether or not this is the correct fix, I have not had time to investigate, but it does work around the problem, at least.

**Comment by vincode-io** [comment]
Thanks for figuring this out! That definitely looks like a problem to me. I'm honestly baffled as to why we don't see this all the time. Your solution also sounds correct.

Do you want to submit a pull request for this? We would really appreciate it.

**Comment by winniequinn** [comment]
Glad I was able to get to the bottom of it!

I wish I could submit a PR today, but I can't do so due to my relationship with my present employer: I'd need to get it cleared first. I'm currently away from work until July, so, as embarrassed as I am by this situation, you may just want to make the fix yourself unless you're okay with waiting a few weeks. (If you are though, I'll certainly get you a PR as soon as I can!)

**Comment by winniequinn** [comment]
I believe you have the same problem in the `enableExtensionPoints` and `enableExtensionPointFromSelection` methods of `ExtensionPointPreferencesViewController` (although I can't trigger a crash, for whatever reason).

**Comment by vincode-io** [comment]
I don't know yet when our next bug release for the Mac version will be. If you aren't able get to it, I'll make the change and just hope for the best since I can't recreate it.

I'll also take a look at the other functions you mentioned.

**Comment by winniequinn** [comment]
@vincode-io: #3670 should take care of this! While I cannot confirm that it fixes the crash I had when adding an iCloud account _specifically_ (as I did not attempt to build a version of NWW with iCloud support), it does fix the crash I had when attempting to add any other type of account; I imagine it covers the iCloud case too.

**Comment by winniequinn** [comment]
**Note:** While I did try changing `isDeveloperRestricted` as suggested, that alone did not result in iCloud showing up as an account option in a development build. No matter though: I am still reasonably confident that the issue is fixed as I had the same issue with all other account types.

**Comment by brentsimmons** [comment]
Reopening because this needs additional verification.
