### ISSUE TITLE
Better phrased iCloud error message

### ISSUE THREAD

**Issue by LPFchan** [Ranchero-Software/NetNewsWire#3610]
<img width="780" alt="Screen Shot 2022-06-24 at 7 57 33" src="https://user-images.githubusercontent.com/1547081/175428578-217b83b9-6c43-46bf-92f2-011139e9a7a4.png">

NetNewsWire will display an error message as follows: 

> Unable to add iCloud Account. Please make sure you have iCloud and iCloud enabled in System Preferences.

... even when you have iCloud account logged in and active in System Preferences.
I found out the hard way that what NetNewsWire actually requires is "iCloud Drive" enabled. So the better phrase would be: 

> Unable to add iCloud Account. Please make sure you have iCloud and iCloud **Drive** enabled in System Preferences.

**Comment by dmarcos89** [comment]
@LPFchan This thread saved me a lot of time. thanks! 😄

**Comment by brentsimmons** [comment]
Reopening because this needs additional verification.
