### ISSUE TITLE
nitter.net timing out in built-in browser

### ISSUE THREAD

**Issue by john-catalano** [Ranchero-Software/NetNewsWire#3612]
In the last few days, in the layers iOS is/app, nitter.net links will time out in the built-in browser. They open just fine in Safari, tapping the bottom-right button in NetNewsWire. 

I don’t see this happen for other sites.

**Comment by brentsimmons** [comment]
It’s probably checking User-Agent or something like that. It opens fine for me in Safari, but when I try curl on the command line I get a 404. There’s nothing we can do about that. (You could report it as a bug to the nitter.net folks.)

% curl -I 'https://nitter.net'

HTTP/2 404 
server: nginx/1.22.0
date: Fri, 01 Jul 2022 23:18:42 GMT
content-type: text/html;charset=utf-8
content-length: 3108
strict-transport-security: max-age=31536000; includeSubDomains; preload
