### ISSUE TITLE
iOS Beta Has Expired

### ISSUE THREAD

**Issue by thombet** [Ranchero-Software/NetNewsWire#3616]
Hello,

Today I cannot open the NetNewsWire app on my iOS device because it says "NetNewsWire Beta Has Expired" (iPhone SE - iOS 15.4.1) whereas I was able to open it last night.
I cannot find the app anymore in TestFlight.

Is it something related to my TestFlight account or is there something that can be done on your side to fix the problem please?

Thanks in advance.

**Comment by nicksherman** [comment]
I am experiencing the same issue.

**Comment by Thomas-U** [comment]
You have to load the AppStore version as Brent announced here: https://netnewswire.slack.com/archives/CC4LQ2D8R/p1657000847514039

**Comment by thombet** [comment]
Thanks for the link @Thomas-U but it seems I need an account to access that page. Could you please post the information directly here?

**Comment by Thomas-U** [comment]
That is a question to ask on the Slack channel #general.

**Comment by thombet** [comment]
A new beta version (6.1 build 6105) was just published and it worked on my side so I will close the ticket.
