### ISSUE TITLE
iOS help request: Selfhosted FreshRSS account states server certificate is invalid. 

### ISSUE THREAD

**Issue by milesmcclane** [Ranchero-Software/NetNewsWire#3619]
I am trying to link to my FreshRSS instance, but it’s throwing up this error message:

<<The certificate for this server is invalid.
You might be connecting to a server
that is pretending to be
"Blahblah.com" which could put
your confidential information at risk.>>

Is there anyway to bypass this? It’s my site, it’s perfectly safe. On a standard browser I have to click through a couple of ‘are you sure’ warnings but then it’s fine. What can I do if anything? Thanks for any assistance! Miles.

**Comment by brentsimmons** [comment]
Isn’t there some way to import your site’s SSL certificate into your Keychain? I don’t recall how one would find the certificate and then import it, but maybe that’s enough of a hint?

**Comment by milesmcclane** [comment]
> Isn’t there some way to import your site’s SSL certificate into your Keychain? I don’t recall how one would find the certificate and then import it, but maybe that’s enough of a hint?

That’s an excellent suggestion. I’ll try that, I’m sure there must be a way. I can export the cert from my NAS I think, and I’ll just see what happens when putting it in my keychain. Thanks!
