### ISSUE TITLE
MacOS 15.5 beta: Links take multiple tries to open

### ISSUE THREAD

**Issue by leehauser** [Ranchero-Software/NetNewsWire#3622]
I've left Apple beta feedback on this as well.

I'm running a 2020 MacBook Air. Previously, I could highlight a link, left-tap the trackpad, and have the link open. Now it just switches to Safari, with the last viewed page open. If I go back to NNW, do a "force click" on the link (press the left side of the trackpad down to get a haptic/audible click) it will open the link without problem. This happens with a wide variety of feeds, everything from BoingBoing to MetaFilter. It did not happen before 15.5 beta.

I'm running NNW 6.1 (6106).

**Comment by stuartbreckenridge** [comment]
MacOS 12.5 or iOS 15.5?

I am on 6.1 (6106) on both macOS 13 and iOS 16 and can't reproduce on those betas.

**Comment by leehauser** [comment]
So sorry I wasn't clear. MacOS 12.5 beta

**Comment by leehauser** [comment]
I've installed the Ventura public beta and the problem seems to have cleared up.
