### ISSUE TITLE
Most of my subscriptions stopped updating 

### ISSUE THREAD

**Issue by CCareyCC** [Ranchero-Software/NetNewsWire#3627]
Around 10am PDT today, Mon. July 18, most of my subscriptions in NetNewsWire stopped updating.

I'm running NetNewsWire 6.1 on a MacBook Pro macOS Monterey 12.3.1

I have 349 subscriptions. I only received new posts from about 10 of them after 10am PDT today.

I'm having no other issues with anything else on my Mac right now.

**Comment by hydroclaus** [comment]
it seems like I had similar issues; encountered them for first time a couple hours ago.
Now, I deleted iCloud account on macOS. Then added it again (not only de-activate but "full" delete). Now it's stuck since minutes on 1 of 145....

**Comment by vincode-io** [comment]
@CCareyCC are you using iCloud? If so you may have to wait a very, very long time for your syncs to complete. Has the syncing indicator completely disappeared for you and the sync completed?

**Comment by vincode-io** [comment]
I'm going to assume that this was the long iCloud sync issue and close this. We can reopen if we get more diagnostic info.
