### ISSUE TITLE
Adding external account not working NNW6.1 Macos

### ISSUE THREAD

**Issue by dng2403** [Ranchero-Software/NetNewsWire#3631]
Hi,

I've been trying to add my Feedly and Twitter feeds. There is a pop-up browser opened but it shows a blank page. The MS Edge address bar shows about:blank and nothing proceeds.

I have tried deleting the app and data, re-copy to the application folder; restart the computer multiple times. I have looked into the Keychain and there is no feedly account.

**Comment by vincode-io** [comment]
It should be opening a Safari window, not a MS Edge one. Have you deleted Safari or made some other unusual modifications that would redirect macOS to Edge instead of Safari?

**Comment by dng2403** [comment]
> 

No, I made MS Edge as my default browser in the system setting. Is it an issue?

**Comment by dng2403** [comment]
> > It should be opening a Safari window, not a MS Edge one. Have you deleted Safari or made some other unusual modifications that would redirect macOS to Edge instead of Safari?
> 
> No, I made MS Edge as my default browser in the system setting. Is it an issue?

I changed the default browser in system settings from MS Edge to Safari and it works perfectly now. Closing the case. Many thanks for your advice.

Anyway, worth noting that there is an issue with MS Edge (probably other 3rd party browser)
