### ISSUE TITLE
Feed not found for customized atom feed

### ISSUE THREAD

**Issue by SunRunAway** [Ranchero-Software/NetNewsWire#3644]
Hi, I've created binance news atom feed "http://35.88.61.195/binance" but it says "Feed not found"

**Comment by vincode-io** [comment]
What kind of account are you using? I was able to add the feed using the local account.

**Comment by SunRunAway** [comment]
Oh, I use feedly. Maybe it is feedly's issue.

**Comment by vincode-io** [comment]
I'm pretty sure it is on the Feedly side. If it looks like there is anything we can do to help, we can reopen this issue.
