### ISSUE TITLE
Possible to reduce the 17+ rating?

### ISSUE THREAD

**Issue by tylerbenson** [Ranchero-Software/NetNewsWire#3652]
I would like to allow my kids access to a limited set of predefined RSS feeds but I still want to prevent other apps. Is it possible to release a trimmed down version of the app that would satisfy more strict ratings requirements?

Thanks!

**Comment by brentsimmons** [comment]
If somebody wanted to take the NetNewsWire code and build a separate app that was all about being kid-friendly in that way, then that would be cool, but it’s not something we’re going to add to NetNewsWire.

**Comment by tylerbenson** [comment]
Ok, thanks for letting me know.
