### ISSUE TITLE
[Feature Request] Add a "open links in default browser" toggle to iOS settings

### ISSUE THREAD

**Issue by DEFCON001** [Ranchero-Software/NetNewsWire#3653]
Adding an open links in default browser toggle to the iOS app settings would make using the app a smoother experience, rather than having to click the open in browser button after the built in app browser launches.

**Comment by stuartbreckenridge** [comment]
This feature is already included in a future release.

**Comment by DEFCON001** [comment]
Which version update and when is said version estimated to hit the app store?

**Comment by stuartbreckenridge** [comment]
It's in 6.1 which is the current TestFlight build. [No estimated release](https://inessential.com/2019/10/28/no_etas).

**Comment by DEFCON001** [comment]
Is the TestFlight release public, and if so where is the link for it (I can't find it in the README or main website)?

**Comment by DEFCON001** [comment]
I found it:
https://netnewswire.com/test-ios
