### ISSUE TITLE
Article Detail View isn't working **without** Reader View

### ISSUE THREAD

**Issue by vencewill** [Ranchero-Software/NetNewsWire#3659]
## macOS `13.0 Beta (22A5311f)` behaviour:

https://user-images.githubusercontent.com/23724267/185729100-f910a064-d498-4ba0-90ff-16b302348977.mov

## iOS `16.0 (20A5349b)` behaviour:

https://user-images.githubusercontent.com/23724267/185729111-3d5bf659-4108-4eca-935f-879976cf1ea0.mp4

**Comment by vencewill** [comment]
Feed: https://blog.timac.org/index.xml

**Comment by stuartbreckenridge** [comment]
This is correct behaviour. The Timac feed does not provide full text articles in its feed.
