### ISSUE TITLE
Global Reader Mode

### ISSUE THREAD

**Issue by JPortet** [Ranchero-Software/NetNewsWire#3663]
Control the use of Reader View at a global level. For example:
- Use Reader View on all feeds
- Use Reader View on all feeds within this folder
- User Reader View on selected feeds. I can only toggle Reader Mode one feed at a time, enable this for a group of feeds at a time.

**Comment by vincode-io** [comment]
Reader View is intended for use only when needed. The service we use to provide it is donating the servers and bandwidth to support it. We don't want to abuse this kindness and use Reader View when it isn't really needed.
