### ISSUE TITLE
Add a single article, do not subscribe

### ISSUE THREAD

**Issue by joeworkman** [Ranchero-Software/NetNewsWire#3664]
I would love to share a single article to NNW. I don't want to subscribe to the entire blog feed. I basically want to have a Reading List in NNW comprised of individual blogs. 

Could it be possible to integrate with Safari Reading List?

**Comment by brentsimmons** [comment]
For me it appears in the Share menu as Add to Reading List. You may have to choose More… and customize your Share menu to have it appear.

**Comment by joeworkman** [comment]
@brentsimmons I think that you misunderstood my request. I want NNW to be my one place to read content. If I had an article to read, I want to add it to NNW as a one off article to read. I do not want to subscribe to that blog's RSS feed.

**Comment by brentsimmons** [comment]
You’re right! I totally misunderstood.

Some of the read-later services offer RSS feeds, I think. If you use one of those systems, it’s conceivable that you could subscribe to your own feed of read-later articles and read them in NetNewsWire. (They probably wouldn’t get marked as read in the service, though.)
