### ISSUE TITLE
Will there be Tiny Tiny RSS in the future?

### ISSUE THREAD

**Issue by i-iooi-i** [Ranchero-Software/NetNewsWire#3665]
Will there be tiny tiny RSS in the future?
NetNewsWire is almost perfect, but ttrss can't be added all the time, which is a pity. I hope there will be such a plan in the future.Good luck.😘😘😘

**Comment by Wym1ng** [comment]
Yes, I would also like NetNewsWire to support ttrss because it's a great experience, not too fond of Reader in comparison.

**Comment by vincode-io** [comment]
Duplicate of #388.

**Comment by eric-pierce** [comment]
Tiny-Tiny RSS is now usable with NetNewsWire. I recently published a plugin for Tiny Tiny RSS that will allow NetNewsWire to interface with it using the FreshRSS API here: https://github.com/eric-pierce/freshapi

I've got to say NNW is a really nice experience, better with TT-RSS as the server. If you give it a shot please provide any feedback or issues you find!
