### ISSUE TITLE
Missing "Open Link" option when right-clicking a link in the article

### ISSUE THREAD

**Issue by GetToSet** [Ranchero-Software/NetNewsWire#3666]
To prevent accidentally replacing current content, I always open a link with a right click rather than direct clicking it. Thus I assume the first contextual menu item of a link would always be "Open Link" or "Open Link in New Tab", this would be the truth for every Apple's application.

NetNewsWire:
<img width="624" alt="2022-08-28 16 55 57" src="https://user-images.githubusercontent.com/8158163/187066062-45abba1e-3b59-48e3-b6ec-334f08c55ce7.png">

Apple Mail:
<img width="624" alt="2022-08-28 16 56 06" src="https://user-images.githubusercontent.com/8158163/187066067-75e5366f-61ef-4e17-9188-839edec4b126.png">

It seems NetNewsWire is missing this option and should NetNewsWire implement such behavior? If this is a proper behavior, I'd be happy to contribute to implementing it.

**Comment by vincode-io** [comment]
Please check out our [Contributing](https://github.com/Ranchero-Software/NetNewsWire/blob/main/CONTRIBUTING.md) document. It will let you know how to get approval for a feature to implement in NetNewsWire.
