### ISSUE TITLE
Problem with article parsing 

### ISSUE THREAD

**Issue by michalzelazny** [Ranchero-Software/NetNewsWire#3673]

**Comment by michalzelazny** [comment]
All articles delivered by this source https://oko.press/feed/ cannot be delivered properly. There is a problem with parsing article text. Safari reading mode works fine.

**Comment by stuartbreckenridge** [comment]
What is the issue?

**Comment by stuartbreckenridge** [comment]
Ah!

Safari Reader View and NetNewsWire Reader View are different technologies. We don't host our Reader View implementation and therefore don't have much control when it is unable to scrape article content.
