### ISSUE TITLE
ios：Unable to play audio file

### ISSUE THREAD

**Issue by Spaceship007** [Ranchero-Software/NetNewsWire#3675]
No audio file playback location found in the page.
Is this the default function of the software？or just a bug?
Sorry if there's inappropriate expression,for english is not my mother language

**Comment by brentsimmons** [comment]
What’s the URL of the feed? In which article were you expecting to see audio file playback?

**Comment by Spaceship007** [comment]
https://www.stovol.club/rss
https://feeds.buzzsprout.com/1982525.rss
these two URLs，the content are all supposed to have audio files，they‘re podcasts

**Comment by vincode-io** [comment]
NetNewsWire is an RSS Reader. What you need is a podcasting app like the Podcasts.app that is included on iOS. You will need to manually add these podcasts by URL for it to work.

In Podcasts.app on iOS 16:

1) Click on the Library tab at the bottom
2) Click on the More menu in the top right
3) Select "Follow a Show by URL..."
4) Paste the podcast URL into the dialog box that appeared
5) Click the Follow button

You should now have access to the podcast along with audio, show notes, etc...
