### ISSUE TITLE
Syncing Issues with Feedly

### ISSUE THREAD

**Issue by sarvagnan** [Ranchero-Software/NetNewsWire#3680]
I am facing syncing issues with Feedly and the NNW clients. I use NNW on macOS and iPadOS with my Feedly account linked to both. In the past, when I marked feeds read on one client, the change would propagate to Feedly and to the other NNW client. Now however, each seems to maintain a separate state that only it is aware of. The NNW macOS and iPadOS clients keep track of which feeds have been read on their ends but do not sync with each other or the Feedly web client. I am not sure how to produce logs for this.

**Comment by vincode-io** [comment]
Did you restore anything from a Time Machine backup or migrate to a new device lately?

**Comment by sarvagnan** [comment]
I have not. The only possible issue in the setup is that the iPad is on the 16 beta. Everything else has stayed the same. However, up until a month or so ago, everything was syncing (including on the iPad with the beta OS)

**Comment by vincode-io** [comment]
If you do a manual refresh on either your Mac or iPad, do you get an error?

When you check against the Feedly web interface, which matches it? Your iPad or your Mac?

**Comment by sarvagnan** [comment]
I don't get any errors on either the iPad or the Mac. None of them are in sync either. To test, I read a bunch of feeds on one device, then synced. Checked Feedly online and the other device. All of them show different unread counts. Each device seems to be keeping track of everything that has been read on that device, but is not syncing them over to Feedly itself.

**Comment by vincode-io** [comment]
I don't know what is happening to be honest. To resolve it, I recommend deleting your Feedly accounts on both your Mac and iPad and recreating them.

**Comment by sarvagnan** [comment]
I reset everything and that finally made it work. I'm annoyed that I don't know why it stopped working, because nuking and restarting isn't really a solution, but it's worked for now. Thank you for your help and apologies for the bother.

**Comment by vincode-io** [comment]
Most likely your local sync databases got corrupted. We aren't sure how this happens and it isn't a common occurrence, but it seems to happen for all Account types. We're sorry this happened, but are glad that you are back up and working again.
