### ISSUE TITLE
Wrong article when reading The Verge - NNW for iOS

### ISSUE THREAD

**Issue by mape85** [Ranchero-Software/NetNewsWire#3688]
I am subscribed to the main feed of [The Verge](https://www.theverge.com).
The feed is at: [https://www.theverge.com/rss/index.xml](https://www.theverge.com/rss/index.xml)

I've noticed that when I open some articles Net News Wire shows me the text of a completely different one. For example I opened the articled titled [The iPhone 15 ‘Ultra’ could replace the Pro Max](https://www.theverge.com/2022/9/25/23371160/iphone-15-ultra-replace-pro-max-apple-rumors-usb-c) and NNW showed me something about crash detection on the new iPhone 14.

For The Verge I use Reader view. I noticed that if I toggle that view off, I get an excerpt of the article I want. If I turn it on again, it gives me the content of that other weird article.

Is this an issue of The Verge's feed or NNW?

Screen recording of the issue here: [https://share.icloud.com/photos/014WWhHueJ_z59UKV-S8pMIhw](https://share.icloud.com/photos/014WWhHueJ_z59UKV-S8pMIhw)

**Comment by vincode-io** [comment]
It looks like there is an issue with the Reader View service that we are using that is only impacted when viewing The Verge. There isn't anything we can do about this because it is a 3rd party service and not under our control.

Why are you using Reader View for The Verge? The RSS feed contains full article content and using Reader View only slows down being able to read the article.

**Comment by mape85** [comment]
I use reader view because it's the only way I get full articles on The Verge.

No reader view: [https://share.icloud.com/photos/01f6Z5bQ0oBWTyP-wQ3yxIS4Q](https://share.icloud.com/photos/01f6Z5bQ0oBWTyP-wQ3yxIS4Q)

Reader view: [https://share.icloud.com/photos/0d4zAGG3fh9ZILoXtQper1Sbg](https://share.icloud.com/photos/0d4zAGG3fh9ZILoXtQper1Sbg)

I accept workarounds, hacks, and suggestion if you have any. 😊

**Comment by vincode-io** [comment]
Use this URL. 

http://www.theverge.com/rss/full.xml

**Comment by mape85** [comment]
I hate that it was so easy…

ಠ_ಠ

Thank so much!
