### ISSUE TITLE
Bug: iOS and macOS feed lists don’t match (using iCloud)

### ISSUE THREAD

**Issue by stevenjmesser** [Ranchero-Software/NetNewsWire#3694]
I’m using the macOS app and the iOS app, both using iCloud as syncing. I’ve been trying to understand why the number of unreads on iOS is different to macOS, and came across this problem.

As an example, the first 10 feeds in my Subscriptions folder on macOS are as follows:
![image](https://user-images.githubusercontent.com/23193154/192455931-0bbcbfe6-1a23-441d-a8cf-246f7865edac.png)

1. | More Than Human
2. | Peter Merholz
3. A Stick a Dog and a Box with Something In It
4. A Whole Lotta Nothing
5. Adactio: Journal
6. Adam Curtis Feed
7. Adam Greenfield
8. Addis Army Cricket
9. AI Weirdness  
10. Alex McLean

The first 10 feeds in the same folder on iOS are as follows:
![image](https://user-images.githubusercontent.com/23193154/192456222-347b00d0-8a29-4377-964e-ece15ce9d285.png)

1. A Stick a Dog and a Box with Something In It
2. A Whole Lotta Nothing
3. Adactio: Journal
4. Adam Greenfield
5. Alex McLean
6. Applied Mythology
7. Articles on Smashing Magazine
8. Automatter
9. AVC
11. BLDGBLOG

**Comment by vincode-io** [comment]
Those aren't even close. Are you sure you are using the same Apple ID on your Mac as your iOS device?

**Comment by brentsimmons** [comment]
Did you set up iCloud syncing in NetNewsWire? It’s not automatic — you have to go Preferences > Accounts and add an iCloud account.

**Comment by stevenjmesser** [comment]
> Those aren't even close. Are you sure you are using the same Apple ID on your Mac as your iOS device?

Yup, definitely.

**Comment by stevenjmesser** [comment]
> Did you set up iCloud syncing in NetNewsWire? It’s not automatic — you have to go Preferences > Accounts and add an iCloud account.

Yep, those are the steps I took.

**Comment by stevenjmesser** [comment]
I’m going to try
- removing the iCloud account from iOS
- exporting the subscriptions to OPML
- removing the iCloud account from macOS
- deleting the NetNewsWire files from iCloud, and
- starting again.

OK, I did the above and loaded the OPML file back into my iCloud account (On My Mac is inactive). That gave me 10,000+ unreads, which I’ve marked all as read. I’ve re-added the iCloud account to iOS and it seems to have fixed it!

**Comment by vincode-io** [comment]
I have no idea what happened there. I've never seen anything like it before.

Since you got it resolved and there isn't any data to analyze, I going to call this one a fluke and close the issue.
