### ISSUE TITLE
BazQux is not loading articles

### ISSUE THREAD

**Issue by KYakerDude** [Ranchero-Software/NetNewsWire#3708]
I'm unable to load any articles with NetNewsWire using BazQux.  It loads the folders, so there is a connection.  And I'm able to use Inoreader and TheOldReader just fine.  I've tried entering my BazQux info a second time but still no luck.

**Comment by vincode-io** [comment]
Is this a new BazQux account you are using or one you've had for a while?

**Comment by KYakerDude** [comment]
I’ve had this account for years.

**Comment by vincode-io** [comment]
How long ago did you set up BazQux in NetNewsWire?

**Comment by KYakerDude** [comment]
I just re-set it up this morning.

**Comment by vincode-io** [comment]
Can you look at the console while you are trying to sync BazQux to see if you are getting any errors?

**Comment by vincode-io** [comment]
This might be related to #3605. Do you have any feeds with a lot of unread items in it?

**Comment by KYakerDude** [comment]
I'm not getting any errors.  I also have Inoreader enabled and that is working.  I don't have any feeds with lots of unread items in them.  The most is 2-3.

**Comment by vincode-io** [comment]
I have no idea what is happening.

If you don't have anything sensitive in your account, do you mind if I took a look? You could change your BazQux account password to something you don't mind sharing and then send me your credentials. If that is ok with you, you can text them to 402-578-6764.

I wouldn't normally ask this of someone, but I can't think of any other way to debug it. If I'm able to sign on to your account using my computer, I can inspect the messages between NNW and BazQux and finally get to the bottom of this. I'm pretty sure this is the same problem as is in the other issue I referenced earlier and was never able to solve.

**Comment by vincode-io** [comment]
Many thanks to @KYakerDude for helping me debug this! We were requiring a JSON property that we shouldn't have and it was failing to decode the article response because of this. It is now fixed and we will try to get a fix out as soon as possible.
