### ISSUE TITLE
The iOS version no longer updates the feeds

### ISSUE THREAD

**Issue by Tanduras** [Ranchero-Software/NetNewsWire#3709]
For quite some time I have been using the MacOS version of NetNewsWire with great enthusiasm, synchronizing my subscribed feeds via iCloud.  Now I have also installed the iOS version on my iPad, which then also took over all feeds. However, not a single feed is updated there, meaning the articles section is empty.

The only way I found out is to delete the RSS address and create a new one. Unfortunately, then only updated for the moment and then no further update takes place. Fortunately this problem does not exist with my MacOS version 6.1!

**Comment by vincode-io** [comment]
This document should get you straightened out.

[iCloud Syncing Limitations & Solutions](https://netnewswire.com/help/iCloud)

**Comment by pinguinpfleger** [comment]
I can't believe that a limit on iCloud's bandwidth is to blame for the fact that syncing no longer works.
