### ISSUE TITLE
iOS/iPadOS/macOS clients out of sync through The Old Reader

### ISSUE THREAD

**Issue by barrymieny** [Ranchero-Software/NetNewsWire#3717]
iPad: iPadOS 15.7 / NNW 6.0.2 (Build 610)
iPhone: iOS 16.0 (20A362) / NNW 6.0.2 (Build 610)
Mac: macOS 12.6 / NNW 6.1 (6106)

For both the Mac and iPad, if I sync/refresh after marking some articles as read the others will see the updated read statuses, whereas if I sync/refresh from the iPhone after marking some articles as read then the other 2 clients don't see the updated read statuses.

So the best I can imagine at this time is that the iPhone doesn't update the read statuses correctly.

This has been happening since I updated the iPhone to iOS 16.

I have checked The Old Reader after doing a sync/refresh from the iPhone and the articles are still unread on there. Is there anything else I can do from my side to help diagnosing this issue further?

**Comment by vincode-io** [comment]
You probably don't know how to use something like Proxyman to watch what The Old Reader is sending back to you, right? If not, you probably can't do much to track this down, which is totally cool.

To get your iPhone working again, I recommend removing The Old Reader account from your iPhone and add it again.

**Comment by barrymieny** [comment]
I've got Proxyman running on my phone, and I'm seeing a lot of 404s when POSTing to https://theoldreader.com/reader/api/0/edit-tag.

The request headers are:
```
POST /reader/api/0/edit-tag HTTP/1.1
Host: theoldreader.com
Content-Type: application/x-www-form-urlencoded
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Accept: */*
User-Agent: NetNewsWire (RSS Reader; https://netnewswire.com/)
Authorization: GoogleLogin auth=anonymisedanonymised
Content-Length: 8903
Accept-Language: nl-nl
```

The body includes `T=anonymisedanonymised&i=tag:google.com,2005:reader/item/012345678901234567890123&I=...` with exactly 150 `&i=...` items.

The response body for these requests are:
```xml
<errors type="array">
  <error>Not found</error>
</errors>
```

If I mark an item as unread, that POST does succeed.

**Comment by vincode-io** [comment]
Nicely done!

That endpoint is supposed to be there according to their documentation and it did used to work. I tested it myself.

I've emailed support for The Old Reader. I'll update this issue when I find something out.

**Comment by vincode-io** [comment]
@barrymieny I just tested this with my The Old Reader account and it works fine. I wonder if there is an item that you have on your iPhone that is trying to be marked as read and it isn't in The Old Reader database anymore. Just a theory.

I don't think we need to spend too much time on this. Just remove your The Old Reader account from your iPhone and add it again. You should be fine.

I'm going to close this issue, but if you see it again, we will definitely get to the bottom of it.

**Comment by shuang886** [comment]
Noticed this happening on my iPad running NetNewsWire 6.1.4 (6120) on iPadOS 17.0.3, seems to be also resolved by removing and re-adding The Old Reader account.
