### ISSUE TITLE
YouTube videos crash when rotating iPhone screen

### ISSUE THREAD

**Issue by stewf** [Ranchero-Software/NetNewsWire#3724]
Open [a post](https://www.macrumors.com/2022/10/26/ipad-10-m2-ipad-pro-hands-on/) with an embedded YouTube video. Play video and go full screen. Rotating the screen stops the video and returns to post view. 

I’m using NNW 6.0.2.

**Comment by vincode-io** [comment]
Duplicate of https://github.com/Ranchero-Software/NetNewsWire/issues/2369.
