### ISSUE TITLE
Where to find feeds on drive

### ISSUE THREAD

**Issue by a2history** [Ranchero-Software/NetNewsWire#3725]
Netnewswire 6 - I moved to new computer but did not export my feeds. Where on the backup drive (which is not bootable) can I find my old news feeds? I do not see a ~/Library/Application Support/Netnewswire folder in the old directory.

**Comment by vincode-io** [comment]
What type of account were you using?

**Comment by a2history** [comment]
Sorry to give a stupid answer, but I’ve been using this for so long, I do not know.

**Comment by vincode-io** [comment]
Check around in `~/Library/Containers/com.ranchero.NetNewsWire-Evergreen/Data/Library/Application Support/NetNewsWire/Accounts`.  Your `Subscriptions.opml` file will be in there somewhere.

**Comment by a2history** [comment]
That was the solution I needed. Gracias!

**Comment by a2history** [comment]
One other issue - doing this on Ventura, and in the Privacy & Security area os System Settings, it seems to be stuck on “Allow applications downloaded from” —> “App Store and identified developers” —> NetNewsWire was blocked from use because it is not from an identified developer. “Open Anyway”. 

NetNewsWire is working, it has all of my feeds, but clicking the “open anyway” button does nothing, and I cannot open OTHER things that need to be opened anyway. 

How can I make that unstick?

**Comment by vincode-io** [comment]
What are "OTHER things"?

**Comment by a2history** [comment]
I’m in the process of re-adding all of my applications, and for some of them I have to use the “open anyway” button. However, NetNewsWire seems to be hogging it right now.
