### ISSUE TITLE
Feedly for iOS Frequently Has Errors

### ISSUE THREAD

**Issue by adamspelbring** [Ranchero-Software/NetNewsWire#3730]
While my Feedly account has never had a single issue with NetNewsWire on the Mac, every week or two on iOS, I get an error saying to add the Feedly account again. (See attached image.) So I remove the account and then add it back and it works fine again for a little while. One thing to note is that I mostly use NNW on the Mac. I only use it on iOS 2-3 times a week.

I really love NetNewsWire and it's flawless on the Mac. I just wonder if there's a problem with Feedly on iOS and if I should try using a different service or if this is an actual bug that needs fixing.

Thanks to the whole NNW team.

![NetNewsWireFeedly](https://user-images.githubusercontent.com/20424924/200143516-a2def880-2c05-42f5-bc9b-d8973b3da566.jpeg)

**Comment by brentsimmons** [comment]
Are you still seeing this bug?

**Comment by adamspelbring** [comment]
Hey Brent. Thanks for getting back to me. If this is about my Feedly issue, I actually switched to iCloud syncing many months ago and it’s been rock solid on all of my devices. So while I can’t speak to Feedly anymore, iCloud is great and really what I wanted anyway.  Be well. AdamFrom my iPhoneOn Mar 10, 2023, at 12:25 AM, Brent Simmons ***@***.***> wrote:﻿
Are you still seeing this bug?
