### ISSUE TITLE
Feature Request: Auto Delete Data After X Days

### ISSUE THREAD

**Issue by goferit** [Ranchero-Software/NetNewsWire#3736]
News moves fast and old headlines become obsolete quickly. Meanwhile device data piles up and storage space gets tight.

Add a setting to delete data after X days (not including the current day). Could be fleshed out on a feed basis, “every”, “since”, “before/ after/ between” filters, but “after X days” is a fine start.

**Comment by vincode-io** [comment]
We do delete data from the local database. Please read our [Retention Policy](https://github.com/Ranchero-Software/NetNewsWire/blob/main/Technotes/RetentionPolicy.markdown) for details.

We don't have plans to make this a user configurable setting. We work hard to make sure that NetNewsWire isn't fiddly and confusing to configure. We don't want to stress our users out by giving them the impression that this is something that they have to fine tune to get NetNewsWire to work optimally.
