### ISSUE TITLE
iPad app won't refresh

### ISSUE THREAD

**Issue by brijazz** [Ranchero-Software/NetNewsWire#3744]
I primarily use NNN on my Mac. I have an older iPad Air 2 (running iPad OS 15.6.1) that I don't use a lot, so I haven't opened NNN there in quite some time. Fired it up today only to find that the app refuses to refresh my feeds (showing zero unread, which is not accurate).

To troubleshoot, I've tried:

1) toggling my iCloud account off/on in the app
2) deleting and reinstalling the app
3) rebooting the iPad
4) adding a new feed to try to "kickstart" things - that new feed worked, but other feeds are still showing zero unread.

Any thoughts on how to get things going again?

**Comment by vincode-io** [comment]
This help page should get you going again. https://netnewswire.com/help/iCloud
