### ISSUE TITLE
[Feature Request] Mark Previous as Read

### ISSUE THREAD

**Issue by rifelpet** [Ranchero-Software/NetNewsWire#3750]
Thanks for the app! Really enjoying it so far.

When viewing a viewing a feed with many unread items and scrolling through them from top to bottom, sometimes I don't have time to get all the way through the list before being interrupted with something.

When interrupted, my options are:
- Mark all as read and lose out on the items I haven't gotten to yet
- Don't mark any as read and have to scroll back through items I've already seen next time
- Mark each item as read individually as I pass over them which involves an unnecessary amount of interaction

It would be great if there was an option similar to "Mark all as Read" but only for items I've scrolled past already.

**Comment by brentsimmons** [comment]
There is a “Mark Above as Read” command that should do the trick.

**Comment by rifelpet** [comment]
Ah, I didnt realize this already exists. For reference, long tap an article and the context menu brings up "Mark Above as Read" and "Mark Below as Read" options 👍🏻  Thanks!
