### ISSUE TITLE
[Bug] Date parsing incorrect

### ISSUE THREAD

**Issue by venilnoronha** [Ranchero-Software/NetNewsWire#3751]
I’m noticing an issue where the dates in the following feed are displayed incorrectly on the iOS app.

https://www.thoughtworks.com/rss/insights.xml

Here’s what I see:

![5E728F37-A3D0-423F-93CB-BC488D104FD9](https://user-images.githubusercontent.com/1722758/202575431-922ebf95-e539-46dc-b4e3-60221992b87d.jpeg)

while here’s what the feed xml returns:

![AF62B75C-5E5F-4CAD-8FC5-1D5EB8061B9A](https://user-images.githubusercontent.com/1722758/202575503-f7b0e010-fadd-46e1-af47-297f058d2be8.jpeg)

**Comment by brentsimmons** [comment]
The date in the feed is not using the proper format:

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.thoughtworks.com%2Frss%2Finsights.xml

Note the error: `pubDate must be an RFC-822 date-time`

A properly formatted date would look like this:

`Wed, Nov 16 2022 00:00:00 GMT`

**Comment by venilnoronha** [comment]
@brentsimmons appreciate the quick response!

I'm wondering if it should still be handled, just for better UX. I don't feel very strongly though, as I'm still able to read these entries, just not in order.

**Comment by brentsimmons** [comment]
I don’t like adding special cases to the date parser for an individual feed — it means adding code that will run for every feed, regardless, which will incrementally slow down the parser, use more battery, etc. for everybody
