### ISSUE TITLE
Clean up mastodon feeds

### ISSUE THREAD

**Issue by adamjrice** [Ranchero-Software/NetNewsWire#3753]
Mastodon generates RSS feeds for users and hashtags, but (at least for the hashtags, which I am trying out), the titles messily show raw HTML—usually. For example

````
Rudydoesbooks@mstdn.social: “<p><span class="h-card"><a hre…”>
````

I can see a few entries in a tag feed where the title lacks the HTML. And the body looks correct.

**Comment by stuartbreckenridge** [comment]
@adamjrice Which tags are you trying? I am not seeing issues with the rendering.

**Comment by stuartbreckenridge** [comment]
Have you got a screenshot? I followed #cycling on mstdn.social and it seemed ok.

**Comment by adamjrice** [comment]
See attached.
<img width="374" alt="#cycling screenshot" src="https://user-images.githubusercontent.com/15695982/203217939-19524fef-0db0-4555-a6fd-87c193610651.png">

**Comment by stuartbreckenridge** [comment]
I am not seeing that issue. Is that a fork of NetNewsWire as it has a similar look, but isn't rendered like the current production build. 


![image](https://user-images.githubusercontent.com/7046652/203219435-110e2a53-71e8-4bfc-8d73-543a2f0c4d45.png)

**Comment by adamjrice** [comment]
My screenshot is from Version 6.1 (6106) on the Mac. I haven't tried this in iOS (NNW takes forever to refresh feeds for me on iOS).

**Comment by brentsimmons** [comment]
What type of account?

**Comment by adamjrice** [comment]
iCloud

**Comment by brentsimmons** [comment]
iCloud explains the slow refresh. https://netnewswire.com/help/iCloud

**Comment by brentsimmons** [comment]
Could I get the feed URL for one of these?

**Comment by adamjrice** [comment]
http://mastodon.cloud/tags/austintx.rss  Obviously that’s just my home instance.

**Comment by brentsimmons** [comment]
I can reproduce this using that URL.

Here’s the thing: there are HTML tags inside the `<title>` element in that feed. But the HTML spec is silent on what to do in this case. Treat as HTML? Or show them as is? It doesn’t say.

It might seem like an obvious answer, but it’s not. What if the title is the `The problem with non-semantic <div> elements`? The `<div>` should show, obviously.

So the policy has been to treat the `title` as plain text, since treating it as HTML could result in parts of the title not being shown.

We could do a special case for Mastodon feeds, but there’s nothing in every Mastodon feed that identifies it as a Mastodon feed. We could make a guess, though, and just be wrong some of the time.

**Comment by stuartbreckenridge** [comment]
I am not this seeing this issue at all: `https://mstdn.social/tags/cycling.rss` 

<img width="1095" alt="Screenshot 2022-11-22 at 13 09 33" src="https://user-images.githubusercontent.com/7046652/203226973-1898d41b-d478-49d1-a2b2-6dfae32a5acc.png">

**Comment by brentsimmons** [comment]
My bet is that different instances are configured differently and/or run different versions of the software.

**Comment by stuartbreckenridge** [comment]
Actually:
- `https://mastodon.cloud/tags/austintx.rss` has issues
- `https://mastodon.social/tags/austintx.rss` is fine

I assume it's an issue with the `matsodon.cloud` instance, which has a slightly different structure to the `mastodon.social` instance: 
- `cloud` is being served via Cloudflare
- `social` appears to be coming directly from Mastodon.



<img width="1088" alt="Screenshot 2022-11-22 at 13 17 41" src="https://user-images.githubusercontent.com/7046652/203227946-79673701-a9d5-4e5c-926b-9264da12abee.png">

**Comment by stuartbreckenridge** [comment]
@brentsimmons / @adamjrice This appears to be an issue with mastodon.cloud. Their server admins emailed me. 

![image](https://user-images.githubusercontent.com/7046652/203319213-d9e23678-337e-49d3-ab59-8143bbc6798c.jpeg)
