### ISSUE TITLE
Stuck on `Finding feed..`

### ISSUE THREAD

**Issue by nikitavoloboev** [Ranchero-Software/NetNewsWire#3760]
Get this whenever I add any feed now. For example trying to add https://nnw.ranchero.com/feed.xml feed and get:

<img width="695" alt="image" src="https://user-images.githubusercontent.com/6391776/203653026-f509cc3b-9e87-49fd-b434-464fffc31323.png">

App becomes non responsive and is like this for 20+ min.

Not sure what to do, everything worked before.

macOS 13.0.1
NetNewsWire 6.1

**Comment by brentsimmons** [comment]
What kind of account are you using?

**Comment by nikitavoloboev** [comment]
iCloud.

**Comment by nikitavoloboev** [comment]
Okay it started working again. 

If this happens again. Is there anything I can send you to understand why it freezes the app? @brentsimmons
