### ISSUE TITLE
Tag RSS feeds and browse by tag

### ISSUE THREAD

**Issue by freyquency** [Ranchero-Software/NetNewsWire#3767]
The paradigm of folders quickly breaks apart for RSS feeds. It always has – see Kottke's blog and put that in a folder that describes the content.

I'd like to be able to tag things like Imani Barbarin's blog with `disability, race, accessibility, politics` and have it show up in those reading queues.

**Comment by brentsimmons** [comment]
I have Kottke’s blog in a folder called “Blogs.” :)

Point taken, though. If you’re using an On My Mac/iPad/iPhone account or an iCloud account, you can actually have a feed appear in multiple folders if you want to.

Drag and drop the feed into a different folder — but hold down the option key as you do so. This will make a copy.

You could have separate folders for each of disability, race, accessibility, and politics and put a copy of Imani Barbarin's blog in each folder.

(To be clear — the feed isn’t exactly copied. It’s the exact same feed, with the same settings and statuses, in each location. Which is what you want — you wouldn't want to read each article multiple times.)
