### ISSUE TITLE
One Feed hangs when fetching

### ISSUE THREAD

**Issue by hybras** [Ranchero-Software/NetNewsWire#3773]
This is not a bug report or feature request.
Whenever my feeds refresh, it hangs at (n-1/n) feeds. I assume there's a single feed that takes longer than the others to refresh. How can I find out which? Is there a log somewhere?

**Comment by vincode-io** [comment]
What kind of account are you using?

**Comment by brentsimmons** [comment]
NetNewsWire of Yore had an Activity window which would let you see that. That’s something we could consider adding to modern NetNewsWire. (Should create a separate feature request for this. Might be one already.)

**Comment by hybras** [comment]
I'm using "on my mac" only
