### ISSUE TITLE
App Store -- Presentation Issue

### ISSUE THREAD

**Issue by vikinglumberjack** [Ranchero-Software/NetNewsWire#3776]
Hey, I just wanted to give an FYI regarding a minor, but confusing issue with your app in the App Store; I just read about your app on the web, and went to install it from the App Store, but when I searched for it by name, I got results for other RSS readers. Then, when I finally found it, the App Store displayed a little message at the top: "Not compatible with this device." I'm running Ventura 13.0.1 on an M1 Mini. Fortunately, I was able to download and install your app from your website, but I assume you would consider this situation to be sub-optimal, as it could deter people from using your app. I've attached some screenshots. Please let me know if you have any questions.

Thanks!
![Screenshot 2022-12-15 at 05 58 51](https://user-images.githubusercontent.com/8934908/207842637-6dd3cd21-cc07-4943-a4e3-8124f6bdf135.png)
![Screenshot 2022-12-15 at 05 56 24](https://user-images.githubusercontent.com/8934908/207842700-4a3950e3-d215-45e8-8814-3d387c8ce19f.png)

**Comment by stuartbreckenridge** [comment]
The macOS app is not available via the Mac App Store. The version you are seeing there is the iOS version, which we have flagged as not compatible with macOS.
