### ISSUE TITLE
Twitter Screen Name Feed not updating past Dec 13

### ISSUE THREAD

**Issue by tghuguenin** [Ranchero-Software/NetNewsWire#3780]
I follow several Twitter accounts via the Twitter extension of NetNewsWire. I noticed today that none of them have any tweets pulled in later than Dec 13. Other types of Twitter extension feeds, such as Mentions and Searches, seem to still be working.

**Comment by brentsimmons** [comment]
Since Twitter integration will stop working soon — as soon as Twitter ends free Twitter API access — I’m closing this.
