### ISSUE TITLE
Not refreshing all feeds at a time

### ISSUE THREAD

**Issue by instrumaker** [Ranchero-Software/NetNewsWire#3782]
<img width="407" alt="image" src="https://user-images.githubusercontent.com/25771042/208605989-a147ef64-4a87-48a9-a817-b81836ea5048.png">
<img width="345" alt="image" src="https://user-images.githubusercontent.com/25771042/208615355-94ea0d51-3f9c-48cf-9737-2f0c8b077104.png">

Every time I manually refresh NNW, it only sends 4-5 feed updating requests though I have roughly 100 feeds.
I tried different network(WIFI and 5G)/Reinstalled NNW/Changed different feed bundles, and the problem remain the same. Have tried other RSS Reader apps, they work fine though.
Anyone have any ideas? Really bother me here ... 😢

**Comment by vincode-io** [comment]
What kind of account are you using and how are you trying to determine if NetNewsWire is checking a feed? It looks like you are looking at the console which doesn't log when a feed is checked. You would have to use something like ProxyMan to check network access.

I'm going to close this issue, but we can reopen if if you can provide better data that shows that NetNewsWire isn't checking feeds.
