### ISSUE TITLE
[iOS] Widget Articles Are in Random Order

### ISSUE THREAD

**Issue by stuartbreckenridge** [Ranchero-Software/NetNewsWire#3783]
Articles are added to `Set`s and left unordered in the widget encoder. This means that when the widget data is encoded the articles are in a random, inconsistent order each time.

**Comment by vincode-io** [comment]
@stuartbreckenridge Would you please not bundle unrelated bug fixes and features into omnibus pull requests? It makes it really hard for me to validate what changed and why.

**Comment by stuartbreckenridge** [comment]
(This fix is no longer part of the #3778 PR.)
