### ISSUE TITLE
OMPL export file lacks options metadata

### ISSUE THREAD

**Issue by ekamil** [Ranchero-Software/NetNewsWire#3793]
To reproduce 
1. have subscriptions from Feedbin (not sure if the account type matters)
2. check option for "Always Use Reader View"
3. export feeds
The feed in resulting OPML has no metadata corresponding to the option.

Ideally OPML could contain all the data required to restore one's subscriptions.

**Comment by brentsimmons** [comment]
When exporting OPML we’re making sure it’s of the same format that other readers expect.

Other readers know nothing about our extra metadata, and so we don’t include that in the exported OPML, because it could prevent OPML import from working with other readers.

**Comment by michaeljtsai** [comment]
It seems like that’s against the spirit of XML, ignoring attributes that you don’t know about. What are these other readers doing instead?

**Comment by brentsimmons** [comment]
I haven’t seen OPML with custom attributes from any other reader. Doesn’t mean it doesn’t exist, but I’ve never seen it.

We’re following the “be conservative in what you send” rule with this, to make sure our OPML is compatible with every other RSS reader.

**Comment by michaeljtsai** [comment]
[Tiny Tiny RSS](https://tt-rss.org) does this by default.
