### ISSUE TITLE
Add a Mastodon feed provider extension

### ISSUE THREAD

**Issue by leonp** [Ranchero-Software/NetNewsWire#3796]
We can currently follow our Twitter and Reddit streams via NetNewsWire.

With the popularity of Mastodon – but it’s similarity to Twitter (feed, likes, boosts etc.) – it’d be good to have the option to be able to read our feeds in NetNewsWire.

I would see it working in the same way, as an extension.

<img width="624" alt="NNW extension picker pane." src="https://user-images.githubusercontent.com/2016649/209838437-9733e6d6-8d86-484b-9a5a-ba71705edec8.png">

<img width="624" alt="NNW add an extension pane." src="https://user-images.githubusercontent.com/2016649/209838488-259b655b-ad47-4209-bcbe-d2571a2b59df.png">

**Comment by danny-berg-whitt** [comment]
@leonp I agree with adding this extension!

That said, it is already possible to follow Mastodon-compatible feeds. Simply add a feed with the URL formatted as the username appended with `.rss`, e.g:*
```
https://mastodon.social/@username.rss
```
Even entering this URL into my browser results in:
<img width="451" alt="image" src="https://user-images.githubusercontent.com/40334869/211369122-76ef9925-46ea-41f3-b6db-015dc91c7021.png">

* [Here's](https://mstdn.social/@feditips/108357998963885456) a note posted exploring this feature.

**Comment by tylerbenson** [comment]
The Twitter view is nice because it includes media in the post. When subscribing to a mastodon post via rss, it only shows the text. I have to visit the url to see any images. It would be nice if the integration can display a more rich view.

**Comment by sjoerger** [comment]
Just wanted to add that this also works for following hashtags such as https://mastodon.world/tags/infosec.rss

**Comment by brentsimmons** [comment]
We can enhance Mastodon support without having to add a feed provider extension.
