### ISSUE TITLE
Previously deleted local feeds reappear on iPhone and iPad when reinstalling NetNewsWire

### ISSUE THREAD

**Issue by jeremybickerstaffe** [Ranchero-Software/NetNewsWire#3798]
Weird bug on my iPhone. I installed NetNewsWire and found several feeds in the local account that I'd previously deleted the last time I had it installed.

These steps reliably reproduce the problem on my iPhone.
1. Install NetNewsWire
2. There are several feeds in the "On My iPhone" account
3. Delete the feeds
4. Uninstall NetNewsWire
5. Reinstall NetNewsWire
6. The previously deleted "On My iPhone" feeds are there again

I did some investigating and found the problem also affects my iPad, the same feeds appear in the "On My iPad" account each time I install NetNewsWire.

**Comment by stuartbreckenridge** [comment]
This is working correctly—the default local account is created (with sample feeds) when the app is installed (or re-installed).
