### ISSUE TITLE
mis-represented unicode pi character

### ISSUE THREAD

**Issue by denisa** [Ranchero-Software/NetNewsWire#3800]
Reading http://brooker.co.za/blog/2022/12/15/thumb in the internal reader fails to display properly the Pi symbol (look toward the bottom of thepost).

It displays ok in Safari

**Comment by brentsimmons** [comment]
What’s the URL of the feed? What kind of account are you using?

**Comment by stuartbreckenridge** [comment]
The π symbol seems ok using the NetNewsWire theme. However, I do see
that the footnotes aren't displayed when the reader view is active. 


![image](https://user-images.githubusercontent.com/7046652/210027709-4becb771-0a66-481c-b877-1ae808dbabee.png)

![image](https://user-images.githubusercontent.com/7046652/210027814-3cb7a703-ab28-45a4-91ba-1f9882cd41df.png)

**Comment by denisa** [comment]
Please see at the bottom-right:

![image](https://user-images.githubusercontent.com/1205618/210030858-b2fa2c59-5d35-4110-a7bd-2a8f70fef3ad.png)

**Comment by denisa** [comment]
the feed url is: <http://brooker.co.za/blog/rss.xml>

**Comment by stuartbreckenridge** [comment]
@brentsimmons Is NNW impacted when a feed is utf-8 encoded but the server is reporting US-ASCII? I can’t reproduced the above issue, but that’s the only thing I can see that is _potentially_ wrong.

**Comment by Wevah** [comment]
FWIW, I can't reproduce it either on iOS or macOS.

**Comment by denisa** [comment]
I’ve the same behavior on the mac (OS: 13.1 (22C65)) version (NNW: Version 6.1 (6106))…

Is there any information I could add to this to help?

**Comment by denisa** [comment]
@brentsimmons Getting these through feedly

**Comment by denisa** [comment]
I added a iCloud syncing account to NNW, moved the blog’s RSS feed to it and can now see it properly.

So, feedly is corrupting something…

My use of NNW pre-dates iCloud syncing (by far!) and it never seemed necessary to switch.

I guess we can close this now.
