### ISSUE TITLE
How do I cancel my NetNewsWire subscription?

### ISSUE THREAD

**Issue by nudefireninja** [Ranchero-Software/NetNewsWire#3803]
Don't bill me, Brent Simmons!

`https://justuseapp.com/cancel/1480640210/netnewswire-rss-reader`

We're entering a new age of AI-generated spam/fraud.

Anyway, I was just googling how to set NNW as the default reader. Any help with that?

**Comment by vincode-io** [comment]
This is the only way I know to change how. I don't know if it works in macOS 12.

Closing since this is a question, not an issue.

**Comment by brentsimmons** [comment]
Ideally we’d take our old code for setting the default RSS reader and make that into a separate mini-app that just does that one thing. It’s not easy to find time, though, given everything else on our plate.
