### ISSUE TITLE
When I delete a source or folder it deletes the folder or source below it instead.

### ISSUE THREAD

**Issue by albas99** [Ranchero-Software/NetNewsWire#3812]
I was trying to delete a couple of folders but I noticed it was deleting the folders below it instead of the actual folder I wanted to delete. Furthermore the folder itself is not being deleted.

**Comment by brentsimmons** [comment]
Mac or iOS? Does the problem persist if you quit and restart the app? (Force-quitting, if on iOS.)

**Comment by albas99** [comment]
Looks like the issue was from my connection with InoReader. I haven't used both apps in a while so it seems like the connection was lost. Now that I've disconnected Inoreader, I think the issue shouldn't persist anymore.

**Comment by vincode-io** [comment]
I don't know what happened, but it looks like you resolved it. If that isn't the case, let me know and give us some more information. I'll reopen the issue then.

**Comment by albas99** [comment]
Sure.
