### ISSUE TITLE
Bug: Release Notes link in iOS app leads to 404

### ISSUE THREAD

**Issue by tedmiston** [Ranchero-Software/NetNewsWire#3814]
Currently clicking "Release Notes" in the latest release of the app points to here:

https://github.com/Ranchero-Software/NetNewsWire/releases/tag/ios-6.1

However, that page shows a 404.

When I looked into the releases manually, I noticed the case sensitivity difference (`ios` vs `iOS`) and it appears that release URLs *are* case sensitive, hence the 404.

https://github.com/Ranchero-Software/NetNewsWire/releases/tag/iOS-6.1

I haven't tried replicating this behavior in the macOS app, so it may have a similar issue.

**Comment by stuartbreckenridge** [comment]
We are dropping direct links to release notes in future versions.

**Comment by urda** [comment]
This issue has resurfaced or still exists by the way.

macOS points to https://github.com/Ranchero-Software/NetNewsWire/releases/tag/mac-6.1.2 which does not 404

iOS points to https://github.com/Ranchero-Software/NetNewsWire/releases/tag/ios-6.1.2 which **Does 404**
