### ISSUE TITLE
Multiple authors appear in wrong (random?) order

### ISSUE THREAD

**Issue by hbhargava7** [Ranchero-Software/NetNewsWire#3816]
I use NetNewsWire to read Pubmed RSS feeds of scientific papers. Papers typically have multiple authors, which are listed in the feed using `<dc:creator>` tags. The order of authorship is important (it reflects how much each author contributed). For some reason, NNW displays authors in an apparently random order:

The RSS XML for the entry screenshotted below has the authors in the correct order, but they appear in what appears to be arbitrary order in the entry (the issue is present on the latest versions of both iOS and macOS clients, but interestingly iOS and macOS show different (wrong) orders.

```xml
<dc:creator>Greg M Allen</dc:creator>
<dc:creator>Nicholas W Frankel</dc:creator>
<dc:creator>Nishith R Reddy</dc:creator>
<dc:creator>Hersh K Bhargava</dc:creator>
<dc:creator>Maia A Yoshida</dc:creator>
<dc:creator>Sierra R Stark</dc:creator>
<dc:creator>Megan Purl</dc:creator>
<dc:creator>Jungmin Lee</dc:creator>
<dc:creator>Jacqueline L Yee</dc:creator>
<dc:creator>Wei Yu</dc:creator>
<dc:creator>Aileen W Li</dc:creator>
<dc:creator>K Christopher Garcia</dc:creator>
<dc:creator>Hana El-Samad</dc:creator>
<dc:creator>Kole T Roybal</dc:creator>
<dc:creator>Matthew H Spitzer</dc:creator>
<dc:creator>Wendell A Lim</dc:creator>

```

<img width="680" alt="Screenshot 2023-01-18 at 4 38 15 PM" src="https://user-images.githubusercontent.com/1378894/213328532-441660ad-21a1-440f-a79c-1bafce4f5268.png">
<img width="405" alt="Screenshot 2023-01-18 at 4 38 06 PM" src="https://user-images.githubusercontent.com/1378894/213328534-2e74d839-3e41-435d-9c3c-7ebddddb5aa6.png">

For reference, here is a complete example RSS item
```xml
<item>
      <title>Synthetic cytokine circuits that drive T cells into immune-excluded tumors</title>
      <link>https://pubmed.ncbi.nlm.nih.gov/36520915/?utm_source=Chrome&amp;utm_medium=rss&amp;utm_campaign=pubmed-2&amp;utm_content=1pAhYGWnaLEewUEs1xIZZGXst5EwFQBUJFQSXblDm4iRvKbEvW&amp;fc=20230116143442&amp;ff=20230118192802&amp;v=2.17.9.post6+86293ac</link>

      <description>Chimeric antigen receptor (CAR) T cells are ineffective against solid tumors with immunosuppressive microenvironments...</description>

      <content:encoded><![CDATA[<div><p style="color: #4aa564;"><b>Science</b>. 2022 Dec 16;378(6625):eaba1624. doi: 10.1126/science.aba1624. Epub 2022 Dec 16.</p><p><b>ABSTRACT</b></p><p xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:mml="http://www.w3.org/1998/Math/MathML" xmlns:p1="http://pubmed.gov/pub-one">Chimeric antigen receptor (CAR) T cells are ineffective against solid tumors with immunosuppressive microenvironments.</p><p style="color: lightgray">PMID:<a href="https://pubmed.ncbi.nlm.nih.gov/36520915/?utm_source=Chrome&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1pAhYGWnaLEewUEs1xIZZGXst5EwFQBUJFQSXblDm4iRvKbEvW&fc=20230116143442&ff=20230118192802&v=2.17.9.post6+86293ac">36520915</a> | DOI:<a href=https://doi.org/10.1126/science.aba1624>10.1126/science.aba1624</a></p></div>]]></content:encoded>

      <guid isPermaLink="false">pubmed:36520915</guid>
      <pubDate>Thu, 15 Dec 2022 06:00:00 -0500</pubDate>
<dc:creator>Greg M Allen</dc:creator>
<dc:creator>Nicholas W Frankel</dc:creator>
<dc:creator>Nishith R Reddy</dc:creator>
<dc:creator>Hersh K Bhargava</dc:creator>
<dc:creator>Maia A Yoshida</dc:creator>
<dc:creator>Sierra R Stark</dc:creator>
<dc:creator>Megan Purl</dc:creator>
<dc:creator>Jungmin Lee</dc:creator>
<dc:creator>Jacqueline L Yee</dc:creator>
<dc:creator>Wei Yu</dc:creator>
<dc:creator>Aileen W Li</dc:creator>
<dc:creator>K Christopher Garcia</dc:creator>
<dc:creator>Hana El-Samad</dc:creator>
<dc:creator>Kole T Roybal</dc:creator>
<dc:creator>Matthew H Spitzer</dc:creator>
<dc:creator>Wendell A Lim</dc:creator>
      <dc:date>2022-12-15</dc:date>
      <dc:source>Science (New York, N.Y.)</dc:source>
      <dc:title>Synthetic cytokine circuits that drive T cells into immune-excluded tumors</dc:title>
      <dc:identifier>pmid:36520915</dc:identifier>
      <dc:identifier>doi:10.1126/science.aba1624</dc:identifier>
    </item>
```

**Comment by vincode-io** [comment]
As you discussed with @brentsimmons, it is impractical for us to implement this at this point in time.

**Comment by vwkd** [comment]
Encountering the same issue with JSON 1.1 feeds with identical `authors` array on different feed items. For different feed items the identical authors are shown in a random order.

@vincode-io I don't think randomness is good UI. I believe the order of the authors in the feed should be respected (first first, last last).

**Comment by teddybradford** [comment]
> Encountering the same issue with JSON 1.1 feeds with identical `authors` array on different feed items. For different feed items the identical authors are shown in a random order.
> 
> [@vincode-io](https://github.com/vincode-io) I don't think randomness is good UI. I believe the order of the authors in the feed should be respected (first first, last last).

I also ran into this. I thought it was a UI bug when I noticed it happening. @vincode-io Can you share the context for why this issue was closed and/or could it be reopened at some point?
