### ISSUE TITLE
Full article not displayed & Reader View error without loading

### ISSUE THREAD

**Issue by neilmorton** [Ranchero-Software/NetNewsWire#3819]
Trying to access articles via https://www.moneysavingexpert.com/news/feeds/news.rss, standard view only gives short snippet. Tap Reader View, and icon swaps to `!` and the article isn't shown in Reader view.
Accessing via other apps shows same initial view, but Reader View shows article.
Can ReaderView be updated to work with sites like this?

**Comment by EdsonBittencourt** [comment]
I'm with the same issue but in another RSS. When in normal mode just a snippet and in reader mode the images aren't loaded. Maybe the same bug?

**Comment by neilmorton** [comment]
Do you see the reader view icon switch to show an exclamation mark ! inside? For me, tapping the reader view doesn’t change the content display at all, and simply switches the reader view icon to having an exclamation mark inside?

Would love to use this app (speed, cleanliness etc)., but having used Reeder for a long time and being used to simply being able to tap Reader View to have articles that only show in part load fully, it is rather annoying!

**Comment by tyrochemist** [comment]
I am encountering the same issue. Quitting and restarting the apps seems to work temporarily. After a few selections of articles, however, the view pane just shows "Loading..." and the button has changed to an exclamation point.

**Comment by neilmorton** [comment]
Unfortunately I don't get the temporary working bit with a restart.
I really hope that someone is able to shed some light on this and resolve.

**Comment by brentsimmons** [comment]
Here’s what I found — tested using my Mac.

I subscribed to https://www.moneysavingexpert.com/news/feeds/news.rss via Feedbin. (Not sure if the account type matters, but the site wouldn’t let me subscribe directly from NetNewsWire.)

I selected an article from that feed. I clicked the Reader View button in the toolbar. It gave me an exclamation mark.

Then I selected another feed and an article in that other feed. Tried Reader View — got the exclamation mark. Tried it multiple times with multiple feeds and multiple articles. Always the exclamation mark.

Initial guess: somehow that moneysavingexpert feed gets our Reader View into a weird state where it won’t work for anything. (There are probably other feeds that trigger this same bug.)

**Comment by LitoFrame** [comment]
I have the same issue. For me none of my feeds loading with reader view or all feeds are good. Many times I found little loading issues, which could be some seconds delay or not load the feed then a couple of seconds later it is working fine. These are not a big issues and the problem could be something else.
Yesterday and today I could't load any feed with reader view for a couple of hours, that was annoying.

**Comment by neilmorton** [comment]
Thank you @brentsimmons . Appreciate you looking at this and adding it to the roadmap.

**Comment by brentsimmons** [comment]
I can’t reproduce this issue currently. I’ll close it — but it can be reopened if this comes up again (possibly with a different feed).

**Comment by neilmorton** [comment]
Hi @brentsimmons, whilst the issue of the exclamation mark appearing no longer occurs, I am still experiencing the same core issue in that the article content does not load. The only way I can read the articles is to go to the web page.

I have tried deleting and re-adding the feed as detailed in the issue, and also by simply pasting the home page url, to see if creating from scratch added a different feed that works, but no luck.

Can this be re-opened and investigated further?
