### ISSUE TITLE
Twitter feeds not being updated

### ISSUE THREAD

**Issue by abodnar** [Ranchero-Software/NetNewsWire#3830]
I recently setup the Twitter extension in NetNewsWire and have been noticing that it's not getting new tweets from accounts I've setup as a feed. Feeds from FreshRSS work fine, but obviously a little simpler

Now what's weird is that I've done the same on another computer and it does get the new tweets when feeds are refreshed.

Both computers are running macOS Monterey. The feeds are stored in iCloud. The non-working computer is an M1 Pro, the other is an Intel. Not sure why that would matter, but feel it's good to give all the info.

Thoughts?

**Comment by brentsimmons** [comment]
Have you set up the Twitter account in NetNewsWire Preferences on both computers?

**Comment by abodnar** [comment]
Yes

<img width="508" alt="Screen Shot 2023-01-24 at 10 51 15 AM" src="https://user-images.githubusercontent.com/1891200/214356197-8071095f-764f-44f1-aa10-0d9ae1529060.png">

**Comment by brentsimmons** [comment]
Have you tried quitting and restarting NetNewsWire on the non-working machine? Or rebooting that machine? Or removing and re-adding your Twitter account from NetNewsWire?

Are the machines on different networks — could the non-working one have some kind of firewall or blocker running that might block Twitter?

**Comment by sashkab** [comment]
I'm experiencing same issue. I know there are new tweets, but NNW won't show them. Is NNW hitting some kind of limit on API token which causing it not to display twitter posts? Is there a way to see some kind of logging during the update process to attempt to troubleshoot this?

**Comment by nijynot** [comment]
I'm experiencing similar issues. Opted for an alternative publicly hosted solution instead, for the time being.

**Comment by sashkab** [comment]
> Opted for an alternative publicly hosted solution instead,

What's that @nijynot?

**Comment by abodnar** [comment]
> Have you tried quitting and restarting NetNewsWire on the non-working machine? Or rebooting that machine? Or removing and re-adding your Twitter account from NetNewsWire?
> 
> Are the machines on different networks — could the non-working one have some kind of firewall or blocker running that might block Twitter?

I did restart the app and nothing changed. Haven't had a chance to reboot yet. Removed and re-added to NNW and no change. Both machines are on same network. Non working one is a work machine and is on VPN, so maybe that. But never had any issues with Tweetbot.

@brentsimmons Yeah, I definitely see that it is likely the issue. 

Just to provide some more info, I am only doing username feeds. None of the other types that available. I'm going to run the two side by side tomorrow and see if I see the behavior happen live. Cause right now, I only notice that when I sit back down at my personal MBP that I see all the tweets that I missed during the day while working.

**Comment by antwake** [comment]
looks like twitter feeds stopped working on Jan 16? (also https://netnewswire.com's footer's year is still 2022 ;) )

**Comment by brentsimmons** [comment]
Twitter feeds are still working for me. It may be that they’ve been extremely unreliable since around that date, though.

**Comment by brentsimmons** [comment]
Closing this because Twitter integration is going away with the end of the free use of the Twitter API.
