### ISSUE TITLE
Twitter (and future Mastodon) extension: Dynamic folders for each account in timeline

### ISSUE THREAD

**Issue by tylerbenson** [Ranchero-Software/NetNewsWire#3833]
When using the twitter extension, all messages are grouped into `Twitter Timeline`. Sometimes a particular Twitter account can get noisy.  When using Tweetbot, I would handle this by muting that user temporarily which would clear out the current view from all the noise.  I think it would be great to accomplish something similar by having a dynamic view for each account in the timeline. From there, I could select it to filter to just that account's tweets (or retweets) and I can "mark all as read" to clear out the noise. It would also make it easier to view a particular thread from an account.

Thanks!

**Comment by brentsimmons** [comment]
Since Twitter integration will stop working soon — as soon as Twitter ends free Twitter API access — I’m closing this.
