### ISSUE TITLE
Duplicated feeds on transvanilla.hu

### ISSUE THREAD

**Issue by 0xallie** [Ranchero-Software/NetNewsWire#3835]
Device: iPhone 13

OS: iOS 16.3

NetNewsWire version: 6.1 (Build 6110)

Feed URL (happens with both):
* https://transvanilla.hu/?format=feed&type=atom
* https://transvanilla.hu/?format=feed&type=rss

Subscription type: iCloud

---

Using either the Atom or RSS feed from transvanilla.hu results in most posts eventually becoming duplicated. They do not appear to be duplicated in the source.

![Screenshot of duplicated feeds](https://user-images.githubusercontent.com/482367/215078092-dce3ed85-24e8-40f2-bbe2-a87615272207.png)

**Comment by stuartbreckenridge** [comment]
Looking at the feed it seems like the url is being used for GUID. Can you copy the article URL for both entries of an article and paste them into notes and see if they are the same?

**Comment by 0xallie** [comment]
It seems like they're different:
* https://transvanilla.hu/tobb-evnyi-pereskedes-utan-kaphatjak-meg-helyes-irataikat-a-transvanilla-ugyfelei
* https://mail.transvanilla.hu/tobb-evnyi-pereskedes-utan-kaphatjak-meg-helyes-irataikat-a-transvanilla-ugyfelei

**Comment by stuartbreckenridge** [comment]
This is a problem with the feed. When the GUID changes, NetNewsWire sees it as a new article.
