### ISSUE TITLE
Enhancement request - add unread badge on dock icon for macos

### ISSUE THREAD

**Issue by robot1125** [Ranchero-Software/NetNewsWire#3838]
It would be nice to know if new articles are available just by glancing at the dock icon.  If it can already do that, I'd like to find out where to enable it!

**Comment by brentsimmons** [comment]
In System Settings, make sure `Badge application icon` is turned on for NetNewsWire.

<img width="761" alt="Screenshot 2023-02-03 at 10 19 04 PM" src="https://user-images.githubusercontent.com/1297121/216752449-26cd58b8-48d0-4ac8-b0a1-5b86bedc2141.png">

**Comment by robot1125** [comment]
Thank you!

￼

(I feel dumb)

-Shane
