### ISSUE TITLE
Problems with syncing iCloud feeds that are not in folders on iPad

### ISSUE THREAD

**Issue by flaksp** [Ranchero-Software/NetNewsWire#3839]
This is how my feeds look on macOS:

<img width="730" alt="Screenshot 2023-02-01 at 00 11 16" src="https://user-images.githubusercontent.com/12474739/215884203-0c5ae95e-388a-476c-9842-505e24e71d1c.png">

And this is my new iPad:

![IMG_A0AE0C6A8E2C-1](https://user-images.githubusercontent.com/12474739/215885775-71d33c2c-3b7f-4e96-9b46-5daefbbf47bc.jpeg)

It missing all feeds that are not in folders.

I tried:

- Pressing the "Remove Account" button on iCloud from NewNewsWire settings;
- Switching the "Active" toggle;
- Disabling and then enabling iCloud sync for NewNewsWire app in the system settings.

And nothing helps.

I had an old iPad with NewNewsWire installed and my feeds were there until I tried to press the "Remove Account" button just for investigation purposes. So I have two iPads with broken sync now 😔

**Comment by brentsimmons** [comment]
What happens if you create a folder just for those feeds, and move those feeds into that folder? Do they appear iPad (a little while later, after syncing)?

**Comment by brentsimmons** [comment]
If they do, what happens if you then move those folders back to the top level, and delete the (now empty) folder you created?

**Comment by flaksp** [comment]
I created a folder, moved all feeds, and they appeared in the folder after sync. Then I moved them back to the root, deleted the folder, triggered sync and they disappeared (as in my first message here).

**Comment by brentsimmons** [comment]
If you go into NetNewsWire settings on your iPad (gear button at bottom of Feeds screen), and scroll to the bottom — what version of NetNewsWire are you running?

**Comment by flaksp** [comment]
It's 6.1 (build 6110).

**Comment by vincode-io** [comment]
@flaksp The iCloud account in NNW on your Mac might be confused. Let's try this. Put your Mac feeds how you want them and then export the iCloud account as an OPML file.

Then delete the Mac's iCloud account and add it again. I suspect you might be missing your root folder feeds, but you should be back in sync with your iPads. If this is the case, you will need to add the root feeds again.

Let us know what happens so that we can give you further help if you need it.

**Comment by flaksp** [comment]
Also, I noticed strange thing: if I create feeds (in the root) on iPads, they will sync only between my iPads (and not on an iPhone and Mac!). 

<details>
  <summary>Screenshots</summary>
  
  <img width="513" alt="Screenshot 2023-02-04 at 12 20 23" src="https://user-images.githubusercontent.com/12474739/216759493-21b2485a-f085-4e59-843e-6457c6652350.png">
  
  ![IMG_FB022CA411DF-1](https://user-images.githubusercontent.com/12474739/216759496-d651527a-d8a1-4669-ab91-ff57e34c79c6.jpeg)
  
  ![IMG_4C99528C6E42-1](https://user-images.githubusercontent.com/12474739/216759502-bbef489b-372c-4b08-9051-f310ed5fd5c9.jpeg)
</details>

iOS and macOS apps sync correctly, but they missing stuff created on iPads. And iPads are missing things created on iPhone and Mac.

**Comment by flaksp** [comment]
I tried deleting all iCloud data for the app, then re-added all feeds and problem gone.

<img width="615" alt="Screenshot 2023-02-04 at 12 38 48" src="https://user-images.githubusercontent.com/12474739/216760238-5e58d3c6-e6f4-48ba-9515-cf35f7f5b236.png">


Thank you for help!

**Comment by vincode-io** [comment]
I'm not sure how everything got out of whack, but I'm glad that you got the issue resolved.

**Comment by I7T5** [comment]
I have the same problem, and it's solved with the same solution.
