### ISSUE TITLE
Remove Twitter Extension

### ISSUE THREAD

**Issue by stuartbreckenridge** [Ranchero-Software/NetNewsWire#3841]
`@TwitterDev`: 

https://twitter.com/TwitterDev/status/1621026986784337922?s=20&t=PH8grgFcRU8-zD1LRernug

The API will be restricted from 9th Febrthe 9th February. 

- Do we do anything destructive with the Twitter feeds a user has subscribed to or just leave them as is? 
- Do we any any sort of alert in the app to update users (only displayed if they have Twitter feeds)?

**Comment by stuartbreckenridge** [comment]
If that happens to be the case, you're also asking NetNewsWire developers to pay for API access so that we can ensure NetNewsWire continues to work.

**Comment by michaeljtsai** [comment]
I’m just saying we don’t know how this is going to work yet. If the API restriction is actually about bots, as claimed, maybe read-only access will remain free. If there’s no free tier, maybe interested users and developers would help test or chip in. How does testing work for BazQux, which is not free?

**Comment by vincode-io** [comment]
@michaeljtsai BazQux was super cool and gave me a free account to test with. I usually just keep creating and deleting accounts to use the free trial for other services like Feedbin.

We have to take the Twitter Dev account at their word and do the best we can with it. Just having our Twitter support stop working or throwing errors would be a bad user experience. I don’t see that we have any choice but to take this path.

One thing you could do is not upgrade until after the deadline has passed. If the bots get shutdown and NNW keeps working, you could just not upgrade. If it keeps working, that doesn’t change anything for us. We’re tired of Twitter’s BS. But, if you wanted future enhancements and Twitter support, you could do your own fork and pull in upstream changes for personal use. I’d be happy to walk you through how to get the API keys from Twitter and integrate them securely into you NNW fork.

**Comment by michaeljtsai** [comment]
@vincode-io Thanks. What happens to iCloud data with a fork? If I use my current database, will it get confused because the existing record IDs are not valid in the new container? Or just re-upload everything as new?

**Comment by vincode-io** [comment]
@michaeljtsa Unfortunately there isn't a way to migrate to a new CloudKit container. You would have to start all over by importing you OPML file.

**Comment by andyzickler** [comment]
@michaeljtsai It is not a perfect solution, but https://github.com/zedeus/nitter scrapes twitter and provides rss feeds of accounts. For example you can subscribe to https://nitter.nl/NetNewsWire/rss You can also run your own instance if desired.

**Comment by michaeljtsai** [comment]
@andyzickler Thanks. I’ve actually been using that for the last few days, and it seems to work well. The downsides are that it doesn’t show replies or private accounts.

**Comment by brentsimmons** [comment]
Closing this because I think it’s been done. :)
