### ISSUE TITLE
Remove Twitter integration

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#3842]
Leave Twitter feeds intact, so that people can retain their saved articles. People should still be able to read what they’ve downloaded.

Delete all Twitter-related code not needed for the above. (Hopefully none of it is needed for the above! But, if so, then keep that code.)

**Comment by vincode-io** [comment]
I deleted everything Twitter related in both `mac-release` and `ios-release`.
