### ISSUE TITLE
Feature: Resyndication?

### ISSUE THREAD

**Issue by joescharf** [Ranchero-Software/NetNewsWire#3845]
Hi,

Excited to see a resurgence of RSS and open protocols now that Twitter is dying. I did some searching (albeit, somewhat abbreviated) around the web and in the issues here. Wondering if there's a reader out there (or a missing feature) that would support RSS resyndication. 

Basically I have a bunch of feeds that I consume and would love to be able to drag/drop articles I like into one or more RSS feeds that I publish / curate that others could subsequently consume. Basically a matter of managing one or more  xml file(s) and syncing it to S3 or some publicly accessible object storage. Sure I can manually cut / paste / upload, or use a separate feed creation tool but seems it would be a straightforward addition to provide some rudimentary publishing support and unify both functionalities. 

_(I'm a developer so I get it - how hard can it be? Yes I know I can contribute and I might just take a look into this, but wanted to put this out there first and see if there's any thoughts / guidance. feel free to delete / ignore if I'm repeating a FAQ)_

**Comment by brentsimmons** [comment]
We wouldn’t add this to NetNewsWire — it’s a huge undertaking, it would cost money, and it would mean us spending a bunch of time on customer support.

However, we’d be happy to integrate with other services — local apps, web apps — that do this kind of thing. We have a sharing menu, and we’d be happy to work with anyone who wants to do the publishing side.
