### ISSUE TITLE
Swipe right to go Back

### ISSUE THREAD

**Issue by reppep** [Ranchero-Software/NetNewsWire#3846]
When I'm reading an article, swiping the article to the right of my iPhone screen should go Back up in the hierarchy, like the upper-left < Button does. In a feed, it should do the same. I didn't find an open issue for this -- apologies if this is a dupe.

**Comment by vincode-io** [comment]
NNW does do this. Are not starting close enough to the edge of the screen?

**Comment by reppep** [comment]
Yep! I was used to Reeder behavior where I did it from mid-screen. I tried and you're right. I'll switch my behavior, thanks.
