### ISSUE TITLE
M1 iPad Pro not working with icloud

### ISSUE THREAD

**Issue by akagumo** [Ranchero-Software/NetNewsWire#3848]
I had two iPads, an iPad air2 and iPad 6, but worked fine for both to sync with iCloud.
I got a new m1 iPad Pro to replace iPad Air 2.
but M1 iPad will not sync with iCloud for NNW.
just shows stuck what looks like 5% forever.  I deactivated iCloud, deleted app and re-added, reactivate icloud.
still the same, stuck.
is there a bug for M1 and cloud sync in NNW?

**Comment by vincode-io** [comment]
It is just taking longer to sync than you would expect. Please read this document to get you through setting up your new iPad.

https://netnewswire.com/help/iCloud

If you are still not able to get it to sync, let us know and we can reopen this issue.
