### ISSUE TITLE
Error in iOS app when loading any theme

### ISSUE THREAD

**Issue by uanjoze** [Ranchero-Software/NetNewsWire#3849]
When refreshing feeds, a pop up appears with an error message. It doesn’t seem to refresh the feeds either because of the error.

> This theme cannot be used because of data corruption in the Info.plist. Invalid value around line 1, column 0..

![E5275E97-376F-4BAC-8645-9E52A9BAAC77](https://user-images.githubusercontent.com/632451/216772577-619ec7d0-2eff-4893-b283-ee60db1649f2.png)

It’s the build 6110

**Comment by stuartbreckenridge** [comment]
What themes do you have installed?

**Comment by vincode-io** [comment]
More specifically, what was the last theme you installed before beginning to get this error?

**Comment by uanjoze** [comment]
I’ve never installed one or even changed it, so I assume the ones that come by default. I’ll add the list here just in case:
- Default
- Appanoose
- Hyperlegible
- NewsFax
- Promenade
- Sepia

However, the issue isn’t happening anymore! So it might have been an issue with the connection to Feedly - it’s strange tho that the error mentioned a problem with the theme (instead of with the feed)

**Comment by stuartbreckenridge** [comment]
Feedly were doing maintenance today. Maybe that caused it, but it still suggests there's an incorrect error being presented.

**Comment by brentsimmons** [comment]
Didn't this get fixed?

**Comment by Vynce** [comment]
I’m seeing exactly this error message in NetNewsWire 6.1.4 (Build 6120) on iOS, presumably because Feedly is down for maintenance: https://status.feedly.com/incident/227900
![image](https://github.com/Ranchero-Software/NetNewsWire/assets/377567/c1e8d82c-44a6-42ac-bb89-4c85a47521a1)

**Comment by jimtut** [comment]
Same as Vynce.  So… how was this “closed” in the past?  Because the Feedly maintenance window ended?  Or a code change? I’m guessing former. This should be reopened until a code change is added to handle this more gracefully.

**Comment by brentsimmons** [comment]
Reopening because this needs additional verification.

**Comment by brentsimmons** [comment]
Fixed in 7.1.3.
