### ISSUE TITLE
Feeds from siftrss cannot be added to Feedly account

### ISSUE THREAD

**Issue by msridhar** [Ranchero-Software/NetNewsWire#3853]
I'm running NetNewsWire 6.1 on Mac, and I'm unable to add feeds from [siftrss](https://siftrss.com).  E.g., I created this filtered feed:

https://siftrss.com/f/KDBdMjrZ8k

It seems to be valid:

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fsiftrss.com%2Ff%2FKDBdMjrZ8k

But when I try to add it to NetNewsWire, I get an error, "Can’t add a feed because no feed was found."  If I can provide any other information, please let me know.

**Comment by brentsimmons** [comment]
I just tried it with an On My Mac account and it worked fine. What kind of account are you trying to add it to?

**Comment by msridhar** [comment]
Ah, it fails when trying to add it to a Feedly account.  I can confirm that it works fine when adding to my iCloud via NetNewsWire.

I can also add the feed via Feedly.com successfully and it then shows up in NetNewsWire, so that's a workaround for now.  Thanks for taking a look so quickly!

**Comment by vincode-io** [comment]
I just tested this and it works now. It must have been a temporary Feedly issue.
