### ISSUE TITLE
Images not shown correctly

### ISSUE THREAD

**Issue by himazawa** [Ranchero-Software/NetNewsWire#3864]
Hi, 

on this feed: https://appsec.space/index.xml images are not displayed correctly, and they load indefinitely. The website uses github pages.

**Comment by danielpunkass** [comment]
It seems like a problem with the feed, not with NetNewsWire. Does this feed load correctly in any news reader? I note that the feed content doesn't include any IMG tags.

**Comment by brentsimmons** [comment]
Daniel’s right — there are no img tags in the feed.
