### ISSUE TITLE
Sidebar state resets on launch

### ISSUE THREAD

**Issue by dylanseeger** [Ranchero-Software/NetNewsWire#3866]
NetNewsWire should remember the user's sidebar view preferences after quitting and launching the application.

**Comment by brentsimmons** [comment]
What version of NetNewsWire and what version of macOS are you running? I ask because, for me, it does actually save and restore my sidebar view preference.

Could it be that you have the sidebar all the way hidden?

**Comment by brentsimmons** [comment]
Duplicate of https://github.com/Ranchero-Software/NetNewsWire/issues/1944
