### ISSUE TITLE
Is there anyway I can get the rendered page？

### ISSUE THREAD

**Issue by bfcs** [Ranchero-Software/NetNewsWire#3872]

**Comment by bfcs** [comment]
Hi, 
Thanks for great work, I am new to NetNewsWire, I wonder if I could export the rendered pages, pdf or html? when I share a article, it actually uses the url of target website.

**Comment by brentsimmons** [comment]
Maybe via AppleScript? I haven’t written an AppleScript script in many years, and I don’t have anything handy. If I come up with something I’ll add a comment.
