### ISSUE TITLE
Tabbing to the "Folder" dropdown when adding a feed does not work

### ISSUE THREAD

**Issue by niclake** [Ranchero-Software/NetNewsWire#3879]
When I'm in the "New Web Feed" dialog, it drops me in on the URL. I can then tab to the Name field, but hitting tab again will just jump back to the URL. I'd love to be able to tab down to the Folder dropdown & choose the destination that way.

**Comment by brentsimmons** [comment]
To make this work, you’ll have to turn on Keyboard navigation in System Settings. In macOS 13, the screen looks like this:

<img width="483" alt="Screenshot 2023-02-23 at 9 45 15 PM" src="https://user-images.githubusercontent.com/1297121/221101880-146f0c9f-d538-4981-a618-e7e3bdb072e2.png">
