### ISSUE TITLE
Apparently valid RSS feed isn't accepted by NNW

### ISSUE THREAD

**Issue by chrisbulow** [Ranchero-Software/NetNewsWire#3881]
The URL: https://thepsychogastronomy.cafe/ or https://thepsychogastronomy.cafe/feed/ (& various combinations thereof) fail to get added in NNW with error "feed not found". 

All my other iOS and Mac OS readers pick it ups without issue. 

The URL is validated OK at W3C it appears.

I'm obviously missing something obvious, so grateful for any suggestions.

Thanks, Chris

<img width="273" alt="NNW" src="https://user-images.githubusercontent.com/7009135/221149803-73f90def-bb8a-423f-ba8a-fddc76ac67ac.png">

<img width="1385" alt="NNW2" src="https://user-images.githubusercontent.com/7009135/221150234-2ad44331-9276-43f0-93f0-70f0a1c319a8.png">

**Comment by brentsimmons** [comment]
I just tried it with an On My Mac account and it worked perfectly. Does it still not work for you? If so, what kind of account are you using?

**Comment by chrisbulow** [comment]
Thanks Brent.Still isn’t accepted. Not 100% sure what the account questions means? I simply tried to add it to my existing list of RSS feeds in the main panel?RegardsChris Bulow P: +44 (0) ***@***.*** 27 Feb 2023, at 05:53, Brent Simmons ***@***.***> wrote:﻿
I just tried it with an On My Mac account and it worked perfectly. Does it still not work for you? If so, what kind of account are you using?

**Comment by chrisbulow** [comment]
Just a quick screen shot after trying to add On My iPadApologies; choosing On my IPad get this feed accepted. Feedly still doesn’t.I’ve never been 100% sure what the difference is, so if I just need to move the feeds from Feedly to my iPad to overcome this, that shouldn’t take toto long and then I can delete the Feedly group?RegardsChris Bulow P: +44 (0) ***@***.*** 27 Feb 2023, at 06:16, Chris Bulow ***@***.***> wrote:﻿Thanks Brent.Still isn’t accepted. Not 100% sure what the account questions means? I simply tried to add it to my existing list of RSS feeds in the main panel?RegardsChris Bulow P: +44 (0) ***@***.*** 27 Feb 2023, at 05:53, Brent Simmons ***@***.***> wrote:﻿
I just tried it with an On My Mac account and it worked perfectly. Does it still not work for you? If so, what kind of account are you using?

**Comment by brentsimmons** [comment]
It sounds like you’re using Feedly to sync your feeds and articles across devices and computers. Cool.

When you add this feed to your Feedly account in NetNewsWire, NetNewsWire has to ask Feedly’s server to add the feed. Feedly’s server is responding, incorrectly, that it can’t find that feed.

However, I’ve found that you can go to the Feedly website and add the feed there. That’s what I recommend doing.

My guess is that there’s some bug in Feedly where very new feeds like this one don’t get added to the API-accessible search database quickly enough. But that’s just a guess. You could report the bug to Feedly, or just add the feed via the Feedly website and move on. :)

**Comment by chrisbulow** [comment]
Appreciate the speedy help Brett; as always, love the support and the software.RegardsChris Bulow P: +44 (0) ***@***.*** 27 Feb 2023, at 06:41, Brent Simmons ***@***.***> wrote:﻿
It sounds like you’re using Feedly to sync your feeds and articles across devices and computers. Cool.
When you add this feed to your Feedly account in NetNewsWire, NetNewsWire has to ask Feedly’s server to add the feed. Feedly’s server is responding, incorrectly, that it can’t find that feed.
However, I’ve found that you can go to the Feedly website and add the feed there. That’s what I recommend doing.
My guess is that there’s some bug in Feedly where very new feeds like this one don’t get added to the API-accessible search database quickly enough. But that’s just a guess. You could report the bug to Feedly, or just add the feed via the Feedly website and move on. :)
