### ISSUE TITLE
Feature Request: Sync Always-Use-Reader-Mode Per-Feed Setting

### ISSUE THREAD

**Issue by I7T5** [Ranchero-Software/NetNewsWire#3882]
I use NNW6 on my iPhone and MacBook, and sometimes iPad. All my feeds are in iCloud. The individual feed setting "Always Use Reader Mode," however, does not sync across devices, even though the feeds are synced across iCloud, and it's not that convenient as I mind myself marking "Always Use Reader Mode" twice or thrice for one single feed (and I have lots of feed). 

Could there be an option to sync those settings through iCloud too?

**Comment by brentsimmons** [comment]
I could see how it would be useful. No promises, of course, as to if or when it might happen, but we will consider it for a future release.
