### ISSUE TITLE
Cannot add valid feed to NNW, but can through Feedly

### ISSUE THREAD

**Issue by ZNielsen** [Ranchero-Software/NetNewsWire#3884]
Feed in question: https://www.zachn.me/feed.xml

I've seen a couple of similar issues on here, but the resolution on those don't quite match what I'm seeing
- I am able to `curl https://www.zachn.me/feed.xml` and get the full document
- The feed passes the validator from W3C
- This feed used to work in NNW. The existing entry I have in the app does not receive updates, and attempting to remove/add the feed again fails with "Feed not found - Can’t add a feed because no feed was found."

I was able to work around by adding the feed on Feedly — the feed is now accessible in Net News Wire after adding through the Feedly web UI. Indicates a parsing or validation issue perhaps?

**Comment by brentsimmons** [comment]
What kind of account were you trying to add it to in NetNewsWire? (Sounds like Feedly, but I’m not sure and want to be sure before attempting to debug this.)

**Comment by ZNielsen** [comment]
Correct, a Feedly account via the Add Item -> Add Web Feed (the + in the bottom right of the iOS app). 
Worth mentioning I was seeing the same error on iOS and Mac NNW.

**Comment by brentsimmons** [comment]
We had another report like this with Feedly. It appears to be a bug with Feedly’s API — for some feeds it’s reporting that it can’t find a feed that actually does exist and can be added via the website.

Closing this as it’s a Feedly bug. It would be nice to report it to them, but I can’t guarantee I’ll have the time.
