### ISSUE TITLE
Feature Request: add support for Reddit custom feeds

### ISSUE THREAD

**Issue by Thad-Supersperm** [Ranchero-Software/NetNewsWire#3890]
The ones you can create by aggregating subreddits in the multi-reddit

**Comment by 9p4** [comment]
You can already do this:

https://www.reddit.com/r/programming+funny/top.xml

**Comment by Thad-Supersperm** [comment]
It gives me an error: “Feed not found - Can’t add a feed because no feed was found”

**Comment by Thad-Supersperm** [comment]
I even tried your link, but doesn’t work.

BTW I’m on 6.1.1 (6111)

**Comment by 9p4** [comment]
https://user-images.githubusercontent.com/17993169/222543290-2f33098c-7f37-4455-81ef-7a674819afeb.MOV

**Comment by Thad-Supersperm** [comment]
I’m on Mac and it doesn’t work

**Comment by 9p4** [comment]
https://user-images.githubusercontent.com/17993169/222553694-28e8b45f-f53f-47c6-9f10-538618d7c383.mp4

**Comment by Thad-Supersperm** [comment]
Maybe it’s my Mac or I need to update the os, I’ll post here in the next days if I find a solution

**Comment by 9p4** [comment]
That was recorded on Catalina.

**Comment by Thad-Supersperm** [comment]
I was on Ventura 13.2 when I opened the issue because it didn’t work. Now I updated to 13.2.1 and the same problem persists. Maybe it will be revolved in the next NNW update.

**Comment by brentsimmons** [comment]
Figured out what’s happening. If you have a Reddit account in Preferences > Extensions, then our Reddit support tries to handle the feed and fails — it doesn’t get treated as a regular feed.

If you remove that Reddit account from NetNewsWire, then the feed works properly.

**Comment by vincode-io** [comment]
@brentsimmons Do you consider this the same thing as #3234 or do you want me to add another Reddit feed type?

**Comment by andreiglingeanu** [comment]
This also happens on my end and I don't see to have the Reddit extension enabled since I am on 6.1.4. But adding just a straight RSS feed from Reddit does not work:


https://github.com/Ranchero-Software/NetNewsWire/assets/2979628/78005eca-bedd-427f-a4b5-4776ae620fda

Am I doing anything wrong on my end?

**Comment by brentsimmons** [comment]
Is this still not working?

**Comment by andreiglingeanu** [comment]
@brentsimmons thanks for chiming in! Indeed this works well now (I'm on 6.1.5b). Do you know was the fix for it?

**Comment by brentsimmons** [comment]
I think it got fixed when we deleted the Reddit extension.

**Comment by andreiglingeanu** [comment]
That makes sense, thanks a lot.
