### ISSUE TITLE
Safari Extension Icon Disappears in macOS 13.2.1 and Reappears on Reinstall

### ISSUE THREAD

**Issue by I7T5** [Ranchero-Software/NetNewsWire#3891]
I've just updated the OS. NNW's Safari extension (Subscribe to feed) icon somehow disappeared. When I tried to disable and reenable the extension, the icon sort of "glitches" on the toolbar, and vanishes after a second or so. My AdGuard extension works just fine, so I don't think it's Safari's problem. 

I reinstalled NNW and it worked. Sharing this in case anyone finds it useful. 

System Version: macOS 13.2.1
Safari Version: 16.3
NNW Version: 6.1

**Comment by brentsimmons** [comment]
@danielpunkass Is this something we have any control over? I’m guessing not.

**Comment by danielpunkass** [comment]
@brentsimmons I don't think so but I am a little curious about the fact @I7T5 said it didn't affect other extensions. I feel like the Safari extension situation, while better than it used to be, is still a little prone to bugs. 

I think we could close this one, keep it as reference, and wait to see if we get more reports. Or try continue following up with the original poster.

**Comment by brentsimmons** [comment]
Sounds good. We’ll reopen this if we need to.

(My strong sense is that there’s literally nothing we could do about this, though.)
