### ISSUE TITLE
Request: move filter UIButton from top-right corner to botto-left (nav bar ->  bottom bar)

### ISSUE THREAD

**Issue by kevinm6** [Ranchero-Software/NetNewsWire#3897]
In NNW **Feeds page**, the filter button is on the top-right corner and it stays there when opening a smart feed or other folder.

My request/suggestion is to move the filter button in the bottom bar, replacing the **Settings** one: I think is more common filter unread articles than change some preference, that could justify to be easier to reach.  

![suggestion](https://user-images.githubusercontent.com/72861758/222987668-177e99d6-c1ad-4db2-b710-280140c84496.jpeg)  
---
Just like **Apple in Mail** ![mail app](https://user-images.githubusercontent.com/72861758/222987648-902045a8-e525-48ed-8e40-8ae0f0ae70da.jpeg)  

I think that **Settings** button could be move up, since it's less used.

**Comment by brentsimmons** [comment]
I myself use Settings more often than the filter button — but it’s quite possible, even likely, that my use is atypical.

I want to keep the filter button in the same location for both the Feeds screen and the timeline. This would mean moving the filter button to the bottom in the timeline — but what’s there currently in the timeline really needs to be: mark-all-read button, last-update message, next-unread button. Those two buttons are more important than the filter button. We could move the last-update message, but I don‘t see where. (Its location in the bottom toolbar matches Apple precedent, which is good.)

**Comment by kevinm6** [comment]
I get it.
I agree that it has to stay in the same position both in the Feed screen and timeline.
Maybe it's my usage but I almost never used the **next unread** button probably because I prefer choose which article open and it's very unlikely that it's the first unread on the list.

Thank you for the reply, by the way.

**Comment by brentsimmons** [comment]
People use NetNewsWire in _very_ different ways! Me, I use next-unread all the time. I also use the Unread smart feed a ton, while I think @vincode-io doesn’t use that smart feed at all.
