### ISSUE TITLE
Optimistic «mark all read»

### ISSUE THREAD

**Issue by tallakt** [Ranchero-Software/NetNewsWire#3916]
Hi. Thanks for a great piece of software. 

I have a suggested improvement regarding the «mark all read» feature. 

I use this a lot, and it would be nice if we could get rid of the «are you sure» dialog and rather just do it but show a ephemeral «undo» button

**Comment by kevinm6** [comment]
@tallakt you can already do it: from `Settings > Confirm Mark All as Read` as in the image below 
![image](https://user-images.githubusercontent.com/72861758/225118886-eb1ebc92-a71f-464c-96fa-11653f594460.jpeg)

To undo, you can use the `three finger tap` or the classic `shake to undo`.

**Comment by tallakt** [comment]
Wow. Thanks
