### ISSUE TITLE
Read articles remain visible even after refreshing

### ISSUE THREAD

**Issue by Drarok** [Ranchero-Software/NetNewsWire#3918]
I'd like a way to "clear" read items from the _All Unread_ section.

I've not been a user for long, but I find it weird that the articles I've read stay on-screen even after refreshing. Is the expected use case to switch from _All Unread_ to another "tab" and back again?

**Comment by brentsimmons** [comment]
On Mac or iOS?

**Comment by Drarok** [comment]
macOS, sorry.

**Comment by brentsimmons** [comment]
On Macs, you can do View > Clean Up Articles to remove the read articles from the All Unread feed. Keyboard shortcut is cmd-'

The reason we don’t do it automatically while you’re still in the All Unread feed is because you may not actually be ready for read items to disappear. There might be something you wanted to come back to, maybe something that you passed by quickly, for instance.

**Comment by Drarok** [comment]
Ah, and there's even a toolbar button already for it! The behaviour is still a little odd, the final selected-and-read article stays in the list until I de-select and hit the button again.

**Comment by brentsimmons** [comment]
Sure — because you’re still reading that article. Or there’s a good chance you’re reading it, and it would be jarring to have it removed before you’re finished.

**Comment by Drarok** [comment]
I guess this is a philosophical difference – as a completionist, I don't want to "clean up" until after I'm done reading _everything_, and at that point I want everything marked as read gone.

Would you entertain a preference for this behaviour? I'm willing to have a go myself, I don't expect it done for me. Been a while since I did macOS dev, but I'd gladly try.

**Comment by brentsimmons** [comment]
I hate to disappoint, but I don’t think I’d want a preference for this. We’re trying hard to keep the app from being overwhelmed with preferences, and this is a very small issue. (This is the first time it’s come up.)

**Comment by Drarok** [comment]
No problem at all, thanks for the replies all the same.
