### ISSUE TITLE
How do I manually restore NNW feed list / db from backup

### ISSUE THREAD

**Issue by sonn-gamm** [Ranchero-Software/NetNewsWire#3925]
Hi!

Apologies if it is the wrong place to ask for this. I forgot to manually export my Feed list before formatting my computer and installing everything from scratch. I do have though a Time Machine and Carbon Copy Cloner backup of the previous computer state. I tried to look around in the `~/Library` folder where the NNW data could be, but could not find my way around.

Is there any way to either restore the previous db or extract the list of my feed subscriptions from there?

Thanks!

**Comment by vincode-io** [comment]
Usually the best way to get help is to go into the [NetNewsWire Slack](http://netnewswire.slack.com).

The On My Mac account files are here:

`~/Library/Containers/com.ranchero.NetNewsWire-Evergreen/Data/Library/Application Support/NetNewsWire/Accounts/OnMyMac`

Replace everything in that folder with your backup and you should be good to go.
