### ISSUE TITLE
Adding Feedly account always launches Safari for sign-in, no matter which browser is set.

### ISSUE THREAD

**Issue by JosefEreq** [Ranchero-Software/NetNewsWire#3927]
When adding a Feedly account for feed sync on MacOS, the app launches Safari for signing in to Feedly, no matter which browser has been set under Settings -> General -> Browser.

**Comment by codywalker77** [comment]
When adding any account it does so through safari. No matter the default browser.

**Comment by ksurl** [comment]
it doesn't open any browser when trying to add on mine. tried changing default browser also

**Comment by brentsimmons** [comment]
This sign-on flow is using an Apple-provided API, which always uses Safari.

There is a known bug, though, where Safari might not appear. In that case, rebooting your Mac should fix it. (It’s an Apple bug, to be clear.)

**Comment by ksurl** [comment]
It worked after restarting the application
