### ISSUE TITLE
Space Bar to Page Down Broken by Ventura 13.3

### ISSUE THREAD

**Issue by AlexCharyna** [Ranchero-Software/NetNewsWire#3929]
I used to be able to hit space and it would page down an article.  At the end of the article it would go to the next unread one.
After today's 13.3 update, that seems have broken.

A short article which doesn't require paging down still goes to the next unread article, as does being at the bottom of a multipage article.  

But if it's long enough, space seems to have stopped working.

**Comment by ELBeavers** [comment]
I also started seeing this after the update. If it helps, I'm using an Apple Extended Keyboard II connected to my M1 MacBook Pro via iMate USB-A through a USB-C hub. For the record, it doesn't work using the spacebar on the laptop either.

**Comment by sashkab** [comment]
If current article is short, it works as expected, i.e advances to the next unread article. But if article is long, pressing space has no results.

**Comment by brentsimmons** [comment]
Yes — this was broken by macOS 13.3. We hope to find a workaround!

**Comment by geraint360** [comment]
Holding down the down arrow on a longer article will sound the warning beep although scrolling will continue

**Comment by brentsimmons** [comment]
This is fixed in macOS 13.4 beta.
