### ISSUE TITLE
iCloud articles will not sync/pull in new articles.

### ISSUE THREAD

**Issue by soopafly** [Ranchero-Software/NetNewsWire#3930]
On my iPhone since transferring from previous iPhone, articles that are in iCloud will not sync on my iPhone only. Those same articles will sync on all of my other iOS and macOS devices. I’ve attempted to remove the feeds and Re-add them manually. I’ve attempted to nuke everything on all my devices and force a sync but the sync on the iPhone hangs while other devices will pull in articles.

**Comment by brentsimmons** [comment]
This is a known issue — here’s a page about it: https://netnewswire.com/help/iCloud

**Comment by soopafly** [comment]
I ended up having to nuke the data in iCloud as I have already done the “Leave it open all night” thing. I had also previously deleted all feeds in iCloud and re-added them and the iPhone still would not sync. So nuking the data in iCloud seems to be the resolution. Thank you!
