### ISSUE TITLE
iOS 6.1 (6110) release notes function shows a GitHub 404 page

### ISSUE THREAD

**Issue by kconner** [Ranchero-Software/NetNewsWire#3933]
It tries to load this URL: <https://github.com/Ranchero-Software/NetNewsWire/releases/tag/ios-6.1>

I think it's meant to load: <https://github.com/Ranchero-Software/NetNewsWire/releases/tag/iOS-6.1>

![IMG_3805](https://user-images.githubusercontent.com/602569/229314312-1dce5c37-f147-40f5-adb4-da5b0383a947.png)
![IMG_3806](https://user-images.githubusercontent.com/602569/229314322-d3a79af6-ce49-4f40-a5cc-857192d0f1bb.png)

**Comment by stuartbreckenridge** [comment]
We are removing these links in a future build.
