### ISSUE TITLE
nitter.net RSS feed can't be added to NNW

### ISSUE THREAD

**Issue by kimonostereo** [Ranchero-Software/NetNewsWire#3935]
Hello! Since Twitter feeds were removed from the latest NNW, I was wondering if it would be possible to add nitter.net RSS feeds directly to NNW. Their RSS feeds work with feedly, but I can't seem to add them directly in NNW. The error I get is "can't add a feed because no feed was found." 

[Example nitter RSS feed](https://nitter.net/kimonostereo/rss)

**Comment by brentsimmons** [comment]
We recommend talking to the good people at Nitter. For some reason it’s not returning a feed to NetNewsWire — that’s on the Nitter side of things.

**Comment by markcellus** [comment]
You could use Open RSS as a workaround until Nitter works: https://openrss.org/twitter.com/kimonostereo

**Comment by kimonostereo** [comment]
> You could use Open RSS as a workaround until Nitter works: https://openrss.org/twitter.com/kimonostereo

Thanks! I'll give this a try. I also opened an issue on the [nitter github ](https://github.com/zedeus/nitter/issues/832) as well.

**Comment by andyzickler** [comment]
@kimonostereo I found that using nitter.nl works for me. https://github.com/Ranchero-Software/NetNewsWire/issues/3841#issuecomment-1419139133 I wonder if it's a server configuration issue on their end. But meanwhile the other host should work.

**Comment by kimonostereo** [comment]
@andyzickler thanks! Looks like they fixed it! Turns out it was [blocked](https://github.com/zedeus/nitter/issues/832#issuecomment-1514446990).
