### ISSUE TITLE
Shows Old Articles as new and Unread

### ISSUE THREAD

**Issue by greg-marra** [Ranchero-Software/NetNewsWire#3939]
this feed and another feed will regularly show. I believe it’s the first two posts in the feed is on read about once a week more than happy to help troubleshoot. Send logs in anyway I can!

![IMG_0963](https://user-images.githubusercontent.com/45101876/231288742-366a677c-1ac8-4a0a-b1c7-bc2877852abe.png)

**Comment by brentsimmons** [comment]
What‘s the URL of the feed or feeds that exhibit this behavior?

Are you using On My iPhone, iCloud, or some other account (Feedly, etc.)?

**Comment by greg-marra** [comment]
Paul Graham - http://www.aaronsw.com/2002/feeds/pgessays.rss

Get Rich Slowly - http://feeds.feedburner.com/getrichslowly

**Comment by greg-marra** [comment]
Happened again today with Paul Graham's blog:

https://imgur.com/a/vbXBYSD

**Comment by brentsimmons** [comment]
It’s the feed. Whenever we investigate something like this, it’s _always_ the feed. In this case, if you look at the feed, you can see that the links for those two items have gone weird. They look like this:

```http://www.paulgraham.com/https://sep.turbifycdn.com/ty/cdn/paulgraham/acl2.txt?t=1683312440&amp;```

While other links look like this example:

```http://www.paulgraham.com/progbot.html```
