### ISSUE TITLE
Hidden sidebar still selectable with keyboard shortcuts...

### ISSUE THREAD

**Issue by pqbon** [Ranchero-Software/NetNewsWire#3944]
With the sidebar hidden using the view->hide sidebar...

The keyboard arrow keys can still move the active selection in the sidebar.

**Comment by GetToSet** [comment]
HI @pqbon, could you provide more context about this issue (screen recording or macOS and NetNewsWire version etc.)? I've tried with the steps and could not reproduce it.

**Comment by pqbon** [comment]
[Screen Recording 2023-05-25 at 11.49.51.mov.zip](https://github.com/Ranchero-Software/NetNewsWire/files/11563955/Screen.Recording.2023-05-25.at.11.49.51.mov.zip)
Screen recording of using arrow keys on the keyboard to select things that are hidden by hiding the side bar. The only keys used in this recording are the arrow keys.
