### ISSUE TITLE
MacOS Version 6.1.2 (6114) stops refreshing feeds, getting stuck loading 1 of 82

### ISSUE THREAD

**Issue by mcarlson** [Ranchero-Software/NetNewsWire#3959]
Hello, I have to quit and restart the client to get it to refresh the feeds. It appears to be stuck trying to load a single feed (1 of 82) in the lower-left of the window.

Let me know how I can diagnose this or if there's any way to work around it. Thank you!

**Comment by brentsimmons** [comment]
Using On My Mac, iCloud, Feedbin, Feedly, or…?

**Comment by mcarlson** [comment]
Using iCloud

**Comment by brentsimmons** [comment]
This sounds like the slow-iCloud issue that we’ve written up here: https://netnewswire.com/help/iCloud
