### ISSUE TITLE
Won't load feed (stuck) on iOS and Mac (latest versions) 

### ISSUE THREAD

**Issue by OddHouseGames** [Ranchero-Software/NetNewsWire#3965]
Is there a limit to the number of feeds that you can have (iCloud)? For 6 roughly months I've not been able to use NetNewsWire as it just stalls on iOS and Desktop at 1 of 207.

**Comment by brentsimmons** [comment]
There is no limit to the number of feeds — but iCloud syncing can be really, really slow sometimes. Here‘s a help page about it: https://netnewswire.com/help/iCloud

**Comment by OddHouseGames** [comment]
Apologies, I misread the old response, didn't realize I could just copy to the 'on my mac' section and then just make regular back-ups.

YAY! Happy to be fully functioning with NetNewsWire again, and apologies I didn't realize it was a rate limiting issue on Apple's side. 

Hats off for a great product!
