### ISSUE TITLE
OFF TOPIC (please delete after owner review)

### ISSUE THREAD

**Issue by sjehuda** [Ranchero-Software/NetNewsWire#3966]
Hello Brent,

I didn't find your email address and I didn't yet set up a personal ActivityPub compatible account yet.

I have wrote a JSON Feed reader in [Javascript](https://openuserjs.org/scripts/sjehuda/Newspaper) last Friday and I'd be glad if you'd list it at [jasonfeed.org](https://www.jsonfeed.org/code/).

Please look into the "Help" section and let me know what to add.
NetNewsWire is marked as a recommended software.

Please pardon me for the off-topic post.

Thank you,
Schimon

**Comment by sjehuda** [comment]
My email address sjehuda@yandex.com

**Comment by brentsimmons** [comment]
@sjehuda Hi Schimon — you should contact Manton Reece, who runs that website these days.

**Comment by sjehuda** [comment]
Thank you, Brent!
