### ISSUE TITLE
Contents of document not scrolling after pressing `space` under Macbook Pro with M1 chip

### ISSUE THREAD

**Issue by dantezhu** [Ranchero-Software/NetNewsWire#3969]
Pressing `space` will not scroll the document content, but will switch directly to the next document if it is already at the bottom of the document.

Device: Apple M1 Pro
OS: macOS 13.3.1 (a) (22E772610a)

**Comment by danielpunkass** [comment]
This is a duplicate of #3929, which should be addressed by the next updated to Ventura.
