### ISSUE TITLE
[iOS] Theme reloading display issues in `main`

### ISSUE THREAD

**Issue by stuartbreckenridge** [Ranchero-Software/NetNewsWire#3988]
Changing the theme from the article view results in the new theme being displayed over the previous theme (or themes).  I _think_ this was introduced as part of #3950. 

https://github.com/Ranchero-Software/NetNewsWire/assets/7046652/07bb7ddb-7111-4e12-bed7-38221ea35371

**Comment by vincode-io** [comment]
That may have caused it. I'll take a look later.
