### ISSUE TITLE
[Tentative] Remove Reddit Extension

### ISSUE THREAD

**Issue by stuartbreckenridge** [Ranchero-Software/NetNewsWire#4010]
Similar to Twitter, and dependent on Reddit following through with [API pricing changes](https://www.reddit.com/r/apolloapp/comments/13ws4w3/had_a_call_with_reddit_to_discuss_pricing_bad/): 

- [ ] Remove Reddit-specific code
- [ ] Remove _Extensions_ UI in iOS Settings and macOS Settings (erstwhile Preferences 😢)
- [ ] Include an Alert informing users of Reddit removal

**Comment by johnsturgeon** [comment]
I'm confused, isn't there still a level of free access per OAuth token?
from : https://www.reddit.com/r/reddit/comments/145bram/addressing_the_community_about_changes_to_our_api/
## Free Data API
Effective July 1, 2023, the rate limits to use the Data API free of charge are:
* 100 queries per minute per OAuth client id if you are using OAuth authentication and 
* 10 queries per minute if you are not using OAuth authentication.

**Comment by vincode-io** [comment]
The 100 queries per minute is per application. Across all users, NNW would exceed that constantly.

> Today, over 90% of apps fall into this category and can continue to access the Data API for free.

I'm sure most apps in this category are toy apps or were never actually created once the developer registered them with Reddit.

**Comment by johnsturgeon** [comment]
Can't each client provide their own OAuth credentials?  100 queries is per OAuth client.

**Comment by brentsimmons** [comment]
Even if we could make it work technically for each user to provide their own OAuth credentials, we would be acting in bad faith. It’s clear that Reddit wants apps like ours to either stop using the Reddit API or pay for the privilege.

Which is their right, of course, though it’s a damn shame.

**Comment by johnsturgeon** [comment]
Gotcha, welp, let's hope they don't kill the RSS feeds then.
