### ISSUE TITLE
When using SwitchGlass NNW icon gets the no entry sign

### ISSUE THREAD

**Issue by adamprocter** [Ranchero-Software/NetNewsWire#4020]
In the dock it is fine , see attached
<img width="66" alt="Screenshot 2023-06-03 at 16 45 35" src="https://github.com/Ranchero-Software/NetNewsWire/assets/123951/35a1e156-1570-4b29-95de-4de890e0ce2d">

**Comment by brentsimmons** [comment]
Looks like MarsEdit has the same problem. I recommend reporting the bug to SwitchGlass folks.

**Comment by brentsimmons** [comment]
Which is John Siracusa, I just remembered.

**Comment by siracusa** [comment]
I [re-filed this against SwitchGlass](https://github.com/siracusa/SwitchGlass-Issues/issues/1).
