### ISSUE TITLE
BBC NEWS - World - Why?

### ISSUE THREAD

**Issue by akirataguchi115** [Ranchero-Software/NetNewsWire#4023]
I just installed this app to my iPhone XR. "On My iPhone" there is by default BBC NEWS - World which would be fine to demonstrate how this app works with RSS feeds but you can see from the image that it's not quite working.

![image](https://github.com/Ranchero-Software/NetNewsWire/assets/31825085/b99a41b8-5698-400a-aa96-9e9aa4060c5e)

Should this RSS feed in particular be removed. Also why are there 700+ notifications in the app icon when you first install the app?

**Comment by akirataguchi115** [comment]
So it seems. Then why do we have the BBC feed by default here?

**Comment by markcellus** [comment]
Open RSS provides full text of BBC articles: https://openrss.org/www.bbc.com/news/world

**Comment by akirataguchi115** [comment]
Great! Thanks for sharing that, @uncenter . Maybe we should then remove feeds from the defaults that aren't following best practice? Surely we're better than that.

**Comment by uncenter** [comment]
> Is not "in the business of"? What does this mean? Shouldn't NetNewsWire provide good examples of RSS feeds for the new users?
> 
> Also I'm opening two other issues that have yet not been answered on this issue that have been brought up: #4033 & #4034 .

NetNewsWire is a feed reader, not an feed creator. The purpose of the BCC feed is to, IMO, show what sorts of content can be displayed in the app, not serve as an example for a good feed.

**Comment by brentsimmons** [comment]
I don’t have to justify my decisions on things like this.

And me and the team are under no obligation to respond quickly to anything. Remember that this is a completely free app made entirely by volunteers in their spare time.

**Comment by akirataguchi115** [comment]
You and your team are under no obligation to respond quickly to anything. I remind myself at this point that this is a completely free app made entirely by volunteers during their spare time.

I argue that you do have to justify your decisions on things like this. Saying no as a maintainer is sometimes necessary but giving reasoning for the contributors is needed. Closing issues without explanation is not welcoming for the new contributors nor the for anyone else.

I hope this source-available project of yours and your team goes well.
