### ISSUE TITLE
Privacy Policy button link is broken

### ISSUE THREAD

**Issue by johnsturgeon** [Ranchero-Software/NetNewsWire#4027]
<img width="624" alt="image" src="https://github.com/Ranchero-Software/NetNewsWire/assets/9746310/d3394c8e-2de4-4fba-bb92-eb16ce35d235">

Clicking on 'Privacy Policy' goes here:
https://netnewswire.com/privacypolicy

Which (atm) is 404

**Comment by Jerry23011** [comment]
Hi, @johnsturgeon, you can try that again, it should be already fixed.

**Comment by johnsturgeon** [comment]
Works great!  Thank you
