### ISSUE TITLE
Open GitHub Discussions

### ISSUE THREAD

**Issue by akirataguchi115** [Ranchero-Software/NetNewsWire#4033]
Could we open GitHub Discussions? People on Slack aren't very responsive and I don't consider Slack channels to be "open" in the context of open source. This way we could have discussions about NetNewsWire without polluting the Issues more than it already is.

**Comment by brentsimmons** [comment]
I’d rather not have yet another channel for discussion. I’ve been happy with using a mix of Slack and GitHub issues.
