### ISSUE TITLE
Notification badges on by default

### ISSUE THREAD

**Issue by akirataguchi115** [Ranchero-Software/NetNewsWire#4034]
Why are notification badges on by default? Is there some reason this isn't an opt-in thing?

**Comment by stuartbreckenridge** [comment]
Notification badges are not on by default. 

Users are asked if they wish to enable notifications on the first launch of a freshly installed NetNewsWire. If they say yes, badges are displayed _and_ they can configure feeds to display new article notifications. If they say no, no badges are displayed, and new article notifications aren't possible.

There is no configuration option (at the current time) to enable notifications but suppress the badge count.

**Comment by vincode-io** [comment]
> There is no configuration option (at the current time) to enable notifications but suppress the badge count. 

This is because it can be done in System Settings.

**Comment by akirataguchi115** [comment]
Thanks for the information! Should we keep this open but change the title for something more descriptive like "Add option to suppress badge account"?

**Comment by stuartbreckenridge** [comment]
There's no need to add a feature. 

NetNewsWire -> Settings -> Open System Settings -> Notifications -> _Disable Badges_

**Comment by akirataguchi115** [comment]
Ah. What about getting notification badges for only a selection of RSS feeds?

Also where is this stated?

> There's no need to add a feature.

We only have a code of conduct but not actual CONTRIBUTING. Creating another issue for this: #4035 .
