### ISSUE TITLE
New feed not showing new items, but showing old items instead

### ISSUE THREAD

**Issue by ryancabanas** [Ranchero-Software/NetNewsWire#4036]
Hi,

I just installed NetNewsWire v6.1.2 today on my M1 MacOS v13.4 and logged in with a Feedly account.  I added this AWS Health Dashboard RSS feed (https://status.aws.amazon.com/rss/multipleservices-us-east-1.rss) to my Feedly account.  There are 3 new posts in this feed, but I'm not seeing them in the NetNewsWire app (or Feedly.com), but instead I'm seeing some old posts.

Any idea why?

Thanks!
Ryan

**Comment by pdokas** [comment]
Feedly doesn't update feeds from the origin on demand. It can take a while to pick up new content, especially for feeds with fewer subscribers.

**Comment by ryancabanas** [comment]
Got it.  Thanks!
