### ISSUE TITLE
Manual refresh for content feeds

### ISSUE THREAD

**Issue by mkardi** [Ranchero-Software/NetNewsWire#4038]
Does NetNewsWire currently allow manual refresh for feeds or it is done fully in background?
I did not find such options so it would be nice to have manual refresh toggle somewhere.

**Comment by brentsimmons** [comment]
On Mac you can use File > Refresh or click the Refresh button in the toolbar.

On iOS you can do pull-to-refresh on the Feeds screen.

**Comment by brentsimmons** [comment]
Ah. Gotcha. On Mac there is — see the Refresh Feeds popup. On iOS there is not.

**Comment by Morse6690** [comment]
This is a +1 for me. I understand why the app auto refresh will help most users.
It would be really heroism to my use case to have the iron to disable any form of auto refresh, and have the option to only refresh manually.
Really loving using this app so far though.
