### ISSUE TITLE
Storage of feeds on phone

### ISSUE THREAD

**Issue by GaryGadget** [Ranchero-Software/NetNewsWire#4040]
Hi, I’m curious to know how the records stored are managed i.e. do all of the stories get saved so over time the app takes up more and more memory. I can’t see a way of purging them without deleting the feed itself. Thanks for your help.

**Comment by stuartbreckenridge** [comment]
@GaryGadget https://github.com/Ranchero-Software/NetNewsWire/blob/main/Technotes/DatabaseCleanup.md describes how articles are managed.
