### ISSUE TITLE
Scrolling article view with arrow keys triggers key repeat bonk sounds

### ISSUE THREAD

**Issue by cadin** [Ranchero-Software/NetNewsWire#4041]
If I hold the up or down arrow key to scroll through an article it triggers the key repeat sound effect. This happens both at the end of an article and while the article is actually scrolling.

I believe this is a newish issue that started either with Ventura or with a recent NNW update (I updated both at the same time).

I'm using NNW 6.1.2 (6114) on MacOS 13.4 (22F66).

**Comment by brentsimmons** [comment]
It’s a macOS 13.4 bug, unfortunately.
