### ISSUE TITLE
[Bug] "Release Notes" link in iOS 404's

### ISSUE THREAD

**Issue by urda** [Ranchero-Software/NetNewsWire#4043]
# Problem:

The "Release Notes" link 404's if clicked on in iOS apps.

# Expected Response:

The "Release Notes" link opens a release notes page.

# Actual Response:

The "Release Notes" link reaches a Github.com 404 error page.

# Workarounds

Visit the release notes page manually, but otherwise no.

# Possible Corrections

It seems the dynamic URL builder [in this section](https://github.com/Ranchero-Software/NetNewsWire/blob/87f69eed050f25082a8c364aae006680b143a828/Shared/Extensions/URL-Extensions.swift#L23-L36) is prone to error since it requires making sure the Github tag exists first. This URL should **Fall back** to `https://github.com/Ranchero-Software/NetNewsWire/releases` perhaps if the tag is unavailable from Github?

# Related Issues

Related to #3814

**Comment by zll600** [comment]
@brentsimmons You have already changed the release notes URL to `https://github.com/Ranchero-Software/NetNewsWire/releases/` in https://github.com/Ranchero-Software/NetNewsWire/commit/799d3f38946b6c424f54575a711ad7c7583c601e. Has this issue been resolved?
