### ISSUE TITLE
[Feature Request][macOS] Option to show unread article count on dock icon

### ISSUE THREAD

**Issue by alohawolf** [Ranchero-Software/NetNewsWire#4057]
It'd be real nice to be able to have an option to show the unread article count on the dock icon. Right now I just need to go check it periodically to see if there are unread articles.

**Comment by brentsimmons** [comment]
You can!

Go to System Settings, click on Notifications, find NetNewsWire. Make sure `Badge Application Icon` is turned on.

<img width="764" alt="Screenshot 2023-07-08 at 10 48 59 AM" src="https://github.com/Ranchero-Software/NetNewsWire/assets/1297121/a01e46ba-dcc2-414d-9166-30bcfecec9dc">
