### ISSUE TITLE
Cannot load feed on fresh install

### ISSUE THREAD

**Issue by klimenttoshkov** [Ranchero-Software/NetNewsWire#4074]
I have NetNewsWire installed on a few of my computers and iOS devices. The feed is in iCloud and is automatically picked up. Recently installed version 6.1.4 on an Air M1, 2020 with Ventura 13.5. Application finds 68 feeds and is stuck on "Loading 1 of 68". Never gets to the point to initialize with data the feeds. 

Note that I had similar issue with older versions on intel macs as well, but after long waiting it somehow fixed itself. But now it does not load and is stuck like forever.

<img width="275" alt="image" src="https://github.com/Ranchero-Software/NetNewsWire/assets/59835221/f2ed0da9-5f1a-43ad-a3db-a6b73e19c609">

**Comment by brentsimmons** [comment]
We describe this issue and some things to do. But the best advice is just to wait — it can take many hours, but eventually it should catch up. https://netnewswire.com/help/iCloud
