### ISSUE TITLE
Can't open in browser when feed guid has no http prefix

### ISSUE THREAD

**Issue by UjuiUjuMandan** [Ranchero-Software/NetNewsWire#4082]
The feed URL is `https://blog.xulihang.me/feed/`.

It looks like this when trying to open an article in browser:

<img width="801" alt="Screenshot 2023-08-13 at 22 11 54" src="https://github.com/Ranchero-Software/NetNewsWire/assets/125150101/87b49726-8c49-4664-854a-96810d69885e">

_The application can't be opened_

And, the only difference I found between it and others seems to be this line:

```
<guid>blog.xulihang.me/accidentally-broke-my-ankle</guid>
```

It does not have a `http`/`https` prefix.

Also, the output of `Copy Article URL` is `blog.xulihang.me/accidentally-broke-my-ankle`, which differs from others that always the prefix.

On macOS Ventura 13.4.1. I don't know how to export logs, any help is appreciated.

**Comment by brentsimmons** [comment]
Can’t reproduce in current main (29 Sep 2024).
