### ISSUE TITLE
Previously read articles keep coming back as unread seemingly randomly

### ISSUE THREAD

**Issue by robolth** [Ranchero-Software/NetNewsWire#4090]
I use NNW Version 6.1.4 (6120) on macOS Ventura 13.5 and NNW 6.1.4 on iOS 16.6, with iCloud sync.
I wasn't able to identify a pattern, sometimes it goes back a few years. It usually comes in waves though: I wake up one morning and I have hundreds of unread articles which have been redownloaded to the app.

**Comment by robolth** [comment]
I tried to switch to Reeder and the problem was the same, so the issue is not with NNW, my bad. Closing the issue.

**Comment by stuartbreckenridge** [comment]
This is likely because the unique id of an item in a feed has changed — ideally it should be static.

**Comment by robolth** [comment]
Hey, thanks for your help. Two questions if I may:
-is NNW occasionally cleaning the list of seen IDs? (I suppose not since I saw the same behavior with Reeder, but I ask just in case)
- is there any way with NNW to check this seen IDs list so as to help me further diagnose the problem?
Thanks again!
