### ISSUE TITLE
iOS: footnote markers in main text have wrong z-index once tapped

### ISSUE THREAD

**Issue by JostMigenda** [Ranchero-Software/NetNewsWire#4117]
See attached screenshot of [this post](https://onefoottsunami.com/2023/09/22/coors-marketings-home-run/) displayed in NNW 6.1.4 (Build 6120) on iOS 16.6.1
![image](https://github.com/Ranchero-Software/NetNewsWire/assets/16189747/1d88c039-60a6-48e3-8920-cc8adfb0f577)

Steps to reproduce:
1. View the article
2. Tap footnote marker "2" to show the footnote in a pop-up.
3. Tap elsewhere to dismiss the pop-up.
4. Tap footnote marker "1".

Expected result:
The pop-up for footnote 1 is displayed above the footnote marker "2".

Actual result:
See screenshot.
(Note that step 2. is essential. If you skip it, you get the expected result.)

Let me know if you have any questions; I'm happy to help!

**Comment by Wevah** [comment]
Replicable on macOS as well.
