### ISSUE TITLE
NetNewsWire Mac stalls forever in "Finding feed"

### ISSUE THREAD

**Issue by jcbsv** [Ranchero-Software/NetNewsWire#4125]
I believe this is a bug: When trying to add the [Scott Hanselman blog](https://www.hanselman.com/blog/) to my feedlist the Mac app stalls forever in the "Finding feed" progress dialog.

**Comment by markcellus** [comment]
Open RSS offers this feed at https://openrss.org/www.hanselman.com/blog/ that can be used with NetNewsWire app.

**Comment by markcellus** [comment]
oh the OP seemed like it was something wrong with just the hanselman feed since that was singled out. does it happen with any other RSS feed?

**Comment by brentsimmons** [comment]
This is working with current main branch (29 Sep 2024)
