### ISSUE TITLE
Blogspot icon is half missing

### ISSUE THREAD

**Issue by Majorseventhchord** [Ranchero-Software/NetNewsWire#4126]
I noticed this evening that the icon for Blogpost blogs is half missing:

![Screenshot 2023-10-06 at 9 53 19 PM](https://github.com/Ranchero-Software/NetNewsWire/assets/125771322/ec6ef233-895e-4eb8-9697-51a6bdbfdc93)

**Comment by Majorseventhchord** [comment]
I should have added: that’s on a Mac just updated to Sonoma 14.0. In iOS 17 the icon is fine.

**Comment by Majorseventhchord** [comment]
I just updated to Sonoma 14.1. The icon is back in full.

**Comment by brentsimmons** [comment]
Sounds like an Apple bug that got fixed. Cool. Means there’s nothing we have to do — and probably there was nothing we actually _could_ have done.

**Comment by Majorseventhchord** [comment]
Thanks for your reply and for such a great app, Brent.

Michael
