### ISSUE TITLE
NetNewsWire can't find my blog's feeds

### ISSUE THREAD

**Issue by nathansnelgrove** [Ranchero-Software/NetNewsWire#4129]
Hey there! Working on a new blog on a new platform, and part of the job is migrating RSS feeds.

NetNewsWire doesn't want to recognize mine, though, and I'm not sure why. (Reeder does.)

In NetNewsWire for Mac, I've tried adding the following URLS:

- https://beta.nathansnelgrove.com
- https://beta.nathansnelgrove.com/feeds/writing.atom
- https://beta.nathansnelgrove.com/feeds/watching.atom
- https://beta.nathansnelgrove.com/feeds/feed.atom

I get the same error message for all of them. I'd like to be visible to NetNewsWire. Any idea what I'm doing wrong?

FWIW, the files are all atom files with a .atom extension, and the `<head>` of each HTML page includes: 

```
<link rel="alternate" title="All Content" type="application/atom+xml" href="{{ url('feeds/feed.atom') }}">
<link rel="alternate" title="Writing" type="application/atom+xml" href="{{ url('feeds/writing.atom') }}">
<link rel="alternate" title="Movie Log" type="application/atom+xml" href="{{ url('feeds/watching.atom') }}">
```

The fancy handlebars-style url is just for the templating engine the CMS uses. They all point to the right place though.

**Comment by brentsimmons** [comment]
What type of account are you using? On My Mac, iCloud, Feedly, etc.…?

**Comment by nathansnelgrove** [comment]
Feedly. And just to make sure I'm clear on this, Reeder finds all three feeds from their browser extension and lets me pick which. NNW doesn't find any, or it hangs (if I copy and paste the main URL rather than using the browser extension.)

**Comment by brentsimmons** [comment]
If you use an On My Mac account with NetNewsWire (you can use multiple types of accounts) does it work then?

(My suspicion is that this is the same Feedly bug we’ve seen before with adding feeds.)

**Comment by nathansnelgrove** [comment]
Holy fart. That worked. 

Are there known problems like this with Feedbin? I've been considering switching for a very long time, but have never had a professional reason to. Apparently I do, now that I'm making RSS feeds.

This probably requires a separate ticket, but if I type in a domain and there are multiple feeds, it'd be awesome if NNW could display a list and let me select what I want to add.

**Comment by brentsimmons** [comment]
No known issues like with this Feedbin.

On the topic of picking a feed — there is already a separate ticket for that.

**Comment by nathansnelgrove** [comment]
Perfect! Thanks Brent. I appreciate all you do for all of us in the Apple Community!
