### ISSUE TITLE
Can't find feed on my blog

### ISSUE THREAD

**Issue by boredzo** [Ranchero-Software/NetNewsWire#4131]
I'm using NetNewsWire 6.1.4 (6120) on Monterey 12.6.8 (21G725).

I wondered if NNW for Mac could auto-detect feeds when I try to add a non-feed URL. It doesn't work on my own blog's feed: https://boredzo.org/blog/  NNW tries, then gives up and says “Can’t add a feed because no feed was found.”.

If I try the official WordPress blog, that works: https://wordpress.org/news/

So, seems like it might be something about my theme that is tripping NNW up?

I do have feed links in the `head` element:

```
<link rel="alternate" type="application/atom+xml" title="Idle Time Atom 1.0 Feed" href="feed:://boredzo.org/blog/feed/atom">
<link rel="alternate" type="application/rss+xml" title="Idle Time RSS 2.0 Feed" href="feed:://boredzo.org/blog/feed">
```

**Comment by brentsimmons** [comment]
What kind of account in NetNewsWire? Feedly, On My Mac, iCloud, etc.?

**Comment by boredzo** [comment]
On My Mac.

**Comment by brentsimmons** [comment]
Two things:

1) A `feed` URL should have one :, as in feed://boredzo.org/blog/feed instead of feed:://boredzo.org/blog/feed

2) But in these link elements, it should be a regular http(s) URL and not a feed: URL

**Comment by boredzo** [comment]
Oooh. Well-spotted, especially on that double colon.

Changing both of those things in my WordPress theme's header.php fixed it. Thank you!

**Comment by boredzo** [comment]
The relevant code, by the way, was:

```
<link rel="alternate" type="application/atom+xml" title="<?php bloginfo('name'); ?> Atom 1.0 Feed" href="feed:<?php echo substr(get_bloginfo('atom_url'), 5); ?>" />
<link rel="alternate" type="application/rss+xml" title="<?php bloginfo('name'); ?> RSS 2.0 Feed" href="feed:<?php echo substr(get_bloginfo('rss2_url'), 5); ?>" />
```

I suspect this dates back to when `get_blogInfo('atom_url')` returned an `http:` link, so the offset was correct and was then made incorrect when my blog switched over to https. I think my intent for the substitution (many years ago) was to promote the use of feed: URLs. These days it's more useful (and probably better for avoiding unnecessary redirects) to promote https: instead.

So I've taken out the substitution outright, and now just emit the result of `get_bloginfo` verbatim. The result is an `https:` URL, and NetNewsWire happily discovers it.

**Comment by brentsimmons** [comment]
Great! Thanks, Peter.
