### ISSUE TITLE
Widget for iOS not refreshing

### ISSUE THREAD

**Issue by iamllanero** [Ranchero-Software/NetNewsWire#4133]
The widget on iOS doesn't seem to refresh without having to open NNW -- thereby defeating the whole purpose of having a widget imo. I have set the background refresh on. Does NNW have a background refresh poll setting that I am missing?

**Comment by stuartbreckenridge** [comment]
Background refresh (and therefore background refresh of our widgets) is controlled by iOS. 

The more NetNewsWire is used, the more time iOS will give NetNewsWire in the background...with the knock-on benefit of more widget refreshes. 

(We request a background refresh every 15 minutes, but whether or not that happens is out of our control.)

**Comment by iamllanero** [comment]
Ah makes sense. I thought I used enough to give it more priority but will have to ratchet it up! Will close this issue.
