### ISSUE TITLE
Reader view fails on seattletimes.com articles

### ISSUE THREAD

**Issue by sdpoole** [Ranchero-Software/NetNewsWire#4134]
Version 6.1.4 (6120)
macOS 14.0 (23A344)
Apple Mac mini M1 2020

I've added a couple of Seattle Times feeds. Consistently, switching to reader view for an article causes the reader view icon to animate for about five seconds and then change to an exclamation point without rendering the reader view. 

I tried another RSS reader (Fluent Reader) and it was able to show the full articles. 

I'm not seeing the issue with any of the default NetNewsWire feeds.

Sample feed: https://www.seattletimes.com/seattle-news/feed/

**Comment by brentsimmons** [comment]
Unfortunately, article extraction is not a perfect science. We use a free service provided by Feedbin — it’s not something we can extend or fix.
