### ISSUE TITLE
Not bringing in news updates

### ISSUE THREAD

**Issue by cbismetoo** [Ranchero-Software/NetNewsWire#4137]
NetNewsWire has never done this before. It doesn't bring in updates after I tell it to update. This is the first time in years that this has happened. 

I use NetNewsWire app on my iPad Pro with iPadOS 16.7.1 . It worked fine yesterday, but stopped working today. Nothing has changed on iPad Pro nor the app that I know of. Wi-Fi is working fine.

**Comment by brentsimmons** [comment]
What type of account — On My iPad, iCloud, Feedly, etc. — are you using?

**Comment by cbismetoo** [comment]
iPad ProCBOn Oct 25, 2023, at 9:53 PM, Brent Simmons ***@***.***> wrote:﻿
What type of account — On My iPad, iCloud, Feedly, etc. — are you using?

**Comment by brentsimmons** [comment]
What type of syncing account? None, or one of the various systems like iCloud, Feedbin, NewsBlur, Feedly?

**Comment by cbismetoo** [comment]
I think Feedly, but I'm not sure. How do I find out?CBOn Oct 25, 2023, at 9:59 PM, Brent Simmons ***@***.***> wrote:﻿
What type of syncing account? None, or one of the various systems like iCloud, Feedbin, NewsBlur, Feedly?

**Comment by Millyonline** [comment]
Hello,
I have the same problem and I am using Feedly. 
NetNewsWire stopped syncing with it on all my devices at the same time.

**Comment by brentsimmons** [comment]
One thing to try — go to NetNewsWire’s settings, and disable Feedly, then re-enable it.

**Comment by cbismetoo** [comment]
It's working for me now and has for the past few days— thank goodness.It was just that one day where it didn't update. CBOn Oct 27, 2023, at 9:16 AM, Brent Simmons ***@***.***> wrote:﻿
One thing to try — go to NetNewsWire’s settings, and disable Feedly, then re-enable it.

**Comment by Millyonline** [comment]
Argh! Yea, I did disable Feedly, then re-enable it, and debuted all devices.
But then it got me thinking that I hadn't yet tried to deleted and star from the top. 
It worked, I got my Feedly back.
Thanks!
