### ISSUE TITLE
starred post stuck in "today"

### ISSUE THREAD

**Issue by olets** [Ranchero-Software/NetNewsWire#4151]
One of my starred posts is showing in the "today" smart feed, even though it isn't from today.

Lmk if there's anything I can do to help debug.

**Comment by brentsimmons** [comment]
Is it still stuck?

Is there any chance it was from the past 24 hours? (“Today” really means past 24 hours in NetNewsWire.)

**Comment by olets** [comment]
It's no longer stuck. I bet I was tricked by today vs past 24h. Thanks!
