### ISSUE TITLE
NetNewsWire not refreshing

### ISSUE THREAD

**Issue by oliviazhaoxu** [Ranchero-Software/NetNewsWire#4152]
Hello, my NetNewsWire has been unable to fetch the feed and update for a few days. Even when I manually hit the refresh button nothing shows up. It worked fine last week. I tried quitting the application and reopening it, as well as restarting my laptop, but it didn't work. Can anyone tell me what's wrong? Thanks!

**Comment by Wevah** [comment]
All feeds, or just a specific feed?

**Comment by oliviazhaoxu** [comment]
All feeds!

---
Olivia Zhao (she / her / hers)
(415) 307 1971 | ***@***.***

**Comment by oliviazhaoxu** [comment]
> All feeds, or just a specific feed?

All feeds!

**Comment by oliviazhaoxu** [comment]
OK I figured it out. It's because the RSS feed aggregator I used is dead! I changed it to RSSHub and it works again.
