### ISSUE TITLE
where's the preference?

### ISSUE THREAD

**Issue by RedemptionC** [Ranchero-Software/NetNewsWire#4154]
I've read [this guide](https://netnewswire.com/help/mac/6.1/en/twitter-feeds)

it mentions that we could add feed from Reddit or Twitter in the preference setting:
>Choose NetNewsWire › Preferences from the menu bar.

But there isn't the preference
<img width="269" alt="image" src="https://github.com/Ranchero-Software/NetNewsWire/assets/17563754/a22dca5a-cf2c-4cb4-9f7c-b92a16682247">

I'm using the latest version of NNW
<img width="396" alt="image" src="https://github.com/Ranchero-Software/NetNewsWire/assets/17563754/d3033da4-631c-4c89-9f75-30d0807e17a3">

**Comment by brentsimmons** [comment]
The guide needs to be updated. Unfortunately, both Twitter and Reddit no longer allow us to use their API.
