### ISSUE TITLE
Inoreader support

### ISSUE THREAD

**Issue by venkatasg** [Ranchero-Software/NetNewsWire#416]
http://www.inoreader.com/developers/

I love the app so far, and I'd love to see it have support for inoreader, since that's the service I use.

**Comment by jbeker** [comment]
Per conversation with Brent and Maurice, I'll start researching.

**Comment by venkatasg** [comment]
Any way I can help? I've never worked on this sort of stuff but I think I can be of some help :)

**Comment by jbeker** [comment]
@vincode-io I have been looking into this and the basic API is similar to Google Readers, but the big difference is authentication, which is OAuth2. This will require a 2-phase UI to accomplish that will probably need to be much different in iOS vs. Mac. I saw you had put a placeholder OAuth2 authentication type in; did you have thoughts on how this could be implemented?

**Comment by vincode-io** [comment]
I haven't given it any thought.  I know that we will have to do OAuth2 for Feedly, so it's on my list of things to do.

**Comment by vincode-io** [comment]
This has been implemented and is scheduled to be part of the 6.0 NetNewsWire release.  Watch the NetNewsWire News blog because we will be announcing test versions of NetNewsWire 6.0 and really need some help testing this sync service.
