### ISSUE TITLE
Can't add https://github.com/ShikiSuen/r128x/releases.atom

### ISSUE THREAD

**Issue by breun** [Ranchero-Software/NetNewsWire#4181]
I already have many GitHub releases feeds in NetNewsWire (e.g. https://github.com/immutables/immutables/releases.atom), but when I try to add https://github.com/ShikiSuen/r128x/releases.atom I get this error message:

> Feed not found
>
> Can't add a feed because no feed was found.

According to https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fgithub.com%2FShikiSuen%2Fr128x%2Freleases.atom this is a valid Atom 1.0 feed. Any ideas?

**Comment by brentsimmons** [comment]
Using what kind of account? Of On My Mac, iCloud, Feedly, Feedbin, etc.?

Also: Mac or iOS?

**Comment by markcellus** [comment]
May be something with NNW. Works for me in Inoreader. You can also try Open RSS feeds as an alternative

https://openrss.org/github.com/ShikiSuen/r128x/releases

**Comment by brentsimmons** [comment]
It works for me in NetNewsWire using my On My Mac account, which makes me think @breun might be using some other type of account.

**Comment by breun** [comment]
> Using what kind of account? Of On My Mac, iCloud, Feedly, Feedbin, etc.?
> 
> Also: Mac or iOS?

Ah sorry, I'm using a Feedly account in NetNewsWire on macOS.

I just tried adding it again, and now it worked. Yesterday I tried multiple times without success. 🤷‍♂️

Since I can't reproduce the issue anymore, I guess I'll close this issue.

**Comment by brentsimmons** [comment]
Feedly was my guess. We’ve seen this as an intermittent issue with Feedly — looks like some kind of issue on their side.
