### ISSUE TITLE
Article list processes HTML tags in title

### ISSUE THREAD

**Issue by eDeniska** [Ranchero-Software/NetNewsWire#4182]
Article title looks differently on the article list pane and article view - HTML tags are processed or stripped on article list.
If tags are not stripped but rather processed, this could lead to styling issues, or even code injection in case if <script> tag is also supported.

Screenshot attached with article list and article contents shown.
<img width="1484" alt="Screenshot 2023-12-23 at 9 24 04 AM" src="https://github.com/Ranchero-Software/NetNewsWire/assets/950994/bc80b224-905d-4375-97d6-6d15e3fbe309">

**Comment by brentsimmons** [comment]
HTML code is stripped (not processed) from the timeline.

**Comment by Wevah** [comment]
I do agree that there should be better alignment between what's shown in the timeline and the title in the article view.
