### ISSUE TITLE
Blockquote-like paragraphs in Beehiiv feeds don't show up in NNW 

### ISSUE THREAD

**Issue by wendycholbi** [Ranchero-Software/NetNewsWire#4190]
At first I thought this was related to Support Media RSS #4132 , which is causing some images and embeds that use the <media:content> tag to not show up (particularly in Substack feeds), but when I inspect the page source of this Beehiiv feed, I don't see that tag applied, only CSS for padding and borders, applied to paragraphs. 

I'm using NetNewsWire 6.1.4 on MacOS 12.7.2 (Monterey), so if this is an issue that would magically be fixed by upgrading to Ventura/Sonoma, please just let me know and I'll file it under "things that will be fixed when I can buy a newer MacBook Pro" :)

Two examples:

1. https://www.todayintabs.com/p/eat-of-my-strawberry-flesh
There are 3 quotes (first starts with "IT'S A DRAMATIC...", second starts with "There was zero explanation...", third starts with "I'd been furious...") and none of them appear in the NNW feed. There's not even an extra space indicating something is missing, so without the context clue of a colon indicating a following quote, you would never know there was an entire missing paragraph.
2. https://www.todayintabs.com/p/the-ox-man-cometh
There are 2 quotes (first starts with "In her response...", second stars with "In her very ease...") and neither of them appear in the NNW feed.

All of these quotes are paragraph tags (not using the blockquote tag), wrapped in divs with no other tags involved, and I can't figure out why any of the CSS would cause them to not appear in the feed.

**Comment by brentsimmons** [comment]
What’s the URL of the feed? What kind of account are you using?

**Comment by wendycholbi** [comment]
Oh sorry, didn't think to provide the full feed URL as I just put https://www.todayintabs.com/ into the New Feed dialog in NNW and let it find the feed:

https://rss.beehiiv.com/feeds/ZRiesnGI0u.xml

I just add feeds On My Mac in NNW, no external service or account.

Now, looking at that feed in my browser, I can see that there are just empty blockquotes where those quotes are supposed to be. Which makes it clear that it's an issue originating with Beehiiv instead of NNW's display of the feed. 

Color me sheepish! I'm sorry -- I should have investigated more fully before filing this.

**Comment by brentsimmons** [comment]
All good. Thanks for looking into it!
