### ISSUE TITLE
Social media embeds do not show in third party services

### ISSUE THREAD

**Issue by gferreroferri** [Ranchero-Software/NetNewsWire#4192]
I have noticed that if a feed article has social media embeds like X or Instagram, and the feed is in a third party service (Feedly, FreshRSS, etc.), the embed shows as text. However, if I use the iCloud option, it shows properly. Is this a bug?

**Comment by brentsimmons** [comment]
Some third party services strip out all JavaScript, and JavaScript is required for social media embeds to work correctly.
