### ISSUE TITLE
URL encoded characters in list and article view

### ISSUE THREAD

**Issue by pimoore** [Ranchero-Software/NetNewsWire#4195]
I’m seeing URL encoded characters instead of an apostrophe in an article:

![image](https://github.com/Ranchero-Software/NetNewsWire/assets/5413470/e60bba52-aab5-49e4-a1a4-0fcbdb4af02f)

I don’t recall seeing this before, so I’m wondering if it’s a new bug or something with the particular article?

Update: I just checked the same article in Reeder, and the apostrophe displays correctly. Definitely seems to be NNW specific.

**Comment by brentsimmons** [comment]
What’s the URL of the feed? Which sync service are you using?

**Comment by pimoore** [comment]
Feed URL: https://adactio.com/rss/
Aggregator: Feedbin 

I also just tested this same feed with iCloud sync in NNW, and same encoded character error occurs.

**Comment by brentsimmons** [comment]
It’s a bug in the feed. The apostrophe is encoded as `&amp;#8217;` but it should be just `&#8217;`.
