### ISSUE TITLE
Does anyone else think Hyphenation needs some tweaking?

### ISSUE THREAD

**Issue by chriswrightau** [Ranchero-Software/NetNewsWire#4198]
This is my first contribution here; I’m reviving an old support request I made back in 2020 which nothing ever came of, but I maintain is an issue.

I’ll preface this by saying I am not a programmer and do not understand the underlying frameworks and technologies behind what I’m about to discuss. 

But from a user point of view, the way hyphenation works in NetNewsWire has always felt broken to me. I’m frequently seeing hyphens used in more than 40% of the paragraph lines, which feels like far too many. I’ve attached an example from my morning read where 12 out of 19 visible lines were hyphenated, that’s 63%.

![IMG_3946](https://github.com/Ranchero-Software/NetNewsWire/assets/7374259/e1572031-a9e7-4f4a-b005-f2c342a20b6d)

Do others share this concern? If so, I would propose making the following changes/conditions:

- No consecutive hyphens (2 or more in lines above/below each other)
- No hyphens near the beginning or end of words (should be a 70:30 split at most, and never leave less than 3 letters on one line)
- No hyphens in headings, captions, or quotes.

One last request would be to have the option to disable hyphens all together as I feel they’re often unnecessary on modern devices. 

Curious to hear other people’s thoughts on this, and grateful for the app and its community as always!

**Comment by brentsimmons** [comment]
The hyphenation is outside of our control — it’s provided by WebKit, which does all the rendering for the article views.

I think, though I’d have to check, that one could turn off hyphenation by making a custom theme out of our standard themes — and just edit the CSS file to turn off hyphenation. I’m not positive of this, since I haven’t tried it, but it sounds possible.

**Comment by chriswrightau** [comment]
Thanks for following up Brent. Appreciate the suggestion too, I'll look into it!

**Comment by chriswrightau** [comment]
Just following up — I have zero knowledge or experience programming but managed to do exactly what Brent suggested in 2 minutes. If anyone would like to do the same, you can download this [modified version of the default theme here](https://github.com/chriswrightau/Default-Without-Hyphens/blob/e5634ce06536387a765a1446441045738fbca701/Default%20Without%20Hyphens.nnwtheme.zip).

**Comment by Wevah** [comment]
There's also a [`hyphenate-limit-chars`](https://developer.mozilla.org/en-US/docs/Web/CSS/hyphenate-limit-chars) property which WebKit doesn't (yet) support, but it does have `-webkit-hyphenate-limit-before` and `-webkit-hyphenate-limit-after` (which AIUI are being replaced by the former one).
