### ISSUE TITLE
Newsblur sync

### ISSUE THREAD

**Issue by nickoneill** [Ranchero-Software/NetNewsWire#420]
I realize integration with services are a future feature, so here's my newsblur sync placeholder.

Happy to contribute code for either this specific service or part of the sync integration in general when it's time. API docs are here: https://newsblur.com/api

**Comment by jtraulle** [comment]
I add my vote for this feature and add that Newsblur has support for folder hierarchy (folders and subfolders to order feeds) and that no Mac client (neither Reeder not ReadKit) currently support that particularity (this should be considered when building the integration/sync feature).

**Comment by PBones** [comment]
Count me as yet another user who would love, love, love to see this. I use NewsBlur as my reader because it makes sync easy. But on the Mac, I use a SSB app for it, which isn't ideal. I'd much rather use NNW.

**Comment by kemayo** [comment]
I’m on the NewsBlur-as-prerequisite train as well. That said, I suppose “netnewswire iOS + iCloud sync” would be a completely viable alternative, so whichever of these comes up first...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lamnatos** [comment]
One more NB wish from me, also it'd be even better if NB's Intelligence Classifiers (aka Feed Training/Focus Mode) could also be supported at some point:

https://www.newsblur.com/api#/classifier/:id

**Comment by kemayo** [comment]
I noticed while digging that [a fairly large amount](https://github.com/Ranchero-Software/NetNewsWire/commits/master/Frameworks/Account/NewsBlur) of work on NewsBlur support seems to have landed on March 21st, so I figured I'd mention it here to inspire hope in others. (Obviously, [no ETAs](https://inessential.com/2019/10/28/no_etas).)

**Comment by nickoneill** [comment]
Has this been implemented?

**Comment by vincode-io** [comment]
Yes.  It is scheduled to be released in NetNewsWire 6.0, but that could change depending on how testing goes.
