### ISSUE TITLE
Feature Request: Toolbar button to show and hide the sidebar

### ISSUE THREAD

**Issue by YacYac** [Ranchero-Software/NetNewsWire#4204]
It would be nice to have a button in the toolbar to show and hide the sidebar that's common in many mac apps that feature one. I don't always remember the exact keyboard shortcut and i'd prefer not to dig in the menu for something I do commonly when I'm trying to conserve screen real estate on my laptop.

**Comment by tkafka** [comment]
Same here, thanks for considering! As there is already a menu option, I'd love to add a button into the interface.
Bonus points if the preference is preserved between app runs :).

<img width="1217" alt="image" src="https://github.com/user-attachments/assets/95f1c6d0-5e44-436f-826b-dbfd91edc0ed">

**Comment by brentsimmons** [comment]
Fixed in NetNewsWire 6.1.5.

**Comment by tkafka** [comment]
Thank you!
