### ISSUE TITLE
Feature Request: Ability to deactivate or mute feeds

### ISSUE THREAD

**Issue by tyeNewton** [Ranchero-Software/NetNewsWire#4206]
I'd love the ability to deactivate or mute feeds so they do not auto-refresh or contribute to unread count. 

I have some feeds that I like to park and manually check now and then. Sure, I could do this by visiting that feed's webpage, but having them all collected in NetNewsWire to either prompt me when I happen to open the app, or just to have at the ready to reactivate when I want to, would be ideal. Ultimately, I just don't want those particular feeds to contribute to the unread count and download content at this time.

**Comment by djpowers** [comment]
I was searching for this as well, looks like it's already been suggested in #3401.

**Comment by brentsimmons** [comment]
Closing as duplicate.
