### ISSUE TITLE
Feature Request: Unread count badge on macOS app icon

### ISSUE THREAD

**Issue by tyeNewton** [Ranchero-Software/NetNewsWire#4207]
Currently, only the iOS/iPadOS app shows the unread count in a red badge on the app icon. I'd like to have the option to have show this on the macOS app, at least while it's running (just like Apple's Mail app).

**Comment by brentsimmons** [comment]
Go to System Settings, click on Notifications, then select NetNewsWire, then choose Badge application icon.

<img width="533" alt="Screenshot 2024-02-03 at 2 07 05 PM" src="https://github.com/Ranchero-Software/NetNewsWire/assets/1297121/1ac11c62-27ab-4506-802f-b9fe1a65fd5e">

**Comment by tyeNewton** [comment]
Oh how funny, it didn't occur to me that it would be on the macOS end since I intended to enable Notifications if/when initially prompted. Does NNW not request permission to allow notifications on first launch, or must I have mistakenly disallowed them without noticing? (I set up NNW today, so not something I did a while back and forgot about.) 

Perhaps a shortcut inside NNW app Settings redirecting to System Settings > Notifications would help future dummies like me. : )

In any case, thanks Brent!

**Comment by dnywh** [comment]
Echoing the above. I didn’t even think of editing macOS settings directly. I was expected a setting directly in the app, like Things or even [version 5 of NetNewsWire](https://netnewswire.com/help/mac/5.1/en/customizing.html). I almost filed another issue. Would be great to have a shortcut!
