### ISSUE TITLE
Are starred entries saved anywhere?

### ISSUE THREAD

**Issue by bladerunnerwalrus** [Ranchero-Software/NetNewsWire#4210]
I had to reset my mac, but kept a backup. I want to recover starred posts, but cannot find their location. Is there a way to recover? Everything was local.

**Comment by brentsimmons** [comment]
You’ll have to go into ~/Library/Containers and find NetNewsWire’s container, then go to Data/Library/Application Support/NetNewsWire/Accounts/

Each account should have a DB.sqlite3 file. You can open it in Terminal using sqlite3 on the command line.

In sqlite3, you can then get the data for your articles with this command:

`select * from articles where articleID in (select articleID from statuses where starred=1);`

It won’t be pretty, but you should be able to copy and paste from Terminal into a text editor and then do something with the data.

Alternately, you could just grab feed URLs, titles, and links, something like this:

`select feedID, uniqueID, title, url, externalURL from articles where articleID in (select articleID from statuses where starred=1);`

I hope this helps! I realize this isn’t at all convenient or easy. But the good news is that the data should all be there in the database.

**Comment by brentsimmons** [comment]
You might see two or more folders named NetNewsWire in the Containers folder. This is a confusing thing macOS does. Only one of those folders if for the app. Just one will have a folder at Data/Library/Application Support/NetNewsWire/Accounts/
