### ISSUE TITLE
[iOS] Missing top image on Reader Views most of the time

### ISSUE THREAD

**Issue by fede777** [Ranchero-Software/NetNewsWire#4213]
Hi, almost every time I use Reader View the top image on an article is missing.

![WhatsApp Image 2024-02-08 at 16 12 05](https://github.com/Ranchero-Software/NetNewsWire/assets/7155112/ee5e2ba3-2583-4ced-a6f4-be7280d46126)

Is this a known issue?

**Comment by brentsimmons** [comment]
The Reader View is a free service supplied by the generous folks at Feedbin — I recommend reporting Reader View bugs to them 👍
