### ISSUE TITLE
Handle rate limiting for openrss.org

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#4224]
Pay attention to 429 status code and the `Retry-After` header.

**Comment by DamonHD** [comment]
My I suggest treating it and Cache-Control max-age the same, to maintain a don't-update-before internal date?

Slow-updating feeds really don't need to be checked every hour if they tell you to cache things or go away for several hours!

And you'll help save some battery life and data charges and carbon emissions for client and server too...  B^>

Rgds

Damon

**Comment by brentsimmons** [comment]
Just added support for Cache-Control in Mac beta: https://github.com/Ranchero-Software/NetNewsWire/releases/tag/mac-6.1.5b3

**Comment by eivindml** [comment]
Hey. Looks like this issue still exists with OpenRSS. My feeds from OpenRSS aren't updating as they should. 

https://openrss.org/issue/54

As they write:

> However, NetNewsWire is still overloading the Open RSS server with requests being made all at the same time across different feeds. Until this issue is addressed per our recommendation to [space out its requests](https://openrss.org/guides/developers-guide-to-open-rss-feeds#space-out-your-requests), the NetNewsWire app continues to hog resources and makes the Open RSS service slow for other users.
>
> To keep the NetNewsWire application from degrading the experience for other Open RSS users, its users are still being automatically blocked from accessing Open RSS feeds.


OpenRSS is a really great organisation that helps to keep RSS alive. I think it would be really great for the community in general to support their feeds.

**Comment by brentsimmons** [comment]
Are you using On My (Mac/iPhone/iPad) or iCloud syncing?

If so: we’ve done all this work and more to be ultra-gentle to OpenRSS servers. What I suspect is that you’re seeing the outcome of that work — those feeds will refresh much less often, because NetNewsWire is refreshing them much less often.

If you’re using Feedbin, Feedly, or other system, then it’s in their hands and not something NetNewsWire can affect.

**Comment by eivindml** [comment]
@brentsimmons I'm using iCloud syncinc.

How much is "much less often"? In my case it's not updating for days.

---

Here is an example of a feed not updating. The url for the podcast, through OpenRSS, is: https://openrss.org/podcasts.apple.com/no/podcast/econtalk/id135066958

The latest episode of that show came out two days ago, on the 17th, but still not showing up in NetNewsWire (see screenshot).

If I open the same feed URL through a random online RSS viewer, we can see that it's able to get the latest episode: https://rss.app/feed/GLbiiF496VpcR7mg?utm_source=rssviewer&utm_medium=website

<img width="1188" alt="Image" src="https://github.com/user-attachments/assets/d88ddd59-7426-4de4-9c3b-b2e45be79e0f" />

Same results when going through the iOS app. Both are updated to latest versions.

---

Another issue, which I suspect is related, is that OpenRSS feeds are not correctly synced between iOS and macOS. 

For instance the show "Trygdekontoret" is missing the latest episode on iOS. It's been like this for two days. Its' missing the episode "Verdensrommet".



<table >
<tr>
<td><img width="430" alt="Image" src="https://github.com/user-attachments/assets/bcb68b6a-711c-467c-8a06-b31c470a13f4" /></td>
<td><img width="1426" alt="Image" src="https://github.com/user-attachments/assets/7d0ac91f-d8d1-473a-acd1-81f3cb7b8514" /></td>
</tr>
</table>

**Comment by brentsimmons** [comment]
“Less often” could mean “for days,” yes.

How many OpenRSS feeds do you have? (The more you have, the less often they will be updated.)

**Comment by eivindml** [comment]
Oh, OK. I have about 15 OpenRSS feeds.
