### ISSUE TITLE
Ask on first launch, whether or not default feeds are desired

### ISSUE THREAD

**Issue by leoheitmannruiz** [Ranchero-Software/NetNewsWire#4225]
Hey, thanks for this awesome feed reader!!

Have you considered asking the user, upon the first launch, whether or not they are interested in default feeds?

Two points come to my mind, as to why I think this would be good:

1. Users who know that they are not interested, don't have to bother deleting them.
2. Users can decide whether or not they want to connect to (at the moment 14) websites. I certainly enjoy programs that connect to other computers only when I ask them to do so.

**Comment by brentsimmons** [comment]
What I like about the current way we do this is that there is zero friction on first run. Launch the app, and a few seconds later there are actual articles to read.

People don’t like having to make decisions, especially on first launch. It causes anxiety. What if I say I don’t want the default feeds — is there a way to try them later? What if I say I do want the default feeds — will they be hard to get rid of?

This way there’s no issue. No first-run anxiety!
