### ISSUE TITLE
iOS: no background refresh for FreshRSS

### ISSUE THREAD

**Issue by drew6017** [Ranchero-Software/NetNewsWire#4236]
I don't think iOS's background refresh frequency is the problem. Gave it more than a day and haven't received a single notification.
Feeds all update instantly when I open the app.

### Steps
- install latest app version
- enable notifications / background-refresh in iOS-settings
- disable `On My Phone`
- add FreshRSS feed
- no change if [Hold]->`Get Info`->`Notify About New Articles` is on for the respective feed

### Specs
- iOS 14.7.1
- iPhone Xs (A12)

**Comment by brentsimmons** [comment]
I suspect it takes a lot more than a day before the system decides to start giving NetNewsWire background refresh time, unfortunately.

**Comment by drew6017** [comment]
Maybe. I haven't noticed it take this long for any other app though. Hence the issue. Anyone else have this?

**Comment by drew6017** [comment]
NetNewsWire background refresh code seems straight out of Apples reference impl., ended up using the tweak `Bakgrunnur` (jailbroken) to force refreshes as months of regular use and iOS still wouldn't do it. I suspect it's because this is an old device, prioritizing battery over all else. Either way, no apparent issue on your part, closing.
