### ISSUE TITLE
Sync with Android

### ISSUE THREAD

**Issue by bladerunnerwalrus** [Ranchero-Software/NetNewsWire#4241]
I know you don't have an app for Android, but do you have any suggestions on how could I access my feeds and starred posts on Android phone? I use iCloud and it syncs perfectly between Mac and iPad, but I usually just use Mac. Sometimes I want to access starred posts from phone and I couldn't find a proper way to do so without switching to another app.

**Comment by brentsimmons** [comment]
Instead of iCloud, you could use another of the syncing systems that NetNewsWire supports, such as Feedbin, Feedly, FreshRSS, and so on.

**Comment by sjehuda** [comment]
@bladerunnerwalrus ticket #4425 might be of interest to you.
