### ISSUE TITLE
NetNewsWire Beta on iOS (17.4) is expired

### ISSUE THREAD

**Issue by psandtner** [Ranchero-Software/NetNewsWire#4245]
Today NetNewsWire Beta on iOS (17.4) is expired. Not shure what to do...

**Comment by brentsimmons** [comment]
You can switch to the App Store release — you won’t lose data.

Hopefully I’ll have a new TestFlight beta within a few days, though.

**Comment by psandtner** [comment]
No problem, I still have a functioning the MacOS version 😉.  Loving NetNewsWire – it's one of my favorite apps... 

Thanks for your great work!
