### ISSUE TITLE
“Feed not found” on seemingly valid URL

### ISSUE THREAD

**Issue by brandonweiss** [Ranchero-Software/NetNewsWire#4258]
I’m adding the feed [https://tonsky.me]() in 6.1.4 using iCloud.

`<link href="/atom.xml" rel="alternate" title="Nikita Prokopov’s blog" type="application/atom+xml">` is in the header and that seems right to me so I’d expect the feed to be found, but it’s not.

Weirdly, when I added the feed URL ([https://tonsky.me/atom.xml]()) manually it also says the feed is not found. It loads just fine for me and I think the headers are right…

<img width="515" alt="Screenshot 2024-04-25 at 2 54 59 PM" src="https://github.com/Ranchero-Software/NetNewsWire/assets/4727/051dd9c2-058d-4402-94fe-638e192cc897">

I can’t figure out if this is a bug or something obvious I’m missing 🤔

**Comment by brandonweiss** [comment]
Oooh, I just tried adding the feed via the iOS app and it worked 🤔 So maybe it’s an issue with the macOS app?

**Comment by brentsimmons** [comment]
Works for me using the Mac app. (Which uses the exact same feed-finding code as the iOS app.) Maybe try again? Could have been a momentary glitch of some kind. Network error or something.

**Comment by brandonweiss** [comment]
Ugh, yep, it works for me now in the Mac app too 🥲
