### ISSUE TITLE
I don't get notifications when the app is closed on macOS.

### ISSUE THREAD

**Issue by YousufSSyed** [Ranchero-Software/NetNewsWire#4260]
Any ideas for troubleshooting this?

**Comment by stuartbreckenridge** [comment]
NetNewsWire uses local notifications (and not push notifications). Therefore it needs to be running on macOS to receive notifications.

**Comment by YousufSSyed** [comment]
@stuartbreckenridge Is there a way to keep running in the background and not have the icon show in my dock?

**Comment by stuartbreckenridge** [comment]
Not to my knowledge.

**Comment by YousufSSyed** [comment]
I just opened an FR for this: https://github.com/Ranchero-Software/NetNewsWire/issues/4261
