### ISSUE TITLE
When syncing, the loading bar stops for a long time and doesn't provide feedback

### ISSUE THREAD

**Issue by jsalvadorcaffarena** [Ranchero-Software/NetNewsWire#4275]
<img width="210" alt="image" src="https://github.com/Ranchero-Software/NetNewsWire/assets/14583691/d1379a18-a2ff-4935-ba4b-e13183fb1c6d">

The app is stuck like the above for several minutes now, in my iPad and iPhone has been like that for more than a day, there is nothing I can apparently do to move past it, no error message and no way to identify which feed is causing the block that I know of.

**Comment by jsalvadorcaffarena** [comment]
Update: Seems to be a problem with using an iCloud account rather with the sites themselves, exported my feeds and imported them to the "on my mac" account and no problems there.

**Comment by brentsimmons** [comment]
This is a known issue with iCloud. We have a page about it: https://netnewswire.com/help/iCloud.html
