### ISSUE TITLE
Can't add feed for The National Post (nationalpost.com)

### ISSUE THREAD

**Issue by dlehman** [Ranchero-Software/NetNewsWire#4276]
I'm trying to add the feed for The National Post (nationalpost.com).
https://nationalpost.com/feed

There appears to be a valid feed at this address, but it gives the old "Feed not found. Can't add a feed because no feed was found" error when I try to add it in NNW.

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fnationalpost.com%2Ffeed%2F

**Comment by markcellus** [comment]
Yeah seems to work when trying it through openrss 

https://openrss.org/nationalpost.com/feed

Probably just has some invalid syntax

**Comment by brentsimmons** [comment]
The server is returning a 403 status code to NetNewsWire. It’s probably a good idea to report it as a bug to the website.
