### ISSUE TITLE
export subscriptions to Feeder (Android RSS App)

### ISSUE THREAD

**Issue by Yolakalemowa** [Ranchero-Software/NetNewsWire#4285]
Hi, 

I love your app and sad to leave, but I started using Android and would love to have my subscipritons imported to Feeder.
Would that be possible?

tysm

**Comment by michaelnordmeyer** [comment]
If only there was an "Export Subscriptions" in NetNewsWire's settings, then Feeder could import those.

**Comment by Yolakalemowa** [comment]
> If only there was an "Export Subscriptions" in NetNewsWire's settings, then Feeder could import those.

I'm a noob sorry.. I just realized my question is stupid. Cause there's an extension that is supported by both, exported then imported successfuly.
thx
