### ISSUE TITLE
Add keyboard shortcut for "Copy Article URL" menu item

### ISSUE THREAD

**Issue by djpowers** [Ranchero-Software/NetNewsWire#4286]
I make regular use of right-clicking an article and selecting the "Copy Article URL" option. I know this is also available under the Edit menu, and I would prefer to use that option if there were a keyboard shortcut associated with it. Currently, there is not one assigned:
![CleanShot 2024-07-26 at 11 09 28@2x](https://github.com/user-attachments/assets/831601a0-b640-4cba-80d6-02faed018d31)

Would it be possible to add one here? My proposal would be to use ⇧⌘C, which feels semantically appropriate as a modification to the default copy action.

If the team is open to this change, I'd be open to doing so if some guidance could be provided on where exactly in the code it should be added.

Thanks!

**Comment by brentsimmons** [comment]
⇧⌘C seems like the right call.

**Comment by timpritlove** [comment]
I totally support this move.
