### ISSUE TITLE
Wrong date parsing

### ISSUE THREAD

**Issue by pharmarin** [Ranchero-Software/NetNewsWire#4344]
When add this feed : [https://www.francetvinfo.fr/titres.rss](https://www.francetvinfo.fr/titres.rss)

Date displayed : 31 Dec 1969 at 22:59 for every item instead of pubDate

**Comment by brentsimmons** [comment]
It’s a bug in the feed. It’s using two-digit years instead of four-digit years in the pubDate field. I recommend letting them know.

https://www.feedvalidator.org/check.cgi?url=https%3A%2F%2Fwww.francetvinfo.fr%2Ftitres.rss

**Comment by pharmarin** [comment]
Thank you for your answer. I thought it worked previously but I must not remember right. Le 1 août 2024 à 18:27, Brent Simmons ***@***.***> a écrit :﻿
It’s a bug in the feed. It’s using two-digit years instead of four-digit years in the pubDate field. I recommend letting them know.
https://www.feedvalidator.org/check.cgi?url=https%3A%2F%2Fwww.francetvinfo.fr%2Ftitres.rss
