### ISSUE TITLE
Can’t add a feed because no feed was found.

### ISSUE THREAD

**Issue by yiranzhimo** [Ranchero-Software/NetNewsWire#4347]
For the RSS link, https://nitter.poast.org/joy_protocol/rss, NetNewsWire shows『Feed not found』error.

But I could follow it through another RSS app.

**Comment by brentsimmons** [comment]
It’s a Nitter bug. It returns a 403 Forbidden and some HTML about verifying your browser.

**Comment by brentsimmons** [comment]
I recommend contacting Nitter and reporting the bug to them.
