### ISSUE TITLE
Desktop notifications don't appear if application is not open

### ISSUE THREAD

**Issue by 101Dude** [Ranchero-Software/NetNewsWire#4354]
Thank you for NetNewsWire!

This may be as intended but may not be or could just be a limitation of the app.

I don't get any desktop notifications unless NewNewsWire.app is running on macOS.
Is there no notification helper.app that can do this?

**Comment by stuartbreckenridge** [comment]
This is as designed. We use local notifications instead of push notifications. On macOS, local notifications require the app to be running.
