### ISSUE TITLE
"Search with Google" context menu item uses Safari instead of system default browser

### ISSUE THREAD

**Issue by teemutammela** [Ranchero-Software/NetNewsWire#4360]
I have set Brave as my default system browser. I have "System Default (Brave Browser)" selected in NetNewsWire's general settings. Yet, when I select a string of text on the reading area, right-click to open the "Search with Google" context menu item, it is opened in Safari.

macOS Ventura 13.6.9
NetNewsWire 6.1.4 (6120)

**Comment by brentsimmons** [comment]
The “Search with Google” menu item is added by Apple, and it’s not something we can alter, unfortunately.
