### ISSUE TITLE
Wrong date on feed (12/31/1969)

### ISSUE THREAD

**Issue by ASLLR** [Ranchero-Software/NetNewsWire#4384]
Hi everyone, 

i'm new user of NetNewsWire and when i import (or add mannually) this rss feed : https://www.francetvinfo.fr/titres.rss 

the date and hour is wrong on app. For all of article, the date is (in DD/MM/YYYY format) 31/12/1969. Do you reproduce ? it is a bug ? 

Thank you in advance,

**Comment by thombet** [comment]
I have the same issue but it seems it comes from a wrong format in the RSS feed, not from a bug in NetNewsWire as explained in #4344

I have sent a mail to the customer service of France TV Info to report the problem.
I think this issue can be closed meanwhile.

**Comment by ASLLR** [comment]
Thank you for the answer i'll wait for France TV :)
