### ISSUE TITLE
dont work on MACOS12. Can it support MACOS12?

### ISSUE THREAD

**Issue by zyw5535** [Ranchero-Software/NetNewsWire#4416]
after 6.1.4, This version of the application "NetNewsWire.app"  does not work with this version of macOS.

**Comment by brentsimmons** [comment]
I hate to disappoint, but we won’t be revising it to work with macOS 12. Supporting older version is a lot of work and testing, and we want to concentrate on fixing bugs and adding new features rather than on supporting older versions of macOS.
