### ISSUE TITLE
Support MacOS 12, Monterey

### ISSUE THREAD

**Issue by AlbatorLaho** [Ranchero-Software/NetNewsWire#4417]
I'm running MacOS 12, Monterey.
I updated from 6.1.4 to 6.1.5 via Brew, and there was nothing saying this new version would be incompatible.
Is there any reason for the OS version bump? Can you lower it back to support macOS 12?

**Comment by brentsimmons** [comment]
I hate to disappoint, but we won’t be revising it to work with macOS 12. Supporting older versions is a lot of work and testing, and we want to concentrate on fixing bugs and adding new features rather than on supporting older versions of macOS.

**Comment by AlbatorLaho** [comment]
That's fair, I may have to fork it and make my own the way I want it... for now I'll just download the old version. 😅
Best of luck! It was a nice product!

**Comment by brentsimmons** [comment]
I don’t know who made the brew cask — I’d like to know, though. How can I find out?

**Comment by AlbatorLaho** [comment]
Well I'm not sure how you'd figure out specifically who made the cask, but I imagine just creating an issue at [homebrew-cask](https://github.com/Homebrew/homebrew-cask) should work fine? (which I could probably do that if you don't have time)
