### ISSUE TITLE
Sync progress inaccurate with FreshRSS (4.1.5 build 6129)

### ISSUE THREAD

**Issue by kyvandoan** [Ranchero-Software/NetNewsWire#4424]
# Bug summary
**The refresh bar does not disappear after all items have been pulled form the server**

# Bug categorization
- Platform tested: iOS (iPhone)
- Type: UI issue
- Regression: ´true´, it did not happen on previous 6.1.5 build 6128

# Environment description
- Platform version: iOS 18.1.1 (22B91)
- NetNewsWire version: 6.1.5 build 6129 (TestFlight)
- Server backend: FreshRSS 1.25.0-dev (edge branch)

# Bug description
## Steps to reproduce
1. In the iOS application, pull down to refresh the feed
2. Wait for the feed refresh to complete

## Expected outcome
- Refresh bar to disappear 
- Replaced by "Last refreshed" + time elapsed label

# Appendix
- Can confirm feed refresh has been completed as connection with the server has been closed accordingly to the logs on the server side. 

# Attachment:
1. Screenshot of NetNewsWire "Today's" view with the refresh bar completed, but still displayed. 

![image](https://github.com/user-attachments/assets/21ea58fb-6693-4734-b68e-f19c786e257a)

**Comment by brentsimmons** [comment]
Possibly fixed by e720d30dc38b08ecb7870f2e2e4a11f81d037e6c — not sure yet.

**Comment by brentsimmons** [comment]
Fixed in ad8c7706d8b6055b7ebc06f4675c9098875bd409.

**Comment by brentsimmons** [comment]
(The fix will probably go out on TestFlight likely on Tuesday night)
