### ISSUE TITLE
Overhaul Data synchronization

### ISSUE THREAD

**Issue by sjehuda** [Ranchero-Software/NetNewsWire#4425]
**Is your feature request related to a problem? Please describe.**
This feature offers synchronization functionality of feeds, entries, read status etc.

**Describe the solution you would like**
Utilize XMPP as a platform for data synchronization.

**Describe alternatives you have considered**
No.

**Additional context**
My name is Schimon, and I am a co-founder of project Blasta.

Blasta is an collaborative annotation management system (i.e. bookmarks manager) which purpose is to make bookmarks accessible from anywhere.

The experiment of Blasta has been successfull and I intend to write an extension the Falkon browser.

I advise to stongly consider to utilize the XMPP platform as a system to synchronize browser data, including bookmarks, history, tabs, cookies, password etc.

Chris:
> XMPP?

Schimon:
> Yes. XMPP, the *Extensible* Messaging and Presence Protocol.

Chris:
> This must be a mistake.

Schimon:
> **There is no mistake!**

Please. Watch the video presentation for the technicalities or visit these resources:
- https://blasta.woodpeckersnest.eu/help/about/xmpp/pubsub
- https://blasta.woodpeckersnest.eu/help/about/xmpp/atomsub

|          |                                                    |
|      --- | ---                                                |
| Code     | https://git.xmpp-it.net/sch/Blasta                 |
| Video    | https://video.xmpp-it.net/w/cfozoUeVLFbBFMCCSCJ1Dn |
| Instance | https://blasta.woodpeckersnest.eu                  |
|          |                                                    |

Resources:
- https://portal.mozz.us/gemini/woodpeckersnest.space/~schapps/journal/2024-11-28-xmpp-for-browsers.gmi
- https://github.com/jarun/buku/discussions/795

**Comment by sjehuda** [comment]
Why was this ticket close?

May you kindly provide a reason for closing this ticket?

**Comment by sjehuda** [comment]
I am sorry. I copy and paste this exact post for various of news readers and browsers.

At the bottom of the article, I have posted a list of projects and progress.

Please. See https://portal.mozz.us/gemini/woodpeckersnest.space/~schapps/journal/2024-11-28-xmpp-for-browsers.gmi

**Comment by sjehuda** [comment]
Brent, may I re-open this ticket?

**Comment by brentsimmons** [comment]
We’re not going to add syncing via XMPP.

**Comment by sjehuda** [comment]
I much appreciate you being candid about it.

Currently, it is only an idea.

I intend to implement such system to an HTML browser, and I hope that
it will gain popularity amongst browsers and news readers, as I believe
that it will be helpful in many cases.

Thank you.
