### ISSUE TITLE
Unhandled error when trying to update feeds

### ISSUE THREAD

**Issue by wcaleb** [Ranchero-Software/NetNewsWire#4434]
I am using version 6.1.4 (Build 6120) on iOS 18.1.1 with an iPhone 13, and earlier this week, I started being unable to update feeds. Whenever I pull down to refresh, I get an error message that says "Unhandled Error," and no feeds update.

**Comment by brentsimmons** [comment]
That’s an iCloud error of some kind. Is your iCloud working fine otherwise?

**Comment by wcaleb** [comment]
That was it. Sorry, I had missed an alert to agree to new iCloud terms. Thank you. On Dec 13, 2024, at 5:25 PM, Brent Simmons ***@***.***> wrote:﻿
That’s an iCloud error of some kind. Is your iCloud working fine otherwise?
