### ISSUE TITLE
NetNewsWire forgets preferred view options and UI states between sessions

### ISSUE THREAD

**Issue by dnptr** [Ranchero-Software/NetNewsWire#4439]
Since the 6.1.7 update, NetNewsWire no longer remembers my preferred view options and UI states between sessions. Whenever the app is launched…
- all sidebar folders are collapsed
- all read feeds are visible
- all read articles are visible

Of course I can simply keep the app running at all times, as it's so wonderfully lean. Still, it's not ideal.

M4, macOS 15.2, syncing via iCloud.

**Comment by annard** [comment]
I have noticed a similar problem on macOS 14.7.2 and MacBook Pro M2.

**Comment by annard** [comment]
When I start it from a Temrinal these are the only messages I see:

```
2024-12-18 11:43:12.499 NetNewsWire[6007:132016] WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:.
2024-12-18 11:43:12.651 NetNewsWire[6007:132016] It's not legal to call -layoutSubtreeIfNeeded on a view which is already being laid out.  If you are implementing the view's -layout method, you can call -[super layout] instead. Break on void _NSDetectedLayoutRecursion(void) to debug.  This will be logged only once.  This may break in the future.
```

**Comment by vincode-io** [comment]
@brentsimmons If you cherry-pick commit 05d2727 it should either fix this problem or get you very close.

**Comment by brentsimmons** [comment]
Just put up a beta to hopefully state restoration — please let me know if it fixes the issues or not:

https://github.com/Ranchero-Software/NetNewsWire/releases/tag/mac-6.1.8b1

**Comment by dnptr** [comment]
With 6.1.8b1, all issues seem to be fixed for me. Thank you so much!

**Comment by annard** [comment]
Hi Brent,

For me this works as well. Thanks for the quick fix!

Best wishes for the holidays,
Annard

**Comment by annard** [comment]
Not sure if this is related but when I (re)started it a few times, it doensn't show the article content. That pane stays black, then applies my theme colour, then black again and nothing happens. Internet connection and all is working because I can open it in a browser and view it there.

**Comment by brentsimmons** [comment]
@annard Would you post a screenshot so I can see what’s happening?

**Comment by annard** [comment]
Hello Brent,

It’s a non-related issue. I don’t know what happened but I tried to start Quicktime Player to make a screen recording and it was bouncing for ever. Then I decided to restart my Mac and bingo everything worked fine. Macs are like PCs nowadays…

So sorry to trouble you. The patch is still fine!

Annard

**Comment by brentsimmons** [comment]
Great! Thanks @annard
