### ISSUE TITLE
Showing All Articles list in the iOS app

### ISSUE THREAD

**Issue by mjeshurun** [Ranchero-Software/NetNewsWire#4441]
Hello friends, 

Is it possible to show an All Articles list in the latest iOS 6.1.5 app? 

Currently, I can only see an All Uread list, and when I Mark All Articles As Read, that list becomes empty. 

Is there a way to show ann All Articles list that includes both unread and read articles? 

Hope someone can help 🙏

**Comment by brentsimmons** [comment]
To be clear — is that you want to see all the articles all at once in a single timeline, both read and unread?

**Comment by mjeshurun** [comment]
Hi Brent, thank you for your answer. 
Yes, that’s what i meant.

**Comment by mjeshurun** [comment]
> If we showed all the articles, it could be many thousands — too many that it would be a performance and memory issue.

Actually it won’t be many thousands, because most RSS aggregators has a settings to delete articles older than X days, or they allow to set a maximum number of articles retention policy.

most RSS reader apps I’ve used have the All Articles list and they aren’t slowed down (at least not in my case). 

I can confirm this with the following iOS apps: Fiery Feeds, Nextcloud News
and with the progressive web app for FreshRSS. 

Personally speaking, I find the All Articles list much more comfortable than having to go to each feed folder and search there for a specific article, because sometimes I don’t remember on which feed I saw an article. I just remember I saw it in the last few days.

**Comment by brentsimmons** [comment]
NetNewsWire also deletes articles automatically. But a person might have a couple thousand feeds, and each one might have 100 articles. This could easily become a problem.

Does the search work for you to find articles you’ve recently seen?

**Comment by mjeshurun** [comment]
Using the search feature is a workaround, but for me, having an All Articles list is still preferable, because it saves the need to go to search, type and then scroll to find the relevant article. 

With the All Articles list I can directly and quickly scroll to find what I’m looking for.

**Comment by mjeshurun** [comment]
Hi Brent, small question. 
Doesn’t NextNewsWire cache downloaded articles for a certain amount of time? 

If that’s the case, then why would showing read and cached articles on the All Articles list slow the sync process of new articles? 

I mean, the read articles are already cached, so the app will only need to download and add the new unread articles, and then show them above the already read and cached articles. 

Am I getting this wrong?
