### ISSUE TITLE
[Bug] if an article is selected, and mark all read done, once the app launch again this article is still here

### ISSUE THREAD

**Issue by JYPochez** [Ranchero-Software/NetNewsWire#4442]
seen on macos.
you're on the "all unread" smart feed, reading the unread articles
once all read you hit "mark all read" and quit the app
if you had one article selected, once you relaunch the app the article is still here, 
but it has been read so it should not be here.

thanks.

**Comment by brentsimmons** [comment]
Here’s the thing — you might still be reading that article! NetNewsWire has no way to know.

**Comment by JYPochez** [comment]
even if I am still reading it, if I am on the "**unread**" smart feed, it is no more **unread**. it should not be there anymore ?

**Comment by brentsimmons** [comment]
The most important thing for NetNewsWire is to remember which article you’re reading! It’s more important than removing read articles.
