### ISSUE TITLE
Images intermittently not loading on MacOS

### ISSUE THREAD

**Issue by tungol** [Ranchero-Software/NetNewsWire#4444]
I've been having a annoying problem with images sometimes not loading for a few minutes at a time.

I have a lot of tumblr RSS feeds that I follow, which I frequently encounter posts that embed multiple large gifs. The problem seems to be related to these. Sometimes these are slow to load. If I wait, generally they'll load and I can continue without issue. If I move to the next item in my feed before the images are loaded, I find that images will not load at all for any post. Going back to the first post which failed to load doesn't help. This continues for a while until it seems like a timeout is reached, and images suddenly start working normally again. I can also fix it by restarting NetNewsWire, but I find that the problem often immediately re-occurs when I do that, so it's not a very good solution.

It feels to me like there's an image loading queue that's getting clogged somehow? But I don't know if that's how the internal architecture of NNW works or not. I'm using the MacOS version 6.1.8, but the problem has been occurring for at least a couple point releases now. I'm not sure when I first noticed it; I want to say not more than 6 months ago and maybe as recently as 1 to 2 months.

Thanks for your consideration, and all the work you do!

**Comment by brentsimmons** [comment]
The image loading in the article views is done entirely by the system — NetNewsWire code doesn’t play a role in it. If this is happening specifically with Tumblr, then it’s most likely a Tumblr issue and, unfortunately, not something we can fix.

**Comment by tungol** [comment]
Interesting. In that case, I think we can close this out. Thanks!
