### ISSUE TITLE
Fix warnings except for CloudKit warning

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#4447]

**Comment by stuartbreckenridge** [comment]
@brentsimmons What warnings? I've done a few clean builds on for the Mac and iOS targets on Xcode 16.1 and it seems to be warning free.

<img width="667" alt="Screenshot 2024-12-30 at 19 57 09" src="https://github.com/user-attachments/assets/02af5fda-d4ba-47c2-9624-1270027cf0b4" />

**Comment by brentsimmons** [comment]
I should have noted that this milestone is being built from the 6.1.6-ios branch. (Added a note to the milestone description.)
