### ISSUE TITLE
Syncing via CloudKit

### ISSUE THREAD

**Issue by graygilmore** [Ranchero-Software/NetNewsWire#491]
I saw this on the roadmap:

> Syncing via CloudKit (maaaaaybe, if feasible)

I would love to see this implemented. I'm creating this issue just to raise some visibility on this and hopefully this issue can get a few +1s to help shape some of the development.

This would be super beneficial for syncing between iOS and macOS apps.

<sup>Feel free to close this issue if it's not an appropriate use case for one</sup>

**Comment by mikewojo** [comment]
Seconded! Been using NetNewsWire at work for a while now and would love to easily sync between my work and home computers via iCloud without relying on a third party service.

**Comment by jeffrey** [comment]
I’ve been reasonably happy with Newsify because it has exactly this feature. I would be thrilled to switch (back!) to NNW if it didn’t require me to set up yet another account.

**Comment by bbsixzz** [comment]
Betamagic News Explorer does this, it's a killer feature.

NNW needs this to stay competitive.

**Comment by bolincho** [comment]
I would also love these. When I read NNW was back I downloaded it and deleted my feedly account. I would love to see this feature or something similary like wifi sync without any third party service.

**Comment by brentsimmons** [comment]
Totally understood. I’ve been trying to nerd-snipe a friend of mine (who’s an amazing developer) into taking this on. :)

But here’s the issue: we don’t actually know if CloudKit would work very well for this. Syncing subscriptions is fine, but syncing read/unread/starred status means a whole ton of small records — and I just don’t know if CloudKit is up to doing this well, reliably, and quickly. So it will mean exploratory programming, with a possible this-won’t-work end state.

**Comment by bbsixzz** [comment]
>…we don’t actually know if CloudKit would work very well for this. Syncing subscriptions is fine, but syncing read/unread/starred status means a whole ton of small records — and I just don’t know if CloudKit is up to doing this well, reliably, and quickly.

News Explorer does this already, you can download it and try it yourself.

**Comment by brentsimmons** [comment]
That News Explorer does this is encouraging, but it doesn’t tell us if there are limits, or how it fails when it fails, or what performance is like. It still means exploratory programming, where syncing with other systems is pretty much guaranteed to be do-able.

**Comment by bbsixzz** [comment]
Please don't take this the wrong way; that sounds very defensive and presumptive when you can just test the app and see that it neither fails nor lacks in performance. CloudKit has proved itself more than capable, free users from the shackles of third party sync services.

**Comment by brentsimmons** [comment]
I _am_ taking this the wrong way, I suppose — because I can’t help but do so. You called my comments “defensive and presumptive” when they are honest comments made in good faith by a software developer with decades of experience in the Apple ecosystem.

I also took “NNW needs this to stay competitive” the wrong way, too, because that’s the kind of thing you say to a developer who you think can be manipulated. That’s definitely not me.

**Comment by bbsixzz** [comment]
You're still deflecting, CloudKit sync is possible and has been proven by others.

…decades of experience, yet all you talk about are limits, failings, and performance issues.

I read your post, "working on this is a risk" pretty much sums it up. I've seen NNW go through its ups and downs over the years, I'm sure you don't want it ending up as an also-ran with the rest of the vanilla readers out there. That's why I laid it on thick with CloudKit, I have better things to do than to "manipulate" well-intentioned developers giving away their hard work for free.

I'm sorry if I rustled your feathers, they say pride comes before the fall.

**Comment by adamprocter** [comment]
It’s pretty clear CloudKit Sync it’s doable but I agree that firstly sync for other RSS services such as Fever etc. would encourage new adoption. So I think CloudKit is a low priority at this time. First thing is to get the iOS app working and add one sync service at a time.

**Comment by boxed** [comment]
@bbsixzz do you have apple stock or are you on the iCloud team or something? Why are you so terribly agreessive and defensive of iCloud? 

I know that iCloud sync still has one photo in my wives Photos library that it has marked as "cannot sync" for years. Literally years. iCloud isn't perfect.

**Comment by bbsixzz** [comment]
@boxed  

Straw man fallacy.

@adamprocter 

Fever would be great, never said Brent should have done CloutKit in version 1.0

Can we all just hug now?

**Comment by adamprocter** [comment]
Hugs all good 
So I’m gonna try and get this issue back on track. 

CloudKit sync would be great especially with an iOS app coming this is natively supported. 

Can CloudKit do all the required needs. This is unknown. One app has implemented what appears to be a similar use case but without seeing the source or talking to the developer it’s difficult to evaluate. We all know Sync is hard to do well and I like many have avoided CloudKit / iCloud for a long time as Apple have been terrible at this stuff. But it’s certainly maturing. iOS 13 and Catalina may also bring more positive changes. 

Any sync service needs to be evaluated and tested and it will have a major impact on performance if implemented in the wrong way or is just not suited for the platforms of choice. I am Currently puzzling over a PouchDB -> CouchDB situation on my own project. 

I have used CloudKit once for reminders and it was odd you had to use the Calendar part of it to access the storage for reminders  which was odd. 

I don’t know how the feedly implementation worked but if the sync “engine” can be modular then work could be done on many services by the community. 

I would love CloudKit sync. And I am not buying any 3rd party paid solution. I have a Fever server setup but Fever is no longer updated. With both of these I trust the owner myself or Apple.

**Comment by Thomas-U** [comment]
My 2 cents: Right now on my devices iCloud-Sync does not work reliably with these Apple-Apps:
Contacts, Calendars, Notifications. Time and again suddenly duplicates appear out of the blue: Double contacts, calendar-entries, notifications. Apple Support‘s only advice: Switch off iCloud sync on all devices, fresh setup of iOS on Phone and iPad, manage/erase duplicates on the Mac side, switch sync on again. It helps for a couple of hours - then same shit again.
Last time I spoke to support they told me they would discuss it on the developer level and get back to me. That was more than 2 months ago.
With this I just want to make the point that if something works for a lot of people it does not mean that it is flawless.
And I would love iCloud sync too - especially if it worked reliably.

**Comment by adamprocter** [comment]
I know a number of apps such as Ulysses do a good job in using CloudKit and they have complicated stuff going on. They did also have there own Sync thing before and moved to CloudKit 

Bear I believe uses CloudKit as well. 

But again without talking to those devs it’s all about implementation. Like you say mind Apple don’t seem to get it quiet right 😂

John Siracusa has pointed out the fact that contacts don’t sync properly and he still has to occasionally do the iCloud dance. 

I have found this is becoming less of an issue myself over the last couple of years. 

But when sync doesn’t work and with CloudKit the user can see anything that’s going on anywhere, hence the turn off and on dance, it’s real hell.

**Comment by nickgravelyn** [comment]
I’d love this feature but News Explorer definitely gets it wrong a lot for me. I change my starred articles on iPad and it fails to change on iOS. No amount of pulling down changes anything. It just gets out of sync for a while. 

I would love to see this in NetNewsWire but I also know that it’s likely a tricky thing to get right. It also isn’t quite as important until an iOS app shows up. 

Best of luck to the devs on the app. I’m glad to see more RSS apps in the world.

**Comment by bbsixzz** [comment]
While we're sharing anecdotes, News Explorer has worked great for me since release.

Also, this: [Managing background tasks with the new Task Scheduler in iOS 13](https://medium.com/snowdog-labs/managing-background-tasks-with-new-task-scheduler-in-ios-13-aaabdac0d95b)

Great for improving sync and battery life in iOS 13.

**Comment by josherrickson** [comment]
Sorry to bump an old issue, but what about CloudKit sync just for list of feeds? I realize it wouldn’t be useful for actively switching between two devices, but it would a) provide security that your list of feeds is backed up in case anything happens to your device, and b) makes replacing your phone/Mac much easier.  While of course using a 3rd party does this as well (and arguably better), I for one would prefer to see an all-Apple solution.

**Comment by kabouzeid** [comment]
Agreed, I would also love to see this.

**Comment by vincode-io** [comment]
Yep, I am literally working on CloudKit sync as we speak.  As usual, no ETA's.  https://inessential.com/2019/10/28/no_etas

**Comment by bbsixzz** [comment]
Looking forward to testing this.

**Comment by vincode-io** [comment]
This has been completed and will be part of the 6.0 release.

**Comment by graygilmore** [comment]
Thank you so much! Can't wait to utilize it 😄

**Comment by bbsixzz** [comment]
I just want to thank you for a wonderful app, I've been testing the betas and iCloud sync has been working great.

I ditched the other app a long time ago, yours is much leaner and faster on my trusty iPhone SE.

Great job, what a crazy journey NetNewsWire has had.

The future looks bright :]


P.S.

I'm sorry if I offended anyone.
