### ISSUE TITLE
Alt text not displayed in main window

### ISSUE THREAD

**Issue by westy48** [Ranchero-Software/NetNewsWire#492]
Hi Brent - thanks for your work on NNW!

I can't see the very important alt text in [XKCD](https://xkcd.com/) unless I open the comic in an external browser.

Thanks,

James

**Comment by westy48** [comment]
Seems to work now so I'l close this - not sure why I wasn't seeing it before.

Thanks again.

James

**Comment by matveyp** [comment]
Problem remains and seems to be related to double quotes. See https://xkcd.com/2100/ - the alt text stops with the word "his." Interestingly, if the alt text begins with the double quote, it seems to work fine - see https://xkcd.com/2101/

**Comment by brentsimmons** [comment]
What’s the URL of the feed? There are multiple feeds, and knowing which one is the problem would be very helpful.

(Unfortunately, the item you reference has fallen out of both the xkcd.com feeds.)

**Comment by westy48** [comment]
http://xkcd.com/rss.xml is the feed I'm viewing in NetNewsWire

**Comment by matveyp** [comment]
http://xkcd.com/atom.xml

**Comment by brentsimmons** [comment]
I have yet to be able to reproduce this.

**Comment by afragen** [comment]
Unfortunately I still see this using the feed from https://xkcd.com/rss.xml

This is in the iOS app. The alt text isn’t viewable from NNW 😢

**Comment by brentsimmons** [comment]
What happens if you tap the image?

**Comment by afragen** [comment]
![B8F953DA-18E9-4E39-AFC6-2E309153FEEE](https://user-images.githubusercontent.com/1296790/72195158-f8904600-33c5-11ea-85d5-e49bcc6ae463.png)

**Comment by brentsimmons** [comment]
What if you just tap it instead of long-press?

**Comment by afragen** [comment]
Thank you. Unfortunately I became used to how it works on the site with a long press. Tap works great! 

Thanks Brent and I must say I’m really enjoying NNW again.

**Comment by brentsimmons** [comment]
Thanks!
