### ISSUE TITLE
Command-key to toggle Open in Background preference

### ISSUE THREAD

**Issue by peternlewis** [Ranchero-Software/NetNewsWire#559]
It would be nice if clicking a web link with the command-key toggled the Open in Background setting (so clicking the link could open in normally, and command-clicking could open it in the background).

**Comment by brentsimmons** [comment]
Good point. I wonder if the callback API tells me anything about modifier keys. (I suppose I could inspect the current NSEvent.)

**Comment by peternlewis** [comment]
I suspect it would be safe enough to just use NSEvent.  It's unlikely to be that time critical.

**Comment by Wevah** [comment]
This should be fixed in #2100 (for Mac 5.1); feel free to reopen if it's not.
