### ISSUE TITLE
There should be an Open in Browser in Background menu variant

### ISSUE THREAD

**Issue by peternlewis** [Ranchero-Software/NetNewsWire#561]
There should be an Open in Browser in Background menu variant, perhaps ⌘⇧Right Arrow?

**Comment by peternlewis** [comment]
The shift-key behaviour should be toggled by the Open in Background preference.

**Comment by AJK18** [comment]
I prefer the old method - it was a setting, and then it would let me just open in the background, as I prefer

**Comment by JayBrown** [comment]
In Vienna it's a setting: "Open links in external browser" plus "Open new links in the background", which is very helpful, and it would be my preferred solution for NNW.

**Comment by brentsimmons** [comment]
Note: this is done on master.
