### ISSUE TITLE
Right arrow when a closed folder is selected should open it

### ISSUE THREAD

**Issue by juandesant** [Ranchero-Software/NetNewsWire#574]
Currently, if an RSS source is selected, typing the left arrow key closes the folder. However, if a closed folder is selected, typing the right arrow key does not open the folder, and somehow changes the focus status.

**Comment by spodick** [comment]
+1 for this - I love that I can left arrow to go to a higher-level folder, then left again to close the folder.  Right arrow to open the closed folder selected makes so much sense.

Compounded by open folders not being reopened when NNW is relaunched (all folders closed on relaunch when I would prefer some always open - should I enter that as a separate request?).

**Comment by ptsgmartins** [comment]
Was just looking for this.
Actually, as far as I could tell there is no way to open a folder with the keyboard, which is its own problem...
Since there is even a "New Folder" button encouraging the user to create folders, there should a key for opening them.

**Comment by brentsimmons** [comment]
You can use the . key or option-rightArrow. See Help > Keyboard Shortcuts for more.
