### ISSUE TITLE
Double item listings are unclear

### ISSUE THREAD

**Issue by jdlewin** [Ranchero-Software/NetNewsWire#671]
Likely an edge case, but when there are two entries in the OPML, the item list render is unclear (in this case, the top entry comes from the OPML root and the bottom entry from within a directory). It may be helpful for new users to render the subscription path, e.g. Tech > Manton.

<img width="456" alt="Screen Shot 2019-05-21 at 17 12 24 " src="https://user-images.githubusercontent.com/19195907/58131652-36e5b480-7bed-11e9-96cb-af2ac8819d37.png">

**Comment by brentsimmons** [comment]
Adding the folder name would add clutter that most people wouldn’t find valuable, I believe.

We do have a command, in the contextual menu for the timeline, to select the feed in the sidebar, which can help when there are cases like this.
