### ISSUE TITLE
Feedbin: Twitter videos are very small in the article view

### ISSUE THREAD

**Issue by aaronraimist** [Ranchero-Software/NetNewsWire#718]
![Screen Shot 2019-05-29 at 8 28 58 AM](https://user-images.githubusercontent.com/5855073/58560987-cf7ec480-81eb-11e9-8dde-392eb1f1263a.png)

**Comment by brentsimmons** [comment]
Do you have the URL of a feed that does this?

**Comment by aaronraimist** [comment]
I don't know what the actual feed URL is, I believe it is hidden away by this Feedbin feature https://feedbin.com/blog/2018/01/11/feedbin-is-the-best-way-to-read-twitter/

but if you have a Feedbin account and you type in `https://twitter.com/gruber` there are examples of this

https://twitter.com/gruber/status/1136809273349083136 tweet shows no image/video even though there is a video attached to the tweet

![Screen Shot 2019-06-07 at 1 08 20 PM](https://user-images.githubusercontent.com/5855073/59124478-5424bd80-8925-11e9-98f0-50b0c64ac842.png)

This tweet shows it very small https://twitter.com/gruber/status/1136769176956260358
![Screen Shot 2019-06-07 at 1 07 48 PM](https://user-images.githubusercontent.com/5855073/59124453-40795700-8925-11e9-8fbf-c2964cb830d5.png)

In Feedbin they both show up fine:
![Screen Shot 2019-06-07 at 1 09 14 PM](https://user-images.githubusercontent.com/5855073/59124516-7ddde480-8925-11e9-9706-a842e66401de.png)
![Screen Shot 2019-06-07 at 1 09 21 PM](https://user-images.githubusercontent.com/5855073/59124511-78809a00-8925-11e9-8edd-30e89669e5c2.png)

**Comment by thatguygriff** [comment]
@brentsimmons I have been experiencing this behaviour on macOS and in the iOS Test Flight. I was going to submit it as an issue but figured I would share my findings when I went to collect details on the issue.

Like with @aaronraimist it isn't on a public feed, but Twitter feeds through Feedbin. I captured the raw HTML from the FeedBin API for a recent post from the `@penguins` twitter account.

```
    <div class="feedbin--wrap">
        <p class="feedbin--content-text">Any bold predictions for tonight's righteous rumble?</p>
            <p class="feedbin--media-wrap">
                    <video poster="https://pbs.twimg.com/media/ENTOQz_XYAENPVj.jpg:large" width="16" height="9" src="https://video.twimg.com/amplify_video/1212819035664060416/vid/1280x720/5FhNjM1i7t2tp7lA.mp4?tag=13"></video>
            </p>
    </div>
```

FeedBin is setting the width and height to be `16` and `9`. It would appear that NNW is simply respecting those dimensions when rendering the `<video>` tag.

**Comment by vincode-io** [comment]
@benubois is this something you would look into for us?  See the above comment.  Is there something we can do to make these Feedbin/Twitter videos larger and playable?

**Comment by benubois** [comment]
I can no longer build NetNewsWire locally due to code signing issues, but I think it would be best for NetNewsWire to not trust the size on any incoming video tag, and instead make them responsive to the viewport size. 

On a video tag a CSS rule like this will accomplish this:

```css
video {
    width: 100% !important;
    height: auto !important;
}
```

**Comment by vincode-io** [comment]
Good point on the video tag. I’ll make the change. 

Let us known if there is anything we can do to help with the code signing issues.

**Comment by thatguygriff** [comment]
The other thing I have noticed with a few videos in the last week is that even if they are large enough to see you cannot start playing them on iOS. On macOS I can right click and choose play. 

NetNewsWire probably shouldn't rely on the `<video>` element having `controls` attribute set to show playback controls.

**Comment by vincode-io** [comment]
@thatguygriff So weird that you commented just now.  I literally fixed the controls bug and came here to get the issue number to add to the commit, right this moment.

**Comment by vincode-io** [comment]
Another bug bites the dust.  Look for this in an upcoming release.

**Comment by uncleungie** [comment]
This issue has popped up again. Twitter videos from Feedbin subscriptions are very small in the article view on both iOS and macOS.

The tiny box beneath the text is the video. Most videos in Feedbin twitter feeds are unusably small.

![IMG_2468](https://user-images.githubusercontent.com/4439121/116829842-43623e00-ab74-11eb-8d71-e9f105b861fb.PNG)
