### ISSUE TITLE
Fever support

### ISSUE THREAD

**Issue by cortig** [Ranchero-Software/NetNewsWire#76]
I know online services are not yet supported, but in your list of services that will be supported in the future I’d love to see Fever…

**Comment by dewey** [comment]
That would be great, a lot of self-hosted feed readers like https://miniflux.app use it to support third party clients like Reeder.

**Comment by hyakugei** [comment]
FYI api documentation -- https://feedafever.com/api

**Comment by cansurmeli** [comment]
Can we get some feedback from the developers regarding this matter please! Are they working on this or do they even plan to work on this.

I really want to make use of NetNewesWire but it having no support for Fever makes it impossible for me to use.

Some background from my side on this subject:

I'm making use of TT-RSS. I prefer to host my own RSS service. I try to minimise my dependencies. Paid services are here one day and not the other.

Looking at NetNewsWire's source options, I realised that Feedbin can also be self-hosted but I've a pretty solid system running on TT-RSS at the moment and don't want to move it unless I really have to.

TT-RSS, by itself is close to outside readers but a plugin simulates Fever and then it becomes broadcastable.

Thanks.

**Comment by brentsimmons** [comment]
Right now we’re working on Feedly syncing.

We’d like to support all of the various syncing systems, but we can’t guarantee that we’ll cover every single one. In part it depends on people showing up to volunteer to work on a particular system.

**Comment by steakscience** [comment]
I think if any dev wants to add Fever support, it shouldn't be too much work. NNW is opensource anyway!

**Comment by brentsimmons** [comment]
We’d love it if somebody wants to volunteer to add Fever support!

**Comment by cansurmeli** [comment]
Oh, yeah, sorry. Actually it's my bad.

I'm going to contribute; should've written something here.

It's just that I can take a crack at it after two weeks or so. I'm extremely busy at the moment.

**Comment by kenokenobingo** [comment]
It’d be nice to have Miniflux supported if this is possible.

**Comment by kaiwei** [comment]
Another vote for Fever API support!

**Comment by iPFT** [comment]
Hey everyone. I uploaded my Pythonista script for the Fever API here: https://github.com/iPFT/Feverista

I'm not an iOS dev and have only been working on something that works in Pythonista. I have had some basic success converting it to swift (authenticating and downloading from the api) but would have no clue how to incorporate it into the NetNewsWire as I've built it into a SQLite database. So if anyone else wants to build on it, then feel free.

**Comment by dumprop** [comment]
Any progress? Im ready to test

**Comment by cansurmeli** [comment]
Hello.

I'm terribly sorry. I got caught up with my master's studies and couldn't look into this project.

I also need this functionality. I might be able to come up with something in the coming weeks but not making any promises.

**Comment by brentsimmons** [comment]
Our current thinking on Fever: we’ll consider adding support some time after NetNewsWire 6.0 ships.

**Comment by cortig** [comment]
> On Feb 15, 2021, at 18:40, Brent Simmons <notifications@github.com> wrote:
> 
> Our current thinking on Fever: we’ll consider adding support some time after NetNewsWire 6.0 ships.


Thanks a million for letting us know Brent. I can’t wait :-)

Corentin

**Comment by brentsimmons** [comment]
To be clear — we’ll consider it. There are significant downsides to supporting self-hosted RSS readers, and those downsides are all the larger given that Fever itself has no support. If something goes wrong, we’ll probably get a bug report, and then spend n hours tracking it down, only to find it’s an issue with Fever or with that instance of Fever. This is a terrible use of our limited time. It means we’re not moving the app forward for everybody when we’re dealing with that issue.

But, that said, we have a bias toward supporting all the various systems. We lean toward yes. But we won’t think more about it till after we ship 6.0.

**Comment by jamespo** [comment]
Another benefit of this would be there is a fever plugin for tt-rss (https://github.com/DigitalDJ/tinytinyrss-fever-plugin), so this would add tt-rss syncing as well

**Comment by boggydigital** [comment]
That's not really adding much to Fever API, but I wanted to point folks who use Miniflux and want Fever API because of it to the steps to get NetNewsWire working with new Google Reader API in Miniflux (added in 2.0.35): https://github.com/Ranchero-Software/NetNewsWire/issues/2859#issuecomment-1019066748

**Comment by i-iooi-i** [comment]
> Our current thinking on Fever: we’ll consider adding support some time after NetNewsWire 6.0 ships.

I'm looking forward to it very much. I'll always pay attention to it. Come on!

**Comment by vincode-io** [comment]
Are there any other RSS aggregators still using Fever besides Miniflux? Since Minuflux has added support for th Google Reader API, we might not have any reason to support Fever.

**Comment by brentsimmons** [comment]
I know it’s disappointing, but it’s unlikely we’ll ever support Fever. It’s been discontinued for years, and its user base is shrinking. It makes sense for us to spend our time on things that will benefit way more of our users (localization, smart feeds, etc. etc.)

**Comment by mrzool** [comment]
> I know it’s disappointing, but it’s unlikely we’ll ever support Fever.

Now that I can use NetNewsWire with Miniflux via the Google Reader API this issue has lost relevance to me. I'm a very happy NetNewsWire user now.

**Comment by dewey** [comment]
Same, I updated the [second comment in that issue ](https://github.com/Ranchero-Software/NetNewsWire/issues/76#issuecomment-520923832)asking for it because of Miniflux to reflect that. I'm also not interested in Fever support any more at this point. The Google Reader API is the better solution.

**Comment by vincode-io** [comment]
We don't have any plans to implement this feature since it has been superseded by Google Reqder API support in Miniflux.
