### ISSUE TITLE
Odd view of pref > accounts

### ISSUE THREAD

**Issue by adamprocter** [Ranchero-Software/NetNewsWire#764]
I found it a little odd first time recently I looked in the preference > accounts the right side has the 2 options...which is the add account mode (image 1) ... but as I have an account already I would like the info view to be the default view personally (image 2)

IMAGE 1
<img width="534" alt="Screenshot 2019-06-18 12 59 00" src="https://user-images.githubusercontent.com/123951/59680401-23684200-91c9-11e9-9e13-67de234aa729.png">
 
IMAGE 2
<img width="536" alt="Screenshot 2019-06-18 13 02 13" src="https://user-images.githubusercontent.com/123951/59680475-514d8680-91c9-11e9-8c9d-9f7d2a4252c5.png">

**Comment by adamprocter** [comment]
Also I think the default ui pattern for an add account action is a fold out sheet?

<img width="564" alt="Screenshot 2019-06-18 13 03 54" src="https://user-images.githubusercontent.com/123951/59680578-940f5e80-91c9-11e9-992f-576324353702.png">

**Comment by brentsimmons** [comment]
We did revise this UI (though not exactly as requested).
