### ISSUE TITLE
BazQux: Syncing

### ISSUE THREAD

**Issue by vincode-io** [Ranchero-Software/NetNewsWire#777]
Service: https://bazqux.com

API Documentation: https://github.com/bazqux/bazqux-api

Bazqux uses the Google Reader API.  We have this implemented as ReaderAPI and it is currently being used with FreshRSS.

Ideally we would make the ReaderAPI implementation work with minimal changes and minimal checking of the AccountType.  We don't want to break FreshRSS.  If things start getting to convoluted in the ReaderAPI we should copy it to its own implementation for Bazqux.

**Comment by WanderingStar** [comment]
I'm happy to test this.

**Comment by aredridel** [comment]
Same.

**Comment by rodalpho** [comment]
Really surprised NNW doesn't support Bazqux, as it uses the Google Reader API. This is the first RSS app I've run across that doesn't support it, and I've tried them _all._

**Comment by brentsimmons** [comment]
It’s because this is a new app, despite the version number, and we prioritized Feedbin and Feedly first.

**Comment by rodalpho** [comment]
Ahh that explains it. Most RSS apps have been around for a very long time now.

**Comment by odinian** [comment]
> Ahh that explains it. Most RSS apps have been around for a very long time now, in one form or another.

Well, NNW has been around, in one form or another, since 2002. :-)

I too would like BazQux support.

**Comment by brentsimmons** [comment]
It’s a unique situation. While NetNewsWire has been around since 2002, NetNewsWire 5 is nevertheless a brand-new app.

It started out life as an app named Evergreen. We changed the name to NetNewsWire when we got the name back from Black Pixel.

But, under the hood, it really is a 1.0 app!

I know that’s confusing, but that’s the situation.

**Comment by rodalpho** [comment]
No problem, perfectly understandable. Thanks for resurrecting the app, I look forward to trying it out when Bazqux is supported!

**Comment by vincode-io** [comment]
This has been implemented and is scheduled to be part of the 6.0 NetNewsWire release.  Watch the NetNewsWire News blog because we will be announcing test versions of NetNewsWire 6.0 and really need some help testing this sync service.
