### ISSUE TITLE
TheOldReader: Syncing

### ISSUE THREAD

**Issue by vincode-io** [Ranchero-Software/NetNewsWire#778]
Service: https://theoldreader.com

API Documentation: https://github.com/theoldreader/api

TheOldReader uses the Google Reader API. We have this implemented as ReaderAPI and it is currently being used with FreshRSS.

Ideally we would make the ReaderAPI implementation work with minimal changes and minimal checking of the AccountType. We don't want to break FreshRSS. If things start getting to convoluted in the ReaderAPI we should copy it to its own implementation for TheOldReader.

**Comment by y0y0z** [comment]
@brentsimmons: could you please share your time estimation for releasing version 5.2 alpha?

**Comment by brentsimmons** [comment]
Any time estimation I might come up with would be a complete wild guess, and would probably be wrong in some direction by several months. Sorry about that!

**Comment by vincode-io** [comment]
This has been implemented and is scheduled to be part of the 6.0 NetNewsWire release.  Watch the NetNewsWire News blog because we will be announcing test versions of NetNewsWire 6.0 and really need some help testing this sync service.
