### ISSUE TITLE
Feature request: restore folder expansion state on launch

### ISSUE THREAD

**Issue by ucbsm** [Ranchero-Software/NetNewsWire#795]
If "Folders" are expanded upon application Quit, would be nice if they remained expanded upon app relaunch...

**Comment by HillbillyInBC** [comment]
Seconded. Yet another missing feed organization feature that will keep me on NNW4.

**Comment by ssgelm** [comment]
Yes please!  This one is driving me crazy. :)

**Comment by macdaddy1944** [comment]
Second this request. I haven't gone back to 4 yet but having to expand each folder every time I launch the app is a major waste of time.

**Comment by dkocher** [comment]
Duplicate for #562.

**Comment by vincode-io** [comment]
I'm closing this as a duplicate of #562.
