### ISSUE TITLE
Feature request: traditional view for timeline and article

### ISSUE THREAD

**Issue by ucbsm** [Ranchero-Software/NetNewsWire#796]
Hoping "Layout" option(s) might be implemented, as in NNW3. (as in attached screenshot)

![Screen Shot 2019-07-07 at 10 41 22 AM](https://user-images.githubusercontent.com/52629457/60769964-fb6f4e80-a0a3-11e9-9b93-994015233e99.png)

**Comment by timmerk** [comment]
Seconded - the "Traditional View" in NNW3 is one of the main reasons I still use it over the other Mac RSS readers out there.

**Comment by JayBrown** [comment]
Definitely second that. If you implement this, I'll leave my **[Vienna](https://github.com/ViennaRSS/vienna-rss)** exile and return to NNW.

**Comment by chicagobob** [comment]
Ditto.  Came here to search open issues just looking for this one.  Even though I'm already sold on NNW5, this would be really great IMHO.

**Comment by noahkuhn** [comment]
+1 Yes, this is necessary.

**Comment by tompave** [comment]
+1

The usability of a layout is highly subjective. The current 3 column "modern" one is not the best for everyone.

**Comment by tompave** [comment]
Actually, I think that this is a duplicate of https://github.com/brentsimmons/NetNewsWire/issues/102.

**Comment by vincode-io** [comment]
Duplicate of #102.
