### ISSUE TITLE
"make new feed" AppleScript doesn't return a valid object specifier

### ISSUE THREAD

**Issue by olofhellman** [Ranchero-Software/NetNewsWire#799]
Something seems to have changed in creating a feed, so that when 
   handleCreateElement(command:NSCreateCommand)
in Feed+Scriptability.swift is called, the newly created feed can't make a valid objectSpecifier.

So, when running a script like 

    tell application "NetNewsWire"
	make new feed with data "https://boingboing.net/feed"
    end tell

the feed does get created (that's good!), but the result returned from the script is invalid (that's not good)

The error in Script Editor is:
  error "NetNewsWire got an error: Can’t make application \"NetNewsWire\" into type specifier."

**Comment by Wevah** [comment]
It looks like it doesnt like it when you don't tell it what account to create the new feed in. It works for me if I do

```applescript
tell application "NetNewsWire"
    make new feed with data "https://boingboing.net/feed" at account id "OnMyMac"
end tell
```

**Comment by Wevah** [comment]
Seems that it should be defaulting to "OnMyMac" if no account is specified, though?

**Comment by olofhellman** [comment]
Wevah -- I think you've found the wrinkle that's the source of the problem -- at some point there's a need to default to 'account "OnMyMac"' if no account is specified when making or resolving the object specifier.  Maybe ScriptableFeed objects created in NSApplication+Scriptability's 'func feeds()' should use a ScriptableAccoutn object for the container instead of 'self'.  I will experiment with this tonight.

**Comment by Wevah** [comment]
Reading the code, it looks like that's what it does (defaults to "OnMyMac"), but Script Editor/the running app is still trying to resolve `application "NetNewsWire"`, for some reason? I could be mistaken, though.

**Comment by brentsimmons** [comment]
I fixed the crash where a feed already existed.

But I can’t figure out the error where the account is not specified. I *think* this is an AppleScript system bug, not our bug.

I’m comfortable telling scripters that they have to specify an account.
