### ISSUE TITLE
Darkmode selection hides disclosure and gear in sidebar

### ISSUE THREAD

**Issue by vincode-io** [Ranchero-Software/NetNewsWire#846]
When selecting a smartfeed in the sidebar the gear is hidden.  It should probably be switched to a white color so that it is visible.
![Screen Shot 2019-08-14 at 8 01 07 PM](https://user-images.githubusercontent.com/16448027/63066256-cc33d480-bece-11e9-814a-ac467e0e6c61.png)
The same is true of the disclosure arrow when a folder is selected.
![Screen Shot 2019-08-14 at 8 00 44 PM](https://user-images.githubusercontent.com/16448027/63066290-f2f20b00-bece-11e9-82c1-c68339afbcd1.png)

Testing was done using NNW 5.0b4 on macOS Catalina.

**Comment by vincode-io** [comment]
I should also note that this only happens when using the graphite accent color.

**Comment by brentsimmons** [comment]
Great catch!

**Comment by brentsimmons** [comment]
This is not true in the current shipping macOS, so I’m punting this to 5.0.1.

**Comment by brentsimmons** [comment]
Since Catalina is a moving target and likely not to ship until October, I’m punting on this one till we get closer to the macOS ship date. (By which time it may not be a bug.)

**Comment by brentsimmons** [comment]
Looks like Apple fixed this at some point.

**Comment by brentsimmons** [comment]
Oh, no, wait. They didn’t. I forgot this was just with graphite.

**Comment by brentsimmons** [comment]
We should file a bug with Apple.
