### ISSUE TITLE
Feature request: Faster refresh feed intervals (less than 10 minutes)

### ISSUE THREAD

**Issue by UnderEu** [Ranchero-Software/NetNewsWire#882]
One of the features I really prefer in other readers/services is this option which feeds updates quicker than NNW since always (as I can remember).
It would be nice to see quicker options rather than "Every 10 minutes" at minimum.

![Screen Shot 2019-08-27 at 10 29 37](https://user-images.githubusercontent.com/16519758/63775391-9cfd6a00-c8b5-11e9-9e67-a2bf50d88747.png)
![Screen Shot 2019-08-27 at 10 29 06](https://user-images.githubusercontent.com/16519758/63775396-9ec72d80-c8b5-11e9-8819-78c750a80bf0.png)

**Comment by UnderEu** [comment]
Asking for new features became irrelevant due to a stupid decision to get rid of development for proper macOS versions

**Comment by brentsimmons** [comment]
I don’t understand — what do you mean by “get rid of development for proper macOS versions”?

**Comment by brentsimmons** [comment]
Never mind — you made your point in a separate bug.
