### ISSUE TITLE
Link netnewswireapp.com to ranchero.com

### ISSUE THREAD

**Issue by JohannesWarn** [Ranchero-Software/NetNewsWire#883]
http://netnewswireapp.com is one of the first hits for NetNewsWire on Google and DuckDuckGo. The webpage links to the announcements from 2018. Finding your way to the version 5 download from there is quite hard.

It would be good to have a link directly to https://ranchero.com/netnewswire/ (or possibly a redirect?).

**Comment by JohannesWarn** [comment]
Intermediate solution could be to put a link at the top of [your announcement](https://inessential.com/2018/08/31/netnewswire_comes_home).

**Comment by brentsimmons** [comment]
Moved to the 5.x milestone because we can’t get in a position where this is holding us up.

**Comment by felibb** [comment]
Polite bump because the first result in DDG search for "netnewswire" confused me today.

**Comment by brentsimmons** [comment]
I wish there was more we could do. We’re just waiting. It’s out of our control.

**Comment by brentsimmons** [comment]
I can’t even get them to take down the current netnewswireapp.com website.Sigh.

**Comment by brentsimmons** [comment]
Just sent email to the owner. Let’s see if we can get this done.

Looks like it’s not nearly as important as it used to be — netnewswire.com seems to be top of the search results these days — but it’s still a good idea to get it done.

(I’d just have netnewswireapp.com redirect to netnewswire.com.)

**Comment by brentsimmons** [comment]
I have been unable to get netnewswireapp.com transferred to me. Right now there seems to be no website there at all.
