### ISSUE TITLE
Refresh feeds occurs on launch with "Manually only"

### ISSUE THREAD

**Issue by lapcat** [Ranchero-Software/NetNewsWire#894]
In NNW General Preferences, I have Refresh feeds set to "Manually only", but my feeds are still automatically refreshed on every launch.

**Comment by cdevroe** [comment]
@brentsimmons I was filling out a brand-new issue for this when Github suggested that there were similar requests in the past. I'd like to throw my vote behind @lapcat's suggestion as well.

I'd personally prefer the app _not_ refresh the feeds when I open the app. This way my unread count from my previous session, whether that be zero or 1,000, would still be there.

**Comment by osxrox** [comment]
This was a pet peeve of mine when I was testing for Black Pixel, namely, that Manual means what it says, not sometimes, always. So, yes, I'd like to see the app not refresh at launch.

**Comment by vincode-io** [comment]
We will add a hidden preference to suppress syncing on launch.

**Comment by vincode-io** [comment]
You will be able to enable this hidden preference by entering the following on the command line.

`defaults write com.ranchero.NetNewsWire-Evergreen DevroeSuppressSyncOnLaunch -bool true`

**Comment by cdevroe** [comment]
@vincode-io Very much looking forward to 6.1. Thank you!
