### ISSUE TITLE
Entry is marked as unread every time the feed is refreshed.

### ISSUE THREAD

**Issue by lapcat** [Ranchero-Software/NetNewsWire#895]
The URL of the feed is https://alerts.weather.gov/cap/wwaatmget.php?x=WIC025 from the National Weather Service. The updated date changes, but nothing else changes.

`<entry>
  	<id>https://alerts.weather.gov/cap/wwaatmget.php?x=WIC025&amp;y=0</id>
  	<updated>2019-08-28T02:29:55+00:00</updated>
  	<author>
  	<name>w-nws.webmaster@noaa.gov</name>
  	</author>
  	<title>There are no active watches, warnings or advisories</title>
  	<link href="https://alerts.weather.gov/cap/wwaatmget.php?x=WIC025&amp;y=0"/>
  	</entry>`

`<entry>
  	<id>https://alerts.weather.gov/cap/wwaatmget.php?x=WIC025&amp;y=0</id>
  	<updated>2019-08-28T02:32:32+00:00</updated>
  	<author>
  	<name>w-nws.webmaster@noaa.gov</name>
  	</author>
  	<title>There are no active watches, warnings or advisories</title>
  	<link href="https://alerts.weather.gov/cap/wwaatmget.php?x=WIC025&amp;y=0"/>
  	</entry>`

**Comment by brentsimmons** [comment]
If this is still happening — which kind of account are you using?

**Comment by lapcat** [comment]
This appears to be fixed now.

On My Mac account
