### ISSUE TITLE
In dark mode, selected sources are unreadable in fullscreen, slide-over side bar.

### ISSUE THREAD

**Issue by joaofrgomes** [Ranchero-Software/NetNewsWire#896]
Basically, when the app is in fullscreen mode, the sidebar is hidden and macOS is in Dark Mode, the currently selected source is unreadable because the highlight colour is converted into white instead of gray, and the text is not inverted, thus becoming a white-on-white unreadable rectangle.

![Captura de ecrã 2019-08-28, às 04 09 43](https://user-images.githubusercontent.com/29361091/63822955-fdd68200-c949-11e9-9973-0e49366fb89c.png)

The issue goes away when the app is in light mode, however.

![Captura de ecrã 2019-08-28, às 04 09 57](https://user-images.githubusercontent.com/29361091/63822959-029b3600-c94a-11e9-8f50-a7137d32409d.png)

Also, after tabbing between fields, it does indeed become readable, even in Dark Mode.

![Captura de ecrã 2019-08-28, às 04 08 38](https://user-images.githubusercontent.com/29361091/63822969-0d55cb00-c94a-11e9-888e-3ec52ccc60fc.png)

**Comment by joaofrgomes** [comment]
Oh, ok. To be fair, I had never used slide-over sidebars in fullscreen before; seeing how I'm used to Feedly, and having quite a lot of readable area as articles open on top of the article list, I decided to try this config and it works really nicely on a 13'' screen (on my 27'' iMac I probably won't bother at all).

By the way, maybe you could add a “Show (hide) sidebar button” and have the first flexible space snap the buttons to the edge of the sidebar, à la Mail.app? Just a thought, as it'd make it more similar to first-party apps (and NetNewsWire is already leagues ahead of the competition when it comes to that, but why not going the extra inch? ;) ).

By the way, I forgot to add that I'm running macOS Mojave 10.14.6, as I like to keep current.

**Comment by brentsimmons** [comment]
I don’t think we can snap those buttons the way Mail does — I haven’t seen anything in the toolbar API for that. I strongly suspect that Mail is using private API for this.

**Comment by joaofrgomes** [comment]
Ahh, yes, Apple does that a lot. Wow, if so, they've been holding on to it for very long. I remember that functionality from maybe as far back as Mail.app v.2, in Tiger (back when I used NetNewsWire v.3, heh :P )! In any case, the “show (hide)” button should be nice enough, as would be that highlight fix. ;)

I'm really enjoying the app, and I can't wait for Feedly sync and those iOS and iPadOS versions. Keep up the good work!

**Comment by michelf** [comment]
I think Mail is simply changing the max width of the first flexible space item dynamically as you move the splitter: you take the width of the sidebar, subtract some fixed amount for the toolbar margin, subtract the width of any item before the flexible space, and that gives you your max width.  I did something like this once, only it wasn't with a spacer.

**Comment by brentsimmons** [comment]
Right — but I don’t think we have any way to affect the width of a flexible space item in the toolbar.

**Comment by joaofrgomes** [comment]
So… sadly, a private API, right?

Interesting discussion. It's at times like these that I wish I was a developer (even with all the limitations and frustration that may come from them). ;)

**Comment by brentsimmons** [comment]
I tried a bunch of things. Hammering on it to re-draw, basically. I got nothing. I don’t know what this is going to take.

It’s definitely a macOS bug. Maybe it will get fixed in Catalina.

Removing it from the 5.0.1 milestone.

**Comment by joaofrgomes** [comment]
Oh well. Perhaps we could escalate this directly to Apple, then. I still have Feedback Assistant here in my system, even though I'm not running a public beta or anything right now, and it may work.

In any case, I've been itching to try Catalina and check how Music behaves with an external library, as that is the config I'm using right now on my main machine, so I might as well see if the bug still lingers, then, and flag it appropriately if it does. :)

**Comment by vincode-io** [comment]
I stumbled across this issue and am closing it since there is nothing we can do about this macOS bug.

**Comment by joaofrgomes** [comment]
Hi Maurice,

I had completely forgotten about this. The latest stable build, v. 5.1.1 (3012), no longer exhibits this behaviour under macOS Catalina 10.15.7 (19H2), so Apple likely fixed whatever was causing it on their end anyway.

In any case, thanks for the heads up.
