### ISSUE TITLE
Edited name not always appearing subs list

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#906]
![Screen Shot 2019-08-28 at 5 36 26 PM](https://user-images.githubusercontent.com/1297121/63901671-6a896500-c9ba-11e9-89d0-52aded44497a.png)

**Comment by brentsimmons** [comment]
Moving this to 5.x since I can’t reproduce it at the moment.

**Comment by vincode-io** [comment]
This one has me stumped.  I can't recreate it, but it clearly happened.  NetNewsWire shouldn't even be able to get into the state shown in the screenshot.  The sidebar gets updated as you type the new name.

Since this bug is over a year old, maybe we fixed this already?

**Comment by brentsimmons** [comment]
Closing. We can reopen it if it shows up again.
