### ISSUE TITLE
Feature request: Import starred items exported from Inoreader

### ISSUE THREAD

**Issue by greggvm** [Ranchero-Software/NetNewsWire#915]
Inoreader will export starred items as well as your subscriptions xml file. The starred items are json files. Is there any chance you would consider supporting the import of those as well as the subscriptions?

**Comment by brentsimmons** [comment]
We’re more likely to just support Inoreader syncing. :)

**Comment by greggvm** [comment]
That would work! :) Thank you!

**Comment by greggvm** [comment]
Happy Holidays!

Have been playing with the iOS beta for the last 25-30 minutes. Deleted the subscriptions that came with the install after reading through a number of them and getting a feel for the app. Then I imported the Inoreader xml subscriptions and have been going through those  and trying everything I can think to try thus far. Pretty damned good first beta thus far. Congrats to all on the hard work!

Best wishes,

Gregg Morris

**Comment by greggvm** [comment]
Really well put. Hope it gets lots of play!
