### ISSUE TITLE
VoiceOver announces opposite when marking as read/unread

### ISSUE THREAD

**Issue by PeterSaathoff-Harshfield** [Ranchero-Software/NetNewsWire#936]
Reproduction steps:
1. Enable VoiceOver (command + F5)
2. Ensure an article is selected
3. Press [command + shift + U] to mark the article as read or unread
4. Observe that VoiceOver announces the opposite

Video:
https://youtu.be/tRDel6_92Uw

Note: Mail.app has done this since 10.14, too, but that doesn't make it right.

**Comment by vincode-io** [comment]
I tested this and voice over is announcing the command that was executed as a result of pressing the keyboard shortcut.  These commands come from the menu bar and are read by VoiceOver.

Are we supposed to be announcing the final state of the article status update?  I tried to find some guidance on this in Apple's documentation, but wasn't able to find anything.

**Comment by brentsimmons** [comment]
Let’s punt on this too. I’ll ask a friend who used to work in Apple accessibility about it.

**Comment by vincode-io** [comment]
Hmmm...   I just watched your video again and it was doing the opposite of what my test was.  I'll keep looking into this.
