### ISSUE TITLE
iOS: "Vibrant" (NNW blue selection) cells in the iOS app have incorrect selection/highlight behavior

### ISSUE THREAD

**Issue by correia** [Ranchero-Software/NetNewsWire#948]
The selection/highlight behavior of the vibrant cells in the feed, timeline, and settings table views are subtly wrong and inconsistent across the three locations.

This is related to earlier work on bug #692.

**Comment by correia** [comment]
The Settings stuff is in flux and likely moving to SwiftUI, we let's leave that alone for now.

Discussed other work with @vincode-io, and I intend to take a branch to clean those lists up.

**Comment by correia** [comment]
Pull request #949 addresses this problem for the feed and timeline lists.

**Comment by brentsimmons** [comment]
I’ll leave it to @vincode-io to review and merge.

**Comment by vincode-io** [comment]
Oops. Looks like I forgot to close this one.
