### ISSUE TITLE
Slow rendering of feeds containing iframes

### ISSUE THREAD

**Issue by sashkab** [Ranchero-Software/NetNewsWire#962]
I've noticed, that it takes about 1 second to render an article from Slashdot. Is this because they using iframes?

Feed URL: http://rss.slashdot.org/Slashdot/slashdotMain?format=usm

Note, if you already read that article, it will render fast, only iframe will take loading, but when reading it for the first time, in pool of other unread articles it will be slower to render.

**Comment by brentsimmons** [comment]
Yes — that iframe takes extra time to load.

**Comment by brentsimmons** [comment]
We’re using Apple’s WebKit for that view. We don’t have a way of affecting how quickly it renders, unfortunately. (Well, we could just strip out the iframe, but that’s probably not what you want.)

**Comment by sashkab** [comment]
> Well, we could just strip out the iframe, but that’s probably not what you want

It's actually what I want, but was afraid to ask. 

But the problem is not that iframe renders _after_ the view loaded. For some reason on multiple different systems (iMac5k, iMac Pro, 2012 MacBook pro) these articles take about 1s to load the article view.

**Comment by brentsimmons** [comment]
This no longer appears to be an issue. If it still is an issue, we can re-open this ticket.
