### ISSUE TITLE
Copy an article via Edit > Copy

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#963]
Probably would put HTML on the clipboard.

**Comment by danielpunkass** [comment]
There may some contention with supporting Copy while overtly selecting content in an article.

There may be some merit in supporting dedicated "Copy Source" and "Copy Link" items.

**Comment by brentsimmons** [comment]
Hmmm. If the timeline has focus, though, then shouldn’t it copy the entire article?

**Comment by brentsimmons** [comment]
I think older NNWs had specific copy commands for things like URL and so on. Probably a good idea to look back at what those were.

**Comment by danielpunkass** [comment]
@brentsimmons Yeah, maybe Copy could be overloaded to the most obvious default behavior, while also offering specific menu items for the more precise commands.

**Comment by vincode-io** [comment]
Issues #1285, #381, and #1809 are all similar to this one.  We might be able to close them when this one is resolved.

**Comment by vincode-io** [comment]
Here's how I'm going to implement this. Someone stop me if it isn't cool!

The regular copy command (cmd-c) will copy the article permalink to the clipboard.  I think this makes the most sense because it is how drag-n-drop and the share menu work.

A new copy command Copy Article (shift-cmd-c) will copy the article body to the clipboard.

**Comment by vincode-io** [comment]
Nevermind.  We should be using `ArticlePasteboardWriter` and letting the target determine which UTI it wants.  So I'll just be implementing the regular copy command which will do both URL's and full HTML copies of the article.

**Comment by vincode-io** [comment]
Once I got in there and looked, it appears that this was already coded.  I just had to extend `Article` with `PasteboardWriterOwner` to get it to work with the `RSCore` stuff.
