### ISSUE TITLE
Have the Sidebar function like the Finder

### ISSUE THREAD

**Issue by ErniePC12** [Ranchero-Software/NetNewsWire#966]
I navigate around NNW 3 with my keyboard.  It is the same as if I am navigating around in the finder as a list. I am getting confused because NNW 5 doesn't seem to follow the same navigation motions as in the Finder.

I am expecting to be able to open and close the different folders by pressing the `left` and `right` keys.   When I am nested in a folder, I expect a `left keypress` to send me back to the top folder of the one I am in. `Up` and `down` work as normal. 

Hitting `tab` would bring me to right to the article list then to the article, `shift-tab` would bring the focus in the opposite direction.

> My computer with NNW 3 is out getting a swelling better replaced, so I can't describe how that works. at this time.

Is it hard to change the function of the feed list to act the same as it does in the Finder list view?

**Comment by brentsimmons** [comment]
NetNewsWire 5 works the same as 3 (and even 1 and 2) with this — we use arrow keys for moving between panes.

It‘s part of the app’s DNA by now!

For more about this, listen to this episode of The Talk Show: https://daringfireball.net/thetalkshow/2019/08/31/ep-262
