### ISSUE TITLE
Mark as read and mark all as read icons are the same

### ISSUE THREAD

**Issue by leonp** [Ranchero-Software/NetNewsWire#983]
Means relying on hover to make sure you click the right icon.

Version 5.0 (2609)

<img width="903" alt="netnewswire" src="https://user-images.githubusercontent.com/2016649/64376185-95f5fa80-d01f-11e9-90da-45a9ddaa5c48.png">

**Comment by brentsimmons** [comment]
They’re different — but I can see how they might not be different enough.

One work-around would be to move mark-all-as-read so that it’s over the timeline, since that’s what it applies to, and leave mark-as-read over the article, since that’s what that one applies to.

**Comment by leonp** [comment]
Thanks, makes sense to me as it’s hard to think of how to differentiate the icons. If you were looking at that maybe several ticks for mark all?

Oh, and thanks for NetNewsWire: it’s great!

**Comment by vincode-io** [comment]
We use very different versions of these icons in the 6.0 NNW Big Sur toolbar, so I'm going to close this issue.
