### ISSUE TITLE
MAS build

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#992]
Mostly configuration, I think? There shouldn’t be much in the way of sandboxing to do. I think. I hope.

**Comment by brentsimmons** [comment]
Trying to assign to @danielpunkass but for some reason he’s not on the list. Grrrr.

**Comment by brentsimmons** [comment]
Assignment accomplished!

**Comment by danielpunkass** [comment]
Off the top of my head as a free app, I think the main distinction between NNW MAS and NNW Direct will be that Sparkle should be disabled/removed from the app when building for MAS. I can figureo out how to handle this, probably in a similar manner to how I handle it for my own apps.

**Comment by brentsimmons** [comment]
We should probably have different bundle IDs, too. I don’t plan to support going back and forth between direct and MAS — they should be considered distinct apps.

**Comment by danielpunkass** [comment]
That sounds fine. With the caveat that users who want to switch will just have to figure out how to do the export/import of feeds.
