### ISSUE TITLE
Activity status when refreshing feeds: what is it counting?

### ISSUE THREAD

**Issue by paulrobertlloyd** [Ranchero-Software/NetNewsWire#994]
I’m currently syncing feeds using Feedbin. When I choose to refresh, the activity status at the bottom of the sidebar says ‘[n] of 6’ as the progress bar increments. This is really nit-picky, but it’s been bugging me for ages… where does the ’6’ come from!? 🤪

I am using 9 tags in Feedbin (shown as folders in NNW), and sync only 1 set of feeds. Are there six steps undertaken during a refresh? It’s unclear.

**Comment by brentsimmons** [comment]
Yes, it’s counting steps. Do you have an idea for how that could be communicated more clearly?

**Comment by paulrobertlloyd** [comment]
I wonder if it’s a needless detail? Would ‘Updating feeds…’ suffice (much like is the case in Mail.app)? Looking at Mail.app, I wonder… is the progress bar needed? From my own usage, updates are super quick, but those with more feeds/slower connections may appreciate this feedback mechanism.

Alternatively, although a bit more involved, my instinct was to look for an activity window, which might reveal the meaning behind the number. But I suspect with updates being so quick, this could be difficult to follow.

**Comment by vincode-io** [comment]
This has been answered, so I'm closing this issue.  Thank you everyone for the feedback.
